//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPSWebEntry.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class TempCache : global::System.Configuration.ApplicationSettingsBase {
        
        private static TempCache defaultInstance = ((TempCache)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TempCache())));
        
        public static TempCache Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SerializedPayment {
            get {
                return ((string)(this["SerializedPayment"]));
            }
            set {
                this["SerializedPayment"] = value;
            }
        }
    }
}
