CREATE TABLE [dbo].[AP03_Master_Application] (
    [AF_APL_ID]          CHAR (9)        NOT NULL,
    [BF_SSN]             CHAR (9)        NULL,
    [AN_SEQ]             INT             NULL,
    [LF_STU_SSN]         CHAR (9)        NULL,
    [IC_LON_PGM]         VARCHAR (6)     NULL,
    [AD_CRT_APL]         DATETIME        NULL,
    [AC_STA_ORG_PRC]     VARCHAR (2)     NULL,
    [AD_STA_ORG_PRC]     DATETIME        NULL,
    [AC_APL_SCR_STA]     CHAR (1)        NULL,
    [AC_APL_PRC_TYP]     CHAR (1)        NULL,
    [AI_BR_DLQ_FED_DET]  CHAR (1)        NULL,
    [AI_BR_DET]          BIT             NULL,
    [AC_BR_INT_OPT]      BIT             NULL,
    [AC_BR_RPD_OPT]      CHAR (1)        NULL,
    [AI_BR_NED_ORG_FEE]  BIT             NULL,
    [AI_BR_ATH_DSB_EFT]  BIT             NULL,
    [AI_EDS_XST_ON_APL]  BIT             NULL,
    [AI_RFR_XST_ON_APL]  BIT             NULL,
    [AD_STU_LON_TRM_BEG] DATETIME        NULL,
    [AD_STU_LON_TRM_END] DATETIME        NULL,
    [AD_STU_GRD_XPC]     DATETIME        NULL,
    [AI_STU_FGN_CNY_STY] CHAR (1)        NULL,
    [AC_STU_MAJ_STY]     VARCHAR (3)     NULL,
    [AX_STU_CNL_MAJ_STY] VARCHAR (15)    NULL,
    [AC_STU_SCL_ENR_STA] CHAR (1)        NULL,
    [AI_STU_DFR_REQ]     BIT             NULL,
    [AA_STU_REQ]         INT             NULL,
    [AF_DOE_SCL]         VARCHAR (8)     NULL,
    [AF_CNL_NON_EDU_BRH] VARCHAR (4)     NULL,
    [AD_SCL_LON_TRM_BEG] DATETIME        NULL,
    [AD_SCL_LON_TRM_END] DATETIME        NULL,
    [AD_SCL_ACA_TRM_BEG] DATETIME        NULL,
    [AD_SCL_ACA_TRM_END] DATETIME        NULL,
    [AD_SCL_GRD_XPC]     DATETIME        NULL,
    [AC_SCL_STA_STU_ENR] CHAR (1)        NULL,
    [AC_SCL_ACA_GDE_LEV] VARCHAR (2)     NULL,
    [AC_SCL_ACA_PGS]     CHAR (1)        NULL,
    [AA_SCL_EDU_CST]     INT             NULL,
    [AA_SCL_EDU_AID_TOT] INT             NULL,
    [AA_SCL_EFC]         INT             NULL,
    [AA_SCL_REQ]         INT             NULL,
    [AI_SCL_CNF_MPN_OVR] CHAR (1)        NULL,
    [AI_SCL_STU_PAS_DU]  BIT             NULL,
    [AN_SCL_AMT_CLC_MLT] NUMERIC (7, 4)  NULL,
    [AF_DOE_LDR]         VARCHAR (8)     NULL,
    [AF_LDR_NON_EDU_BRH] VARCHAR (4)     NULL,
    [AF_LDR_APL_FIL]     VARCHAR (10)    NULL,
    [AA_LDR_APV]         INT             NULL,
    [AC_LDR_PGM_YR]      CHAR (1)        NULL,
    [AI_LDR_CNF_MPN_OVR] CHAR (1)        NULL,
    [AF_LDR_BND_ISS]     VARCHAR (8)     NULL,
    [AF_LDR_FEE_TIR]     VARCHAR (3)     NULL,
    [AI_LDR_NO_FEE_OVR]  CHAR (1)        NULL,
    [AF_LDR_ITR_TIR]     VARCHAR (3)     NULL,
    [AI_LDR_NO_ITR_OVR]  CHAR (1)        NULL,
    [AD_LDR_APL_REJ]     DATETIME        NULL,
    [AF_LDR_ORG]         VARCHAR (8)     NULL,
    [AI_LDR_MAT_SLL_LON] CHAR (1)        NULL,
    [AF_LDR_LST_RST]     VARCHAR (8)     NULL,
    [IF_GTR]             VARCHAR (6)     NULL,
    [AF_GTR_RFR]         VARCHAR (10)    NULL,
    [AA_GTR_LON]         NUMERIC (9, 2)  NULL,
    [AD_GTR_LON_REQ]     DATETIME        NULL,
    [AD_GTR_ORG]         DATETIME        NULL,
    [AR_GTR_INT]         NUMERIC (6, 3)  NULL,
    [AC_GTR_ITR_TYP]     VARCHAR (2)     NULL,
    [AR_GTR_FEE]         NUMERIC (6, 3)  NULL,
    [AI_GTR_TL4_PIO_787] CHAR (1)        NULL,
    [AI_GTR_DSB_LTE_AZ]  CHAR (1)        NULL,
    [AD_GTR_DSB_MAX_LTE] DATETIME        NULL,
    [AA_GTR_RSC]         INT             NULL,
    [AD_GTR_RSC]         DATETIME        NULL,
    [AC_GTR_DFR_REQ]     CHAR (1)        NULL,
    [AC_GTR_INT_BIL_OPT] VARCHAR (2)     NULL,
    [AC_GTR_REA_RDC]     VARCHAR (2)     NULL,
    [AA_GTR_TOT_SFD_BAL] NUMERIC (9, 2)  NULL,
    [AA_GTR_TOT_PLS_BAL] NUMERIC (9, 2)  NULL,
    [AI_GTR_RSC]         CHAR (1)        NULL,
    [AC_SRC_APL]         VARCHAR (3)     NULL,
    [AC_VRS_ALT_APL]     VARCHAR (4)     NULL,
    [AC_SER_RUE]         VARCHAR (2)     NULL,
    [AD_PNT_SIG]         DATETIME        NULL,
    [AI_PNT_VER]         BIT             NULL,
    [AF_PNT_VER_BY]      VARCHAR (8)     NULL,
    [AD_PNT_VER]         DATETIME        NULL,
    [AI_ESC]             BIT             NULL,
    [AC_APL_HLD]         VARCHAR (2)     NULL,
    [AD_APL_HLD]         DATETIME        NULL,
    [AA_STF_APV]         INT             NULL,
    [AA_ESM_RPD]         NUMERIC (7, 2)  NULL,
    [AD_ESM_RPD_SR]      DATETIME        NULL,
    [AD_ESM_POF]         DATETIME        NULL,
    [AC_SYS_CLC_DFR]     CHAR (1)        NULL,
    [AA_ANL_INC]         NUMERIC (9, 2)  NULL,
    [AA_MTH_CLC_RPD]     NUMERIC (9, 2)  NULL,
    [AA_MTH_CMB_DET]     NUMERIC (9, 2)  NULL,
    [AA_MTH_CMB_INC]     NUMERIC (9, 2)  NULL,
    [AR_CMB_DET_INC_RTO] NUMERIC (6, 3)  NULL,
    [AA_TOT_SFD_BAL]     NUMERIC (9, 2)  NULL,
    [AA_TOT_PLS_BAL]     NUMERIC (9, 2)  NULL,
    [AA_TOT_SLS_BAL]     NUMERIC (9, 2)  NULL,
    [AA_TOT_PRK_BAL]     NUMERIC (9, 2)  NULL,
    [AA_TOT_HEA_BAL]     NUMERIC (9, 2)  NULL,
    [AA_OTH_EDU_LON_BAL] INT             NULL,
    [AA_TOT_STU_LN_BAL]  INT             NULL,
    [AA_ORG_FEE_PD]      INT             NULL,
    [AA_GTR_FEE_PD]      INT             NULL,
    [AC_REA_CPY_AP03]    CHAR (1)        NULL,
    [AF_APL_ID_CPY]      VARCHAR (9)     NULL,
    [AI_EXT_CVN]         BIT             NULL,
    [AF_APL_ID_CPY_ORG]  VARCHAR (9)     NULL,
    [AN_SEQ_CVN]         INT             NULL,
    [AN_SIG_ON_PNT]      SMALLINT        NULL,
    [AF_RGL_CAT_LP06]    VARCHAR (7)     NULL,
    [AF_RGL_CAT_LP09]    VARCHAR (7)     NULL,
    [AF_RGL_CAT_LP10]    VARCHAR (7)     NULL,
    [AF_RGL_CAT_LP12]    VARCHAR (7)     NULL,
    [AF_RGL_CAT_LP20]    VARCHAR (7)     NULL,
    [AD_LON_1_DSB]       DATETIME        NULL,
    [AC_ORG_DPT]         VARCHAR (2)     NULL,
    [AR_LP_TB_ITR_MGN]   NUMERIC (6, 3)  NULL,
    [AD_AMR_BEG]         DATETIME        NULL,
    [AR_SCL_SUB]         NUMERIC (7, 3)  NULL,
    [AC_PNT_DEL]         CHAR (1)        NULL,
    [AD_PNT_SNT]         DATETIME        NULL,
    [AC_SCL_NTF_STA_CHG] CHAR (1)        NULL,
    [AI_DSB_REJ_ACK_FIL] BIT             NULL,
    [AC_PIO_ORG_STA]     CHAR (1)        NULL,
    [AC_MN_TYP]          CHAR (1)        NULL,
    [AC_MN_SRL_LON]      CHAR (1)        NULL,
    [AI_MN_PSD_BS]       CHAR (1)        NULL,
    [AC_MN_CNF]          CHAR (1)        NULL,
    [AC_MN_BR_CNF]       CHAR (1)        NULL,
    [AD_MN_EXP]          DATETIME        NULL,
    [AI_MN_NOG]          CHAR (1)        NULL,
    [AI_MN_LN_OF_CRD]    CHAR (1)        NULL,
    [AC_MN_SRL_LON_ORG]  CHAR (1)        NULL,
    [AD_MN_BR_CNF_SNT]   DATETIME        NULL,
    [AD_MN_BR_CNF_RCV]   DATETIME        NULL,
    [AA_MN_BR_CNF]       INT             NULL,
    [AC_MN_REV_REA]      VARCHAR (2)     NULL,
    [AF_MN_MST_NTE]      VARCHAR (11)    NULL,
    [AN_MN_MST_NTE_SEQ]  INT             NULL,
    [AI_MN_ORG_RGT_SLD]  BIT             NULL,
    [AF_MN_RGT_SLD_TO]   VARCHAR (8)     NULL,
    [AF_CNL]             VARCHAR (17)    NULL,
    [AF_CNL_SFX]         VARCHAR (2)     NULL,
    [AX_CNL_GTR_USE]     VARCHAR (23)    NULL,
    [AC_CNL_GTR_STA]     VARCHAR (2)     NULL,
    [AD_CNL_GTR_STA]     DATETIME        NULL,
    [AF_CNL_GTR_TRT_DTS] DATETIME        NULL,
    [AX_CNL_LDR_USE]     VARCHAR (23)    NULL,
    [AC_CNL_LDR_SER_STA] VARCHAR (2)     NULL,
    [AD_CNL_LDR_SER_STA] DATETIME        NULL,
    [AF_CNL_LDR_TRT_DTS] DATETIME        NULL,
    [AX_CNL_SCL_USE]     VARCHAR (23)    NULL,
    [AA_CNL_ACL_RTD]     NUMERIC (9, 2)  NULL,
    [AA_CNL_WDR_GR_RFD]  NUMERIC (9, 2)  NULL,
    [AA_CNL_AVL_RNS]     NUMERIC (9, 2)  NULL,
    [AC_CNL_MTD_FUD_RTD] VARCHAR (2)     NULL,
    [AI_CNL_DSB_CNS]     CHAR (1)        NULL,
    [AC_CNL_PRC_TYP_APL] VARCHAR (2)     NULL,
    [AC_CNL_RPT_STA]     VARCHAR (2)     NULL,
    [AC_CNL_SRV_TYP]     VARCHAR (2)     NULL,
    [AC_CNL_ITL_RSP]     CHAR (1)        NULL,
    [AC_FLW_TYP]         VARCHAR (2)     NULL,
    [AC_FLW_STA]         CHAR (1)        NULL,
    [AD_FLW_STA]         DATETIME        NULL,
    [AD_FLW_APV]         DATETIME        NULL,
    [AF_LST_USR_AP03]    VARCHAR (8)     NULL,
    [AF_LST_DTS_AP03]    DATETIME        NULL,
    [AD_LON_1_PAY_DU]    DATETIME        NULL,
    [AI_STA_ORG_PRC_CHG] BIT             NULL,
    [AI_PNT_PRT]         BIT             NULL,
    [AD_TO_SER_CMP]      DATETIME        NULL,
    [AI_LDR_RGT_SLD_CHG] CHAR (1)        NULL,
    [AC_MN_MST_NTE_ASG]  CHAR (1)        NULL,
    [AC_CRD_WOR_RED]     CHAR (1)        NULL,
    [AI_FEE_MNL_CLC]     CHAR (1)        NULL,
    [AC_BR_ST_DSB_1]     VARCHAR (2)     NULL,
    [AC_SCL_ST_DSB_1]    VARCHAR (2)     NULL,
    [AC_FIL_TYP_REQ]     VARCHAR (2)     NULL,
    [AC_FIL_RCP]         CHAR (1)        NULL,
    [AC_PNT_YR]          VARCHAR (7)     NULL,
    [AC_STP_PUR]         CHAR (1)        NULL,
    [AI_PIO_APL_LDR]     CHAR (1)        NULL,
    [AI_SCL_ENT_CCL]     CHAR (1)        NULL,
    [AI_DEG_SKG]         CHAR (1)        NULL,
    [AA_BS_POI]          NUMERIC (7, 4)  NULL,
    [AF_CUR_POR]         VARCHAR (20)    NULL,
    [AF_DTS_APL_ELG_CER] DATETIME        NULL,
    [AD_DTR_APL_CER_CMP] DATETIME        NULL,
    [AF_USR_CER_CLG]     VARCHAR (8)     NULL,
    [AC_EDU_LEV_TYP]     CHAR (1)        NULL,
    [AA_LST_CTR_OFR]     NUMERIC (13, 2) NULL,
    [AD_LST_CTR_OFR]     DATETIME        NULL,
    [AC_BR_CTR_OFR_RSP]  CHAR (1)        NULL,
    [AN_BR_PIO_ALT_DNL]  SMALLINT        NULL,
    [AF_ALT_LON_APL]     VARCHAR (9)     NULL,
    [AC_ALT_APL_ELG_STA] VARCHAR (2)     NULL,
    [AC_ALT_APL_ACT_STA] CHAR (1)        NULL,
    [AF_APL_SLC_DIS]     VARCHAR (11)    NULL,
    [AI_TLX_APL]         CHAR (1)        NULL,
    [AF_PNT_VRS]         VARCHAR (7)     NULL,
    [AD_APL_EXP]         DATETIME        NULL,
    [AC_APL_EXP_EVT]     VARCHAR (3)     NULL,
    [AC_APL_RVW]         CHAR (1)        NULL,
    [AC_CNL_TRN_REA]     CHAR (1)        NULL,
    [AC_ALT_APL_FLW]     VARCHAR (2)     NULL,
    CONSTRAINT [PK_AP03_Master_Application] PRIMARY KEY CLUSTERED ([AF_APL_ID] ASC)
);

