*-------------------------------------------------------------*
|UTLWU03 SKIP CONTACT OR ATTEMPT TELEPHONE ACTIVITY QC REPORT |
*-------------------------------------------------------------*;
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/ULWU03.LWU03R2";
FILENAME REPORTZ "&RPTLIB/ULWU03.LWU03RZ";

DATA _NULL_;
     CALL SYMPUT('PRVDY',"'"||PUT(INTNX('DAY',TODAY(),-1,'BEGINNING'), MMDDYYD10.)||"'");
	IF WEEKDAY(TODAY()) = 2 THEN DO;
		CALL SYMPUT('PRVDY',"'"||PUT(INTNX('DAY',TODAY(),-3,'BEGINNING'), MMDDYYD10.)||"'");
	END;
     CALL SYMPUT('PRVDY',"'"||PUT(INTNX('DAY',TODAY(),-1,'BEGINNING'), MMDDYYD10.)||"'");
     CALL SYMPUT('RUNDATE',PUT(INTNX('DAY',TODAY(),0,'beginning'), MMDDYY10.));
	 CALL SYMPUT('RUNTIME',PUT(TIME(), TIME.));
RUN;

%SYSLPUT PRVDY = &PRVDY;

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;

%MACRO SQLCHECK (SQLRPT= );
%IF &SQLXRC NE 0 %THEN %DO;
	DATA _NULL_;
    FILE REPORTZ NOTITLES;
    PUT @01 " ********************************************************************* "
      / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
      / @01 " ****  THE SAS LOG IN &SQLRPT SHOULD BE REVIEWED.          **** "       
      / @01 " ********************************************************************* "
      / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
      / @01 " ****  &SQLXMSG   **** "
      / @01 " ********************************************************************* ";
	RUN;
%END;
%MEND;

PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE SCATAR AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT A.BF_LST_USR_AY01	AS USER_ID
	,A.PF_ACT				AS ACTION_CODE
	,RTRIM(B.PX_ACT_DSC)	AS ACTION_CODE_DESCRIPTION
	,A.BC_ATY_TYP			AS ACTIVITY_TYPE
	,A.BC_ATY_CNC_TYP		AS CONTACT_TYPE 
	,CASE 
		WHEN SUBSTR(A.DF_PRS_ID,1,2) = 'RF' THEN A.DF_PRS_ID
		ELSE C.DF_SPE_ACC_ID		
	 END AS ACCT
	,A.BD_ATY_PRF			AS DATE
	,A.BX_CMT				AS COMMENTS
FROM OLWHRM1.AY01_BR_ATY A
INNER JOIN OLWHRM1.AC01_ACT B
	ON A.PF_ACT = B.PF_ACT
LEFT OUTER JOIN OLWHRM1.PD01_PDM_INF C
	ON A.DF_PRS_ID = C.DF_PRS_ID
WHERE A.BD_ATY_PRF = &PRVDY
	AND A.PF_ACT IN ('KABAB','KSBAB','KUBAB','KAEAE','KSEAE',
				'KUEAE','KABA2','KSBA1','KUBA3','KUBA4',
				'KAEA2','KSEA1','KUEA3','KUEA4','KAEAB',
				'KSEAB','KUEAB')
	AND A.BF_LST_USR_AY01 NOT IN ('UT00204','UT00221','UT00205','UT00240'
				,'UT00314','UT00553','UT00554','UT00555','UT00564')
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>>  ;  * INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK (SQLRPT=ULWU03.LWU03RZ);*/
/*QUIT;*/
ENDRSUBMIT;
DATA SCATAR;
	SET WORKLOCL.SCATAR;
RUN;
PROC SORT DATA=SCATAR;
	BY USER_ID ACTION_CODE ACCT;
RUN;
DATA _NULL_;
SET SCATAR ;
LENGTH DESCRIPTION $2000.;
USER = USER_ID;
ACT_DT = DATE;
DESCRIPTION = CATX(',',
	'ACCOUNT NUMBER = '||ACCT,
	'ACTION CODE = '||ACTION_CODE,
	'ACTION CODE DESCRIPTION = '||ACTION_CODE_DESCRIPTION,
	'ACTIVITY TYPE = '||ACTIVITY_TYPE,
	'CONTACT TYPE = '||CONTACT_TYPE,
	'COMMENTS = '||COMMENTS
);
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
FORMAT USER $10. ;
FORMAT ACT_DT MMDDYY10. ;
FORMAT DESCRIPTION $2000. ;
IF _N_ = 1 THEN DO;
	PUT "USER,ACT_DT,DESCRIPTION";
END;
DO;
   PUT USER $ @;
   PUT ACT_DT @;
   PUT DESCRIPTION $ ;
END;
RUN;
