CREATE PROCEDURE [dbo].[LT_TS06BNEGAM_FormFields]
	@AccountNumber CHAR(10),
	@IsCoborrower BIT = 0
AS
BEGIN

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE	@LetterId VARCHAR(10) = 'TS06BNEGAM'
DECLARE @PF_REQ_ACT VARCHAR(5) = (SELECT AC11.PF_REQ_ACT FROM AC11_ACT_REQ_LTR AC11 WHERE PF_LTR = @LetterId)

IF @IsCoborrower = 0
	BEGIN
		SELECT
			'$' + CAST(SUM(FS12.LA_PRJ_NEG_AMR_INT) AS VARCHAR) AS [InterestAmount]
		FROM
			PD10_PRS_NME PD10
			INNER JOIN 
			(
				SELECT DISTINCT
					FS12I.BF_SSN,
					MAX(FS12I.LD_CRT_NEG_AMR_LTR) AS LD_CRT_NEG_AMR_LTR
				FROM
					FS12_ICR_NEG_AMR FS12I
					INNER JOIN
					(
						SELECT
							LN85.BF_SSN,
							LN85.LN_SEQ
						FROM
							LN85_LON_ATY LN85
							INNER JOIN --GETS THE MOST RECENT ARC LEFT ON THE BORROWERS ACCOUNT TO GET THE LOAN SEQ'S THE LETTER APPLIES TO
							(
								SELECT
									AY10.BF_SSN,
									MAX(AY10.LN_ATY_SEQ) AS LN_ATY_SEQ,
									MAX(AY10.LD_ATY_REQ_RCV) AS LD_ATY_REQ_RCV
								FROM 
									AY10_BR_LON_ATY AY10
									INNER JOIN PD10_PRS_NME PD10
										ON PD10.DF_PRS_ID = AY10.BF_SSN
								WHERE
									AY10.PF_REQ_ACT = @PF_REQ_ACT
									AND PD10.DF_SPE_ACC_ID = @AccountNumber
								GROUP BY
									AY10.BF_SSN
							)AY10
								ON AY10.BF_SSN = LN85.BF_SSN
								AND AY10.LN_ATY_SEQ = LN85.LN_ATY_SEQ
					)LN85
						ON LN85.BF_SSN = FS12I.BF_SSN
						AND LN85.LN_SEQ = FS12I.LN_SEQ
				GROUP BY
					FS12I.BF_SSN
			) FS12Max
				ON FS12Max.BF_SSN = PD10.DF_PRS_ID
			INNER JOIN FS12_ICR_NEG_AMR FS12
				ON FS12.BF_SSN = FS12Max.BF_SSN
				AND FS12.LD_CRT_NEG_AMR_LTR = FS12Max.LD_CRT_NEG_AMR_LTR
		WHERE 
			PD10.DF_SPE_ACC_ID = @AccountNumber
		GROUP BY
			FS12.BF_SSN
	END
ELSE
	BEGIN
		SELECT
			'$' + CAST(SUM(FS12.LA_PRJ_NEG_AMR_INT) AS VARCHAR) AS [InterestAmount]
		FROM
			PD10_PRS_NME PD10
			INNER JOIN LN20_EDS LN20
				ON LN20.LF_EDS = PD10.DF_PRS_ID
				AND LN20.LC_EDS_TYP = 'M'
				AND LN20.LC_STA_LON20 = 'A'
			INNER JOIN 
			(
				SELECT DISTINCT
					FS12I.BF_SSN,
					FS12I.LN_SEQ,
					MAX(FS12I.LD_CRT_NEG_AMR_LTR) OVER(PARTITION BY FS12I.BF_SSN) AS LD_CRT_NEG_AMR_LTR
				FROM
					FS12_ICR_NEG_AMR FS12I
					INNER JOIN
					(
						SELECT
							LN85.BF_SSN,
							LN85.LN_SEQ
						FROM
							LN85_LON_ATY LN85
							INNER JOIN --GETS THE MOST RECENT ARC LEFT ON THE BORROWERS ACCOUNT TO GET THE LOAN SEQ'S THE LETTER APPLIES TO
							(
								SELECT
									AY10.BF_SSN,
									MAX(AY10.LN_ATY_SEQ) AS LN_ATY_SEQ,
									MAX(AY10.LD_ATY_REQ_RCV) AS LD_ATY_REQ_RCV
								FROM 
									AY10_BR_LON_ATY AY10
									INNER JOIN LN20_EDS LN20
										ON LN20.BF_SSN = AY10.BF_SSN
										AND LN20.LC_EDS_TYP = 'M'
										AND LN20.LC_STA_LON20 = 'A'
									INNER JOIN PD10_PRS_NME PD10
										ON PD10.DF_PRS_ID = LN20.LF_EDS
								WHERE
									AY10.PF_REQ_ACT = @PF_REQ_ACT
									AND PD10.DF_SPE_ACC_ID = @AccountNumber
								GROUP BY
									AY10.BF_SSN
							)AY10
								ON AY10.BF_SSN = LN85.BF_SSN
								AND AY10.LN_ATY_SEQ = LN85.LN_ATY_SEQ
					)LN85
						ON LN85.BF_SSN = FS12I.BF_SSN
						AND LN85.LN_SEQ = FS12I.LN_SEQ
			) FS12Max
				ON FS12Max.BF_SSN = LN20.BF_SSN
				AND FS12Max.LN_SEQ = LN20.LN_SEQ
			INNER JOIN FS12_ICR_NEG_AMR FS12
				ON FS12.BF_SSN = FS12Max.BF_SSN
				AND FS12.LN_SEQ = FS12Max.LN_SEQ
				AND FS12.LD_CRT_NEG_AMR_LTR = FS12Max.LD_CRT_NEG_AMR_LTR
		WHERE 
			PD10.DF_SPE_ACC_ID = @AccountNumber
		GROUP BY
			FS12.BF_SSN
	END
END