CREATE PROCEDURE [dbo].[LT_US06BCTDRN_FormFields]
	@BF_SSN VARCHAR(9),
	@IsCoborrower BIT = 0,
	@RN_ATY_SEQ_PRC INT
AS
BEGIN

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @Today DATE = GETDATE()
DECLARE	@LetterId VARCHAR(10) = 'US06BCTDRN'
DECLARE @PF_REQ_ACT VARCHAR(5) = (SELECT AC11.PF_REQ_ACT FROM AC11_ACT_REQ_LTR AC11 WHERE PF_LTR = @LetterId)


IF @IsCoborrower = 0
	BEGIN
		SELECT
			CONVERT(VARCHAR(10), CAST(MAX(D.EndDate) AS DATE), 101) AS EndDate,
			CONVERT(VARCHAR(10), CAST(DATEADD(M, 6, MAX(D.EndDate)) AS DATE), 101) AS DeadlineDate
		FROM
		(
			SELECT
				MAX(LN50.LD_DFR_END) AS EndDate
			FROM
				LN10_LON LN10
				INNER JOIN LN50_BR_DFR_APV LN50
					ON LN10.BF_SSN = LN50.BF_SSN
					AND LN10.LN_SEQ = LN50.LN_SEQ
				INNER JOIN DF10_BR_DFR_REQ DF10
					ON LN50.BF_SSN = DF10.BF_SSN
					AND LN50.LF_DFR_CTL_NUM = DF10.LF_DFR_CTL_NUM
				INNER JOIN
				(
					SELECT
						LN85.BF_SSN,
						LN85.LN_SEQ
					FROM
						LN85_LON_ATY LN85
						INNER JOIN AY10_BR_LON_ATY AY10
							ON AY10.BF_SSN = LN85.BF_SSN
							AND AY10.LN_ATY_SEQ = LN85.LN_ATY_SEQ
					WHERE   
						AY10.PF_REQ_ACT = @PF_REQ_ACT
						AND AY10.BF_SSN = @BF_SSN
						AND AY10.LN_ATY_SEQ = @RN_ATY_SEQ_PRC
						--Active flag ignored, as LT20 provides the exact record that is tied to this request
				)LN85
					ON LN85.BF_SSN = LN10.BF_SSN
					AND LN85.LN_SEQ = LN10.LN_SEQ 
			WHERE
				LN10.BF_SSN = @BF_SSN
				AND	DF10.LC_DFR_TYP = '37'
				AND DF10.LC_DFR_SUB_TYP IN ('CT','CP')
				AND DF10.LC_DFR_STA = 'A'
				AND DF10.LC_STA_DFR10 = 'A'
				AND LN50.LC_DFR_RSP != '003'
				AND LN50.LC_STA_LON50 = 'A'

			UNION
		
			SELECT
				MAX(LN60.LD_FOR_END) AS EndDate
			FROM
				LN10_LON LN10
				INNER JOIN LN60_BR_FOR_APV LN60
					ON LN10.BF_SSN = LN60.BF_SSN
					AND LN10.LN_SEQ = LN60.LN_SEQ
				INNER JOIN FB10_BR_FOR_REQ FB10
					ON LN60.BF_SSN = FB10.BF_SSN
					AND LN60.LF_FOR_CTL_NUM = FB10.LF_FOR_CTL_NUM
				INNER JOIN
				(
					SELECT
						LN85.BF_SSN,
						LN85.LN_SEQ
					FROM
						LN85_LON_ATY LN85
						INNER JOIN AY10_BR_LON_ATY AY10
							ON AY10.BF_SSN = LN85.BF_SSN
							AND AY10.LN_ATY_SEQ = LN85.LN_ATY_SEQ
					WHERE   
						AY10.PF_REQ_ACT = @PF_REQ_ACT
						AND AY10.BF_SSN = @BF_SSN
						AND AY10.LN_ATY_SEQ = @RN_ATY_SEQ_PRC
						--Active flag ignored, as LT20 provides the exact record that is tied to this request
				)LN85
					ON LN85.BF_SSN = LN10.BF_SSN
					AND LN85.LN_SEQ = LN10.LN_SEQ 
			WHERE
				LN10.BF_SSN = @BF_SSN
				AND	FB10.LC_FOR_TYP = '34'
				AND FB10.LC_FOR_STA = 'A'
				AND FB10.LC_STA_FOR10 = 'A'
				AND LN60.LC_FOR_RSP != '003'
				AND LN60.LC_STA_LON60 = 'A'
		) D
	END
ELSE
	BEGIN
		SELECT
			CONVERT(VARCHAR(10), CAST(MAX(D.EndDate) AS DATE), 101) AS EndDate,
			CONVERT(VARCHAR(10), CAST(DATEADD(M, 6, MAX(D.EndDate)) AS DATE), 101) AS DeadlineDate
		FROM
		(
			SELECT
				MAX(LN50.LD_DFR_END) AS EndDate
			FROM
				PD10_PRS_NME PD10
				INNER JOIN LN20_EDS LN20
					ON LN20.LF_EDS = PD10.DF_PRS_ID
					AND LN20.LC_EDS_TYP = 'M'
					AND LN20.LC_STA_LON20 = 'A'
				INNER JOIN LN10_LON LN10
					ON LN10.BF_SSN = LN20.BF_SSN
					AND LN10.LN_SEQ = LN20.LN_SEQ
				INNER JOIN LN50_BR_DFR_APV LN50
					ON LN20.BF_SSN = LN50.BF_SSN
					AND LN20.LN_SEQ = LN50.LN_SEQ
				INNER JOIN DF10_BR_DFR_REQ DF10
					ON LN50.BF_SSN = DF10.BF_SSN
					AND LN50.LF_DFR_CTL_NUM = DF10.LF_DFR_CTL_NUM
				INNER JOIN
				(
					SELECT
						LN85.BF_SSN,
						LN85.LN_SEQ
					FROM
						LN85_LON_ATY LN85
						INNER JOIN AY10_BR_LON_ATY AY10
							ON AY10.BF_SSN = LN85.BF_SSN
							AND AY10.LN_ATY_SEQ = LN85.LN_ATY_SEQ
						INNER JOIN LN20_EDS LN20
							ON LN20.BF_SSN = LN85.BF_SSN
							AND LN20.LN_SEQ = LN85.LN_SEQ
							AND LN20.LC_STA_LON20 = 'A'
							AND LN20.LC_EDS_TYP = 'M'
					WHERE   
						AY10.PF_REQ_ACT = @PF_REQ_ACT
						AND LN20.LF_EDS = @BF_SSN
						AND AY10.LN_ATY_SEQ = @RN_ATY_SEQ_PRC
						--Active flag ignored, as LT20 provides the exact record that is tied to this request
				)LN85
					ON LN85.BF_SSN = LN10.BF_SSN
					AND LN85.LN_SEQ = LN10.LN_SEQ 
			WHERE
				PD10.DF_PRS_ID = @BF_SSN
				AND	DF10.LC_DFR_TYP = '37'
				AND DF10.LC_DFR_SUB_TYP IN ('CT','CP')
				AND DF10.LC_DFR_STA = 'A'
				AND DF10.LC_STA_DFR10 = 'A'
				AND LN50.LC_DFR_RSP != '003'
				AND LN50.LC_STA_LON50 = 'A'

			UNION
		
			SELECT
				MAX(LN60.LD_FOR_END) AS EndDate
			FROM
				PD10_PRS_NME PD10
				INNER JOIN LN20_EDS LN20
					ON LN20.LF_EDS = PD10.DF_PRS_ID
					AND LN20.LC_EDS_TYP = 'M'
					AND LN20.LC_STA_LON20 = 'A'
				INNER JOIN LN10_LON LN10
					ON LN10.BF_SSN = LN20.BF_SSN
					AND LN10.LN_SEQ = LN20.LN_SEQ
				INNER JOIN LN60_BR_FOR_APV LN60
					ON LN20.BF_SSN = LN60.BF_SSN
					AND LN20.LN_SEQ = LN60.LN_SEQ
				INNER JOIN FB10_BR_FOR_REQ FB10
					ON LN60.BF_SSN = FB10.BF_SSN
					AND LN60.LF_FOR_CTL_NUM = FB10.LF_FOR_CTL_NUM
				INNER JOIN
				(
					SELECT
						LN85.BF_SSN,
						LN85.LN_SEQ
					FROM
						LN85_LON_ATY LN85
						INNER JOIN AY10_BR_LON_ATY AY10
							ON AY10.BF_SSN = LN85.BF_SSN
							AND AY10.LN_ATY_SEQ = LN85.LN_ATY_SEQ
						INNER JOIN LN20_EDS LN20
							ON LN20.BF_SSN = LN85.BF_SSN
							AND LN20.LN_SEQ = LN85.LN_SEQ
							AND LN20.LC_STA_LON20 = 'A'
							AND LN20.LC_EDS_TYP = 'M'
					WHERE   
						AY10.PF_REQ_ACT = @PF_REQ_ACT
						AND LN20.LF_EDS = @BF_SSN
						AND AY10.LN_ATY_SEQ = @RN_ATY_SEQ_PRC
						--Active flag ignored, as LT20 provides the exact record that is tied to this request
				)LN85
					ON LN85.BF_SSN = LN10.BF_SSN
					AND LN85.LN_SEQ = LN10.LN_SEQ 
			WHERE
				PD10.DF_PRS_ID = @BF_SSN
				AND	FB10.LC_FOR_TYP = '34'
				AND FB10.LC_FOR_STA = 'A'
				AND FB10.LC_STA_FOR10 = 'A'
				AND LN60.LC_FOR_RSP != '003'
				AND LN60.LC_STA_LON60 = 'A'
		) D
	END
END
