SELECT * FROM OPENQUERY(DUSTER, '
SELECT DISTINCT
	PD10.DF_SPE_ACC_ID
	,A.DF_PRS_ID			AS DF_PRS_ID_A
	,B.DF_PRS_ID		AS DF_PRS_ID_B	
	,A.PF_ACT			AS PF_ACT_A
	,B.PF_ACT			AS PF_ACT_B	
	,A.BF_LST_DTS_AY01	AS BF_LST_DTS_AY01_A
	,B.BF_LST_DTS_AY01	AS BF_LST_DTS_AY01_B
	,PD24.DD_BKR_STA
	,A.BX_CMT
	,LN10.LC_STA_LON10
	,LN10.LA_CUR_PRI
	,DW01.WC_DW_LON_STA
	,PD24.DC_BKR_TYP
	,PD24.DC_BKR_STA
FROM 
	DLGSUTWH.OLWHRM1.AY01_BR_ATY A
	INNER JOIN DLGSUTWH.OLWHRM1.AY01_BR_ATY B
		ON A.DF_PRS_ID = B.DF_PRS_ID
	INNER JOIN DLGSUTWH.OLWHRM1.LN10_LON LN10
		ON A.DF_PRS_ID = LN10.BF_SSN
	INNER JOIN DLGSUTWH.OLWHRM1.DW01_DW_CLC_CLU DW01
		ON LN10.BF_SSN = DW01.BF_SSN
		AND LN10.LN_SEQ = DW01.LN_SEQ
	INNER JOIN DLGSUTWH.OLWHRM1.PD24_PRS_BKR PD24
		ON LN10.BF_SSN = PD24.DF_PRS_ID
	INNER JOIN DLGSUTWH.OLWHRM1.PD10_PRS_NME PD10
		ON LN10.BF_SSN = PD10.DF_PRS_ID

WHERE 
	A.PF_ACT = ''MDCID''
	AND	B.PF_ACT = ''DBKRW''
	AND (SUBSTR(A.BX_CMT,65,5)) = ''ASMOC''
	AND A.BF_LST_DTS_AY01 < B.BF_LST_DTS_AY01 
	AND DAYS(A.BF_LST_DTS_AY01) > DAYS(PD24.DD_BKR_STA)
	AND LN10.LC_STA_LON10 = ''R''
	AND LN10.LA_CUR_PRI > 0
	AND DW01.WC_DW_LON_STA = ''21''
	AND PD24.DC_BKR_TYP = ''07''
	AND PD24.DC_BKR_STA = ''06''
	AND DAYS(A.BF_LST_DTS_AY01) = DAYS(CURRENT DATE) - 5
')
