CREATE TABLE [dbo].[LCTR_DAT_Risk] (
    [ID]   BIGINT    NOT NULL,
    [Type] CHAR (10) NOT NULL,
    [Risk] TEXT      NULL,
    CONSTRAINT [PK_LCTR_DAT_Risk] PRIMARY KEY CLUSTERED ([ID] ASC, [Type] ASC),
    CONSTRAINT [FK_LCTR_DAT_Risk_LCTR_LST_Type] FOREIGN KEY ([Type]) REFERENCES [dbo].[LCTR_LST_Type] ([Type])
);

