CREATE TABLE [dbo].[SCKR_DAT_ScriptSchedule] (
    [Script]       NVARCHAR (100) NOT NULL,
    [dMon]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_dMon] DEFAULT (0) NOT NULL,
    [dTue]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_dTue] DEFAULT (0) NOT NULL,
    [dWed]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_dWed] DEFAULT (0) NOT NULL,
    [dThu]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_dThu] DEFAULT (0) NOT NULL,
    [dFri]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_dFri] DEFAULT (0) NOT NULL,
    [mJan]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_mJan] DEFAULT (0) NOT NULL,
    [mFeb]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_mFeb] DEFAULT (0) NOT NULL,
    [mMar]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_mMar] DEFAULT (0) NOT NULL,
    [mApr]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_mApr] DEFAULT (0) NOT NULL,
    [mMay]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_mMay] DEFAULT (0) NOT NULL,
    [mJun]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_mJun] DEFAULT (0) NOT NULL,
    [mJul]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_mJul] DEFAULT (0) NOT NULL,
    [mAug]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_mAug] DEFAULT (0) NOT NULL,
    [mSep]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_mSep] DEFAULT (0) NOT NULL,
    [mOct]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_mOct] DEFAULT (0) NOT NULL,
    [mNov]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_mNov] DEFAULT (0) NOT NULL,
    [mDec]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_mDec] DEFAULT (0) NOT NULL,
    [mOn]          NVARCHAR (50)  CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_mOn] DEFAULT ('') NULL,
    [OnDemandDate] SMALLDATETIME  NULL,
    [Other]        NVARCHAR (50)  CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_Other] DEFAULT ('') NULL,
    [Hold]         BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_Hold] DEFAULT (0) NOT NULL,
    [Holder]       NVARCHAR (50)  CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_Holder] DEFAULT ('') NULL,
    [Prints]       BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_Prints] DEFAULT (0) NOT NULL,
    [Duplex]       BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_Duplex] DEFAULT (0) NOT NULL,
    [Perforated]   BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_Perforated] DEFAULT (0) NOT NULL,
    [Manual]       BIT            CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_Manual] DEFAULT (0) NOT NULL,
    [UserID]       NVARCHAR (50)  CONSTRAINT [DF_SCKR_DAT_ScriptSchedule_UserID] DEFAULT ('') NULL,
    CONSTRAINT [PK_datScriptSchedule] PRIMARY KEY CLUSTERED ([Script] ASC) WITH (FILLFACTOR = 90)
);

