CREATE TABLE [dbo].[SCKR_DAT_ScriptRequests] (
    [Request]                INT            IDENTITY (1, 1) NOT NULL,
    [Class]                  NVARCHAR (3)   CONSTRAINT [DF_SCKR_DAT_ScriptRequests_Class] DEFAULT (N'Scr') NOT NULL,
    [Title]                  NVARCHAR (100) NULL,
    [Script]                 NVARCHAR (100) NULL,
    [Requester]              NVARCHAR (50)  NULL,
    [Requested]              SMALLDATETIME  NULL,
    [Required]               SMALLDATETIME  NULL,
    [Priority]               NVARCHAR (50)  NULL,
    [Reason]                 NTEXT          NULL,
    [Type]                   NVARCHAR (50)  NULL,
    [Summary]                NTEXT          NULL,
    [History]                NTEXT          NULL,
    [SSA]                    NVARCHAR (50)  NULL,
    [OSA]                    NVARCHAR (50)  NULL,
    [Court]                  NVARCHAR (50)  NULL,
    [CourtDate]              SMALLDATETIME  NULL,
    [CurrentStatus]          NVARCHAR (50)  CONSTRAINT [DF_SCKR_DAT_ScriptRequests_CurrentStatus] DEFAULT (N'Draft') NULL,
    [StatusDate]             SMALLDATETIME  CONSTRAINT [DF_SCKR_DAT_ScriptRequests_StatusDate] DEFAULT (convert(datetime,floor(convert(real,getdate())))) NULL,
    [PreviousStatus]         NVARCHAR (50)  NULL,
    [Update]                 NTEXT          NULL,
    [Training]               BIT            CONSTRAINT [DF_SCKR_DAT_ScriptRequests_Training] DEFAULT (0) NOT NULL,
    [TestCo]                 BIT            CONSTRAINT [DF_SCKR_DAT_ScriptRequests_TestCo] DEFAULT ((0)) NOT NULL,
    [TopTen]                 BIT            CONSTRAINT [DF_SCKR_DAT_ScriptRequests_TopTen] DEFAULT (0) NOT NULL,
    [Project]                NVARCHAR (50)  NULL,
    [Expedited]              BIT            CONSTRAINT [DF_SCKR_DAT_ScriptRequests_Expedited] DEFAULT (0) NOT NULL,
    [PriorityCategoryOption] NVARCHAR (50)  NULL,
    [PriorityUrgencyOption]  NVARCHAR (50)  NULL,
    [DevEstimateComplete] decimal(6, 2) NULL, 
    [DevEstimateBegin] DATETIME NULL, 
    [DevEstimateEnd] DATETIME NULL, 
	[TestEstimateComplete] decimal(6, 2) NULL, 
    [TestEstimateBegin] DATETIME NULL, 
    [TestEstimateEnd] DATETIME NULL, 
    CONSTRAINT [PK_datScriptRequests] PRIMARY KEY CLUSTERED ([Request] ASC, [Class] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_SCKR_DAT_ScriptRequests_SCKR_DAT_Scripts] FOREIGN KEY ([Script]) REFERENCES [dbo].[SCKR_DAT_Scripts] ([Script]) ON UPDATE CASCADE
);

