CREATE TABLE [dbo].[SYSA_REF_UserID_Groups] (
    [UserID] NVARCHAR (7)  NOT NULL,
    [Group]  NVARCHAR (10) NOT NULL,
    CONSTRAINT [PK_SYSA_REF_UserID_Groups] PRIMARY KEY CLUSTERED ([UserID] ASC, [Group] ASC),
    CONSTRAINT [FK_SYSA_REF_UserID_Groups_SYSA_LST_Groups] FOREIGN KEY ([Group]) REFERENCES [dbo].[SYSA_LST_Groups] ([GroupName]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_SYSA_REF_UserID_Groups_SYSA_LST_UserIDInfo] FOREIGN KEY ([UserID]) REFERENCES [dbo].[SYSA_LST_UserIDInfo] ([UserID]) ON DELETE CASCADE ON UPDATE CASCADE
);

