CREATE TABLE [dbo].[BORR_Summaries] (
    [DF_SPE_ACC_ID]  VARCHAR (10)    NOT NULL,
    [LA_CUR_PRI]     NUMERIC (38, 2) NULL,
    [WA_TOT_BRI_OTS] NUMERIC (38, 2) NULL,
    [LR_ITR_DLY]     NUMERIC (8, 2)  NULL,
    [LR_ITR_MONTH]   NUMERIC (11, 2) NULL,
    [LR_ITR_MONTH_5] NUMERIC (8, 2)  NULL,
    [COHORT]         VARCHAR (4)     NULL,
    [COHORT_IND]     VARCHAR (1)     NOT NULL,
    CONSTRAINT [PK_BORR_Summaries] PRIMARY KEY CLUSTERED ([DF_SPE_ACC_ID] ASC) WITH (FILLFACTOR = 95)
);

