CREATE TABLE [dbo].[LN16_LON_DLQ_HST] (
    [BF_SSN]             CHAR (9)    NOT NULL,
    [LN_SEQ]             SMALLINT    NOT NULL,
    [LN_DLQ_SEQ]         SMALLINT    NOT NULL,
    [LC_DLQ_TYP]         CHAR (1)    NOT NULL,
    [LC_STA_LON16]       CHAR (1)    NOT NULL,
    [LD_STA_LON16]       DATETIME    NOT NULL,
    [LD_DLQ_OCC]         DATETIME    NULL,
    [LN_DLQ_MAX]         NUMERIC (4) NOT NULL,
    [LN_DLQ_ITL]         NUMERIC (4) NOT NULL,
    [LD_DLQ_MAX]         DATETIME    NOT NULL,
    [LD_DLQ_ITL]         DATETIME    NOT NULL,
    [LF_LST_DTS_LN16]    DATETIME    NOT NULL,
    [LI_RSM_DUN_NXT_BKT] CHAR (1)    NOT NULL,
    [LI_NO_DLQ_IC]       CHAR (1)    NOT NULL,
    [LI_DLQ_PFU_PAY_XST] CHAR (1)    NULL,
    CONSTRAINT [PK_LN16_LON_DLQ_HST] PRIMARY KEY CLUSTERED ([BF_SSN] ASC, [LN_SEQ] ASC, [LN_DLQ_SEQ] ASC)
);




GO
CREATE NONCLUSTERED INDEX [IX_LCDLQTYP_LCSTALON16]
    ON [dbo].[LN16_LON_DLQ_HST]([LC_DLQ_TYP] ASC, [LC_STA_LON16] ASC)
    INCLUDE([BF_SSN], [LN_SEQ], [LD_DLQ_OCC]);


GO
CREATE NONCLUSTERED INDEX [IX_LCSTALON16]
    ON [dbo].[LN16_LON_DLQ_HST]([LC_STA_LON16] ASC)
    INCLUDE([BF_SSN], [LN_SEQ], [LN_DLQ_MAX]);

