CREATE TABLE [dbo].[SD10_STU_SPR] (
    [LF_STU_SSN]         CHAR (9)      NOT NULL,
    [LN_STU_SPR_SEQ]     SMALLINT      NOT NULL,
    [LD_STA_STU10]       DATE          NULL,
    [LC_STA_STU10]       CHAR (1)      NOT NULL,
    [LD_NTF_SCL_SPR]     DATE          NULL,
    [LC_SCR_SCL_SPR]     CHAR (2)      NOT NULL,
    [LC_REA_SCL_SPR]     CHAR (2)      NOT NULL,
    [LD_SCL_SPR]         DATE          NULL,
    [LF_DOE_SCL_ENR_CUR] VARCHAR (8)   NOT NULL,
    [LF_LST_DTS_SD10]    DATETIME2 (7) NOT NULL,
    [IF_HSP]             CHAR (6)      NULL,
    [LD_SCL_CER_STU_STA] DATE          NULL,
    [LD_ENR_STA_EFF_CAM] DATE          NULL,
    [LC_SEP_DTE_TRT_SRC] VARCHAR (2)   NOT NULL,
    [LF_LST_USR_SD10]    VARCHAR (8)   NOT NULL,
    [LX_GTR_ID_CHG_SRC]  VARCHAR (3)   NOT NULL,
    CONSTRAINT [PK_SD10_STU_SPR] PRIMARY KEY CLUSTERED ([LF_STU_SSN] ASC, [LN_STU_SPR_SEQ] ASC) WITH (FILLFACTOR = 95)
);


GO
CREATE NONCLUSTERED INDEX [IX_LCSTASTU10_LDSCLSPR]
    ON [dbo].[SD10_STU_SPR]([LC_STA_STU10] ASC, [LD_SCL_SPR] ASC)
    INCLUDE([LF_STU_SSN]);


GO
CREATE NONCLUSTERED INDEX [IX_LCSTASTU10_LCREASCLSPR]
    ON [dbo].[SD10_STU_SPR]([LC_STA_STU10] ASC, [LC_REA_SCL_SPR] ASC)
    INCLUDE([LF_STU_SSN]);

