options remote= cyprus ;
signon ;
LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE TESTQUERY AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT distinct df_spe_acc_id
FROM	OLWHRM1.PD10_PRS_NME a
inner join OLWHRM1.PD42_PRS_PHN b
	on a.df_prs_id = b.df_prs_id
LEFT OUTER JOIN OLWHRM1.PD41_PHN_HST D
	ON B.DF_PRS_ID = D.DF_PRS_ID
	AND B.DC_PHN = D.DC_PHN_HST
WHERE dc_phn = 'H'
	AND DN_DOM_PHN_ARA = '801'
	AND DN_DOM_PHN_XCH = '555'
	AND DN_DOM_PHN_LCL = '1212'
	AND DD_PHN_VER BETWEEN '04/13/2011' AND '04/19/2011'
	and dd_crt_41 = dd_phn_ver


FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
ENDRSUBMIT;
DATA TESTQUERY;
	SET WORKLOCL.TESTQUERY;
RUN;

DATA _NULL_;
SET testquery ;
FILE 't:\sas\Loan Servicing MD Primary Phone Clean Up.txt' DELIMITER=',' DSD DROPOVER LRECL=32767;
put df_spe_acc_id $;
RUN;
