CREATE TABLE [dbo].[LCTR_DAT_LinkedTopics] (
    [ID]   BIGINT NOT NULL,
    [ToID] BIGINT NOT NULL,
    CONSTRAINT [PK_LCTR_DAT_LinkedTopics] PRIMARY KEY CLUSTERED ([ID] ASC, [ToID] ASC),
    CONSTRAINT [FK_LCTR_DAT_LinkedTopics_LCTR_DAT_Topic] FOREIGN KEY ([ID]) REFERENCES [dbo].[LCTR_DAT_Topic] ([ID]),
    CONSTRAINT [FK_LCTR_DAT_LinkedTopics_LCTR_DAT_Topic1] FOREIGN KEY ([ToID]) REFERENCES [dbo].[LCTR_DAT_Topic] ([ID])
);

