CREATE TABLE [dbo].[SCKR_DAT_SASSchedule] (
    [Job]          NVARCHAR (100) NOT NULL,
    [Description]  NVARCHAR (30)  NULL,
    [EffDate]      SMALLDATETIME  CONSTRAINT [DF_SCKR_DAT_SASSchedule_EffDate] DEFAULT (convert(datetime,floor(convert(real,getdate())))) NULL,
    [NoReports]    INT            NULL,
    [Predecessor]  NVARCHAR (100) NULL,
    [Successor]    NVARCHAR (50)  NULL,
    [Restart]      NVARCHAR (110) CONSTRAINT [DF_SCKR_DAT_SASSchedule_Restart] DEFAULT (N'Restart the job the first time it fails; after that, e-mail Jay, Scott, Andy, Trent, Debbie, and Brenda.') NOT NULL,
    [dMon]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_dMon] DEFAULT (0) NOT NULL,
    [dTue]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_dTue] DEFAULT (0) NOT NULL,
    [dWed]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_dWed] DEFAULT (0) NOT NULL,
    [dThu]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_dThu] DEFAULT (0) NOT NULL,
    [dFri]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_dFri] DEFAULT (0) NOT NULL,
    [dSat]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_dSat] DEFAULT (0) NOT NULL,
    [dMonAM]       BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_dMonAM] DEFAULT (0) NOT NULL,
    [wMon]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_wMon] DEFAULT (0) NOT NULL,
    [wTue]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_wTue] DEFAULT (0) NOT NULL,
    [wWed]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_wWed] DEFAULT (0) NOT NULL,
    [wThu]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_wThu] DEFAULT (0) NOT NULL,
    [wFri]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_wFri] DEFAULT (0) NOT NULL,
    [wSat]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_wSat] DEFAULT (0) NOT NULL,
    [wMonAM]       BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_wMonAM] DEFAULT (0) NOT NULL,
    [mJan]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_mJan] DEFAULT (0) NOT NULL,
    [mFeb]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_mFeb] DEFAULT (0) NOT NULL,
    [mMar]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_mMar] DEFAULT (0) NOT NULL,
    [mApr]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_mApr] DEFAULT (0) NOT NULL,
    [mMay]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_mMay] DEFAULT (0) NOT NULL,
    [mJun]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_mJun] DEFAULT (0) NOT NULL,
    [mJul]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_mJul] DEFAULT (0) NOT NULL,
    [mAug]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_mAug] DEFAULT (0) NOT NULL,
    [mSep]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_mSep] DEFAULT (0) NOT NULL,
    [mOct]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_mOct] DEFAULT (0) NOT NULL,
    [mNov]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_mNov] DEFAULT (0) NOT NULL,
    [mDec]         BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_mDec] DEFAULT (0) NOT NULL,
    [mOn]          NVARCHAR (50)  CONSTRAINT [DF_SCKR_DAT_SASSchedule_mOn] DEFAULT (0) NULL,
    [OnDemand]     BIT            NOT NULL,
    [EOM]          BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_EOM] DEFAULT (0) NOT NULL,
    [Other]        NVARCHAR (50)  NULL,
    [ExcSat]       BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_ExcSat] DEFAULT (0) NOT NULL,
    [ExcEOM]       BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_ExcEOM] DEFAULT (1) NOT NULL,
    [ExcBeforeEOM] BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_ExcBeforeEOM] DEFAULT (1) NOT NULL,
    [ExcHoliday]   BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_ExcHoliday] DEFAULT (1) NOT NULL,
    [RollNot]      BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_RollNot] DEFAULT (0) NOT NULL,
    [RollNext]     BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_RollNext] DEFAULT (0) NOT NULL,
    [RollPrevious] BIT            CONSTRAINT [DF_SCKR_DAT_SASSchedule_RollPrevious] DEFAULT (0) NOT NULL,
    [Archive]      NVARCHAR (50)  NULL,
    [Vault1]       NVARCHAR (50)  NULL,
    [Vault2]       NVARCHAR (50)  NULL,
    CONSTRAINT [PK_datSASSchedule] PRIMARY KEY CLUSTERED ([Job] ASC) WITH (FILLFACTOR = 90)
);

