CREATE TABLE [dbo].[SODT_LST_Test] (
    [PKEY] BIGINT        IDENTITY (1, 1) NOT NULL,
    [JN]   VARCHAR (100) CONSTRAINT [DF_SODT_LST_Test_JN] DEFAULT (' ') NOT NULL,
    [MN]   VARCHAR (50)  CONSTRAINT [DF_SODT_LST_Test_MN] DEFAULT (' ') NOT NULL,
    [RB]   VARCHAR (50)  CONSTRAINT [DF_SODT_LST_Test_RB] DEFAULT (' ') NOT NULL,
    [FIN]  BIT           CONSTRAINT [DF_SODT_LST_Test_FIN] DEFAULT (0) NOT NULL,
    [RD]   DATETIME      CONSTRAINT [DF_SODT_LST_Test_RD] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_SODT_LST_Test] PRIMARY KEY CLUSTERED ([PKEY] ASC)
);

