CREATE TABLE [dbo].[SYSA_REF_UserID_Systems] (
    [UserID] NVARCHAR (7)  NOT NULL,
    [System] NVARCHAR (30) NOT NULL,
    [Notes]  NTEXT         NULL,
    CONSTRAINT [PK_SYSA_REF_UserID_Systems] PRIMARY KEY CLUSTERED ([UserID] ASC, [System] ASC),
    CONSTRAINT [FK_SYSA_REF_UserID_Systems_SYSA_LST_Systems] FOREIGN KEY ([System]) REFERENCES [dbo].[SYSA_LST_Systems] ([System]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_SYSA_REF_UserID_Systems_SYSA_LST_UserIDInfo] FOREIGN KEY ([UserID]) REFERENCES [dbo].[SYSA_LST_UserIDInfo] ([UserID]) ON DELETE CASCADE ON UPDATE CASCADE
);

