CREATE PROCEDURE [dbo].[LT_US06BIDRFG_Loans]
	@BF_SSN CHAR(9),
	@IsCoborrower BIT = 0,
	@RN_ATY_SEQ_PRC INT
AS
BEGIN
	
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @LetterId VARCHAR(10) = 'US06BIDRFG'
DECLARE @PF_REQ_ACT VARCHAR(5) = (SELECT AC11.PF_REQ_ACT FROM AC11_ACT_REQ_LTR AC11 WHERE PF_LTR = @LetterId)

IF @IsCoborrower = 0
	BEGIN
		SELECT
			ISNULL(FMT.Label, LN10.IC_LON_PGM) AS [Loan Program],
			CONVERT(VARCHAR(10), LN10.LD_LON_1_DSB, 101) AS [Disbursement Date],
			ISNULL(LN72.LR_ITR, 0.0) AS [Interest Rate],
			'$' + CAST(ISNULL(LN10.LA_CUR_PRI,0) AS VARCHAR) AS [Current Principal Balance]
		FROM
			LN10_LON LN10
			INNER JOIN DW01_DW_CLC_CLU DW01
				ON DW01.BF_SSN = LN10.BF_SSN
				AND DW01.LN_SEQ = LN10.LN_SEQ
			INNER JOIN
			(	--Adding Active Interest Rate
				SELECT
					LN72.BF_SSN, 
					LN72.LN_SEQ,
					LN72.LR_ITR,
					ROW_NUMBER() OVER (PARTITION BY LN72.BF_SSN, LN72.LN_SEQ, LN72.LR_ITR ORDER BY LD_STA_LON72 DESC) AS SEQ
				FROM
					LN72_INT_RTE_HST LN72
					INNER JOIN PD10_PRS_NME PD10 
						ON PD10.DF_PRS_ID = LN72.BF_SSN
				WHERE
					LN72.LC_STA_LON72 = 'A'
					AND	CAST(GETDATE() AS DATE) BETWEEN LN72.LD_ITR_EFF_BEG AND LN72.LD_ITR_EFF_END
					AND	LN72.BF_SSN = @BF_SSN
			) LN72 
				ON LN10.BF_SSN = LN72.BF_SSN
				AND LN10.LN_SEQ = LN72.LN_SEQ
				AND LN72.SEQ = 1
			INNER JOIN
			(
				SELECT
					LN85.BF_SSN,
					LN85.LN_SEQ
				FROM
					LN85_LON_ATY LN85
					INNER JOIN AY10_BR_LON_ATY AY10
						ON AY10.BF_SSN = LN85.BF_SSN
						AND AY10.LN_ATY_SEQ = LN85.LN_ATY_SEQ
				WHERE   
					AY10.PF_REQ_ACT = @PF_REQ_ACT
					AND AY10.BF_SSN = @BF_SSN
					AND AY10.LN_ATY_SEQ = @RN_ATY_SEQ_PRC
					--Active flag ignored, as LT20 provides the exact record that is tied to this request
			)LN85
				ON LN85.BF_SSN = LN10.BF_SSN
				AND LN85.LN_SEQ = LN10.LN_SEQ 
			LEFT JOIN FormatTranslation FMT
				ON FMT.FmtName = '$LNPROG'
				AND FMT.Start = LN10.IC_LON_PGM
			WHERE
				LN10.BF_SSN = @BF_SSN
	END
ELSE
	BEGIN
		SELECT
			ISNULL(FMT.Label, LN10.IC_LON_PGM) AS [Loan Program],
			CONVERT(VARCHAR(10), LN10.LD_LON_1_DSB, 101) AS [Disbursement Date],
			ISNULL(LN72.LR_ITR, 0.0) AS [Interest Rate],
			'$' + CAST(ISNULL(LN10.LA_CUR_PRI,0)  AS VARCHAR) AS [Current Principal Balance]
		FROM
			LN20_EDS LN20
			INNER JOIN LN10_LON LN10
				ON LN10.BF_SSN = LN20.BF_SSN
				AND LN10.LN_SEQ = LN20.LN_SEQ
			INNER JOIN DW01_DW_CLC_CLU DW01
				ON DW01.BF_SSN = LN10.BF_SSN
				AND DW01.LN_SEQ = LN10.LN_SEQ
			INNER JOIN
			(	--Adding Active Interest Rate
				SELECT
					LN72.BF_SSN, 
					LN72.LN_SEQ,
					LN72.LR_ITR,
					ROW_NUMBER() OVER (PARTITION BY LN72.BF_SSN, LN72.LN_SEQ, LN72.LR_ITR ORDER BY LD_STA_LON72 DESC) AS SEQ
				FROM
					LN72_INT_RTE_HST LN72
					INNER JOIN LN20_EDS LN20
						ON LN20.BF_SSN = LN72.BF_SSN
						AND LN20.LN_SEQ = LN72.LN_SEQ
						AND LN20.LC_STA_LON20 = 'A'
						AND LN20.LC_EDS_TYP = 'M' --Coborrower
					INNER JOIN PD10_PRS_NME PD10 
						ON PD10.DF_PRS_ID = LN20.LF_EDS
				WHERE
					LN72.LC_STA_LON72 = 'A'
					AND	CAST(GETDATE() AS DATE) BETWEEN LN72.LD_ITR_EFF_BEG AND LN72.LD_ITR_EFF_END
					AND	LN20.LF_EDS = @BF_SSN
			) LN72 
				ON LN10.BF_SSN = LN72.BF_SSN
				AND LN10.LN_SEQ = LN72.LN_SEQ
				AND LN72.SEQ = 1
			INNER JOIN
			(
				SELECT
					LN85.BF_SSN,
					LN85.LN_SEQ
				FROM
					LN85_LON_ATY LN85
					INNER JOIN AY10_BR_LON_ATY AY10
						ON AY10.BF_SSN = LN85.BF_SSN
						AND AY10.LN_ATY_SEQ = LN85.LN_ATY_SEQ
					INNER JOIN LN20_EDS LN20
						ON LN20.BF_SSN = LN85.BF_SSN
						AND LN20.LN_SEQ = LN85.LN_SEQ
						AND LN20.LC_STA_LON20 = 'A'
						AND LN20.LC_EDS_TYP = 'M'
				WHERE   
					AY10.PF_REQ_ACT = @PF_REQ_ACT
					AND LN20.LF_EDS = @BF_SSN
					AND AY10.LN_ATY_SEQ = @RN_ATY_SEQ_PRC
					--Active flag ignored, as LT20 provides the exact record that is tied to this request
			)LN85
				ON LN85.BF_SSN = LN10.BF_SSN
				AND LN85.LN_SEQ = LN10.LN_SEQ 
			LEFT JOIN FormatTranslation FMT
				ON FMT.FmtName = '$LNPROG'
				AND FMT.Start = LN10.IC_LON_PGM
			WHERE
				LN20.LF_EDS = @BF_SSN
				AND LN20.LC_EDS_TYP = 'M'
				AND LN20.LC_STA_LON20 = 'A'
	END
END