/*UTLWA05 - Calculated Origination Fees on Loans not Owned by UHEAA*/
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/

%LET RPTLIB = C:/WINDOWS/TEMP;
FILENAME REPORT2 "&RPTLIB/ULWA05.LWA05R2";
/*PREVIOUS QUARTER*/
DATA _NULL_;
	CALL SYMPUT('END',"'"||PUT(intnx('QTR',today()+3,-1,'end'), MMDDYYD10.)||"'");
RUN;
%SYSLPUT END = &END;
libname  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=work  ;
RSUBMIT;
options symbolgen;
LIBNAME SAS_TAB V8 '/sas/whse/progrevw';
PROC SQL NOPRINT;
	SELECT "'"||TRIM(LENDER_ID)||"'"
		INTO :UHEAA_LIST SEPARATED BY ","
	FROM SAS_TAB.LDR_AFF
	WHERE AFFILIATION = 'UHEAA';
QUIT;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE QTRORG AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT COUNT(DISTINCT A.BF_SSN||CHAR(A.LN_SEQ)) AS LON_CT
	,SUM((B.LA_DSB - COALESCE(B.LA_DSB_CAN,0)) * 0.03) AS ORG_FEE
FROM  OLWHRM1.LN10_LON A 
INNER JOIN OLWHRM1.LN15_DSB B
	ON A.BF_SSN = B.BF_SSN
	AND A.LN_SEQ = B.LN_SEQ
INNER JOIN OLWHRM1.DW01_DW_CLC_CLU C
	ON A.BF_SSN = C.BF_SSN
	AND A.LN_SEQ = C.LN_SEQ

WHERE B.LC_DSB_TYP = '2' /*ACTUAL*/
AND B.LC_STA_LON15 IN ('1','3')
AND A.IF_GTR = '000749'
AND A.LF_LON_CUR_OWN NOT IN (&UHEAA_LIST)
AND C.WC_DW_LON_STA IN ('01','02','03','20','21')
AND (B.LA_DSB_CAN IS NULL
    OR B.LA_DSB_CAN <> B.LA_DSB)
AND A.LA_CUR_PRI > 0
AND A.LD_LON_GTR BETWEEN '05/01/2000' AND &END
);
DISCONNECT FROM DB2;
ENDRSUBMIT;

DATA QTRORG; 
SET WORKLOCL.QTRORG; 
RUN;

PROC PRINTTO PRINT=REPORT2 new;
RUN;
OPTIONS CENTER NODATE NUMBER PAGENO=1 LS=132;
PROC PRINT NOOBS SPLIT='/' DATA=QTRORG WIDTH=UNIFORM WIDTH=MIN;
VAR LON_CT ORG_FEE;
LABEL LON_CT="NUMBER OF LOANS" ORG_FEE="CALCULATED ORIGINATION FEES";
FORMAT LON_CT COMMA9. ORG_FEE DOLLAR14.2;
TITLE 'Calculated Origination Fees on Loans not Owned by UHEAA';
FOOTNOTE  'JOB = UTLWA05     REPORT = ULWA05.LWA05R2';
RUN;
PROC PRINTTO;
RUN;

/*testfile;

DATA _NULL_;
CALL SYMPUT('END',"'"||PUT(intnx('QTR',today()+3,-1,'end'), MMDDYYD10.)||"'");
RUN;

%SYSLPUT END = &END;
libname  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=work  ;
RSUBMIT;
options symbolgen;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE QTRORGTST AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT A.BF_SSN
	,A.LN_SEQ
	,C.WC_DW_LON_STA
	,A.LD_LON_GTR
	,B.LN_LON_DSB_SEQ
	,B.LA_DSB
	,COALESCE(B.LA_DSB_CAN,0) AS LA_DSB_CAN
FROM  OLWHRM1.LN10_LON A 
INNER JOIN OLWHRM1.LN15_DSB B
	ON A.BF_SSN = B.BF_SSN
	AND A.LN_SEQ = B.LN_SEQ
INNER JOIN OLWHRM1.DW01_DW_CLC_CLU C
	ON A.BF_SSN = C.BF_SSN
	AND A.LN_SEQ = C.LN_SEQ

WHERE B.LC_DSB_TYP = '2'
AND B.LC_STA_LON15 IN ('1','3')
AND A.IF_GTR = '000749'
AND A.LF_LON_CUR_OWN <> '828476'
AND C.WC_DW_LON_STA IN ('01','02','03','20','21')
AND (B.LA_DSB_CAN IS NULL
    OR B.LA_DSB_CAN <> B.LA_DSB)
AND A.LA_CUR_PRI > 0
AND A.LD_LON_GTR BETWEEN '05/01/2000' AND &END
ORDER BY A.BF_SSN, A.LN_SEQ, B.LN_LON_DSB_SEQ
);
DISCONNECT FROM DB2;
ENDRSUBMIT;

DATA QTRORGTST; 
SET WORKLOCL.QTRORGTST; 
RUN;

PROC EXPORT DATA= WORKLOCL.QTRORGTST
            OUTFILE= "T:\SAS\QTRORGTST.txt" 
            DBMS=CSV REPLACE;
RUN;
*/
