/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/ULWM42.LWM42RZ";
FILENAME REPORT2 "&RPTLIB/ULWM42.LWM42R2";
FILENAME REPORT3 "&RPTLIB/ULWM42.LWM42R3";

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
%MACRO SQLCHECK ;
  %IF  &SQLXRC NE 0  %THEN  %DO  ;
    DATA _NULL_  ;
            FILE REPORTZ NOTITLES  ;
            PUT @01 " ********************************************************************* "
              / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
              / @01 " ****  THE SAS SHOULD BE REVIEWED.                                **** "       
              / @01 " ********************************************************************* "
              / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
              / @01 " ****  &SQLXMSG   **** "
              / @01 " ********************************************************************* "
            ;
         RUN  ;
  %END  ;
%MEND  ;

PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE DEMO AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT E.DF_SPE_ACC_ID
	,B.AD_DSB_ADJ
	,A.LF_CLM_ID
	,D.BN_RHB_PAY_CTR
	,COALESCE(A.LA_CLM_PRI,0) + COALESCE(A.LA_CLM_INT,0) - COALESCE(A.LA_PRI_COL,0)
	+ COALESCE(A.LA_INT_ACR,0) + COALESCE(C.LA_CLM_INT_ACR,0) 
	- COALESCE(A.LA_INT_COL,0) + COALESCE(A.LA_LEG_CST_ACR,0) 
	- COALESCE(A.LA_LEG_CST_COL,0) + COALESCE(A.LA_OTH_CHR_ACR,0)
	- COALESCE(A.LA_OTH_CHR_COL,0) + COALESCE(A.LA_COL_CST_ACR,0)
	- COALESCE(A.LA_COL_CST_COL,0) + COALESCE(C.LA_CLM_PRJ_COL_CST,0) AS BALANCE
FROM OLWHRM1.PD01_PDM_INF E
INNER JOIN OLWHRM1.BR01_BR_CRF D
	ON E.DF_PRS_ID = D.BF_SSN
INNER JOIN OLWHRM1.DC01_LON_CLM_INF A
	ON E.DF_PRS_ID = A.BF_SSN
INNER JOIN OLWHRM1.DC02_BAL_INT C
	ON A.AF_APL_ID = C.AF_APL_ID
	AND A.AF_APL_ID_SFX = C.AF_APL_ID_SFX
	AND A.LF_CRT_DTS_DC10 = C.LF_CRT_DTS_DC10
INNER JOIN OLWHRM1.GA11_LON_DSB_ATY B
	ON A.AF_APL_ID = B.AF_APL_ID
	AND A.AF_APL_ID_SFX = B.AF_APL_ID_SFX
WHERE A.LC_STA_DC10 = '03'
	AND A.LC_RHB_CON != '07'
	AND B.AD_DSB_ADJ >= '10/01/2007'
	AND B.AN_DSB_SEQ = 1
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;

/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>> ;  ** INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK;*/
/*QUIT;*/

ENDRSUBMIT;
DATA DEMO;
	SET WORKLOCL.DEMO;
RUN;
PROC SORT DATA=DEMO;
	BY DF_SPE_ACC_ID LF_CLM_ID AD_DSB_ADJ ;
RUN;
DATA DEMO;
SET DEMO;
BY DF_SPE_ACC_ID LF_CLM_ID AD_DSB_ADJ ;
IF FIRST.LF_CLM_ID;
RUN;
PROC SORT DATA=DEMO;
	BY DF_SPE_ACC_ID AD_DSB_ADJ LF_CLM_ID;
RUN;

/*FOR PORTRAIT REPORTS;*/
OPTIONS ORIENTATION = PORTRAIT;
OPTIONS PS=52 LS=96 NONUMBER;
TITLE 'POTENTIAL REHABS FOR LOAN DISB ON OR AFTER 10/1/07';

PROC PRINTTO PRINT=REPORT2 NEW;
RUN;

PROC PRINT NOOBS SPLIT='/' DATA=DEMO WIDTH=UNIFORM WIDTH=MIN LABEL;
FORMAT BALANCE DOLLAR12.2 AD_DSB_ADJ MMDDYY10.;
VAR DF_SPE_ACC_ID AD_DSB_ADJ LF_CLM_ID BN_RHB_PAY_CTR BALANCE;
LABEL DF_SPE_ACC_ID = 'ACCOUNT NUMBER'
	AD_DSB_ADJ = '1ST DISBURSEMENT DATE'
	LF_CLM_ID = 'CLAIM ID'
	BN_RHB_PAY_CTR = 'REHAB PAYMENT COUNTER'
	BALANCE = 'CURRENT BALANCE';
RUN;

DATA SUMMARY(KEEP=TOT_NUM TOT_BAL TOT_BAL_1_8 TOT_BAL_9);
SET DEMO END=LAST;
RETAIN TOT_NUM TOT_BAL TOT_BAL_1_8 TOT_BAL_9 0;
TOT_NUM + 1;
TOT_BAL + BALANCE;
IF BN_RHB_PAY_CTR >=1 AND BN_RHB_PAY_CTR <= 8 THEN TOT_BAL_1_8 + BALANCE;
ELSE IF BN_RHB_PAY_CTR >=9 THEN TOT_BAL_9 + BALANCE;
IF LAST;
RUN;

PROC PRINTTO PRINT=REPORT3 NEW;
RUN;
TITLE 'SUMMARY OF LOANS 1ST DISB ON OR AFTER 10/01/07';

PROC PRINT NOOBS SPLIT='/' DATA=SUMMARY WIDTH=UNIFORM WIDTH=MIN LABEL;
FORMAT TOT_BAL TOT_BAL_1_8 TOT_BAL_9 DOLLAR12.2;
VAR TOT_NUM TOT_BAL TOT_BAL_1_8 TOT_BAL_9;
LABEL TOT_NUM = 'TOTAL # OF LOANS IN DEFAULT'
	TOT_BAL = 'TOTAL OUTSTANDING BALANCE'
	TOT_BAL_1_8 = 'TOTAL BALANCE: 1 TO 8 PAYMENTS TOWARD REHAB'
	TOT_BAL_9 = 'TOTAL BALANCE: 9+ PAYMENTS TOWARD REHAB';

PROC PRINTTO;
RUN;
