/*UTLWI03 AUX SERVICES ACTION CODE-ARC USAGE SUMMARY*/
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/ULWI03.LWI03RZ";
FILENAME REPORT2 "&RPTLIB/ULWI03.LWI03R2";

DATA _NULL_;
     CALL SYMPUT('PRVDY',"'"||PUT(INTNX('DAY',TODAY(),-1,'BEGINNING'), MMDDYYD10.)||"'");
	 CALL SYMPUT("RUNDT",LEFT(PUT("&SYSDATE"D,MMDDYY10.)));
RUN;
%SYSLPUT PRVDY = &PRVDY;
LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
%MACRO SQLCHECK (SQLRPT= );
%IF &SQLXRC NE 0 %THEN %DO;
	DATA _NULL_;
    FILE REPORTZ NOTITLES;
    PUT @01 " ********************************************************************* "
      / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
      / @01 " ****  THE SAS LOG IN &SQLRPT SHOULD BE REVIEWED.          **** "       
      / @01 " ********************************************************************* "
      / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
      / @01 " ****  &SQLXMSG   **** "
      / @01 " ********************************************************************* ";
	RUN;
%END;
%MEND;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE ONELINK AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT
	A.BF_LST_USR_AY01	AS USER_ID,
	A.PF_ACT			AS ACTION_CODE,
	RTRIM(B.PX_ACT_DSC)	AS ACTION_CODE_DESCRIPTION,  
	A.BC_ATY_TYP		AS ACTIVITY_TYPE,
	A.BC_ATY_CNC_TYP	AS CONTACT_TYPE, 
	A.DF_PRS_ID			AS SSN,
	A.BD_ATY_PRF		AS DATE,
	A.BX_CMT			AS COMMENTS
FROM OLWHRM1.AY01_BR_ATY A 
 	INNER JOIN OLWHRM1.AC01_ACT B
ON A.PF_ACT = B.PF_ACT
INNER JOIN OLWHRM1.US10_USR_PFL F
	ON A.BF_LST_USR_AY01 = F.PF_USR
WHERE A.BD_ATY_PRF = &PRVDY
AND F.PC_SER_DPT = 'DOC'
AND F.PD_USR_IN_DPT_END IS NULL
FOR READ ONLY WITH UR
);

CREATE TABLE COMPASS AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT
	A.LF_PRF_BY				AS USER_ID,
	A.PF_REQ_ACT			AS ACTION_CODE,
	RTRIM(B.PX_ACT_DSC_REQ)	AS ACTION_CODE_DESCRIPTION,  
	A.LC_ATY_RCP			AS ACTIVITY_TYPE,
	A.PF_RSP_ACT			AS RESPONSE_CODE, 
	A.BF_SSN				AS SSN,
	A.LD_ATY_RSP			AS DATE,
	D.LX_ATY				AS COMMENTS,
	D.LF_LST_DTS_AY20		AS CDTSMP,
	D.LN_ATY_CMT_SEQ,
	C.LN_ATY_SEQ	
FROM OLWHRM1.AY10_BR_LON_ATY A 
INNER JOIN OLWHRM1.AC10_ACT_REQ B
	ON A.PF_REQ_ACT = B.PF_REQ_ACT
INNER JOIN OLWHRM1.AY15_ATY_CMT C
	ON A.BF_SSN = C.BF_SSN
	AND A.LN_ATY_SEQ = C.LN_ATY_SEQ
INNER JOIN OLWHRM1.AY20_ATY_TXT D
 	ON C.BF_SSN = D.BF_SSN
	AND C.LN_ATY_SEQ = D.LN_ATY_SEQ
	AND C.LN_ATY_CMT_SEQ = D.LN_ATY_CMT_SEQ
INNER JOIN OLWHRM1.US10_USR_PFL F
	ON A.LF_PRF_BY = F.PF_USR
WHERE A.LD_ATY_RSP = &PRVDY
AND F.PC_SER_DPT = 'DOC'
AND F.PD_USR_IN_DPT_END IS NULL
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>>  ;  * INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK (SQLRPT=UTLWI03.LWI03RZ);*/
/*QUIT;*/
ENDRSUBMIT;
DATA ONELINK;SET WORKLOCL.ONELINK;RUN;
DATA COMPASS;SET WORKLOCL.COMPASS;RUN;

PROC SORT DATA = COMPASS;
BY SSN LN_ATY_SEQ USER_ID ACTION_CODE ACTION_CODE_DESCRIPTION ACTIVITY_TYPE RESPONSE_CODE DATE;
RUN;

PROC TRANSPOSE DATA=COMPASS OUT=COMPASS (DROP=_NAME_ _LABEL_) PREFIX=CMT;
VAR COMMENTS;
BY SSN LN_ATY_SEQ USER_ID ACTION_CODE ACTION_CODE_DESCRIPTION ACTIVITY_TYPE RESPONSE_CODE DATE;
RUN;

%MACRO CRT_TBL(NEWTAB,OLDTAB);
PROC SQL;
CREATE TABLE &NEWTAB AS
SELECT USER_ID
	,ACTION_CODE
	,ACTION_CODE_DESCRIPTION
	,COUNT(ACTION_CODE) AS TTL_BY_CD
FROM &OLDTAB
GROUP BY USER_ID, ACTION_CODE, ACTION_CODE_DESCRIPTION
ORDER BY USER_ID, ACTION_CODE, ACTION_CODE_DESCRIPTION
;
QUIT;
%MEND CRT_TBL;
%CRT_TBL(COSUM,COMPASS);
%CRT_TBL(ONELINKSUM,ONELINK);

DATA ACSUM;
SET ONELINKSUM COSUM;
RUN;

PROC SORT DATA=ACSUM;
BY USER_ID ACTION_CODE;
RUN;

PROC PRINTTO PRINT=REPORT2 NEW;
RUN;
OPTIONS ORIENTATION = PORTRAIT PS = 52 LS = 96 PAGENO=1 NOBYLINE;
PROC PRINT NOOBS SPLIT='/' DATA=ACSUM;
BY 		USER_ID;
PAGEBY USER_ID;
SUM 	TTL_BY_CD;
LABEL 	USER_ID = 'User ID'
		ACTION_CODE = 'Action Code'
		ACTION_CODE_DESCRIPTION = 'Action Code Description'
		TTL_BY_CD = 'Total Used';
VAR 	ACTION_CODE ACTION_CODE_DESCRIPTION TTL_BY_CD;
TITLE	"Document Services' Action Code/ARC Usage Summary";
TITLE2 	'For User ID: #BYVAL1';
FOOTNOTE  'JOB = UTLWI03     REPORT = ULWI03.LWI03R2';
RUN;
PROC PRINTTO;
RUN;
/*-----------------------------ONELINK DETAIL REPORTS-----------------------------*/
/*PROC SORT DATA=ONELINK;BY USER_ID;RUN;*/
/*OPTIONS ORIENTATION = LANDSCAPE PS = 39 LS = 128 PAGENO=1;*/
/*PROC PRINTTO PRINT="&RPTLIB/UTLWI03_ONELINK_ACTIVITY" NEW;*/
/*RUN;*/
/*PROC PRINT SPLIT='/' DATA=ONELINK N="TOTAL:  " ;*/
/*BY USER_ID;*/
/*LABEL USER_ID = 'User ID'*/
/*ACTION_CODE = 'Action Code'*/
/*ACTION_CODE_DESCRIPTION = 'Action Code Description'*/
/*ACTIVITY_TYPE = 'Activity Type'*/
/*CONTACT_TYPE = 'Contact Type'*/
/*SSN = 'SNN'*/
/*DATE = 'Date'*/
/*COMMENTS = 'Comments';*/
/*VAR USER_ID ACTION_CODE ACTION_CODE_DESCRIPTION ACTIVITY_TYPE CONTACT_TYPE SSN DATE;*/
/*FORMAT DATE MMDDYY.;*/
/*TITLE	"Document Services' Activity History Entries - OneLINK";*/
/*FOOTNOTE  'JOB = UTLWI03     REPORT = UTLWI03_ONELINK_ACTIVITY';*/
/*RUN;*/
/*PROC PRINTTO PRINT="&RPTLIB/UTLWI03_ONELINK_ACTIVITY_COMMENTS" NEW;*/
/*RUN;*/
/*OPTIONS PAGENO=1;*/
/*PROC PRINT SPLIT='/' DATA=ONELINK N="TOTAL:  " ;*/
/*BY USER_ID;*/
/*LABEL COMMENTS = 'Comments';*/
/*VAR COMMENTS;*/
/*FORMAT COMMENTS $122.;*/
/*TITLE	"Document Services' Comments";*/
/*FOOTNOTE  'JOB = UTLWI03     REPORT = UTLWI03_ONELINK_ACTIVITY_COMMENTS';*/
/*RUN;*/
/*PROC PRINTTO;*/
/*RUN;*/
/*-----------------------------COMPASS DETAIL REPORT-----------------------------*/
/*DATA COMPASS (DROP=CMT1-CMT15);*/
/*LENGTH CMT1-CMT15 $ 360.;*/
/*SET COMPASS;*/
/*COMMENTS = TRIM(CMT1)||' '||TRIM(CMT2)||' '||TRIM(CMT3)||' '||TRIM(CMT4)||' '||TRIM(CMT5)||' '||*/
/*		   TRIM(CMT6)||' '||TRIM(CMT7)||' '||TRIM(CMT8)||' '||TRIM(CMT9)||' '||TRIM(CMT10)||' '||*/
/*	       TRIM(CMT11)||' '||TRIM(CMT12)||' '||TRIM(CMT13)||' '||TRIM(CMT14)||' '||TRIM(CMT15);		   */
/*COMMENTS = TRIM(COMMENTS);*/
/*RUN;*/
/*PROC SORT DATA = COMPASS;*/
/*BY USER_ID ACTION_CODE SSN ;*/
/*RUN;*/
/*PROC PRINTTO PRINT="&RPTLIB/UTLWI03_COMPASS_ACTIVITY" NEW;*/
/*RUN;*/
/*OPTIONS ORIENTATION = LANDSCAPE;*/
/*OPTIONS PS = 39 LS = 128;*/
/*OPTIONS CENTER NODATE NUMBER PAGENO=1 LS=132;*/
/*PROC REPORT DATA= COMPASS HEADSKIP SPLIT='*' NOWD;*/
/*TITLE	"Document Services' Activity History Entries - COMPASS";*/
/*TITLE2 "RUN DATE: &RUNDT";*/
/*FOOTNOTE 'JOB = UTLWI03     REPORT = ULWI03.LWI03R5';*/
/*COLUMN USER_ID ACTION_CODE ACTION_CODE_DESCRIPTION ACTIVITY_TYPE RESPONSE_CODE SSN DATE */
/*COMMENTS;*/
/*DEFINE USER_ID / DISPLAY "USER ID" WIDTH=9;*/
/*DEFINE ACTION_CODE /  "ACTION*CODE" WIDTH=6;*/
/*DEFINE ACTION_CODE_DESCRIPTION /  "ACTION CODE*DESCRIPTION" WIDTH=15;*/
/*DEFINE ACTIVITY_TYPE /  "ACTIVITY*TYPE" WIDTH=8;*/
/*DEFINE RESPONSE_CODE /  "RESPONSE*CODE" WIDTH=8;*/
/*DEFINE SSN /  'SSN';*/
/*DEFINE DATE /  'DATE' FORMAT=MMDDYY10.;*/
/*DEFINE COMMENTS / DISPLAY WIDTH=50 FLOW;*/
/*RUN;*/
/*PROC PRINTTO;*/
/*RUN;*/
