/*-----------------------------------------*
| UTLWK19 SKIPS WITH VALID EMAIL - COMPASS |
*-----------------------------------------*/
LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
%LET RPTLIB = %SYSGET(reportdir);
%LET PROGREVW = /sas/whse/progrevw;
/*%LET RPTLIB = T:\SAS;*/
/*%LET PROGREVW = Q:\Support Services\Test Files\SAS\PROGREVW;*/
FILENAME REPORT2 "&RPTLIB/ULWK19.LWK19R2";
FILENAME REPORTZ "&RPTLIB/ULWK19.LWK19RZ";
DATA _NULL_;
     CALL SYMPUT('DTE',"'"||PUT(INTNX('DAY',TODAY(),-45,'BEGINNING'), MMDDYYD10.)||"'");
RUN;

/*%SYSLPUT DTE = &DTE;*/

LIBNAME PROGREVW "&PROGREVW";

PROC SQL NOPRINT;
	SELECT 
		"'"||STRIP(LENDER_ID)||"'" INTO :INCL_LIST SEPARATED BY ","
	FROM 
		PROGREVW.LENDER_GROUP_LENDERS
	WHERE 
		LENDER_GROUP_ID = 3
	;
QUIT;
%PUT &INCL_LIST;

/*%SYSLPUT INCL_LIST = &INCL_LIST;*/
/*LIBNAME  WORKLOCL  REMOTE  SERVER=DUSTER  SLIBREF=WORK;*/
/*RSUBMIT;*/
%MACRO SQLCHECK (SQLRPT= );
%IF &SQLXRC NE 0 %THEN %DO;
	DATA _NULL_;
    FILE REPORTZ NOTITLES;
    PUT @01 " ********************************************************************* "
      / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
      / @01 " ****  THE SAS LOG IN &SQLRPT SHOULD BE REVIEWED.          **** "       
      / @01 " ********************************************************************* "
      / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
      / @01 " ****  &SQLXMSG   **** "
      / @01 " ********************************************************************* ";
	RUN;
%END;
%MEND;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE BASE AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT 
		B.DF_PRS_ID AS SSN
		,DX_ADR_EML
FROM	OLWHRM1.PD27_PRS_SKP_PRC A
		INNER JOIN OLWHRM1.PD32_PRS_ADR_EML B
			ON A.DF_PRS_ID = B.DF_PRS_ID
		INNER JOIN OLWHRM1.DW01_DW_CLC_CLU C
			ON A.DF_PRS_ID = C.BF_SSN 
			AND C.WC_DW_LON_STA NOT IN ('16', '17', '18', '19', '20','21', '22')
		JOIN OLWHRM1.LN10_LON LN10
			ON C.BF_SSN = LN10.BF_SSN
			AND C.LN_SEQ = LN10.LN_SEQ
			AND LN10.LF_LON_CUR_OWN IN (&INCL_LIST)
WHERE 	B.DI_VLD_ADR_EML = 'Y' 
			AND A.DC_STA_SKP = '2'
			AND B.DC_STA_PD32 = 'A'
FOR READ ONLY WITH UR
);

/*----------- ADDRESS SKIP -----------*/
CREATE TABLE ASKIP AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT
		A.DF_PRS_ID AS SSN
		,'A' AS SKP
FROM 	OLWHRM1.PD30_PRS_ADR A
		INNER JOIN OLWHRM1.PD42_PRS_PHN B
			ON A.DF_PRS_ID = B.DF_PRS_ID
		INNER JOIN OLWHRM1.PD32_PRS_ADR_EML C
			ON B.DF_PRS_ID = C.DF_PRS_ID
		INNER JOIN OLWHRM1.DW01_DW_CLC_CLU D
			ON A.DF_PRS_ID = D.BF_SSN 
			AND D.WC_DW_LON_STA NOT IN ('16', '17', '18', '19', '20','21', '22')
		JOIN OLWHRM1.LN10_LON LN10
			ON D.BF_SSN = LN10.BF_SSN
			AND D.LN_SEQ = LN10.LN_SEQ
			AND LN10.LF_LON_CUR_OWN IN (&INCL_LIST)
WHERE 	A.DC_ADR = 'L'
			AND A.DI_VLD_ADR = 'N'
			AND B.DI_PHN_VLD = 'Y'
			AND B.DC_PHN = 'H'
			AND C.DI_VLD_ADR_EML = 'Y'
FOR READ ONLY WITH UR
);

/*----------- PHONE SKIP -----------*/
CREATE TABLE PSKIP AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT 
		A.DF_PRS_ID AS SSN
		,'P' AS SKP
FROM 	OLWHRM1.PD30_PRS_ADR A
		INNER JOIN OLWHRM1.PD42_PRS_PHN B
			ON A.DF_PRS_ID = B.DF_PRS_ID
		INNER JOIN OLWHRM1.PD32_PRS_ADR_EML C
			ON B.DF_PRS_ID = C.DF_PRS_ID
		INNER JOIN OLWHRM1.DW01_DW_CLC_CLU D
			ON A.DF_PRS_ID = D.BF_SSN 
			AND D.WC_DW_LON_STA NOT IN ('16', '17', '18', '19', '20','21', '22')
		JOIN OLWHRM1.LN10_LON LN10
			ON D.BF_SSN = LN10.BF_SSN
			AND D.LN_SEQ = LN10.LN_SEQ
			AND LN10.LF_LON_CUR_OWN IN (&INCL_LIST)
WHERE 	A.DC_ADR = 'L'
			AND A.DI_VLD_ADR = 'Y'
			AND B.DI_PHN_VLD = 'N'
			AND B.DC_PHN = 'H'
			AND C.DI_VLD_ADR_EML = 'Y'
FOR READ ONLY WITH UR
);

/*------------ BOTH SKIP ------------*/
CREATE TABLE BSKIP AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT 
		A.DF_PRS_ID AS SSN
		,'B' AS SKP
FROM	 OLWHRM1.PD30_PRS_ADR A
		INNER JOIN OLWHRM1.PD42_PRS_PHN B
			ON A.DF_PRS_ID = B.DF_PRS_ID
		INNER JOIN OLWHRM1.PD32_PRS_ADR_EML C
			ON B.DF_PRS_ID = C.DF_PRS_ID
		INNER JOIN OLWHRM1.DW01_DW_CLC_CLU D
			ON A.DF_PRS_ID = D.BF_SSN 
			AND D.WC_DW_LON_STA NOT IN ('16', '17', '18', '19', '20','21', '22')
		JOIN OLWHRM1.LN10_LON LN10
			ON D.BF_SSN = LN10.BF_SSN
			AND D.LN_SEQ = LN10.LN_SEQ
			AND LN10.LF_LON_CUR_OWN IN (&INCL_LIST)
WHERE 	A.DC_ADR = 'L'
			AND A.DI_VLD_ADR = 'N'
			AND B.DI_PHN_VLD = 'N'
			AND B.DC_PHN = 'H'
			AND C.DI_VLD_ADR_EML = 'Y'
FOR READ ONLY WITH UR
);

/*------- EXCLUSION DATA SETS -------*/
CREATE TABLE X1 AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT 	DF_PRS_ID AS SSN
FROM 	OLWHRM1.AY01_BR_ATY 
WHERE	PF_ACT = 'KEMAL'
		AND BD_ATY_PRF >= &DTE
FOR READ ONLY WITH UR
);

CREATE TABLE X2 AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT 	DF_PRS_ID_BR AS SSN
FROM 	OLWHRM1.CT30_CALL_QUE 
WHERE 	IF_WRK_GRP = 'KSKEMAIL'
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;

	/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>>  ;  * INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
	/*%SQLCHECK (SQLRPT=ULWK19.LWK19RZ);*/
QUIT;

DATA SKP_TYP;
SET ASKIP PSKIP BSKIP;
RUN;

DATA EX;
SET X1 X2;
RUN;

PROC SQL;
CREATE TABLE COMSVEAD AS 
SELECT DISTINCT A.SSN
	,A.DX_ADR_EML
	,B.SKP
FROM BASE A
LEFT OUTER JOIN SKP_TYP B
	ON A.SSN = B.SSN
WHERE A.SSN NOT IN (
	SELECT DISTINCT SSN
	FROM EX
	)
ORDER BY SSN
;
QUIT;
/*ENDRSUBMIT;*/
/**/
/*DATA COMSVEAD;*/
/*SET WORKLOCL.COMSVEAD;*/
/*RUN;*/

DATA COMSVEAD (KEEP=TARGET_ID QUEUE_NAME INSTITUTION_ID INSTITUTION_TYPE DATE_DUE TIME_DUE COMMENTS);
SET COMSVEAD ;
LENGTH COMMENTS $ 600.;
TARGET_ID = SSN;
QUEUE_NAME = 'KSKEMAIL';
INSTITUTION_ID = '';
INSTITUTION_TYPE = '';
DATE_DUE = '';
TIME_DUE = '';
COMMENTS = 'Compass Email: '||TRIM(LEFT(DX_ADR_EML))||','||'Skip type: '||TRIM(LEFT(SKP));
RUN;

DATA _NULL_;
SET  WORK.COMSVEAD; 
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
   FORMAT COMMENTS $600. ;
   FORMAT TARGET_ID $9. ;
   FORMAT QUEUE_NAME $8. ;
   FORMAT INSTITUTION_ID $1. ;
   FORMAT INSTITUTION_TYPE $1. ;
   FORMAT DATE_DUE $1. ;
   FORMAT TIME_DUE $1. ;
DO;
	PUT TARGET_ID $ @;
	PUT QUEUE_NAME $ @;
	PUT INSTITUTION_ID $ @;
	PUT INSTITUTION_TYPE $ @;
	PUT DATE_DUE $ @;
	PUT TIME_DUE $ @;
	PUT COMMENTS $ ;
END;
RUN;
