//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public Entity()
        {
            this.AttributeAllowedValues = new HashSet<AttributeAllowedValue>();
            this.AttributeAllowedValues1 = new HashSet<AttributeAllowedValue>();
            this.AttributeAllowedValuesHistories = new HashSet<AttributeAllowedValuesHistory>();
            this.AttributeAllowedValuesHistories1 = new HashSet<AttributeAllowedValuesHistory>();
            this.Attributes = new HashSet<Attribute>();
            this.Attributes1 = new HashSet<Attribute>();
            this.AttributeSelectionTypes = new HashSet<AttributeSelectionType>();
            this.AttributeSelectionTypes1 = new HashSet<AttributeSelectionType>();
            this.Entities11 = new HashSet<Entity>();
            this.EntityAttributeValues = new HashSet<EntityAttributeValue>();
            this.EntityAttributeValues1 = new HashSet<EntityAttributeValue>();
            this.EntityAttributeValuesHistories = new HashSet<EntityAttributeValuesHistory>();
            this.EntityAttributeValuesHistories1 = new HashSet<EntityAttributeValuesHistory>();
            this.EntityTypeAttributes = new HashSet<EntityTypeAttribute>();
            this.EntityTypeAttributes1 = new HashSet<EntityTypeAttribute>();
            this.EntityTypes = new HashSet<EntityType>();
            this.EntityTypes1 = new HashSet<EntityType>();
            this.PermissionTypes = new HashSet<PermissionType>();
            this.PermissionTypes1 = new HashSet<PermissionType>();
            this.RoleAttributePermissions = new HashSet<RoleAttributePermission>();
            this.RoleAttributePermissions1 = new HashSet<RoleAttributePermission>();
        }
    
        public int EntityId { get; set; }
        public int EntityTypeId { get; set; }
        public string EntityName { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> InactivatedAt { get; set; }
        public Nullable<int> InactivatedBy { get; set; }
        private Nullable<bool> InternalActive { get; set; }
    
        public virtual ICollection<AttributeAllowedValue> AttributeAllowedValues { get; set; }
        public virtual ICollection<AttributeAllowedValue> AttributeAllowedValues1 { get; set; }
        public virtual ICollection<AttributeAllowedValuesHistory> AttributeAllowedValuesHistories { get; set; }
        public virtual ICollection<AttributeAllowedValuesHistory> AttributeAllowedValuesHistories1 { get; set; }
        public virtual ICollection<Attribute> Attributes { get; set; }
        public virtual ICollection<Attribute> Attributes1 { get; set; }
        public virtual ICollection<AttributeSelectionType> AttributeSelectionTypes { get; set; }
        public virtual ICollection<AttributeSelectionType> AttributeSelectionTypes1 { get; set; }
        public virtual ICollection<Entity> Entities11 { get; set; }
        public virtual Entity Entity2 { get; set; }
        public virtual EntityType EntityType { get; set; }
        public virtual ICollection<EntityAttributeValue> EntityAttributeValues { get; set; }
        public virtual ICollection<EntityAttributeValue> EntityAttributeValues1 { get; set; }
        public virtual ICollection<EntityAttributeValuesHistory> EntityAttributeValuesHistories { get; set; }
        public virtual ICollection<EntityAttributeValuesHistory> EntityAttributeValuesHistories1 { get; set; }
        public virtual ICollection<EntityTypeAttribute> EntityTypeAttributes { get; set; }
        public virtual ICollection<EntityTypeAttribute> EntityTypeAttributes1 { get; set; }
        public virtual ICollection<EntityType> EntityTypes { get; set; }
        public virtual ICollection<EntityType> EntityTypes1 { get; set; }
        public virtual ICollection<PermissionType> PermissionTypes { get; set; }
        public virtual ICollection<PermissionType> PermissionTypes1 { get; set; }
        public virtual ICollection<RoleAttributePermission> RoleAttributePermissions { get; set; }
        public virtual ICollection<RoleAttributePermission> RoleAttributePermissions1 { get; set; }
    }
}
