//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryStatusType
    {
        public HistoryStatusType()
        {
            this.EntityAttributeValuesHistories = new HashSet<EntityAttributeValuesHistory>();
        }
    
        public int HistoryStatusTypeId { get; set; }
        public string HistoryStatusTypeDescription { get; set; }
    
        public virtual ICollection<EntityAttributeValuesHistory> EntityAttributeValuesHistories { get; set; }
    }
}
