/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/ULWGG8.LWGG8RZ";
FILENAME REPORT2 "&RPTLIB/ULWGG8.LWGG8R2";
LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
%MACRO SQLCHECK ;
  %IF  &SQLXRC NE 0  %THEN  %DO  ;
    DATA _NULL_  ;
            FILE REPORTZ NOTITLES  ;
            PUT @01 " ********************************************************************* "
              / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
              / @01 " ****  THE SAS SHOULD BE REVIEWED.                                **** "       
              / @01 " ********************************************************************* "
              / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
              / @01 " ****  &SQLXMSG   **** "
              / @01 " ********************************************************************* "
            ;
         RUN  ;
  %END  ;
%MEND  ;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE DEMO AS
SELECT A.DF_PRS_ID_STU AS BF_SSN
FROM DLGSUTWH.SD02_STU_ENR A
INNER JOIN DLGSUTWH.GA01_APP B
	 ON A.DF_PRS_ID_STU = B.DF_PRS_ID_BR
INNER JOIN DLGSUTWH.GA10_LON_APP C
	ON B.AF_APL_ID = C.AF_APL_ID
LEFT OUTER JOIN DLGSUTWH.PD01_PDM_INF D
	ON A.DF_PRS_ID_STU = D.DF_PRS_ID
WHERE A.LD_ENR_CER >= TODAY() - 1
	AND A.LC_STA_SD02 = 'A'
	AND C.AF_CUR_LON_OPS_LDR IN ('826717','829769','830248')
	AND A.DF_PRS_ID_STU NOT IN (SELECT DF_PRS_ID_BR
					FROM  DLGSUTWH.CT30_CALL_QUE 
					WHERE IF_WRK_GRP = 'LINKING')
;
DISCONNECT FROM DB2;

/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>> ;  ** INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK;*/
/*QUIT;*/

ENDRSUBMIT;
DATA DEMO;
	SET WORKLOCL.DEMO;
RUN;
PROC SORT DATA=DEMO NODUPKEY;
	BY BF_SSN ;
RUN;

DATA _NULL_;
SET DEMO ;
LENGTH COMMENTS $ 600.;
QUEUE_NAME = 'LINKING';
INSTITUTION_ID = '';
INSTITUTION_TYPE = '';
DATE_DUE = '';
TIME_DUE = '';
COMMENTS = '';
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
DO;
	PUT BF_SSN $ @;
	PUT QUEUE_NAME $ @;
	PUT INSTITUTION_ID $ @;
	PUT INSTITUTION_TYPE $ @;
	PUT DATE_DUE $ @;
	PUT TIME_DUE $ @;
	PUT COMMENTS $ ;
END;
RUN;
