CREATE PROCEDURE [payoff].[GetCoborrowerLoanInformation]
	@AccountNumber VARCHAR(10)
AS
SET NOCOUNT ON;

BEGIN
	SELECT
		ROW_NUMBER() OVER (PARTITION BY LN10.BF_SSN ORDER BY LN10.BF_SSN, LN10.LN_SEQ ASC) AS RowId, 
		LN20.LF_EDS AS CoborrowerSSN,
		LN10.LN_SEQ AS LoanSequence,
		CONVERT(VARCHAR(16), CAST(LN10.LA_CUR_PRI AS MONEY), 2) AS CurrentPrincipal,
		LN10.IC_LON_PGM AS LoanProgram
	FROM
		UDW..PD10_PRS_NME PD10
		INNER JOIN LN20_EDS LN20
				ON LN20.BF_SSN = PD10.DF_PRS_ID
				AND LN20.LC_STA_LON20 = 'A'
				AND LN20.LC_EDS_TYP = 'M' --Coborrower
		INNER JOIN UDW..LN10_LON LN10
			ON LN10.BF_SSN = LN20.BF_SSN
			AND LN10.LN_SEQ = LN20.LN_SEQ
	WHERE
		PD10.DF_SPE_ACC_ID = @AccountNumber
		AND LN10.LA_CUR_PRI > 0
		AND LN10.LC_STA_LON10 IN ('I','J','P','R')
END


RETURN 0
