/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/ULWG95.LWG95R2";
FILENAME REPORT3 "&RPTLIB/ULWG95.LWG95R3";
FILENAME REPORTZ "&RPTLIB/ULWG95.LWG95RZ";

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;

%macro sqlcheck ;
  %if  &sqlxrc ne 0  %then  %do  ;
    data _null_  ;
            file reportz notitles  ;
            put @01 " ********************************************************************* "
              / @01 " ****  The SQL code above has experienced an error.               **** "
              / @01 " ****  The SAS should be reviewed.                                **** "       
              / @01 " ********************************************************************* "
              / @01 " ****  The SQL error code is  &sqlxrc  and the SQL error message  **** "
              / @01 " ****  &sqlxmsg   **** "
              / @01 " ********************************************************************* "
            ;
         run  ;
  %end  ;
%mend  ;


PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE PLUS AS
SELECT *
FROM CONNECTION TO DB2 (

SELECT 
	DAYS(A.AD_PRC) - DAYS(CURRENT DATE) AS DAYS_CNT
	,D.DF_SPE_ACC_ID AS B_ACCN
	,E.DF_SPE_ACC_ID AS E_ACCN
	,A.AA_GTE_LON_AMT AS AMT
	,A.AD_PRC
	,C.AC_LON_STA_TYP 

FROM	OLWHRM1.GA10_LON_APP A
INNER JOIN OLWHRM1.GA01_APP B
	ON A.AF_APL_ID = B.AF_APL_ID
INNER JOIN OLWHRM1.GA14_LON_STA C
	ON A.AF_APL_ID = C.AF_APL_ID
	AND A.AF_APL_ID_SFX = C.AF_APL_ID_SFX
INNER JOIN OLWHRM1.PD01_PDM_INF D
	ON B.DF_PRS_ID_BR = D.DF_PRS_ID
INNER JOIN OLWHRM1.PD01_PDM_INF E
	ON B.DF_PRS_ID_EDS = E.DF_PRS_ID
WHERE A.AC_LON_TYP IN ('PL','GB')
AND C.AF_CRT_DTS_GA14 IN (SELECT MAX(ZZ.AF_CRT_DTS_GA14) FROM OLWHRM1.GA14_LON_STA ZZ WHERE ZZ.AF_APL_ID = C.AF_APL_ID AND ZZ.AF_APL_ID_SFX = C.AF_APL_ID_SFX )
AND A.AC_PRC_STA = 'A'
AND A.AD_PRC >= '09/01/2006'
AND B.AC_EDS_TYP = 'E'
AND C.AC_LON_STA_TYP <> 'CP'


FOR READ ONLY WITH UR

);
DISCONNECT FROM DB2;

/*%put  sqlxrc= >>> &sqlxrc <<< ||| sqlxmsg= >>> &sqlxmsg >>> ;  ** includes error messages to SAS log  ;*/
/*%sqlcheck;*/
/*quit;*/

ENDRSUBMIT;

DATA PLUS; SET WORKLOCL.PLUS; RUN;

PROC SORT DATA=PLUS;
BY AD_PRC;
RUN;

DATA PLUS_CURR PLUS_HIST;
SET PLUS;
IF DAYS_CNT = 1 THEN OUTPUT PLUS_CURR;
ELSE OUTPUT PLUS_HIST;
RUN;

PROC PRINTTO PRINT=REPORT2;
RUN;

/*For portrait reports;*/
OPTIONS ORIENTATION = PORTRAIT;
OPTIONS CENTER NODATE NUMBER PAGENO=1 PS=52 LS=96;
PROC CONTENTS DATA=PLUS_CURR OUT=EMPTYSET NOPRINT;
DATA _NULL_;
SET EMPTYSET;
FILE PRINT;
IF  NOBS=0 AND _N_ =1 THEN DO;
	PUT // 90*'-';
	PUT      ////////
		@35 '**** NO RECORDS FOUND ****';
	PUT ////////
		@38 '-- END OF REPORT --';
	PUT ////////////////
		@27 "JOB = UTLWG95     REPORT = ULWG95.LWG95R2";
	END;
RETURN;
TITLE "PLUS With Endorsers";
TITLE2 'Guaranteed Previous Day';
RUN;
PROC PRINT NOOBS SPLIT='/' DATA=PLUS_CURR;
FORMAT AMT DOLLAR10.2;
FORMAT AD_PRC MMDDYY10.;

VAR B_ACCN E_ACCN AMT AD_PRC AC_LON_STA_TYP;
LABEL	B_ACCN = 'BORROWER ACC#'
		E_ACCN = 'ENDORSER ACC#'
		AMT = 'AMOUNT'
		AD_PRC = 'GUARANTEED DATE'
		AC_LON_STA_TYP = 'STATUS';

TITLE "PLUS With Endorsers";
TITLE2 'Guaranteed Previous Day';
FOOTNOTE  'JOB = UTLWG95     REPORT = UTLWG95.LWG95R2';
RUN;

PROC PRINTTO PRINT=REPORT3;
RUN;

OPTIONS ORIENTATION = PORTRAIT;
OPTIONS CENTER NODATE NUMBER PAGENO=1 PS=52 LS=96;
PROC CONTENTS DATA=PLUS_HIST OUT=EMPTYSET NOPRINT;
DATA _NULL_;
SET EMPTYSET;
FILE PRINT;
IF  NOBS=0 AND _N_ =1 THEN DO;
	PUT // 90*'-';
	PUT      ////////
		@35 '**** NO RECORDS FOUND ****';
	PUT ////////
		@38 '-- END OF REPORT --';
	PUT ////////////////
		@27 "JOB = UTLWG95     REPORT = ULWG95.LWG95R3";
	END;
RETURN;
TITLE "PLUS With Endorsers";
TITLE2 'Historical';
RUN;
PROC PRINT NOOBS SPLIT='/' DATA=PLUS_HIST;
FORMAT AMT DOLLAR10.2 AD_PRC DATE9.;
FORMAT AD_PRC MMDDYY10.;

VAR B_ACCN E_ACCN AMT AD_PRC AC_LON_STA_TYP;
LABEL	B_ACCN = 'BORROWER ACC#'
		E_ACCN = 'ENDORSER ACC#'
		AMT = 'AMOUNT'
		AD_PRC = 'GUARANTEED DATE'
		AC_LON_STA_TYP = 'STATUS';

TITLE "PLUS With Endorsers";
TITLE2 'Historical';
FOOTNOTE  'JOB = UTLWG95     REPORT = UTLWG95.LWG95R3';
RUN;

PROC PRINTTO;
RUN;
