/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/ULWS47.LWS47RZ";
FILENAME REPORT2 "&RPTLIB/ULWS47.LWS47R2";
FILENAME REPORT3 "&RPTLIB/ULWS47.LWS47R3";
FILENAME REPORT4 "&RPTLIB/ULWS47.LWS47R4";
FILENAME REPORT5 "&RPTLIB/ULWS47.LWS47R5";
LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
%MACRO SQLCHECK ;
  %IF  &SQLXRC NE 0  %THEN  %DO  ;
    DATA _NULL_  ;
            FILE REPORTZ NOTITLES  ;
            PUT @01 " ********************************************************************* "
              / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
              / @01 " ****  THE SAS SHOULD BE REVIEWED.                                **** "       
              / @01 " ********************************************************************* "
              / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
              / @01 " ****  &SQLXMSG   **** "
              / @01 " ********************************************************************* "
            ;
         RUN  ;
  %END  ;
%MEND  ;

PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE DEMO AS
select *
FROM CONNECTION TO DB2 (
SELECT DISTINCT C.DF_SPE_ACC_ID
	,TRIM(C.DM_PRS_1 ) || ' ' || TRIM (C.DM_PRS_LST) AS NAME
	,C.DX_EML_ADR
	,E.PF_ACT
FROM OLWHRM1.PD01_PDM_INF C
INNER JOIN OLWHRM1.PD03_PRS_ADR_PHN D
	ON C.DF_PRS_ID = D.DF_PRS_ID
INNER JOIN OLWHRM1.AY01_BR_ATY E
	ON C.DF_PRS_ID = E.DF_PRS_ID
LEFT OUTER JOIN OLWHRM1.AY01_BR_ATY F
	ON C.DF_PRS_ID = F.DF_PRS_ID
	AND F.PF_ACT IN ('DEM01','DEM02','DEM03','DEM04')
	and substr(f.pf_act,5,1) = substr(e.pf_act,5,1)
	AND f.BD_ATY_PRF >= E.BD_ATY_PRF

INNER JOIN OLWHRM1.DC01_LON_CLM_INF A
	ON C.DF_PRS_ID = A.BF_SSN
LEFT OUTER JOIN (SELECT B.LC_TRX_TYP
			,B.AF_APL_ID
			,B.AF_APL_ID_SFX
		FROM OLWHRM1.DC11_LON_FAT B
		WHERE DAYS(B.LD_TRX_EFF) = (SELECT MAX(DAYS(E.LD_TRX_EFF)) AS LD_TRX_EFF
					FROM OLWHRM1.DC11_LON_FAT E
					WHERE B.AF_APL_ID = E.AF_APL_ID
						AND B.AF_APL_ID_SFX = E.AF_APL_ID_SFX
					GROUP BY E.AF_APL_ID
						,E.AF_APL_ID_SFX)
			AND B.LC_TRX_TYP IN ('BR')
)	B
	ON A.AF_APL_ID = B.AF_APL_ID
	AND A.AF_APL_ID_SFX = B.AF_APL_ID_SFX
WHERE A.LC_STA_DC10 = '03'
	AND A.LC_AUX_STA = ''
	AND A.LI_DFL_LTR_1_IVL IS NOT NULL
	AND D.DI_EML_ADR_VAL = 'Y'
	AND (A.LD_LST_PAY IS NULL 
		OR B.LC_TRX_TYP NOT IN ('BR'))
	AND E.PF_ACT IN ('DLDF1','DLDF2','DLDF3','DLDF4')
	AND DAYS(E.BD_ATY_PRF) >= DAYS(CURRENT DATE) - 15
	and F.DF_PRS_ID is null

FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;

/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>> ;  ** INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK;*/
QUIT;
ENDRSUBMIT;
DATA DEMO;
	SET WORKLOCL.DEMO;
RUN; 

PROC SORT DATA=DEMO NODUPKEY;
	BY DF_SPE_ACC_ID PF_ACT ;
RUN;
%MACRO REPORTS(R,IN);
DATA _NULL_;
SET DEMO ;
WHERE PF_ACT = &IN ;
FILE REPORT&R DELIMITER=',' DSD DROPOVER LRECL=32767;
IF _N_ = 1 THEN DO;
	PUT "ACCOUNTNUMBER,NAME,RECIPIENT";
END;
DO;
   PUT DF_SPE_ACC_ID $ @;
   PUT NAME @;
   PUT DX_EML_ADR $ ;
END;
RUN;
%MEND;
%REPORTS(2,'DLDF1');
%REPORTS(3,'DLDF2');
%REPORTS(4,'DLDF3');
%REPORTS(5,'DLDF4');
