USE CLS
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [tlfqcfed].[TeacherLoanForgivenessFSA](
	[TeacherLoanForgivenessFSAId] [int] IDENTITY(1,1) NOT NULL,
	[DF_SPE_ACC_ID] [char](10) NOT NULL,
	[PF_REQ_ACT] [char](5) NOT NULL,
	[LD_ATY_REQ_RCV] [datetime] NOT NULL,
	[LC_STA_ACTY10] [char](1) NOT NULL,
	[LF_LST_DTS_AY10] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TeacherLoanForgivenessFSAId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
