--clear table
DELETE FROM	CLS.tlfqcfed.TeacherLoanForgivenessFSA

--repopulate table with active tasks
INSERT INTO CLS.tlfqcfed.TeacherLoanForgivenessFSA
	(
		DF_SPE_ACC_ID,
		PF_REQ_ACT,
		LD_ATY_REQ_RCV,
		LC_STA_ACTY10,
		LF_LST_DTS_AY10
	)
SELECT 
	PD10.DF_SPE_ACC_ID,
	AY10.PF_REQ_ACT,
	AY10.LD_ATY_REQ_RCV,
	AY10.LC_STA_ACTY10,
	AY10.LF_LST_DTS_AY10
FROM
	CDW..PD10_PRS_NME PD10
	INNER JOIN CDW..AY10_BR_LON_ATY AY10
		ON PD10.DF_PRS_ID = AY10.BF_SSN
	LEFT JOIN
	(
		SELECT
			BF_SSN,
			MAX(CAST(LD_ATY_REQ_RCV AS DATE)) AS MaxApvDny
		FROM
			CDW..AY10_BR_LON_ATY AY10
		WHERE
			AY10.LC_STA_ACTY10 = 'A'
			AND AY10.PF_REQ_ACT IN ('TLDNY', 'ADTLF')
		GROUP BY
			BF_SSN	
	) APR_DNY
		ON PD10.DF_PRS_ID = APR_DNY.BF_SSN
WHERE
	AY10.LC_STA_ACTY10 = 'A'
	AND AY10.PF_REQ_ACT = 'TLFSA'
	AND 
	(
		APR_DNY.BF_SSN IS NULL
		OR AY10.LD_ATY_REQ_RCV >= APR_DNY.MaxApvDny
	)
