/*UTLWK12 - Open Bankruptcy Record - Not Greatest Filing Date*/
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/ULWK12.LWK12R2";
options symbolgen;
LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
%macro sqlcheck ;
  %if  &sqlxrc ne 0  %then  %do  ;
    data _null_  ;
            file reportz notitles  ;
            put @01 " ********************************************************************* "
              / @01 " ****  The SQL code above has experienced an error.               **** "
              / @01 " ****  The SAS should be reviewed.                                **** "       
              / @01 " ********************************************************************* "
              / @01 " ****  The SQL error code is  &sqlxrc  and the SQL error message  **** "
              / @01 " ****  &sqlxmsg   **** "
              / @01 " ********************************************************************* "
            ;
         run  ;
  %end  ;
%mend  ;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE DEMO AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT B.BF_SSN AS SSN
	,A.LF_LST_USR_DC18
	,DATE(A.LF_LST_DTS_DC18) AS LF_LST_DTS_DC18
	,A.AF_APL_ID
	,A.AF_APL_ID_SFX
	,A.LC_BKR_STA
	,A.LD_BKR_FIL
	,A.LF_BKR_DKT
	,C.LF_CLM_ID
	,D.DF_SPE_ACC_ID AS ACCT_NUMBER
FROM	OLWHRM1.DC18_BKR A
INNER JOIN OLWHRM1.DC01_LON_CLM_INF B
ON A.AF_APL_ID = B.AF_APL_ID
AND A.AF_APL_ID_SFX = B.AF_APL_ID_SFX
AND A.LF_CRT_DTS_DC10 = B.LF_CRT_DTS_DC10
LEFT OUTER JOIN OLWHRM1.DC01_LON_CLM_INF C
ON A.AF_APL_ID = C.AF_APL_ID
AND A.AF_APL_ID_SFX = C.AF_APL_ID_SFX
AND A.LF_CRT_DTS_DC10 = C.LF_CRT_DTS_DC10
INNER JOIN OLWHRM1.PD01_PDM_INF D
	ON B.BF_SSN = D.DF_PRS_ID
FOR READ ONLY WITH UR
);

CREATE TABLE DEMO2 AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT A.AF_APL_ID
	,A.AF_APL_ID_SFX
FROM OLWHRM1.DC18_BKR A
WHERE A.LC_BKR_STA = '01'
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
%put  sqlxrc= >>> &sqlxrc <<< ||| sqlxmsg= >>> &sqlxmsg >>> ;  ** includes error messages to SAS log  ;
%sqlcheck;
quit;

DATA DEMO; SET WORKLOCL.DEMO; RUN;
DATA DEMO2; SET WORKLOCL.DEMO2; RUN;

PROC SQL;
CREATE TABLE B2 AS
SELECT DISTINCT SSN
,LF_LST_USR_DC18
,LF_LST_DTS_DC18
,DEMO.AF_APL_ID 
,DEMO.AF_APL_ID_SFX 
,DEMO.AF_APL_ID || DEMO.AF_APL_ID_SFX AS CLUID
,LC_BKR_STA
,LD_BKR_FIL
,LF_BKR_DKT
,DEMO.LF_CLM_ID
,ACCT_NUMBER
FROM DEMO 
INNER JOIN DEMO2
ON DEMO.AF_APL_ID = DEMO2.AF_APL_ID
AND DEMO.AF_APL_ID_SFX = DEMO2.AF_APL_ID_SFX;
QUIT;

ENDRSUBMIT;
DATA B2;
SET WORKLOCL.B2;
RUN;

PROC SQL;
CREATE TABLE SAMEDATE AS
SELECT DISTINCT SSN
,AF_APL_ID
,AF_APL_ID_SFX
,LD_BKR_FIL
, COUNT(*) AS CNT
,ACCT_NUMBER
FROM B2 
GROUP BY SSN, AF_APL_ID, AF_APL_ID_SFX,LD_BKR_FIL;
QUIT;

PROC SQL;
CREATE TABLE SAMEDATE2 AS
SELECT *
FROM SAMEDATE 
WHERE CNT > 1
;
QUIT;

PROC SQL;
CREATE TABLE PENDING AS
SELECT DISTINCT SSN
,AF_APL_ID
,AF_APL_ID_SFX
,LC_BKR_STA
,LD_BKR_FIL
,LF_BKR_DKT
,ACCT_NUMBER
FROM B2 
WHERE LC_BKR_STA = '01';
QUIT;

PROC SQL;
CREATE TABLE PENDING2 AS
SELECT DISTINCT SSN
,AF_APL_ID
,AF_APL_ID_SFX
,MAX(LD_BKR_FIL) AS MAXDT
,ACCT_NUMBER
FROM B2 
GROUP BY SSN, AF_APL_ID, AF_APL_ID_SFX,ACCT_NUMBER;
QUIT;

PROC SQL;
CREATE TABLE PENDING3 AS
SELECT DISTINCT P.*
FROM PENDING P
INNER JOIN PENDING2 P2
ON P.SSN = P2.SSN
AND P.AF_APL_ID = P2.AF_APL_ID
AND P.AF_APL_ID_SFX = P2.AF_APL_ID_SFX
WHERE  LD_BKR_FIL NE MAXDT
;
QUIT;

PROC SQL;
CREATE TABLE FINAL AS
SELECT DISTINCT B2.*
FROM B2 B
INNER JOIN PENDING3 P3
ON B.AF_APL_ID = P3.AF_APL_ID
AND B.AF_APL_ID_SFX = P3.AF_APL_ID_SFX
INNER JOIN SAMEDATE2 S2
ON B.AF_APL_ID = S2.AF_APL_ID
AND B.AF_APL_ID_SFX = S2.AF_APL_ID_SFX
;
QUIT;

DATA FINAL;
SET FINAL;
IF LC_BKR_STA = '01' THEN OUTPUT FINAL;
	ELSE DELETE;
RUN;

PROC SORT DATA=FINAL;
BY ACCT_NUMBER;
RUN;
*The following aliases were used above: DF_SPE_ACC_ID = ACCT_NUMBER;

DATA _NULL_;
SET FINAL ;
LENGTH DESCRIPTION $600.;
USER = LF_LST_USR_DC18;
ACT_DT = LF_LST_DTS_DC18;
DESCRIPTION = CATX(',',
	ACCT_NUMBER,
	PUT(LD_BKR_FIL, MMDDYY10.),
	LF_CLM_ID,
	CLUID,
	LC_BKR_STA,
	PUT(LD_BKR_FIL, MMDDYY10.),
	LF_BKR_DKT);
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
FORMAT USER $10. ;
FORMAT ACT_DT MMDDYY10. ;
FORMAT DESCRIPTION $600. ;
IF _N_ = 1 THEN DO;
	PUT "USER,ACT_DT,DESCRIPTION";
END;
DO;
   PUT USER $ @;
   PUT ACT_DT @;
   PUT DESCRIPTION $ ;
END;
RUN;
