DECLARE @TODAY DATE = GETDATE();
SELECT DISTINCT
	P.AccountNumber AS [Account Number],
	P.AccountNamespace AS [Account Namespace],
	CASE WHEN Bky.AF_APL_ID IS NOT NULL THEN 'Bankruptcy'
		 WHEN Dcv.AF_APL_ID IS NOT NULL THEN 'Closed'
		 WHEN Dth.AF_APL_ID IS NOT NULL THEN 'Closed'
		 WHEN Dis.AF_APL_ID IS NOT NULL THEN 'Closed'
		 WHEN Defr.AF_APL_ID IS NOT NULL THEN 'Closed'
		 WHEN SchClosed.AF_APL_ID IS NOT NULL THEN 'Closed'
		 WHEN FalseCert.AF_APL_ID IS NOT NULL THEN 'Closed'
		 WHEN Sat.AF_APL_ID IS NOT NULL THEN 'Paid'
	END AS [Recall Reason],
	CONVERT(VARCHAR,@TODAY,1) AS [Recall Date],
	CONVERT(VARCHAR,@TODAY,1) AS placementinfo
FROM
	OLS.trueaccord.Placements P
	INNER JOIN ODW..PD01_PDM_INF PD01
		ON PD01.DF_SPE_ACC_ID = P.AccountNumber
	INNER JOIN
	(
		SELECT DISTINCT
			DC01.AF_APL_ID,
			DC01.AF_APL_ID_SFX,
			DC01.BF_SSN,
			MAX(DC01.LF_CRT_DTS_DC10) AS LF_CRT_DTS_DC10
		FROM
			ODW..DC01_LON_CLM_INF DC01
		GROUP BY
			DC01.AF_APL_ID,
			DC01.AF_APL_ID_SFX,
			DC01.BF_SSN
	) DC01
		ON DC01.BF_SSN = PD01.DF_PRS_ID
		AND DC01.AF_APL_ID = P.AF_APL_ID
		AND DC01.AF_APL_ID_SFX = P.AF_APL_ID_SFX
	INNER JOIN ODW..GA14_LON_STA GA14
		ON GA14.AF_APL_ID = DC01.AF_APL_ID
		AND GA14.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND GA14.AC_STA_GA14 = 'A'
		AND GA14.AC_LON_STA_TYP = 'CP'
	LEFT JOIN ODW..DC01_LON_CLM_INF Bky
		ON Bky.AF_APL_ID = DC01.AF_APL_ID
		AND Bky.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND Bky.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND 
		(
			Bky.LC_PCL_REA IN('BC','BO')
			OR Bky.LC_AUX_STA = '07'
		)
	LEFT JOIN ODW..DC01_LON_CLM_INF Dcv
		ON Dcv.AF_APL_ID = DC01.AF_APL_ID
		AND Dcv.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND Dcv.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND ISNULL(Dcv.LD_CLM_ASN_DOE,'') != ''
		AND ISNULL(Dcv.LC_REA_CLM_ASN_DOE,'') != ''
	LEFT JOIN ODW..DC01_LON_CLM_INF Sat
		ON Sat.AF_APL_ID = DC01.AF_APL_ID
		AND Sat.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND Sat.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND 
		(
			Sat.LC_STA_DC10 = '04'
			OR Sat.LC_AUX_STA IN('01','06','10','11','12')
		)
	LEFT JOIN ODW..DC01_LON_CLM_INF Dth
		ON Dth.AF_APL_ID = DC01.AF_APL_ID
		AND Dth.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND Dth.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND 
		(
			Dth.LC_PCL_REA = 'DE'
			OR Dth.LC_AUX_STA = '02'
		)
	LEFT JOIN ODW..DC01_LON_CLM_INF Dis
		ON Dis.AF_APL_ID = DC01.AF_APL_ID
		AND Dis.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND Dis.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND 
		(
			Dis.LC_PCL_REA = 'DI'
			OR Dis.LC_AUX_STA = '03'
		)
	LEFT JOIN ODW..DC01_LON_CLM_INF Defr
		ON Defr.AF_APL_ID = DC01.AF_APL_ID
		AND Defr.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND Defr.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND Defr.LC_AUX_STA = '05'
	LEFT JOIN ODW..DC01_LON_CLM_INF SchClosed
		ON SchClosed.AF_APL_ID = DC01.AF_APL_ID
		AND SchClosed.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND SchClosed.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND SchClosed.LC_AUX_STA = '08'
	LEFT JOIN ODW..DC01_LON_CLM_INF FalseCert
		ON FalseCert.AF_APL_ID = DC01.AF_APL_ID
		AND FalseCert.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND FalseCert.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND FalseCert.LC_AUX_STA = '09'
WHERE
	P.DeletedAt IS NULL
	AND 
	(
		P.RetractedAt IS NULL
		OR CAST(P.RetractedAt AS DATE) = @TODAY
	)
	AND
	(
		Bky.AF_APL_ID IS NOT NULL
		OR Dcv.AF_APL_ID IS NOT NULL
		OR Sat.AF_APL_ID IS NOT NULL
		OR Dth.AF_APL_ID IS NOT NULL
		OR Dis.AF_APL_ID IS NOT NULL
		OR Defr.AF_APL_ID IS NOT NULL
		OR SchClosed.AF_APL_ID IS NOT NULL
		OR FalseCert.AF_APL_ID IS NOT NULL
	)


UPDATE
	P
SET
	P.RetractedAt = GETDATE(),
	P.RetractedBy = CASE WHEN Bky.AF_APL_ID IS NOT NULL THEN 'Bankruptcy'
		 WHEN Dcv.AF_APL_ID IS NOT NULL THEN 'Deconverted'
		 WHEN Dth.AF_APL_ID IS NOT NULL THEN 'Death'
		 WHEN Dis.AF_APL_ID IS NOT NULL THEN 'Disability'
		 WHEN Defr.AF_APL_ID IS NOT NULL THEN 'Deferred'
		 WHEN SchClosed.AF_APL_ID IS NOT NULL THEN 'School Closure'
		 WHEN FalseCert.AF_APL_ID IS NOT NULL THEN 'False Certification'
		 WHEN Sat.AF_APL_ID IS NOT NULL THEN 'Paid'
	END
FROM
	OLS.trueaccord.Placements P
	INNER JOIN ODW..PD01_PDM_INF PD01
		ON PD01.DF_SPE_ACC_ID = P.AccountNumber
	INNER JOIN
	(
		SELECT DISTINCT
			DC01.AF_APL_ID,
			DC01.AF_APL_ID_SFX,
			DC01.BF_SSN,
			MAX(DC01.LF_CRT_DTS_DC10) AS LF_CRT_DTS_DC10
		FROM
			ODW..DC01_LON_CLM_INF DC01
		GROUP BY
			DC01.AF_APL_ID,
			DC01.AF_APL_ID_SFX,
			DC01.BF_SSN
	) DC01
		ON DC01.BF_SSN = PD01.DF_PRS_ID
		AND DC01.AF_APL_ID = P.AF_APL_ID
		AND DC01.AF_APL_ID_SFX = P.AF_APL_ID_SFX
	INNER JOIN ODW..GA14_LON_STA GA14
		ON GA14.AF_APL_ID = DC01.AF_APL_ID
		AND GA14.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND GA14.AC_STA_GA14 = 'A'
		AND GA14.AC_LON_STA_TYP = 'CP'
	LEFT JOIN ODW..DC01_LON_CLM_INF Bky
		ON Bky.AF_APL_ID = DC01.AF_APL_ID
		AND Bky.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND Bky.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND 
		(
			Bky.LC_PCL_REA IN('BC','BO')
			OR Bky.LC_AUX_STA = '07'
		)
	LEFT JOIN ODW..DC01_LON_CLM_INF Dcv
		ON Dcv.AF_APL_ID = DC01.AF_APL_ID
		AND Dcv.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND Dcv.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND ISNULL(Dcv.LD_CLM_ASN_DOE,'') != ''
		AND ISNULL(Dcv.LC_REA_CLM_ASN_DOE,'') != ''
	LEFT JOIN ODW..DC01_LON_CLM_INF Sat
		ON Sat.AF_APL_ID = DC01.AF_APL_ID
		AND Sat.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND Sat.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND 
		(
			Sat.LC_STA_DC10 = '04'
			OR Sat.LC_AUX_STA IN('01','06','10','11','12')
		)
	LEFT JOIN ODW..DC01_LON_CLM_INF Dth
		ON Dth.AF_APL_ID = DC01.AF_APL_ID
		AND Dth.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND Dth.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND 
		(
			Dth.LC_PCL_REA = 'DE'
			OR Dth.LC_AUX_STA = '02'
		)
	LEFT JOIN ODW..DC01_LON_CLM_INF Dis
		ON Dis.AF_APL_ID = DC01.AF_APL_ID
		AND Dis.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND Dis.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND 
		(
			Dis.LC_PCL_REA = 'DI'
			OR Dis.LC_AUX_STA = '03'
		)
	LEFT JOIN ODW..DC01_LON_CLM_INF Defr
		ON Defr.AF_APL_ID = DC01.AF_APL_ID
		AND Defr.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND Defr.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND Defr.LC_AUX_STA = '05'
	LEFT JOIN ODW..DC01_LON_CLM_INF SchClosed
		ON SchClosed.AF_APL_ID = DC01.AF_APL_ID
		AND SchClosed.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND SchClosed.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND SchClosed.LC_AUX_STA = '08'
	LEFT JOIN ODW..DC01_LON_CLM_INF FalseCert
		ON FalseCert.AF_APL_ID = DC01.AF_APL_ID
		AND FalseCert.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
		AND FalseCert.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
		AND FalseCert.LC_AUX_STA = '09'
WHERE
	P.DeletedAt IS NULL
	AND P.RetractedAt IS NULL
	AND
	(
		Bky.AF_APL_ID IS NOT NULL
		OR Dcv.AF_APL_ID IS NOT NULL
		OR Sat.AF_APL_ID IS NOT NULL
		OR Dth.AF_APL_ID IS NOT NULL
		OR Dis.AF_APL_ID IS NOT NULL
		OR Defr.AF_APL_ID IS NOT NULL
		OR SchClosed.AF_APL_ID IS NOT NULL
		OR FalseCert.AF_APL_ID IS NOT NULL
	)