CREATE TABLE [acurintr].[CompassQueue] (
    [CompassQueueID]      INT          IDENTITY (1, 1) NOT NULL,
    [Queue]               VARCHAR (2)  NOT NULL,
    [SubQueue]            VARCHAR (2)  NOT NULL,
    [TaskControlNumber]   VARCHAR (18) NOT NULL,
    [Ssn]                 VARCHAR (9)  NOT NULL,
    [AccountNumber]       VARCHAR (10) NOT NULL,
    [Address1]            VARCHAR (45) NULL,
    [Address2]            VARCHAR (30) NULL,
    [City]                VARCHAR (20) NULL,
    [State]               VARCHAR (2)  NULL,
    [Zipcode]             VARCHAR (17) NULL,
    [Country]             VARCHAR (25) NULL,
    [ForeignState]        VARCHAR (15) NULL,
    [AddressSource]       VARCHAR (2)  NULL,
    [AddressValidityDate] DATETIME     NULL,
    [OriginalAddressText] VARCHAR (75) NULL,
    [PrimaryPhone]        VARCHAR (10) NULL,
    [PhoneSource]         VARCHAR (2)  NULL,
    [PhoneValidityDate]   DATETIME     NULL,
    [OriginalPhoneText]   VARCHAR (10) NULL,
    [CreatedAt]           DATETIME     CONSTRAINT [DF_CompassQueue_CreatedAt] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]           VARCHAR (50) CONSTRAINT [DF_CompassQueue_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [ProcessedAt]         DATETIME     NULL,
    [DeletedAt]           DATETIME     NULL,
    [DeletedBy]           VARCHAR (50) NULL,
    CONSTRAINT [PK_CompassQueue] PRIMARY KEY CLUSTERED ([CompassQueueID] ASC) WITH (FILLFACTOR = 95)
);

