*--------------------------*
| ONELINK SPECIAL CAMPAIGN |
*--------------------------*;
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/ULWK26.LWK26R2";
FILENAME REPORTZ "&RPTLIB/ULWK26.LWK26RZ";

%LET QUEUES = 'REFRCALS','KDREFCLL','KCREFCLL',
	'KAREFCLL','EXITCALL','EXITCAL2',
	'PSCWDRW','KBWRCAL1','KBWRCAL2','KBWRCAL3';
/*	removing this for now it will be added back later 'DCLL2BOR'*/
%SYSLPUT QUEUES = &QUEUES;
LIBNAME  WORKLOCL  REMOTE  SERVER=DUSTER  SLIBREF=WORK;
RSUBMIT;
%MACRO SQLCHECK (SQLRPT= );
%IF &SQLXRC NE 0 %THEN %DO;
	DATA _NULL_;
    FILE REPORTZ NOTITLES;
    PUT @01 " ********************************************************************* "
      / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
      / @01 " ****  THE SAS LOG IN &SQLRPT SHOULD BE REVIEWED.          **** "       
      / @01 " ********************************************************************* "
      / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
      / @01 " ****  &SQLXMSG   **** "
      / @01 " ********************************************************************* ";
	RUN;
%END;
%MEND;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE OLSPC AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT A.DF_PRS_ID_TGT
	,A.DF_PRS_ID_BR
	,A.IF_WRK_GRP 
	,A.IC_TSK_STA AS TCI
	,A.LD_LST_PAY
	,RTRIM(BRW_INF.DM_PRS_1)||' '||RTRIM(DM_PRS_MID)||' '||RTRIM(DM_PRS_LST) AS BOR_NAME
	,BRW_INF.DD_BRT
	,BRW_INF.DF_SPE_ACC_ID
	,A.LD_LST_WRK
	,RTRIM(A.DM_TGT_PRS_1)||' '||RTRIM(A.DM_TGT_PRS_MID)||' '||RTRIM(A.DM_TGT_PRS_LST) AS TGT_NAME
	,A.DX_TGT_STR_ADR_1 	AS TGT_ADD1
	,A.DX_TGT_STR_ADR_2 	AS TGT_ADD2 
	,A.DM_TGT_CT			AS TGT_CT
	,A.DC_TGT_DOM_ST		AS TGT_ST
	,A.DF_TGT_ZIP			AS TGT_ZIP
	,TGT_INF.DM_FGN_CNY		AS TGT_FGN_CNY
	,TGT_INF.DI_VLD_ADR		AS TGT_VLD_ADR
	,CASE
		WHEN TGT_INF.DC_CEP IN ('L','P') THEN 'Y' 
		WHEN TGT_INF.DC_CEP IN ('N','U', 'T') THEN 'N'
		WHEN TGT_INF.DC_CEP IS NULL THEN 'N'
	END AS HOME_PHONE_CONSENT
	,CASE
		WHEN TGT_INF.DC_ALT_CEP IN ('L','P') THEN 'Y' 
		WHEN TGT_INF.DC_ALT_CEP IN ('N','U', 'T') THEN 'N'
		WHEN TGT_INF.DC_CEP IS NULL THEN 'N'
	END AS ALT_PHONE_CONSENT
	,CASE
		WHEN SUBSTR(A.DF_PRS_ID_TGT,1,2) = 'RF' AND RFR_INF.BI_DOM_PHN_VLD = 'Y' THEN A.DN_TGT_PHN
		WHEN SUBSTR(A.DF_PRS_ID_TGT,1,2) = 'RF' AND RFR_INF.BI_DOM_PHN_VLD <> 'Y' THEN ''
		WHEN SUBSTR(A.DF_PRS_ID_TGT,1,2) <> 'RF' AND TGT_INF.DI_PHN_VLD = 'Y' THEN A.DN_TGT_PHN
		WHEN SUBSTR(A.DF_PRS_ID_TGT,1,2) <> 'RF' AND TGT_INF.DI_PHN_VLD <> 'Y' THEN ''
	 END AS TGT_HOME_PHONE
	,TGT_INF.DN_ALT_PHN		AS TGT_ALT_PHONE
	,CASE 
		WHEN SUBSTR(A.IF_WRK_GRP,1,1) IN ('K','R') THEN RFR_INF.BD_RFR_LST_ATT_HME
		WHEN SUBSTR(A.IF_WRK_GRP,1,1) IN ('D','E','P') THEN DC01.LD_DFL_LST_ATT_CNC 
	 END AS LST_TGT_ATT_DT
	,CASE 
		WHEN SUBSTR(A.IF_WRK_GRP,1,1) IN ('K','R') THEN RFR_INF.BD_RFR_LST_CNC_HME
		WHEN SUBSTR(A.IF_WRK_GRP,1,1) IN ('D','E','P') THEN DC01.LD_DFL_LST_CNC 
	 END AS LST_TGT_CNC_DT
	,CASE 
		WHEN SUBSTR(A.IF_WRK_GRP,1,1) IN ('K','R') THEN 'SKP'
		WHEN SUBSTR(A.IF_WRK_GRP,1,1) IN ('D') THEN 'DFT'
		WHEN SUBSTR(A.IF_WRK_GRP,1,1) IN ('E','P') THEN 'PRE'
	 END AS REGION

	,BRW_ADD_INF.DX_STR_ADR_1 	AS REG_ADD1
	,BRW_ADD_INF.DX_STR_ADR_2	AS REG_ADD2
	,BRW_ADD_INF.DM_CT			AS REG_CT
	,BRW_ADD_INF.DC_DOM_ST		AS REG_ST
	,BRW_ADD_INF.DF_ZIP			AS REG_ZIP
	,BRW_ADD_INF.DM_FGN_CNY		AS REG_FGN_CNY
	,BRW_ADD_INF.DI_VLD_ADR		AS REG_VLD_ADR
	,BRW_ADD_INF.DI_PHN_VLD		AS REG_VLD_PHN
	,BRW_ADD_INF.DN_PHN			AS REG_HOME_PHONE
	,MAX_SKIP_DT.MAX_DT			AS REG_SKIP_DT
	,CHAR(LN16.REG_2_DAYS_DELQ) AS REG_2_DAYS_DELQ

FROM OLWHRM1.CT30_CALL_QUE A
LEFT OUTER JOIN OLWHRM1.BR03_BR_REF RFR_INF
	ON A.DF_PRS_ID_TGT = RFR_INF.DF_PRS_ID_RFR

LEFT OUTER JOIN OLWHRM1.PD03_PRS_ADR_PHN TGT_INF
	ON A.DF_PRS_ID_TGT = TGT_INF.DF_PRS_ID
	AND TGT_INF.DC_ADR = 'L'

LEFT OUTER JOIN OLWHRM1.PD01_PDM_INF BRW_INF
	ON A.DF_PRS_ID_BR = BRW_INF.DF_PRS_ID
LEFT OUTER JOIN OLWHRM1.PD03_PRS_ADR_PHN BRW_ADD_INF	
	ON A.DF_PRS_ID_BR = BRW_ADD_INF.DF_PRS_ID
	AND BRW_ADD_INF.DC_ADR = 'L'
LEFT OUTER JOIN (
	SELECT BF_SSN
		,MAX(LD_DFL_LST_ATT_CNC) AS LD_DFL_LST_ATT_CNC
		,MAX(LD_DFL_LST_CNC) AS LD_DFL_LST_CNC
	FROM OLWHRM1.DC01_LON_CLM_INF 
	GROUP BY BF_SSN
	) DC01
	ON A.DF_PRS_ID_BR = DC01.BF_SSN
LEFT OUTER JOIN (
	SELECT DISTINCT BF_SSN
		,DAYS(CURRENT DATE) - DAYS(X.LD_DLQ_OCC) AS REG_2_DAYS_DELQ
	FROM OLWHRM1.LN16_LON_DLQ_HST X
	WHERE LC_STA_LON16 = '1'
	AND X.LD_DLQ_OCC = (
			SELECT MIN(Y.LD_DLQ_OCC)
			FROM OLWHRM1.LN16_LON_DLQ_HST Y
			WHERE Y.BF_SSN = X.BF_SSN
			AND Y.LC_STA_LON16 = X.LC_STA_LON16
			)
	) LN16
	ON A.DF_PRS_ID_BR = LN16.BF_SSN
LEFT OUTER JOIN (
	SELECT DF_PRS_ID_BR 
		,MAX(DD_SKP_STA_EFF) AS MAX_DT
	FROM OLWHRM1.PD26_PRS_SKP_PRC
	GROUP BY DF_PRS_ID_BR 
	 ) MAX_SKIP_DT
	ON A.DF_PRS_ID_BR = MAX_SKIP_DT.DF_PRS_ID_BR
WHERE A.IF_WRK_GRP IN (&QUEUES) 
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>>  ;  * INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK (SQLRPT=ULWK26.LWK26RZ);*/
/*QUIT;*/
ENDRSUBMIT;

DATA OLSPC;
SET WORKLOCL.OLSPC;
RUN;
/*------------------------------*
|    VARIABLE INITIALIZATION    |
*------------------------------*/
DATA OLSPC;
SET OLSPC;
DAYS_LEFT = '00001';
DIALER_ORDER = '000';
TIME_ZONE = 'EAST';
BLOANS = '00000';
BWAGES = '000000000';
BOR_EI = 'N';
BOR_PAY_AMT = '000000000';
BOR_OUT_BAL = '000000000';
TAR2BOR = 'O';
HYPE = 'D';
AYPE = 'D';
REL2BOR = 'R';
FIL = ' ';
/*DTTME = '2006-02-01-00.30.46.106552';*/
IF MONTH(TODAY()) < 10 AND DAY(TODAY()) < 10 THEN DO;
DTTME = TRIM(LEFT(YEAR(TODAY())))||'-'||
	'0'||TRIM(LEFT(MONTH(TODAY())))||'-'||
	'0'||TRIM(LEFT(DAY(TODAY())))||
	'-00.00.00.000000';
	END;
ELSE IF MONTH(TODAY()) >= 10 AND DAY(TODAY()) < 10 THEN DO;
DTTME = TRIM(LEFT(YEAR(TODAY())))||'-'||
	TRIM(LEFT(MONTH(TODAY())))||'-'||
	'0'||TRIM(LEFT(DAY(TODAY())))||
	'-00.00.00.000000';
	END;
ELSE IF MONTH(TODAY()) < 10 AND DAY(TODAY()) >= 10 THEN DO;
DTTME = TRIM(LEFT(YEAR(TODAY())))||'-'||
	'0'||TRIM(LEFT(MONTH(TODAY())))||'-'||
	TRIM(LEFT(DAY(TODAY())))||
	'-00.00.00.000000';
	END;
ELSE DO;
DTTME = TRIM(LEFT(YEAR(TODAY())))||'-'||
	TRIM(LEFT(MONTH(TODAY())))||'-'||
	TRIM(LEFT(DAY(TODAY())))||
	'-00.00.00.000000';
	END;
RUN;
/*-------------------------------*
| CREATE THE FILE FOR THE DIALER |
*-------------------------------*/
DATA _NULL_;
SET  WORK.OLSPC;
FILE REPORT2 DROPOVER LRECL=32767;
FORMAT DF_PRS_ID_TGT $9. ;
FORMAT DF_PRS_ID_BR $9. ;
FORMAT BOR_NAME $50. ;
FORMAT DD_BRT YYMMDDN8. ;
FORMAT LD_LST_PAY YYMMDDN8.;
FORMAT LST_TGT_ATT_DT YYMMDDN8.;
FORMAT LST_TGT_CNC_DT YYMMDDN8.;
FORMAT DF_SPE_ACC_ID $10. ;
FORMAT LD_LST_WRK YYMMDDN8. ;
FORMAT TGT_NAME $50. ;
FORMAT TGT_ADD1 $35. ;
FORMAT TGT_ADD2 $35. ;
FORMAT TGT_CT $30. ;
FORMAT TGT_ST $2. ;
FORMAT TGT_ZIP $14. ;
FORMAT TGT_FGN_CNY $25. ;
FORMAT TGT_VLD_ADR $1. ;
FORMAT TGT_HOME_PHONE $10. ;
FORMAT TGT_ALT_PHONE $10. ;
FORMAT REG_ADD1 $35. ;
FORMAT REG_ADD2 $35. ;
FORMAT REG_CT $30. ;
FORMAT REG_ST $2. ;
FORMAT REG_ZIP $14. ;
FORMAT REG_FGN_CNY $25. ;
FORMAT REG_VLD_ADR $1. ;
FORMAT REG_VLD_PHN $1. ;
FORMAT REG_SKIP_DT YYMMDDN8. ;
FORMAT REGION $3. ;
FORMAT DAYS_LEFT $5. ;
FORMAT DIALER_ORDER $3. ;
FORMAT TCI $1. ;
FORMAT TIME_ZONE $4. ;
FORMAT BLOANS $5. ;
FORMAT BWAGES $9. ;
FORMAT BOR_EI $1. ;
FORMAT BOR_PAY_AMT $9. ;
FORMAT BOR_OUT_BAL $9. ;
FORMAT TAR2BOR $1. ;
FORMAT HYPE $1. ;
FORMAT AYPE $1. ;
FORMAT REL2BOR $1. ;
FORMAT DTTME $26. ;
FORMAT FIL $1.;
FORMAT REG_HOME_PHONE $17.;
FORMAT REG_2_DAYS_DELQ $5.;
DO;
PUT @ 1 DF_PRS_ID_TGT 
	@ 10 REGION
	@ 13 IF_WRK_GRP 
	@ 21 DAYS_LEFT
	@ 26 DIALER_ORDER
	@ 29 TCI
/*	@ 30 */
	@ 60 TIME_ZONE 
/*	@ 64 */
	@ 67 DF_PRS_ID_BR
	@ 76 BOR_NAME
	@ 126 BLOANS  
	@ 131 BWAGES     
	@ 140 BOR_EI
	@ 141 BOR_PAY_AMT     
	@ 150 BOR_OUT_BAL     
	@ 159 LD_LST_PAY
/*	@ 167 */
/*	@ 175 */
	@ 195 DD_BRT 
	@ 203 DF_SPE_ACC_ID 
/*	@ 213 */
	@ 220 LST_TGT_ATT_DT 
	@ 228 LST_TGT_CNC_DT 
	@ 236 LD_LST_WRK
	@ 244 TAR2BOR
	@ 245 TGT_NAME 
	@ 295 TGT_ADD1 
	@ 330 TGT_ADD2
	@ 365 TGT_CT  
	@ 395 TGT_ST 
	@ 397 TGT_ZIP
/*	@ 411 */
	@ 436 TGT_VLD_ADR     
/*	@ 437 */
	@ 441 HYPE     	
	@ 442 TGT_HOME_PHONE     
	@ 459 AYPE  
	@ 460 TGT_ALT_PHONE
/*	@ 477 */
/*	@ 478 */
	@ 495 HOME_PHONE_CONSENT
	@ 496 ALT_PHONE_CONSENT
	@ 510 REG_2_DAYS_DELQ
	@ 515 REL2BOR 
	@ 516 DF_PRS_ID_BR
	@ 525 BOR_NAME
	@ 575 REG_ADD1
	@ 610 REG_ADD2
	@ 645 REG_CT 
	@ 665 REG_ST 
	@ 667 REG_ZIP
	@ 681 REG_FGN_CNY
	@ 706 REG_VLD_ADR     
	@ 707 REG_HOME_PHONE     
	@ 724 REG_SKIP_DT       
/*	@ 732 */
	@ 735 DTTME
/*	@ 761 */
	@ 800 FIL;
END;
RUN;
