CREATE TABLE [dbo].[AP03_Master_Application]
(
	[AF_APL_ID] [char](9) NOT NULL,
	[BF_SSN] [char](9) NULL,
	[AN_SEQ] [int] NULL,
	[LF_STU_SSN] [char](9) NULL,
	[IC_LON_PGM] [varchar](6) NULL,
	[AD_CRT_APL] [datetime] NULL,
	[AC_STA_ORG_PRC] [varchar](2) NULL,
	[AD_STA_ORG_PRC] [datetime] NULL,
	[AC_APL_SCR_STA] [char](1) NULL,
	[AC_APL_PRC_TYP] [char](1) NULL,
	[AI_BR_DLQ_FED_DET] [char](1) NULL,
	[AI_BR_DET] BIT NULL,
	[AC_BR_INT_OPT] BIT NULL,
	[AC_BR_RPD_OPT] [char](1) NULL,
	[AI_BR_NED_ORG_FEE] BIT NULL,
	[AI_BR_ATH_DSB_EFT] BIT NULL,
	[AI_EDS_XST_ON_APL] BIT NULL,
	[AI_RFR_XST_ON_APL] BIT NULL,
	[AD_STU_LON_TRM_BEG] [datetime] NULL,
	[AD_STU_LON_TRM_END] [datetime] NULL,
	[AD_STU_GRD_XPC] [datetime] NULL,
	[AI_STU_FGN_CNY_STY] [char](1) NULL,
	[AC_STU_MAJ_STY] [varchar](3) NULL,
	[AX_STU_CNL_MAJ_STY] [varchar](15) NULL,
	[AC_STU_SCL_ENR_STA] [char](1) NULL,
	[AI_STU_DFR_REQ] [bit] NULL,
	[AA_STU_REQ] [int] NULL,
	[AF_DOE_SCL] [varchar](8) NULL,
	[AF_CNL_NON_EDU_BRH] [varchar](4) NULL,
	[AD_SCL_LON_TRM_BEG] [datetime] NULL,
	[AD_SCL_LON_TRM_END] [datetime] NULL,
	[AD_SCL_ACA_TRM_BEG] [datetime] NULL,
	[AD_SCL_ACA_TRM_END] [datetime] NULL,
	[AD_SCL_GRD_XPC] [datetime] NULL,
	[AC_SCL_STA_STU_ENR] [char](1) NULL,
	[AC_SCL_ACA_GDE_LEV] [varchar](2) NULL,
	[AC_SCL_ACA_PGS] [char](1) NULL,
	[AA_SCL_EDU_CST] [int] NULL,
	[AA_SCL_EDU_AID_TOT] [int] NULL,
	[AA_SCL_EFC] [int] NULL,
	[AA_SCL_REQ] [int] NULL,
	[AI_SCL_CNF_MPN_OVR] [char](1) NULL,
	[AI_SCL_STU_PAS_DU] [bit] NULL,
	[AN_SCL_AMT_CLC_MLT] [numeric](7, 4) NULL,
	[AF_DOE_LDR] [varchar](8) NULL,
	[AF_LDR_NON_EDU_BRH] [varchar](4) NULL,
	[AF_LDR_APL_FIL] [varchar](10) NULL,
	[AA_LDR_APV] [int] NULL,
	[AC_LDR_PGM_YR] [char](1) NULL,
	[AI_LDR_CNF_MPN_OVR] [char](1) NULL,
	[AF_LDR_BND_ISS] [varchar](8) NULL,
	[AF_LDR_FEE_TIR] [varchar](3) NULL,
	[AI_LDR_NO_FEE_OVR] [char](1) NULL,
	[AF_LDR_ITR_TIR] [varchar](3) NULL,
	[AI_LDR_NO_ITR_OVR] [char](1) NULL,
	[AD_LDR_APL_REJ] [datetime] NULL,
	[AF_LDR_ORG] [varchar](8) NULL,
	[AI_LDR_MAT_SLL_LON] [char](1) NULL,
	[AF_LDR_LST_RST] [varchar](8) NULL,
	[IF_GTR] [varchar](6) NULL,
	[AF_GTR_RFR] [varchar](10) NULL,
	[AA_GTR_LON] [numeric](9, 2) NULL,
	[AD_GTR_LON_REQ] [datetime] NULL,
	[AD_GTR_ORG] [datetime] NULL,
	[AR_GTR_INT] [numeric](6, 3) NULL,
	[AC_GTR_ITR_TYP] [varchar](2) NULL,
	[AR_GTR_FEE] [numeric](6, 3) NULL,
	[AI_GTR_TL4_PIO_787] [char](1) NULL,
	[AI_GTR_DSB_LTE_AZ] [char](1) NULL,
	[AD_GTR_DSB_MAX_LTE] [datetime] NULL,
	[AA_GTR_RSC] [int] NULL,
	[AD_GTR_RSC] [datetime] NULL,
	[AC_GTR_DFR_REQ] [char](1) NULL,
	[AC_GTR_INT_BIL_OPT] [varchar](2) NULL,
	[AC_GTR_REA_RDC] [varchar](2) NULL,
	[AA_GTR_TOT_SFD_BAL] [numeric](9, 2) NULL,
	[AA_GTR_TOT_PLS_BAL] [numeric](9, 2) NULL,
	[AI_GTR_RSC] [char](1) NULL,
	[AC_SRC_APL] [varchar](3) NULL,
	[AC_VRS_ALT_APL] [varchar](4) NULL,
	[AC_SER_RUE] [varchar](2) NULL,
	[AD_PNT_SIG] [datetime] NULL,
	[AI_PNT_VER] [bit] NULL,
	[AF_PNT_VER_BY] [varchar](8) NULL,
	[AD_PNT_VER] [datetime] NULL,
	[AI_ESC] [bit] NULL,
	[AC_APL_HLD] [varchar](2) NULL,
	[AD_APL_HLD] [datetime] NULL,
	[AA_STF_APV] [int] NULL,
	[AA_ESM_RPD] [numeric](7, 2) NULL,
	[AD_ESM_RPD_SR] [datetime] NULL,
	[AD_ESM_POF] [datetime] NULL,
	[AC_SYS_CLC_DFR] [char](1) NULL,
	[AA_ANL_INC] [numeric](9, 2) NULL,
	[AA_MTH_CLC_RPD] [numeric](9, 2) NULL,
	[AA_MTH_CMB_DET] [numeric](9, 2) NULL,
	[AA_MTH_CMB_INC] [numeric](9, 2) NULL,
	[AR_CMB_DET_INC_RTO] [numeric](6, 3) NULL,
	[AA_TOT_SFD_BAL] [numeric](9, 2) NULL,
	[AA_TOT_PLS_BAL] [numeric](9, 2) NULL,
	[AA_TOT_SLS_BAL] [numeric](9, 2) NULL,
	[AA_TOT_PRK_BAL] [numeric](9, 2) NULL,
	[AA_TOT_HEA_BAL] [numeric](9, 2) NULL,
	[AA_OTH_EDU_LON_BAL] [int] NULL,
	[AA_TOT_STU_LN_BAL] [int] NULL,
	[AA_ORG_FEE_PD] [int] NULL,
	[AA_GTR_FEE_PD] [int] NULL,
	[AC_REA_CPY_AP03] [char](1) NULL,
	[AF_APL_ID_CPY] [varchar](9) NULL,
	[AI_EXT_CVN] [bit] NULL,
	[AF_APL_ID_CPY_ORG] [varchar](9) NULL,
	[AN_SEQ_CVN] [int] NULL,
	[AN_SIG_ON_PNT] [smallint] NULL,
	[AF_RGL_CAT_LP06] [varchar](7) NULL,
	[AF_RGL_CAT_LP09] [varchar](7) NULL,
	[AF_RGL_CAT_LP10] [varchar](7) NULL,
	[AF_RGL_CAT_LP12] [varchar](7) NULL,
	[AF_RGL_CAT_LP20] [varchar](7) NULL,
	[AD_LON_1_DSB] [datetime] NULL,
	[AC_ORG_DPT] [varchar](2) NULL,
	[AR_LP_TB_ITR_MGN] [numeric](6, 3) NULL,
	[AD_AMR_BEG] [datetime] NULL,
	[AR_SCL_SUB] [numeric](7, 3) NULL,
	[AC_PNT_DEL] [char](1) NULL,
	[AD_PNT_SNT] [datetime] NULL,
	[AC_SCL_NTF_STA_CHG] [char](1) NULL,
	[AI_DSB_REJ_ACK_FIL] [bit] NULL,
	[AC_PIO_ORG_STA] [char](1) NULL,
	[AC_MN_TYP] [char](1) NULL,
	[AC_MN_SRL_LON] [char](1) NULL,
	[AI_MN_PSD_BS] [char](1) NULL,
	[AC_MN_CNF] [char](1) NULL,
	[AC_MN_BR_CNF] [char](1) NULL,
	[AD_MN_EXP] [datetime] NULL,
	[AI_MN_NOG] [char](1) NULL,
	[AI_MN_LN_OF_CRD] [char](1) NULL,
	[AC_MN_SRL_LON_ORG] [char](1) NULL,
	[AD_MN_BR_CNF_SNT] [datetime] NULL,
	[AD_MN_BR_CNF_RCV] [datetime] NULL,
	[AA_MN_BR_CNF] [int] NULL,
	[AC_MN_REV_REA] [varchar](2) NULL,
	[AF_MN_MST_NTE] [varchar](11) NULL,
	[AN_MN_MST_NTE_SEQ] [int] NULL,
	[AI_MN_ORG_RGT_SLD] [bit] NULL,
	[AF_MN_RGT_SLD_TO] [varchar](8) NULL,
	[AF_CNL] [varchar](17) NULL,
	[AF_CNL_SFX] [varchar](2) NULL,
	[AX_CNL_GTR_USE] [varchar](23) NULL,
	[AC_CNL_GTR_STA] [varchar](2) NULL,
	[AD_CNL_GTR_STA] [datetime] NULL,
	[AF_CNL_GTR_TRT_DTS] [datetime] NULL,
	[AX_CNL_LDR_USE] [varchar](23) NULL,
	[AC_CNL_LDR_SER_STA] [varchar](2) NULL,
	[AD_CNL_LDR_SER_STA] [datetime] NULL,
	[AF_CNL_LDR_TRT_DTS] [datetime] NULL,
	[AX_CNL_SCL_USE] [varchar](23) NULL,
	[AA_CNL_ACL_RTD] [numeric](9, 2) NULL,
	[AA_CNL_WDR_GR_RFD] [numeric](9, 2) NULL,
	[AA_CNL_AVL_RNS] [numeric](9, 2) NULL,
	[AC_CNL_MTD_FUD_RTD] [varchar](2) NULL,
	[AI_CNL_DSB_CNS] [char](1) NULL,
	[AC_CNL_PRC_TYP_APL] [varchar](2) NULL,
	[AC_CNL_RPT_STA] [varchar](2) NULL,
	[AC_CNL_SRV_TYP] [varchar](2) NULL,
	[AC_CNL_ITL_RSP] [char](1) NULL,
	[AC_FLW_TYP] [varchar](2) NULL,
	[AC_FLW_STA] [char](1) NULL,
	[AD_FLW_STA] [datetime] NULL,
	[AD_FLW_APV] [datetime] NULL,
	[AF_LST_USR_AP03] [varchar](8) NULL,
	[AF_LST_DTS_AP03] [datetime] NULL,
	[AD_LON_1_PAY_DU] [datetime] NULL,
	[AI_STA_ORG_PRC_CHG] [bit] NULL,
	[AI_PNT_PRT] [bit] NULL,
	[AD_TO_SER_CMP] [datetime] NULL,
	[AI_LDR_RGT_SLD_CHG] [char](1) NULL,
	[AC_MN_MST_NTE_ASG] [char](1) NULL,
	[AC_CRD_WOR_RED] [char](1) NULL,
	[AI_FEE_MNL_CLC] [char](1) NULL,
	[AC_BR_ST_DSB_1] [varchar](2) NULL,
	[AC_SCL_ST_DSB_1] [varchar](2) NULL,
	[AC_FIL_TYP_REQ] [varchar](2) NULL,
	[AC_FIL_RCP] [char](1) NULL,
	[AC_PNT_YR] [varchar](7) NULL,
	[AC_STP_PUR] [char](1) NULL,
	[AI_PIO_APL_LDR] [char](1) NULL,
	[AI_SCL_ENT_CCL] [char](1) NULL,
	[AI_DEG_SKG] [char](1) NULL,
	[AA_BS_POI] [numeric](7, 4) NULL,
	[AF_CUR_POR] [varchar](20) NULL,
	[AF_DTS_APL_ELG_CER] [datetime] NULL,
	[AD_DTR_APL_CER_CMP] [datetime] NULL,
	[AF_USR_CER_CLG] [varchar](8) NULL,
	[AC_EDU_LEV_TYP] [char](1) NULL,
	[AA_LST_CTR_OFR] [numeric](13, 2) NULL,
	[AD_LST_CTR_OFR] [datetime] NULL,
	[AC_BR_CTR_OFR_RSP] [char](1) NULL,
	[AN_BR_PIO_ALT_DNL] [smallint] NULL,
	[AF_ALT_LON_APL] [varchar](9) NULL,
	[AC_ALT_APL_ELG_STA] [varchar](2) NULL,
	[AC_ALT_APL_ACT_STA] [char](1) NULL,
	[AF_APL_SLC_DIS] [varchar](11) NULL,
	[AI_TLX_APL] [char](1) NULL,
	[AF_PNT_VRS] [varchar](7) NULL,
	[AD_APL_EXP] [datetime] NULL,
	[AC_APL_EXP_EVT] [varchar](3) NULL,
	[AC_APL_RVW] [char](1) NULL,
	[AC_CNL_TRN_REA] [char](1) NULL,
	[AC_ALT_APL_FLW] [varchar](2) NULL, 
    CONSTRAINT [PK_AP03_Master_Application] PRIMARY KEY ([AF_APL_ID])
)
