CREATE TABLE [dbo].[PD21_GTR_DTH]
(
	[DF_PRS_ID] VARCHAR(9) NOT NULL, 
	[DD_DTH_NTF] DATETIME NOT NULL, 
	[IF_GTR] VARCHAR(6) NOT NULL, 
	[DD_DTH_VER] DATETIME NULL, 
	[DC_DTH_STA] VARCHAR(2) NULL, 
	[DC_DTH_CER] VARCHAR(2) NULL, 
	[DF_LST_DTS_PD21] DATETIME NULL, 
	[DD_DTH_STA] DATETIME NULL, 

    PRIMARY KEY ([DF_PRS_ID], 
				[DD_DTH_NTF], 
				[IF_GTR]
				)
)
