//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class users
{

    private usersUser[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("user", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public usersUser[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class usersUser
{
    #region CUSTOM FIELDS
    public string ManagerAuthParam { get; set; }
    public string ManagerLoginID { get; set; }
    public string ManagerEmail { get; set; }
    public string ManagerFirstName { get; set; }
    public string ManagerLastName { get; set; }
    #endregion
    private string first_nameField;

    private string middle_InitialField;

    private string middle_nameField;

    private string last_nameField;

    private string userGUIDField;

    private string loginIDField;

    private string authTypeField;

    private string authParamField;

    private string managerIdField;

    private string emailField;

    private string terminationDateField;

    private string hireDateField;

    private string retiredField;

    private string full_NameField;

    private string preferred_NameField;

    private string sSNOField;

    private string dOBField;

    private string sectionContactInfoField;

    private string address1Field;

    private string address2Field;

    private string cityField;

    private string stateField;

    private string zipField;

    private string countryField;

    private string phoneField;

    private string secondary_PhoneField;

    private string workPhone1Field;

    private string workPhone2Field;

    private string sectionEEOInfoField;

    private string maritalStatusField;

    private string ethnicityField;

    private string genderField;

    private string disability_StatusField;

    private string sectionVeteranEEOInfoField;

    private string veteran_ArmedForcesField;

    private string veteran_DisabledField;

    private string veteran_RecentlySeperatedField;

    private string veteran_SpecialDisabledField;

    private string veteran_VietnamEraField;

    private string veteran_OtherProtectedField;

    private string veteran_NotApplicableField;

    private string sectionPositionInfoField;

    private string resume_IDField;

    private string positionField;

    private string role_dropdownField;

    private string business_UnitField;

    private string tracking_CodeField;

    private string job_IDField;

    private string recruiterField;

    private string hiring_ManagerField;

    private string eEO_Job_CategoryField;

    private string position_TypeField;

    private string job_Template_NameField;

    private string job_Template_CodeField;

    private string offer_DateField;

    private string salary_AmountField;

    private string salary_TypeField;

    private string co_nameField;

    private string co_address1Field;

    private string co_address2Field;

    private string co_cityField;

    private string co_stateField;

    private string co_zipField;

    private string co_einField;

    private usersUserKeyProperties[] keyPropertiesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string first_name
    {
        get
        {
            return this.first_nameField;
        }
        set
        {
            this.first_nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Middle_Initial
    {
        get
        {
            return this.middle_InitialField;
        }
        set
        {
            this.middle_InitialField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string middle_name
    {
        get
        {
            return this.middle_nameField;
        }
        set
        {
            this.middle_nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string last_name
    {
        get
        {
            return this.last_nameField;
        }
        set
        {
            this.last_nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UserGUID
    {
        get
        {
            return this.userGUIDField;
        }
        set
        {
            this.userGUIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoginID
    {
        get
        {
            return this.loginIDField;
        }
        set
        {
            this.loginIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AuthType
    {
        get
        {
            return this.authTypeField;
        }
        set
        {
            this.authTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AuthParam
    {
        get
        {
            return this.authParamField;
        }
        set
        {
            this.authParamField = value;
        }
    }

    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ManagerID
    {
        get
        {
            return this.managerIdField;
        }
        set
        {
            this.managerIdField = value;
        }
    }


    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TerminationDate
    {
        get
        {
            return this.terminationDateField;
        }
        set
        {
            this.terminationDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HireDate
    {
        get
        {
            return this.hireDateField;
        }
        set
        {
            this.hireDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Retired
    {
        get
        {
            return this.retiredField;
        }
        set
        {
            this.retiredField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Full_Name
    {
        get
        {
            return this.full_NameField;
        }
        set
        {
            this.full_NameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Preferred_Name
    {
        get
        {
            return this.preferred_NameField;
        }
        set
        {
            this.preferred_NameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SSNO
    {
        get
        {
            return this.sSNOField;
        }
        set
        {
            this.sSNOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DOB
    {
        get
        {
            return this.dOBField;
        }
        set
        {
            this.dOBField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SectionContactInfo
    {
        get
        {
            return this.sectionContactInfoField;
        }
        set
        {
            this.sectionContactInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Address1
    {
        get
        {
            return this.address1Field;
        }
        set
        {
            this.address1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Address2
    {
        get
        {
            return this.address2Field;
        }
        set
        {
            this.address2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string City
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string State
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Zip
    {
        get
        {
            return this.zipField;
        }
        set
        {
            this.zipField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Country
    {
        get
        {
            return this.countryField;
        }
        set
        {
            this.countryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Secondary_Phone
    {
        get
        {
            return this.secondary_PhoneField;
        }
        set
        {
            this.secondary_PhoneField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WorkPhone1
    {
        get
        {
            return this.workPhone1Field;
        }
        set
        {
            this.workPhone1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WorkPhone2
    {
        get
        {
            return this.workPhone2Field;
        }
        set
        {
            this.workPhone2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SectionEEOInfo
    {
        get
        {
            return this.sectionEEOInfoField;
        }
        set
        {
            this.sectionEEOInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MaritalStatus
    {
        get
        {
            return this.maritalStatusField;
        }
        set
        {
            this.maritalStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Ethnicity
    {
        get
        {
            return this.ethnicityField;
        }
        set
        {
            this.ethnicityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Gender
    {
        get
        {
            return this.genderField;
        }
        set
        {
            this.genderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Disability_Status
    {
        get
        {
            return this.disability_StatusField;
        }
        set
        {
            this.disability_StatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SectionVeteranEEOInfo
    {
        get
        {
            return this.sectionVeteranEEOInfoField;
        }
        set
        {
            this.sectionVeteranEEOInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Veteran_ArmedForces
    {
        get
        {
            return this.veteran_ArmedForcesField;
        }
        set
        {
            this.veteran_ArmedForcesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Veteran_Disabled
    {
        get
        {
            return this.veteran_DisabledField;
        }
        set
        {
            this.veteran_DisabledField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Veteran_RecentlySeperated
    {
        get
        {
            return this.veteran_RecentlySeperatedField;
        }
        set
        {
            this.veteran_RecentlySeperatedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Veteran_SpecialDisabled
    {
        get
        {
            return this.veteran_SpecialDisabledField;
        }
        set
        {
            this.veteran_SpecialDisabledField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Veteran_VietnamEra
    {
        get
        {
            return this.veteran_VietnamEraField;
        }
        set
        {
            this.veteran_VietnamEraField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Veteran_OtherProtected
    {
        get
        {
            return this.veteran_OtherProtectedField;
        }
        set
        {
            this.veteran_OtherProtectedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Veteran_NotApplicable
    {
        get
        {
            return this.veteran_NotApplicableField;
        }
        set
        {
            this.veteran_NotApplicableField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SectionPositionInfo
    {
        get
        {
            return this.sectionPositionInfoField;
        }
        set
        {
            this.sectionPositionInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Resume_ID
    {
        get
        {
            return this.resume_IDField;
        }
        set
        {
            this.resume_IDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Position
    {
        get
        {
            return this.positionField;
        }
        set
        {
            this.positionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Role_dropdown
    {
        get
        {
            return this.role_dropdownField;
        }
        set
        {
            this.role_dropdownField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Business_Unit
    {
        get
        {
            return this.business_UnitField;
        }
        set
        {
            this.business_UnitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Tracking_Code
    {
        get
        {
            return this.tracking_CodeField;
        }
        set
        {
            this.tracking_CodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Job_ID
    {
        get
        {
            return this.job_IDField;
        }
        set
        {
            this.job_IDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Recruiter
    {
        get
        {
            return this.recruiterField;
        }
        set
        {
            this.recruiterField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Hiring_Manager
    {
        get
        {
            return this.hiring_ManagerField;
        }
        set
        {
            this.hiring_ManagerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EEO_Job_Category
    {
        get
        {
            return this.eEO_Job_CategoryField;
        }
        set
        {
            this.eEO_Job_CategoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Position_Type
    {
        get
        {
            return this.position_TypeField;
        }
        set
        {
            this.position_TypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Job_Template_Name
    {
        get
        {
            return this.job_Template_NameField;
        }
        set
        {
            this.job_Template_NameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Job_Template_Code
    {
        get
        {
            return this.job_Template_CodeField;
        }
        set
        {
            this.job_Template_CodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Offer_Date
    {
        get
        {
            return this.offer_DateField;
        }
        set
        {
            this.offer_DateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Salary_Amount
    {
        get
        {
            return this.salary_AmountField;
        }
        set
        {
            this.salary_AmountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Salary_Type
    {
        get
        {
            return this.salary_TypeField;
        }
        set
        {
            this.salary_TypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string co_name
    {
        get
        {
            return this.co_nameField;
        }
        set
        {
            this.co_nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string co_address1
    {
        get
        {
            return this.co_address1Field;
        }
        set
        {
            this.co_address1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string co_address2
    {
        get
        {
            return this.co_address2Field;
        }
        set
        {
            this.co_address2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string co_city
    {
        get
        {
            return this.co_cityField;
        }
        set
        {
            this.co_cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string co_state
    {
        get
        {
            return this.co_stateField;
        }
        set
        {
            this.co_stateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string co_zip
    {
        get
        {
            return this.co_zipField;
        }
        set
        {
            this.co_zipField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string co_ein
    {
        get
        {
            return this.co_einField;
        }
        set
        {
            this.co_einField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("KeyProperties", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public usersUserKeyProperties[] KeyProperties
    {
        get
        {
            return this.keyPropertiesField;
        }
        set
        {
            this.keyPropertiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class usersUserKeyProperties
{

    private usersUserKeyPropertiesCategory[] categoryField;

    private usersUserKeyPropertiesPerson[] personField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Category", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public usersUserKeyPropertiesCategory[] Category
    {
        get
        {
            return this.categoryField;
        }
        set
        {
            this.categoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Person", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public usersUserKeyPropertiesPerson[] Person
    {
        get
        {
            return this.personField;
        }
        set
        {
            this.personField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class usersUserKeyPropertiesCategory
{

    private string categoryCodeField;

    private string nameField;

    private string valueField;

    private string codeField;

    private string pathField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CategoryCode
    {
        get
        {
            return this.categoryCodeField;
        }
        set
        {
            this.categoryCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class usersUserKeyPropertiesPerson
{

    private string codeField;

    private string nameField;

    private string valueField;

    private string loginIDField;

    private string managerIdField;

    private string emailField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LoginID
    {
        get
        {
            return this.loginIDField;
        }
        set
        {
            this.loginIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ManagerID
    {
        get
        {
            return this.managerIdField;
        }
        set
        {
            this.managerIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
}
