/*THIS SPECIFICIES WHAT DIRECTORY TO READ REPORTS FROM AND WHICH DATABASE TO UPDATE.*/
/*LIVE*/
%INCLUDE "X:\Sessions\Local SAS Schedule\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas";
%LET REPORT = X:\PADD\FTP;

/*TEST*/
/*%INCLUDE "X:\PADU\SAS\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas" ;
%LET REPORT = T:\SAS;*/

%FILECHECK(48);

DATA MR01;
	INFILE REPORT48 DSD DLM = ',' FIRSTOBS=1 MISSOVER END = EOF;
	INPUT 
		BF_SSN :$9.
		LN_SEQ :2.
		LA_CUR_PRI :8.2
		WA_ACR_BRI_RUN_DTE :7.2
		WD_RUN :DATE9.
		WN_DAY_DLQ_INT :4.0
		WD_DCO_INT :DATE9.
		WA_PSS_DU_INT :7.2
		WA_CUR_INT_DU :7.2
		WN_DAY_DLQ_ISL :4.0
		WD_DCO_ISL :DATE9.
		WA_PSS_DU_ISL :7.2
		WA_CUR_DU_ISL :7.2
		IC_LON_PGM :$6.
		WX_LON_PGM :$20.
		IF_BND_ISS :$8.
		LD_LON_1_DSB :DATE9.
		LD_LON_EFF_ADD :DATE9.
		LF_STU_SSN :$9.
		LD_STA_STU10 :DATE9.
		LD_SCL_SPR :DATE9.
		LD_DFR_BEG :DATE9.
		LD_DFR_END :DATE9.
		LD_DFR_GRC_END :DATE9.
		LC_DFR_RSP :$3.
		WX_DFR_RSP :$20.
		LD_DFR_APL :DATE9.
		LD_FOR_BEG :DATE9.
		LD_FOR_END :DATE9.
		LC_FOR_RSP :$3.
		WX_FOR_RSP :$20.
		LD_FOR_APL :DATE9.
		WA_RPS_ISL_1 :7.2
		WN_RPS_TRM_1 :3.0
		WA_RPS_ISL_2 :7.2
		WN_RPS_TRM_2 :3.0
		WA_RPS_ISL_3 :7.2
		WN_RPS_TRM_3 :3.0
		WA_RPS_ISL_4 :7.2
		WN_RPS_TRM_4 :3.0
		WA_RPS_ISL_5 :7.2
		WN_RPS_TRM_5 :3.0
		WA_RPS_ISL_6 :7.2
		WN_RPS_TRM_6 :3.0
		WA_RPS_ISL_7 :7.2
		WN_RPS_TRM_7 :3.0
		LD_RPS_1_PAY_DU :DATE9.
		WC_ITR_TYP_1 :$2.
		WX_ITR_TYP_1 :$20.
		WR_ITR_1 :5.3
		WD_ITR_EFF_BEG_1 :DATE9.
		WC_ITR_TYP_2 :$2.
		WX_ITR_TYP_2 :$20.
		WR_ITR_2 :5.3
		WD_ITR_EFF_BEG_2 :DATE9.
		DM_PRS_1 :$13.
		DM_PRS_MID :$13.
		DM_PRS_LST :$23.
		DM_PRS_LST_SFX :$4.
		DI_PHN_VLD :1.
		DN_DOM_PHN_ARA :$3.
		IF_GTR :$6.
		LF_LON_OWN_CUR :$8.
		LF_DOE_SCL_ORG :$8.
		LF_DOE_SCL_ENR_CUR :$8.
		LF_GTR_RFR :$12.
		LD_END_GRC_PRD :DATE9.
		LC_ELG_SIN :1.
		WX_ELG_SIN :$20.
		LF_CUR_POR :$20.
		LF_OWN_ORG_POR :$20.
		LC_LOC_PNT :$3.
		WX_LOC_PNT :$20.
		LD_OWN_EFF_SR :DATE9.
		WC_ISL_DLQ_CAT :$1.
		WX_ISL_DLQ_CAT :$20.
		WC_INT_DLQ_CAT :$1.
		WX_INT_DLQ_CAT :$20.
		WA_ORG_PRI :8.2
		WN_ATV_DSB :3.0
		WN_ACL_DSB :3.0
		WN_ANT_DSB :3.0
		WC_LON_STA :$2.
		WX_LON_STA :$10.
		WC_LON_SUB_STA :$2.
		WX_LON_SUB_STA :$12.
		WC_LON_CLM_STA :$2.
		WX_LON_CLM_STA :$20.
		WC_BR_PRS_STA :$2.
		WX_BR_PRS_STA :$20.
		LC_DFR_TYP :$2.
		WX_DFR_TYP :$20.
		LC_FOR_TYP :$2.
		WX_FOR_TYP :$20.
		LC_FOR_SUB_TYP :$1.
		WX_FOR_SUB_TYP :$20.
		LC_TYP_SCH_DIS :$2.
		WX_TYP_SCH_DIS :$20.
		LD_NTF_SCL_SPR :DATE9.
		LD_SPA_STP :DATE9.
		LD_SPA_STP_ENT :DATE9.
		LD_SPA_RTT :DATE9.
		LD_SPA_RTT_ENT :DATE9.
		WA_ACR_BRI_MTT :7.2
		WA_CUR_LTE_FEE :6.2
		WA_PRV_LTE_FEE :6.2
		LC_ST_BR_RSD_APL :$2.
		LC_STA_NEW_BR :$3.
		WF_NON_PR_ACT_REQ :$5.
		WD_FNL_DMD_BR :DATE9.
		WD_FNL_DMD_EDS :DATE9.
		LC_IND_BIL_SNT :$1.
		LC_BIL_MTD :$1.
		LD_DSB :DATE9.
		WA_LST_DSB_WK :8.2
		WI_LON_FUL_DSB_WK :1.


	;
	%TRUNCAT(48, BF_SSN);
RUN;
%copyerror;

DATA MR01;
SET MR01;
	WD_RUN = WD_RUN * 86400;
	WD_DCO_INT = WD_DCO_INT * 86400;
	WD_DCO_ISL = WD_DCO_ISL * 86400;
	LD_LON_1_DSB = LD_LON_1_DSB * 86400;
	LD_LON_EFF_ADD = LD_LON_EFF_ADD * 86400;
	LD_STA_STU10 = LD_STA_STU10 * 86400;
	LD_SCL_SPR = LD_SCL_SPR * 86400;
	LD_DFR_BEG = LD_DFR_BEG * 86400;
	LD_DFR_END = LD_DFR_END * 86400;
	LD_DFR_GRC_END = LD_DFR_GRC_END * 86400;
	LD_DFR_APL = LD_DFR_APL * 86400;
	LD_FOR_BEG = LD_FOR_BEG * 86400;
	LD_FOR_END = LD_FOR_END * 86400;
	LD_FOR_APL = LD_FOR_APL * 86400;
	LD_RPS_1_PAY_DU = LD_RPS_1_PAY_DU * 86400;
	WD_ITR_EFF_BEG_1 = WD_ITR_EFF_BEG_1 * 86400;
	WD_ITR_EFF_BEG_2 = WD_ITR_EFF_BEG_2 * 86400;
	LD_END_GRC_PRD = LD_END_GRC_PRD * 86400;
	LD_OWN_EFF_SR = LD_OWN_EFF_SR * 86400;
	LD_NTF_SCL_SPR = LD_NTF_SCL_SPR * 86400;
	LD_SPA_STP = LD_SPA_STP * 86400;
	LD_SPA_STP_ENT = LD_SPA_STP_ENT * 86400;
	LD_SPA_RTT = LD_SPA_RTT * 86400;
	LD_SPA_RTT_ENT = LD_SPA_RTT_ENT * 86400;
	WD_FNL_DMD_BR = WD_FNL_DMD_BR * 86400;
	WD_FNL_DMD_EDS = WD_FNL_DMD_EDS * 86400;
	LD_DSB = LD_DSB * 86400;

RUN;

PROC SORT DATA=MR01; BY BF_SSN LN_SEQ; RUN;

%ENCHILADA
	(
		MR01,
		MR01_MGT_RPT_LON,
		BF_SSN  
		LN_SEQ,  
		LA_CUR_PRI  
		WA_ACR_BRI_RUN_DTE  
		WD_RUN  
		WN_DAY_DLQ_INT  
		WD_DCO_INT  
		WA_PSS_DU_INT  
		WA_CUR_INT_DU  
		WN_DAY_DLQ_ISL  
		WD_DCO_ISL  
		WA_PSS_DU_ISL  
		WA_CUR_DU_ISL  
		IC_LON_PGM  
		WX_LON_PGM  
		IF_BND_ISS  
		LD_LON_1_DSB  
		LD_LON_EFF_ADD  
		LF_STU_SSN  
		LD_STA_STU10  
		LD_SCL_SPR  
		LD_DFR_BEG  
		LD_DFR_END  
		LD_DFR_GRC_END  
		LC_DFR_RSP  
		WX_DFR_RSP  
		LD_DFR_APL  
		LD_FOR_BEG  
		LD_FOR_END  
		LC_FOR_RSP  
		WX_FOR_RSP  
		LD_FOR_APL  
		WA_RPS_ISL_1  
		WN_RPS_TRM_1  
		WA_RPS_ISL_2  
		WN_RPS_TRM_2  
		WA_RPS_ISL_3  
		WN_RPS_TRM_3  
		WA_RPS_ISL_4  
		WN_RPS_TRM_4  
		WA_RPS_ISL_5  
		WN_RPS_TRM_5  
		WA_RPS_ISL_6  
		WN_RPS_TRM_6  
		WA_RPS_ISL_7  
		WN_RPS_TRM_7  
		LD_RPS_1_PAY_DU  
		WC_ITR_TYP_1  
		WX_ITR_TYP_1  
		WR_ITR_1  
		WD_ITR_EFF_BEG_1  
		WC_ITR_TYP_2  
		WX_ITR_TYP_2  
		WR_ITR_2  
		WD_ITR_EFF_BEG_2  
		DM_PRS_1  
		DM_PRS_MID  
		DM_PRS_LST  
		DM_PRS_LST_SFX  
		DI_PHN_VLD  
		DN_DOM_PHN_ARA  
		IF_GTR  
		LF_LON_OWN_CUR  
		LF_DOE_SCL_ORG  
		LF_DOE_SCL_ENR_CUR  
		LF_GTR_RFR  
		LD_END_GRC_PRD  
		LC_ELG_SIN  
		WX_ELG_SIN  
		LF_CUR_POR  
		LF_OWN_ORG_POR  
		LC_LOC_PNT  
		WX_LOC_PNT  
		LD_OWN_EFF_SR  
		WC_ISL_DLQ_CAT  
		WX_ISL_DLQ_CAT  
		WC_INT_DLQ_CAT  
		WX_INT_DLQ_CAT  
		WA_ORG_PRI  
		WN_ATV_DSB  
		WN_ACL_DSB  
		WN_ANT_DSB  
		WC_LON_STA  
		WX_LON_STA  
		WC_LON_SUB_STA  
		WX_LON_SUB_STA  
		WC_LON_CLM_STA  
		WX_LON_CLM_STA  
		WC_BR_PRS_STA  
		WX_BR_PRS_STA  
		LC_DFR_TYP  
		WX_DFR_TYP  
		LC_FOR_TYP  
		WX_FOR_TYP  
		LC_FOR_SUB_TYP  
		WX_FOR_SUB_TYP  
		LC_TYP_SCH_DIS  
		WX_TYP_SCH_DIS  
		LD_NTF_SCL_SPR  
		LD_SPA_STP  
		LD_SPA_STP_ENT  
		LD_SPA_RTT  
		LD_SPA_RTT_ENT  
		WA_ACR_BRI_MTT  
		WA_CUR_LTE_FEE  
		WA_PRV_LTE_FEE  
		LC_ST_BR_RSD_APL  
		LC_STA_NEW_BR  
		WF_NON_PR_ACT_REQ  
		WD_FNL_DMD_BR  
		WD_FNL_DMD_EDS  
		LC_IND_BIL_SNT  
		LC_BIL_MTD  
		LD_DSB  
		WA_LST_DSB_WK  
		WI_LON_FUL_DSB_WK  

	)
;

%FINISH;
