/*THIS SPECIFICIES WHAT DIRECTORY TO READ REPORTS FROM AND WHICH DATABASE TO UPDATE.*/
/*LIVE*/
%INCLUDE "X:\Sessions\Local SAS Schedule\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas";
%LET REPORT = X:\PADD\FTP;

/*TEST*/
/*%INCLUDE "X:\PADU\SAS\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas" ;
%LET REPORT = T:\SAS;*/

%FILECHECK(8);

DATA PD10(drop=trunc) ;
	INFILE REPORT8 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
	INPUT DF_SPE_ACC_ID :$10. BF_SSN :$9. DM_PRS_1 :$13. DM_PRS_LST :$23. DM_PRS_MID :$13. DD_BRT :$10.;
%TRUNCAT(8,DF_SPE_ACC_ID);
RUN;
%copyerror;

PROC SORT DATA=PD10 ; BY DF_SPE_ACC_ID; RUN;
DATA PD10; SET PD10; BY DF_SPE_ACC_ID; IF LAST.DF_SPE_ACC_ID; RUN;

%ENCHILADA(PD10,PD10_BORROWER,DF_SPE_ACC_ID,BF_SSN DM_PRS_1 DM_PRS_LST DM_PRS_MID DD_BRT ,);

%GOODBYE_NULL(PD10_BORROWER,DM_PRS_1,'');
%GOODBYE_NULL(PD10_BORROWER,DM_PRS_LST,'');
%GOODBYE_NULL(PD10_BORROWER,DM_PRS_MID,'');
%GOODBYE_NULL(PD10_BORROWER,DD_BRT,'');

%FINISH;
