SELECT 
	LNXX.BF_SSN,
    LNXX.LN_SEQ,
    LNXX.LN_FAT_SEQ,
    ADXX.LD_FAT_ADJ_REQ,
    ADXX.LN_SEQ_FAT_ADJ_REQ
FROM 
	CDW..ADXX_PCV_ATY_ADJ ADXX 
	INNER JOIN CDW..LNXX_FIN_ATY LNXX
		ON ADXX.BF_SSN = LNXX.BF_SSN
		AND ADXX.LN_SEQ = LNXX.LN_SEQ
WHERE 
	ADXX.LC_TYP_FAT_ADJ_REQ = 'XX'
	AND ADXX.LC_STA_FAT_ADJ_REQ = 'A'
	AND LNXX.PC_FAT_TYP = 'XX'
	AND LNXX.PC_FAT_SUB_TYP = 'XX'
	AND YEAR(LNXX.LD_FAT_EFF) = XXXX
	AND LNXX.LD_FAT_EFF < 'XX/XX/XXXX'
	AND LNXX.LC_STA_LONXX = 'A'
	AND ISNULL(LNXX.LC_FAT_REV_REA,'') = ''
	AND ADXX.LD_FAT_ADJ_REQ_BEG = LNXX.LD_FAT_EFF
	AND (COALESCE(ADXX.LA_FAT_ADJ_CUR_PRI, X)
     + COALESCE(ADXX.LA_FAT_ADJ_ILG_PRI, X)
     + COALESCE(ADXX.LA_FAT_ADJ_NSI, X)) =
      (COALESCE(LNXX.LA_FAT_CUR_PRI, X)
     + COALESCE(LNXX.LA_FAT_ILG_PRI, X)
     + COALESCE(LNXX.LA_FAT_NSI, X))
  