USE CDW
GO

SELECT
	PDXX.DM_PRS_X,
	PDXX.DM_PRS_LST,
	PDXX.DF_PRS_ID, 
	AYXX.PF_REQ_ACT
FROM
	CDW..PDXX_PRS_NME PDXX
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	INNER JOIN CDW..AYXX_BR_LON_ATY AYXX
		ON AYXX.BF_SSN = LNXX.BF_SSN
WHERE
	AYXX.PF_REQ_ACT = 'DIFCR'
	AND LNXX.LF_DOE_SCL_ORG IN ('XXXXXXXX')
