USE CDW
GO

SELECT
	PD10.DF_SPE_ACC_ID AS BORROWER_ACCOUNT_NUMBER,
	PD10E.DF_SPE_ACC_ID AS ENDORSER_ACCOUNT_NUMBER,
	LN10.LN_SEQ AS LOAN_SEQ,
	LN10.IC_LON_PGM AS LOAN_TYPE
FROM
	CDW..LN20_EDS LN20
	INNER JOIN CDW..LN10_LON LN10
		ON LN10.BF_SSN = LN20.BF_SSN
		AND LN10.LN_SEQ = LN20.LN_SEQ
	INNER JOIN CDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = LN10.BF_SSN
	INNER JOIN CDW..PD10_PRS_NME PD10E
		ON PD10E.DF_PRS_ID = LN20.LF_EDS
WHERE
	LN20.LC_EDS_TYP = 'S'
	AND LN10.LC_STA_LON10 = 'R'
	AND LN10.LA_CUR_PRI > 0.00
ORDER BY
	BORROWER_ACCOUNT_NUMBER,
	LOAN_SEQ