SELECT DISTINCT
	PDXX.DF_SPE_ACC_ID,
	LNXX.LN_SEQ,
	LNXX.LD_DSB,
	Student.LD_SCL_SPR,
	LNXX.LF_DOE_SCL_ORG
FROM
	CDW..PDXX_PRS_NME PDXX
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	INNER JOIN CDW..LNXX_DSB LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
		AND LNXX.LC_STA_LONXX = 'X'
	INNER JOIN 
	(
		SELECT
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			SDXX.LN_STU_SPR_SEQ,
			SDXX.LC_REA_SCL_SPR,
			SDXX.LD_SCL_SPR
		FROM
			CDW..SDXX_STU_SPR SDXX
			INNER JOIN CDW..LNXX_LON_STU_OSD LNXX
				ON LNXX.LF_STU_SSN = SDXX.LF_STU_SSN
				AND LNXX.LN_STU_SPR_SEQ = SDXX.LN_STU_SPR_SEQ
				AND LNXX.LC_STA_LONXX = 'A'
			INNER JOIN 
			(
				SELECT
					LNXX.BF_SSN,
					LNXX.LN_SEQ,
					MAX(SDXX.LN_STU_SPR_SEQ) AS LN_STU_SPR_SEQ
				FROM
					CDW..SDXX_STU_SPR SDXX
					INNER JOIN CDW..LNXX_LON_STU_OSD LNXX
						ON LNXX.LF_STU_SSN = SDXX.LF_STU_SSN
						AND LNXX.LN_STU_SPR_SEQ = SDXX.LN_STU_SPR_SEQ
						AND LNXX.LC_STA_LONXX = 'A'
				WHERE
					SDXX.LC_STA_STUXX = 'A'
				GROUP BY 
					LNXX.BF_SSN,
					LNXX.LN_SEQ
			) MaxRec
				ON MaxRec.BF_SSN = LNXX.BF_SSN
				AND MaxRec.LN_SEQ = LNXX.LN_SEQ
				AND MaxRec.LN_STU_SPR_SEQ = SDXX.LN_STU_SPR_SEQ
		WHERE
			SDXX.LC_STA_STUXX = 'A'
			AND SDXX.LD_SCL_SPR <= CAST(GETDATE() AS DATE)
	) Student
		ON Student.BF_SSN = LNXX.BF_SSN
		AND Student.LN_SEQ = LNXX.LN_SEQ
WHERE
	LNXX.IC_LON_PGM IN('DLSTFD','DLUNST')
	AND LNXX.LC_STA_LONXX = 'R'
	AND LNXX.LA_CUR_PRI > X.XX
	AND CAST(LNXX.LD_DSB AS DATE) > CAST(DATEADD(DAY,XXX,Student.LD_SCL_SPR) AS DATE)
ORDER BY
	PDXX.DF_SPE_ACC_ID,
	LNXX.LN_SEQ

SELECT DISTINCT
	PDXX.DF_SPE_ACC_ID,
	WQXX.WF_USR_ASN_TSK,
	WQXX.WF_USR_ASN_BY_TSK
FROM
	CDW..WQXX_TSK_QUE WQXX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = WQXX.BF_SSN
WHERE
	WQXX.WF_QUE = 'BX'
	AND WQXX.WC_STA_WQUEXX NOT IN ('X','C')
