USE CDW
GO

SELECT
*
FROM
(
SELECT
	DF_SPE_ACC_ID,
	POP.LN_SEQ,
	LA_DSB,
	ISNULL(LA_DSB_CAN,X) AS LA_DSB_CAN,
	SUM(ISNULL(LA_DSB,X) - ISNULL(LA_DSB_CAN,X)) OVER(PARTITION BY POP.DF_SPE_ACC_ID, POP.LN_SEQ) AS TOTAL_DSB,
	LNXX.LA_CUR_PRI AS CURRENT_BALANCE
FROM
(
SELECT DISTINCT
	LNXX.BF_SSN,
	PDXX.DF_SPE_ACC_ID,
	LNXX.LN_SEQ,
	LA_DSB,
	LA_DSB_CAN
FROM
	CDW..LNXX_DSB LNXX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = LNXX.BF_SSN
) POP
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = POP.BF_SSN
		AND LNXX.LN_SEQ = POP.LN_SEQ
WHERE
	LNXX.LA_CUR_PRI > X.XX
) FINAL
	WHERE FINAL.TOTAL_DSB = X