USE CDW
GO

SELECT
	PDXX.DF_SPE_ACC_ID,
	LNXX.LN_SEQ,
	lnXX.LA_CUR_PRI,
	grXX.WC_NDS_RPT_STA
FROM
	CDW..GRXX_RPT_LON_APL GRXX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = GRXX.BF_SSN
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = GRXX.BF_SSN
		AND LNXX.LN_SEQ = GRXX.LN_SEQ
WHERE
	LNXX.LA_CUR_PRI > X.XX
	and WC_NDS_RPT_STA = 'C'