set transaction isolation level read uncommitted
DROP TABLE IF EXISTS #DATA


select distinct
	DWXX.bf_ssn AS SSN,
	DWXX.ln_seq AS LOAN_SEQ,
	LNXX.IC_LON_PGM AS LOAN_PGM,
	COALESCE(NULLIF(DWXX.WX_OVR_DW_LON_STA,''),LKXX.PX_DSC_MDM, dwXX.WC_DW_LON_STA) AS LOAN_STATUS,
	rsXX.LD_SNT_RPD_DIS AS DISCLOSURE_PRINT_DATE,
	ISNULL(LNXX.LN_DLQ_MAX,X) AS DAYS_PAST_DUE,
	CASE WHEN LNXX.BF_SSN IS NOT NULL THEN 'Y' ELSE 'N' END AS MADE_PAYMENT_AFTER_DISCLOSER_DATE,
	ISNULL(CONVERT(VARCHAR(XX), LAST_CONTACT.LD_ATY_REQ_RCV , XXX),'N/A') AS LAST_CONTACT,
	dwXX.WD_LON_RPD_SR,
	lnXX.LD_END_GRC_PRD,

	rsXX.LD_RPS_X_PAY_DU,
	lnXX.LD_PIF_RPT,
	LNXX.LA_CUR_PRI,
	LNXX.LA_LON_AMT_GTR,
	
	CASE WHEN LNXXD.BF_SSN IS NOT NULL THEN LNXXD.LD_FAT_EFF ELSE NULL END AS DECON_DATE,
	lnXX.LD_CRT_LONXX
	--count(distinct dwXX.bf_ssn) as c
INTO #DATA
from
	cdw..DWXX_DW_CLC_CLU dwXX
	inner join cdw..LNXX_LON lnXX
		on lnXX.BF_SSN = dwXX.bf_ssn
		and lnXX.LN_SEQ = dwXX.LN_SEQ
	inner join cdw..PDXX_PRS_NME pdXX
		on pdXX.DF_PRS_ID = dwXX.BF_SSN
	inner join
	(
		select
			bf_ssn,
			count(*) as lc
		from
			cdw..LNXX_LON lnXX
		where
			LNXX.LD_LON_ACL_ADD > 'XX/XX/XXXX'
		group by
			bf_ssn
	)lc
		on lc.BF_SSN = dwXX.BF_SSN
	left join cdw..AYXX_BR_LON_ATY ayXX
		on ayXX.BF_SSN = dwXX.BF_SSN
		and ayXX.PF_REQ_ACT = 'MSRPD'
	left join cls.[print].PrintProcessing pp
		on pp.AccountNumber = pdXX.DF_SPE_ACC_ID
		and pp.ScriptDataId in (X,X)
	LEFT JOIN CDW..LNXX_LON_DLQ_HST LNXX
		ON LNXX.BF_SSN = DWXX.BF_SSN
		AND LNXX.LN_SEQ = DWXX.LN_SEQ
		AND LNXX.LC_STA_LONXX = 'X'
	left JOIN 
	(
		SELECT	
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			MIN(RSXX.LN_RPS_SEQ) AS LN_RPS_SEQ
		FROM
			CDW..LNXX_LON LNXX
			INNER JOIN CDW..RSXX_BR_RPD RSXX
				ON RSXX.BF_SSN = LNXX.BF_SSN
				AND RSXX.LD_SNT_RPD_DIS > LNXX.LD_LON_EFF_ADD
		GROUP BY
			LNXX.BF_SSN,
			LNXX.LN_SEQ
	)RPD
		ON RPD.BF_SSN = DWXX.BF_SSN
		AND RPD.LN_SEQ = DWXX.LN_SEQ
	left join cdw..RSXX_BR_RPD rsXX
		on rsXX.BF_SSN = dwXX.BF_SSN
		and rsXX.LN_RPS_SEQ = RPD.LN_RPS_SEQ
	left join cdw..LNXX_LON_RPS lnXX
		on lnXX.BF_SSN = rsXX.BF_SSN
		and lnXX.LN_RPS_SEQ = rsXX.LN_RPS_SEQ
	LEFT JOIN CDW..LNXX_FIN_ATY LNXX
		ON LNXX.BF_SSN = DWXX.BF_SSN
		AND LNXX.LN_SEQ = DWXX.LN_SEQ
		AND LNXX.PC_FAT_TYP = 'XX'
		AND LNXX.PC_FAT_SUB_TYP = 'XX'
		AND LNXX.LD_FAT_EFF > ISNULL(rsXX.LD_SNT_RPD_DIS,RSXX.LD_RPS_X_PAY_DU)
	LEFT JOIN OPENQUERY(LEGEND, 'SELECT PX_DSC_MDM, PX_ATR_VAL FROM PKUB.LKXX_LS_CDE_LKP WHERE PM_ATR = ''WC-DW-LON-STA''') LKXX
		ON LKXX.PX_ATR_VAL = dwXX.WC_DW_LON_STA
	LEFT JOIN
	(
		SELECT
			BF_SSN,
			MAX(LD_ATY_REQ_RCV) AS LD_ATY_REQ_RCV
		FROM
			CDW..AYXX_BR_LON_ATY
		WHERE
			PF_REQ_ACT = 'DDPHN'
			AND PF_RSP_ACT = 'CNTCT'
		GROUP BY
			BF_SSN
	)LAST_CONTACT
		ON LAST_CONTACT.BF_SSN = DWXX.BF_SSN
		AND LAST_CONTACT.LD_ATY_REQ_RCV > ISNULL(RSXX.LD_RTN_RPD_DIS,RSXX.LD_RPS_X_PAY_DU)
	LEFT JOIN
	(
		SELECT
			LNXX.*
		FROM
			CDW..LNXX_FIN_ATY LNXX
			INNER JOIN
			(
				SELECT
					BF_SSN,
					LN_SEQ,
					MAX(LN_FAT_SEQ) AS LN_FAT_SEQ
				FROM
					CDW..LNXX_FIN_ATY
				WHERE
					PC_FAT_TYP = 'XX'
					AND PC_FAT_SUB_TYP = 'XX'
					AND ISNULL(LC_FAT_REV_REA,'') = ''
				GROUP BY
					BF_SSN,
					LN_SEQ
			)MSEQ
				ON MSEQ.BF_SSN = LNXX.BF_SSN
				AND MSEQ.LN_SEQ	= LNXX.LN_SEQ
				AND MSEQ.LN_FAT_SEQ = LNXX.LN_FAT_SEQ
		) LNXXD
			ON LNXXD.BF_SSN = DWXX.BF_SSN
			AND LNXXD.LN_SEQ = DWXX.LN_SEQ
where
	(
		DWXX.WC_DW_LON_STA  IN ('XX','XX')
		OR
		(DWXX.WC_DW_LON_STA = 'XX' AND LNXX.IC_LON_PGM NOT IN ('DLPLGB', 'DLPLUS', 'PLUS', 'PLUSGB') )
	)
	AND AYXX.BF_SSN IS NULL
	AND pp.AccountNumber IS NULL
	AND LNXX.LD_LON_ACL_ADD > 'XX/XX/XXXX'
	AND RSXX.BF_SSN IS NOT NULL
	AND ISNULL(RSXX.LD_SNT_RPD_DIS,RSXX.LD_RPS_X_PAY_DU) < 'XX/XX/XXXX'

SELECT *  FROM #DATA

WHERE

	  DECON_DATE IS NULL
	OR
	(
		
		DECON_DATE > LD_END_GRC_PRD
	)

order by 
	DISCLOSURE_PRINT_DATE

