
SELECT
	COUNT(*)
FROM
(
SELECT DISTINCT
	DF_PRS_ID
FROM
	CDW..PD30_PRS_ADR PD30
	INNER JOIN CDW..LN10_LON LN10
		ON LN10.BF_SSN = PD30.DF_PRS_ID
WHERE
	DC_DOM_ST = 'CA'
	AND DC_ADR = 'L'
	AND DD_VER_ADR <= '12/31/2018'
	AND DI_VLD_ADR = 'Y'

UNION ALL

SELECT DISTINCT
	PD31.DF_PRS_ID

FROM
	CDW..PD31_PRS_INA PD31
	INNER JOIN CDW..LN10_LON LN10
		ON LN10.BF_SSN = PD31.DF_PRS_ID
	INNER JOIN
	(
		SELECT
			DF_PRS_ID,
			MAX(DN_ADR_SEQ) AS DN_ADR_SEQ
		FROM
			CDW..PD31_PRS_INA
		WHERE
			DD_VER_ADR_HST <= '12/31/2018'
			AND DC_ADR_HST = 'L'
		GROUP BY
			DF_PRS_ID
	) MPD31
		ON MPD31.DF_PRS_ID = PD31.DF_PRS_ID
		AND MPD31.DN_ADR_SEQ = PD31.DN_ADR_SEQ
WHERE
	DC_DOM_ST_HST = 'CA'
) POP