SELECT
	*
FROM OPENQUERY
(
	LEGEND,
	'
		SELECT
			BF_SSN,
			LN_SEQ
		FROM
			PKUB.LNXX_LON
		WHERE
			LF_DOE_SCL_ORG IN(''XXXXXXX'',''XXXXXXX'',''XXXXXXX'',''XXXXXXX'',''XXXXXXX'',''XXXXXXX'',''XXXXXXX'')
	'
)
