SELECT DISTINCT
	LTRIM(RTRIM(PDXX.DM_PRS_X)) + ' ' + LTRIM(RTRIM(PDXX.DM_PRS_LST)) AS Name,
	PDXX.DF_SPE_ACC_ID,
	MAX(LNXX.LN_DLQ_MAX) AS Delinquency
FROM
	CDW..PDXX_PRS_NME PDXX
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
		AND LNXX.IC_LON_PGM = 'DLPLUS'
	INNER JOIN CDW..DWXX_DW_CLC_CLU DWXX
		ON DWXX.BF_SSN = LNXX.BF_SSN
		AND DWXX.WC_DW_LON_STA ='XX'
	INNER JOIN CDW..DWXX_DW_CLC_CLU DWXXX
		ON DWXXX.BF_SSN = LNXX.BF_SSN
		AND DWXXX.WC_DW_LON_STA = 'XX'
	LEFT JOIN CDW..LNXX_LON_DLQ_HST LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
		AND LNXX.LC_STA_LONXX = 'X'
GROUP BY
	PDXX.DF_SPE_ACC_ID,
	PDXX.DM_PRS_X,
	PDXX.DM_PRS_LST
