SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SELECT
	PDXX.DF_SPE_ACC_ID,
	PDXX.DM_PRS_X,
	PDXX.DM_PRS_LST,
	PDXX.DC_PHN,
	ISNULL(PDXX.DN_DOM_PHN_ARA,'') + ISNULL(PDXX.DN_DOM_PHN_XCH,'') + ISNULL(PDXX.DN_DOM_PHN_LCL,'') AS Phone,
	PDXX.DX_STR_ADR_X,
	PDXX.DX_STR_ADR_X,
	PDXX.DX_STR_ADR_X,
	PDXX.DM_CT,
	PDXX.DC_DOM_ST,
	PDXX.DF_ZIP_CDE,
	LNXX.LN_DLQ_MAX
FROM
	CDW..LNXX_LON LNXX
	INNER JOIN CDW..LNXX_LON_RPS LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
		AND LNXX.LC_TYP_SCH_DIS IN('IL','IA','IP','CQ','CP')
		AND LNXX.LC_STA_LONXX = 'A'
		AND CAST(LNXX.LF_LST_DTS_LNXX AS DATE) BETWEEN CAST(DATEADD(DAY,-XX,GETDATE()) AS DATE) AND CAST(DATEADD(DAY,-XX,GETDATE()) AS DATE)
	INNER JOIN CDW..LNXX_LON_DLQ_HST LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
		AND LNXX.LC_STA_LONXX = 'X'
		AND LNXX.LN_DLQ_MAX BETWEEN XX AND XX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = LNXX.BF_SSN
	LEFT JOIN CDW..PDXX_PRS_PHN PDXX
		ON PDXX.DF_PRS_ID = LNXX.BF_SSN
		AND PDXX.DI_PHN_VLD ='Y'
	LEFT JOIN CDW..PDXX_PRS_ADR PDXX
		ON PDXX.DF_PRS_ID = LNXX.BF_SSN
		AND PDXX.DC_ADR = 'L'
		AND PDXX.DI_VLD_ADR = 'Y'
WHERE
	LNXX.LA_CUR_PRI > X
	AND LNXX.LC_STA_LONXX = 'R'
ORDER BY
	LNXX.LF_LST_DTS_LNXX