LIBNAME  LEGEND  REMOTE  SERVER=LEGEND SLIBREF=work  ;
RSUBMIT LEGEND;
%let DB = DNFPUTDL;  *This is live;
LIBNAME PKUB DBX DATABASE=&DB OWNER=PKUB;

PROC SQL INOBS = XXX;
	CONNECT TO DBX (DATABASE=&DB);

	CREATE TABLE CXX AS
		SELECT	
			*
		FROM	
			CONNECTION TO DBX 
				(
					SELECT DISTINCT
						A.BF_SSN
					FROM
						PKUB.LNXX_LON_RPS A
						JOIN PKUB.LNXX_LON_RPS B
							ON A.BF_SSN = B.BF_SSN
							AND A.LN_SEQ = B.LN_SEQ
						JOIN PKUB.LNXX_LON LNXX
							ON A.BF_SSN = LNXX.BF_SSN
							AND A.LN_SEQ = LNXX.LN_SEQ
							AND LNXX.LA_CUR_PRI > X
							AND LNXX.LC_STA_LONXX = 'R'
					WHERE
						A.LC_STA_LONXX = 'A'
						AND B.LC_STA_LONXX = 'A'
						AND A.LC_TYP_SCH_DIS <> B.LC_TYP_SCH_DIS
						AND A.LN_RPS_SEQ <> B.LN_RPS_SEQ

					FOR READ ONLY WITH UR
				)
	;

	CREATE TABLE CXX AS
		SELECT	
			*
		FROM	
			CONNECTION TO DBX 
				(
					SELECT DISTINCT
						LNXX.BF_SSN
					FROM
						PKUB.LNXX_LON LNXX
						LEFT JOIN PKUB.LNXX_LON_RPS LNXX
							ON LNXX.BF_SSN = LNXX.BF_SSN
							AND LNXX.LN_SEQ = LNXX.LN_SEQ
							AND LNXX.LA_CUR_PRI > X
							AND LNXX.LC_STA_LONXX = 'R'
							AND LNXX.LC_STA_LONXX = 'A'
					WHERE
						LNXX.BF_SSN IS NULL
						OR LNXX.LC_RPD_INA_REA <> ''

					FOR READ ONLY WITH UR
				)
	;

	CREATE TABLE CXX AS
		SELECT	
			*
		FROM	
			CONNECTION TO DBX 
				(
					SELECT DISTINCT
						LNXX.BF_SSN
					FROM
						PKUB.LNXX_LON LNXX
						JOIN PKUB.LNXX_LON_RPS LNXX
							ON LNXX.BF_SSN = LNXX.BF_SSN
							AND LNXX.LN_SEQ = LNXX.LN_SEQ
							AND LNXX.LA_CUR_PRI > X
							AND LNXX.LC_STA_LONXX = 'R'
							AND LNXX.LC_STA_LONXX = 'A'
							AND LNXX.LC_TYP_SCH_DIS IN ('IL', 'CP', 'CQ')

					FOR READ ONLY WITH UR
				)
	;

	CREATE TABLE CXX AS
		SELECT	
			*
		FROM	
			CONNECTION TO DBX 
				(
					SELECT DISTINCT
						LNXX.BF_SSN
					FROM
						PKUB.LNXX_LON LNXX
						JOIN PKUB.LNXX_LON_RPS LNXX
							ON LNXX.BF_SSN = LNXX.BF_SSN
							AND LNXX.LN_SEQ = LNXX.LN_SEQ
							AND LNXX.LA_CUR_PRI > X
							AND LNXX.LC_STA_LONXX = 'R'
							AND LNXX.LC_STA_LONXX = 'A'
							AND LNXX.LC_TYP_SCH_DIS IN ('IB','CX','CX','CX','CA')
						JOIN PKUB.RSXX_IBR_RPS RSXX
							ON LNXX.BF_SSN = RSXX.BF_SSN
							AND DAYS(RSXX.BD_ANV_QLF_IBR) <= DAYS(CURRENT_DATE) + XX

					FOR READ ONLY WITH UR
				)
	;

	CREATE TABLE CXX AS
		SELECT	
			*
		FROM	
			CONNECTION TO DBX 
				(
					SELECT DISTINCT
						LNXX.BF_SSN
					FROM
						PKUB.LNXX_LON LNXX
						JOIN PKUB.LNXX_LON_RPS LNXX
							ON LNXX.BF_SSN = LNXX.BF_SSN
							AND LNXX.LN_SEQ = LNXX.LN_SEQ
							AND LNXX.LA_CUR_PRI > X
							AND LNXX.LC_STA_LONXX = 'R'
							AND LNXX.LC_STA_LONXX = 'A'
							AND LNXX.LC_TYP_SCH_DIS IN ('IB','CX','CX','CX','CA')
						JOIN PKUB.RSXX_IBR_RPS RSXX
							ON LNXX.BF_SSN = RSXX.BF_SSN
							AND DAYS(RSXX.BD_ANV_QLF_IBR) > DAYS(CURRENT_DATE) + XX

					FOR READ ONLY WITH UR
				)
	;

	CREATE TABLE CXX AS
		SELECT	
			*
		FROM	
			CONNECTION TO DBX 
				(
					SELECT DISTINCT
						LNXX.BF_SSN
					FROM
						PKUB.LNXX_LON LNXX
						JOIN PKUB.LNXX_LON_RPS LNXX
							ON LNXX.BF_SSN = LNXX.BF_SSN
							AND LNXX.LN_SEQ = LNXX.LN_SEQ
							AND LNXX.LA_CUR_PRI > X
							AND LNXX.LC_STA_LONXX = 'R'
							AND LNXX.LC_STA_LONXX = 'A'
						JOIN PKUB.RSXX_BR_RPD A
							ON LNXX.BF_SSN = A.BF_SSN
							AND A.LC_STA_RPSTXX = 'A'
						JOIN PKUB.RSXX_BR_RPD B
							ON LNXX.BF_SSN = B.BF_SSN
							AND B.LC_STA_RPSTXX = 'A'
					WHERE
						DAY(A.LD_RPS_X_PAY_DU) <> DAY(B.LD_RPS_X_PAY_DU)

					FOR READ ONLY WITH UR
				)
	;

	CREATE TABLE CXX AS
		SELECT	
			*
		FROM	
			CONNECTION TO DBX 
				(
					SELECT DISTINCT
						LNXX.BF_SSN
					FROM
						PKUB.LNXX_LON LNXX
						JOIN PKUB.LNXX_LON_RPS LNXX
							ON LNXX.BF_SSN = LNXX.BF_SSN
							AND LNXX.LN_SEQ = LNXX.LN_SEQ
							AND LNXX.LA_CUR_PRI > X
							AND LNXX.LC_STA_LONXX = 'R'
							AND LNXX.LC_STA_LONXX = 'A'
					WHERE
						LNXX.LD_LON_X_DSB < 'XXXX-XX-XX'
						AND LNXX.LC_TYP_SCH_DIS IN ('EL','EG')

					FOR READ ONLY WITH UR
				)
	;

	CREATE TABLE CXX AS
		SELECT	
			*
		FROM	
			CONNECTION TO DBX 
				(
					SELECT DISTINCT
						A.BF_SSN
					FROM
						PKUB.LNXX_LON A
						JOIN PKUB.LNXX_LON B
							ON A.BF_SSN = B.BF_SSN
							AND A.LA_CUR_PRI > X
							AND A.LC_STA_LONXX = 'R'
							AND B.LA_CUR_PRI > X
							AND B.LC_STA_LONXX = 'R'
					WHERE
						A.IC_LON_PGM IN ('DLPLUS','DLPCNS')
						AND B.IC_LON_PGM IN ('DLSTFD','DLUNST')

					FOR READ ONLY WITH UR
				)
	;

	CREATE TABLE CXX AS
		SELECT	
			*
		FROM	
			CONNECTION TO DBX 
				(
					SELECT DISTINCT
						LNXX.BF_SSN
					FROM
						PKUB.LNXX_LON LNXX
					WHERE
						LNXX.LC_STA_LONXX = 'R'
					GROUP BY
						BF_SSN
					HAVING
						SUM(LNXX.LA_CUR_PRI) > XXXXX

					FOR READ ONLY WITH UR
				)
	;

	DISCONNECT FROM DBX;

QUIT;

ENDRSUBMIT;

DATA CXX; SET LEGEND.CXX; RUN;
DATA CXX; SET LEGEND.CXX; RUN;
DATA CXX; SET LEGEND.CXX; RUN;
DATA CXX; SET LEGEND.CXX; RUN;
DATA CXX; SET LEGEND.CXX; RUN;
DATA CXX; SET LEGEND.CXX; RUN;
DATA CXX; SET LEGEND.CXX; RUN;
DATA CXX; SET LEGEND.CXX; RUN;
DATA CXX; SET LEGEND.CXX; RUN;

%MACRO TOFILE(FILE);
	PROC EXPORT
			DATA = &FILE
			OUTFILE = 'T:\SAS\NH XXXX.XLS'
			REPLACE;
		SHEET = &FILE;
	RUN;
%MEND;

%TOFILE(CXX);
%TOFILE(CXX);
%TOFILE(CXX);
%TOFILE(CXX);
%TOFILE(CXX);
%TOFILE(CXX);
%TOFILE(CXX);
%TOFILE(CXX);
%TOFILE(CXX);
