LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
	CREATE TABLE LTRS AS
		SELECT DISTINCT
			PDXX.DF_PRS_ID,
			PDXX.DF_SPE_ACC_ID,
			PDXX.DM_PRS_X,
			PDXX.DM_PRS_MID,
			PDXX.DM_PRS_LST,
			PDXX.DC_ADR,
			PDXX.DX_STR_ADR_X,
			PDXX.DX_STR_ADR_X,
			PDXX.DM_CT,
			PDXX.DC_DOM_ST,
			PDXX.DF_ZIP_CDE,
			PDXX.DM_FGN_CNY,
			PDXX.DM_FGN_ST
		FROM
			PKUB.LNXX_LON LNXX
			JOIN PKUB.PDXX_PRS_NME PDXX
				ON LNXX.BF_SSN = PDXX.DF_PRS_ID
				AND LNXX.LA_CUR_PRI > X.XX
				AND LNXX.LC_STA_LONXX = 'R'
			JOIN PKUB.PDXX_PRS_ADR PDXX
				ON LNXX.BF_SSN = PDXX.DF_PRS_ID
			LEFT JOIN PKUB.PDXX_PRS_ADR_EML PDXX
				ON LNXX.BF_SSN = PDXX.DF_PRS_ID
				AND PDXX.DC_STA_PDXX = 'A'
				AND PDXX.DI_VLD_ADR_EML = 'Y'
		WHERE
			PDXX.DF_PRS_ID IS NULL
		ORDER BY
			PDXX.DC_DOM_ST
	;
QUIT;
ENDRSUBMIT;

DATA LTRS; SET LEGEND.LTRS; RUN;


*CALCULATE KEYLINE;
DATA KLTRS (DROP = KEYSSN MODAY KEYLINE CHKDIG DIG I CHKDIG CHKX CHKX CHKX CHKDIGIT CHECK DF_PRS_ID DC_ADR);
	SET LTRS;

	FORMAT CURRENT_DATE MMDDYYXX.;

	KEYSSN = TRANSLATE(DF_PRS_ID,'MYLAUGHTER','XXXXXXXXXX');
	MODAY = PUT(DATE(),MMDDYYNX.);
	KEYLINE = "P"||KEYSSN||MODAY||DC_ADR;
	CHKDIG = X;
	LENGTH DIG $X.;
	DO I = X TO LENGTH(KEYLINE);
		IF I/X NE ROUND(I/X,X) 
			THEN DIG = PUT(INPUT(SUBSTR(KEYLINE,I,X),BITSX.X) * X, X.);
		ELSE DIG = PUT(INPUT(SUBSTR(KEYLINE,I,X),BITSX.X), X.);
		IF SUBSTR(DIG,X,X) = " " 
			THEN CHKDIG = CHKDIG + INPUT(SUBSTR(DIG,X,X),X.);
			ELSE DO;
				CHKX = INPUT(SUBSTR(DIG,X,X),X.);
				CHKX = INPUT(SUBSTR(DIG,X,X),X.);
				IF CHKX + CHKX >= XX
					THEN DO;
						CHKX = PUT(CHKX + CHKX,X.);
						CHKX = INPUT(SUBSTR(CHKX,X,X),X.);
						CHKX = INPUT(SUBSTR(CHKX,X,X),X.);
					END;
				CHKDIG = CHKDIG + CHKX + CHKX;
			END;
	END;
	CHKDIGIT = XX - INPUT(SUBSTR((RIGHT(PUT(CHKDIG,X.))),X,X),X.);
	IF CHKDIGIT = XX THEN CHKDIGIT = X;
	CHECK = PUT(CHKDIGIT,X.);
	ACSKEY = "#"||KEYLINE||CHECK||"#";
	CURRENT_DATE = TODAY();

	LABEL
		DF_SPE_ACC_ID = 'ACCT NO'
		DM_PRS_X = 'FIRST NAME'
		DM_PRS_MID = 'MIDDLE INITIAL'
		DM_PRS_LST = 'LAST NAME'
		DX_STR_ADR_X = 'STREET X'
		DX_STR_ADR_X = 'STREET X'
		DM_CT = 'CITY'
		DC_DOM_ST = 'STATE'
		DF_ZIP_CDE = 'ZIP'
		DM_FGN_CNY = 'FOREIGN COUNTRY'
		DM_FGN_ST = 'FOREIGN STATE'
		ACSKEY = 'ACS KEYLINE'
		CURRENT_DATE = 'CURRENT DATE'
	;
RUN;

PROC EXPORT
		DATA=KLTRS
		OUTFILE='T:\NHXXXX.CSV'
		REPLACE
		LABEL;
RUN;
