LIBNAME XL 'T:\NH XXXX FSA Data.xlsx';
LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;

DATA DISB;
	SET XL.'archived-rdcs_disbursements$'N;
RUN;

DATA ADJ;
	SET XL.'archived-rdcs_adjustments$'N;
RUN;

DATA RDC_AMT;
	SET XL.'rdc-amt$'N;
RUN;

DATA RDC_DISB;
	SET XL.'rdc-disb$'N;
RUN;


DATA LEGEND.DISB; SET DISB; RUN;
DATA LEGEND.ADJ; SET ADJ; RUN;
DATA LEGEND.RDC_AMT; SET RDC_AMT; RUN;
DATA LEGEND.RDC_DISB; SET RDC_DISB; RUN;

RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;

PROC SQL;
	CREATE TABLE CDISB AS
		SELECT DISTINCT
			DISB.*
		FROM
			DISB
			JOIN PKUB.LNXX_LON LNXX
				ON DISB.SSN = LNXX.BF_SSN
	;

	CREATE TABLE CADJ AS
		SELECT DISTINCT
			ADJ.*
		FROM
			ADJ
			JOIN PKUB.LNXX_LON LNXX
				ON ADJ.SSN = LNXX.BF_SSN
	;

	CREATE TABLE CRDC_AMT AS
		SELECT DISTINCT
			RDC.*
		FROM
			RDC_AMT RDC
			JOIN PKUB.FSXX_DL_LON FSXX
				ON RDC.AWARD_ID = CATX('',FSXX.LF_FED_AWD,PUT(LN_FED_AWD_SEQ,ZX.))
	;

	CREATE TABLE CRDC_DISB AS
		SELECT DISTINCT
			RDC.*
		FROM
			RDC_DISB RDC
			JOIN PKUB.FSXX_DL_LON FSXX
				ON RDC.AWARD_ID = CATX('',FSXX.LF_FED_AWD,PUT(LN_FED_AWD_SEQ,ZX.))
	;
QUIT;
ENDRSUBMIT;

DATA CDISB; SET LEGEND.CDISB; RUN;
DATA CADJ; SET LEGEND.CADJ; RUN;
DATA CRDC_AMT; SET LEGEND.CRDC_AMT; RUN;
DATA CRDC_DISB; SET LEGEND.CRDC_DISB; RUN;

PROC EXPORT
		DATA=CDISB
		OUTFILE='T:\SAS\RDC Files.xlsx'
		REPLACE;
	SHEET='archived-rdcs_disbursements';
RUN;

PROC EXPORT
		DATA=CADJ
		OUTFILE='T:\SAS\RDC Files.xlsx'
		REPLACE;
	SHEET='archived-rdcs_adjustments';
RUN;

PROC EXPORT
		DATA=CRDC_AMT
		OUTFILE='T:\SAS\RDC Files.xlsx'
		REPLACE;
	SHEET='rdc-all_amt';
RUN;

PROC EXPORT
		DATA=CRDC_DISB
		OUTFILE='T:\SAS\RDC Files.xlsx'
		REPLACE;
	SHEET='rdc-all_disb';
RUN;
