LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;

PROC SQL;
	CREATE TABLE NHXXXX AS
		SELECT DISTINCT
			PDXX.DF_SPE_ACC_ID,
			PDXX.DM_PRS_LST
		FROM	
			PKUB.PDXX_PRS_NME PDXX
			INNER JOIN PKUB.LNXX_LON LNXX
				ON LNXX.BF_SSN = PDXX.DF_PRS_ID
			INNER JOIN PKUB.BRXX_BR_EFT BRXX
				ON LNXX.BF_SSN = BRXX.BF_SSN
				AND BRXX.BC_EFT_STA = 'A'
			INNER JOIN PKUB.LNXX_EFT_TO_LON LNXX
				ON LNXX.BF_SSN = LNXX.BF_SSN
				AND LNXX.LN_SEQ = LNXX.LN_SEQ
				AND LNXX.BN_EFT_SEQ = BRXX.BN_EFT_SEQ
			INNER JOIN PKUB.PDXX_PRS_ADR_EML PDXX
				ON PDXX.DF_PRS_ID = LNXX.BF_SSN
				AND PDXX.DI_VLD_ADR_EML = 'Y'
				AND PDXX.DC_STA_PDXX = 'A'
		WHERE	
			LNXX.LC_LON_SND_CHC ^= 'Y'
			AND LNXX.LA_CUR_PRI > X.XX
			AND LNXX.LC_STA_LONXX = 'R'
			AND LNXX.LD_EFT_EFF_BEG >= 'XXJANXXXX'D

	;
QUIT;
ENDRSUBMIT;

PROC EXPORT
		DATA=LEGEND.NHXXXX
		OUTFILE='T:\SAS\NH XXXX.XLSX'
		REPLACE;
RUN;
