--X. Multiple open loans, some loans are current, some loans with only partial payments made.


--Output for each scenario:

--SSN
--Borrower First/Last Name
--Loan Sequence #
--Type XX Forbearance End Date
--Delinquency Date (if applicable)
--Effective Payment Date(s) after the type XX forbearance end date (when applicable, if both ACH and Manual for scenario X, list both)

--DROP TABLE IF EXISTS #QUESTIONX
--SELECT 
--	*
--INTO #QUESTIONX
--FROM
--(
--SELECT DISTINCT
--	LNXX.BF_SSN,
--	RTRIM(PDXX.DM_PRS_X) + ' ' + RTRIM(PDXX.DM_PRS_LST) AS [NAME],
--	LNXX.LN_SEQ,
--	LNXX.CUR_DUE,
--	ISNULL(CONVERT(varchar(XX), FORB.LD_FOR_END, XXX),'N/A') AS FORBEARANCE_END_DATE,
--	COUNT(*) OVER (PARTITION BY LNXX.BF_SSN) AS LOAN_COUNT,
--	SUM(LNXX.CUR_DUE) OVER (PARTITION BY LNXX.BF_SSN) AS TOTAL_DUE,
--	LD_FAT_EFF
--FROM
--	CDW..AYXX_BR_LON_ATY AYXX
--	INNER JOIN CDW..PDXX_PRS_NME PDXX
--		ON PDXX.DF_PRS_ID = AYXX.BF_SSN
--	INNER JOIN CDW..LNXX_LON LNXX
--		ON LNXX.BF_SSN = AYXX.BF_SSN
--	INNER JOIN
--	(
--		SELECT
--				LNXX.BF_SSN,
--				LNXX.LN_SEQ,
--				CASE WHEN SUM(COALESCE(LNXX.LA_BIL_CUR_DU,X) - COALESCE(LNXX.LA_TOT_BIL_STS,X)) < X THEN X 
--				ELSE SUM(COALESCE(LNXX.LA_BIL_CUR_DU,X) - COALESCE(LNXX.LA_TOT_BIL_STS,X)) END  AS CUR_DUE,
--				LNXX.LD_FAT_EFF
--			FROM 
--				CDW..LNXX_LON_BIL_CRF LNXX
--				INNER JOIN 
--				(
--					SELECT
--						LNXX.BF_SSN,
--						LNXX.LN_SEQ,
--						MIN(LNXX.LD_BIL_DU_LON) AS LD_BIL_DU_LON
--					FROM 
--						CDW..LNXX_LON_BIL_CRF LNXX
--						INNER JOIN CDW..PDXX_PRS_NME PDXX
--							ON PDXX.DF_PRS_ID = LNXX.BF_SSN
--						INNER JOIN CDW..LNXX_LON LNXX
--							ON LNXX.BF_SSN = LNXX.BF_SSN
--							AND LNXX.LN_SEQ = LNXX.LN_SEQ
						
--					WHERE 
--						LNXX.LC_STA_LONXX = 'A'
--						AND LNXX.LC_LON_STA_BIL = 'X'
--						AND CAST(LNXX.LD_BIL_DU_LON AS DATE) >= CAST(GETDATE() AS DATE)
--						AND LNXX.LC_STA_LONXX IN ('R','L')
--						AND LNXX.LA_CUR_PRI > X
--					GROUP BY 
--						LNXX.BF_SSN,
--						LNXX.LN_SEQ
--				) MIN_DTE
--					ON LNXX.BF_SSN = MIN_DTE.BF_SSN
--						AND LNXX.LN_SEQ = MIN_DTE.LN_SEQ
--						AND LNXX.LD_BIL_DU_LON = MIN_DTE.LD_BIL_DU_LON
--				INNER JOIN CDW..LNXX_BIL_LON_FAT LNXX
--					ON LNXX.BF_SSN = LNXX.BF_SSN
--					AND LNXX.LN_SEQ = LNXX.LN_SEQ
--					AND LNXX.LD_BIL_CRT = LNXX.LD_BIL_CRT
--					AND LNXX.LN_SEQ_BIL_WI_DTE = LNXX.LN_SEQ_BIL_WI_DTE
--					AND LNXX.LN_BIL_OCC_SEQ = LNXX.LN_BIL_OCC_SEQ
--				INNER JOIN CDW..LNXX_FIN_ATY LNXX
--					ON LNXX.BF_SSN = LNXX.BF_SSN
--					AND LNXX.LN_SEQ = LNXX.LN_SEQ
--					AND LNXX.LN_FAT_SEQ = LNXX.LN_FAT_SEQ
--			WHERE 
--				LNXX.LC_STA_LONXX = 'A'
--				AND LNXX.LC_LON_STA_BIL = 'X'
--			GROUP BY 
--				LNXX.BF_SSN,
--				LNXX.LN_SEQ,
--				LNXX.LD_FAT_EFF
--	) LNXX
--		ON LNXX.BF_SSN = LNXX.BF_SSN
--		AND LNXX.LN_SEQ = LNXX.LN_SEQ
--	LEFT JOIN 
--	(
--		SELECT
--			LNXX.*
--		FROM
--			CDW..FBXX_BR_FOR_REQ FBXX
--			INNER JOIN CDW..LNXX_BR_FOR_APV LNXX
--				ON LNXX.BF_SSN = FBXX.BF_SSN
--				AND LNXX.LF_FOR_CTL_NUM = FBXX.LF_FOR_CTL_NUM
--			INNER JOIN CDW..LNXX_LON LNXX
--				ON LNXX.BF_SSN = LNXX.BF_SSN
--				AND LNXX.LN_SEQ = LNXX.LN_SEQ
--				AND LNXX.LA_CUR_PRI > X
--				AND LNXX.LC_STA_LONXX = 'R'
--		WHERE
--			LNXX.LC_STA_LONXX = 'A'
--			AND FBXX.LC_STA_FORXX = 'A'
--			AND FBXX.LC_FOR_STA = 'A' --denied records cant have this active
--			AND LNXX.LC_FOR_RSP != 'XXX'
--			AND FBXX.LC_FOR_TYP = 'XX'
			
--	) FORB
--		ON FORB.BF_SSN = LNXX.BF_SSN
--		AND FORB.LN_SEQ = LNXX.LN_SEQ
--WHERE
--	AYXX.PF_REQ_ACT = 'CVDOO'
--	AND AYXX.LC_STA_ACTYXX = 'A' 
--	AND LNXX.LA_CUR_PRI > X
--	AND LNXX.LC_STA_LONXX = 'R'

--) POP
--WHERE 
--	POP.LOAN_COUNT > X

--ORDER BY 
--	POP.BF_SSN,
--	POP.LN_SEQ

--DROP TABLE IF EXISTS #QX
--SELECT DISTINCT
--	POP.BF_SSN
--INTO #QX
--FROM
--	#QUESTIONX POP
--WHERE
--	(POP.CUR_DUE = X AND TOTAL_DUE != X)  --ONE LOAN HAS NO CURRENT AMOUNT DUE AND BUT THE TOTAL DOES HAVE SOMETHING DUE
--	AND POP.LD_FAT_EFF > POP.FORBEARANCE_END_DATE

--SELECT
--	Q.BF_SSN,
--	Q.[NAME],
--	Q.LN_SEQ,
--	Q.FORBEARANCE_END_DATE,
--	Q.LD_FAT_EFF
--FROM
--	#QUESTIONX Q
--	INNER JOIN #QX P
--		ON Q.BF_SSN = P.BF_SSN
--ORDER BY
--	Q.BF_SSN,
--	Q.LN_SEQ

--X. Multiple open loans, some loans are current, some loans are delinquent.

--Output for each scenario:

--SSN
--Borrower First/Last Name
--Loan Sequence #
--Type XX Forbearance End Date
--Delinquency Date (if applicable)
--Effective Payment Date(s) after the type XX forbearance end date (when applicable, if both ACH and Manual for scenario X, list both)

--DROP TABLE IF EXISTS #QUESTIONX
--SELECT 
--	*
--INTO #QUESTIONX
--FROM
--(
--SELECT DISTINCT
--	LNXX.BF_SSN,
--	RTRIM(PDXX.DM_PRS_X) + ' ' + RTRIM(PDXX.DM_PRS_LST) AS [NAME],
--	LNXX.LN_SEQ,
--	ISNULL(LNXX.LN_DLQ_MAX,X) AS DAYS_PAST_DUE,
--	ISNULL(CONVERT(varchar(XX), FORB.LD_FOR_END, XXX),'N/A') AS FORBEARANCE_END_DATE,
--	COUNT(*) OVER (PARTITION BY LNXX.BF_SSN) AS LOAN_COUNT,
--	SUM(ISNULL(LNXX.LN_DLQ_MAX,X)) OVER (PARTITION BY LNXX.BF_SSN) AS TOTAL_DAYS_PAST_DUE,
--	ISNULL(CONVERT(VARCHAR(XX), LNXX.LD_DLQ_OCC, XXX), 'N/A') AS LD_DLQ_OCC
--FROM
--	CDW..AYXX_BR_LON_ATY AYXX
--	INNER JOIN CDW..PDXX_PRS_NME PDXX
--		ON PDXX.DF_PRS_ID = AYXX.BF_SSN
--	INNER JOIN CDW..LNXX_LON LNXX
--		ON LNXX.BF_SSN = AYXX.BF_SSN
--	LEFT JOIN CDW..LNXX_LON_DLQ_HST LNXX
--		ON LNXX.BF_SSN = LNXX.BF_SSN
--		AND LNXX.LN_SEQ = LNXX.LN_SEQ
--		AND LC_STA_LONXX = 'X'
--		AND CAST(LNXX.LD_DLQ_MAX AS DATE) BETWEEN CAST(DATEADD(DAY,-X,GETDATE()) AS DATE) AND CAST(GETDATE() AS DATE)
--	LEFT JOIN 
--	(
--		SELECT
--			LNXX.*
--		FROM
--			CDW..FBXX_BR_FOR_REQ FBXX
--			INNER JOIN CDW..LNXX_BR_FOR_APV LNXX
--				ON LNXX.BF_SSN = FBXX.BF_SSN
--				AND LNXX.LF_FOR_CTL_NUM = FBXX.LF_FOR_CTL_NUM
--			INNER JOIN CDW..LNXX_LON LNXX
--				ON LNXX.BF_SSN = LNXX.BF_SSN
--				AND LNXX.LN_SEQ = LNXX.LN_SEQ
--				AND LNXX.LA_CUR_PRI > X
--				AND LNXX.LC_STA_LONXX = 'R'
--		WHERE
--			LNXX.LC_STA_LONXX = 'A'
--			AND FBXX.LC_STA_FORXX = 'A'
--			AND FBXX.LC_FOR_STA = 'A' --denied records cant have this active
--			AND LNXX.LC_FOR_RSP != 'XXX'
--			AND FBXX.LC_FOR_TYP = 'XX'
			
--	) FORB
--		ON FORB.BF_SSN = LNXX.BF_SSN
--		AND FORB.LN_SEQ = LNXX.LN_SEQ
--WHERE
--	AYXX.PF_REQ_ACT = 'CVDOO'
--	AND AYXX.LC_STA_ACTYXX = 'A' 
--	AND LNXX.LA_CUR_PRI > X
--	AND LNXX.LC_STA_LONXX = 'R'

--) POP
--WHERE 
--	POP.LOAN_COUNT > X

--ORDER BY 
--	POP.BF_SSN,
--	POP.LN_SEQ

--DROP TABLE IF EXISTS #QX
--SELECT DISTINCT
--	POP.BF_SSN
--INTO #QX
--FROM
--	#QUESTIONX POP
--WHERE
--	(POP.DAYS_PAST_DUE = X AND TOTAL_DAYS_PAST_DUE != X)  --ONE LOAN IS PAST DUE ONE IS NOT

--SELECT
--	Q.BF_SSN,
--	Q.[NAME],
--	Q.LN_SEQ,
--	Q.FORBEARANCE_END_DATE,
--	Q.LD_DLQ_OCC
--	--Q.*
--FROM
--	#QUESTIONX Q
--	INNER JOIN #QX P
--		ON Q.BF_SSN = P.BF_SSN
--ORDER BY
--	Q.BF_SSN,
--	Q.LN_SEQ

--X. Loans that were delinquent following the ending of the type XX forbearance.


--Output for each scenario:

--SSN
--Borrower First/Last Name
--Loan Sequence #
--Type XX Forbearance End Date
--Delinquency Date (if applicable)
--Effective Payment Date(s) after the type XX forbearance end date (when applicable, if both ACH and Manual for scenario X, list both)


--DROP TABLE IF EXISTS #QUESTIONX
--SELECT 
--	*
--INTO #QUESTIONX
--FROM
--(
--SELECT DISTINCT
--	LNXX.BF_SSN,
--	RTRIM(PDXX.DM_PRS_X) + ' ' + RTRIM(PDXX.DM_PRS_LST) AS [NAME],
--	LNXX.LN_SEQ,
--	ISNULL(LNXX.LN_DLQ_MAX,X) AS DAYS_PAST_DUE,
--	ISNULL(CONVERT(varchar(XX), FORB.LD_FOR_END, XXX),'N/A') AS FORBEARANCE_END_DATE,
--	COUNT(*) OVER (PARTITION BY LNXX.BF_SSN) AS LOAN_COUNT,
--	SUM(ISNULL(LNXX.LN_DLQ_MAX,X)) OVER (PARTITION BY LNXX.BF_SSN) AS TOTAL_DAYS_PAST_DUE,
--	ISNULL(CONVERT(VARCHAR(XX), LNXX.LD_DLQ_OCC, XXX), 'N/A') AS LD_DLQ_OCC
--FROM
--	CDW..AYXX_BR_LON_ATY AYXX
--	INNER JOIN CDW..PDXX_PRS_NME PDXX
--		ON PDXX.DF_PRS_ID = AYXX.BF_SSN
--	INNER JOIN CDW..LNXX_LON LNXX
--		ON LNXX.BF_SSN = AYXX.BF_SSN
--	INNER JOIN 
--	(
--		SELECT
--			LNXX.*
--		FROM
--			CDW..FBXX_BR_FOR_REQ FBXX
--			INNER JOIN CDW..LNXX_BR_FOR_APV LNXX
--				ON LNXX.BF_SSN = FBXX.BF_SSN
--				AND LNXX.LF_FOR_CTL_NUM = FBXX.LF_FOR_CTL_NUM
--			INNER JOIN CDW..LNXX_LON LNXX
--				ON LNXX.BF_SSN = LNXX.BF_SSN
--				AND LNXX.LN_SEQ = LNXX.LN_SEQ
--				AND LNXX.LA_CUR_PRI > X
--				AND LNXX.LC_STA_LONXX = 'R'
--		WHERE
--			LNXX.LC_STA_LONXX = 'A'
--			AND FBXX.LC_STA_FORXX = 'A'
--			AND FBXX.LC_FOR_STA = 'A' --denied records cant have this active
--			AND LNXX.LC_FOR_RSP != 'XXX'
--			AND FBXX.LC_FOR_TYP = 'XX'
			
--	) FORB
--		ON FORB.BF_SSN = LNXX.BF_SSN
--		AND FORB.LN_SEQ = LNXX.LN_SEQ
--	INNER JOIN CDW..LNXX_LON_DLQ_HST LNXX
--		ON LNXX.BF_SSN = LNXX.BF_SSN
--		AND LNXX.LN_SEQ = LNXX.LN_SEQ
--		AND LNXX.LD_DLQ_OCC = DATEADD(DAY, X, FORB.LD_FOR_END) --BECAME PAST DUE THE DAY AFTER THE FORB ENDED
--WHERE
--	AYXX.PF_REQ_ACT = 'CVDOO'
--	AND AYXX.LC_STA_ACTYXX = 'A' 
--	AND LNXX.LA_CUR_PRI > X
--	AND LNXX.LC_STA_LONXX = 'R'

--) POP
--WHERE 
--	POP.LOAN_COUNT > X

--ORDER BY 
--	POP.BF_SSN,
--	POP.LN_SEQ

--DROP TABLE IF EXISTS #QX
--SELECT DISTINCT
--	POP.BF_SSN
--INTO #QX
--FROM
--	#QUESTIONX POP
--WHERE
--	(POP.DAYS_PAST_DUE = X AND TOTAL_DAYS_PAST_DUE != X)  --ONE LOAN IS PAST DUE ONE IS NOT

--SELECT
--	Q.BF_SSN,
--	Q.[NAME],
--	Q.LN_SEQ,
--	Q.FORBEARANCE_END_DATE,
--	Q.LD_DLQ_OCC
--	--Q.*
--FROM
--	#QUESTIONX Q
--	INNER JOIN #QX P
--		ON Q.BF_SSN = P.BF_SSN
--ORDER BY
--	Q.BF_SSN,
--	Q.LN_SEQ

--X. Loans where the ACH payment withdrew prior to the payment due date.


--Output for each scenario:

--SSN
--Borrower First/Last Name
--Loan Sequence #
--Type XX Forbearance End Date
--Delinquency Date (if applicable)
--Effective Payment Date(s) after the type XX forbearance end date (when applicable, if both ACH and Manual for scenario X, list both)

--SELECT
--	LNXX.BF_SSN,
--	RTRIM(PDXX.DM_PRS_X) + ' ' + RTRIM(PDXX.DM_PRS_LST) AS [NAME],
--	LNXX.LN_SEQ,
--	RMXX.LD_RMT_PAY_EFF,
--	RMXX.LD_BIL_DU
--FROM
--	CDW..AYXX_BR_LON_ATY AYXX
--	INNER JOIN CDW..PDXX_PRS_NME PDXX
--		ON PDXX.DF_PRS_ID = AYXX.BF_SSN
--	INNER JOIN CDW..LNXX_LON LNXX
--		ON LNXX.BF_SSN = AYXX.BF_SSN
--	INNER JOIN 
--	(
--		SELECT
--			LNXX.*
--		FROM
--			CDW..FBXX_BR_FOR_REQ FBXX
--			INNER JOIN CDW..LNXX_BR_FOR_APV LNXX
--				ON LNXX.BF_SSN = FBXX.BF_SSN
--				AND LNXX.LF_FOR_CTL_NUM = FBXX.LF_FOR_CTL_NUM
--			INNER JOIN CDW..LNXX_LON LNXX
--				ON LNXX.BF_SSN = LNXX.BF_SSN
--				AND LNXX.LN_SEQ = LNXX.LN_SEQ
--				AND LNXX.LA_CUR_PRI > X
--				AND LNXX.LC_STA_LONXX = 'R'
--		WHERE
--			LNXX.LC_STA_LONXX = 'A'
--			AND FBXX.LC_STA_FORXX = 'A'
--			AND FBXX.LC_FOR_STA = 'A' --denied records cant have this active
--			AND LNXX.LC_FOR_RSP != 'XXX'
--			AND FBXX.LC_FOR_TYP = 'XX'
			
--	) FORB
--		ON FORB.BF_SSN = LNXX.BF_SSN
--		AND FORB.LN_SEQ = LNXX.LN_SEQ
--	INNER JOIN 
--	(
--		SELECT  
--			BLXX.LD_BIL_DU,
--			RMXX.*,
--			LNXX.LN_SEQ
--		FROM 
--			[CDW].[DBO].[RMXX_BR_RMT] RMXX
--			INNER JOIN CDW..BLXX_BR_BIL BLXX
--				ON BLXX.BF_SSN = RMXX.BF_SSN
--				AND BLXX.LD_BIL_CRT = RMXX.LD_BIL_CRT
--				AND BLXX.LN_SEQ_BIL_WI_DTE = RMXX.LN_SEQ_BIL_WI_DTE
--			INNER JOIN CDW..LNXX_LON_BIL_CRF LNXX	
--				ON LNXX.BF_SSN = BLXX.BF_SSN
--				AND LNXX.LD_BIL_CRT = BLXX.LD_BIL_CRT
--				AND LNXX.LN_SEQ_BIL_WI_DTE = BLXX.LN_SEQ_BIL_WI_DTE
--		WHERE
--			LD_RMT_PAY_EFF BETWEEN 'XX/XX/XXXX' AND GETDATE()
--			AND LC_RMT_STA = 'A'
--			AND PC_FAT_TYP = 'XX'
--			AND PC_FAT_SUB_TYP = 'XX'
--			AND LC_RMT_PAY_SRC = 'XX'
--	) RMXX
--		ON RMXX.BF_SSN = LNXX.BF_SSN
--		AND RMXX.LN_SEQ = LNXX.LN_SEQ
--		AND RMXX.LD_RMT_PAY_EFF > FORB.LD_FOR_END
--WHERE
--	AYXX.PF_REQ_ACT = 'CVDOO'
--	AND AYXX.LC_STA_ACTYXX = 'A' 
--	AND LNXX.LA_CUR_PRI > X
--	AND LNXX.LC_STA_LONXX = 'R'
--	AND (RMXX.LD_RMT_PAY_EFF) < (RMXX.LD_BIL_DU) 

--X. Loans where the borrower made a manual payment AND an ACH payment pulled for the same bill due.

--Output for each scenario:

--SSN
--Borrower First/Last Name
--Loan Sequence #
--Type XX Forbearance End Date
--Delinquency Date (if applicable)
--Effective Payment Date(s) after the type XX forbearance end date (when applicable, if both ACH and Manual for scenario X, list both)

--DROP TABLE IF EXISTS #QUESTIONX
--SELECT
--	LNXX.BF_SSN,
--	RTRIM(PDXX.DM_PRS_X) + ' ' + RTRIM(PDXX.DM_PRS_LST) AS [NAME],
--	LNXX.LN_SEQ,
--	FORB.LD_FOR_END,
--	RMXX.LD_BIL_CRT
--INTO #QUESTIONX
--FROM
--	CDW..AYXX_BR_LON_ATY AYXX
--	INNER JOIN CDW..PDXX_PRS_NME PDXX
--		ON PDXX.DF_PRS_ID = AYXX.BF_SSN
--	INNER JOIN CDW..LNXX_LON LNXX
--		ON LNXX.BF_SSN = AYXX.BF_SSN
--	INNER JOIN 
--	(
--		SELECT
--			LNXX.*
--		FROM
--			CDW..FBXX_BR_FOR_REQ FBXX
--			INNER JOIN CDW..LNXX_BR_FOR_APV LNXX
--				ON LNXX.BF_SSN = FBXX.BF_SSN
--				AND LNXX.LF_FOR_CTL_NUM = FBXX.LF_FOR_CTL_NUM
--			INNER JOIN CDW..LNXX_LON LNXX
--				ON LNXX.BF_SSN = LNXX.BF_SSN
--				AND LNXX.LN_SEQ = LNXX.LN_SEQ
--				AND LNXX.LA_CUR_PRI > X
--				AND LNXX.LC_STA_LONXX = 'R'
--		WHERE
--			LNXX.LC_STA_LONXX = 'A'
--			AND FBXX.LC_STA_FORXX = 'A'
--			AND FBXX.LC_FOR_STA = 'A' --denied records cant have this active
--			AND LNXX.LC_FOR_RSP != 'XXX'
--			AND FBXX.LC_FOR_TYP = 'XX'
			
--	) FORB
--		ON FORB.BF_SSN = LNXX.BF_SSN
--		AND FORB.LN_SEQ = LNXX.LN_SEQ
--	INNER JOIN 
--	(
--		SELECT  
--			RMXX.BF_SSN,
--			RMXX.LD_BIL_CRT,
--			LNXX.LN_SEQ,
--			COUNT(DISTINCT LC_RMT_PAY_SRC) AS C
--		FROM 
--			[CDW].[DBO].[RMXX_BR_RMT] RMXX
--			INNER JOIN CDW..BLXX_BR_BIL BLXX
--				ON BLXX.BF_SSN = RMXX.BF_SSN
--				AND BLXX.LD_BIL_CRT = RMXX.LD_BIL_CRT
--				AND BLXX.LN_SEQ_BIL_WI_DTE = RMXX.LN_SEQ_BIL_WI_DTE
--			INNER JOIN CDW..LNXX_LON_BIL_CRF LNXX	
--				ON LNXX.BF_SSN = BLXX.BF_SSN
--				AND LNXX.LD_BIL_CRT = BLXX.LD_BIL_CRT
--				AND LNXX.LN_SEQ_BIL_WI_DTE = BLXX.LN_SEQ_BIL_WI_DTE
--		WHERE
--			LD_RMT_PAY_EFF BETWEEN 'XX/XX/XXXX' AND GETDATE()
--			AND LC_RMT_STA = 'A'
--			AND PC_FAT_TYP = 'XX'
--			AND PC_FAT_SUB_TYP = 'XX'
--		GROUP BY 
--			RMXX.BF_SSN,
--			RMXX.LD_BIL_CRT,
--			LNXX.LN_SEQ
--	) RMXX
--		ON RMXX.BF_SSN = LNXX.BF_SSN
--		AND RMXX.LN_SEQ = LNXX.LN_SEQ
--		AND RMXX.LD_BIL_CRT > FORB.LD_FOR_END
--WHERE
--	AYXX.PF_REQ_ACT = 'CVDOO'
--	AND AYXX.LC_STA_ACTYXX = 'A' 
--	AND LNXX.LA_CUR_PRI > X
--	AND LNXX.LC_STA_LONXX = 'R'
--	AND RMXX.C > X

--SELECT 
--	Q.BF_SSN,
--	Q.[NAME],
--	Q.LN_SEQ,
--	CONVERT(VARCHAR(XX), Q.LD_FOR_END, XXX) AS FORBEARANCE_END_DATE,
--	RMXX.LD_RMT_PAY_EFF AS PAYMENT_EFF_DATE,
--	LKXX.PX_DSC_MDM AS PAYMENT_TYPE
--FROM 
--	#QUESTIONX Q
--	INNER JOIN 
--	(
--		SELECT  
--			RMXX.*,
--			LNXX.LN_SEQ
--		FROM 
--			[CDW].[DBO].[RMXX_BR_RMT] RMXX
--			INNER JOIN CDW..BLXX_BR_BIL BLXX
--				ON BLXX.BF_SSN = RMXX.BF_SSN
--				AND BLXX.LD_BIL_CRT = RMXX.LD_BIL_CRT
--				AND BLXX.LN_SEQ_BIL_WI_DTE = RMXX.LN_SEQ_BIL_WI_DTE
--			INNER JOIN CDW..LNXX_LON_BIL_CRF LNXX	
--				ON LNXX.BF_SSN = BLXX.BF_SSN
--				AND LNXX.LD_BIL_CRT = BLXX.LD_BIL_CRT
--				AND LNXX.LN_SEQ_BIL_WI_DTE = BLXX.LN_SEQ_BIL_WI_DTE
--		WHERE
--			LD_RMT_PAY_EFF BETWEEN 'XX/XX/XXXX' AND GETDATE()
--			AND LC_RMT_STA = 'A'
--			AND PC_FAT_TYP = 'XX'
--			AND PC_FAT_SUB_TYP = 'XX'
	
--	) RMXX
--		ON RMXX.BF_SSN = Q.BF_SSN
--		AND RMXX.LN_SEQ = Q.LN_SEQ
--		AND RMXX.LD_BIL_CRT =  Q.LD_BIL_CRT
--	  inner join cdw..LKXX_LS_CDE_LKP lkXX
--	on lkXX.PM_ATR = 'LC-RMT-PAY-SRC'
--	and lkXX.PX_ATR_VAL = rmXX.LC_RMT_PAY_SRC
--ORDER BY
--	Q.BF_SSN,
--	RMXX.LD_RMT_PAY_EFF,
--	Q.LN_SEQ



DROP TABLE IF EXISTS #QUESTIONX
SELECT 
	*
INTO #QUESTIONX
FROM
(
SELECT DISTINCT
	LNXX.BF_SSN,
	RTRIM(PDXX.DM_PRS_X) + ' ' + RTRIM(PDXX.DM_PRS_LST) AS [NAME],
	LNXX.LN_SEQ,
	LNXX.CUR_DUE,
	ISNULL(CONVERT(varchar(XX), FORB.LD_FOR_END, XXX),'N/A') AS FORBEARANCE_END_DATE,
	COUNT(*) OVER (PARTITION BY LNXX.BF_SSN) AS LOAN_COUNT,
	SUM(LNXX.CUR_DUE) OVER (PARTITION BY LNXX.BF_SSN) AS TOTAL_DUE,
	RS.LA_RPS_ISL,
	FSXX.LF_FED_AWD + RIGHT('XXX' + CAST(LN_FED_AWD_SEQ AS VARCHAR(X)), X) AS AWARD_ID,
	DAY(RS.LD_RPS_X_PAY_DU) AS PAYMENT_DUE_DATE,
	LNXX.LD_BIL_CRT AS BILL_SENT_DATE
FROM
	CDW..AYXX_BR_LON_ATY AYXX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = AYXX.BF_SSN
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = AYXX.BF_SSN
	INNER JOIN CDW.calc.RepaymentSchedules RS
		ON RS.BF_SSN = LNXX.BF_SSN
		AND RS.LN_SEQ = LNXX.LN_SEQ
		AND RS.CurrentGradation = X
	INNER JOIN CDW..FSXX_DL_LON FSXX
		ON FSXX.BF_SSN = LNXX.BF_SSN
		AND FSXX.LN_SEQ = LNXX.LN_SEQ
	INNER JOIN
	(
		SELECT DISTINCT
				LNXX.BF_SSN,
				LNXX.LN_SEQ,
				LNXX.LD_BIL_CRT,
				CASE WHEN SUM(COALESCE(LNXX.LA_BIL_CUR_DU,X) - COALESCE(LNXX.LA_TOT_BIL_STS,X)) < X THEN X 
				ELSE SUM(COALESCE(LNXX.LA_BIL_CUR_DU,X) - COALESCE(LNXX.LA_TOT_BIL_STS,X)) END  AS CUR_DUE
			FROM  
				CDW..LNXX_LON_BIL_CRF LNXX
				INNER JOIN 
				(
					SELECT
						LNXX.BF_SSN,
						LNXX.LN_SEQ,
						MIN(LNXX.LD_BIL_DU_LON) AS LD_BIL_DU_LON
					FROM 
						CDW..LNXX_LON_BIL_CRF LNXX
						INNER JOIN CDW..PDXX_PRS_NME PDXX
							ON PDXX.DF_PRS_ID = LNXX.BF_SSN
						INNER JOIN CDW..LNXX_LON LNXX
							ON LNXX.BF_SSN = LNXX.BF_SSN
							AND LNXX.LN_SEQ = LNXX.LN_SEQ
						
					WHERE 
						LNXX.LC_STA_LONXX = 'A'
						AND LNXX.LC_LON_STA_BIL = 'X'
						AND CAST(LNXX.LD_BIL_DU_LON AS DATE) >= CAST(GETDATE() AS DATE)
						AND LNXX.LC_STA_LONXX IN ('R','L')
						AND LNXX.LA_CUR_PRI > X
					GROUP BY 
						LNXX.BF_SSN,
						LNXX.LN_SEQ
				) MIN_DTE
					ON LNXX.BF_SSN = MIN_DTE.BF_SSN
						AND LNXX.LN_SEQ = MIN_DTE.LN_SEQ
						AND LNXX.LD_BIL_DU_LON = MIN_DTE.LD_BIL_DU_LON
			WHERE 
				LNXX.LC_STA_LONXX = 'A'
				AND LNXX.LC_LON_STA_BIL = 'X'
			GROUP BY 
				LNXX.BF_SSN,
				LNXX.LN_SEQ,
				LNXX.LD_BIL_CRT
	) LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
	LEFT JOIN 
	(
		SELECT
			LNXX.*
		FROM
			CDW..FBXX_BR_FOR_REQ FBXX
			INNER JOIN CDW..LNXX_BR_FOR_APV LNXX
				ON LNXX.BF_SSN = FBXX.BF_SSN
				AND LNXX.LF_FOR_CTL_NUM = FBXX.LF_FOR_CTL_NUM
			INNER JOIN CDW..LNXX_LON LNXX
				ON LNXX.BF_SSN = LNXX.BF_SSN
				AND LNXX.LN_SEQ = LNXX.LN_SEQ
				AND LNXX.LA_CUR_PRI > X
				AND LNXX.LC_STA_LONXX = 'R'
		WHERE
			LNXX.LC_STA_LONXX = 'A'
			AND FBXX.LC_STA_FORXX = 'A'
			AND FBXX.LC_FOR_STA = 'A' --denied records cant have this active
			AND LNXX.LC_FOR_RSP != 'XXX'
			AND FBXX.LC_FOR_TYP = 'XX'
			
	) FORB
		ON FORB.BF_SSN = LNXX.BF_SSN
		AND FORB.LN_SEQ = LNXX.LN_SEQ
WHERE
	AYXX.PF_REQ_ACT = 'CVDOO'
	AND AYXX.LC_STA_ACTYXX = 'A' 
	AND LNXX.LA_CUR_PRI > X
	AND LNXX.LC_STA_LONXX = 'R'

) POP
WHERE 
	POP.LOAN_COUNT > X

--select * from #QUESTIONX


DROP TABLE IF EXISTS #QX
SELECT DISTINCT
	POP.BF_SSN
INTO #QX
FROM
	#QUESTIONX POP
WHERE
	(POP.CUR_DUE = X AND TOTAL_DUE != X)  --ONE LOAN HAS NO CURRENT AMOUNT DUE AND BUT THE TOTAL DOES HAVE SOMETHING DUE
	AND POP.CUR_DUE < POP.LA_RPS_ISL
	and pop.BILL_SENT_DATE > pop.FORBEARANCE_END_DATE
	--AND POP.LD_FAT_EFF > POP.FORBEARANCE_END_DATE

SELECT DISTINCT
	Q.BF_SSN,
	Q.[NAME],
	Q.LN_SEQ,
	Q.AWARD_ID,
	Q.FORBEARANCE_END_DATE,
	Q.CUR_DUE AS PAYMENT_AMOUNT_DUE,
	Q.BILL_SENT_DATE,
	Q.LA_RPS_ISL AS REPAYMENT_SCHEDULE_AMT
FROM
	#QUESTIONX Q
	INNER JOIN #QX P
		ON Q.BF_SSN = P.BF_SSN
ORDER BY
	Q.BF_SSN,
	Q.LN_SEQ
