LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
	CREATE TABLE BA AS
		SELECT
			FSXX.BF_SSN,
			FSXX.LN_SEQ,
			FSXX.LF_CON_LON_ORG
		FROM
			PKUB.PDXX_PRS_NME PDXX
			JOIN PKUB.FSXX_DL_LON FSXX
				 ON PDXX.DF_PRS_ID = FSXX.BF_SSN
				 AND PDXX.DF_SPE_ACC_ID = 'XXXXXXXXXX'
				 AND FSXX.LN_SEQ = X
	;
QUIT;
ENDRSUBMIT;

