USE CDW
GO

DECLARE @StartDate DATE = 'XXXX-X-X'
DECLARE @EndDate DATE = GETDATE()

SELECT DISTINCT	
	LNXX.BF_SSN,
	LNXX.LN_SEQ,
	LNXX.IC_LON_PGM
FROM	
	CDW..LNXX_LON LNXX
	INNER JOIN CDW..DWXX_DW_CLC_CLU DWXX ON LNXX.BF_SSN = DWXX.BF_SSN AND LNXX.LN_SEQ = DWXX.LN_SEQ
	INNER JOIN CDW..LNXX_INT_RTE_HST LNXX ON LNXX.BF_SSN = LNXX.BF_SSN AND LNXX.LN_SEQ = LNXX.LN_SEQ
WHERE	
	LNXX.LC_STA_LONXX = 'R'
	AND 
	LNXX.LA_CUR_PRI > X
	AND	
	DWXX.WC_DW_LON_STA IN ('XX','XX','XX','XX','XX','XX','XX','XX','XX','XX')
	AND
	(
		LNXX.IC_LON_PGM NOT IN 
		(
			'DLUCNS', 'DLSCNS', 'CNSLDN', 'DSCON', 'DLUSPL', 'DUCON', 
			'SPCNSL', 'SUBCNS', 'SUBSPC', 'UNCNS', 'DLSPCN', 'DLSSPL', 
			'DLCNSL', 'DLPCNS', 'UNSPC', 'DLSCST', 'DLSCUN', 'DLSCPL', 
			'DLSCPG', 'DLSCSL', 'DLSCSC', 'DLSCUC', 'DLSCCN'
		)
	)
	--AND
	--LNXX.LC_ITR_TYP = FX
	--AND
	--something.something BETWEEN @StartDate AND @EndDate