USE CDW
GO

UPDATE
	LTXX_LetterRequests
SET
	SystemLetterExclusionReasonId = X,
	InactivatedAt = GETDATE()
WHERE
	LTXX_LETTER_REQUEST_ID IN (XXXXXXX,XXXXXXX)
	SystemLetterExclusionReasonId = X,
	InactivatedAt = GETDATE()
WHERE
	LTXX_LETTER_REQUEST_ID IN (XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX)
