/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;

PROC IMPORT OUT= WORK.FILEX
            DATAFILE= "T:\Cornerstone AK cleanup X.xlsx" 
            DBMS=EXCEL REPLACE;
     RANGE="SheetX$"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
RUN;

%MACRO SEND_DATA(DATASET);
LIBNAME  LEGEND  REMOTE  SERVER=LEGEND SLIBREF=WORK;
DATA LEGEND.&DATASET; *Send data to Duster;
SET &DATASET;
RUN;
%MEND;

%SEND_DATA(FILEX);

RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
		CREATE TABLE CLEANUP_FILE_X AS
			SELECT	
				D.*,
				GRXX.WC_NDS_LN_REB_RPT,
				GRXX.WC_NDS_RPT_STA
			FROM
				FILEX D
				INNER JOIN PKUB.GRXX_RPT_LON_APL GRXX
					ON D.BF_SSN = GRXX.BF_SSN
					AND INPUT(D.LN_SEQ,BESTXX.) = GRXX.LN_SEQ
					AND INPUT(D.WN_SEQ_GRXX,BESTXX.) = GRXX.WN_SEQ_GRXX
;

QUIT;
ENDRSUBMIT;

DATA CLEANUP_FILE_X;
SET LEGEND.CLEANUP_FILE_X;
RUN;

PROC EXPORT DATA= WORK.CLEANUP_FILE_X 
            OUTFILE= "T:\CNH XXXX FILEX.xlsx" 
            DBMS=EXCEL REPLACE;
     SHEET="AK_records"; 
RUN;

