USE CDW;
GO

DECLARE @RedefaultedLoans TABLE (ID INT, BF_SSN VARCHAR(X), AWARD_ID VARCHAR(XX), LN_SEQ VARCHAR(X));
INSERT INTO @RedefaultedLoans (ID, BF_SSN, AWARD_ID, LN_SEQ) VALUES
--ID BF_SSN		AWARD_ID	<IF_LON_SRV_DFL_LON>	Loan seq
( X,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
( X,'XXXXXXXXX','XXXXXXXXXPXXGXXXXXXXX','XXXX'),
( X,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
( X,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
( X,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
( X,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
( X,'XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','XXXX'),
( X,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
( X,'XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','XXXX'),
(XX,'XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','XXXX')
;

--SELECT * FROM @RedefaultedLoans;


SELECT
	 RL.BF_SSN
	,RL.AWARD_ID
	,LNXX.IF_LON_SRV_DFL_LON
	,RL.LN_SEQ AS [Loan seq]
	--,LNXX.LN_SEQ	
FROM
	@RedefaultedLoans RL
	INNER JOIN LNXX_RPD_PIO_CVN LNXX
		ON RL.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = RIGHT(RL.LN_SEQ,X)
ORDER BY 
	RL.ID
;
