USE CDW
GO

SELECT DISTINCT
	PDXX.DF_SPE_ACC_ID AS [ACCOUNT NUMBER],
	WQXX.WF_CRT_DTS_WQXX AS [TASK OPEN DATE],
	LNXX.LN_SEQ AS [LOAN SEQ],
	LNXX.LA_CUR_PRI AS [CURRENT BALANCE]
FROM
	CDW..WQXX_TSK_QUE WQXX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = WQXX.BF_SSN
	INNER JOIN CDW..AYXX_BR_LON_ATY AYXX
		ON AYXX.BF_SSN = WQXX.BF_SSN
		AND AYXX.LN_ATY_SEQ = WQXX.LN_ATY_SEQ
	INNER JOIN CDW..LNXX_LON_ATY LNXX
		ON LNXX.BF_SSN = AYXX.BF_SSN
		AND LNXX.LN_ATY_SEQ = AYXX.LN_ATY_SEQ
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
WHERE
	WC_STA_WQUEXX NOT IN ('X','C')
	AND WF_QUE = 'XZ'
ORDER BY
	[ACCOUNT NUMBER],
	LNXX.LN_SEQ