LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
	CREATE TABLE DMCS AS
		SELECT
			PDXX.DF_SPE_ACC_ID
		FROM
			PKUB.PDXX_PRS_NME PDXX
			JOIN PKUB.LNXX_LON LNXX
				ON PDXX.DF_PRS_ID = LNXX.BF_SSN
		WHERE
			LNXX.LC_SST_LONXX IN ('X', 'X')
			AND LNXX.LD_STA_LONXX < 'XXNOVXXXX'D
	;
QUIT;
ENDRSUBMIT;

