SELECT
	*
FROM OPENQUERY
(LEGEND,
'
	SELECT
		LNXX.BF_SSN,
		LNXX.LN_SEQ,
		LNXX.LF_DOE_SCL_ORG,
		LNXX.LD_TRM_BEG
	FROM
		PKUB.LNXX_LON LNXX
	WHERE
		LNXX.LF_DOE_SCL_ORG IN (''XXXXXXXX'',''XXXXXXXX'',''XXXXXXXX'')
		AND LNXX.LD_TRM_BEG BETWEEN ''XXXX-XX-XX'' AND ''XXXX-XX-XX''
'	
)