SELECT DISTINCT
	CAST(AYXX.LD_ATY_REQ_RCV AS DATE) AS LD_ATY_REQ_RCV,
	PDXX.DF_SPE_ACC_ID
FROM
	CDW..PDXX_PRS_NME PDXX
	INNER JOIN CDW..AYXX_BR_LON_ATY AYXX
		ON PDXX.DF_PRS_ID = AYXX.BF_SSN
WHERE
	AYXX.PF_REQ_ACT = 'DISBA'
	AND CAST(AYXX.LD_ATY_REQ_RCV AS DATE) IN
	(
		'X/XX/XXXX', 
		'X/XX/XXXX', 
		'X/XX/XXXX', 
		'X/XX/XXXX', 
		'X/XX/XXXX', 
		'X/XX/XXXX', 
		'X/XX/XXXX', 
		'X/XX/XXXX', 
		'X/XX/XXXX', 
		'X/XX/XXXX'
	)
ORDER BY
	CAST(AYXX.LD_ATY_REQ_RCV AS DATE)

--for verification there are no ARCs on some dates
--SELECT DISTINCT
--	CAST(AYXX.LD_ATY_REQ_RCV AS DATE) AS LD_ATY_REQ_RCV
--FROM
--	CDW..AYXX_BR_LON_ATY AYXX
--WHERE
--	AYXX.PF_REQ_ACT = 'DISBA'
--ORDER BY
--	CAST(AYXX.LD_ATY_REQ_RCV AS DATE)