/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;

%MACRO READIN (DTE,NME);
DATA FILE&DTE;
INFILE "Q:/Systems Support/Chris/FCOSCUL From Noble/Processed/&NME" MISSOVER;
INPUT   LF_USR_REQ_ATY $X.
        +X
        BF_SSN X.
        PF_RSP_ACT $X.
        +X
        LD_ATY_RSP mmddyyXX.
        +XX
        LF_PRF_BY $X.
        Filler $;
FORMAT BF_SSN zX.;
RUN;
%MEND READIN;
%READIN (XXXXXXXX, Batch.autodialer.XXXX-XX-XX);
%READIN (XXXXXXXX, Batch.autodialer.XXXX-XX-XX);
%READIN (XXXXXXXX, Batch.autodialer.XXXX-XX-XX);
%READIN (XXXXXXXX, Batch.autodialer.XXXX-XX-XX);
%READIN (XXXXXXXX, Batch.autodialer.XXXX-XX-XX);
%READIN (XXXXXXXX, Batch.autodialer.XXXX-XX-XX);
%READIN (XXXXXXXX, Batch.autodialer.XXXX-XX-XX);
%READIN (XXXXXXXX, Batch.autodialer.XXXX-XX-XX);
%READIN (XXXXXXXX, Batch.autodialer.XXXX-XX-XX);

DATA CombinedFiles;
SET FILEXXXXXXXX FILEXXXXXXXX FILEXXXXXXXX FILEXXXXXXXX FILEXXXXXXXX
    FILEXXXXXXXX FILEXXXXXXXX FILEXXXXXXXX FILEXXXXXXXX;
RUN;

LIBNAME  LEGEND  REMOTE  SERVER=LEGEND SLIBREF=work  ;

DATA LEGEND.COMBINEDFILES;
	SET COMBINEDFILES;
RUN;

RSUBMIT LEGEND;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
	CREATE TABLE DEMO AS
		SELECT DISTINCT
			AYXX.BF_SSN,
			AYXX.LN_ATY_SEQ,
			AYXX.LD_ATY_REQ_RCV,
			AYXX.LD_ATY_RSP,
			AYXX.LC_STA_ACTYXX
		FROM
			COMBINEDFILES cf
			INNER JOIN PKUB.AYXX_BR_LON_ATY AYXX 
				ON cf.LF_USR_REQ_ATY = AYXX.LF_USR_REQ_ATY 
				AND cf.BF_SSN = input(AYXX.BF_SSN, bestXX.)
				AND cf.PF_RSP_ACT = AYXX.PF_RSP_ACT
				AND cf.LF_PRF_BY = AYXX.LF_PRF_BY
	;
QUIT;
ENDRSUBMIT;


data demo;
set LEGEND.demo;
run;

PROC EXPORT DATA = demo
            OUTFILE = "T:\comment files.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="SheetX"; 
RUN;

