USE CDW
GO

SELECT
		--borrower info
		REPLACE(LTRIM(RTRIM(BORR.DM_PRS_X)),',','')  + ' ' + REPLACE(LTRIM(RTRIM(BORR.DM_PRS_LST)),',','') + ' ' + REPLACE(LTRIM(RTRIM(BORR.DM_PRS_LST_SFX)),',','')  AS Name,
		--address info
		REPLACE(LTRIM(RTRIM(ADDR.DX_STR_ADR_X)),',','')  AS AddressX,
		REPLACE(LTRIM(RTRIM(ADDR.DX_STR_ADR_X)),',','')  AS AddressX,
		CASE	
			WHEN LEN(LTRIM(RTRIM(ADDR.DF_ZIP_CDE))) = X THEN REPLACE(LTRIM(RTRIM(ADDR.DM_CT)),',','')  + ' ' + REPLACE(LTRIM(RTRIM(ADDR.DC_DOM_ST)),',','')  + '  ' + LEFT(LTRIM(RTRIM(ADDR.DF_ZIP_CDE)), X) + '-' + RIGHT(LTRIM(RTRIM(ADDR.DF_ZIP_CDE)), X)
			ELSE REPLACE(LTRIM(RTRIM(ADDR.DM_CT)),',','') + ' ' + REPLACE(LTRIM(RTRIM(ADDR.DC_DOM_ST)),',','') + '  ' + REPLACE(LTRIM(RTRIM(ADDR.DF_ZIP_CDE)),',','')
		END AS CityStateZip,
		REPLACE(LTRIM(RTRIM(ADDR.DM_FGN_ST)),',','')  AS ForeignState,
		REPLACE(LTRIM(RTRIM(ADDR.DM_FGN_CNY)),',','') AS Country,
		BORR.DF_SPE_ACC_ID AS AccountNumber,
		BORR.DF_PRS_ID AS SSN,
		REPLACE(LTRIM(RTRIM(ADDR.DM_CT)),',','')  AS City,
		REPLACE(LTRIM(RTRIM(ADDR.DC_DOM_ST)),',','')  AS [State],
		CASE	
			WHEN LEN(ADDR.DF_ZIP_CDE) = X THEN LEFT(LTRIM(RTRIM(ADDR.DF_ZIP_CDE)), X) + '-' + RIGHT(LTRIM(RTRIM(ADDR.DF_ZIP_CDE)), X)
			ELSE LTRIM(RTRIM(ADDR.DF_ZIP_CDE))
		END AS Zip,
		CASE
			WHEN DI_VLD_ADR = 'Y' THEN X
			ELSE X
		END AS HasValidAddress
	FROM
		dbo.PDXX_PRS_NME BORR 
		INNER JOIN dbo.PDXX_PRS_ADR ADDR 
			ON BORR.DF_PRS_ID = ADDR.DF_PRS_ID
	WHERE 
		BORR.DF_PRS_ID IN ('XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX')
		AND ADDR.DC_ADR = 'L'