SELECT
	PDXX.DF_SPE_ACC_ID AS ACCOUNT_NUMBER,
	--DWXX.BF_SSN,
	DWXX.LN_SEQ AS LOAN_SEQ,
	DWXX.WD_LON_RPD_SR AS REPAYMENT_START_DATE,
	CONVERT(VARCHAR,LNXX.LD_FOR_BEG,XXX) AS BEGIN_DATE,
	CONVERT(VARCHAR,LNXX.LD_FOR_END,XXX) AS END_DATE,
	'FORBEARANCE' AS [TYPE],
	FBXX.LC_FOR_TYP AS SYSTEM_CODE
FROM
	CDW..DWXX_DW_CLC_CLU DWXX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = DWXX.BF_SSN
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = DWXX.BF_SSN
		AND LNXX.LN_SEQ = DWXX.LN_SEQ
	INNER JOIN CDW..FBXX_BR_FOR_REQ FBXX
		ON FBXX.BF_SSN = DWXX.BF_SSN
	INNER JOIN CDW..LNXX_BR_FOR_APV LNXX
		ON LNXX.BF_SSN = DWXX.BF_SSN
		AND LNXX.LN_SEQ = DWXX.LN_SEQ
		AND LNXX.LF_FOR_CTL_NUM = FBXX.LF_FOR_CTL_NUM
WHERE
	LNXX.LD_FOR_BEG < DWXX.WD_LON_RPD_SR
	AND FBXX.LC_FOR_STA = 'A'
	AND FBXX.LC_STA_FORXX = 'A'
	AND LNXX.LC_STA_LONXX = 'A'
	AND LNXX.LC_FOR_RSP != 'XXX'


UNION 

SELECT
	PDXX.DF_SPE_ACC_ID AS ACCOUNT_NUMBER,
	--DWXX.BF_SSN,
	DWXX.LN_SEQ AS LOAN_SEQ,
	DWXX.WD_LON_RPD_SR AS REPAYMENT_START_DATE,
	CONVERT(VARCHAR,LNXX.LD_DFR_BEG,XXX) AS BEGIN_DATE,
	CONVERT(VARCHAR,LNXX.LD_DFR_END,XXX) AS END_DATE,
	'DEFERMENT' AS [TYPE],
	DFXX.LC_DFR_TYP AS SYSTEM_CODE
FROM
	CDW..DWXX_DW_CLC_CLU DWXX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = DWXX.BF_SSN
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = DWXX.BF_SSN
		AND LNXX.LN_SEQ = DWXX.LN_SEQ
	INNER JOIN CDW..DFXX_BR_DFR_REQ DFXX
		ON DFXX.BF_SSN = DWXX.BF_SSN
	INNER JOIN CDW..LNXX_BR_DFR_APV LNXX
		ON LNXX.BF_SSN = DWXX.BF_SSN
		AND LNXX.LN_SEQ = DWXX.LN_SEQ
		AND LNXX.LF_DFR_CTL_NUM = DFXX.LF_DFR_CTL_NUM
WHERE
	LNXX.LD_DFR_BEG < DWXX.WD_LON_RPD_SR
	AND DFXX.LC_DFR_STA = 'A'
	AND DFXX.LC_STA_DFRXX = 'A'
	AND LNXX.LC_STA_LONXX = 'A'
	AND lnXX.LC_DFR_RSP != 'XXX'
ORDER BY	
	ACCOUNT_NUMBER,
	LOAN_SEQ