USE [CDW]
GO
/****** Object:  StoredProcedure [dbo].[LT_TSXXBISF_Reversed_Transaction]    Script Date: X/XX/XXXX X:XX:XX AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[LT_TSXXBISF_Reversed_Transaction]
	@AccountNumber CHAR(XX)
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;


	SELECT TOP X
		PDXX.DF_SPE_ACC_ID,
		LNXX.LN_FAT_SEQ,
		SUM(ISNULL(LNXX.LA_FAT_CUR_PRI, X) + ISNULL(LNXX.LA_FAT_ILG_PRI, X) + ISNULL(LNXX.LA_FAT_LTE_FEE, X) + ISNULL(LNXX.LA_FAT_NSI, X) + ISNULL(LNXX.LA_FAT_PCL_FEE, X)) [LA_TRAN],
		CONVERT(VARCHAR(XX), LNXX.LD_FAT_EFF, XXX) [LD_MAX_TRAN]
	FROM
		PDXX_PRS_NME PDXX
		INNER JOIN LNXX_FIN_ATY LNXX ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	WHERE
		PDXX.DF_SPE_ACC_ID = @AccountNumber
		AND LNXX.LC_FAT_REV_REA = 'X'
		AND LNXX.PC_FAT_TYP = 'XX'
		AND LNXX.LC_STA_LONXX = 'A'
	GROUP BY
		PDXX.DF_SPE_ACC_ID,
		LNXX.LN_FAT_SEQ,
		LNXX.LD_FAT_EFF
	ORDER BY
		LNXX.LN_FAT_SEQ DESC

END

IF @@ROWCOUNT = X 
	BEGIN
		RAISERROR('No data returned for Account Number: %s. ([dbo].[LT_TSXXBISF_Reversed_Transaction])',XX,X, @AccountNumber)
	END


