LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;


PROC SQL;
	CREATE TABLE WQXXData AS
		SELECT 
			WQXX.WF_QUE as Queue,
			WQXX.WF_SUB_QUE as Subqueue,
			WQXX.WN_CTL_TSK as TaskControlNumber,
			WQXX.PF_REQ_ACT as ActionRequest
		FROM
			PKUB.WQXX_TSK_QUE WQXX
		WHERE 
			WQXX.WF_QUE = 'RX' 
			AND WQXX.WF_SUB_QUE = 'XX'
	;
QUIT;

ENDRSUBMIT;

PROC EXPORT	
		DATA=LEGEND.WQXXData
		OUTFILE='T:\SAS\NH XXXX data dump.xlsx'
		REPLACE;
RUN;
