LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;

/*LIBNAME XL 'T:\t-v-s-X-XXXX vX.xlsx';*/
/*DATA FSA (KEEP=AWARD_ID);*/
/*	SET XL.'t-v-s-X-XXXX$'N;*/
/*	WHERE AWARD_ID ^= '';*/
/*RUN;*/

/*LIBNAME XL 'T:\cornerstone_rebate_only_problems_XXXXXX.xlsx';*/
/*DATA FSA (RENAME=(AWARD=AWARD_ID) KEEP=AWARD);*/
/*	SET XL.'corn_reb_chk_XXXXXX$'N;*/
/*	WHERE AWARD ^= '';*/
/*RUN;*/

LIBNAME XL 'T:\cornerstone_new_diff.xlsx' HEADER=NO;
DATA FSA (RENAME=(FX=AWARD_ID) KEEP=FX);
	SET XL.'new_diff$'N;
	WHERE FX ^= '';
RUN;

DATA LEGEND.FSA;
	SET FSA;
RUN;

RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
LIBNAME PKUS DBX DATABASE=DNFPUTDL OWNER=PKUS;
PROC SQL;
	CREATE TABLE DISBS AS
		SELECT DISTINCT
			PDXX.DF_SPE_ACC_ID,
			PDXX.DM_PRS_LST,
			PDXX.DM_PRS_X,
			FSA.AWARD_ID,
			LNXX.LN_BR_DSB_SEQ,
			LNXX.LD_DSB AS LD_DSB,
			LNXX.LA_DSB AS LA_DSB,
			LNXX.LA_DSB AS LA_NEW_DSB,
			LNXX.LA_DL_DSB_REB
		FROM
			FSA
			JOIN PKUB.FSXX_DL_LON FSXX
				ON FSA.AWARD_ID = CATX('',FSXX.LF_FED_AWD,PUT(FSXX.LN_FED_AWD_SEQ,ZX.))
			LEFT JOIN PKUB.LNXX_DSB LNXX
				ON FSXX.BF_SSN = LNXX.BF_SSN
				AND FSXX.LN_SEQ = LNXX.LN_SEQ
			LEFT JOIN PKUB.PDXX_PRS_NME PDXX
				ON FSXX.BF_SSN = PDXX.DF_PRS_ID
	;

	CREATE TABLE CANCS AS
		SELECT DISTINCT
			PDXX.DF_SPE_ACC_ID,
			PDXX.DM_PRS_LST,
			PDXX.DM_PRS_X,
			FSA.AWARD_ID,
			LNXX.LN_BR_DSB_SEQ,
			LNXX.LD_DSB_CAN AS LD_DSB,
			LNXX.LA_DSB_CAN*-X AS LA_DSB,
			LNXX.LA_DSB - COALESCE(LNXX.LA_DSB_CAN,X) AS LA_NEW_DSB,
			X AS LA_DL_DSB_REB
		FROM
			FSA
			JOIN PKUB.FSXX_DL_LON FSXX
				ON FSA.AWARD_ID = CATX('',FSXX.LF_FED_AWD,PUT(FSXX.LN_FED_AWD_SEQ,ZX.))
			LEFT JOIN PKUB.LNXX_DSB LNXX
				ON FSXX.BF_SSN = LNXX.BF_SSN
				AND FSXX.LN_SEQ = LNXX.LN_SEQ
			LEFT JOIN PKUB.PDXX_PRS_NME PDXX
				ON FSXX.BF_SSN = PDXX.DF_PRS_ID
		WHERE
			LNXX.LA_DSB_CAN IS NOT NULL
	;
QUIT;
ENDRSUBMIT;

DATA DISBS; SET LEGEND.DISBS; RUN;
DATA CANCS; SET LEGEND.CANCS; RUN;

DATA COMB;
	SET DISBS CANCS;
RUN;

PROC SORT DATA=COMB;
	BY DF_SPE_ACC_ID AWARD_ID LD_DSB;
RUN;

DATA RUNTOT (DROP=DF_SPE_ACC_ID);
	SET COMB;
	BY DF_SPE_ACC_ID AWARD_ID;
	RETAIN LA_TOT;

	IF FIRST.AWARD_ID THEN LA_TOT = LA_DSB - COALESCE(LA_DL_DSB_REB, X);
	ELSE LA_TOT + LA_DSB - COALESCE(LA_DL_DSB_REB, X);
RUN;

PROC SQL;
	CREATE TABLE AWARDIDS AS
		SELECT DISTINCT
			'' AS DM_PRS_LST,
			'' AS DM_PRS_X,
			AWARD_ID,
			. AS LN_BR_DSB_SEQ,
			. AS LD_DSB,
			. AS LA_DSB,
			. AS LA_NEW_DSB
		FROM
			FSA
	;
QUIT;

DATA WITHBLANKS;
	SET RUNTOT AWARDIDS;
	LABEL
		DM_PRS_LST = 'Last Name'
		DM_PRS_X = 'First Name'
		AWARD_ID = 'Award ID'
		LN_BR_DSB_SEQ = 'Disb Seq'
		LD_DSB = 'Disb Date'
		LA_DSB = 'Disb Amount'
		LA_NEW_DSB = 'New Disb Amount'
	;
RUN;

PROC SORT DATA=WITHBLANKS;
	BY AWARD_ID LD_DSB;
RUN;

PROC EXPORT
		DATA=WITHBLANKS
		OUTFILE='T:\Disbursement Query for cornerstone_new_diff.XLSX'
		REPLACE;
RUN;
