LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;

PROC SQL;
	CREATE TABLE REBATE AS
		SELECT
			PDXX.DF_SPE_ACC_ID,
			LNXX.LN_SEQ,
			LNXX.LN_LON_BBS_SEQ,
			LC_BBS_DSQ_REA,
			LD_BBS_DSQ,
			LN_BBS_STS_PCV_PAY,
			LC_LON_BBT_DSQ_REA,
			LC_LON_BBT_STA,
			LN_LON_BBT_PAY,
			LN_BBS_STS_PCV_PAY,
			LD_LON_BBT_STA
		FROM
			PKUB.PDXX_PRS_NME PDXX
			JOIN PKUB.LNXX_LON_BBS LNXX
				ON PDXX.DF_PRS_ID = LNXX.BF_SSN
			JOIN PKUB.LNXX_LON_BBS_TIR LNXX
				ON LNXX.BF_SSN = LNXX.BF_SSN
				AND LNXX.LN_SEQ = LNXX.LN_SEQ
				AND LNXX.LN_LON_BBS_PGM_SEQ = LNXX.LN_LON_BBS_SEQ
		WHERE
			PDXX.DF_SPE_ACC_ID = 'XXXXXXXXXX'
			AND LC_STA_LNXX = 'A'
			AND LC_STA_LNXX = 'A'
	;
QUIT;
ENDRSUBMIT;

PROC EXPORT
		DATA=LEGEND.REBATE
		OUTFILE='T:\SAS\Rebate Revoke Date XXXXXXXXXX.XLSX'
		REPLACE;
RUN;
			
