/****** Script for SelectTopNRows command from SSMS  ******/
SELECT
	SUM(FirstBill) AS CountFirstBill,
	SUM(CoveredJuneBill) AS CountSatisfiedJuneBill,
	CAST(SUM(DAYS_PAST_DUE) /XXXXX AS DECIMAL(X,X)) AS AverageDaysPastDue,
	SUM(Delinquent) AS DeliquentBorrowers,
	XXXXX - SUM(Delinquent) AS CurrentBorrowers,
	COUNT(Recipient) AS TotalBorrowers
FROM
(
SELECT  DISTINCT
	[Recipient],
	[AccountNumber],
	[FirstName],
	ISNULL(LNXX.LN_DLQ_MAX,X) AS DAYS_PAST_DUE,
	CASE WHEN ISNULL(LNXX.LN_DLQ_MAX,X) = X THEN X ELSE X END AS Delinquent,
	CASE WHEN RSXX.BF_SSN IS NOT NULL THEN X ELSE X END AS FirstBill,
	CASE WHEN LNXX.BF_SSN IS NOT NULL THEN X ELSE X END AS CoveredJuneBill
FROM 
	[CLS].[emailbtcf].[CampaignData] CD
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_SPE_ACC_ID = CD.AccountNumber
	LEFT JOIN 
	(
		SELECT	
			LNXX.BF_SSN,
			MAX(LNXX.LN_DLQ_MAX) AS LN_DLQ_MAX
		FROM
			CDW..LNXX_LON_DLQ_HST LNXX
		WHERE
			LNXX.LC_STA_LONXX = 'X'
		GROUP BY
			LNXX.BF_SSN
	) LNXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	LEFT JOIN CDW..RSXX_BR_RPD RSXX
		ON RSXX.BF_SSN = PDXX.DF_PRS_ID
		AND CAST(RSXX.LD_RPS_X_PAY_DU AS DATE) BETWEEN 'XXXX-XX-XX' AND 'XXXX-XX-XX'
		AND RSXX.LC_STA_RPSTXX = 'A'
	LEFT JOIN CDW..LNXX_LON_BIL_CRF LNXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
		AND LNXX.LC_STA_LONXX = 'A'
		AND ISNULL(LNXX.LA_BIL_DU_PRT,X) <= ISNULL(LNXX.LA_TOT_BIL_STS,X)
		AND CAST(LNXX.LD_BIL_DU_LON AS DATE) BETWEEN 'XXXX-XX-XX' AND 'XXXX-XX-XX'
WHERE 
	EmailCampaignId = XX 
	AND CAST(AddedAt AS DATE) = 'XX/XX/XXXX'
) Data