LIBNAME JUL 'T:\July Closed School.xlsx';
DATA WORK.XLSOURCE (DROP=OPE_ID);
	SET 
		JUL.'SheetX$'N;
	IF OPE_ID ^= .;
	OPEID = PUT(OPE_ID,ZX.);
RUN;
LIBNAME JUL CLEAR;

LIBNAME  LEGEND  REMOTE  SERVER=LEGEND SLIBREF=WORK;
DATA LEGEND.XLSOURCE;
SET XLSOURCE;
RUN;
RSUBMIT LEGEND;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
	CREATE TABLE CLOSED_SCHOOLS AS
		SELECT DISTINCT
			PDXX.DF_SPE_ACC_ID 					AS Account_Number  
			,LNXX.LN_SEQ 						AS Loan_Seq 
			,CATX(' ', PDXX.DM_PRS_X, PDXX.DM_PRS_LST)	AS Borrower_Name 
			,PDXX.DX_STR_ADR_X 					AS Borrower_Street_Add_X  
			,PDXX.DX_STR_ADR_X 					AS Borrower_Street_Add_X  
			,PDXX.DM_CT 						AS Bororwer_City  
			,PDXX.DC_DOM_ST 					AS Borrower_State 
			,PDXX.DF_ZIP_CDE 					AS Borrower_Zip 
			,PDXX.DM_FGN_CNY 					AS Borrower_Foreign_Country  
			,PDXX.DI_VLD_ADR 					AS Borrower_Add_Validity  
			,LNXX.LF_DOE_SCL_ORG 				AS Original_School_Code  
			,SDXX.LF_DOE_SCL_ENR_CUR 			AS Current_School_Code  
			,SDXX.LD_SCL_SPR 					AS Separation_Date   
			,SDXX.LC_REA_SCL_SPR 				AS Separation_Reason    
			,XL.CLOSURE_DATE
		FROM
			PKUB.LNXX_LON LNXX
			INNER JOIN PKUB.PDXX_PRS_NME PDXX
				ON LNXX.BF_SSN = PDXX.DF_PRS_ID
			INNER JOIN PKUB.PDXX_PRS_ADR PDXX
				ON LNXX.BF_SSN = PDXX.DF_PRS_ID
			INNER JOIN PKUB.SDXX_STU_SPR SDXX
				ON LNXX.BF_SSN = SDXX.LF_STU_SSN
				AND SDXX.LC_STA_STUXX = 'A'
			INNER JOIN XLSOURCE XL
				ON (
						LNXX.LF_DOE_SCL_ORG = XL.OPEID
						OR SDXX.LF_DOE_SCL_ENR_CUR = XL.OPEID
					)
		;
QUIT;
ENDRSUBMIT;

DATA CLOSED_SCHOOLS; 
	SET LEGEND.CLOSED_SCHOOLS; 
	LEFT_CLOSURE_DAYS = CLOSURE_DATE - SEPARATION_DATE;
	IF LEFT_CLOSURE_DAYS <= XXX;
RUN;

PROC EXPORT
	DATA=CLOSED_SCHOOLS
	OUTFILE='T:\SAS\CNH XXXXX.xlsx'
	REPLACE;
RUN;	
