SELECT
	LNXX.BF_SSN,
	LNXX.LN_SEQ,
	LNXX.LN_FAT_SEQ,
	LNXX.LD_FAT_APL,
	LNXX.LF_DOE_SCL_ORG
FROM
	CDW..LNXX_FIN_ATY LNXX
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
WHERE
	LNXX.PC_FAT_TYP = 'XX'
	AND LNXX.PC_FAT_SUB_TYP = 'XX'
	AND LNXX.LC_WOF_WUP_REA = 'D'
	AND CAST(LNXX.LD_FAT_APL AS DATE) > CAST('XXXX-XX-XX' AS DATE)
	AND LNXX.LC_STA_LONXX = 'A'
	AND LNXX.LC_FAT_REV_REA = ''
ORDER BY
	LNXX.BF_SSN,
	LNXX.LN_SEQ,
	LNXX.LN_FAT_SEQ