--note: DICSK: school closure --this is not "DISCK"!!!
--note: DIFCR: false certification

/****************CHECK ATTENDANCE********************/
USE CDW
GO

DECLARE @OPEID TABLE (OPEID VARCHAR(X));
INSERT INTO @OPEID (OPEID) VALUES
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX'), 
('XXXXXXXX')
;
--select * from @OPEID

DECLARE @ARC VARCHAR(X) = 'DIFCR';

----generic query
--SELECT DISTINCT * FROM SCXX_SCH_DMO A INNER JOIN @OPEID O ON O.OPEID = A.IF_DOE_SCL
--SELECT DISTINCT * FROM LNXX_LON		A INNER JOIN @OPEID O ON O.OPEID = A.LF_DOE_SCL_ORG order by LD_TRM_BEG
--SELECT DISTINCT * FROM SDXX_STU_SPR	A INNER JOIN @OPEID O ON O.OPEID = A.LF_DOE_SCL_ENR_CUR

DROP TABLE IF EXISTS #BORROWERS;
SELECT 
	* 
INTO 
	#BORROWERS 
FROM 
	(
		--enrolled
		SELECT DISTINCT
			'LNXX' AS SOURCE,
			O.OPEID,
			PDXX.DM_PRS_X AS FirstName,
			PDXX.DM_PRS_LST AS LastName,
			LNXX.BF_SSN AS SSN,
			LNXX.LD_TRM_BEG,
			AYXX.LD_ATY_REQ_RCV,
			AYXX.LC_STA_ACTYXX,
			AYXX.PF_REQ_ACT
			--LNXX.LF_DOE_SCL_ORG --AS LNXX_LF_DOE_SCL_ORG,
			--MRXX.LF_DOE_SCL_ENR_CUR AS MRXX_LF_DOE_SCL_ENR_CUR
		FROM
			PDXX_PRS_NME PDXX
			INNER JOIN AYXX_BR_LON_ATY AYXX
				ON PDXX.DF_PRS_ID = AYXX.BF_SSN
			INNER JOIN LNXX_LON LNXX
				ON LNXX.BF_SSN = PDXX.DF_PRS_ID
			INNER JOIN @OPEID O
				ON LNXX.LF_DOE_SCL_ORG = O.OPEID
		WHERE
			AYXX.PF_REQ_ACT = @ARC

		UNION

		--ever attended
		SELECT DISTINCT
			'MRXX' AS SOURCE,
			O.OPEID,
			PDXX.DM_PRS_X AS FirstName,
			PDXX.DM_PRS_LST AS LastName,
			PDXX.DF_PRS_ID AS SSN,
			LNXX.LD_TRM_BEG,
			AYXX.LD_ATY_REQ_RCV,
			AYXX.LC_STA_ACTYXX,
			AYXX.PF_REQ_ACT
			--LNXX.LF_DOE_SCL_ORG --AS LNXX_LF_DOE_SCL_ORG,
			--MRXX.LF_DOE_SCL_ENR_CUR AS MRXX_LF_DOE_SCL_ENR_CUR
		FROM
			PDXX_PRS_NME PDXX
			INNER JOIN AYXX_BR_LON_ATY AYXX
				ON PDXX.DF_PRS_ID = AYXX.BF_SSN
			INNER JOIN
			(
				SELECT DISTINCT * FROM OPENQUERY (LEGEND,'
				SELECT
					BF_SSN,
					LF_DOE_SCL_ENR_CUR 
				FROM 
					PKUR.MRXX_MGT_RPT_LON
				WHERE
					LF_DOE_SCL_ENR_CUR IN 
					(
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX'',
''XXXXXXXX''
					)
				')
			) MRXX
				ON  PDXX.DF_PRS_ID = MRXX.BF_SSN
			INNER JOIN @OPEID O
				ON MRXX.LF_DOE_SCL_ENR_CUR = O.OPEID
			LEFT JOIN LNXX_LON LNXX
				ON LNXX.BF_SSN = PDXX.DF_PRS_ID
		WHERE
			AYXX.PF_REQ_ACT = @ARC

)POP
;

SELECT * FROM #BORROWERS ORDER BY SSN

select * from LNXX_LON where BF_SSN = ''
--select * from SDXX_STU_SPR where LF_STU_SSN = ''
--select * from AYXX_BR_LON_ATY where BF_SSN = '' 

--note: DIFCR arcs might not have the correlating arcs that DICSK arcs have. Will need to check with BU to see how they track them



----if DICSK school closure borrowers found then:
--DECLARE @ARCX VARCHAR(X) = 'DICSK'--note: this is not "DISCK"!!!"
--		--,@BEGINDATE DATE = 'XXXXXXXX'
--		--,@ENDDATE DATE = 'XXXXXXXX'
--;
--SELECT DISTINCT
--	BOR.FirstName,
--	BOR.LastName,
--	BOR.SSN,
--	BOR.LD_TRM_BEG,
--	BOR.PF_REQ_ACT,
--	BOR.LD_ATY_REQ_RCV,
--	AYXX.PF_REQ_ACT,
--	AYXX.LD_ATY_REQ_RCV,
--	CASE
--		WHEN AYXX.PF_REQ_ACT = 'CSDNY' THEN 'DENIED'
--		WHEN AYXX.PF_REQ_ACT IN ('CSFSA',@ARCX) THEN 'PENDING'
--		WHEN AYXX.PF_REQ_ACT = 'ADCSH' THEN 'APPROVED'
--	END AS 'STATUS'
--	--MAX(AYXX.LD_ATY_REQ_RCV) AS LD_ATY_REQ_RCV
--FROM
--	#BORROWERS BOR
--	INNER JOIN AYXX_BR_LON_ATY AYXX
--		ON BOR.SSN = AYXX.BF_SSN
--	INNER JOIN
--	(--get most recent arc
--		SELECT
--			BF_SSN,
--			MAX(LD_ATY_REQ_RCV) AS LD_ATY_REQ_RCV
--		FROM
--			AYXX_BR_LON_ATY
--		WHERE
--			PF_REQ_ACT IN ('CSDNY','CSFSA','ADCSH',@ARCX)
--		GROUP BY
--			BF_SSN
--	)AYXXmax
--		ON AYXX.BF_SSN = AYXXmax.BF_SSN
--		AND AYXX.LD_ATY_REQ_RCV = AYXXmax.LD_ATY_REQ_RCV
--WHERE
--	--BOR.LD_TRM_BEG BETWEEN @BEGINDATE AND @ENDDATE
--	--AND
--	 AYXX.PF_REQ_ACT IN ('CSDNY','CSFSA','ADCSH',@ARCX)
--ORDER BY
--	BOR.SSN,
--	AYXX.LD_ATY_REQ_RCV
--;
