SELECT
	PDXX.DF_PRS_ID AS ACCOUNT_NUMBER,
	DWXX.LN_SEQ LOAN_SEQ,
	LNXX.LD_LON_X_DSB,
	DWXX.WD_LON_RPD_SR as REPAYMENT_START_DATE
FROM
	CDW..DWXX_DW_CLC_CLU DWXX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = DWXX.BF_SSN
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = DWXX.BF_SSN
		AND LNXX.LN_SEQ = DWXX.LN_SEQ
WHERE
	DWXX.WD_LON_RPD_SR < LNXX.LD_LON_X_DSB