USE CDW
GO

SELECT DISTINCT
	LTRIM(RTRIM(PDXX.DM_PRS_X)) + ' ' + LTRIM(RTRIM(PDXX.DM_PRS_LST)) AS NAME,
	AYXX.*
FROM
	CDW..PDXX_PRS_NME PDXX
	INNER JOIN 
	(
		SELECT
			AYXX.BF_SSN,
			AYXX.PF_REQ_ACT AS ARC,
			CAST(AYXX.LD_ATY_REQ_RCV AS DATE) AS ARC_REC_DATE,
			CAST(AYXX.LD_ATY_RSP AS DATE) AS ARC_COMPLETE_DATE,
			LF_PRF_BY AS [USER_ID]
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
		WHERE
			AYXX.LD_ATY_REQ_RCV BETWEEN 'XX/XX/XXXX' AND 'XX/XX/XXXX'
			AND AYXX.PF_REQ_ACT IN ('DITLF','TLDNY','ADTLF')
	) AYXX
	ON AYXX.BF_SSN = PDXX.DF_PRS_ID

SELECT DISTINCT
	LTRIM(RTRIM(PDXX.DM_PRS_X)) + ' ' + LTRIM(RTRIM(PDXX.DM_PRS_LST)) AS NAME,
	AYXX.*
FROM
	CDW..PDXX_PRS_NME PDXX
	INNER JOIN 
	(
		SELECT
			AYXX.BF_SSN,
			AYXX.PF_REQ_ACT AS ARC,
			CAST(AYXX.LD_ATY_REQ_RCV AS DATE) AS ARC_REC_DATE,
			CAST(AYXX.LD_ATY_RSP AS DATE) AS ARC_COMPLETE_DATE,
			LF_PRF_BY AS [USER_ID]
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
		WHERE
			AYXX.LD_ATY_REQ_RCV BETWEEN 'XX/XX/XXXX' AND 'XX/XX/XXXX'
			AND AYXX.PF_REQ_ACT IN ('DITPD','TPDNY','ADTPD')
	) AYXX
	ON AYXX.BF_SSN = PDXX.DF_PRS_ID

SELECT DISTINCT
	LTRIM(RTRIM(PDXX.DM_PRS_X)) + ' ' + LTRIM(RTRIM(PDXX.DM_PRS_LST)) AS NAME,
	AYXX.*
FROM
	CDW..PDXX_PRS_NME PDXX
	INNER JOIN 
	(
		SELECT
			AYXX.BF_SSN,
			AYXX.PF_REQ_ACT AS ARC,
			CAST(AYXX.LD_ATY_REQ_RCV AS DATE) AS ARC_REC_DATE,
			CAST(AYXX.LD_ATY_RSP AS DATE) AS ARC_COMPLETE_DATE,
			LF_PRF_BY AS [USER_ID]
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
		WHERE
			AYXX.LD_ATY_REQ_RCV BETWEEN 'XX/XX/XXXX' AND 'XX/XX/XXXX'
			AND AYXX.PF_REQ_ACT IN ('DIUPR','UPDNY','ADUPR')
	) AYXX
	ON AYXX.BF_SSN = PDXX.DF_PRS_ID

SELECT DISTINCT
	LTRIM(RTRIM(PDXX.DM_PRS_X)) + ' ' + LTRIM(RTRIM(PDXX.DM_PRS_LST)) AS NAME,
	AYXX.*
FROM
	CDW..PDXX_PRS_NME PDXX
	INNER JOIN 
	(
		SELECT
			AYXX.BF_SSN,
			AYXX.PF_REQ_ACT AS ARC,
			CAST(AYXX.LD_ATY_REQ_RCV AS DATE) AS ARC_REC_DATE,
			CAST(AYXX.LD_ATY_RSP AS DATE) AS ARC_COMPLETE_DATE,
			LF_PRF_BY AS [USER_ID]
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
		WHERE
			AYXX.LD_ATY_REQ_RCV BETWEEN 'XX/XX/XXXX' AND 'XX/XX/XXXX'
			AND AYXX.PF_REQ_ACT IN ('DISPC','SPDNY','ADSPC')
	) AYXX
	ON AYXX.BF_SSN = PDXX.DF_PRS_ID

SELECT DISTINCT
	LTRIM(RTRIM(PDXX.DM_PRS_X)) + ' ' + LTRIM(RTRIM(PDXX.DM_PRS_LST)) AS NAME,
	AYXX.*
FROM
	CDW..PDXX_PRS_NME PDXX
	INNER JOIN 
	(
		SELECT
			AYXX.BF_SSN,
			AYXX.PF_REQ_ACT AS ARC,
			CAST(AYXX.LD_ATY_REQ_RCV AS DATE) AS ARC_REC_DATE,
			CAST(AYXX.LD_ATY_RSP AS DATE) AS ARC_COMPLETE_DATE,
			LF_PRF_BY AS [USER_ID]
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
		WHERE
			AYXX.LD_ATY_REQ_RCV BETWEEN 'XX/XX/XXXX' AND 'XX/XX/XXXX'
			AND AYXX.PF_REQ_ACT IN ('DIFCR','FCDNY','ADFCR')
	) AYXX
	ON AYXX.BF_SSN = PDXX.DF_PRS_ID

SELECT DISTINCT
	LTRIM(RTRIM(PDXX.DM_PRS_X)) + ' ' + LTRIM(RTRIM(PDXX.DM_PRS_LST)) AS NAME,
	AYXX.*
FROM
	CDW..PDXX_PRS_NME PDXX
	INNER JOIN 
	(
		SELECT
			AYXX.BF_SSN,
			AYXX.PF_REQ_ACT AS ARC,
			CAST(AYXX.LD_ATY_REQ_RCV AS DATE) AS ARC_REC_DATE,
			CAST(AYXX.LD_ATY_RSP AS DATE) AS ARC_COMPLETE_DATE,
			LF_PRF_BY AS [USER_ID]
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
		WHERE
			AYXX.LD_ATY_REQ_RCV BETWEEN 'XX/XX/XXXX' AND 'XX/XX/XXXX'
			AND AYXX.PF_REQ_ACT IN ('DIDTH','DTDNY','ADDTH')
	) AYXX
	ON AYXX.BF_SSN = PDXX.DF_PRS_ID