SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SELECT DISTINCT
	FSXX.LF_FED_AWD + RIGHT('XXX' + CAST(FSXX.LN_FED_AWD_SEQ AS VARCHAR(X)), X) AS [Award ID],
	LNXX.BF_SSN AS SSN,
	COALESCE(SUBSTRING(WQXX.LX_ATY, CHARINDEX(':', WQXX.LX_ATY, X) + X, XXX), WQXX.WX_MSG_X_TSK) AS [Latest Reject Reason],
	COALESCE(CAST(SUBSTRING(WQXX.LX_ATY, X, XX) AS DATE),DATEADD(DAY, -X, WQXX.WD_ACT_REQ)) AS [Latest Reject Date],
	DATEDIFF(DAY, LNXX.LD_DLQ_OCC, GETDATE()) AS [# of Days Delinquent]
FROM
	CDW..PDXX_PRS_NME PDXX
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	INNER JOIN CDW..FSXX_DL_LON FSXX
		ON FSXX.BF_SSN = LNXX.BF_SSN
		AND FSXX.LN_SEQ = LNXX.LN_SEQ
	INNER JOIN CDW..DWXX_DW_CLC_CLU DWXX
		ON DWXX.BF_SSN = LNXX.BF_SSN
		AND DWXX.LN_SEQ = LNXX.LN_SEQ
		AND DWXX.WX_OVR_DW_LON_STA IN ('REJECT DELQ TRANSFER','SUBMIT DELQ TRANSFER','PEND DELQ TRANSFER')
	INNER JOIN 
	(
		SELECT DISTINCT
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			COUNT(*) OVER(PARTITION BY LNXX.BF_SSN, LNXX.LN_SEQ) AS ArcOccurances
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
			INNER JOIN CDW..LNXX_LON_ATY LNXX
				ON LNXX.BF_SSN = AYXX.BF_SSN
				AND LNXX.LN_ATY_SEQ = AYXX.LN_ATY_SEQ
		WHERE
			AYXX.LC_STA_ACTYXX = 'A'
			AND AYXX.PF_REQ_ACT = 'DCSRR'
	) Arcs
		ON Arcs.BF_SSN = LNXX.BF_SSN
		AND Arcs.LN_SEQ = LNXX.LN_SEQ
		AND Arcs.ArcOccurances > X
	INNER JOIN 
	(
		SELECT DISTINCT
			WQXX.BF_SSN,
			WQXX.WX_MSG_X_TSK,
			WQXX.WD_ACT_REQ,
			AYXX.LX_ATY
		FROM
			CDW..WQXX_TSK_QUE WQXX
			LEFT JOIN CDW..AYXX_ATY_TXT AYXX
				ON WQXX.BF_SSN = AYXX.BF_SSN
				AND WQXX.LN_ATY_SEQ = AYXX.LN_ATY_SEQ
		WHERE
			WQXX.PF_REQ_ACT = 'DCSRR'
	) WQXX
		ON WQXX.BF_SSN = Arcs.BF_SSN
	LEFT JOIN CDW..LNXX_LON_DLQ_HST LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
		AND LNXX.LC_STA_LONXX = 'X'
ORDER BY
	[# of Days Delinquent]
DESC	

SELECT TOP X
	COUNT(LNXX.LN_SEQ) OVER() AS NumberOfLoans,
	AVG(DATEDIFF(DAY, LNXX.LD_DLQ_OCC, GETDATE()) - XXX) OVER() AS AverageAge,
	MAX(DATEDIFF(DAY, LNXX.LD_DLQ_OCC, GETDATE()) - XXX) OVER() AS OldestAge,
	COALESCE(SUBSTRING(WQXX.LX_ATY, CHARINDEX(':', WQXX.LX_ATY, X) + X, XXX), WQXX.WX_MSG_X_TSK) AS [Reject Reason]
FROM
	CDW..PDXX_PRS_NME PDXX
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	INNER JOIN CDW..FSXX_DL_LON FSXX
		ON FSXX.BF_SSN = LNXX.BF_SSN
		AND FSXX.LN_SEQ = LNXX.LN_SEQ
	INNER JOIN CDW..DWXX_DW_CLC_CLU DWXX
		ON DWXX.BF_SSN = LNXX.BF_SSN
		AND DWXX.LN_SEQ = LNXX.LN_SEQ
		AND DWXX.WX_OVR_DW_LON_STA IN ('REJECT DELQ TRANSFER','SUBMIT DELQ TRANSFER','PEND DELQ TRANSFER')
	INNER JOIN 
	(
		SELECT DISTINCT
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			COUNT(*) OVER(PARTITION BY LNXX.BF_SSN, LNXX.LN_SEQ) AS ArcOccurances
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
			INNER JOIN CDW..LNXX_LON_ATY LNXX
				ON LNXX.BF_SSN = AYXX.BF_SSN
				AND LNXX.LN_ATY_SEQ = AYXX.LN_ATY_SEQ
		WHERE
			AYXX.LC_STA_ACTYXX = 'A'
			AND AYXX.PF_REQ_ACT = 'DCSRR'
	) Arcs
		ON Arcs.BF_SSN = LNXX.BF_SSN
		AND Arcs.LN_SEQ = LNXX.LN_SEQ
	INNER JOIN 
	(
		SELECT DISTINCT
			WQXX.BF_SSN,
			WQXX.WX_MSG_X_TSK,
			WQXX.WD_ACT_REQ,
			AYXX.LX_ATY
		FROM
			CDW..WQXX_TSK_QUE WQXX
			INNER JOIN
			(
				SELECT
					BF_SSN,
					MAX(LN_ATY_SEQ) AS LN_ATY_SEQ
				FROM
					CDW..WQXX_TSK_QUE
				WHERE
					PF_REQ_ACT = 'DCSRR'
				GROUP BY
					BF_SSN
			) MaxedWQXX
				ON MaxedWQXX.BF_SSN = WQXX.BF_SSN
				AND MaxedWQXX.LN_ATY_SEQ = WQXX.LN_ATY_SEQ
			LEFT JOIN CDW..AYXX_ATY_TXT AYXX
				ON WQXX.BF_SSN = AYXX.BF_SSN
				AND WQXX.LN_ATY_SEQ = AYXX.LN_ATY_SEQ
	) WQXX
		ON WQXX.BF_SSN = Arcs.BF_SSN
	LEFT JOIN CDW..LNXX_LON_DLQ_HST LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
		AND LNXX.LC_STA_LONXX = 'X'
WHERE
	DATEDIFF(DAY, LNXX.LD_DLQ_OCC, GETDATE()) >= XXX	
ORDER BY
	DATEDIFF(DAY, LNXX.LD_DLQ_OCC, GETDATE()) - XXX
