SELECT * FROM OPENQUERY(LEGEND,
'
		SELECT DISTINCT	
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			LNXX.IC_LON_PGM
		FROM	
			PKUB.LNXX_LON LNXX
			INNER JOIN PKUB.PDXX_PRS_NME PDXX
				ON LNXX.BF_SSN = PDXX.DF_PRS_ID
			INNER JOIN PKUB.DWXX_DW_CLC_CLU DWXX
				ON LNXX.BF_SSN = DWXX.BF_SSN
				AND LNXX.LN_SEQ = DWXX.LN_SEQ
			LEFT JOIN
			(
				SELECT
					LNXX.BF_SSN,
					LNXX.LN_SEQ
				FROM
					PKUB.LNXX_LON LNXX
					INNER JOIN PKUB.LNXX_INT_RTE_HST LNXX
						ON LNXX.BF_SSN = LNXX.BF_SSN
						AND LNXX.LN_SEQ = LNXX.LN_SEQ
				WHERE
					LNXX.LC_ITR_TYP = ''FX''
					AND	LNXX.LC_STA_LONXX = ''A''
					AND	CURRENT DATE BETWEEN LNXX.LD_ITR_EFF_BEG AND LNXX.LD_ITR_EFF_END
					AND	LNXX.LC_STA_LONXX = ''R''
					AND LNXX.LA_CUR_PRI > X
					AND	LNXX.IC_LON_PGM IN 
					(
						''DLUCNS'', ''DLSCNS'', ''CNSLDN'', ''DSCON'',  ''DLUSPL'', ''DUCON'', 
						''SPCNSL'', ''SUBCNS'', ''SUBSPC'', ''UNCNS'',  ''DLSPCN'', ''DLSSPL'', 
						''DLCNSL'', ''DLPCNS'', ''UNSPC'',  ''DLSCST'', ''DLSCUN'', ''DLSCPL'', 
						''DLSCPG'', ''DLSCSL'', ''DLSCSC'', ''DLSCUC'', ''DLSCCN''
					)	
			) FIXED_CONSOL
				ON LNXX.BF_SSN = FIXED_CONSOL.BF_SSN
				AND LNXX.LN_SEQ = FIXED_CONSOL.LN_SEQ
		WHERE	
			LNXX.LC_STA_LONXX = ''R''
			AND LNXX.LA_CUR_PRI > X
			AND	DWXX.WC_DW_LON_STA IN (''XX'',''XX'',''XX'',''XX'',''XX'',''XX'',''XX'',''XX'',''XX'',''XX'')
			AND FIXED_CONSOL.BF_SSN IS NULL


')