USE CDW
GO
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
DECLARE @REVIEWDATE DATE = 'X/X/XXXX'

SELECT DISTINCT
	LNXX.BF_SSN
	,LNXX.PC_FAT_TYP
	,LNXX.PC_FAT_SUB_TYP
	,LNXX.LD_FAT_APL
FROM
	LNXX_FIN_ATY LNXX
WHERE
	LNXX.PC_FAT_TYP = 'XX'
	AND LNXX.PC_FAT_SUB_TYP IN ('XX')
	AND LNXX.LD_FAT_APL between 'XX/XX/XXXX' and 'XX/XX/XXXX'
