--Current Accounts
SELECT DISTINCT
	WQXX.WF_QUE,
	WQXX.WF_SUB_QUE,
	WQXX.WN_CTL_TSK,
	WQXX.PF_REQ_ACT,
	'Current'
FROM
	CDW..WQXX_TSK_QUE WQXX
	LEFT JOIN CDW..LNXX_LON_DLQ_HST LNXX
		ON LNXX.BF_SSN = WQXX.BF_SSN
		AND LNXX.LC_STA_LONXX = 'X'
		AND CAST(LNXX.LD_DLQ_MAX AS DATE) = CAST(DATEADD(DAY,-X,GETDATE()) AS DATE)
WHERE
	WQXX.WF_QUE = 'DX'
	AND WQXX.WF_SUB_QUE = 'XX'
	AND WQXX.WC_STA_WQUEXX NOT IN ('X','C')
	AND LNXX.BF_SSN IS NULL

UNION

SELECT DISTINCT
	WQXX.WF_QUE,
	WQXX.WF_SUB_QUE,
	WQXX.WN_CTL_TSK,
	WQXX.PF_REQ_ACT,
	'Delinquent Duplicates'
FROM
	CDW..WQXX_TSK_QUE WQXX
	INNER JOIN CDW..LNXX_LON_DLQ_HST LNXX
		ON LNXX.BF_SSN = WQXX.BF_SSN
		AND LNXX.LC_STA_LONXX = 'X'
		AND CAST(LNXX.LD_DLQ_MAX AS DATE) = CAST(DATEADD(DAY,-X,GETDATE()) AS DATE)
	LEFT JOIN 
	(
		SELECT DISTINCT
			WQXX.WF_QUE,
			WQXX.WF_SUB_QUE,
			MIN(WQXX.WN_CTL_TSK) AS WN_CTL_TSK,
			WQXX.PF_REQ_ACT,
			WQXX.BF_SSN
		FROM
			CDW..WQXX_TSK_QUE WQXX
			INNER JOIN CDW..LNXX_LON_DLQ_HST LNXX
				ON LNXX.BF_SSN = WQXX.BF_SSN
				AND LNXX.LC_STA_LONXX = 'X'
				AND CAST(LNXX.LD_DLQ_MAX AS DATE) = CAST(DATEADD(DAY,-X,GETDATE()) AS DATE)
		WHERE
			WQXX.WF_QUE = 'DX'
			AND WQXX.WF_SUB_QUE = 'XX'
			AND WQXX.WC_STA_WQUEXX NOT IN ('X','C')
		GROUP BY
			WQXX.WF_QUE,
			WQXX.WF_SUB_QUE,
			WQXX.PF_REQ_ACT,
			WQXX.BF_SSN
	) KeepTask
		ON KeepTask.WF_QUE = WQXX.WF_QUE
		AND KeepTask.WF_SUB_QUE = WQXX.WF_SUB_QUE
		AND KeepTask.PF_REQ_ACT = WQXX.PF_REQ_ACT
		AND KeepTask.BF_SSN = WQXX.BF_SSN
		AND KeepTask.WN_CTL_TSK = WQXX.WN_CTL_TSK
WHERE
	WQXX.WF_QUE = 'DX'
	AND WQXX.WF_SUB_QUE = 'XX'
	AND WQXX.WC_STA_WQUEXX NOT IN ('X','C')
	AND KeepTask.BF_SSN IS NULL
