USE CDW
GO

DECLARE @DATEX DATE = 'X/X/XX'
--SELECT @DATEX

SELECT DISTINCT
	LNXX.BF_SSN
	,LNXX.LN_SEQ
	,LNXX.LC_STA_LONXX
	,CASE
		WHEN LNXX.LA_CUR_PRI > X.XX
		THEN '>X'
		ELSE 'ERROR'
	END AS LA_CUR_PRI
	,LNXX.LD_LON_EFF_ADD
	,CASE
		WHEN LNXX.LC_TYP_SCH_DIS IN ('IB', 'IL', 'IP', 'IX, CQ', 'CX', 'CX', 'CX', 'CA', 'CP, IX', 'IA')
		THEN 'IDR'
		ELSE 'NOT IDR'
	END AS LNXX_FLAG
FROM
	..LNXX_LON LNXX
	INNER JOIN ..LNXX_LON_RPS LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
	LEFT JOIN
	(
		SELECT
			BF_SSN
			,LN_SEQ
		FROM
			..LNXX_LON_RPS
		WHERE
			LC_TYP_SCH_DIS IN ('IB', 'IL', 'IP', 'IX, CQ', 'CX', 'CX', 'CX', 'CA', 'CP, IX', 'IA')
	) LNXXA
		ON LNXX.BF_SSN = LNXXA.BF_SSN
		AND LNXX.LN_SEQ = LNXXA.LN_SEQ
WHERE
	LNXXA.BF_SSN IS NULL
	AND LNXXA.LN_SEQ IS NULL
	AND LNXX.LC_STA_LONXX = 'R'
	AND LNXX.LA_CUR_PRI > X.XX
	AND LNXX.LD_LON_EFF_ADD < @DATEX
ORDER BY
	--LNXX.LD_LON_EFF_ADD DESC
	LNXX.BF_SSN
	,LNXX.LN_SEQ



--Provide uniquue loan count.
;WITH LOANS AS
(
	SELECT DISTINCT
		LNXX.BF_SSN
		,LNXX.LN_SEQ
	FROM
		..LNXX_LON LNXX
		INNER JOIN ..LNXX_LON_RPS LNXX
			ON LNXX.BF_SSN = LNXX.BF_SSN
			AND LNXX.LN_SEQ = LNXX.LN_SEQ
		LEFT JOIN
		(
			SELECT
				BF_SSN
				,LN_SEQ
			FROM
				..LNXX_LON_RPS
			WHERE
				LC_TYP_SCH_DIS IN ('IB', 'IL', 'IP', 'IX, CQ', 'CX', 'CX', 'CX', 'CA', 'CP, IX', 'IA')
		) LNXXA
			ON LNXX.BF_SSN = LNXXA.BF_SSN
			AND LNXX.LN_SEQ = LNXXA.LN_SEQ
	WHERE
		LNXXA.BF_SSN IS NULL
		AND LNXXA.LN_SEQ IS NULL
		AND LNXX.LC_STA_LONXX = 'R'
		AND LNXX.LA_CUR_PRI > X.XX
		AND LNXX.LD_LON_EFF_ADD < @DATEX
)
SELECT
	COUNT(*) AS LOAN_COUNT
FROM
	LOANS