SELECT 
	LNXX.BF_SSN,
	LNXX.LN_SEQ,
	LNXX.LN_DLQ_MAX,
	CAST(LNXX.LD_DLQ_MAX AS DATE) AS LD_DLQ_MAX,
	CASE WHEN AYXX.BF_SSN IS NULL THEN 'FALSE' ELSE 'TRUE' END AS HASARC
FROM 
	CDW..LNXX_LON_DLQ_HST LNXX 
	LEFT JOIN CDW..AYXX_BR_LON_ATY AYXX 
		ON AYXX.BF_SSN = LNXX.BF_SSN 
		AND AYXX.PF_REQ_ACT = 'DLFDL'
		AND CAST(AYXX.LD_ATY_REQ_RCV AS DATE) BETWEEN 'XXXX-XX-XX' AND 'XXXX-XX-XX'
WHERE 
	LNXX.LC_STA_LONXX = 'X' 
	AND LNXX.LN_DLQ_MAX >= XXX 
	AND CAST(LNXX.LD_DLQ_MAX AS DATE) BETWEEN 'XXXX-XX-XX' AND 'XXXX-XX-XX'
	
