DECLARE @DATA TABLE (BF_SSN CHAR(X), LN_SEQ INT)
INSERT INTO @DATA VALUES
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X),
('XXXXXXXXX',X)


SELECT
	*
FROM
	CDW..LNXX_FIN_ATY LNXX
	INNER JOIN @DATA D
		ON D.BF_SSN = LNXX.BF_SSN
		AND D.LN_SEQ = LNXX.LN_SEQ
WHERE
	LNXX.PC_FAT_TYP = 'XX'
	AND LNXX.PC_FAT_SUB_TYP = 'XX'
	AND LNXX.LD_FAT_EFF > 'XX/XX/XXXX'
ORDER BY
	LNXX.BF_SSN,
	LNXX.LN_SEQ,
	LNXX.LD_FAT_EFF