SELECT
	POP.DF_SPE_ACC_ID,
	POP.LN_SEQ,
	SUM(POP.DAYS_USED) AS DAYS_USED
FROM
(
SELECT DISTINCT
	PD10.DF_SPE_ACC_ID,
	LN60.LN_SEQ,
	CASE 
		WHEN CAST(LN60.LD_FOR_END AS DATE) < '02/29/2020' THEN DATEDIFF(DAY, CAST(LN60.LD_FOR_BEG AS DATE), CAST(LN60.LD_FOR_END AS DATE))
		ELSE DATEDIFF(DAY, CAST(LN60.LD_FOR_BEG AS DATE), '02/29/2020')
	END DAYS_USED
FROM
	CDW..FB10_BR_FOR_REQ FB10
	INNER JOIN CDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = FB10.BF_SSN
	INNER JOIN CDW..LN60_BR_FOR_APV LN60
		ON LN60.BF_SSN = FB10.BF_SSN
		AND LN60.LF_FOR_CTL_NUM = FB10.LF_FOR_CTL_NUM
	INNER JOIN CDW..LN10_LON LN10
		ON LN10.BF_SSN = LN60.BF_SSN
		AND LN10.LN_SEQ = LN60.LN_SEQ
		AND LN10.LA_CUR_PRI > 0
		AND LN10.LC_STA_LON10 = 'R'
WHERE
	LN60.LC_STA_LON60 = 'A'
	AND FB10.LC_STA_FOR10 = 'A'
	AND FB10.LC_FOR_STA = 'A' --denied records cant have this active
	AND LN60.LC_FOR_RSP != '003'
	AND FB10.LC_FOR_TYP = '39'
	
) POP
GROUP BY
	POP.DF_SPE_ACC_ID,
	POP.LN_SEQ
HAVING SUM(DAYS_USED) > 90
order by
	pop.DF_SPE_ACC_ID,
	pop.LN_SEQ