SELECT * FROM
(
	SELECT
		ROW_NUMBER() OVER (PARTITION BY LNXX.BF_SSN, LNXX.LN_SEQ ORDER BY LN_ITR_SEQ DESC) AS SEQ,
		lnXX.*
	FROM
		LNXX_INT_RTE_HST LNXX
		INNER JOIN PDXX_PRS_NME PDXX 
			ON PDXX.DF_PRS_ID = LNXX.BF_SSN
		INNER JOIN CDW..LNXX_LON LNXX
			ON LNXX.BF_SSN = LNXX.BF_SSN
			AND LNXX.LN_SEQ = LNXX.LN_SEQ
			AND LNXX.LA_CUR_PRI > X
			AND LNXX.LC_STA_LONXX = 'R'
	WHERE
		LR_ITR = X
		and LC_INT_RDC_PGM = 'S'
		AND LNXX.LD_ITR_EFF_END > 'XX-XX-XXXX'
) LNXX
WHERE
	seq = X
ORDER BY
	BF_SSN,
	LN_SEQ,
	SEQ