USE [CDW]
GO
/****** Object:  StoredProcedure [dbo].[LT_TSXXBDXXX_Loans]    Script Date: X/X/XXXX X:XX:XX AM ******/

SELECT 
	PDXX.DF_SPE_ACC_ID,
	LNXX.LN_SEQ,
	DEFER.LC_DFR_TYP,
	CONVERT(VARCHAR(XX), Defer.LD_DFR_BEG, XXX) AS [Begin Date],
	CONVERT(VARCHAR(XX), Defer.LD_DFR_END, XXX) AS [End Date]
FROM 
	PDXX_PRS_NME PDXX
	INNER JOIN LNXX_LON LNXX 
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
			
	INNER JOIN
	(
		SELECT 
			DFXX.LC_DFR_TYP,
			LNXX.LD_DFR_BEG,
			LNXX.LD_DFR_END,
			DFXX.LD_CRT_REQ_DFR,
			DFXX.LF_LST_DTS_DFXX,
			DFXX.LC_DFR_STA,
			LNXX.BF_SSN,
			LNXX.LN_SEQ
		FROM
			LNXX_BR_DFR_APV LNXX
			INNER JOIN DFXX_BR_DFR_REQ DFXX
				ON DFXX.BF_SSN = LNXX.BF_SSN
				AND DFXX.LF_DFR_CTL_NUM = LNXX.LF_DFR_CTL_NUM
					
		WHERE
			LNXX.LC_STA_LONXX = 'A'
			AND DFXX.LC_STA_DFRXX = 'A'
			AND DFXX.LC_DFR_STA = 'A' --Denied requests are valid
			and LNXX.LC_DFR_RSP != 'XXX'
			AND DFXX.LC_DFR_TYP = 'XX'
	) Defer
		ON Defer.BF_SSN = LNXX.BF_SSN
		AND Defer.LN_SEQ = LNXX.LN_SEQ
WHERE
	GETDATE() BETWEEN DEFER.LD_DFR_BEG AND DEFER.LD_DFR_END
	OR
	DEFER.LD_DFR_BEG >= 'XX/XX/XXXX'

SELECT 
	PDXX.DF_SPE_ACC_ID,
	LNXX.LN_SEQ,
	DEFER.LC_FOR_TYP,
	CONVERT(VARCHAR(XX), Defer.LD_FOR_BEG, XXX) AS [Begin Date],
	CONVERT(VARCHAR(XX), Defer.LD_FOR_END, XXX) AS [End Date]
FROM 
	PDXX_PRS_NME PDXX
	INNER JOIN LNXX_LON LNXX 
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
			
	INNER JOIN
	(
		SELECT 
			FBXX.LC_FOR_TYP,
			LNXX.LD_FOR_BEG,
			LNXX.LD_FOR_END,
			FBXX.LD_CRT_REQ_FOR,
			FBXX.LF_LST_DTS_FBXX,
			FBXX.LC_FOR_STA,
			LNXX.BF_SSN,
			LNXX.LN_SEQ
		FROM
			LNXX_BR_FOR_APV LNXX
			INNER JOIN FBXX_BR_FOR_REQ FBXX
				ON FBXX.BF_SSN = LNXX.BF_SSN
				AND FBXX.LF_FOR_CTL_NUM = LNXX.LF_FOR_CTL_NUM
					
		WHERE
			LNXX.LC_STA_LONXX = 'A'
			AND FBXX.LC_STA_FORXX = 'A'
			AND FBXX.LC_FOR_STA = 'A' --Denied requests are valid
			and LNXX.LC_FOR_RSP != 'XXX'
			AND FBXX.LC_FOR_TYP = 'XX'
	) Defer
		ON Defer.BF_SSN = LNXX.BF_SSN
		AND Defer.LN_SEQ = LNXX.LN_SEQ
WHERE
	GETDATE() BETWEEN DEFER.LD_FOR_BEG AND DEFER.LD_FOR_END
	OR
	DEFER.LD_FOR_BEG >= 'XX/XX/XXXX'
