LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
	CREATE TABLE LNS AS
		SELECT
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			LNXX.IC_LON_PGM,
			LNXX.LD_LON_X_DSB,
			LNXX.LR_ITR,
			CATX('',FSXX.LF_FED_AWD,PUT(LN_FED_AWD_SEQ,ZX.)) AS AWARD_ID
		FROM
			PKUB.LNXX_LON LNXX
			JOIN PKUB.LNXX_INT_RTE_HST LNXX
				ON LNXX.BF_SSN = LNXX.BF_SSN
				AND LNXX.LN_SEQ = LNXX.LN_SEQ
				AND LNXX.IC_LON_PGM IN ('DLSCNS','DLUCNS','DLSSPL','DLUSPL')
				AND LNXX.LA_CUR_PRI > X
				AND TODAY() BETWEEN LNXX.LD_ITR_EFF_BEG AND LNXX.LD_ITR_EFF_END
				AND LNXX.LC_STA_LONXX = 'A'
			JOIN PKUB.FSXX_DL_LON FSXX
				ON LNXX.BF_SSN = FSXX.BF_SSN
				AND LNXX.LN_SEQ = FSXX.LN_SEQ
	;

	CREATE TABLE CNS AS
		SELECT DISTINCT
			LNS.BF_SSN,
			SCNS.LN_SEQ AS SCNS_LN_SEQ,
 			SCNS.AWARD_ID AS SCNS_AWARD_ID,
 			SCNS.LR_ITR AS SCNS_LR_ITR,
			SCNS.LD_LON_X_DSB AS SCNS_LD_LON_X_DSB,
			UCNS.LN_SEQ AS UCNS_LN_SEQ,
 			UCNS.AWARD_ID AS UCNS_AWARD_ID,
 			UCNS.LR_ITR AS UCNS_LR_ITR,
			UCNS.LD_LON_X_DSB AS UCNS_LD_LON_X_DSB
		FROM
			LNS
			JOIN LNS SCNS
				ON LNS.BF_SSN = SCNS.BF_SSN
				AND SCNS.IC_LON_PGM = 'DLSCNS'
			JOIN LNS UCNS
				ON LNS.BF_SSN = UCNS.BF_SSN
				AND UCNS.IC_LON_PGM = 'DLUCNS'
		WHERE
			SCNS.LD_LON_X_DSB = UCNS.LD_LON_X_DSB
			AND SCNS.LR_ITR <> UCNS.LR_ITR
		ORDER BY
			LNS.BF_SSN
	;

	CREATE TABLE SPL AS
		SELECT DISTINCT
			LNS.BF_SSN,
			SSPL.LN_SEQ AS SSPL_LN_SEQ,
 			SSPL.AWARD_ID AS SSPL_AWARD_ID,
 			SSPL.LR_ITR AS SSPL_LR_ITR,
			SSPL.LD_LON_X_DSB AS SSPL_LD_LON_X_DSB,
			USPL.LN_SEQ AS USPL_LN_SEQ,
 			USPL.AWARD_ID AS USPL_AWARD_ID,
 			USPL.LR_ITR AS USPL_LR_ITR,
			USPL.LD_LON_X_DSB AS USPL_LD_LON_X_DSB
		FROM
			LNS
			JOIN LNS SSPL
				ON LNS.BF_SSN = SSPL.BF_SSN
				AND SSPL.IC_LON_PGM = 'DLSSPL'
			JOIN LNS USPL
				ON LNS.BF_SSN = USPL.BF_SSN
				AND USPL.IC_LON_PGM = 'DLUSPL'
		WHERE
			SSPL.LD_LON_X_DSB = USPL.LD_LON_X_DSB
			AND USPL.LR_ITR <> SSPL.LR_ITR
		ORDER BY
			LNS.BF_SSN
	;
QUIT;
ENDRSUBMIT;

DATA CNS; SET LEGEND.CNS; RUN;
DATA SPL; SET LEGEND.SPL; RUN;

PROC EXPORT
		DATA=CNS
		OUTFILE='T:\SAS\Query Needed For FSA - Misaligned Rates.XLSX'
		REPLACE;
RUN;

PROC EXPORT
		DATA=SPL
		OUTFILE='T:\SAS\Query Needed For FSA - Misaligned Rates.XLSX'
		REPLACE;
RUN;
