DECLARE @BEGIN AS DATE = 'XXXX-XX-XX'
DECLARE @END AS DATE = 'XXXX-XX-XX'


--closed school
SELECT  DISTINCT
	SUM(CASE WHEN CSFSA.BF_SSN IS NOT NULL AND ADCSH.BF_SSN IS NULL AND CSDNY.BF_SSN IS NULL THEN X ELSE X END) AS PENDING
	,SUM(CASE WHEN ADCSH.BF_SSN IS NOT NULL THEN X ELSE X END) AS APPROVED
	,SUM(CASE WHEN CSDNY.BF_SSN IS NOT NULL THEN X ELSE X END) AS DENIED

FROM
	(
		SELECT DISTINCT
			AYXX.BF_SSN
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
		WHERE
			AYXX.LD_ATY_REQ_RCV BETWEEN  @BEGIN AND @END
			AND AYXX.PF_REQ_ACT = 'DICSK'
	) DICSK
	LEFT JOIN
	(
		SELECT DISTINCT
			AYXX.BF_SSN
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
		WHERE
			AYXX.LD_ATY_REQ_RCV BETWEEN  @BEGIN AND @END
			AND AYXX.PF_REQ_ACT = 'CSFSA'
	) CSFSA
		ON DICSK.BF_SSN = CSFSA.BF_SSN
	LEFT JOIN
	(
		SELECT DISTINCT
			AYXX.BF_SSN
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
		WHERE
			AYXX.LD_ATY_REQ_RCV BETWEEN  @BEGIN AND @END
			AND AYXX.PF_REQ_ACT = 'ADCSH'
	) ADCSH
		ON DICSK.BF_SSN = ADCSH.BF_SSN
	LEFT JOIN
	(
		SELECT DISTINCT
			AYXX.BF_SSN
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
		WHERE
			AYXX.LD_ATY_REQ_RCV BETWEEN  @BEGIN AND @END
			AND AYXX.PF_REQ_ACT = 'CSDNY'
	) CSDNY
		ON DICSK.BF_SSN = CSDNY.BF_SSN

--false cert
SELECT  DISTINCT
	SUM(CASE WHEN PRFCR.BF_SSN IS NOT NULL AND ADFCR.BF_SSN IS NULL AND FCDNY.BF_SSN IS NULL THEN X ELSE X END) AS PENDING
	,SUM(CASE WHEN ADFCR.BF_SSN IS NOT NULL THEN X ELSE X END) AS APPROVED
	,SUM(CASE WHEN FCDNY.BF_SSN IS NOT NULL THEN X ELSE X END) AS DENIED

FROM
	(
		SELECT DISTINCT
			AYXX.BF_SSN
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
		WHERE
			AYXX.LD_ATY_REQ_RCV BETWEEN  @BEGIN AND @END
			AND AYXX.PF_REQ_ACT = 'DIFCR'
	) DIFCR
	LEFT JOIN
	(
		SELECT DISTINCT
			AYXX.BF_SSN
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
		WHERE
			AYXX.LD_ATY_REQ_RCV BETWEEN  @BEGIN AND @END
			AND AYXX.PF_REQ_ACT = 'PRFCR'
	) PRFCR
		ON DIFCR.BF_SSN = PRFCR.BF_SSN
	LEFT JOIN
	(
		SELECT DISTINCT
			AYXX.BF_SSN
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
		WHERE
			AYXX.LD_ATY_REQ_RCV BETWEEN  @BEGIN AND @END
			AND AYXX.PF_REQ_ACT = 'ADFCR'
	) ADFCR
		ON DIFCR.BF_SSN = ADFCR.BF_SSN
	LEFT JOIN
	(
		SELECT DISTINCT
			AYXX.BF_SSN
		FROM
			CDW..AYXX_BR_LON_ATY AYXX
		WHERE
			AYXX.LD_ATY_REQ_RCV BETWEEN  @BEGIN AND @END
			AND AYXX.PF_REQ_ACT = 'FCDNY'
	) FCDNY
		ON DIFCR.BF_SSN = FCDNY.BF_SSN