SELECT DISTINCT
	LNXX.BF_SSN,
	LNXX.LN_SEQ
FROM
	CDW..LNXX_LON LNXX
	LEFT OUTER JOIN CDW..SDXX_STU_SPR SDXX
		ON LNXX.BF_SSN = SDXX.LF_STU_SSN
		AND LF_DOE_SCL_ENR_CUR LIKE 'XXXXXX%'
WHERE
	LNXX.LF_DOE_SCL_ORG LIKE 'XXXXXX%'
	OR SDXX.LF_STU_SSN IS NOT NULL
