LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
LIBNAME X 'T:\UPDATE Query XXXX.xlsx';

DATA LEGEND.ACCOUNTS; SET X.'Account #$'N; RUN;

RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;

PROC SQL;
	CREATE TABLE NHXXXX AS
		SELECT DISTINCT
			PDXX.DF_SPE_ACC_ID,
			LNXX.LN_SEQ,
			LNXX.LC_ACA_GDE_LEV,
			FSXX.LC_DL_STU_DEP_STA,
			FSXX.LI_DL_XED_USB_LMT,
			FSXX.LR_DL_DSB_REB_PER,
			FSXX.LF_DL_FIN_AWD_YR,
			FSXX.LD_DL_STU_ACA_BEG,
			FSXX.LD_DL_STU_ACA_END,
			FSXX.LI_DL_BR_ELG_HPA,
			FSXX.LF_DL_MPN,
			FSXX.LC_DL_STA_MPN,
			LNXX.LD_MPN_EXP,
			LNXX.LF_FED_CLC_RSK
		FROM
			ACCOUNTS ACNT
			JOIN PKUB.PDXX_PRS_NME PDXX
				ON ACNT.Acct__ = PDXX.DF_SPE_ACC_ID
			JOIN PKUB.LNXX_LON LNXX
				ON PDXX.DF_PRS_ID = LNXX.BF_SSN
				AND ACNT.Loan_Seq = LNXX.LN_SEQ
			JOIN PKUB.FSXX_DL_LON FSXX
				ON LNXX.BF_SSN = FSXX.BF_SSN
				AND LNXX.LN_SEQ = FSXX.LN_SEQ
	;
QUIT;

ENDRSUBMIT;

DATA NHXXXX; SET LEGEND.NHXXXX; RUN;

PROC EXPORT
		DATA=NHXXXX
		OUTFILE='T:\SAS\NH XXXX OUTPUT.XLSX'
		REPLACE;
RUN;
