--Unique LTXX.RM_DSC_LTR_PRC
--Where PrintedAt is on or after XX/XX/XXXX

SELECT DISTINCT
	LTXX.RM_DSC_LTR_PRC
FROM
	CDW..LTXX_LTR_REQ_PRC LTXX
WHERE
	CONVERT(DATE,LTXX.PrintedAt) >= 'XXXX-XX-XX'
