USE CDW
GO

SELECT
	PDXX.DF_SPE_ACC_ID
	,LNXX.LN_SEQ
	,LNXX.LF_FED_CLC_RSK
FROM
	LNXX_LON LNXX
	INNER JOIN PDXX_PRS_NME PDXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
WHERE
	(PDXX.DF_SPE_ACC_ID = 'XXXXXXXXXX' AND LNXX.LN_SEQ = XXXX)
	OR (PDXX.DF_SPE_ACC_ID = 'XXXXXXXXXX' AND LNXX.LN_SEQ = XXXX)  
	OR (PDXX.DF_SPE_ACC_ID = 'XXXXXXXXXX' AND LNXX.LN_SEQ = XXXX)
	OR (PDXX.DF_SPE_ACC_ID = 'XXXXXXXXXX' AND LNXX.LN_SEQ = XXXX)
	OR (PDXX.DF_SPE_ACC_ID = 'XXXXXXXXXX' AND LNXX.LN_SEQ = XXXX)
	OR (PDXX.DF_SPE_ACC_ID = 'XXXXXXXXXX' AND LNXX.LN_SEQ = XXXX)
	OR (PDXX.DF_SPE_ACC_ID = 'XXXXXXXXXX' AND LNXX.LN_SEQ = XXXX)
ORDER BY
	LNXX.BF_SSN