/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/UNWSXX.NWSXXRZ";
FILENAME REPORTX "&RPTLIB/UNWSXX.NWSXXRX";

LIBNAME  LEGEND  REMOTE  SERVER=LEGEND SLIBREF=work  ;
RSUBMIT LEGEND;
/*%let DB = DNFPRQUT;  *This is test;*/
%let DB = DNFPUTDL;  *This is live;

LIBNAME PKUB DBX DATABASE=&DB OWNER=PKUB;

%MACRO SQLCHECK ;
  %IF  &SQLXRC NE X  %THEN  %DO  ;
    DATA _NULL_  ;
            FILE REPORTZ NOTITLES  ;
            PUT @XX " ********************************************************************* "
              / @XX " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
              / @XX " ****  THE SAS SHOULD BE REVIEWED.                                **** "       
              / @XX " ********************************************************************* "
              / @XX " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
              / @XX " ****  &SQLXMSG   **** "
              / @XX " ********************************************************************* "
            ;
         RUN  ;
  %END  ;
%MEND  ;

%MACRO TBL_PUL(DSET,TABLE);
PROC SQL ;
CONNECT TO DBX (DATABASE=&DB);
CREATE TABLE &DSET AS
SELECT *
FROM CONNECTION TO DBX (
	SELECT DISTINCT
		A.*
	FROM
		PKUB.&TABLE A
	WHERE 
		A.IC_LON_PGM IN ('DLSTFD','DLUNST','DLPLUS','DLPLGB','SLS','DLSCNS','DLUCNS','CNSLDN')

	FOR READ ONLY WITH UR
				)
	;

DISCONNECT FROM DBX;
%MEND TBL_PUL;
%TBL_PUL(LPXX,LPXX_CAP_OPT_RUL);
%TBL_PUL(LPXX,LPXX_DFR_PAR);
%TBL_PUL(LPXX,LPXX_RDI);
%TBL_PUL(LPXX,LPXX_UPD_SQR_ORD);
%TBL_PUL(LPXX,LPXX_FOR_PAR);
%TBL_PUL(LPXX,LPXX_ITR_AND_TYP);
%TBL_PUL(LPXX,LPXX_PAY_APL_PAR);
%TBL_PUL(LPXX,LPXX_OWN_DSB_PAR);
%TBL_PUL(LPXX,LPXX_RPY_PAR);
%TBL_PUL(LPXX,LPXX_WUP_RFD_PAR);
%TBL_PUL(LPXX,LPXX_GTR_DSB_PAR);
%TBL_PUL(LPXX,LPXX_DD_ACT_STA);
%TBL_PUL(LPXX,LPXX_DD_ACT_WDO);
%TBL_PUL(LPXX,LPXX_DD_ACT_STE);
%TBL_PUL(LPXX,LPXX_STP_PUR);
%TBL_PUL(LPXX,LPXX_DD_CYC_PAR);
%TBL_PUL(LPXX,LPXX_DD_SKP_PAR);
%TBL_PUL(LPXX,LPXX_GTR_OWN_FEE);
QUIT;
ENDRSUBMIT;

%MACRO PUL_DWN(DSET);
DATA &DSET; SET LEGEND.&DSET; RUN;
%MEND PUL_DWN;
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);
%PUL_DWN(LPXX);

%MACRO EXP_EXL(DSET);
PROC EXPORT DATA=&DSET
            OUTFILE= "T:\SAS\LP Table Dumps Xnd Set.xlsx" 
            DBMS=EXCEL REPLACE;
     SHEET="&DSET"; 
RUN;
%MEND EXP_EXL;
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
%EXP_EXL(LPXX);
