PROC IMPORT
		OUT=GREATLAKES
		DATAFILE='T:\NH XXXX - XXJANXXX.XLSX'
		DBMS=EXCEL
		REPLACE;
RUN;

LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;

DATA LEGEND.GREATLAKES; SET GREATLAKES; RUN;

RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;

PROC SQL;
	CREATE TABLE CONAI AS
		SELECT DISTINCT
			FSXX.BF_SSN,
			FSXX.LN_SEQ,
			FSXX.LF_FED_AWD||PUT(LN_FED_AWD_SEQ,ZX.) AS AWARD_ID
		FROM
			GREATLAKES GL
			JOIN PKUB.FSXX_DL_LON FSXX
				ON GL.BF_SSN = FSXX.BF_SSN
	;
QUIT;

ENDRSUBMIT;

DATA CONAI; SET LEGEND.CONAI; RUN;

PROC EXPORT
		DATA=CONAI
		OUTFILE='T:\GREAT LAKES AWARD IDs.xlsx'
		REPLACE;
	SHEET=AWARD_ID;
RUN;
