USE CDW
GO
--XXXXXXX
--XXXXXX
DECLARE @TRANSFER_DATE DATE = 'XX/XX/XXXX'

DROP TABLE IF EXISTS #DATA

SELECT DISTINCT
	FSXX.BF_SSN AS SSN,
	FSXX.LF_FED_AWD + RIGHT('XXX' + CAST(FSXX.LN_FED_AWD_SEQ AS VARCHAR(XX)),X) AS AWARD_ID,
	RTRIM(PDXX.DM_PRS_LST) AS LAST_NAME,
	CONVERT(VARCHAR,PDXX.DD_BRT, XXX) AS DATE_OF_BIRTH,
	ISNULL(EMAIL.EmailAddress, 'N/A') AS EMAIL_ADDRESS,
	ABS(LNXX.LA_FAT_CUR_PRI) AS PRINCIPAL_TRANSFERED,
	ABS(LNXX.LA_FAT_NSI) AS INTEREST_TRANSFERED,
	LNXX.LA_CUR_PRI AS CURRENT_PRINCIPAL,
	DWXX.WA_TOT_BRI_OTS AS CURRENT_INTEREST,
	ISNULL(LNXX.LA_TOT_PRI_PD_PCV,X.XX) + ISNULL(TOTAL_PAID.LA_FAT_CUR_PRI,X.XX) AS PBO_PAID,
	ISNULL(TOTAL_PAID.LA_FAT_NSI,X.XX) AS INTEREST_PAID,
	ISNULL(LNXX.LA_ORG_CAP_INT,X.XX) + ISNULL(CAP.LA_FAT_CUR_PRI,X.XX) AS TOTAL_CAPITIALIZED_INTEREST,
	LNXX.LD_LON_X_DSB AS EARLIEST_DISBURSEMENT_DATE,
	DSB_AMT.DISB_AMT_C AS DISBURSEMENT_AMOUNT,
	LNXX.LC_FED_PGM_YR
into #data
FROM
	CDW..FSXX_DL_LON FSXX
	INNER JOIN 
	(
		SELECT DISTINCT
			LNXX.BF_SSN,
			FSXX.LF_FED_AWD,
			FSXX.LN_FED_AWD_SEQ,
			SUM(COALESCE(LA_FAT_CUR_PRI,X.XX)) AS LA_FAT_CUR_PRI,
			SUM(COALESCE(LA_FAT_NSI,X.XX)) AS LA_FAT_NSI
		FROM
			CDW..LNXX_FIN_ATY LNXX
			INNER JOIN CDW..FSXX_DL_LON FSXX
				ON FSXX.BF_SSN = LNXX.BF_SSN
				AND FSXX.LN_SEQ = LNXX.LN_SEQ
		WHERE
			LNXX.LC_STA_LONXX = 'A'
			AND COALESCE(rtrim(LNXX.LC_FAT_REV_REA),'') = ''
			AND LNXX.PC_FAT_TYP = 'XX'
			AND LNXX.PC_FAT_SUB_TYP = 'XX'
			AND LNXX.LD_FAT_EFF = @TRANSFER_DATE
		GROUP BY
			LNXX.BF_SSN,
			FSXX.LF_FED_AWD,
			FSXX.LN_FED_AWD_SEQ
	) LNXX
		ON LNXX.BF_SSN = FSXX.BF_SSN
		AND LNXX.LF_FED_AWD = FSXX.LF_FED_AWD
		AND LNXX.LN_FED_AWD_SEQ = FSXX.LN_FED_AWD_SEQ
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = FSXX.BF_SSN
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = FSXX.BF_SSN
		AND LNXX.LN_SEQ = FSXX.LN_SEQ
	INNER JOIN CDW..DWXX_DW_CLC_CLU DWXX
		ON DWXX.BF_SSN = FSXX.BF_SSN
		AND DWXX.LN_SEQ = FSXX.LN_SEQ
	LEFT JOIN 
	(
		SELECT DISTINCT
			LNXX.BF_SSN,
			FSXX.LF_FED_AWD,
			FSXX.LN_FED_AWD_SEQ,
			SUM(LNXX.LA_TOT_PRI_PD_PCV) AS LA_TOT_PRI_PD_PCV,
			SUM(LNXX.LA_ORG_CAP_INT)  AS LA_ORG_CAP_INT
		FROM
			CDW..LNXX_RPD_PIO_CVN LNXX
			INNER JOIN CDW..FSXX_DL_LON FSXX
				ON FSXX.BF_SSN = LNXX.BF_SSN
				AND FSXX.LN_SEQ = LNXX.LN_SEQ
			INNER JOIN 
			(
				SELECT DISTINCT
					LNXX.BF_SSN,
					LNXX.LN_SEQ
				FROM
					CDW..LNXX_FIN_ATY LNXX
				WHERE
					LNXX.LC_STA_LONXX = 'A'
					AND COALESCE(rtrim(LNXX.LC_FAT_REV_REA),'') = ''
					AND LNXX.PC_FAT_TYP = 'XX'
					AND LNXX.PC_FAT_SUB_TYP = 'XX'
					AND LNXX.LD_FAT_EFF = @TRANSFER_DATE
			) TRANS
				ON TRANS.BF_SSN = LNXX.BF_SSN
				AND TRANS.LN_SEQ = LNXX.LN_SEQ
		GROUP BY
			LNXX.BF_SSN,
			FSXX.LF_FED_AWD,
			FSXX.LN_FED_AWD_SEQ
	) LNXX
		ON LNXX.BF_SSN = FSXX.BF_SSN
		AND LNXX.LF_FED_AWD = FSXX.LF_FED_AWD
		AND LNXX.LN_FED_AWD_SEQ = FSXX.LN_FED_AWD_SEQ
	LEFT JOIN 
	(
		SELECT
			LNXX.BF_SSN,
			FSXX.LF_FED_AWD,
			FSXX.LN_FED_AWD_SEQ,
			SUM(ABS(COALESCE(LA_FAT_CUR_PRI,X.XX)) + abs(isnull(LNXX.LA_FAT_ILG_PRI,X.XX))) AS LA_FAT_CUR_PRI,
			ABS(SUM(COALESCE(LA_FAT_NSI,X.XX))) AS LA_FAT_NSI
		FROM
			CDW..LNXX_FIN_ATY LNXX
			INNER JOIN CDW..FSXX_DL_LON FSXX
				ON FSXX.BF_SSN = LNXX.BF_SSN
				AND FSXX.LN_SEQ = LNXX.LN_SEQ
			INNER JOIN 
			(
				SELECT DISTINCT
					LNXX.BF_SSN,
					LNXX.LN_SEQ
				FROM
					CDW..LNXX_FIN_ATY LNXX
				WHERE
					LNXX.LC_STA_LONXX = 'A'
					AND COALESCE(rtrim(LNXX.LC_FAT_REV_REA),'') = ''
					AND LNXX.PC_FAT_TYP = 'XX'
					AND LNXX.PC_FAT_SUB_TYP = 'XX'
					AND LNXX.LD_FAT_EFF = @TRANSFER_DATE
			) TRANS
				ON TRANS.BF_SSN = LNXX.BF_SSN
				AND TRANS.LN_SEQ = LNXX.LN_SEQ
		WHERE
			LNXX.LC_STA_LONXX = 'A'
			AND (LC_FAT_REV_REA = ' ' OR LC_FAT_REV_REA = '' OR LC_FAT_REV_REA IS NULL)
			AND LNXX.PC_FAT_TYP = 'XX'
			AND LNXX.PC_FAT_SUB_TYP in ('XX', 'XX','XX', 'XX', 'XX','XX','XX','XX','XX','XX','XX','XX','XX','XX', 'XX','XX', 'XX','XX','XX','XX','XX', 'XX','XX','XX', 'XX','XX','XX','XX','XX','XX')  
		GROUP BY
			LNXX.BF_SSN,
			FSXX.LF_FED_AWD,
			fsXX.LN_FED_AWD_SEQ
	) TOTAL_PAID
		ON TOTAL_PAID.BF_SSN = FSXX.BF_SSN
		AND TOTAL_PAID.LF_FED_AWD = FSXX.LF_FED_AWD
		AND TOTAL_PAID.LN_FED_AWD_SEQ = FSXX.LN_FED_AWD_SEQ
	LEFT JOIN 
	( 
		SELECT
			LNXX.BF_SSN,
			FSXX.LF_FED_AWD,
			FSXX.LN_FED_AWD_SEQ,
			SUM(LNXX.LA_FAT_CUR_PRI) AS LA_FAT_CUR_PRI
		FROM
			LNXX_FIN_ATY LNXX
			INNER JOIN CDW..FSXX_DL_LON FSXX
				ON FSXX.BF_SSN = LNXX.BF_SSN
				AND FSXX.LN_SEQ = LNXX.LN_SEQ
			INNER JOIN 
			(
				SELECT DISTINCT
					LNXX.BF_SSN,
					LNXX.LN_SEQ
				FROM
					CDW..LNXX_FIN_ATY LNXX
				WHERE
					LNXX.LC_STA_LONXX = 'A'
					AND COALESCE(rtrim(LNXX.LC_FAT_REV_REA),'') = ''
					AND LNXX.PC_FAT_TYP = 'XX'
					AND LNXX.PC_FAT_SUB_TYP = 'XX'
					AND LNXX.LD_FAT_EFF = @TRANSFER_DATE

			) TRANS
				ON TRANS.BF_SSN = LNXX.BF_SSN
				AND TRANS.LN_SEQ = LNXX.LN_SEQ
		WHERE
			LNXX.PC_FAT_TYP = 'XX' 
			AND LNXX.PC_FAT_SUB_TYP = 'XX'
			AND LNXX.LC_STA_LONXX = 'A'
			AND COALESCE(LNXX.LC_FAT_REV_REA,'') = '' 
		GROUP BY
			LNXX.BF_SSN,
			FSXX.LF_FED_AWD,
			fsXX.LN_FED_AWD_SEQ
	) CAP 
		ON CAP.BF_SSN = LNXX.BF_SSN
		AND CAP.LF_FED_AWD = FSXX.LF_FED_AWD
		AND CAP.LN_FED_AWD_SEQ = FSXX.LN_FED_AWD_SEQ
	LEFT JOIN
	(
		SELECT DISTINCT
			EmailOrdering.DF_PRS_ID,
			EmailOrdering.EmailAddress
		FROM
			(
				SELECT
					EmailPrioritizing.DF_PRS_ID,
					EmailPrioritizing.EmailAddress,
					ROW_NUMBER() OVER (PARTITION BY EmailPrioritizing.DF_PRS_ID ORDER BY EmailPrioritizing.PriorityNumber) AS EmailPriority --number in order of Email.PriorityNumber
				FROM
					(
						SELECT DISTINCT
							PDXX.DF_PRS_ID,
							PDXX.DX_ADR_EML AS EmailAddress,
							CASE 
								WHEN PDXX.DC_ADR_EML = 'H' THEN X 
								WHEN PDXX.DC_ADR_EML = 'A' THEN X 
								WHEN PDXX.DC_ADR_EML = 'W' THEN X 
							END AS PriorityNumber
						FROM
							PDXX_PRS_NME PDXX 
							LEFT JOIN PDXX_PRS_ADR_EML PDXX
								ON PDXX.DF_PRS_ID = PDXX.DF_PRS_ID
								AND PDXX.DI_VLD_ADR_EML = 'Y' 
								AND PDXX.DC_STA_PDXX = 'A' 
						WHERE
							PDXX.DF_PRS_ID LIKE '[X-X]%' 
					) EmailPrioritizing
				WHERE
					EmailPrioritizing.EmailAddress IS NOT NULL 
			) EmailOrdering
		WHERE
			EmailOrdering.EmailPriority = X 
	) EMAIL
		ON EMAIL.DF_PRS_ID = FSXX.BF_SSN
	LEFT JOIN 
	(
		SELECT 
		TABX.BF_SSN, 
		FSXX.LF_FED_AWD ,
		FSXX.LN_FED_AWD_SEQ, 
		SUM(CASE WHEN LNXXAMT IS NOT NULL THEN LNXXAMT ELSE LNXXAMT END) AS DISB_AMT_C
	FROM
	( --aes's logic
		SELECT 
			LNXX.BF_SSN, 
			LNXX.LN_SEQ, 
			LN_BR_DSB_SEQ, 
			SUM(LA_DSB - COALESCE(LA_DSB_CAN,X)) AS LNXXAMT, 
			(
				SELECT 
					SUM(LA_PCV_ADJ_CUR_PRI) 
				FROM 
					CDW..LNXX_PCV_FIN_SCP LNXX 
				WHERE 
					LNXX.BF_SSN = LNXX.BF_SSN 
					AND LNXX.LN_SEQ = LNXX.LN_SEQ 
					AND LNXX.LN_BR_DSB_SEQ = LNXX.LN_BR_DSB_SEQ 
					AND LNXX.LC_STA_LONXX = 'A'
					AND LNXX.LN_SEQ_PCV_ADJ_REQ = 
					(
						SELECT 
							max(LN_SEQ_PCV_ADJ_REQ) 
						FROM 
							CDW..LNXX_PCV_FIN_SCP MXXX 				
							INNER JOIN 
							(
								SELECT DISTINCT
									LNXX.BF_SSN,
									LNXX.LN_SEQ
								FROM
									CDW..LNXX_FIN_ATY LNXX
								WHERE
									LNXX.LC_STA_LONXX = 'A'
									AND COALESCE(rtrim(LNXX.LC_FAT_REV_REA),'') = ''
									AND LNXX.PC_FAT_TYP = 'XX'
									AND LNXX.PC_FAT_SUB_TYP = 'XX'
									AND LNXX.LD_FAT_EFF = @TRANSFER_DATE

							) TRANS
								ON TRANS.BF_SSN = mxXX.BF_SSN
								AND TRANS.LN_SEQ = mxXX.LN_SEQ
						WHERE	
							LNXX.BF_SSN = MXXX.BF_SSN 
							AND LNXX.LN_SEQ = MXXX.LN_SEQ 
							AND LNXX.LN_BR_DSB_SEQ = MXXX.LN_BR_DSB_SEQ 
							AND MXXX.LC_REV_REA = ' '
							AND EXISTS(SELECT X FROM CDW..LNXX_PCV_FIN_SCP LNXXA WHERE MXXX.BF_SSN = LNXXA.BF_SSN AND MXXX.LN_SEQ = LNXXA.LN_SEQ AND MXXX.LN_SEQ_PCV_ADJ_REQ = LNXXA.LN_SEQ_PCV_ADJ_REQ AND LNXXA.LC_STA_LONXX = 'A' AND LNXXA.LC_REV_REA = ' ' AND LNXXA.PC_FAT_TYP = 'XX' AND LNXXA.PC_FAT_SUB_TYP = 'XX')
				
					)
			) AS LNXXAMT
	FROM 
		CDW..LNXX_DSB LNXX
		INNER JOIN 
		(
			SELECT DISTINCT
				LNXX.BF_SSN,
				LNXX.LN_SEQ
			FROM
				CDW..LNXX_FIN_ATY LNXX
			WHERE
				LNXX.LC_STA_LONXX = 'A'
				AND COALESCE(rtrim(LNXX.LC_FAT_REV_REA),'') = ''
				AND LNXX.PC_FAT_TYP = 'XX'
				AND LNXX.PC_FAT_SUB_TYP = 'XX'
				AND LNXX.LD_FAT_EFF = @TRANSFER_DATE
		) TRANS
			ON TRANS.BF_SSN = LNXX.BF_SSN
			AND TRANS.LN_SEQ = LNXX.LN_SEQ

	WHERE 
		LNXX.LC_DSB_TYP IN ('X') 
		AND LNXX.LC_STA_LONXX IN ('X','X')
	GROUP BY 
		LNXX.BF_SSN, 
		LNXX.LN_SEQ, 
		LN_BR_DSB_SEQ
) 
TABX
INNER JOIN CDW..FSXX_DL_LON FSXX 
	ON TABX.BF_SSN = FSXX.BF_SSN 
	AND TABX.LN_SEQ = FSXX.LN_SEQ
GROUP BY 
	TABX.BF_SSN, 
	FSXX.LF_FED_AWD ,
	FSXX.LN_FED_AWD_SEQ
	) DSB_AMT
		ON DSB_AMT.BF_SSN = FSXX.BF_SSN
		AND DSB_AMT.LF_FED_AWD = FSXX.LF_FED_AWD
		AND DSB_AMT.LN_FED_AWD_SEQ = FSXX.LN_FED_AWD_SEQ

SELECT DISTINCT 
	Dense_rank() OVER( ORDER BY SSN) AS RN,
	D.*
FROM 
	#DATA D
WHERE
	D.LC_FED_PGM_YR = 'LNC'
order by rn
	

SELECT DISTINCT 
	Dense_rank() OVER( ORDER BY SSN) AS RN,
	D.*
FROM 
	#DATA D
WHERE
	D.LC_FED_PGM_YR = 'DLO'
order by rn


