USE CDW
GO

SELECT 
	PDXX.DF_SPE_ACC_ID,
	WQXX.WF_QUE,
	WQXX.WF_SUB_QUE
FROM
	CDW..CS_TransferX TX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = TX.BF_SSN
	INNER JOIN CDW..WQXX_TSK_QUE WQXX
		ON WQXX.BF_SSN = TX.BF_SSN
ORDER BY
	WQXX.WF_QUE,
	WQXX.WF_SUB_QUE

SELECT 
	WQXX.WF_QUE,
	WQXX.WF_SUB_QUE,
	COUNT(*) AS TASK_COUNT
FROM
	CDW..CS_TransferX TX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = TX.BF_SSN
	INNER JOIN CDW..WQXX_TSK_QUE WQXX
		ON WQXX.BF_SSN = TX.BF_SSN
GROUP BY
	WQXX.WF_QUE,
	WQXX.WF_SUB_QUE
ORDER BY TASK_COUNT DESC