USE CDW
GO


SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
IF OBJECT_ID('tempdb..#BASE_POP') IS NOT NULL 
	DROP TABLE #BASE_POP

IF OBJECT_ID('tempdb..#FINAL_POP') IS NOT NULL 
	DROP TABLE #FINAL_POP

SELECT DISTINCT
	LNXX.BF_SSN,
	LNXX.LN_SEQ,
	LNXX.LD_BIL_CRT,
	LNXX.LN_SEQ_BIL_WI_DTE,
	LNXX.LN_BIL_OCC_SEQ,
	LNXX.LC_STA_LONXX,
	LNXX.LA_BIL_DU_PRT,
	SUM(CASE WHEN LC_STA_LONXX = 'A' THEN X ELSE X END) OVER (PARTITION BY LNXX.BF_SSN, LNXX.LN_SEQ) AS REC_POP
INTO #BASE_POP
FROM
	CLS..DueDateChange DDC
	INNER JOIN CDW..LNXX_LON_BIL_CRF LNXX
		ON LNXX.BF_SSN = DDC.Ssn
WHERE
	CAST(ProcessedAt AS DATE) > 'XX/XX/XXXX'
	AND Successful = X
	AND LD_BIL_DU_LON BETWEEN 'XX/XX/XXXX' AND 'XX/XX/XXXX'
ORDER BY 
	LNXX.BF_SSN

SELECT DISTINCT
	BF_SSN, 
	LC_STA_LONXX,
	SUM(ISNULL(LA_BIL_DU_PRT,X)) OVER (PARTITION BY BF_SSN, LC_STA_LONXX) AS BIL_AMT
INTO #FINAL_POP
FROM 
	#BASE_POP 
WHERE 
	REC_POP != X 
ORDER BY 
	BF_SSN

SELECT 
	PDXX.DF_SPE_ACC_ID,
	FP.BF_SSN,
	(FP.BIL_AMT - FPS.BIL_AMT) AS DIFF 
FROM 
	#FINAL_POP FP
	INNER JOIN #FINAL_POP FPS
		ON FP.BF_SSN = FPS.BF_SSN
		AND FPS.LC_STA_LONXX = 'I'
	LEFT JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = FP.BF_SSN
WHERE 
	FP.BIL_AMT > X
	AND FP.LC_STA_LONXX = 'A'
	AND FPS.LC_STA_LONXX = 'I'
	AND (FP.BIL_AMT - FPS.BIL_AMT) != X.XX
ORDER BY
	DIFF DESC
