USE CDW
GO

;WITH LOANSUM AS
(
	SELECT
		BF_SSN
		,SUM(COALESCE(LA_CUR_PRI,X.XX) + COALESCE(LA_NSI_OTS,X.XX)) OVER(PARTITION BY BF_SSN) AS SUM_OF_ALL_LOANS
		,LN_SEQ
		,LA_CUR_PRI
		,LA_NSI_OTS
		,LC_STA_LONXX
	FROM
		LNXX_LON
	WHERE
		LC_STA_LONXX = 'R'
		AND LA_CUR_PRI > X.XX
)
SELECT
	PDXX.DF_SPE_ACC_ID
	,LOANSUM.SUM_OF_ALL_LOANS
	,LOANSUM.LN_SEQ
	,LOANSUM.LA_CUR_PRI
	,LOANSUM.LA_NSI_OTS
	,LOANSUM.LC_STA_LONXX
FROM
	LOANSUM
	LEFT JOIN PDXX_PRS_NME PDXX
		ON LOANSUM.BF_SSN = PDXX.DF_PRS_ID
WHERE
	LOANSUM.SUM_OF_ALL_LOANS > XXXXXX.XX
