USE CDW
GO
--DROP TABLE IF EXISTS #BASE_POP


--SELECT DISTINCT
--	*
--INTO #BASE_POP
--FROM
--	CDW..LNXX_INT_RTE_HST LNXX
--WHERE
--	LNXX.LC_INT_RDC_PGM = 'M'
--	AND LR_ITR = X
--	AND 
--	(
--		LD_ITR_EFF_BEG BETWEEN 'XX/XX/XXXX' AND 'XX/XX/XXXX'
--		OR
--		LD_ITR_EFF_END BETWEEN 'XX/XX/XXXX' AND 'XX/XX/XXXX'
--	)



--SELECT DISTINCT
--	BP.BF_SSN,
--	BP.LN_SEQ,
--	MAX(CASE 
--		WHEN 
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END
--			OR
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END THEN  JAN.LA_CUR_PRI
--		ELSE  NULL
--	END) AS JAN_BALANCE,
--	MAX(CASE 
--		WHEN LPXX_JAN.PR_ITR_CLC_LPXX IS NULL AND LPXX_JAN.PR_ITR_MIN = LPXX_JAN.PR_ITR_MAX THEN LPXX_JAN.PR_ITR_MIN 
--		ELSE LPXX_JAN.PR_ITR_CLC_LPXX 
--	END) AS JAN_STAT_RATE,
--	MAX(CASE 
--		WHEN 
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END
--			OR
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END THEN  FEB.LA_CUR_PRI
--		ELSE  NULL
--	END) AS FEB_BALANCE,
--	MAX(CASE 
--		WHEN LPXX_FEB.PR_ITR_CLC_LPXX IS NULL AND LPXX_FEB.PR_ITR_MIN = LPXX_FEB.PR_ITR_MAX THEN LPXX_FEB.PR_ITR_MIN 
--		ELSE LPXX_FEB.PR_ITR_CLC_LPXX 
--	END) AS FEB_STAT_RATE,

--	MAX(CASE 
--		WHEN 
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END
--			OR
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END THEN  MAR.LA_CUR_PRI
--		ELSE  NULL
--	END) AS MAR_BALANCE,
--	MAX(CASE 
--		WHEN LPXX_MAR.PR_ITR_CLC_LPXX IS NULL AND LPXX_MAR.PR_ITR_MIN = LPXX_MAR.PR_ITR_MAX THEN LPXX_MAR.PR_ITR_MIN 
--		ELSE LPXX_MAR.PR_ITR_CLC_LPXX 
--	END) AS MAR_STAT_RATE,

--	MAX(CASE 
--		WHEN 
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END
--			OR
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END THEN  APR.LA_CUR_PRI
--		ELSE  NULL
--	END) AS APR_BALANCE,
--	MAX(CASE 
--		WHEN LPXX_APR.PR_ITR_CLC_LPXX IS NULL AND LPXX_APR.PR_ITR_MIN = LPXX_APR.PR_ITR_MAX THEN LPXX_APR.PR_ITR_MIN 
--		ELSE LPXX_APR.PR_ITR_CLC_LPXX 
--	END) AS APR_STAT_RATE,

--	MAX(CASE 
--		WHEN 
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END
--			OR
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END THEN  MAY.LA_CUR_PRI
--		ELSE  NULL
--	END) AS MAY_BALANCE,
--	MAX(CASE 
--		WHEN LPXX_MAY.PR_ITR_CLC_LPXX IS NULL AND LPXX_MAY.PR_ITR_MIN = LPXX_MAY.PR_ITR_MAX THEN LPXX_MAY.PR_ITR_MIN 
--		ELSE LPXX_MAY.PR_ITR_CLC_LPXX 
--	END) AS MAY_STAT_RATE,

--	MAX(CASE 
--		WHEN 
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END
--			OR
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END THEN  JUN.LA_CUR_PRI
--		ELSE  NULL
--	END) AS JUN_BALANCE,
--	MAX(CASE 
--		WHEN LPXX_JUN.PR_ITR_CLC_LPXX IS NULL AND LPXX_JUN.PR_ITR_MIN = LPXX_JUN.PR_ITR_MAX THEN LPXX_JUN.PR_ITR_MIN 
--		ELSE LPXX_JUN.PR_ITR_CLC_LPXX 
--	END) AS JUN_STAT_RATE,

--	MAX(CASE 
--		WHEN 
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END
--			OR
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END THEN  JUL.LA_CUR_PRI
--		ELSE  NULL
--	END) AS JUL_BALANCE,
--	MAX(CASE 
--		WHEN LPXX_JUL.PR_ITR_CLC_LPXX IS NULL AND LPXX_JUL.PR_ITR_MIN = LPXX_JUL.PR_ITR_MAX THEN LPXX_JUL.PR_ITR_MIN 
--		ELSE LPXX_JUL.PR_ITR_CLC_LPXX 
--	END) AS JUL_STAT_RATE,

--	MAX(CASE 
--		WHEN 
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END
--			OR
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END THEN  AUG.LA_CUR_PRI
--		ELSE  NULL
--	END) AS AUG_BALANCE,
--	MAX(CASE 
--		WHEN LPXX_AUG.PR_ITR_CLC_LPXX IS NULL AND LPXX_AUG.PR_ITR_MIN = LPXX_AUG.PR_ITR_MAX THEN LPXX_AUG.PR_ITR_MIN 
--		ELSE LPXX_AUG.PR_ITR_CLC_LPXX 
--	END) AS AUG_STAT_RATE,

--	MAX(CASE 
--		WHEN 
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END
--			OR
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END THEN  SEP.LA_CUR_PRI
--		ELSE  NULL
--	END) AS SEP_BALANCE,
--	MAX(CASE 
--		WHEN LPXX_SEP.PR_ITR_CLC_LPXX IS NULL AND LPXX_SEP.PR_ITR_MIN = LPXX_SEP.PR_ITR_MAX THEN LPXX_SEP.PR_ITR_MIN 
--		ELSE LPXX_SEP.PR_ITR_CLC_LPXX 
--	END) AS SEP_STAT_RATE,

--	MAX(CASE 
--		WHEN 
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END
--			OR
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END THEN  OCT.LA_CUR_PRI
--		ELSE  NULL
--	END) AS OCT_BALANCE,
--	MAX(CASE 
--		WHEN LPXX_OCT.PR_ITR_CLC_LPXX IS NULL AND LPXX_OCT.PR_ITR_MIN = LPXX_OCT.PR_ITR_MAX THEN LPXX_OCT.PR_ITR_MIN 
--		ELSE LPXX_OCT.PR_ITR_CLC_LPXX 
--	END) AS OCT_STAT_RATE,

--	MAX(CASE 
--		WHEN 
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END
--			OR
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END THEN  NOV.LA_CUR_PRI
--		ELSE  NULL
--	END) AS NOV_BALANCE,
--	MAX(CASE 
--		WHEN LPXX_NOV.PR_ITR_CLC_LPXX IS NULL AND LPXX_NOV.PR_ITR_MIN = LPXX_NOV.PR_ITR_MAX THEN LPXX_NOV.PR_ITR_MIN 
--		ELSE LPXX_NOV.PR_ITR_CLC_LPXX 
--	END) AS NOV_STAT_RATE,

--	MAX(CASE 
--		WHEN 
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END
--			OR
--			'XX/XX/XXXX' BETWEEN BP.LD_ITR_EFF_BEG AND BP.LD_ITR_EFF_END THEN  DECE.LA_CUR_PRI
--		ELSE  NULL
--	END) AS DEC_BALANCE,
--	MAX(CASE 
--		WHEN LPXX_DEC.PR_ITR_CLC_LPXX IS NULL AND LPXX_DEC.PR_ITR_MIN = LPXX_DEC.PR_ITR_MAX THEN LPXX_DEC.PR_ITR_MIN 
--		ELSE LPXX_DEC.PR_ITR_CLC_LPXX 
--	END) AS DEC_STAT_RATE
--INTO #FINAL
--FROM
--	#BASE_POP BP
--	LEFT JOIN AuditCDW..LNXX_LON_JanXXXX JAN
--		ON JAN.BF_SSN = BP.BF_SSN
--		AND JAN.LN_SEQ = BP.LN_SEQ
--	LEFT JOIN LPXX_ITR_AND_TYP LPXX_JAN
--		ON JAN.IC_LON_PGM = LPXX_JAN.IC_LON_PGM
--		AND JAN.LF_RGL_CAT_LPXX = LPXX_JAN.PF_RGL_CAT
--		AND JAN.IF_GTR = LPXX_JAN.IF_GTR
--		AND JAN.LF_LON_CUR_OWN = LPXX_JAN.IF_OWN
--		AND 
--		(
--			'XX/XX/XXXX' BETWEEN LPXX_JAN.PD_EFF_SR_LPDXX AND LPXX_JAN.PD_EFF_END_LPDXX
--			OR
--			'XX/XX/XXXX' BETWEEN LPXX_JAN.PD_EFF_SR_LPDXX AND LPXX_JAN.PD_EFF_END_LPDXX
--		)
--		AND LPXX_JAN.PC_STA_LPDXX = 'A'
--	LEFT JOIN AuditCDW..LNXX_LON_FebXXXX FEB
--		ON FEB.BF_SSN = BP.BF_SSN
--		AND FEB.LN_SEQ = BP.LN_SEQ
--	LEFT JOIN LPXX_ITR_AND_TYP LPXX_FEB
--		ON FEB.IC_LON_PGM = LPXX_FEB.IC_LON_PGM
--		AND FEB.LF_RGL_CAT_LPXX = LPXX_FEB.PF_RGL_CAT
--		AND FEB.IF_GTR = LPXX_FEB.IF_GTR
--		AND FEB.LF_LON_CUR_OWN = LPXX_FEB.IF_OWN
--		AND 
--		(
--			'XX/XX/XXXX' BETWEEN LPXX_FEB.PD_EFF_SR_LPDXX AND LPXX_FEB.PD_EFF_END_LPDXX
--			OR
--			'XX/XX/XXXX' BETWEEN LPXX_FEB.PD_EFF_SR_LPDXX AND LPXX_FEB.PD_EFF_END_LPDXX
--		)
--		AND LPXX_FEB.PC_STA_LPDXX = 'A'
--	LEFT JOIN AuditCDW..LNXX_LON_MARXXXX MAR
--		ON MAR.BF_SSN = BP.BF_SSN
--		AND MAR.LN_SEQ = BP.LN_SEQ
--	LEFT JOIN LPXX_ITR_AND_TYP LPXX_MAR
--		ON MAR.IC_LON_PGM = LPXX_MAR.IC_LON_PGM
--		AND MAR.LF_RGL_CAT_LPXX = LPXX_MAR.PF_RGL_CAT
--		AND MAR.IF_GTR = LPXX_MAR.IF_GTR
--		AND MAR.LF_LON_CUR_OWN = LPXX_MAR.IF_OWN
--		AND 
--		(
--			'XX/XX/XXXX' BETWEEN LPXX_MAR.PD_EFF_SR_LPDXX AND LPXX_MAR.PD_EFF_END_LPDXX
--			OR
--			'XX/XX/XXXX' BETWEEN LPXX_MAR.PD_EFF_SR_LPDXX AND LPXX_MAR.PD_EFF_END_LPDXX
--		)
--		AND LPXX_MAR.PC_STA_LPDXX = 'A'
--	LEFT JOIN AuditCDW..LNXX_LON_APRXXXX APR
--		ON APR.BF_SSN = BP.BF_SSN
--		AND APR.LN_SEQ = BP.LN_SEQ
--	LEFT JOIN LPXX_ITR_AND_TYP LPXX_APR
--		ON APR.IC_LON_PGM = LPXX_APR.IC_LON_PGM
--		AND APR.LF_RGL_CAT_LPXX = LPXX_APR.PF_RGL_CAT
--		AND APR.IF_GTR = LPXX_APR.IF_GTR
--		AND APR.LF_LON_CUR_OWN = LPXX_APR.IF_OWN
--		AND 
--		(
--			'XX/XX/XXXX' BETWEEN LPXX_APR.PD_EFF_SR_LPDXX AND LPXX_APR.PD_EFF_END_LPDXX
--			OR
--			'XX/XX/XXXX' BETWEEN LPXX_APR.PD_EFF_SR_LPDXX AND LPXX_APR.PD_EFF_END_LPDXX
--		)
--		AND LPXX_APR.PC_STA_LPDXX = 'A'
--	LEFT JOIN AuditCDW..LNXX_LON_MAYXXXX MAY
--		ON MAY.BF_SSN = BP.BF_SSN
--		AND MAY.LN_SEQ = BP.LN_SEQ
--	LEFT JOIN LPXX_ITR_AND_TYP LPXX_MAY
--		ON APR.IC_LON_PGM = LPXX_MAY.IC_LON_PGM
--		AND APR.LF_RGL_CAT_LPXX = LPXX_MAY.PF_RGL_CAT
--		AND APR.IF_GTR = LPXX_MAY.IF_GTR
--		AND APR.LF_LON_CUR_OWN = LPXX_MAY.IF_OWN
--		AND 
--		(
--			'XX/XX/XXXX' BETWEEN LPXX_MAY.PD_EFF_SR_LPDXX AND LPXX_MAY.PD_EFF_END_LPDXX
--			OR
--			'XX/XX/XXXX' BETWEEN LPXX_MAY.PD_EFF_SR_LPDXX AND LPXX_MAY.PD_EFF_END_LPDXX
--		)
--		AND LPXX_MAY.PC_STA_LPDXX = 'A'
--	LEFT JOIN AuditCDW..LNXX_LON_JUNXXXX JUN
--		ON JUN.BF_SSN = BP.BF_SSN
--		AND JUN.LN_SEQ = BP.LN_SEQ
--	LEFT JOIN LPXX_ITR_AND_TYP LPXX_JUN
--		ON JUN.IC_LON_PGM = LPXX_JUN.IC_LON_PGM
--		AND JUN.LF_RGL_CAT_LPXX = LPXX_JUN.PF_RGL_CAT
--		AND JUN.IF_GTR = LPXX_JUN.IF_GTR
--		AND JUN.LF_LON_CUR_OWN = LPXX_JUN.IF_OWN
--		AND 
--		(
--			'XX/XX/XXXX' BETWEEN LPXX_JUN.PD_EFF_SR_LPDXX AND LPXX_JUN.PD_EFF_END_LPDXX
--			OR
--			'XX/XX/XXXX' BETWEEN LPXX_JUN.PD_EFF_SR_LPDXX AND LPXX_JUN.PD_EFF_END_LPDXX
--		)
--		AND LPXX_JUN.PC_STA_LPDXX = 'A'
--	LEFT JOIN AuditCDW..LNXX_LON_JULXXXX JUL
--		ON JUL.BF_SSN = BP.BF_SSN
--		AND JUL.LN_SEQ = BP.LN_SEQ
--	LEFT JOIN LPXX_ITR_AND_TYP LPXX_JUL
--		ON JUL.IC_LON_PGM = LPXX_JUL.IC_LON_PGM
--		AND JUL.LF_RGL_CAT_LPXX = LPXX_JUL.PF_RGL_CAT
--		AND JUL.IF_GTR = LPXX_JUL.IF_GTR
--		AND JUL.LF_LON_CUR_OWN = LPXX_JUL.IF_OWN
--		AND 
--		(
--			'XX/XX/XXXX' BETWEEN LPXX_JUL.PD_EFF_SR_LPDXX AND LPXX_JUL.PD_EFF_END_LPDXX
--			OR
--			'XX/XX/XXXX' BETWEEN LPXX_JUL.PD_EFF_SR_LPDXX AND LPXX_JUL.PD_EFF_END_LPDXX
--		)
--		AND LPXX_JUL.PC_STA_LPDXX = 'A'
--	LEFT JOIN AuditCDW..LNXX_LON_AUGXXXX AUG
--		ON AUG.BF_SSN = BP.BF_SSN
--		AND AUG.LN_SEQ = BP.LN_SEQ
--	LEFT JOIN LPXX_ITR_AND_TYP LPXX_AUG
--		ON AUG.IC_LON_PGM = LPXX_AUG.IC_LON_PGM
--		AND AUG.LF_RGL_CAT_LPXX = LPXX_AUG.PF_RGL_CAT
--		AND AUG.IF_GTR = LPXX_AUG.IF_GTR
--		AND AUG.LF_LON_CUR_OWN = LPXX_AUG.IF_OWN
--		AND 
--		(
--			'XX/XX/XXXX' BETWEEN LPXX_AUG.PD_EFF_SR_LPDXX AND LPXX_AUG.PD_EFF_END_LPDXX
--			OR
--			'XX/XX/XXXX' BETWEEN LPXX_AUG.PD_EFF_SR_LPDXX AND LPXX_AUG.PD_EFF_END_LPDXX
--		)
--		AND LPXX_AUG.PC_STA_LPDXX = 'A'
--	LEFT JOIN AuditCDW..LNXX_LON_SEPXXXX SEP
--		ON SEP.BF_SSN = BP.BF_SSN
--		AND SEP.LN_SEQ = BP.LN_SEQ
--	LEFT JOIN LPXX_ITR_AND_TYP LPXX_SEP
--		ON SEP.IC_LON_PGM = LPXX_SEP.IC_LON_PGM
--		AND SEP.LF_RGL_CAT_LPXX = LPXX_SEP.PF_RGL_CAT
--		AND SEP.IF_GTR = LPXX_SEP.IF_GTR
--		AND SEP.LF_LON_CUR_OWN = LPXX_SEP.IF_OWN
--		AND 
--		(
--			'XX/XX/XXXX' BETWEEN LPXX_SEP.PD_EFF_SR_LPDXX AND LPXX_SEP.PD_EFF_END_LPDXX
--			OR
--			'XX/XX/XXXX' BETWEEN LPXX_SEP.PD_EFF_SR_LPDXX AND LPXX_SEP.PD_EFF_END_LPDXX
--		)
--		AND LPXX_SEP.PC_STA_LPDXX = 'A'
--	LEFT JOIN AuditCDW..LNXX_LON_OCTXXXX OCT
--		ON OCT.BF_SSN = BP.BF_SSN
--		AND OCT.LN_SEQ = BP.LN_SEQ
--	LEFT JOIN LPXX_ITR_AND_TYP LPXX_OCT
--		ON OCT.IC_LON_PGM = LPXX_OCT.IC_LON_PGM
--		AND OCT.LF_RGL_CAT_LPXX = LPXX_OCT.PF_RGL_CAT
--		AND OCT.IF_GTR = LPXX_OCT.IF_GTR
--		AND OCT.LF_LON_CUR_OWN = LPXX_OCT.IF_OWN
--		AND 
--		(
--			'XX/XX/XXXX' BETWEEN LPXX_OCT.PD_EFF_SR_LPDXX AND LPXX_OCT.PD_EFF_END_LPDXX
--			OR
--			'XX/XX/XXXX' BETWEEN LPXX_OCT.PD_EFF_SR_LPDXX AND LPXX_OCT.PD_EFF_END_LPDXX
--		)
--		AND LPXX_OCT.PC_STA_LPDXX = 'A'
--	LEFT JOIN AuditCDW..LNXX_LON_NOVXXXX NOV
--		ON NOV.BF_SSN = BP.BF_SSN
--		AND NOV.LN_SEQ = BP.LN_SEQ
--	LEFT JOIN LPXX_ITR_AND_TYP LPXX_NOV
--		ON NOV.IC_LON_PGM = LPXX_NOV.IC_LON_PGM
--		AND NOV.LF_RGL_CAT_LPXX = LPXX_NOV.PF_RGL_CAT
--		AND NOV.IF_GTR = LPXX_NOV.IF_GTR
--		AND NOV.LF_LON_CUR_OWN = LPXX_NOV.IF_OWN
--		AND 
--		(
--			'XX/XX/XXXX' BETWEEN LPXX_NOV.PD_EFF_SR_LPDXX AND LPXX_NOV.PD_EFF_END_LPDXX
--			OR
--			'XX/XX/XXXX' BETWEEN LPXX_NOV.PD_EFF_SR_LPDXX AND LPXX_NOV.PD_EFF_END_LPDXX
--		)
--		AND LPXX_NOV.PC_STA_LPDXX = 'A'
--	LEFT JOIN AuditCDW..LNXX_LON_DECXXXX DECE
--		ON DECE.BF_SSN = BP.BF_SSN
--		AND DECE.LN_SEQ = BP.LN_SEQ
--	LEFT JOIN LPXX_ITR_AND_TYP LPXX_DEC
--		ON DECE.IC_LON_PGM = LPXX_DEC.IC_LON_PGM
--		AND DECE.LF_RGL_CAT_LPXX = LPXX_DEC.PF_RGL_CAT
--		AND DECE.IF_GTR = LPXX_DEC.IF_GTR
--		AND DECE.LF_LON_CUR_OWN = LPXX_DEC.IF_OWN
--		AND 
--		(
--			'XX/XX/XXXX' BETWEEN LPXX_DEC.PD_EFF_SR_LPDXX AND LPXX_DEC.PD_EFF_END_LPDXX
--			OR
--			'XX/XX/XXXX' BETWEEN LPXX_DEC.PD_EFF_SR_LPDXX AND LPXX_DEC.PD_EFF_END_LPDXX
--		)
--		AND LPXX_DEC.PC_STA_LPDXX = 'A'
--GROUP BY
--	BP.BF_SSN,
--	BP.LN_SEQ	

SELECT
	F.BF_SSN,
	F.LN_SEQ,
	F.JAN_BALANCE,
	F.JAN_STAT_RATE,
	(JAN_STAT_RATE / XX / XXX) * F.JAN_BALANCE AS JAN_MONTHLY_INTEREST,
	F.FEB_BALANCE,
	F.FEB_STAT_RATE,
	(FEB_STAT_RATE / XX / XXX) * F.FEB_BALANCE AS FEB_MONTHLY_INTEREST,
	F.FEB_BALANCE,
	F.FEB_STAT_RATE,
	(FEB_STAT_RATE / XX / XXX) * F.FEB_BALANCE AS FEB_MONTHLY_INTEREST,

	F.MAR_BALANCE,
	F.MAR_STAT_RATE,
	(MAR_STAT_RATE / XX / XXX) * F.MAR_BALANCE AS MAR_MONTHLY_INTEREST,

	F.APR_BALANCE,
	F.APR_STAT_RATE,
	(APR_STAT_RATE / XX / XXX) * F.APR_BALANCE AS APR_MONTHLY_INTEREST,

	F.MAY_BALANCE,
	F.MAY_STAT_RATE,
	(MAY_STAT_RATE / XX / XXX) * F.MAY_BALANCE AS MAY_MONTHLY_INTEREST,

	F.JUN_BALANCE,
	F.JUN_STAT_RATE,
	(JUN_STAT_RATE / XX / XXX) * F.JUN_BALANCE AS JUN_MONTHLY_INTEREST,

	F.JUL_BALANCE,
	F.JUL_STAT_RATE,
	(JUL_STAT_RATE / XX / XXX) * F.JUL_BALANCE AS JUL_MONTHLY_INTEREST,

	F.AUG_BALANCE,
	F.AUG_STAT_RATE,
	(AUG_STAT_RATE / XX / XXX) * F.AUG_BALANCE AS AUG_MONTHLY_INTEREST,

	F.SEP_BALANCE,
	F.SEP_STAT_RATE,
	(SEP_STAT_RATE / XX / XXX) * F.SEP_BALANCE AS SEP_MONTHLY_INTEREST,

	F.OCT_BALANCE,
	F.OCT_STAT_RATE,
	(OCT_STAT_RATE / XX / XXX) * F.OCT_BALANCE AS OCT_MONTHLY_INTEREST,

	F.NOV_BALANCE,
	F.NOV_STAT_RATE,
	(NOV_STAT_RATE / XX / XXX) * F.NOV_BALANCE AS NOV_MONTHLY_INTEREST,

	F.DEC_BALANCE,
	F.DEC_STAT_RATE,
	(DEC_STAT_RATE / XX / XXX) * F.DEC_BALANCE AS DEC_MONTHLY_INTEREST

FROM
	#FINAL F
ORDER BY
	F.BF_SSN,
	F.LN_SEQ