--AYXX.PF_REQ_ACT = TLDNY
--Please provide the account number and comment text from AYXX.LX_ATY.


SELECT DISTINCT
	AYXX.BF_SSN,
	AYXX.LN_ATY_SEQ,
	AYXX.LN_ATY_CMT_SEQ,
	AYXX.LN_ATY_TXT_SEQ,
	AYXX.LX_ATY,
	CONVERT(DATE, AYXX.LD_ATY_REQ_RCV) AS LD_ATY_REQ_RCV
FROM
	CDW..AYXX_BR_LON_ATY AYXX
	INNER JOIN CDW..AYXX_ATY_TXT AYXX
		ON AYXX.BF_SSN = AYXX.BF_SSN
		AND AYXX.LN_ATY_SEQ =  AYXX.LN_ATY_SEQ
WHERE 
	AYXX.PF_REQ_ACT = 'TLDNY'
ORDER BY
	AYXX.BF_SSN,
	AYXX.LN_ATY_SEQ,
	AYXX.LN_ATY_CMT_SEQ,
	AYXX.LN_ATY_TXT_SEQ
