SELECT
	PDXX.DF_SPE_ACC_ID,
	PDXX.*
FROM
	CDW..PDXX_PRS_NME PDXX
	LEFT JOIN CDW..PDXX_PRS_DTH PDXX
		ON PDXX.DF_PRS_ID = PDXX.DF_PRS_ID
WHERE DF_SPE_ACC_ID IN 
(

'XXXXXXXXXX',
'XXXXXXXXXX',
'XXXXXXXXXX',
'XXXXXXXXXX',
'XXXXXXXXXX',
'XXXXXXXXXX'
)

