LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;

DATA DLPCNS (KEEP=BF_SSN LN_SEQ);
	SET PKUB.LNXX_LON;
	WHERE
		IC_LON_PGM = 'DLPCNS'
		AND LD_LON_X_DSB > 'XXJULXXXX'D;
RUN;

ENDRSUBMIT;

PROC EXPORT
		DATA=LEGEND.DLPCNS
		OUTFILE='T:\SAS\DLPCNS.XLSX'
		REPLACE;
RUN;
		
