SELECT 
	CASE 
		WHEN MONTH(WD_ACT_REQ) = X AND YEAR(WD_ACT_REQ) = XXXX THEN 'XX/XXXX'
		WHEN MONTH(WD_ACT_REQ) = XX AND YEAR(WD_ACT_REQ) = XXXX THEN 'XX/XXXX'
		WHEN MONTH(WD_ACT_REQ) = X AND YEAR(WD_ACT_REQ) = XXXX THEN 'XX/XXXX'
		WHEN MONTH(WD_ACT_REQ) = X AND YEAR(WD_ACT_REQ) = XXXX THEN 'XX/XXXX'
		WHEN MONTH(WD_ACT_REQ) = X AND YEAR(WD_ACT_REQ) = XXXX THEN 'XX/XXXX'
	END AS TIME_PERIOD,
	COUNT(*) as NEW_TASKS
	
FROM 
	CDW..WQXX_TSK_QUE_HST 
WHERE 
	WF_QUE = 'XX' 
	AND WC_STA_WQUEXX = 'U' 
	AND 
	(
		MONTH(WD_ACT_REQ) = X AND YEAR(WD_ACT_REQ) = XXXX
		OR
		MONTH(WD_ACT_REQ) = XX AND YEAR(WD_ACT_REQ) = XXXX
		OR
		MONTH(WD_ACT_REQ) = X AND YEAR(WD_ACT_REQ) = XXXX
		OR
		MONTH(WD_ACT_REQ) = X AND YEAR(WD_ACT_REQ) = XXXX
		OR
		MONTH(WD_ACT_REQ) = X AND YEAR(WD_ACT_REQ) = XXXX
	)
GROUP BY
	CASE 
		WHEN MONTH(WD_ACT_REQ) = X AND YEAR(WD_ACT_REQ) = XXXX THEN 'XX/XXXX'
		WHEN MONTH(WD_ACT_REQ) = XX AND YEAR(WD_ACT_REQ) = XXXX THEN 'XX/XXXX'
		WHEN MONTH(WD_ACT_REQ) = X AND YEAR(WD_ACT_REQ) = XXXX THEN 'XX/XXXX'
		WHEN MONTH(WD_ACT_REQ) = X AND YEAR(WD_ACT_REQ) = XXXX THEN 'XX/XXXX'
		WHEN MONTH(WD_ACT_REQ) = X AND YEAR(WD_ACT_REQ) = XXXX THEN 'XX/XXXX'
	END