LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
	CREATE TABLE LNXX AS
		SELECT
			LNXX.*,
			LNXX.IC_LON_PGM
		FROM
			PKUB.LNXX_FIN_ATY LNXX
			JOIN PKUB.LNXX_LON LNXX
				ON LNXX.BF_SSN = LNXX.BF_SSN
				AND LNXX.LN_SEQ = LNXX.LN_SEQ
		WHERE
			LNXX.LD_FAT_APL BETWEEN 'XXAPRXXXX'D AND 'XXAPRXXXX'D
	;
QUIT;

ENDRSUBMIT;

PROC EXPORT
		DATA=LEGEND.LNXX
		OUTFILE='T:\SAS\NH XXXX with IC_LON_PGM.XLSX'
		REPLACE;
RUN;
