SELECT DISTINCT
	DAY(LD_RPS_X_PAY_DU) AS DUE_DATE,
	COUNT(DISTINCT BF_SSN) AS BWR_COUNT
FROM 
	cdw.calc.RepaymentSchedules
WHERE
	CurrentGradation = X
GROUP BY
	DAY(LD_RPS_X_PAY_DU)
ORDER BY
	DAY(LD_RPS_X_PAY_DU)