SELECT * FROM OPENQUERY(LEGEND,
'
	SELECT
		RSXX.BF_SSN,
		RSXX.LN_RPS_SEQ,
		RSXX.LC_CAP_TRG_LVE_PFH
	FROM
		PKUB.RSXX_BR_RPD RSXX
		INNER JOIN PKUB.PDXX_PRS_NME PDXX
			ON PDXX.DF_PRS_ID = RSXX.BF_SSN
	WHERE
		PDXX.DF_SPE_ACC_ID = ''XXXXXXXXXX''
')