USE CDW
GO

SELECT DISTINCT
	PDXX.DM_PRS_X AS FIRST_NAME,
	PDXX.DM_PRS_LST AS LAST_NAME,
	LNXX.BF_SSN,
	AYXX.PF_REQ_ACT
FROM
	CDW..LNXX_LON LNXX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = LNXX.BF_SSN
	LEFT JOIN CDW..AYXX_BR_LON_ATY AYXX
		ON AYXX.BF_SSN = LNXX.BF_SSN
		AND PF_REQ_ACT = 'DIFCR'
WHERE
	LNXX.LF_DOE_SCL_ORG LIKE 'XXXXX%'
	