USE CDW
GO

SELECT DISTINCT
	PDXX.DF_SPE_ACC_ID,
	LNXX.LN_SEQ,
	CASE WHEN LNXX.BF_SSN IS NOT NULL THEN 'Y' ELSE 'N' END AS HAS_REFUND
FROM
	CDW..LNXX_LON LNXX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = LNXX.BF_SSN
	LEFT JOIN CDW..LNXX_FIN_ATY LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
		AND LNXX.PC_FAT_TYP = 'XX'
		AND LNXX.LC_STA_LONXX = 'A'
		AND ISNULL(LNXX.LC_FAT_REV_REA,'') = ''
WHERE
	LF_DOE_SCL_ORG IN 
	(
	'XXXXXXXX',
	'XXXXXXXX',
	'XXXXXXXX',
	'XXXXXXXX',
	'XXXXXXXX',
	'XXXXXXXX',
	'XXXXXXXX'
	)	
	AND LA_LON_AMT_GTR = X