USE CDW
GO

SELECT
	*
FROM OPENQUERY(LEGEND,
'
SELECT
	LNXX.*
FROM
	PKUB.PIXX_PID_CHG_LOG PIXX
	INNER JOIN PKUB.LNXX_LON LNXX
		ON LNXX.LF_STU_SSN = PIXX.DF_PRS_ID_NEW
WHERE
	LNXX.IC_LON_PGM = ''DLPLUS''
'
)

SELECT * FROM CDW..LNXX_LON WHERE BF_SSN = LF_STU_SSN AND IC_LON_PGM = 'DLPLUS'