--- LC_STA_LONXX = I
--- LD_STA_LONXX is between XX/XX/XXXX and XX/XX/XXXX
--- LD_FOR_APL is between XX/XX/XXXX and XX/XX/XXXX
--- LC_FOR_TYP = XX

USE CDW
GO

SELECT DISTINCT
	FBXX.LC_FOR_TYP AS FBXX_LC_FOR_TYP,
	LNXX.*
FROM
	LNXX_BR_FOR_APV LNXX
	INNER JOIN FBXX_BR_FOR_REQ FBXX
		ON LNXX.BF_SSN = FBXX.BF_SSN
		AND LNXX.LF_FOR_CTL_NUM = FBXX.LF_FOR_CTL_NUM
WHERE
	LNXX.LC_STA_LONXX = 'I'
	AND LNXX.LD_STA_LONXX BETWEEN CONVERT(DATE,'XXXXXXXX') AND CONVERT(DATE,'XXXXXXXX')
	AND LNXX.LD_FOR_APL BETWEEN CONVERT(DATE,'XXXXXXXX') AND CONVERT(DATE,'XXXXXXXX')
	AND FBXX.LC_FOR_TYP = 'XX'