SELECT 
	WQXX.WF_QUE,
	WQXX.WF_SUB_QUE,
	WQXX.WC_STA_WQUEXX AS CompletionStatus,
	WQXX.WF_USR_ASN_TSK AS Agent,
	WQXX.WD_ACT_REQ AS TaskCreateDate,
	WQXX.WF_LST_DTS_WQXX AS TaskCompleteDate,
	WQXX.PF_REQ_ACT AS ARC,
	PDXX.DF_SPE_ACC_ID AS AccountNumber
FROM 
	CDW..WQXX_TSK_QUE_HST WQXX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = WQXX.BF_SSN
WHERE 
	WQXX.WF_QUE IN('XA','XP') 
	AND WQXX.WC_STA_WQUEXX IN('X','C') 
	AND CAST(WQXX.WF_LST_DTS_WQXX AS DATE) BETWEEN 'XXXX-XX-XX' AND 'XXXX-XX-XX'
	AND WQXX.WF_USR_ASN_TSK IN('UTXXXXX','UTXXXXX','UTXXXXX')
ORDER BY
	Agent,
	WF_QUE,
	TaskCompleteDate