DECLARE @Temp TABLE(BF_SSN CHAR(X), AwardId VARCHAR(XX), FileDate DATE)
INSERT INTO @Temp
VALUES
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXPXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXPXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXUXXGXXXXXXXX','X/XX/XXXX'),
('XXXXXXXXX','XXXXXXXXXSXXGXXXXXXXX','X/XX/XXXX')

SELECT
	'D' AS RecordType,
	'XXXXXX' AS Servicer_ID_From,
	'XXXXXX' AS Servicer_ID_To,
	LNXX.IC_LON_PGM AS [Loan Program],
	T.AwardId AS Loan_ID,
	'TRSVOS' AS [Transaction Code],
	REPLACE(CONVERT(VARCHAR(XX), Trans.LD_FAT_EFF, XXX),'/','') AS DateOfTransfer,
	T.BF_SSN AS SSN,
	ABS(COALESCE(Trans.LA_FAT_CUR_PRI,X.XX)) AS PBO,
	ABS(COALESCE(Trans.LA_FAT_NSI,X.XX)) AS IRB,
	LNXX.LN_SEQ
FROM
	@Temp T
	INNER JOIN CDW..FSXX_DL_LON FSXX
		ON FSXX.BF_SSN = T.BF_SSN
		AND FSXX.LF_FED_AWD + RIGHT('XXX'+ CAST(FSXX.LN_FED_AWD_SEQ AS VARCHAR), X) = T.AwardId
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = FSXX.BF_SSN
		AND LNXX.LN_SEQ = FSXX.LN_SEQ
	LEFT JOIN CDW..LNXX_FIN_ATY DmcsAdj
		ON DmcsAdj.BF_SSN = LNXX.BF_SSN
		AND DmcsAdj.LN_SEQ = LNXX.LN_SEQ
		AND DmcsAdj.LC_STA_LONXX = 'A'
		AND COALESCE(DmcsAdj.LC_FAT_REV_REA,'') = ''
		AND DmcsAdj.PC_FAT_TYP = 'XX'
		AND DmcsAdj.PC_FAT_SUB_TYP IN('XX','XX','XX')
	LEFT JOIN 
	(
		SELECT
			BF_SSN,
			LN_SEQ,
			SUM(COALESCE(LA_FAT_CUR_PRI,X.XX)) AS LA_FAT_CUR_PRI,
			SUM(COALESCE(LA_FAT_NSI,X.XX)) AS LA_FAT_NSI,
			MAX(LD_FAT_EFF) AS LD_FAT_EFF
		FROM
			CDW..LNXX_FIN_ATY
		WHERE
			LC_STA_LONXX = 'A'
			AND COALESCE(LC_FAT_REV_REA,'') = ''
			AND PC_FAT_TYP = 'XX'
			AND PC_FAT_SUB_TYP = 'XX'
		GROUP BY
			BF_SSN,
			LN_SEQ
	) Trans
		ON Trans.BF_SSN = LNXX.BF_SSN
		AND Trans.LN_SEQ = LNXX.LN_SEQ	


select * from openquery(legend, 'select * from pkub.OWXX_OWN ')



SELECT T.*, LNXX.* FROM
	@Temp T
	INNER JOIN CDW..FSXX_DL_LON FSXX
		ON FSXX.BF_SSN = T.BF_SSN
		AND FSXX.LF_FED_AWD + RIGHT('XXX'+ CAST(FSXX.LN_FED_AWD_SEQ AS VARCHAR), X) = T.AwardId
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = FSXX.BF_SSN
		AND LNXX.LN_SEQ = FSXX.LN_SEQ
ORDER BY
	T.BF_SSN, LNXX.LN_SEQ

SELECT DISTINCT LNXX.PC_FAT_TYP FROM 
	@Temp T 
	INNER JOIN CDW..FSXX_DL_LON FSXX
		ON FSXX.BF_SSN = T.BF_SSN
		AND FSXX.LF_FED_AWD + RIGHT('XXX'+ CAST(FSXX.LN_FED_AWD_SEQ AS VARCHAR), X) = T.AwardId
	INNER JOIN CDW..LNXX_FIN_ATY LNXX
		ON LNXX.BF_SSN = FSXX.BF_SSN
		AND LNXX.LN_SEQ = FSXX.LN_SEQ
