USE CDW
GO

SELECT
	PDXX.DF_SPE_ACC_ID,
	LNXX.LN_SEQ,
	PDXX.DI_DSA_VET
FROM 
	CDW..PDXX_PRS_DSA PDXX
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = PDXX.DF_PRS_ID
WHERE
	DI_DSA_VET = 'Y'
	AND LNXX.LA_CUR_PRI > X.XX
	and lnXX.LD_LON_X_DSB <= pdXX.DD_DSA