SELECT * FROM OPENQUERY (LEGEND_TEST_VUKX,'
	SELECT
		PDXX.DF_SPE_ACC_ID
		,ADXX.*
	FROM
		PKUB.ADXX_PCV_ATY_ADJ ADXX
		INNER JOIN PKUB.PDXX_PRS_NME PDXX
			ON ADXX.BF_SSN = PDXX.DF_PRS_ID
	WHERE
		PDXX.DF_SPE_ACC_ID = ''XXXXXXXXXX''
');

SELECT * FROM OPENQUERY (LEGEND_TEST_VUKX,'
	SELECT
		PDXX.DF_SPE_ACC_ID
		,LNXX.*
	FROM
		PKUB.LNXX_INT_RTE_HST LNXX
		INNER JOIN PKUB.PDXX_PRS_NME PDXX
			ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	WHERE
		PDXX.DF_SPE_ACC_ID = ''XXXXXXXXXX''
');