SELECT
	COUNT(*),
	PF_REQ_ACT,
	YEAR(LD_ATY_REQ_RCV) AS [Year],
	MONTH(LD_ATY_REQ_RCV) AS [Month]
FROM
	CDW..AYXX_BR_LON_ATY
WHERE
	PF_REQ_ACT IN ('FCDNY','ADFCR')
	AND LD_ATY_REQ_RCV >= 'XXXX-XX-XX'
GROUP BY
	PF_REQ_ACT,
	YEAR(LD_ATY_REQ_RCV),
	MONTH(LD_ATY_REQ_RCV)
ORDER BY
	PF_REQ_ACT,
	[Year],
	[Month]
	