SELECT
	RTRIM(PD10.DM_PRS_1) + ' ' + rtrim(SUBSTRING(PD10.DM_PRS_MID,1,1)) + ' ' + RTRIM(PD10.DM_PRS_LST) AS [NAME],
	CNH.*
FROM
	CDW..CNH43834 CNH
	INNER JOIN CDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = CNH.SSN