LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;


/************* CHANGE THESE DATE VALUES *************************/

%LET FIRSTDATE = 'XXJANXXXX'd;

%LET LASTDATE = 'XXJANXXXX'd;

/****** keep in this format: 'XXDECXXXX'd; *********************/



PROC SQL;
	CREATE TABLE BORROWER AS
		SELECT DISTINCT
			LNXX.BF_SSN
			,LNXX.LN_SEQ
			,LNXX.PC_FAT_TYP
			,LNXX.PC_FAT_SUB_TYP
			,LNXX.LD_FAT_PST
			,LNXX.LA_FAT_CUR_PRI
			,LNXX.LA_FAT_NSI
			,LNXX.IC_LON_PGM
		FROM 
			PKUB.LNXX_FIN_ATY LNXX
			INNER JOIN PKUB.LNXX_LON LNXX
				ON LNXX.BF_SSN = LNXX.BF_SSN
				AND LNXX.LN_SEQ = LNXX.LN_SEQ
		WHERE 
			LNXX.PC_FAT_TYP = 'XX'
			AND LNXX.PC_FAT_SUB_TYP = 'XX'
			AND LNXX.LD_FAT_PST BETWEEN &FIRSTDATE AND &LASTDATE
	;
QUIT;

ENDRSUBMIT;

PROC EXPORT
		DATA=LEGEND.BORROWER
		OUTFILE="T:\SAS\CNH XXXX.xlsx"
		DBMS = EXCEL
		REPLACE;
		SHEET="DMCS";
RUN;
