%LET BEGIN = 'XX/XX/XXXX';
%LET END = 'XX/XX/XXXX';

%SYSLPUT BEGIN = &BEGIN;
%SYSLPUT END = &END;	

LIBNAME  LEGEND  REMOTE  SERVER=LEGEND  SLIBREF=WORK;
RSUBMIT;

PROC SQL;
CONNECT TO DBX (DATABASE=DNFPUTDL);
	CREATE TABLE BNKR AS
		SELECT 
			*
		FROM
			CONNECTION TO DBX 
			(
				SELECT DISTINCT 
					PDXX.DF_SPE_ACC_ID
					,LNXX.BF_SSN
				FROM
					PKUB.PDXX_PRS_NME PDXX
					INNER JOIN PKUB.LNXX_LON LNXX
						ON PDXX.DF_PRS_ID = LNXX.BF_SSN
					INNER JOIN PKUB.DWXX_DW_CLC_CLU DWXX
						ON LNXX.BF_SSN = DWXX.BF_SSN
						AND LNXX.LN_SEQ = DWXX.LN_SEQ
					INNER JOIN PKUB.PDXX_PRS_BKR PDXX
						ON PDXX.DF_PRS_ID = PDXX.DF_PRS_ID
				WHERE	
					DWXX.WC_DW_LON_STA = 'XX'
					AND LNXX.LA_CUR_PRI > X
					AND PDXX.DD_BKR_FIL BETWEEN &BEGIN AND &END

			FOR READ ONLY WITH UR

			);
DISCONNECT FROM DBX;

ENDRSUBMIT;

DATA BNKR; 
	SET LEGEND.BNKR; 
RUN;

PROC EXPORT DATA= WORK.BNKR
            OUTFILE= "T:\SAS\Fed Bankruptcies.&SYSDATE..xlsx" 
            DBMS=EXCEL REPLACE;
     SHEET="OUPUT"; 
RUN;
