LIBNAME FSA 'Q:\CS Systems Support\Data Mart Validation Reports\X-XX-XX\DF FB Extend Details Feb XX from FSA.xlsx';
LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;

DATA LEGEND.ELEG;
	SET FSA.'Extended$'N;
RUN;

RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;

PROC SQL;
	CREATE TABLE COMPASS AS
		SELECT DISTINCT
			FSXX.BF_SSN,
			FSXX.LF_FED_AWD||PUT(FSXX.LN_FED_AWD_SEQ,ZX.) AS AWARD_ID,
			LNXX.LC_TYP_SCH_DIS
		FROM
			PKUB.LNXX_LON LNXX
			JOIN PKUB.LNXX_LON_RPS LNXX
				ON LNXX.BF_SSN = LNXX.BF_SSN
				AND LNXX.LN_SEQ = LNXX.LN_SEQ
			JOIN PKUB.FSXX_DL_LON FSXX
				ON LNXX.BF_SSN = FSXX.BF_SSN
				AND LNXX.LN_SEQ = FSXX.LN_SEQ
		WHERE
			LNXX.LA_CUR_PRI > X
			AND LNXX.LC_STA_LONXX = 'R'
			AND LNXX.LC_STA_LONXX = 'A'
			AND LNXX.LC_TYP_SCH_DIS IN ('EL','EG')
	;

	CREATE TABLE NOFSA AS
		SELECT DISTINCT
			C.BF_SSN,
			C.AWARD_ID,
			C.LC_TYP_SCH_DIS
		FROM
			COMPASS C
			LEFT JOIN ELEG E
				ON C.AWARD_ID = E.AWARD_ID
		WHERE
			E.AWARD_ID IS NULL
	;

QUIT;

ENDRSUBMIT;

DATA NOFSA; SET LEGEND.NOFSA; RUN;

PROC EXPORT
		DATA=NOFSA
		OUTFILE='T:\EL EG LOANS NOT AT FSA.XLSX'
		REPLACE;
RUN;
