USE CDW
GO

--borrowers
SELECT DISTINCT
	PDXX.DF_SPE_ACC_ID
	,LNXX.LC_STA_LONXX
	,CASE
		WHEN LNXX.LA_CUR_PRI > X.XX
		THEN '>X'
		ELSE NULL
	END AS LA_CUR_PRI
	,PDXX.DC_DOM_ST
	,PDXX.DI_VLD_ADR
FROM
	..LNXX_LON LNXX
	INNER JOIN ..PDXX_PRS_NME PDXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	INNER JOIN ..PDXX_PRS_ADR PDXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
WHERE
	LNXX.LC_STA_LONXX = 'R'
	AND LNXX.LA_CUR_PRI > X.XX
	AND PDXX.DC_DOM_ST = 'DC'
	AND PDXX.DI_VLD_ADR = 'Y'

--loans
SELECT DISTINCT
	PDXX.DF_SPE_ACC_ID
	,LNXX.LN_SEQ
	,LNXX.LC_STA_LONXX
	,CASE
		WHEN LNXX.LA_CUR_PRI > X.XX
		THEN '>X'
		ELSE NULL
	END AS LA_CUR_PRI
	,PDXX.DC_DOM_ST
	,PDXX.DI_VLD_ADR
FROM
	..LNXX_LON LNXX
	INNER JOIN ..PDXX_PRS_NME PDXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	INNER JOIN ..PDXX_PRS_ADR PDXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID

WHERE
	LNXX.LC_STA_LONXX = 'R'
	AND LNXX.LA_CUR_PRI > X.XX
	AND PDXX.DC_DOM_ST = 'DC'
	AND PDXX.DI_VLD_ADR = 'Y'



--# of borrowers
SELECT
	'BORROWERS' [TYPE],
	COUNT(DISTINCT LNXX.BF_SSN) [TOTAL]
FROM
	..LNXX_LON LNXX
	INNER JOIN ..PDXX_PRS_ADR PDXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
WHERE
	LNXX.LC_STA_LONXX = 'R'
	AND LNXX.LA_CUR_PRI > X.XX
	AND PDXX.DC_DOM_ST = 'DC'
	AND PDXX.DI_VLD_ADR = 'Y'

UNION ALL

--# of loans
SELECT
	'LOANS' [TYPE],
	COUNT(LNXX.LN_SEQ) [TOTAL]
FROM
	..LNXX_LON LNXX
	INNER JOIN ..PDXX_PRS_ADR PDXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
WHERE
	LNXX.LC_STA_LONXX = 'R'
	AND LNXX.LA_CUR_PRI > X.XX
	AND PDXX.DC_DOM_ST = 'DC'
	AND PDXX.DI_VLD_ADR = 'Y'
