LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;

DATA DOD;
	INFILE 'T:\SCRA_X_X_UNWSXX.NWSXXRX._XXXV._XXXXXX.txt';
	INPUT SSN $ X-X LT_DOD $ XXX-XXX;
RUN;

DATA DODX (DROP=LT_DOD);
	SET DOD;
	FORMAT LD_DOD DATEX.;
	IF LT_DOD = 'XXXXXXXX' THEN LD_DOD = 'XXDECXXXX'D;
	ELSE LD_DOD = INPUT(LT_DOD,YYMMDDX.);
RUN;

DATA DODX;
	SET DODX;
	WHERE LD_DOD ^= 'XXDECXXXX'D;
RUN;

DATA LEGEND.DOD; SET DODX; RUN;

RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
	CREATE TABLE MILT_INT AS
		SELECT DISTINCT
			DOD.SSN,
			DOD.LD_DOD,
			PDXX.DF_SPE_ACC_ID,
			LNXX.LN_SEQ,
			LNXX.LD_ITR_EFF_BEG,
			LNXX.LD_ITR_EFF_END,
			LNXX.LR_ITR,
			LNXX.LC_INT_RDC_PGM
		FROM
			DOD
			JOIN PKUB.PDXX_PRS_NME PDXX
				ON DOD.SSN = PDXX.DF_PRS_ID
			JOIN PKUB.LNXX_INT_RTE_HST LNXX
				ON PDXX.DF_PRS_ID = LNXX.BF_SSN
		WHERE
			TODAY() BETWEEN LNXX.LD_ITR_EFF_BEG AND LNXX.LD_ITR_EFF_END
			AND LNXX.LR_ITR  < X
			AND LNXX.LC_INT_RDC_PGM = 'M'
			AND LNXX.LD_ITR_EFF_END > DOD.LD_DOD
			AND LNXX.LC_STA_LONXX = 'A'
	;
QUIT;
ENDRSUBMIT;
DATA MILT_INT; SET LEGEND.MILT_INT; RUN;

RSUBMIT;
PROC SQL;
	CREATE TABLE MILT_DEF AS
		SELECT DISTINCT
			DOD.SSN,
			DOD.LD_DOD,
			PDXX.DF_SPE_ACC_ID,
			DEFR.LN_SEQ,
			DEFR.LC_DFR_TYP,
			DEFR.LD_DFR_END
		FROM
			DOD
			JOIN PKUB.PDXX_PRS_NME PDXX
				ON DOD.SSN = PDXX.DF_PRS_ID
			LEFT JOIN
				(
					SELECT 
						LNXX.BF_SSN,
						LNXX.LN_SEQ,
						DFXX.LC_DFR_TYP,
						LNXX.LD_DFR_END
					FROM
						PKUB.DFXX_BR_DFR_REQ DFXX
						JOIN PKUB.LNXX_BR_DFR_APV LNXX
							ON DFXX.BF_SSN = LNXX.BF_SSN
							AND DFXX.LF_DFR_CTL_NUM = LNXX.LF_DFR_CTL_NUM
							AND LNXX.LC_STA_LONXX = 'A'
							AND DFXX.LC_DFR_STA = 'A'
							AND DFXX.LC_STA_DFRXX = 'A'
							AND DFXX.LC_DFR_TYP = 'XX'	
				) DEFR
				ON DOD.SSN = DEFR.BF_SSN
				AND DEFR.LD_DFR_END > DOD.LD_DOD
		WHERE
			DEFR.BF_SSN IS NOT NULL
	;
QUIT;
ENDRSUBMIT;
DATA MILT_DEF; SET LEGEND.MILT_DEF; RUN;

DATA ARC_FILE;
	SET MILT_INT (KEEP=DF_SPE_ACC_ID) MILT_DEF (KEEP=DF_SPE_ACC_ID);
RUN;

PROC SORT DATA=ARC_FILE NODUPKEY;
	BY DF_SPE_ACC_ID;
RUN;

DATA _NULL_;
	SET ARC_FILE ;
	FILE 'T:\QBLDR FILE - Active Duty Military Ended.TXT' DELIMITER=',' DSD DROPOVER LRECL=XXXXX;
	PUT DF_SPE_ACC_ID 'NNNNN,,,,,,,ALL,' ;
RUN;

PROC EXPORT
		DATA=MILT_INT
		OUTFILE='T:\DETAIL FILE - Active Duty Military Ended.XLSX'
		REPLACE;
RUN;

PROC EXPORT
		DATA=MILT_DEF
		OUTFILE='T:\DETAIL FILE - Active Duty Military Ended.XLSX'
		REPLACE;
RUN;

