/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/UNWOXX.NWOXXRZ";
FILENAME REPORTX "&RPTLIB/UNWOXX.NWOXXRX";
LIBNAME  LEGEND  REMOTE  SERVER=LEGEND  SLIBREF=WORK;
RSUBMIT;
LIBNAME pkub DBX DATABASE=DNFPUTDL OWNER=pkub;

PROC SQL;
CONNECT TO DBX (DATABASE=DNFPUTDL);
CREATE TABLE ALL AS
	SELECT	*
	FROM	CONNECTION TO DBX (
		SELECT DISTINCT A.BF_SSN
			,PDXX.DM_PRS_LST
/*			,LNXX.LD_STA_LONXX*/
			,LNXX.LN_DLQ_MAX
			,PDXX.DX_STR_ADR_X
			,PDXX.DX_STR_ADR_X
			,PDXX.DM_CT
			,PDXX.DC_DOM_ST
			,PDXX.DF_ZIP_CDE
			,PDXX.DN_DOM_PHN_ARA
			,PDXX.DN_DOM_PHN_XCH
			,PDXX.DN_DOM_PHN_LCL
			,CASE 
				WHEN C.DF_PRS_ID IS NULL AND D.DF_PRS_ID IS NULL THEN X
				ELSE X
			END AS BOTH_SKIP
			,CASE 
				WHEN C.DF_PRS_ID IS NULL AND D.DF_PRS_ID IS NOT NULL THEN X
				ELSE X
			END AS ADR_SKIP
			,CASE 
				WHEN D.DF_PRS_ID IS NULL AND C.DF_PRS_ID IS NOT NULL THEN X
				ELSE X
			END AS PHN_SKIP
	FROM PKUB.LNXX_LON A
		LEFT OUTER JOIN	(
			SELECT ADR.DF_PRS_ID
			FROM PKUB.PDXX_PRS_ADR ADR
			WHERE ADR.DI_VLD_ADR ='Y'
				AND DC_ADR = 'L') C
			ON A.BF_SSN = C.DF_PRS_ID
		LEFT OUTER JOIN	(
			SELECT PHN.DF_PRS_ID
			FROM PKUB.PDXX_PRS_PHN PHN
			WHERE PHN.DI_PHN_VLD ='Y') D
			ON A.BF_SSN = D.DF_PRS_ID
		INNER JOIN PKUB.LNXX_LON_DLQ_HST LNXX
			ON A.BF_SSN = LNXX.BF_SSN
			AND A.LN_SEQ = LNXX.LN_SEQ
			AND LNXX.LC_STA_LONXX = 'X'
/*			AND LNXX.LD_STA_LONXX = 'X-XX-XXXX'*/
			AND LNXX.LN_DLQ_MAX BETWEEN XX AND XXX
		INNER JOIN PKUB.PDXX_PRS_NME PDXX
			ON A.BF_SSN = PDXX.DF_PRS_ID
		LEFT JOIN PKUB.PDXX_PRS_ADR PDXX
			ON A.BF_SSN = PDXX.DF_PRS_ID
			AND PDXX.DC_ADR = 'L'
		LEFT JOIN PKUB.PDXX_PRS_PHN PDXX
			ON A.BF_SSN = PDXX.DF_PRS_ID
			AND PDXX.DC_PHN = 'H'
	WHERE A.LA_CUR_PRI > X
		AND A.LC_STA_LONXX = 'R'
		AND C.DF_PRS_ID IS NULL OR D.DF_PRS_ID IS NULL
				FOR READ ONLY WITH UR
			);
DISCONNECT FROM DBX;

/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>> ;  ** INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK;*/
QUIT;
ENDRSUBMIT;

DATA ALL;
	SET LEGEND.ALL;
RUN;

/*export to Excel spreadsheet*/
PROC EXPORT DATA = WORK.ALL
            OUTFILE = "T:\SAS\NH XXXX.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="A"; 
RUN;
