LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
	CREATE TABLE FSA AS
		SELECT DISTINCT
			PDXX.DF_SPE_ACC_ID,
			LNXX.LF_DOE_SCL_ORG,
			SDXX.LF_DOE_SCL_ENR_CUR
		FROM
			PKUB.PDXX_PRS_NME PDXX
			JOIN PKUB.LNXX_LON LNXX
				ON PDXX.DF_PRS_ID = LNXX.BF_SSN
			LEFT JOIN PKUB.SDXX_STU_SPR SDXX
				ON PDXX.DF_PRS_ID = SDXX.LF_STU_SSN
		WHERE
			LNXX.LF_DOE_SCL_ORG IN
				(
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX'
				)
			OR SDXX.LF_DOE_SCL_ENR_CUR IN
				(
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX',
					'XXXXXXXX'
				)
	;
QUIT;
ENDRSUBMIT;

DATA FSA; SET LEGEND.FSA; RUN;

PROC EXPORT
		DATA=FSA
		OUTFILE='T:\FSA Request - School Code Query.XLSX'
		REPLACE;
RUN;
				
