
LIBNAME  LEGEND  REMOTE  SERVER=LEGEND SLIBREF=work  ;			
RSUBMIT LEGEND;			
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;			
			
%LET BEGIN = 'XXAPRXXXX'D;	
%LET END = 'XXJUNXXXX'D;	
			
PROC SQL;			
	CREATE TABLE DEMO AS		
		SELECT DISTINCT	
			BF_SSN,
			LN_SEQ,
			LD_FAT_PST,
			CASE 
				WHEN PC_FAT_SUB_TYP = 'XX' THEN 'PSLF'
				WHEN PC_FAT_SUB_TYP = 'XX' THEN 'TPD'
				WHEN PC_FAT_SUB_TYP = 'XX' THEN 'DMCS'
			ELSE ''
			END AS TRANSFER_TYPE
		FROM	
			PKUB.LNXX_FIN_ATY
		WHERE	
			LD_FAT_PST BETWEEN &BEGIN AND &END
			AND PC_FAT_TYP = 'XX'
			AND PC_FAT_SUB_TYP IN ('XX','XX','XX')
	;		
QUIT;			
			
ENDRSUBMIT;			
			
DATA DEMO; SET LEGEND.DEMO; RUN;			
			
/*export to Excel spreadsheet*/			
PROC EXPORT DATA = WORK.DEMO 			
            OUTFILE = "T:\SAS\NH XXXX.xlsx" 			
            DBMS = EXCEL			
			REPLACE;
RUN;			
