SELECT * FROM OPENQUERY(LEGEND,
'
SELECT
	FSXX.*
FROM
	PKUB.PDXX_PRS_NME PDXX
	INNER JOIN PKUB.FSXX_ICR_NEG_AMR FSXX
		ON FSXX.BF_SSN = PDXX.DF_PRS_ID
WHERE 
	DF_SPE_ACC_ID = ''XXXXXXXXXX''
')