USE UDW
GO

SELECT
	MONTH(LD_FAT_EFF) AS [MONTH],
	YEAR(LD_FAT_EFF) AS [YEAR],
	COUNT(DISTINCT BF_SSN) AS BORROWER_COUNT,
	COUNT(*) AS LOAN_COUNT
	--*
FROM
	UDW..LNXX_FIN_ATY LNXX
WHERE
	LC_STA_LONXX = 'A'
	AND ISNULL(LC_FAT_REV_REA,'') = ''
	AND PC_FAT_TYP = 'XX' 
	AND PC_FAT_SUB_TYP = 'XX'
	AND LD_FAT_EFF BETWEEN 'XX-XX-XXXX' AND 'XX-XX-XXXX'
GROUP BY
	MONTH(LD_FAT_EFF),
	YEAR(LD_FAT_EFF) 