/****** Script for SelectTopNRows command from SSMS  ******/
--DROP TABLE IF EXISTS #DATA
--SELECT DISTINCT 
--	AYXX.PF_RSP_ACT,
--	AYXX.PF_REQ_ACT,
--	AYXX.BF_SSN,
--	AYXX.LN_ATY_SEQ,
--	CNH.*
--INTO #DATA
--  FROM [CDW].[dbo].[CNH XXXXX] CNH
--  INNER JOIN CDW..ACXX_ACT_REQ_LTR ACXX
--	ON ACXX.PF_LTR = CNH.RM_DSC_LTR_QUE
--	INNER JOIN CDW..AYXX_BR_LON_ATY AYXX
--		ON AYXX.BF_SSN = CNH.RF_SBJ_QUE
--		AND AYXX.LN_ATY_SEQ = CNH.RN_ATY_SEQ_QUE
--  INNER JOIN CDW..LTXX_LTR_REQ_PRC LTXX
--	ON CNH.RF_SBJ_QUE = LTXX.RF_SBJ_PRC
--	AND CNH.RM_DSC_LTR_QUE = LTXX.RM_DSC_LTR_PRC
--	AND CNH.RN_ENT_REQ_QUE = LTXX.RN_ENT_REQ_PRC
--	AND CNH.RN_ATY_SEQ_QUE = LTXX.RN_ATY_SEQ_PRC
--	AND CNH.RN_SEQ_LTR_CRT_QUE = LTXX.RN_SEQ_LTR_CRT_PRC
--	AND CNH.RN_SEQ_REC_QUE = LTXX.RN_SEQ_REC_PRC
--WHERE 
--	InactivatedAt IS NULL
	
SELECT
	*
FROM
	#DATA
