
%LET RPTLIB = T:\SAS;
FILENAME REPORTX "&RPTLIB/RO_XX_CLEAN_UP";

data borrowers; 
infile 'T:\RXXX Queue Task Killer Need DCR.txt' dlm=',' dsd truncover; 
input queue :$X. subqueue :$X. BF_SSN :$XX. arc :$X.; 
run;

LIBNAME  LEGEND  REMOTE  SERVER=LEGEND SLIBREF=WORK;
DATA LEGEND.BORROWERS; *Send data to LEGEND;
SET BORROWERS;
RUN;

RSUBMIT LEGEND;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
	CREATE TABLE NHXXXX AS
		SELECT	
			PDXX.DF_SPE_ACC_ID,
			CASE
				WHEN S.ARC = 'LSXXX' THEN
					'NVLD PYMNT AMNT X SCHDL, REDISCLS ON LEVEL'
				WHEN S.ARC = 'PRHRA' THEN
					'REVIEW LOANS FOR ELIGIBLITY FOR PL OR PG REPAY SCH'
			END AS COMMENT


		FROM
			 BORROWERS S
		INNER JOIN PKUB.PDXX_PRS_NME PDXX
			ON PDXX.DF_PRS_ID = S.BF_SSN

;
QUIT;
ENDRSUBMIT;

DATA NHXXXX;
SET LEGEND.NHXXXX;
RUN;


/*export to queue builder (fed) file*/
DATA _NULL_;
	SET NHXXXX;
	FILE 'T:\ROXX_CLEAN_UP.TXT' DELIMITER=',' DSD DROPOVER LRECL=XXXXX;
	PUT DF_SPE_ACC_ID 'PRHRA,,,,,,,ALL,'COMMENT;
RUN;

