SELECT DISTINCT
	LNXX.BF_SSN,
	LNXX.LN_SEQ,
	LNXX.LN_DLQ_MAX AS DAYS_PAST_DUE,
	LKXX.PX_DSC_MDM AS LOAN_STATUS
FROM
	CDW..LNXX_LON_DLQ_HST LNXX
	INNER JOIN CDW..DWXX_DW_CLC_CLU DWXX
		ON DWXX.BF_SSN = LNXX.BF_SSN
		AND DWXX.LN_SEQ = LNXX.LN_SEQ
		AND DWXX.WC_DW_LON_STA IN ('XX','XX','XX','XX')
	INNER JOIN CDW..LKXX_LS_CDE_LKP LKXX
		ON LKXX.PM_ATR = 'WC-DW-LON-STA'
		AND LKXX.PX_ATR_VAL = DWXX.WC_DW_LON_STA
WHERE
	LC_STA_LONXX = 'X'
	and LN_DLQ_MAX >= XX



