
SELECT * FROM OPENQUERY(LEGEND,
'
	SELECT DISTINCT
		PDXX.DF_SPE_ACC_ID,
		CASE 
			WHEN LNXX.LF_DOE_SCL_ORG LIKE ''XXXXXX%'' OR LNXX.LF_DOE_SCL_ORG LIKE ''XXXXXX%'' THEN LNXX.LF_DOE_SCL_ORG
			WHEN MRXB.LF_DOE_SCL_ENR_CUR LIKE ''XXXXXX%'' OR MRXB.LF_DOE_SCL_ENR_CUR LIKE ''XXXXXX%'' THEN MRXB.LF_DOE_SCL_ENR_CUR
			ELSE NULL
		END AS SCHOOL_CODE,
		AYXX.PF_REQ_ACT,
		AYXX.LD_ATY_REQ_RCV
	FROM
		PKUB.PDXX_PRS_NME PDXX
		INNER JOIN PKUB.AYXX_BR_LON_ATY AYXX
			ON AYXX.BF_SSN = PDXX.DF_PRS_ID
		LEFT JOIN PKUB.LNXX_LON LNXX
			ON PDXX.DF_PRS_ID = LNXX.BF_SSN
		LEFT JOIN PKUR.MRXB_MR_LON_MTH_XX MRXB
			ON MRXB.BF_SSN = PDXX.DF_PRS_ID
	WHERE
		AYXX.PF_REQ_ACT IN (''DICSK'', ''CSFSA'', ''ADSCH'', ''CSDNY'')
		AND
		(
			LNXX.LF_DOE_SCL_ORG LIKE ''XXXXXX%''
			OR
			LNXX.LF_DOE_SCL_ORG LIKE ''XXXXXX%''
			OR
			MRXB.LF_DOE_SCL_ENR_CUR LIKE ''XXXXXX%''
			OR
			MRXB.LF_DOE_SCL_ENR_CUR LIKE ''XXXXXX%''
		)
')