USE CDW

GO

SELECT DISTINCT
	PDXX.DF_SPE_ACC_ID AS ACCOUNT_NUMBER,
	CAST(WQXX.WF_CRT_DTS_WQXX AS DATE) AS TASK_CREATE_DATE
FROM
	CDW..WQXX_TSK_QUE WQXX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = WQXX.BF_SSN
WHERE
	WF_QUE = 'XR'
	AND PF_REQ_ACT = 'CRDVL'
ORDER BY 
	TASK_CREATE_DATE