LIBNAME XL 'T:\Query Accounts.xlsx';
LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;

DATA LEGEND.ACCOUNTS; SET XL.'SHEETX$'N; RUN;

RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
	CREATE TABLE OUTPUT AS
		SELECT DISTINCT
			ACNT.BF_SSN,
			FSXX.LF_FED_AWD,
			FSXX.LN_FED_AWD_SEQ,
			LNXX.LD_LON_GTR,
			LNXX.LC_FED_PGM_YR,
			LNXX.IC_LON_PGM,
			PDXX.DM_PRS_LST,
			PDXX.DM_PRS_X
		FROM
			ACCOUNTS ACNT
			JOIN PKUB.PDXX_PRS_NME PDXX
				ON ACNT.BF_SSN = PDXX.DF_PRS_ID
			JOIN PKUB.FSXX_DL_LON FSXX
				ON ACNT.BF_SSN = FSXX.BF_SSN
			JOIN PKUB.LNXX_LON LNXX
				ON ACNT.BF_SSN = LNXX.BF_SSN
				AND FSXX.LN_SEQ = LNXX.LN_SEQ
	;
QUIT;
ENDRSUBMIT;

DATA OUTPUT; SET LEGEND.OUTPUT; RUN;

PROC EXPORT
		DATA=OUTPUT
		OUTFILE='T:\Split Loan Transfer Query.XLSX'
		REPLACE;
RUN;
