USE CDW
GO

SELECT DISTINCT
	LNXX.BF_SSN
	,LNXX.LC_STA_LONXX
	,CAST(LNXX.LD_FOR_BEG AS DATE) [LD_FOR_BEG]
	,FBXX.LC_FOR_TYP
	,FBXX.LC_FOR_STA
	,FBXX.LC_STA_FORXX
	,LNXX.LC_FOR_RSP
FROM
	LNXX_LON LNXX
	INNER JOIN LNXX_BR_FOR_APV LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
	INNER JOIN FBXX_BR_FOR_REQ FBXX
		ON LNXX.BF_SSN = FBXX.BF_SSN
		AND LNXX.LF_FOR_CTL_NUM = FBXX.LF_FOR_CTL_NUM
WHERE
	LNXX.LC_STA_LONXX = 'A'
	AND CAST(LNXX.LD_FOR_BEG AS DATE) >= CAST('XXXX-XX-XX' AS DATE)
	AND FBXX.LC_FOR_TYP = 'XX'
	AND FBXX.LC_FOR_STA = 'A'
	AND FBXX.LC_STA_FORXX = 'A'
	AND LNXX.LC_FOR_RSP != 'XXX'
ORDER BY
	[LD_FOR_BEG]
