USE CDW
GO
SELECT
	YEAR(REPAYMENT_START_DATE) AS REPAYMENT_START_DATE_YEAR,
	COUNT(*) AS LOAN_COUNT,
	COUNT(DISTINCT BF_SSN) AS BORROWER_COUNT
FROM
(
	SELECT DISTINCT
		ISNULL(DATEADD(DAY, X, LNXX.LD_END_GRC_PRD), LNXX.LD_DSB) AS REPAYMENT_START_DATE,
		LNXX.BF_SSN,
		LNXX.LN_SEQ
	FROM
		CDW..LNXX_LON LNXX
		INNER JOIN 
		(
			SELECT
				BF_SSN,
				LN_SEQ,
				MAX(LD_DSB) AS LD_DSB
			FROM
				CDW..LNXX_DSB
			WHERE 
				LC_STA_LONXX = 'X'
				AND ISNULL(LC_DSB_CAN_REA,'') = ''
			GROUP BY
				BF_SSN,
				LN_SEQ
		) LNXX
			ON LNXX.BF_SSN = LNXX.BF_SSN
			AND LNXX.LN_SEQ = LNXX.LN_SEQ
	WHERE
		YEAR(ISNULL(DATEADD(DAY, X, LNXX.LD_END_GRC_PRD), LNXX.LD_DSB)) > = XXXX
		AND ISNULL(DATEADD(DAY, X, LNXX.LD_END_GRC_PRD), LNXX.LD_DSB) <= CAST(GETDATE() AS DATE) 
) POP
GROUP BY
	YEAR(REPAYMENT_START_DATE)
ORDER BY
	YEAR(REPAYMENT_START_DATE)
