select * from OPENQUERY(LEGEND, '
SELECT 
	PDXX.DF_SPE_ACC_ID, 
	ADXX.* 
FROM 
	PKUB.ADXX_PCV_ATY_ADJ ADXX 
	INNER JOIN PKUB.PDXX_PRS_NME PDXX 
		ON PDXX.DF_PRS_ID = ADXX.BF_SSN 
WHERE 
	PDXX.DF_SPE_ACC_ID = ''XXXXXXXXXX''')
