DROP TABLE IF EXISTS #FINAL;
WITH RATE AS
(
SELECT
	PDXX.DF_SPE_ACC_ID,
	LNXX.BF_SSN,
	LNXX.LN_SEQ,
	LNXX.LD_ITR_EFF_BEG,
	LNXX.LD_ITR_EFF_END,
	DATEADD(DAY, X, LNXX.LD_ITR_EFF_END) AS MISSING_BEGIN,
	LEAD(LNXX.LD_ITR_EFF_BEG, X) OVER(PARTITION BY LNXX.BF_SSN, LNXX.LN_SEQ ORDER BY LNXX.LD_ITR_EFF_BEG) AS NEXT_DATE,
	LEAD(LNXX.LD_ITR_EFF_BEG, X) OVER(PARTITION BY LNXX.BF_SSN, LNXX.LN_SEQ ORDER BY LNXX.LD_ITR_EFF_BEG) AS MISSING_END,
	ROW_NUMBER() OVER(PARTITION BY LNXX.BF_SSN, LNXX.LN_SEQ ORDER BY LNXX.LD_ITR_EFF_BEG) AS RN
FROM
	CDW..LNXX_INT_RTE_HST LNXX
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = LNXX.BF_SSN
WHERE
	LNXX.LC_STA_LONXX = 'A'
	AND LNXX.LA_CUR_PRI > X
	AND LNXX.LC_STA_LONXX = 'R'
	
)

SELECT 
	*,
	CASE WHEN DATEADD(DAY, X, LD_ITR_EFF_END) != NEXT_DATE AND NEXT_DATE IS NOT NULL THEN X ELSE X END AS FLAG
INTO #FINAL
FROM 
	RATE 

	

SELECT 
	DF_SPE_ACC_ID,
	LN_SEQ, 
	MISSING_BEGIN,
	DATEADD(DAY, -X, MISSING_END) AS MISSING_END
FROM 
	#FINAL
WHERE 
	FLAG = X
