USE CDW;
GO
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
GO

--direct pulls with a lookback datetime stamp
SELECT MAX(LF_LST_DTS_AYXX)	AS AYXX FROM AYXX_BR_LON_ATY
SELECT MAX(LF_LST_DTS_BLXX)	AS BLXX FROM BLXX_BR_BIL
SELECT MAX(BF_LST_DTS_BRXX)	AS BFXX FROM BRXX_BR_EFT
SELECT MAX(LF_LST_DTS_DFXX)	AS DFXX FROM DFXX_BR_DFR_REQ
SELECT MAX(LF_LST_DTS_FBXX)	AS FBXX FROM FBXX_BR_FOR_REQ
SELECT MAX(LF_LST_DTS_LNXX) AS LNXX FROM LNXX_RPD_PIO_CVN------july Xth
SELECT MAX(LF_LST_DTS_LNXX)	AS LNXX FROM LNXX_LON
SELECT MAX(LF_LST_DTS_LNXX)	AS LNXX FROM LNXX_DSB-------------july Xth
SELECT MAX(LF_LST_DTS_LNXX) AS LNXX FROM LNXX_LON_DLQ_HST
SELECT MAX(LF_LST_DTS_LNXX)	AS LNXX FROM LNXX_EDS-------------july Xth
SELECT * FROM OPENQUERY(LEGEND,'SELECT MAX(LF_LST_DTS_LNXX)	AS LNXX FROM PKUB.LNXX_EDS')-------july Xth
SELECT MAX(LF_LST_DTS_LNXX)	AS LNXX FROM LNXX_BR_DFR_APV
SELECT MAX(LF_LST_DTS_LNXX)	AS LNXX FROM LNXX_BR_FOR_APV
SELECT MAX(LF_LST_DTS_LNXX)	AS LNXX FROM LNXX_LON_RPS_SPF--------------july Xth
SELECT MAX(LF_LST_DTS_LNXX)	AS LNXX FROM LNXX_INT_RTE_HST
SELECT MAX(LD_LST_DTS_LNXX)	AS LNXX FROM LNXX_LON_BIL_CRF
SELECT MAX(LF_LST_DTS_LNXX)	AS LNXX FROM LNXX_LON_ATY
SELECT MAX(LF_LST_DTS_LNXX)	AS LNXX FROM LNXX_FIN_ATY------------------july Xth
SELECT * FROM OPENQUERY(LEGEND,'SELECT MAX(LF_LST_DTS_LNXX)	AS LNXX FROM PKUB.LNXX_FIN_ATY')
SELECT MAX(DF_LST_DTS_PDXX) AS PDXX FROM PDXX_PRS_NME----------------july Xth
SELECT MAX(DF_LST_DTS_PDXX)	AS PDXX FROM PDXX_PRS_PHN----------------july Xth
SELECT MAX(DF_LST_DTS_PHXX)	AS PHXX FROM PHXX_CNC_EML----------------july Xth
SELECT MAX(HF_LST_DTS_PHXX)	AS PHXX FROM PHXX_CNC_EML_HST------------july Xth
SELECT MAX(BF_LST_DTS_RFXX)	AS RFXX FROM RFXX_RFR--------------------july Xth
SELECT MAX(LF_LST_DTS_RSXX)	AS RSXX FROM RSXX_BR_RPD
SELECT MAX(DF_CRT_DTS_PDXX)	AS PDXXa FROM PDXX_PRS_ADR_EML-----------july Xth
SELECT MAX(DF_LST_DTS_PDXX)	AS PDXXb FROM PDXX_PRS_ADR_EML-----------july Xth
SELECT MAX(DD_STA_PDXX)		AS PDXXc FROM PDXX_PRS_ADR_EML-----------july Xth
SELECT MAX(WD_CLC_THU) AS DWXX FROM DWXX_DW_CLC_CLU
SELECT MAX(RT_RUN_SRT_DTS_PRC) AS LTXX FROM LTXX_LTR_REQ_PRC

SELECT MAX(LF_CRT_DTS_MRXX) AS MRXX FROM MRXX_BR_TAX----------------may Xth
SELECT * FROM OPENQUERY(LEGEND,'SELECT MAX(LF_CRT_DTS_MRXX) FROM PKUB.MRXX_BR_TAX')---may Xth
SELECT MAX(LF_TAX_YR) AS LF_TAX_YR FROM MRXX_MSC_TAX_RPT------------XXXX
SELECT * FROM OPENQUERY(LEGEND,'SELECT MAX(LF_TAX_YR) FROM PKUB.MRXX_MSC_TAX_RPT');---XXXX

----non-direct pulls and their dependent tables:
--BORR_AmountDue: LNXX, LNXX, PDXX
--BORR_BILL: LOAN_Bill
--BORR_Endorser: PDXX, LNXX
--BORR_Hardship: LNXX, FBXX
--BORR_LastPayment: PDXX, LNXX, 
--BORR_PendingDisb: PDXX, LNXX
--BORR_Rehabilitation: LNXX, PDXX
--BORR_Repayment: LNXX, FBXX
--BOR_Summaries: LNXX, PDXX, DWXX, LNXX
--DailyDelinquency: LNXX, LNXX
--DWXX Loan: PDXX, DWXX, 
--FBXX Forbearance: PDXX, LNXX, FBXX
--IvrData: PDXX, LNXX, DWXX, PDXX, PDXX, LNXX, LNXX, LNXX, MRXX, MRXX
--LNXX Loan: PDXX, LNXX
--LNXX Delinquency: PDXX, LNXX
--LNXX RepeymentSched: PDXX, LNXX
--LNXXInterestRate: 
--LOAN_Bill: BLXX, LNXX, PDXX
--PDXX Borrower: PDXX
--PDXX Address: PDXX, PDXX
--PDXX Email: PDXX, PDXX
--PDXX Phone: PDXX, PDXX
--RepaymentSchedules: PDXX, LNXX, RSXX, LNXX, LNXX, LNXX, DFXX, LNXX, FBXX, LNXX
