USE UDW
GO

SELECT 
	PDXX.DF_SPE_ACC_ID,
	LNXX.LN_SEQ,
	LNXX.LD_LON_IBR_ENT
FROM 
	UDW..PDXX_PRS_NME PDXX
	INNER JOIN UDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
WHERE 
	PDXX.DF_SPE_ACC_ID = 'XXXXXXXXXX'
