--note: due to large amount of output, consider re-writing this in SAS

--gets all those with contact dates
SELECT * 
INTO #POPULATION
FROM OPENQUERY (LEGEND,'
	SELECT
		LNXX.BF_SSN
		,LNXX.LN_SEQ
		,PDXX.DF_SPE_ACC_ID
		,LNXX_AYXX.CONTACT_DATE
		,LNXX_AYXX.DEFAULT_DATE
		,DAYS(LNXX_AYXX.DEFAULT_DATE) - DAYS(LNXX_AYXX.CONTACT_DATE)	AS DAY_DIFFERENCE
	FROM
		PKUB.LNXX_LON LNXX
		INNER JOIN 
		(	
			SELECT 
				LNXX.BF_SSN
				,LNXX.LN_SEQ
				,LNXX.LD_FAT_EFF AS DEFAULT_DATE
				,MAX(AYXX.LD_ATY_RSP) AS CONTACT_DATE
			FROM
				PKUB.AYXX_BR_LON_ATY AYXX
				INNER JOIN PKUB.LNXX_FIN_ATY LNXX
					ON AYXX.BF_SSN = LNXX.BF_SSN
			WHERE
				AYXX.PF_RSP_ACT = ''CNTCT''
				AND LNXX.PC_FAT_TYP = ''XX''
				AND LNXX.PC_FAT_SUB_TYP = ''XX''
				AND AYXX.LD_ATY_RSP < LNXX.LD_FAT_EFF
			GROUP BY
				LNXX.BF_SSN
				,LNXX.LN_SEQ
				,LNXX.LD_FAT_EFF
		) LNXX_AYXX
			ON LNXX.BF_SSN = LNXX_AYXX.BF_SSN
			AND LNXX.LN_SEQ = LNXX_AYXX.LN_SEQ
		INNER JOIN PKUB.PDXX_PRS_NME PDXX
			ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	WHERE
		LNXX.LC_STA_LONXX = ''D''
		AND LNXX.LC_SST_LONXX = ''X'' 
');


--must be within default date range:
SELECT * FROM #POPULATION 
--WHERE DF_SPE_ACC_ID IN (XXXXXXXXXX ,XXXXXXXXXX , XXXXXXXXXX ) ORDER BY DF_SPE_ACC_ID
WHERE DEFAULT_DATE NOT BETWEEN 'XXXX-XX-XX' AND 'XXXX-XX-XX'

DELETE FROM #POPULATION 
WHERE DEFAULT_DATE NOT BETWEEN 'XXXX-XX-XX' AND 'XXXX-XX-XX'


--contact must be before default:
SELECT * FROM #POPULATION 
--WHERE DAY_DIFFERENCE < X ORDER BY DAY_DIFFERENCE DESC
DELETE FROM #POPULATION WHERE DAY_DIFFERENCE < X 


--date tier tabs:
SELECT * FROM #POPULATION WHERE DAY_DIFFERENCE <= XX ORDER BY DAY_DIFFERENCE  DESC
SELECT * FROM #POPULATION WHERE DAY_DIFFERENCE <= XX ORDER BY DAY_DIFFERENCE  DESC
SELECT * FROM #POPULATION WHERE DAY_DIFFERENCE <= XX ORDER BY DAY_DIFFERENCE  DESC
SELECT * FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX ORDER BY DAY_DIFFERENCE DESC
SELECT * FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX ORDER BY DAY_DIFFERENCE DESC
SELECT * FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX ORDER BY DAY_DIFFERENCE DESC
SELECT * FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX ORDER BY DAY_DIFFERENCE DESC
SELECT * FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX ORDER BY DAY_DIFFERENCE DESC
SELECT * FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX ORDER BY DAY_DIFFERENCE DESC
SELECT * FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX ORDER BY DAY_DIFFERENCE DESC
SELECT * FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX ORDER BY DAY_DIFFERENCE DESC
SELECT * FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX ORDER BY DAY_DIFFERENCE DESC


--gets those with null contact dates
SELECT * 
INTO #POPULATION_NO_CONTACT
FROM OPENQUERY (LEGEND,'
	SELECT DISTINCT
		LNXX.BF_SSN
		,LNXX.LN_SEQ
		,PDXX.DF_SPE_ACC_ID
		,AYXX.LD_ATY_RSP		AS CONTACT_DATE
		,LNXX.LD_FAT_EFF		AS DEFAULT_DATE
		,DAYS(LNXX.LD_FAT_EFF) - DAYS(AYXX.LD_ATY_RSP)	AS DAY_DIFFERENCE
	FROM
		PKUB.LNXX_LON LNXX
		INNER JOIN PKUB.LNXX_FIN_ATY LNXX
			ON LNXX.BF_SSN = LNXX.BF_SSN
			AND LNXX.LN_SEQ = LNXX.LN_SEQ
		LEFT JOIN 
		(	
			SELECT 
				BF_SSN
				,MAX(LD_ATY_RSP) AS LD_ATY_RSP
			FROM
				PKUB.AYXX_BR_LON_ATY
			WHERE
				PF_RSP_ACT = ''CNTCT''
			GROUP BY
				BF_SSN
		) AYXX
			ON LNXX.BF_SSN = AYXX.BF_SSN
		INNER JOIN PKUB.PDXX_PRS_NME PDXX
			ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	WHERE
		LNXX.LC_STA_LONXX = ''D''
		AND LNXX.LC_SST_LONXX = ''X'' 
		AND LNXX.PC_FAT_TYP = ''XX''
		AND LNXX.PC_FAT_SUB_TYP = ''XX''
		AND AYXX.BF_SSN IS NULL
');

SELECT * FROM #POPULATION_NO_CONTACT WHERE DEFAULT_DATE BETWEEN 'XXXX-XX-XX' AND 'XXXX-XX-XX'
DELETE FROM #POPULATION_NO_CONTACT WHERE DEFAULT_DATE NOT BETWEEN 'XXXX-XX-XX' AND 'XXXX-XX-XX'

--POPULATION TAB:
SELECT * FROM #POPULATION
UNION 
SELECT * FROM #POPULATION_NO_CONTACT 
ORDER BY DAY_DIFFERENCE 


--NO CONTACT TAB:
SELECT * FROM #POPULATION 
WHERE DAY_DIFFERENCE > XXX 
UNION 
SELECT * FROM #POPULATION_NO_CONTACT 
ORDER BY DAY_DIFFERENCE


--COUNTS TAB:
;WITH CTEX AS (
	SELECT * FROM #POPULATION
	UNION 
	SELECT * FROM #POPULATION_NO_CONTACT 
),
CTEX AS (
	SELECT * FROM #POPULATION 
	WHERE DAY_DIFFERENCE > XXX 
	UNION 
	SELECT * FROM #POPULATION_NO_CONTACT 
)
SELECT COUNT(DISTINCT BF_SSN) AS DISTINCT_BORROWERS, 'POPULATION' AS DAY_TAB FROM CTEX UNION
SELECT COUNT(DISTINCT BF_SSN) AS DISTINCT_BORROWERS, 'NO CONTACT' AS DAY_TAB FROM CTEX UNION
SELECT COUNT(DISTINCT BF_SSN) AS DISTINCT_BORROWERS, 'XXX' AS DAY_TAB FROM #POPULATION WHERE DAY_DIFFERENCE <= XX  UNION
SELECT COUNT(DISTINCT BF_SSN) AS DISTINCT_BORROWERS, 'XXX' AS DAY_TAB FROM #POPULATION WHERE DAY_DIFFERENCE <= XX  UNION
SELECT COUNT(DISTINCT BF_SSN) AS DISTINCT_BORROWERS, 'XXX' AS DAY_TAB FROM #POPULATION WHERE DAY_DIFFERENCE <= XX  UNION
SELECT COUNT(DISTINCT BF_SSN) AS DISTINCT_BORROWERS, 'XXX' AS DAY_TAB FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX UNION 
SELECT COUNT(DISTINCT BF_SSN) AS DISTINCT_BORROWERS, 'XXX' AS DAY_TAB FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX UNION 
SELECT COUNT(DISTINCT BF_SSN) AS DISTINCT_BORROWERS, 'XXX' AS DAY_TAB FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX UNION 
SELECT COUNT(DISTINCT BF_SSN) AS DISTINCT_BORROWERS, 'XXX' AS DAY_TAB FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX UNION 
SELECT COUNT(DISTINCT BF_SSN) AS DISTINCT_BORROWERS, 'XXX' AS DAY_TAB FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX UNION 
SELECT COUNT(DISTINCT BF_SSN) AS DISTINCT_BORROWERS, 'XXX' AS DAY_TAB FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX UNION 
SELECT COUNT(DISTINCT BF_SSN) AS DISTINCT_BORROWERS, 'XXX' AS DAY_TAB FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX UNION 
SELECT COUNT(DISTINCT BF_SSN) AS DISTINCT_BORROWERS, 'XXX' AS DAY_TAB FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX UNION 
SELECT COUNT(DISTINCT BF_SSN) AS DISTINCT_BORROWERS, 'XXX' AS DAY_TAB FROM #POPULATION WHERE DAY_DIFFERENCE <= XXX
ORDER BY DAY_TAB


--DROP TABLE #POPULATION
--DROP TABLE #POPULATION_NO_CONTACT