USE CDW
GO

SELECT DISTINCT
	LTRIM(RTRIM(PDXX.DM_PRS_LST)) AS LAST_NAME,
	LTRIM(RTRIM(PDXX.DM_PRS_X)) AS fIRST_NAME,
	PDXX.DF_PRS_ID AS SSN,
	ISNULL(EMAIL.DX_ADR_EML,'N/A') AS EMAIL_ADDRESS
FROM 
	CDW..PDXX_PRS_NME PDXX
	LEFT JOIN
	(
		SELECT
			P.*,
			ROW_NUMBER() OVER (PARTITION BY DF_PRS_ID ORDER BY LAST_UPDATE DESC) AS RN
		FROM
		(
			SELECT
				DF_PRS_ID,
				DX_ADR_EML,
				MAX(DF_LST_DTS_PDXX) AS LAST_UPDATE
			FROM
				CDW..PDXX_PRS_ADR_EML PDXX
			WHERE
				DC_STA_PDXX = 'A'
				AND DI_VLD_ADR_EML = 'Y'
			GROUP BY
				DF_PRS_ID,
				DX_ADR_EML

			UNION ALL

			SELECT
				PDXX.DF_PRS_ID,
				DX_CNC_EML_ADR AS DX_ADR_EML,
				MAX(DF_LST_DTS_PHXX) AS LAST_UPDATE
			FROM
				CDW..PHXX_CNC_EML PHXX
				INNER JOIN CDW..PDXX_PRS_NME PDXX
					ON PHXX.DF_SPE_ID = PDXX.DF_SPE_ACC_ID
			WHERE 
				DI_VLD_CNC_EML_ADR = 'Y'
			GROUP BY
				PDXX.DF_PRS_ID,
				DX_CNC_EML_ADR
		) P
		
	) EMAIL
		ON EMAIL.DF_PRS_ID = PDXX.DF_PRS_ID
		AND EMAIL.RN = X
WHERE
	PDXX.DF_PRS_ID IN 
	(
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX',
	'XXXXXXXXX'
	)