USE CDW
GO

SELECT
	PDXX.DM_PRS_X AS FirstName,
	PDXX.DM_PRS_LST AS LastName,
	PDXX.DF_SPE_ACC_ID AS AccountNumber,
	LNXX.LD_DFR_BEG AS BeginDate,
	LNXX.LD_DFR_END AS EndDate,
	DFXX.LD_CRT_REQ_DFR AS AppReceivedDate,
	LNXX.LD_DFR_APL AS ProcessedDate,
	LNXX.LA_CUR_PRI AS Balance,
	LNXX.LN_SEQ AS LoanSequence
FROM
	PDXX_PRS_NME PDXX
	INNER JOIN LNXX_LON LNXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	INNER JOIN LNXX_BR_DFR_APV LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
	INNER JOIN DFXX_BR_DFR_REQ DFXX
		ON DFXX.BF_SSN = LNXX.BF_SSN
		AND DFXX.LF_DFR_CTL_NUM = LNXX.LF_DFR_CTL_NUM
WHERE
	LNXX.LC_DFR_RSP != 'XXX' --denied
	AND LNXX.LC_STA_LONXX = 'A'
	AND DFXX.LC_STA_DFRXX = 'A'
	AND DFXX.LC_DFR_STA = 'A'
	AND DFXX.LC_DFR_TYP IN ('XX','XX')
	AND DFXX.LD_CRT_REQ_DFR >= 'XXXX-XX-XX'