SELECT * FROM OPENQUERY (LEGEND,'
	SELECT DISTINCT
		LNXX.BF_SSN
		,LNXX.LN_SEQ
		,LNXX.LN_RPS_SEQ
		,LNXX.LD_CRT_LONXX 
		,RSXX.LD_STA_RPSTXX
		,RSXX.LC_STA_RPSTXX
	FROM
		PKUB.LNXX_LON_RPS LNXX
		INNER JOIN PKUB.LNXX_LON_RPS LNXXP
			ON LNXX.BF_SSN = LNXXP.BF_SSN
			AND LNXX.LN_SEQ = LNXXP.LN_SEQ
			AND LNXX.LN_RPS_SEQ = LNXXP.LN_RPS_SEQ + X
		LEFT  JOIN 
			(
				SELECT DISTINCT
					RSXX.BF_SSN
					,RSXX.LC_STA_RPSTXX
					,MAX(RSXX.LD_STA_RPSTXX) AS LD_STA_RPSTXX
				FROM		
					PKUB.RSXX_BR_RPD RSXX
				--WHERE
				--	RSXX.LC_STA_RPSTXX = ''I''
				GROUP BY
					RSXX.BF_SSN
					,RSXX.LC_STA_RPSTXX
			)RSXX
			ON LNXX.BF_SSN = RSXX.BF_SSN
	WHERE 
		LNXX.BF_SSN = ''XXXXXXXXX''
	ORDER BY
		LNXX.BF_SSN
		,LNXX.LN_SEQ
		,LNXX.LN_RPS_SEQ
');
