/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/UNWSXX.NWSXXRZ";
FILENAME REPORTX "&RPTLIB/UNWSXX.NWSXXRX";

LIBNAME  LEGEND  REMOTE  SERVER=LEGEND SLIBREF=work  ;
RSUBMIT LEGEND;
%let DB = DNFPRQUT;  *This is test;
/*%let DB = DNFPUTDL;  *This is live;*/

LIBNAME PKUB DBX DATABASE=&DB OWNER=PKUB;

PROC SQL;
CONNECT TO DBX (DATABASE=&DB);
	CREATE TABLE FINAL AS
	SELECT *
	FROM CONNECTION TO DBX (
		SELECT DISTINCT	
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
/*			LNXX.IF_LON_SRV_DFL_LON,*/
/*			CHAR(FSXX.LF_FED_AWD) ||  CHAR(FSXX.LN_FED_AWD_SEQ) AS Award_Id,*/
			LNXX.IC_LON_PGM,
			DAYS(CURRENT DATE) - DAYS(LNXX.LD_DLQ_OCC) AS Days_Delq,
/*			LNXX.LD_LON_RHB_PCV,*/
			LNXX.LC_RPR_TYP
		FROM
			PKUB.LNXX_LON LNXX
		INNER JOIN PKUB.LNXX_LON_DLQ_HST LNXX
			ON LNXX.BF_SSN = LNXX.BF_SSN
			AND LNXX.LN_SEQ = LNXX.LN_SEQ
/*		INNER JOIN PKUB.LNXX_RPD_PIO_CVN LNXX*/
/*			ON LNXX.BF_SSN = LNXX.BF_SSN*/
/*			AND LNXX.LN_SEQ = LNXX.LN_SEQ*/
/*		INNER JOIN PKUB.FSXX_DL_LON FSXX*/
/*			ON FSXX.BF_SSN = LNXX.BF_SSN*/
/*			AND FSXX.LN_SEQ = LNXX.LN_SEQ*/
		WHERE
/*			LNXX.LC_STA_LONXX = 'D'      */
/*			AND LNXX.LC_SST_LONXX = 'X'*/
/*			AND LNXX.LC_RPR_TYP IS NULL*/
/*			AND LNXX.LD_LON_RHB_PCV IS NOT NULL*/
			DAYS(CURRENT DATE) - DAYS(LNXX.LD_DLQ_OCC) > XXX
			AND LNXX.LC_STA_LONXX = 'X'
);

DISCONNECT FROM DBX;

/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>> ;  ** INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK;*/
QUIT;
ENDRSUBMIT;

DATA FINAL (DROP=LN_SEQ);
SET LEGEND.FINAL;
RUN;

/*export to Excel spreadsheet*/
PROC EXPORT DATA= WORK.FINAL 
            OUTFILE= "T:\SAS\NHXXXX_&sysdate..xls" 
            DBMS=EXCEL REPLACE;
     SHEET="A"; 
RUN;
