

LIBNAME  LEGEND  REMOTE  SERVER=LEGEND SLIBREF=work  ;
RSUBMIT LEGEND;
/*%let DB = DNFPRQUT;  *This is test;*/
/*%let DB = DNFPRUUT;  *This is VUKX test;*/
%let DB = DNFPUTDL;  *This is live;

LIBNAME PKUB DBX DATABASE=&DB OWNER=PKUB;

PROC SQL;
	CONNECT TO DBX (DATABASE=&DB);

	CREATE TABLE POP AS
		SELECT	
			*
		FROM	
			CONNECTION TO DBX 
				(
					SELECT DISTINCT
						PDXX.DF_SPE_ACC_ID,
						LNXX.LN_SEQ,
						LNXX.LA_CUR_PRI,
						LNXX.PC_FAT_TYP,
						LNXX.PC_FAT_SUB_TYP
					FROM
						PKUB.LNXX_LON LNXX
					INNER JOIN PKUB.PDXX_PRS_NME PDXX
						ON PDXX.DF_PRS_ID = LNXX.BF_SSN
					INNER JOIN PKUB.LNXX_FIN_ATY LNXX
						ON LNXX.BF_SSN = LNXX.BF_SSN
						AND LNXX.LN_SEQ = LNXX.LN_SEQ
						AND LNXX.LC_FAT_REV_REA = ''
						AND LNXX.LC_STA_LONXX = 'A'
							
					WHERE
						LNXX.LC_STA_LONXX = 'R'
						AND LNXX.IC_LON_PGM IN ('DLPLUS', 'DLPLGB', 'DLSTFD', 'DLUNST')
						AND (
								(LNXX.PC_FAT_TYP = 'XX' AND LNXX.PC_FAT_SUB_TYP IN ('XX', 'XX'))
								OR
								(LNXX.PC_FAT_TYP = 'XX' AND LNXX.PC_FAT_SUB_TYP = 'XX')
								OR
								(LNXX.PC_FAT_TYP = 'XX' AND LNXX.PC_FAT_SUB_TYP = 'XX')
							)
				)
	;

	CREATE TABLE POP_DECONVERTED AS
		SELECT	
			*
		FROM	
			CONNECTION TO DBX 
				(
					SELECT DISTINCT
						PDXX.DF_SPE_ACC_ID,
						LNXX.LN_SEQ,
						LNXX.LA_CUR_PRI,
						LNXX.PC_FAT_TYP,
						LNXX.PC_FAT_SUB_TYP
					FROM
						PKUB.LNXX_LON LNXX
					INNER JOIN PKUB.PDXX_PRS_NME PDXX
						ON PDXX.DF_PRS_ID = LNXX.BF_SSN
					INNER JOIN PKUB.LNXX_FIN_ATY LNXX
						ON LNXX.BF_SSN = LNXX.BF_SSN
						AND LNXX.LN_SEQ = LNXX.LN_SEQ
						AND LNXX.LC_FAT_REV_REA = ''
						AND LNXX.LC_STA_LONXX = 'A'
							
					WHERE
						LNXX.LC_STA_LONXX = 'D'
						AND LNXX.IC_LON_PGM IN ('DLPLUS', 'DLPLGB', 'DLSTFD', 'DLUNST')
						AND (
								
								(LNXX.PC_FAT_TYP = 'XX' AND LNXX.PC_FAT_SUB_TYP IN ('XX','XX'))
								
							)
							);

	DISCONNECT FROM DBX;


QUIT;

ENDRSUBMIT;

PROC EXPORT DATA = LEGEND.POP 
            OUTFILE = "T:\SAS\NH XXXX.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="Released"; 
RUN;

PROC EXPORT DATA = LEGEND.POP_DECONVERTED 
            OUTFILE = "T:\SAS\NH XXXX.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="Deconverted"; 
RUN;
