SELECT DISTINCT
	PDXX.DF_SPE_ACC_ID,
	RMXX.LD_PAY,
	RMXX.BA_PAY
FROM
	CDW..CS_TransferX T
	INNER JOIN CDW..RMXX_ONL_PAY RMXX
		ON RMXX.BF_SSN = T.BF_SSN
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = T.BF_SSN
WHERE 
	RMXX.LD_PAY > CAST(GETDATE() AS DATE)	
ORDER BY
	RMXX.LD_PAY
