LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPRQUT OWNER=PKUB;
PROC SQL;
	CREATE TABLE ADXX AS
		SELECT
			ADXX.BF_SSN,
			CATS(FSXX.LF_FED_AWD,PUT(FSXX.LN_FED_AWD_SEQ,ZX.)) AS AWARDID,
			ADXX.LN_BR_DSB_SEQ,
			ADXX.LA_FAT_ADJ_CUR_PRI,
			ADXX.LD_FAT_ADJ_REQ_BEG,
			ADXX.PC_FAT_TYP,
			ADXX.PC_FAT_SUB_TYP
		FROM
			PKUB.ADXX_PCV_ATY_ADJ ADXX
			JOIN PKUB.FSXX_DL_LON FSXX
				ON ADXX.BF_SSN = FSXX.BF_SSN
				AND ADXX.LN_SEQ = FSXX.LN_SEQ
		WHERE
			ADXX.LC_TYP_FAT_ADJ_REQ = 'XX'
	;
QUIT;
ENDRSUBMIT;

PROC EXPORT
		DATA=LEGEND.ADXX
		OUTFILE='T:\Query Needed for COD IST Testing.XLSX'
		REPLACE;
RUN;
