SELECT DISTINCT
	AYXX.BF_SSN,
	ayXX.LF_USR_REQ_ATY,
	ayXX.LX_ATY
FROM 
	CDW..AYXX_BR_LON_ATY AYXX
	LEFT JOIN CDW..AYXX_ATY_TXT AYXX
		ON AYXX.BF_SSN = AYXX.BF_SSN
		AND AYXX.LN_ATY_SEQ = AYXX.LN_ATY_SEQ

WHERE
	PF_REQ_ACT = 'CVDOO'
	AND LC_STA_ACTYXX = 'A'

SELECT DISTINCT
AYXX.BF_SSN,
STUFF(
(
	SELECT 
			' ' + SUB.LX_ATY AS [text()]
	FROM 
		CDW..AYXX_ATY_TXT SUB
		
	WHERE
		SUB.BF_SSN = AYXX.BF_SSN
		AND SUB.LN_ATY_SEQ = AYXX.LN_ATY_SEQ
FOR XML PATH('')
)
,X,X, '') AS LX_ATY
		
FROM	
CDW..AYXX_BR_LON_ATY AYXX
left JOIN CDW..AYXX_ATY_TXT AYXX
	ON AYXX.BF_SSN = AYXX.BF_SSN
	AND AYXX.LN_ATY_SEQ = AYXX.LN_ATY_SEQ

WHERE
AYXX.PF_REQ_ACT = 'CVDOO'
AND AYXX.LC_STA_ACTYXX = 'A'
AND AYXX.LX_ATY like '%OPT%'