USE CDW	
GO	
	
DECLARE @StartDate DATE = 'XXXX-X-X'	
DECLARE @EndDate DATE = 'XXXX-XX-XX'

--code definitions
DECLARE @PC_FAT_TYPES TABLE (CODE VARCHAR(X),PC_FAT_TYP_DEFINE VARCHAR(XX))
INSERT INTO @PC_FAT_TYPES (CODE, PC_FAT_TYP_DEFINE)
VALUES
 ('XX', 'PRECONVERSION START UP INDICATOR')
,('XX', 'DISBURSEMENT DATA CHANGE')
,('XX', 'CONVERSION')
,('XX', 'TRANSFER')
,('XX', 'DECONVERSION')
,('XX', 'REALLOCATION')
,('XX', 'OLD SYSTEM SCHOOL REFUND')
,('XX', 'OLD SYSTEM RETURNED DISBURSEMENT')
,('XX', 'PAYMENT')
,('XX', 'XXXX WINDFALL PROFIT ADJUSTMENT')
,('XX', 'XXXX WINDFALL PROFIT ADJUSTMENT')
,('XX', 'ORIGINATION FEE CREDIT-RIR')
,('XX', 'ORGINATION FEE CREDIT RIR')
,('XX', 'INSURANCE FEE CREDIT')
,('XX', 'GUARANTY FEE CREDIT RIR')
,('XX', 'RIR REBATE')
,('XX', 'OFF SETTING REFUND')
,('XX', 'REFUND')
,('XX', 'LATE FEE')
,('XX', 'PRE-CLAIM FEE')
,('XX', 'SUPPLEMENTAL FEE')
,('XX', 'SUPPLEMENTAL ORIGINATION FEE')
,('XX', 'CREDIT LIFE FEE')
,('XX', 'SUPPLEMENTAL FEE REPAY')
,('XX', 'REINSURANCE REBATE')
,('XX', 'POST FINAL DISBURSEMENT FEE')
,('XX', 'INELIGIBLE PRINCIPAL')
,('XX', 'WRITE OFF')
,('XX', 'INTEREST WRITE-OFF-RIR')
,('XX', 'CHARGE OFF')
,('XX', 'WRITE UP')
,('XX', 'BBS WRITE-UP')
,('XX', 'CAPITALIZATION')
,('XX', 'PRE-CONVERSION ADJUSTMENT')
,('XX', 'NON-SUBSIDIZED INTEREST ACCRUAL')
,('XX', 'PRIOR PERIOD ADJUSTMENT')


DECLARE @PC_FAT_SUB_TYPES TABLE (CODE VARCHAR(X),PC_FAT_SUB_TYP_DEFINE VARCHAR(XX))
INSERT INTO @PC_FAT_SUB_TYPES (CODE, PC_FAT_SUB_TYP_DEFINE)
VALUES
 ('XX', 'PRECONVERSION START UP')
,('XX', 'AUTOMATIC')
,('XX', 'MANUAL REQUEST')
,('XX', 'AUTOMATIC (SYSTEM GENERATED)')
,('XX', 'AUTOMATIC (DEFAULTED ACCOUNT)')
,('XX', 'OWNER LIABILITY')
,('XX', 'AUTOMATIC TAXABLE')
,('XX', 'AUTOMATIC NON-TAXABLE')
,('XX', 'AUTOMATIC TAXABLE')
,('XX', 'BORROWER')
,('XXXX', 'TIMELY PAYMENT ORIGINATION FEE CREDIT')
,('XXXX', 'PLUS INTEREST CREDIT BORROWER BENEFIT')
,('XX', 'BORROWER (INTEREST ONLY)')
,('XX', 'BORROWER (PRINCIPAL ONLY)')
,('XX', 'COSIGNER')
,('XX', 'COSIGNER (INTEREST ONLY)')
,('XX', 'COSIGNER (PRINCIPAL ONLY)')
,('XX', 'BORROWER BEHALF')
,('XX', 'BORROWER BEHALF (INTEREST ONLY)')
,('XX', 'BORROWER BEHALF (PRINCIPAL ONLY)')
,('XX', 'OWNER')
,('XX', 'OWNER (INTEREST ONLY)')
,('XX', 'OWNER (PRINCIPAL ONLY)')
,('XX', 'TIMELY PAYMENT ORIGINATION FEE CREDIT')
,('XX', 'PLUS INTEREST CREDIT BORROWER BENEFIT')
,('XX', 'GUARANTOR')
,('XX', 'GUARANTOR INTEREST ONLY')
,('XX', 'GUARANTOR PRINCIPAL ONLY')
,('XX', 'TIMELY PAYMENT ORIGINATION FEE CREDIT')
,('XX', 'FEDERAL GOVERNMENT')
,('XX', 'GOVERNMENT PAYMENT')
,('XX', 'GOVERNMENT INTEREST')
,('XX', 'BB APPLIED OTHER LOAN PRINCIPAL ONLY')
,('XX', 'BB APPLIED OTHER LN INTEREST/PRINCIPAL')
,('XX', 'SCHOOL REFUND')
,('XX', 'BORROWER-CANCEL')
,('XX', 'SUB-UNSUB CHANGE')
,('XX', 'RETURNED DISBURSEMENT')
,('XX', 'DISB ERROR FIN TRANS SUB TYPE - LO CNCL')
,('XX', 'DISB ERROR FIN TRANS SUB TYPE-NO LO CNCL')
,('XX', 'REALLOCATIONS')
,('XX', 'PARTIAL CANCELLATION')
,('XX', 'FORGIVENESS')
,('XX', 'TILP STATE OFFSET PAYMENT')
,('XX', 'TILP TEACHING CREDIT')
,('XX', 'COLLECTION AGENCY')
,('XX', 'REMITTANCE REFUND REVERSAL-INCOR AMOUNT')
,('XX', 'REMITTANCE REFUND REVERSAL-INCOR PAYEE')
,('XX', 'REMT RFND REV-INCOR TRAN TYPE/SUB TYPE')
,('XX', 'REMT RFND REV-ADJUST MADE/POSTING ERROR')
,('XX', 'REMITTANCE FOR REFUND REVERSAL-OTHER')
,('XX', 'CONSOLIDATION (NON-NETWORK)')
,('XX', 'NON-NETWORK CONSOLIDATION LATE FEE')
,('XX', 'CONSOLIDATION (NETWORK)')
,('XX', 'NETWORK CONSOLIDATION LATE FEE')
,('XX', 'INCREASE')
,('XX', 'DECREASE')
,('XX', 'PURCHASE')
,('XX', 'NON-PURCHASE')
,('XX', 'SALE')
,('XX', 'NON-SALE')
,('XX', 'PAID RE-SALE')


--query
SELECT
	LNXX.BF_SSN,
	LNXX.LN_SEQ,
	--LNXX.LN_FAT_SEQ,
	LNXX.PC_FAT_TYP,
	PFT.PC_FAT_TYP_DEFINE,
	LNXX.PC_FAT_SUB_TYP,
	PFST.PC_FAT_SUB_TYP_DEFINE,
	COALESCE(LNXXX.LD_FAT_APL, LNXX.LD_FAT_APL) [LD_FAT_APL],
	LNXX.LA_FAT_CUR_PRI,
	LNXX.LA_FAT_NSI,
	LNXX.LC_FAT_REV_REA
	--LNXX.LD_FAT_PST,
	--LNXX.LN_FAT_SEQ_REV
FROM	
	CDW..LNXX_FIN_ATY LNXX
	LEFT JOIN CDW..LNXX_FIN_ATY LNXXX
		ON LNXXX.BF_SSN  = LNXX.BF_SSN
		AND LNXXX.LN_SEQ = LNXX.LN_SEQ
		AND LNXXX.LN_FAT_SEQ = LNXX.LN_FAT_SEQ_REV
		AND LNXXX.LD_FAT_APL BETWEEN @StartDate AND @EndDate
	LEFT JOIN @PC_FAT_TYPES PFT
		ON LNXX.PC_FAT_TYP = PFT.CODE
	LEFT JOIN @PC_FAT_SUB_TYPES PFST
		ON LNXX.PC_FAT_SUB_TYP = PFST.CODE
WHERE	
	LNXX.PC_FAT_TYP = 'XX'
	AND 
	LNXX.PC_FAT_SUB_TYP IN ('XX','XX')
	AND 
	LNXX.LC_FAT_REV_REA != ''	
	AND	
	LNXX.LC_FAT_REV_REA IS NOT NULL
	AND 
	LNXX.LD_FAT_APL BETWEEN @StartDate AND @EndDate
	AND 
	LNXXX.LD_FAT_APL BETWEEN  @StartDate AND @EndDate