SELECT * FROM OPENQUERY(LEGEND, 'SELECT * FROM PKUB.LPXX_DD_ACT_STA')
SELECT * FROM OPENQUERY(LEGEND, 'SELECT * FROM PKUB.LPXX_DD_ACT_WDO')
SELECT * FROM OPENQUERY(LEGEND, 'SELECT * FROM PKUB.LPXX_DD_ACT_STE')