USE CDW
GO
--T:\Consol precon\NAtoCSTLCXXXXXXXX_X.xlsx                                                           
SELECT DISTINCT
	PDXX.DF_PRS_ID,
	LTRIM(RTRIM(PDXX.DM_PRS_X)) + ' ' + LTRIM(RTRIM(PDXX.DM_PRS_LST)) AS [NAME],
	cnh.CONFRIMATION_DATE,
	CNH.[CONSOLIDATION LOAN ID_(AWARD ID)] AS AWARD_ID,
	LNXX.IC_LON_PGM AS LOAN_PROGRAM,
	LD_DSB AS DSB_DATE,
	LNXX.LA_DSB AS DSB_AMOUNT,
	LNXX.LA_CUR_PRI AS CURRENT_BALANCE,
	LNXX.LN_SEQ AS LOAN_SEQ,
	CASE WHEN ACH.BF_SSN IS NOT NULL THEN 'Y' ELSE 'N' END AS ON_ACH,
	LNXX.LR_INT_RDC_PGM_ORG as system_rate,
	cast((cnh.Interst_rate_from_file * XXX) as numeric(XX,X)) as file_rate,
	CASE WHEN LNXX.LR_INT_RDC_PGM_ORG != cast((cnh.Interst_rate_from_file * XXX) as numeric(XX,X)) THEN X ELSE X END AS RATE_MATCHES,
	cnh.FileName
FROM
	CDW..[CNH XXXXX] CNH
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = RIGHT('XXXXXXXX' + LTRIM(RTRIM(STR(SSSN))),  X)
	INNER JOIN  CDW..FSXX_DL_LON FSXX
		ON FSXX.BF_SSN = PDXX.DF_PRS_ID
		AND FSXX.LF_FED_AWD = SUBSTRING(LTRIM(RTRIM(CNH.[CONSOLIDATION LOAN ID_(AWARD ID)])),X,XX)
		AND FSXX.LN_FED_AWD_SEQ = CAST(SUBSTRING(LTRIM(RTRIM(CNH.[CONSOLIDATION LOAN ID_(AWARD ID)])), XX,X) AS INT)
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = FSXX.BF_SSN
		AND LNXX.LN_SEQ = FSXX.LN_SEQ
	INNER JOIN CDW..LNXX_DSB LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
	INNER JOIN
	(
		SELECT
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			LNXX.LR_ITR,
			LR_INT_RDC_PGM_ORG,
			ROW_NUMBER() OVER (PARTITION BY LNXX.BF_SSN, LNXX.LN_SEQ ORDER BY LD_STA_LONXX DESC) AS SEQ
		FROM
			LNXX_INT_RTE_HST LNXX
		WHERE
			LNXX.LC_STA_LONXX = 'A'
			AND CAST(GETDATE() AS DATE) BETWEEN LNXX.LD_ITR_EFF_BEG AND LNXX.LD_ITR_EFF_END
	) LNXX 
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
		AND LNXX.SEQ = X
	LEFT JOIN
	(
		SELECT	
			LNXX.BF_SSN,
			LNXX.LN_SEQ
		FROM
			CDW..BRXX_BR_EFT BRXX
			INNER JOIN CDW..LNXX_EFT_TO_LON LNXX
				ON LNXX.BF_SSN = BRXX.BF_SSN
				AND LNXX.BN_EFT_SEQ = BRXX.BN_EFT_SEQ
		WHERE
			BRXX.BC_EFT_STA = 'A'
	) ACH
		ON ACH.BF_SSN = LNXX.BF_SSN
		AND ACH.LN_SEQ = LNXX.LN_SEQ
                                                          