USE CDW
GO






SELECT DISTINCT
	PD10.DF_SPE_ACC_ID AS ACCOUNT_NUMBER,
	LD_ATY_RSP AS DATE_CLOSED,
	LF_PRF_BY AS UT#

FROM
	CDW..AY10_BR_LON_ATY AY10
	INNER JOIN CDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = AY10.BF_SSN
WHERE
	PF_REQ_ACT = 'CRDSP'
	AND PF_RSP_ACT = 'COMPL'
	AND LD_ATY_RSP BETWEEN '07/01/2020' AND '07/31/2020'

