/*set up library to SQL Server and include common code*/
	LIBNAME SQL ODBC REQUIRED="FILEDSN=X:\PADR\ODBC\CLS.dsn; bl_keepnulls=no; READ_ISOLATION_LEVEL=RU" SCHEMA= dbo;
	LIBNAME CDW ODBC REQUIRED="FILEDSN=X:\PADR\ODBC\CDW.dsn; bl_keepnulls=no; READ_ISOLATION_LEVEL=RU" SCHEMA= dbo;
	%INCLUDE "Y:\Codebase\SAS\ArcAdd Common.SAS";

/*begin job specific code*/
;
%LET RPTLIB = T:\;
%LET INPUTFILE = SCRA_X_X_UNWSXX.NWSXXRX._XXXV._XXXXXX June.txt;
/*%LET RPTLIB = T:\;*/
/*%LET INPUTFILE = RESULTS-Identifying Active Duty Military Borrowers--FED--NEWRX.txt;*/

LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;


DATA DODZ;
	INFILE "&RPTLIB\&INPUTFILE";
	INPUT SSN $ X-X ACT_DUT_BEG $ XXX-XXX ACT_DUT_END $ XXX-XXX LC_ACT_DUT $ XXX LC_LFT_ACT_DUT $ XXX LC_NTF_ACT_DUT $ XXX EID_BEGIN_DATE $ XXX-XXX; 

	FORMAT LD_ACT_DUT_BEG LD_ACT_DUT_END LD_EID_BEGIN_DATE MMDDYYXX.;

	IF ACT_DUT_BEG NE 'XXXXXXXX' THEN LD_ACT_DUT_BEG = INPUT(ACT_DUT_BEG, YYMMDDX.);
	IF ACT_DUT_END NE 'XXXXXXXX' THEN LD_ACT_DUT_END = INPUT(ACT_DUT_END, YYMMDDX.);
	IF EID_BEGIN_DATE NE 'XXXXXXXX' THEN LD_EID_BEGIN_DATE = INPUT(EID_BEGIN_DATE, YYMMDDX.);
RUN;

DATA DOD;
	SET DODZ;
	WHERE 
		LC_ACT_DUT ='Z' 
		OR (
			LC_ACT_DUT ='N' 
			AND LC_LFT_ACT_DUT ='N'
			AND LC_NTF_ACT_DUT ='N'
			);
RUN;

DATA LEGEND.DOD; SET DOD; RUN;

RSUBMIT;
/*%LET DB = DNFPRQUT;  *This is test;*/
/*%let DB = DNFPRUUT;  *This is VUKX test;*/
%let DB = DNFPUTDL;  *This is live;

LIBNAME PKUB DBX DATABASE=&DB OWNER=PKUB;

PROC SQL;
	CREATE TABLE ISCRAMISSING AS
	SELECT 
		*
	FROM
		WORK.DOD 
		INNER JOIN PKUB.AYXX_BR_LON_ATY AYXX
		ON AYXX.BF_SSN = DOD.SSN
		AND AYXX.PF_REQ_ACT = 'ASCRA'
		AND AYXX.LC_STA_ACTYXX = 'A'
		LEFT JOIN (
					SELECT 
						AYXXI.BF_SSN,
						AYXXI.PF_REQ_ACT,
						AYXXI.LN_ATY_SEQ
					FROM
						PKUB.AYXX_BR_LON_ATY AYXXI
					WHERE
						AYXXI.PF_REQ_ACT = 'ISCRA'	
					) ISCRA
					ON ISCRA.BF_SSN = AYXX.BF_SSN
					AND ISCRA.LN_ATY_SEQ > AYXX.LN_ATY_SEQ
	WHERE
		ISCRA.BF_SSN IS NULL;
QUIT;
ENDRSUBMIT;

DATA ISCRAMISSING; SET LEGEND.ISCRAMISSING; RUN;

PROC SQL;

INSERT INTO	SQL.ARCADDPROCESSING(ARCTYPEID,ACCOUNTNUMBER,RECIPIENTID,ARC,SCRIPTID,PROCESSON,COMMENT,ISREFERENCE,ISENDORSER,CREATEDAT,CREATEDBY)
(
	SELECT
		X,
		PDXX.DF_SPE_ACC_ID,
		'',
		'ISCRA',
		'UTNWSXX',
		TODAY() *XXXXX, 
		'Active duty status ended',
		X,
		X,
		TODAY() *XXXXX,
		'SCRAFED'
	FROM
		ISCRAMISSING I
		INNER JOIN CDW.PDXX_Borrower PDXX
		ON I.BF_SSN = PDXX.BF_SSN
	WHERE
		I.BF_SSN NOT IN('XXXXXXXXX','XXXXXXXXX','XXXXXXXXX','XXXXXXXXX')
);
QUIT;



PROC EXPORT DATA = WORK.ISCRAMISSING 
            OUTFILE = "T:\ISCRAMISSING.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="SHEETX"; 
RUN;
