LIBNAME XL 'T:\OBOB-XXX Cornerstone.xlsx';
DATA XLSOURCE (RENAME=(_LN_SEQ = LN_SEQ _WN_SEQ_GRXX = WN_SEQ_GRXX));
	SET XL.'SheetX$'N;
	_LN_SEQ = INPUT(LN_SEQ, X.);
	_WN_SEQ_GRXX = INPUT(WN_SEQ_GRXX, X.);
	DROP LN_SEQ WN_SEQ_GRXX;
RUN;
LIBNAME XL CLEAR;

LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
DATA LEGEND.XLSOURCE;
	SET XLSOURCE;
RUN;

RSUBMIT LEGEND;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
	CREATE TABLE GRXX AS
		SELECT 
			XL.BF_SSN,
			XL.LN_SEQ,
			XL.WN_SEQ_GRXX,
			GRXX.WC_NDS_LN_STA_RPT 
		FROM
			XLSOURCE XL
			INNER JOIN PKUB.GRXX_RPT_LON_APL GRXX
				ON XL.BF_SSN = GRXX.BF_SSN
				AND XL.LN_SEQ = GRXX.LN_SEQ
				AND XL.WN_SEQ_GRXX = GRXX.WN_SEQ_GRXX
		ORDER BY
			XL.BF_SSN,
			XL.LN_SEQ,
			XL.WN_SEQ_GRXX
;QUIT;
ENDRSUBMIT;

PROC EXPORT
		DATA=LEGEND.GRXX
		OUTFILE='T:\SAS\CNH XXXXX.xlsx'
		REPLACE;
RUN;	
