LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
	CREATE TABLE RPS AS
		SELECT DISTINCT
			LNXX.BF_SSN,
			DAY(RSXX.LD_RPS_X_PAY_DU) AS PMT_DUE
		FROM
			PKUB.LNXX_LON LNXX
			INNER JOIN PKUB.LNXX_LON_RPS LNXX
				ON LNXX.BF_SSN = LNXX.BF_SSN
				AND LNXX.LN_SEQ = LNXX.LN_SEQ
				AND LNXX.LC_STA_LONXX = 'A'
			INNER JOIN PKUB.RSXX_BR_RPD RSXX
				ON LNXX.BF_SSN = RSXX.BF_SSN
				AND LNXX.LN_RPS_SEQ = RSXX.LN_RPS_SEQ
				AND RSXX.LC_STA_RPSTXX = 'A'
			LEFT JOIN
				(
					SELECT
						LNXX.BF_SSN,
						LNXX.LN_SEQ
					FROM
						PKUB.DFXX_BR_DFR_REQ DFXX
						INNER JOIN PKUB.LNXX_BR_DFR_APV LNXX
							ON DFXX.BF_SSN = LNXX.BF_SSN
							AND DFXX.LF_DFR_CTL_NUM = LNXX.LF_DFR_CTL_NUM
					WHERE
						DFXX.LC_DFR_STA = 'A'
						AND DFXX.LC_STA_DFRXX = 'A'
						AND LNXX.LC_STA_LONXX = 'A'
						AND TODAY() BETWEEN LNXX.LD_DFR_BEG AND LNXX.LD_DFR_END
				) DEFR
				ON LNXX.BF_SSN = DEFR.BF_SSN
				AND LNXX.LN_SEQ = DEFR.LN_SEQ
			LEFT JOIN
				(
					SELECT
						LNXX.BF_SSN,
						LNXX.LN_SEQ
					FROM
						PKUB.FBXX_BR_FOR_REQ FBXX
						INNER JOIN PKUB.LNXX_BR_FOR_APV LNXX
							ON FBXX.BF_SSN = LNXX.BF_SSN
							AND FBXX.LF_FOR_CTL_NUM = LNXX.LF_FOR_CTL_NUM
					WHERE
						FBXX.LC_FOR_STA = 'A'
						AND FBXX.LC_STA_FORXX = 'A'
						AND LNXX.LC_STA_LONXX = 'A'
						AND TODAY() BETWEEN LNXX.LD_FOR_BEG AND LNXX.LD_FOR_END
				) FORB
				ON LNXX.BF_SSN = FORB.BF_SSN
				AND LNXX.LN_SEQ = FORB.LN_SEQ
		WHERE
			LNXX.LA_CUR_PRI > X
			AND LNXX.LC_STA_LONXX = 'R'	
			AND DEFR.BF_SSN IS NULL
			AND FORB.BF_SSN IS NULL
	;

	CREATE TABLE BRWS AS
		SELECT
			'Total Number of Borrowers' AS DESCRIPTION,
			COUNT(DISTINCT BF_SSN) AS BORROWERS
		FROM
			RPS
	;
QUIT;
ENDRSUBMIT;

DATA RPS; 
	SET LEGEND.RPS;
RUN;

PROC SQL;
	CREATE TABLE TOTAL AS
		SELECT
			'Total Number of Borrowers' AS DESCRIPTION,
			COUNT(DISTINCT BF_SSN) AS BORROWERS
		FROM
			RPS
	;

	CREATE TABLE FIFTEENTH AS
		SELECT
			'Payment Due XXth - XXst' AS DESCRIPTION,
			COUNT(DISTINCT BF_SSN) AS BORROWERS
		FROM
			RPS
		WHERE
			PMT_DUE BETWEEN XX AND XX
	;

	CREATE TABLE TWENTYSECOND AS
		SELECT
			'Payment Due XXnd - XXth' AS DESCRIPTION,
			COUNT(DISTINCT BF_SSN) AS BORROWERS
		FROM
			RPS
		WHERE
			PMT_DUE BETWEEN XX AND XX
	;
QUIT;

DATA ANSWERS;
	SET TOTAL 
		FIFTEENTH 
		TWENTYSECOND
	;
RUN;

PROC EXPORT
		DATA=ANSWERS
		OUTFILE='T:\FSA Question about payment due dates.XLSX'
		REPLACE;
RUN;

PROC EXPORT
		DATA=RPS
		OUTFILE='T:\FSA Question about payment due dates.XLSX'
		REPLACE;
RUN;
