LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME PKUB DBX DATABASE=DNFPUTDL OWNER=PKUB;
PROC SQL;
	CREATE TABLE SCRA AS
		SELECT
			LNXX.BF_SSN,
			PDXX.DM_PRS_LST,
			LNXX.LN_SEQ,
			LNXX.LR_ITR,
			LNXX.LC_INT_RDC_PGM,
			LNXX.LD_CRT_LONXX,
			LNXX.LD_ITR_APL,
			LNXX.LD_ITR_EFF_BEG,
			LNXX.LD_ITR_EFF_END
		FROM
			PKUB.PDXX_PRS_NME PDXX
			JOIN PKUB.LNXX_INT_RTE_HST LNXX
				ON PDXX.DF_PRS_ID = LNXX.BF_SSN
		WHERE
			PDXX.DF_SPE_ACC_ID IN ('XXXXXXXXXX')
			AND LNXX.LC_INT_RDC_PGM IN ('M','P')
	;
QUIT;
ENDRSUBMIT;

PROC EXPORT
		DATA=LEGEND.SCRA
		OUTFILE='T:\NH XXXX.XLSX'
		REPLACE;
RUN;
