USE CDW
GO

DROP TABLE IF EXISTS #DATA;

WITH PHN
AS
(
SELECT
	DF_PRS_ID,
	DF_SPE_ACC_ID,
	PHN,
	DF_LST_DTS_PDXX,
	NEXT_DATE,
	MAX(CONSENT) AS CONSENT
FROM
(
SELECT DISTINCT
	PDXX.DF_PRS_ID,
	PDXX.DF_SPE_ACC_ID,
	DN_DOM_PHN_ARA_HST + DN_DOM_PHN_XCH_HST + DN_DOM_PHN_LCL_HST AS PHN,
	DF_LST_DTS_PDXX,
	LEAD(DF_LST_DTS_PDXX, X) OVER (PARTITION BY PDXX.DF_PRS_ID, PDXX.DC_PHN_HST ORDER BY DN_PHN_SEQ) AS NEXT_DATE,
	CASE WHEN DC_ALW_ADL_PHN_HST IN ('L','P', 'X') THEN X ELSE X END AS CONSENT
FROM
	CDW..PDXX_PHN_HST PDXX
	INNER JOIN 
	(
		SELECT DISTINCT
			BF_SSN
		FROM
			CDW..LNXX_LON_DLQ_HST
	) LNXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = PDXX.DF_PRS_ID

WHERE PDXX.DF_SPE_ACC_ID = 'XXXXXXXXXX'

UNION ALL
	
SELECT DISTINCT
	PDXX.DF_PRS_ID,
	PDXX.DF_SPE_ACC_ID,
	DN_DOM_PHN_ARA + DN_DOM_PHN_XCH + DN_DOM_PHN_LCL AS PHN,
	PDXX.DF_LST_DTS_PDXX,
	GETDATE() AS NEXT_DATE,
	CASE WHEN DC_ALW_ADL_PHN IN ('L','P', 'X') THEN X ELSE X END AS CONSENT
FROM
	CDW..PDXX_PRS_PHN PDXX
	INNER JOIN 
	(
		SELECT DISTINCT
			BF_SSN
		FROM
			CDW..LNXX_LON_DLQ_HST
	) LNXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = PDXX.DF_PRS_ID
	
WHERE PDXX.DF_SPE_ACC_ID = 'XXXXXXXXXX'
) POP
GROUP BY
	DF_PRS_ID,
	DF_SPE_ACC_ID,
	PHN,
	DF_LST_DTS_PDXX,
	NEXT_DATE
)
SELECT
	*,
	ISNULL(NEXT_DATE, CASE WHEN NEXT_DATE IS NULL THEN MAX(DF_LST_DTS_PDXX) OVER (PARTITION BY DF_PRS_ID) END) AS FINAL_HST 
INTO #DATA
FROM 
	PHN P
;

SELECT DISTINCT
	--pop.DF_PRS_ID,
	--POP.DF_SPE_ACC_ID AS ACCOUNT_NUMBER,
	--POP.PHN AS PHONE_NUMBER,
	--MIN(POP.ActivityDate) AS FIRST_CALL,
	--MAX(POP.ActivityDate) AS LAST_CALL,
	--MAX(CONSENT) AS CONSENT,
	--COUNT(*) AS NUMBER_OF_CALLS
	POP.*
FROM
(
SELECT DISTINCT
	*
FROM 
	#DATA D
	INNER JOIN NobleCalls..NobleCallHistory NCH
		ON NCH.AccountIdentifier = D.DF_PRS_ID
		AND NCH.PhoneNumber = D.PHN
		AND NCH.ActivityDate BETWEEN D.DF_LST_DTS_PDXX AND D.FINAL_HST
WHERE
	NCH.CallCampaign IN ('XXX','CLST','CBST')

UNION ALL

SELECT DISTINCT
	*
FROM 
	#DATA D
	INNER JOIN NobleCalls..NobleCallHistory NCH
		ON NCH.AccountIdentifier = D.DF_SPE_ACC_ID
		AND NCH.PhoneNumber = D.PHN
		AND NCH.ActivityDate BETWEEN D.DF_LST_DTS_PDXX AND D.FINAL_HST
WHERE
	NCH.CallCampaign IN ('XXX','CLST','CBST')
) POP
--GROUP BY
--	--pop.DF_PRS_ID,
--	POP.DF_SPE_ACC_ID,
--	POP.PHN
--HAVING 
--	MAX(CONSENT) != X
WHERE CONSENT = X
