USE CDW
GO

SELECT DISTINCT
	--PDXX.DF_SPE_ACC_ID,
	--GRXX.LN_SEQ
	GRXX.*
FROM	
	CDW..GRXX_RPT_LON_APL GRXX
	INNER JOIN CDW..PDXX_PRS_NME PDXX
		ON PDXX.DF_PRS_ID = GRXX.BF_SSN
	INNER JOIN CDW..LNXX_LON LNXX
		ON LNXX.BF_SSN = GRXX.BF_SSN
		AND LNXX.LN_SEQ = GRXX.LN_SEQ
WHERE
	GRXX.WC_NDS_RPT_STA = 'C'
	AND LNXX.LA_CUR_PRI > X