SELECT 
	DF_SPE_ACC_ID,
	LN_SEQ,
	IC_LON_PGM
FROM 
	CDW..PD30_PRS_ADR PD30
	INNER JOIN CDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = PD30.DF_PRS_ID
	INNER JOIN CDW..LN10_LON LN10
		ON LN10.BF_SSN = PD30.DF_PRS_ID

WHERE 
	DC_DOM_ST = 'MO'
	AND LC_STA_LON10 = 'R'
	AND LA_CUR_PRI > 0
	AND DI_VLD_ADR = 'Y'