select distinct
	LNXX.IC_LON_PGM,
	LNXX.LR_ITR,
	COUNT(DISTINCT BF_SSN) AS BORROWER_COUNT,
	COUNT(*) AS LOAN_COUNT
from
(
	SELECT
		LNXX.BF_SSN,
		LNXX.LN_SEQ,
		LNXX.LR_ITR,
		LNXX.IC_LON_PGM,
		ROW_NUMBER() OVER (PARTITION BY LNXX.BF_SSN, LNXX.LN_SEQ ORDER BY LD_STA_LONXX DESC) AS SEQ
	FROM
		LNXX_INT_RTE_HST LNXX
		INNER JOIN CDW..LNXX_LON LNXX
			ON LNXX.BF_SSN = LNXX.BF_SSN
			AND LNXX.LN_SEQ = LNXX.LN_SEQ
			AND LNXX.LA_CUR_PRI > X
			AND LNXX.LC_STA_LONXX = 'R'
	WHERE
		LNXX.LC_STA_LONXX = 'A'
		AND CAST(GETDATE() AS DATE) BETWEEN LNXX.LD_ITR_EFF_BEG AND LNXX.LD_ITR_EFF_END
) LNXX 
	where LNXX.SEQ = X
GROUP BY
	LNXX.IC_LON_PGM,
	LNXX.LR_ITR