--CNH XXXXX
 
SELECT
	L.*
FROM
	OPENQUERY
	(
		LEGEND,
		'
			SELECT
				LNXX.BF_SSN,
				LNXX.LN_SEQ,
				LNXX.LF_FED_CLC_RSK,
				FRXX.LN_VIT_CHG_HST_SEQ,
				FRXX.LD_LON_X_DSB_OLD,
				FRXX.LD_LON_X_DSB_NEW,
				FRXX.LF_FED_CLC_RSK_OLD,
				FRXX.LF_FED_CLC_RSK_NEW
			FROM
				PKUB.LNXX_LON LNXX
				LEFT JOIN PKUB.FRXX_VIT_CHG_HST FRXX ON FRXX.BF_SSN = LNXX.BF_SSN AND FRXX.LN_SEQ = LNXX.LN_SEQ
			ORDER BY
				LNXX.BF_SSN,
				LNXX.LN_SEQ,
				FRXX.LN_VIT_CHG_HST_SEQ
		'
	) L
	INNER JOIN tempdb..CNHXXXXX CNH ON CNH.SSN = L.BF_SSN AND CNH.Seq = L.LN_SEQ