/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/UNWSXX.NWSXXRZ";
FILENAME REPORTX "&RPTLIB/UNWSXX.NWSXXRX";

LIBNAME  LEGEND  REMOTE  SERVER=LEGEND SLIBREF=work  ;
RSUBMIT LEGEND;
/*%let DB = DNFPRQUT;  *This is test;*/
/*%let DB = DNFPRUUT;  *This is VUKX test;*/
%let DB = DNFPUTDL;  *This is live;

LIBNAME PKUB DBX DATABASE=&DB OWNER=PKUB;

%MACRO SQLCHECK ;
  %IF  &SQLXRC NE X  %THEN  %DO  ;
    DATA _NULL_  ;
            FILE REPORTZ NOTITLES  ;
            PUT @XX " ********************************************************************* "
              / @XX " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
              / @XX " ****  THE SAS SHOULD BE REVIEWED.                                **** "       
              / @XX " ********************************************************************* "
              / @XX " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
              / @XX " ****  &SQLXMSG   **** "
              / @XX " ********************************************************************* "
            ;
         RUN  ;
  %END  ;
%MEND  ;

PROC SQL;
	CREATE TABLE QUERYX AS
		SELECT DISTINCT
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			ABS((LNXX.LA_FAT_NSI + LNXX.LA_FAT_CUR_PRI)) AS LA_FAT_NSI_LA_FAT_CUR_PRI

		FROM
			PKUB.LNXX_FIN_ATY LNXX
		WHERE
			(LNXX.PC_FAT_TYP = 'XX' AND LNXX.PC_FAT_SUB_TYP = 'XX')
			AND LNXX.LD_FAT_EFF BETWEEN INPUT('X/X/XXXX',MMDDYYXX.) and INPUT('X/XX/XXXX',MMDDYYXX.)

;

	/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>> ;  ** INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
	/*%SQLCHECK;*/
QUIT;

PROC SQL;
	CREATE TABLE QUERYX AS 
		SELECT DISTINCT
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			ADXX.LC_WOF_WUP_REA ,
			ABS((LNXX.LA_FAT_NSI + LNXX.LA_FAT_CUR_PRI)) AS LA_FAT_NSI_LA_FAT_CUR_PRI

		FROM
			PKUB.LNXX_FIN_ATY LNXX
			INNER JOIN PKUB.AYXX_BR_LON_ATY AYXX
				ON AYXX.BF_SSN = LNXX.BF_SSN
			INNER JOIN PKUB.ADXX_PCV_ATY_ADJ ADXX
				ON ADXX.BF_SSN = LNXX.BF_SSN
		WHERE
			(LNXX.PC_FAT_TYP = 'XX' AND LNXX.PC_FAT_SUB_TYP = 'XX')
			AND LNXX.LD_FAT_EFF BETWEEN INPUT('X/X/XXXX',MMDDYYXX.) and INPUT('X/XX/XXXX',MMDDYYXX.)
			AND AYXX.PF_REQ_ACT IN ('ADDTH', 'ADCSH', 'ADTLF','ADFCR','ADUPR')
			AND ADXX.LC_WOF_WUP_REA IN ('A','D', 'E', 'F', 'G', 'H', 'I', 'P', 'T', 'V')
;
	CREATE TABLE QUERYX AS 
		SELECT
			LNXX.BF_SSN,
			AYXX.PF_REQ_ACT,
			SUM(LNXX.LA_NSI_OTS + LNXX.LA_CUR_PRI) AS LA_CUR_PRI_LA_NSI_OTS
		FROM
			PKUB.LNXX_LON LNXX
		INNER JOIN PKUB.AYXX_BR_LON_ATY AYXX
			ON AYXX.BF_SSN = LNXX.BF_SSN
		LEFT JOIN QUERYX QX
			ON QX.BF_SSN = LNXX.BF_SSN
		WHERE
			AYXX.PF_REQ_ACT IN ('DITLF','DIUPR','DIFCR','DIDTH','DICSK')
			AND AYXX.LD_ATY_REQ_RCV BETWEEN INPUT('X/X/XXXX',MMDDYYXX.) and INPUT('X/XX/XXXX',MMDDYYXX.)
			AND QX.BF_SSN IS NULL
		GROUP BY
			LNXX.BF_SSN,
			AYXX.PF_REQ_ACT
;
QUIT;

PROC SQL;
	CREATE TABLE QUERYX AS
		SELECT
			LNXX.BF_SSN,
			PDXX.DX_PRS_DSA_TPD_REA,
			SUM(LNXX.LA_NSI_OTS + LNXX.LA_CUR_PRI) AS LA_CUR_PRI_LA_NSI_OTS
		FROM
			PKUB.LNXX_LON LNXX
		INNER JOIN PKUB.PDXX_GTR_DSA PDXX
			ON PDXX.DF_PRS_ID = LNXX.BF_SSN
		INNER JOIN PKUB.PDXX_PRS_DSA PDXX
			ON PDXX.DF_PRS_ID = PDXX.DF_PRS_ID
		WHERE
			PDXX.DC_DSA_STA  IN ('XX','XX', 'X','X')
			AND PDXX.DX_PRS_DSA_TPD_REA  IN ('XXXSUSUP','INDEFSUSP', 'APPREJ')
			AND PDXX.DD_DSA_RPT BETWEEN INPUT('X/X/XXXX',MMDDYYXX.) AND INPUT('X/XX/XXXX',MMDDYYXX.)
			AND PDXX.DD_DSA_RPT BETWEEN INPUT('X/X/XXXX',MMDDYYXX.) AND INPUT('X/XX/XXXX',MMDDYYXX.)
		GROUP BY
			LNXX.BF_SSN,
			PDXX.DX_PRS_DSA_TPD_REA
;
QUIT;
		
		

ENDRSUBMIT;

DATA QUERYX; SET LEGEND.QUERYX; RUN;
DATA QUERYX; SET LEGEND.QUERYX; RUN;
DATA QUERYX; SET LEGEND.QUERYX; RUN;
DATA QUERYX; SET LEGEND.QUERYX; RUN;



/*export to Excel spreadsheet*/
PROC EXPORT DATA = WORK.QUERYX 
            OUTFILE = "T:\NH XXXX.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="QUERYX"; 
RUN;

PROC EXPORT DATA = WORK.QUERYX 
            OUTFILE = "T:\NH XXXX.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="QUERYX"; 
RUN;

PROC EXPORT DATA = WORK.QUERYX 
            OUTFILE = "T:\NH XXXX.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="QUERYX"; 
RUN;

PROC EXPORT DATA = WORK.QUERYX 
            OUTFILE = "T:\NH XXXX.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="QUERYX"; 
RUN;

