SELECT DISTINCT
	'PSAOR' AS DealId,
	COUNT(DISTINCT TX.BF_SSN) AS BorrowerCount,
	COUNT(TL.BF_SSN) AS LoanCount
FROM
	CDW..CS_TransferPIF TX
	INNER JOIN CDW..CS_TransferPIFLoans TL
		ON TL.BF_SSN = TX.BF_SSN
	INNER JOIN 
	(
		SELECT DISTINCT
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			SUM(COALESCE(LA_FAT_CUR_PRI,X.XX)) AS LA_FAT_CUR_PRI,
			SUM(COALESCE(LA_FAT_NSI,X.XX)) AS LA_FAT_NSI,
			MAX(LD_FAT_EFF) AS LD_FAT_EFF
		FROM
			CDW..LNXX_FIN_ATY LNXX
			INNER JOIN CDW..LNXX_LON LNXX
				ON LNXX.BF_SSN = LNXX.BF_SSN
				AND LNXX.LN_SEQ = LNXX.LN_SEQ
				AND LNXX.LC_FED_PGM_YR = 'LNC'
		WHERE
			LNXX.LC_STA_LONXX = 'A'
			AND COALESCE(LNXX.LC_FAT_REV_REA,'') = ''
			AND LNXX.LD_FAT_EFF >= 'XX/XX/XXXX'
			AND LNXX.PC_FAT_TYP = 'XX'
			AND LNXX.PC_FAT_SUB_TYP = 'XX'
		GROUP BY
			LNXX.BF_SSN,
			LNXX.LN_SEQ
	) Trans
		ON Trans.BF_SSN = TX.BF_SSN
		AND Trans.LN_SEQ = TL.LN_SEQ

SELECT DISTINCT
	'PSAOS' AS DealId,
	COUNT(DISTINCT TX.BF_SSN) AS BorrowerCount,
	COUNT(TL.BF_SSN) AS LoanCount
FROM
	CDW..CS_TransferPIF TX
	INNER JOIN CDW..CS_TransferPIFLoans TL
		ON TL.BF_SSN = TX.BF_SSN
	INNER JOIN 
	(
		SELECT DISTINCT
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			SUM(COALESCE(LA_FAT_CUR_PRI,X.XX)) AS LA_FAT_CUR_PRI,
			SUM(COALESCE(LA_FAT_NSI,X.XX)) AS LA_FAT_NSI,
			MAX(LD_FAT_EFF) AS LD_FAT_EFF
		FROM
			CDW..LNXX_FIN_ATY LNXX
			INNER JOIN CDW..LNXX_LON LNXX
				ON LNXX.BF_SSN = LNXX.BF_SSN
				AND LNXX.LN_SEQ = LNXX.LN_SEQ
				AND LNXX.LC_FED_PGM_YR = 'DLO'
		WHERE
			LNXX.LC_STA_LONXX = 'A'
			AND COALESCE(LNXX.LC_FAT_REV_REA,'') = ''
			AND LNXX.LD_FAT_EFF >= 'XX/XX/XXXX'
			AND LNXX.PC_FAT_TYP = 'XX'
			AND LNXX.PC_FAT_SUB_TYP = 'XX'
		GROUP BY
			LNXX.BF_SSN,
			LNXX.LN_SEQ
	) Trans
		ON Trans.BF_SSN = tX.BF_SSN
		AND Trans.LN_SEQ = TL.LN_SEQ

SELECT DISTINCT
	'PSAOT' AS DealId,
	COUNT(DISTINCT TX.BF_SSN) AS BorrowerCount,
	COUNT(TL.BF_SSN) AS LoanCount
FROM
	CDW..CS_TransferX TX
	INNER JOIN CDW..CS_TransferXLoans TL
		ON TL.BF_SSN = TX.BF_SSN
	INNER JOIN 
	(
		SELECT DISTINCT
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			SUM(COALESCE(LA_FAT_CUR_PRI,X.XX)) AS LA_FAT_CUR_PRI,
			SUM(COALESCE(LA_FAT_NSI,X.XX)) AS LA_FAT_NSI,
			MAX(LD_FAT_EFF) AS LD_FAT_EFF
		FROM
			CDW..LNXX_FIN_ATY LNXX
			INNER JOIN CDW..LNXX_LON LNXX
				ON LNXX.BF_SSN = LNXX.BF_SSN
				AND LNXX.LN_SEQ = LNXX.LN_SEQ
				AND LNXX.LC_FED_PGM_YR = 'DLO'
		WHERE
			LNXX.LC_STA_LONXX = 'A'
			AND COALESCE(LNXX.LC_FAT_REV_REA,'') = ''
			AND LNXX.LD_FAT_EFF >= 'XX/XX/XXXX'
			AND LNXX.PC_FAT_TYP = 'XX'
			AND LNXX.PC_FAT_SUB_TYP = 'XX'
		GROUP BY
			LNXX.BF_SSN,
			LNXX.LN_SEQ
	) Trans
		ON Trans.BF_SSN = tX.BF_SSN
		AND Trans.LN_SEQ = TL.LN_SEQ