PROC IMPORT OUT= WORK.SOURCE
            DATAFILE= "T:\PKUB FSXXLNXX.xlsx" 
            DBMS=EXCEL REPLACE;
     RANGE="PKUB$"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
RUN;

DATA SOURCEX (DROP=ACCOUNT_ID);
	SET SOURCE;
	DF_SPE_ACC_ID = PUT(ACCOUNT_ID,ZXX.);
RUN;

/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/UNWSXX.NWSXXRZ";
FILENAME REPORTX "&RPTLIB/UNWSXX.NWSXXRX";

LIBNAME  LEGEND  REMOTE  SERVER=LEGEND SLIBREF=work  ;

DATA LEGEND.SOURCEX;
	SET SOURCEX;
RUN;

RSUBMIT LEGEND;
/*%let DB = DNFPRQUT;  *This is test;*/
/*%let DB = DNFPRUUT;  *This is VUKX test;*/
%let DB = DNFPUTDL;  *This is live;

LIBNAME PKUB DBX DATABASE=&DB OWNER=PKUB;

PROC SQL;
	CONNECT TO DBX (DATABASE=&DB);

	CREATE TABLE FSXX AS
		SELECT	
			S.DF_SPE_ACC_ID
			,FSXX.*
		FROM SOURCEX S
			INNER JOIN PKUB.PDXX_PRS_NME PDXX
				ON S.DF_SPE_ACC_ID = PDXX.DF_SPE_ACC_ID
			INNER JOIN PKUB.FSXX_DL_LON FSXX
				ON PDXX.DF_PRS_ID = FSXX.BF_SSN
				AND S.LOAN_SEQ = FSXX.LN_SEQ
	;

CREATE TABLE LNXX AS
		SELECT	
			S.DF_SPE_ACC_ID
			,LNXX.*
		FROM SOURCEX S
			INNER JOIN PKUB.PDXX_PRS_NME PDXX
				ON S.DF_SPE_ACC_ID = PDXX.DF_SPE_ACC_ID
			INNER JOIN PKUB.LNXX_LON LNXX
				ON PDXX.DF_PRS_ID = LNXX.BF_SSN
				AND S.LOAN_SEQ = LNXX.LN_SEQ
	;

	DISCONNECT FROM DBX;

	/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>> ;  ** INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
	/*%SQLCHECK;*/
QUIT;

ENDRSUBMIT;

DATA FSXX; SET LEGEND.FSXX; RUN;
DATA LNXX; SET LEGEND.LNXX; RUN;

/*export to Excel spreadsheet*/
PROC EXPORT DATA = WORK.FSXX 
            OUTFILE = "T:\SAS\NH XXXX.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="FSXX"; 
RUN;

/*export to Excel spreadsheet*/
PROC EXPORT DATA = WORK.LNXX
            OUTFILE = "T:\SAS\NH XXXX.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="LNXX"; 
RUN;
