LIBNAME LEGEND REMOTE SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
LIBNAME WHSE DBX DATABASE=DNFPRQUT OWNER=PKUB; *This is VUK test;

PROC SQL;
	CREATE TABLE LNXX AS
		SELECT DISTINCT
			BF_SSN
		FROM 
			WHSE.LNXX_LON
		WHERE 
			LD_LON_X_DSB >= 'XXOCTXXXX'D
	;
QUIT;

ENDRSUBMIT;

PROC EXPORT
		DATA=LEGEND.LNXX
		OUTFILE='T:\SAS\LON_X_DISB.XLSX'
		REPLACE;
QUIT;
