--query based on CNH XXXXX
USE CDW
GO

DECLARE @TODAY DATE = GETDATE()

SELECT DISTINCT	
	PDXX.DF_SPE_ACC_ID
	,LNXX.LN_SEQ
	,DWXX.WC_DW_LON_STA
	,CASE
		WHEN WC_DW_LON_STA = 'XX' THEN 'In Grace'
		WHEN WC_DW_LON_STA = 'XX' THEN 'In School'
		WHEN WC_DW_LON_STA = 'XX' THEN 'In Repayment'
		WHEN WC_DW_LON_STA = 'XX' THEN 'In Deferment'
		WHEN WC_DW_LON_STA = 'XX' THEN 'In Forbearance'
		WHEN WC_DW_LON_STA = 'XX' THEN 'In Cure'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Claim Pending'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Claim Submitted'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Claim Cancelled'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Claim Reject'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Claim Returned'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Claim Paid'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Pre-claim Pending'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Preclaim submitted'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Pre-claim Cancelled'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Death Alleged'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Death Verified'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Disability Alleged'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Disability Verified'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Bankruptcy Alleged'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Bankruptcy Verified' 
		WHEN WC_DW_LON_STA = 'XX' THEN 'Paid In Full'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Not Fully Originated'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Processing Error'
		WHEN WC_DW_LON_STA = 'XX' THEN 'Unknown'
	ELSE 'DWXX STATUS CODE ERROR'
	END AS [Status]
	,CASE
		WHEN LNXX.LC_STA_LNXX = 'A'
		THEN CAST(LNXX.LR_EFT_RDC AS VARCHAR(XX))
		ELSE 'N'
	END AS 'EFT'
	,LNXX.LD_LON_X_DSB AS [Xst Disb Date]
	,LNXX.LR_ITR AS [Interest Rate]
FROM	
	LNXX_LON LNXX
	INNER JOIN PDXX_PRS_NME PDXX
		ON LNXX.BF_SSN = PDXX.DF_PRS_ID
	INNER JOIN LNXX_INT_RTE_HST LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
	INNER JOIN DWXX_DW_CLC_CLU DWXX
		ON LNXX.BF_SSN = DWXX.BF_SSN
		AND LNXX.LN_SEQ = DWXX.LN_SEQ
	LEFT JOIN LNXX_EFT_TO_LON LNXX
		ON LNXX.BF_SSN = LNXX.BF_SSN
		AND LNXX.LN_SEQ = LNXX.LN_SEQ
	LEFT JOIN
	(--flag for exclusion: direct consol loans with fixed rate
		SELECT
			LNXX.BF_SSN
			,LNXX.LN_SEQ
		FROM
			LNXX_LON LNXX
			INNER JOIN LNXX_INT_RTE_HST LNXX
				ON LNXX.BF_SSN = LNXX.BF_SSN
				AND LNXX.LN_SEQ = LNXX.LN_SEQ
		WHERE 
			LNXX.LC_STA_LONXX = 'R'
			AND LNXX.LA_CUR_PRI > X.XX
			AND @TODAY BETWEEN LNXX.LD_ITR_EFF_BEG AND LNXX.LD_ITR_EFF_END
			AND LNXX.LC_STA_LONXX = 'A'
			AND LNXX.LC_ITR_TYP = 'FX'--fixed rate
			AND LNXX.IC_LON_PGM IN 
			(--direct consolidation loans
				'DLCNSL', 
				'DLPCNS', 
				'DLSCCN',
				'DLSCNS', 
				'DLSCPG', 
				'DLSCPL', 
				'DLSCSC', 
				'DLSCSL', 
				'DLSCST', 
				'DLSCUC', 
				'DLSCUN', 
				'DLSPCN', 
				'DLSSPL', 
				'DLUCNS',
				'DLUSPL'
			)
	) EXCLUDE
		ON EXCLUDE.BF_SSN = LNXX.BF_SSN
		AND EXCLUDE.LN_SEQ = LNXX.LN_SEQ
WHERE
	EXCLUDE.BF_SSN IS NULL
	AND LNXX.LC_STA_LONXX = 'R'
	AND LNXX.LA_CUR_PRI > X.XX
	AND @TODAY BETWEEN LNXX.LD_ITR_EFF_BEG AND LNXX.LD_ITR_EFF_END
	AND LNXX.LC_STA_LONXX = 'A'
ORDER BY
	PDXX.DF_SPE_ACC_ID
	,LNXX.LN_SEQ