use cdw
go


--TRUNCATE TABLE CR_XXXX_BORROWER_STATUSES
--INSERT INTO CR_XXXX_BORROWER_STATUSES
--SELECT DISTINCT
--	*,
--	CASE WHEN POP.PAST_DUE IS NULL AND POP.GRACE IS NULL AND POP.MILITARY IS NULL AND POP.DEF_FORB IS NULL THEN 'GENERAL POP' END AS GENERAL_POP
--FROM
--(
--	SELECT DISTINCT
--		PDXX.DF_SPE_ACC_ID,
--		LNXX.BF_SSN,
--		--LNXX.LF_EDS AS ENDORSER_SSN,
--		MAX(CASE WHEN LNXX.BF_SSN IS NOT NULL THEN 'PAST_DUE' END) AS PAST_DUE,
--		MAX(CASE WHEN LNXX.LD_END_GRC_PRD BETWEEN 'XX/XX/XXXX' AND 'XX/XX/XXXX' THEN 'GRACE' END) AS GRACE, --ENDING ON XX/XXX/XXXX AS THE GRACE END OF XX/XX/XXXX WOULD NOTGET THE FOPRBEARANCE
--		MAX(CASE WHEN MIL.BorrSSN IS NOT NULL THEN 'MIL' END) AS MILITARY,  --TODO LOOK AT SCRA TABLES,
--		MAX(CASE WHEN DEF_FORB.BF_SSN IS NOT NULL THEN 'DEF FORB' END) AS DEF_FORB 
--	FROM
--		CDW..LNXX_LON LNXX
--		INNER JOIN CDW..PDXX_PRS_NME PDXX
--			ON PDXX.DF_PRS_ID = LNXX.BF_SSN
--		INNER JOIN
--		(
--			SELECT DISTINCT
--				FBXX.BF_SSN
--			FROM
--				CDW..FBXX_BR_FOR_REQ FBXX
--				INNER JOIN CDW..LNXX_BR_FOR_APV LNXX
--					ON LNXX.BF_SSN = FBXX.BF_SSN
--					AND LNXX.LF_FOR_CTL_NUM = FBXX.LF_FOR_CTL_NUM
--				INNER JOIN CDW..LNXX_LON LNXX
--					ON LNXX.BF_SSN = LNXX.BF_SSN
--					AND LNXX.LN_SEQ = LNXX.LN_SEQ
--					AND LNXX.LA_CUR_PRI > X
--					AND LNXX.LC_STA_LONXX = 'R'
--			WHERE
--				LNXX.LC_STA_LONXX = 'A'
--				AND FBXX.LC_STA_FORXX = 'A'
--				AND FBXX.LC_FOR_STA = 'A' --denied records cant have this active
--				AND LNXX.LC_FOR_RSP != 'XXX'
--				AND FBXX.LC_FOR_TYP = 'XX'
--				AND CAST(GETDATE() AS DATE) BETWEEN CAST(LNXX.LD_FOR_BEG AS DATE) AND CAST(LNXX.LD_FOR_END AS DATE)
--		) FORB
--			ON FORB.BF_SSN = LNXX.BF_SSN
--		LEFT JOIN
--		(
--			SELECT DISTINCT
--					LNXX.BF_SSN,
--					MAX(CASE 
--						WHEN LD_DLQ_MAX < 'XX/XX/XXXX' THEN DATEDIFF(DAY, LD_DLQ_OCC, LD_DLQ_MAX)
--						ELSE DATEDIFF(DAY, LD_DLQ_OCC, 'XX/XX/XXXX')
--					END) AS DDP
--				FROM
--					CDW..LNXX_LON_DLQ_HST LNXX
--					INNER JOIN CDW..LNXX_LON LNXX
--						ON LNXX.BF_SSN = LNXX.BF_SSN
--						AND LNXX.LN_SEQ = LNXX.LN_SEQ
--				WHERE
--					LD_DLQ_OCC < 'XX/XX/XXXX' --past due before the cutoff date 
--					AND LD_DLQ_MAX > 'XX/XX/XXXX' --past due after
--					AND LNXX.LA_CUR_PRI > X
--					--AND LNXX.LC_STA_LONXX = 'R'
--			GROUP BY
--				LNXX.BF_SSN
--		)LNXX
--			ON LNXX.BF_SSN = LNXX.BF_SSN
--		LEFT JOIN
--		(
--			SELECT 
--				FBXX.BF_SSN
--			FROM
--				CDW..FBXX_BR_FOR_REQ FBXX
--				INNER JOIN CDW..LNXX_BR_FOR_APV LNXX
--					ON LNXX.BF_SSN = FBXX.BF_SSN
--					AND LNXX.LF_FOR_CTL_NUM = FBXX.LF_FOR_CTL_NUM

--			WHERE
--				LNXX.LC_STA_LONXX = 'A'
--				AND FBXX.LC_STA_FORXX = 'A'
--				AND FBXX.LC_FOR_STA = 'A'
--				AND LNXX.LD_FOR_BEG = 'XX/XX/XXXX'
--				AND LNXX.LC_FOR_RSP != 'XXX'

--			UNION ALL
	
--			SELECT DISTINCT
--				DFXX.BF_SSN
--			FROM
--				CDW..DFXX_BR_DFR_REQ DFXX
--				INNER JOIN CDW..LNXX_BR_DFR_APV LNXX
--					ON LNXX.BF_SSN = DFXX.BF_SSN
--					AND LNXX.LF_DFR_CTL_NUM = DFXX.LF_DFR_CTL_NUM

--			WHERE
--				LNXX.LC_STA_LONXX = 'A'
--				AND DFXX.LC_STA_DFRXX = 'A'
--				AND DFXX.LC_DFR_STA = 'A'
--				AND LNXX.LD_DFR_BEG = 'XX/XX/XXXX'
--				AND LNXX.LC_DFR_RSP != 'XXX'	
--		) DEF_FORB
--			ON DEF_FORB.BF_SSN = LNXX.BF_SSN
--		LEFT JOIN
--		(
--			SELECT DISTINCT
--				BorrSSN
--			FROM 
--				CLS.scra.DataComparison 
--			WHERE 
--				ActiveRow = X 
--				and (borractive = X or EndrActive = X)
--		) MIL
--			ON MIL.BorrSSN = LNXX.BF_SSN
--		LEFT JOIN CDW..DWXX_DW_CLC_CLU DWXX
--			ON DWXX.BF_SSN = LNXX.BF_SSN
--			AND DWXX.LN_SEQ = LNXX.LN_SEQ
--			AND DWXX.WC_DW_LON_STA IN('XX','XX','XX','XX','XX','XX')
--	WHERE
--		LNXX.LA_CUR_PRI > X
--		AND LNXX.LC_STA_LONXX = 'R'
--		AND DWXX.BF_SSN IS NULL --Dont pull in DDB loans
--	GROUP BY
--		LNXX.BF_SSN,
--		PDXX.DF_SPE_ACC_ID

--) POP





--TRUNCATE TABLE CR_XXXX_COBORROWER_STATUSES

--INSERT INTO CR_XXXX_COBORROWER_STATUSES
SELECT DISTINCT
	*,
	CASE WHEN POP.PAST_DUE IS NULL AND POP.GRACE IS NULL AND POP.MILITARY IS NULL AND POP.DEF_FORB IS NULL THEN 'GENERAL POP' END AS GENERAL_POP
FROM
(
	SELECT DISTINCT
		PDXX.DF_SPE_ACC_ID,
		LNXX.BF_SSN,
		LNXX.LF_EDS AS ENDORSER_SSN,
		MAX(CASE WHEN LNXX.BF_SSN IS NOT NULL THEN 'PAST_DUE' END) AS PAST_DUE,
		MAX(CASE WHEN LNXX.LD_END_GRC_PRD BETWEEN 'XX/XX/XXXX' AND 'XX/XX/XXXX' THEN 'GRACE' END) AS GRACE, --ENDING ON XX/XXX/XXXX AS THE GRACE END OF XX/XX/XXXX WOULD NOTGET THE FOPRBEARANCE
		MAX(CASE WHEN MIL.BorrSSN IS NOT NULL THEN 'MIL' END) AS MILITARY,  --TODO LOOK AT SCRA TABLES,
		MAX(CASE WHEN DEF_FORB.BF_SSN IS NOT NULL THEN 'DEF FORB' END) AS DEF_FORB 
	FROM
		CDW..LNXX_LON LNXX
		INNER JOIN CDW..LNXX_EDS LNXX
			ON LNXX.BF_SSN = LNXX.BF_SSN
			AND LNXX.LN_SEQ = LNXX.LN_SEQ
			AND LNXX.LC_EDS_TYP = 'M'
		INNER JOIN CDW..PDXX_PRS_NME PDXX
			ON PDXX.DF_PRS_ID = LNXX.BF_SSN
		INNER JOIN
		(
			SELECT DISTINCT
				FBXX.BF_SSN
			FROM
				CDW..FBXX_BR_FOR_REQ FBXX
				INNER JOIN CDW..LNXX_BR_FOR_APV LNXX
					ON LNXX.BF_SSN = FBXX.BF_SSN
					AND LNXX.LF_FOR_CTL_NUM = FBXX.LF_FOR_CTL_NUM
				INNER JOIN CDW..LNXX_LON LNXX
					ON LNXX.BF_SSN = LNXX.BF_SSN
					AND LNXX.LN_SEQ = LNXX.LN_SEQ
					AND LNXX.LA_CUR_PRI > X
					AND LNXX.LC_STA_LONXX = 'R'
			WHERE
				LNXX.LC_STA_LONXX = 'A'
				AND FBXX.LC_STA_FORXX = 'A'
				AND FBXX.LC_FOR_STA = 'A' --denied records cant have this active
				AND LNXX.LC_FOR_RSP != 'XXX'
				AND FBXX.LC_FOR_TYP = 'XX'
				AND CAST(GETDATE() AS DATE) BETWEEN CAST(LNXX.LD_FOR_BEG AS DATE) AND CAST(LNXX.LD_FOR_END AS DATE)
		) FORB
			ON FORB.BF_SSN = LNXX.BF_SSN
		LEFT JOIN
		(
			SELECT DISTINCT
					LNXX.BF_SSN,
					MAX(CASE 
						WHEN LD_DLQ_MAX < 'XX/XX/XXXX' THEN DATEDIFF(DAY, LD_DLQ_OCC, LD_DLQ_MAX)
						ELSE DATEDIFF(DAY, LD_DLQ_OCC, 'XX/XX/XXXX')
					END) AS DDP
				FROM
					CDW..LNXX_LON_DLQ_HST LNXX
					INNER JOIN CDW..LNXX_LON LNXX
						ON LNXX.BF_SSN = LNXX.BF_SSN
						AND LNXX.LN_SEQ = LNXX.LN_SEQ
				WHERE
					LD_DLQ_OCC < 'XX/XX/XXXX' --past due before the cutoff date 
					AND LD_DLQ_MAX > 'XX/XX/XXXX' --past due after
					AND LNXX.LA_CUR_PRI > X
					--AND LNXX.LC_STA_LONXX = 'R'
			GROUP BY
				LNXX.BF_SSN
		)LNXX
			ON LNXX.BF_SSN = LNXX.BF_SSN
		LEFT JOIN
		(
			SELECT 
				FBXX.BF_SSN
			FROM
				CDW..FBXX_BR_FOR_REQ FBXX
				INNER JOIN CDW..LNXX_BR_FOR_APV LNXX
					ON LNXX.BF_SSN = FBXX.BF_SSN
					AND LNXX.LF_FOR_CTL_NUM = FBXX.LF_FOR_CTL_NUM

			WHERE
				LNXX.LC_STA_LONXX = 'A'
				AND FBXX.LC_STA_FORXX = 'A'
				AND FBXX.LC_FOR_STA = 'A'
				AND LNXX.LD_FOR_BEG = 'XX/XX/XXXX'
				AND LNXX.LC_FOR_RSP != 'XXX'

			UNION ALL
	
			SELECT DISTINCT
				DFXX.BF_SSN
			FROM
				CDW..DFXX_BR_DFR_REQ DFXX
				INNER JOIN CDW..LNXX_BR_DFR_APV LNXX
					ON LNXX.BF_SSN = DFXX.BF_SSN
					AND LNXX.LF_DFR_CTL_NUM = DFXX.LF_DFR_CTL_NUM

			WHERE
				LNXX.LC_STA_LONXX = 'A'
				AND DFXX.LC_STA_DFRXX = 'A'
				AND DFXX.LC_DFR_STA = 'A'
				AND LNXX.LD_DFR_BEG = 'XX/XX/XXXX'
				AND LNXX.LC_DFR_RSP != 'XXX'	
		) DEF_FORB
			ON DEF_FORB.BF_SSN = LNXX.BF_SSN
		LEFT JOIN
		(
			SELECT DISTINCT
				BorrSSN
			FROM 
				CLS.scra.DataComparison 
			WHERE 
				ActiveRow = X 
				and (borractive = X or EndrActive = X)
		) MIL
			ON MIL.BorrSSN = LNXX.BF_SSN
		LEFT JOIN CDW..DWXX_DW_CLC_CLU DWXX
			ON DWXX.BF_SSN = LNXX.BF_SSN
			AND DWXX.LN_SEQ = LNXX.LN_SEQ
			AND DWXX.WC_DW_LON_STA IN('XX','XX','XX','XX','XX','XX')
	WHERE
		LNXX.LA_CUR_PRI > X
		AND LNXX.LC_STA_LONXX = 'R'
		AND DWXX.BF_SSN IS NULL --Dont pull in DDB loans
	GROUP BY
		LNXX.BF_SSN,
		PDXX.DF_SPE_ACC_ID,
		LNXX.LF_EDS

) POP