
SELECT 
	ISNULL(BU.[Name],'N/A') AS BU,
	COUNT(DISTINCT T.Ticket) AS SUB_COUNT,
	DATENAME(month, REQUESTED) AS M,
	MONTH(REQUESTED) AS MO,
	YEAR(REQUESTED) AS Y
FROM 
	[NeedHelpCornerStone].[dbo].[DAT_Ticket] T
	LEFT JOIN CSYS..GENR_LST_BusinessUnits BU
		ON BU.ID = T.Unit
WHERE 
	Requested BETWEEN 'XX/XX/XXXX' AND 'XX/XX/XXXX'
	AND T.[Status] != 'Withdrawn'
GROUP BY
	ISNULL(BU.[Name],'N/A'),
	DATENAME(month, REQUESTED),
	YEAR(REQUESTED),
	MONTH(REQUESTED)
ORDER BY
	MONTH(REQUESTED),
	YEAR(REQUESTED)