/*LIBNAME DLGSUTWH DBX DATABASE=DLGSUTWH OWNER=PKUB;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/UNWSXX.NWSXXRZ";
FILENAME REPORTX "&RPTLIB/UNWSXX.NWSXXRX";
FILENAME REPORTX "&RPTLIB/UNWSXX.NWSXXRX";
FILENAME REPORTX "&RPTLIB/UNWSXX.NWSXXRX";


LIBNAME Y 'Y:\Development\ExternalDataSources\MonthlyDataSets';
LIBNAME  WORKLOCL  REMOTE  SERVER=LEGEND  SLIBREF=WORK;

PROC SQL;
	CREATE TABLE DLQBKT AS
		SELECT 
			A.BF_SSN
			,A.LN_SEQ
			,A.LN_DLQ_MAX 
			,B.LA_CUR_PRI
		FROM
			Y.Pkus_lnXX_lon_dlq_hst_XXXXXX A
			INNER JOIN Y.Pkub_lnXX_lon_XXXXXX B
				ON A.BF_SSN = B.BF_SSN
				AND A.LN_SEQ = B.LN_SEQ
			INNER JOIN Y.Pkub_dwXX_dw_clc_clu_XXXXXX DWXX
				ON A.BF_SSN = DWXX.BF_SSN
				AND A.LN_SEQ = DWXX.LN_SEQ
				AND DWXX.WC_DW_LON_STA NOT IN ('XX', 'XX', 'XX', 'XX', 'XX', 'XX', 'XX', 'XX')
		WHERE		
			LC_STA_LONXX = 'X'
			AND LD_DLQ_MAX = 'XXDECXXXX'D
			AND B.LA_CUR_PRI > X
			AND B.LC_STA_LONXX = 'R'
		UNION
		SELECT 
			A.BF_SSN
			,A.LN_SEQ
			,TODAY() - A.LD_DLQ_OCC AS LN_DLQ_MAX
			,B.LA_CUR_PRI
		FROM
			Y.Pkus_lnXX_lon_dlq_hst_XXXXXX A
			INNER JOIN Y.Pkub_lnXX_lon_XXXXXX B
				ON A.BF_SSN = B.BF_SSN
				AND A.LN_SEQ = B.LN_SEQ
			INNER JOIN Y.Pkub_dwXX_dw_clc_clu_XXXXXX DWXX
				ON A.BF_SSN = DWXX.BF_SSN
				AND A.LN_SEQ = DWXX.LN_SEQ
				AND DWXX.WC_DW_LON_STA NOT IN ('XX', 'XX', 'XX', 'XX', 'XX', 'XX', 'XX', 'XX')
		WHERE 
			B.LC_SST_LONXX = 'X'
			AND A.LC_STA_LONXX = 'X'
			AND B.LA_CUR_PRI > X
			AND B.LC_STA_LONXX = 'D'
	;
QUIT;

DATA LEGEND.DLQBKT; SET DLQBKT; RUN;

RSUBMIT;
PROC SQL;
	CREATE TABLE DLQBKT AS
		SELECT
			PDXX.DF_SPE_ACC_ID,
			DLQ.LN_SEQ,
			DLQ.LN_DLQ_MAX,
			DLQ.LA_CUR_PRI
		FROM
			PKUB.PDXX_PRS_NME PDXX
			JOIN DLQBKT DLQ
				ON PDXX.DF_PRS_ID = DLQ.BF_SSN
	;
QUIT;
ENDRSUBMIT;

DATA DLQBKT; SET WORKLOCL.DLQBKT; RUN;

/*'determine delinquency periods and buckets*/
DATA DLQBKT;
	SET DLQBKT;
	WHERE LN_DLQ_MAX >= XX;
	LENGTH PERIOD $ XX.;
	IF LN_DLQ_MAX > XXX THEN DO;
		BUCKET = XX;
		PERIOD = ' XXX+';
	END;
	ELSE DO;
		IF LN_DLQ_MAX <= XX THEN DO;
			BUCKET = X ;
			PERIOD = '  XX - XX';
		END;
		ELSE DO;
			BUCKET = INT((LN_DLQ_MAX-X)/XX) ;
			PERIOD = PUT((BUCKET*XX)+X, X.X) || ' - ' || PUT(LEFT(BUCKET*XX + XX), X.X);
		END;

	END;
RUN;

PROC SQL;
/*	data set for borrower count report*/
	CREATE TABLE BRWDLQBKT AS
		SELECT DISTINCT
			DF_SPE_ACC_ID,
			LN_DLQ_MAX,
			PERIOD,
			BUCKET
		FROM
			DLQBKT
	;

/*	loan counts for summary report*/
	CREATE TABLE LN_CNT AS
		SELECT 
			PERIOD, 
			COUNT(*) AS NUM_LOANS LABEL='TOTAL NUMBER OF LOANS',
			SUM(LA_CUR_PRI) AS LA_CUR_PRI LABEL='TOTAL AMOUNT'
		FROM
			DLQBKT
		GROUP BY 
			PERIOD,
			BUCKET
		ORDER BY 
			BUCKET
	;

/*	borrower counts for summary report*/
	CREATE TABLE BRW_CNT AS
		SELECT
			PERIOD,
			COUNT(DISTINCT DF_SPE_ACC_ID) AS NUM_BRWS LABEL='TOTAL NUMBER OF BORROWERS'
		FROM
			DLQBKT
		GROUP BY
			PERIOD
	;

/*	combine data sets to create data for summary report*/
	CREATE TABLE DLQ_REPORT AS
		SELECT
			LNS.PERIOD,
			LNS.NUM_LOANS,
			BRWS.NUM_BRWS,
			LA_CUR_PRI
		FROM
			LN_CNT LNS
			JOIN BRW_CNT BRWS
				ON LNS.PERIOD = BRWS.PERIOD
	;
QUIT;

DATA _NULL_;
	CALL SYMPUT('TODAYS',PUT(TODAY(),WEEKDATEXX.));
RUN;


/*RX summary report*/
PROC PRINTTO PRINT=REPORTX NEW; RUN;
TITLE 'FEDERAL BORROWER DELINQUENCY SUMMARY REPORT';
TITLEX	&TODAYS;

PROC PRINT NOOBS SPLIT='/' DATA=DLQ_REPORT WIDTH=UNIFORM WIDTH=MIN LABEL;
	FORMAT 
		NUM_LOANS COMMAX. 
		LA_CUR_PRI DOLLARXX.X
	;
	VAR 
		PERIOD 
		NUM_LOANS 
		NUM_BRWS 
		LA_CUR_PRI
	;
	LABEL 
		PERIOD = 'Days Delinquent'
		NUM_LOANS = 'Total Number of Loans'
		NUM_BRWS = 'Total Number of Borrowers'
		LA_CUR_PRI = 'Total Amount of Loans'
	;
RUN;

PROC PRINTTO; RUN;


/*RX loan counts*/
PROC FREQ DATA=DLQBKT NOPRINT; 
	TABLE LN_DLQ_MAX / OUT=LN_COUNTS;
RUN;

DATA _NULL_;
	SET		WORK.LN_COUNTS;
	FILE
		REPORTX
		DELIMITER = ','
		DSD
		DROPOVER
		LRECL = XXXXX
	;

	IF _N_ = X THEN
		DO;
			PUT	
				'LN_DLQ_MAX'
				','
				'COUNT'
				','
				'PERCENT'
			;
		END;

	DO;
		PUT LN_DLQ_MAX @;
		PUT COUNT  @;
		PUT PERCENT;
		;
	END;
RUN;

/*RX borrower counts*/
PROC FREQ DATA=BRWDLQBKT NOPRINT; 
	TABLE LN_DLQ_MAX / OUT=BRW_COUNTS;
RUN;

DATA _NULL_;
	SET		WORK.BRW_COUNTS;
	FILE
		REPORTX
		DELIMITER = ','
		DSD
		DROPOVER
		LRECL = XXXXX
	;

	IF _N_ = X THEN
		DO;
			PUT	
				'LN_DLQ_MAX'
				','
				'COUNT'
				','
				'PERCENT'
			;
		END;

	DO;
		PUT LN_DLQ_MAX @;
		PUT COUNT  @;
		PUT PERCENT;
		;
	END;
RUN;
