SELECT 
	*
FROM
	OPENQUERY(LEGEND,
	'
		SELECT DISTINCT
			PDXX.DF_SPE_ACC_ID,
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			LNXX.LC_INT_RDC_PGM,
			LNXX.LD_ITR_EFF_BEG,
			LNXX.LD_ITR_EFF_END,
			LNXX.LD_PIF_RPT,
			LNXX.LC_STA_LONXX
		FROM 
			PKUB.LNXX_INT_RTE_HST LNXX
			INNER JOIN PKUB.PDXX_PRS_NME PDXX
				ON PDXX.DF_PRS_ID = LNXX.BF_SSN
			INNER JOIN PKUB.LNXX_LON LNXX
				ON LNXX.BF_SSN = LNXX.BF_SSN
				AND LNXX.LN_SEQ = LNXX.LN_SEQ
		WHERE
			LNXX.LC_INT_RDC_PGM = ''M''
			AND LNXX.LD_ITR_EFF_BEG <= ''XXXX-XX-XX''
			AND LNXX.LD_ITR_EFF_END BETWEEN ''XXXX-XX-XX'' AND ''XXXX-XX-XX''
	
	'
	)