/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;

FILENAME REPORTZ "&RPTLIB/UNWDWX.NWDWXRZ";
FILENAME REPORTX "&RPTLIB/UNWDWX.NWDWXRX";*FBXX;
FILENAME REPORTX "&RPTLIB/UNWDWX.NWDWXRX";*PDXX;
FILENAME REPORTXX "&RPTLIB/UNWDWX.NWDWXRXX";*LNXX;
FILENAME REPORTXX "&RPTLIB/UNWDWX.NWDWXRXX";*LNXX;
FILENAME REPORTXX "&RPTLIB/UNWDWX.NWDWXRXX";*LNXX;
FILENAME REPORTXX "&RPTLIB/UNWDWX.NWDWXRXX";*PDXX;
FILENAME REPORTXX "&RPTLIB/UNWDWX.NWDWXRXX";*PDXX;
FILENAME REPORTXX "&RPTLIB/UNWDWX.NWDWXRXX";*PDXX;
FILENAME REPORTXX "&RPTLIB/UNWDWX.NWDWXRXX";*DWXX;

LIBNAME  LEGEND  REMOTE  SERVER=LEGEND SLIBREF=WORK;
RSUBMIT;
/*%LET DB = DNFPRQUT;  *This is test;*/
%LET DB = DNFPUTDL;  *This is live;

LIBNAME PKUB DBX DATABASE=&DB OWNER=PKUB; 
LIBNAME PKUS DBX DATABASE=&DB OWNER=PKUS; 
LIBNAME SAS_TAB VX '/sas/whse/progrevw';

/*get last run date*/
DATA _NULL_; 
	SET SAS_TAB.LASTRUN_JOBS;
/*If the job must be run manually set this macro to the last day it successfully ran(last business day).*/
LAST_RUN = TODAY() - X;	*COMMENT FOR PROD, IT WILL READ THE DATE FROM A TABLE;
	IF JOB = 'UTNWDWX' THEN DO;
		CALL SYMPUT('LAST_RUN',"'"||TRIM(LEFT(PUT(LAST_RUN,DATEXX.)))|| "'D");
		CALL SYMPUT('LAST_RUNPASS',"'"|| PUT(LAST_RUN,MMDDYYXX.) || "'");
	END;
RUN;
%PUT &LAST_RUN; 

/*THE TABLES ARE GOING TO HAVE THE ACCOUNT NUMBER RATHER THAN SSN AS A PRIMARY KEY*/
/*THE ACCOUNT NUMBER IS BEING TAKEN FROM THE PDXX TABLE WHILE SSN IS DROPPED*/
%MACRO SSNXACC(TBL,ADKEY);
	PROC SORT DATA=&TBL; BY BF_SSN &ADKEY; RUN;

	DATA &TBL(DROP=BF_SSN);
		MERGE SSNXACC(IN=B) &TBL(IN=A);
		BY BF_SSN;
		IF A AND B;
	RUN;

	PROC SORT DATA=&TBL; BY DF_SPE_ACC_ID &ADKEY; RUN;
%MEND;

/*******************************************
* BORROWER DATA
********************************************/
PROC SQL;
CREATE TABLE SSNXACC AS
	SELECT DISTINCT 
		PDXX.DF_SPE_ACC_ID AS DF_SPE_ACC_ID,
		PDXX.DF_PRS_ID AS BF_SSN
	FROM 
		PKUB.PDXX_PRS_NME PDXX
		LEFT JOIN PKUB.LNXX_LON LNXX
			ON PDXX.DF_PRS_ID = LNXX.BF_SSN
	WHERE 
		COALESCE(LNXX.LC_STA_LONXX,'') NOT IN ('P','J')
		AND PDXX.DF_SPE_ACC_ID ^= ''
	;
QUIT;
PROC SORT DATA=SSNXACC; BY BF_SSN; RUN;

/*******************************************
* FORBEARANCE DATA
********************************************/
PROC SQL;
CONNECT TO DBX (DATABASE=&DB);
CREATE TABLE FBXX AS
	SELECT *
	FROM CONNECTION TO DBX 
	(
		SELECT 
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			LNXX.LF_FOR_CTL_NUM,
			LNXX.LN_FOR_OCC_SEQ,
			FBXX.LC_FOR_TYP,
			FBXX.LD_FOR_INF_CER,
			LNXX.LD_FOR_BEG,
			LNXX.LD_FOR_END,
			LNXX.LC_LON_LEV_FOR_CAP ,
			LNXX.LC_STA_LONXX,
			FBXX.LC_FOR_STA,
			FBXX.LC_STA_FORXX,
			COALESCE(FBXX.LA_REQ_RDC_PAY,X) AS LA_REQ_RDC_PAY,
			LNXX.LI_FOR_VRB_DFL_RUL
		FROM 
			PKUB.LNXX_BR_FOR_APV LNXX
			INNER JOIN PKUB.FBXX_BR_FOR_REQ FBXX
				ON LNXX.BF_SSN = FBXX.BF_SSN
				AND LNXX.LF_FOR_CTL_NUM = FBXX.LF_FOR_CTL_NUM
		WHERE
			LNXX.LF_LST_DTS_LNXX >= &LAST_RUNPASS
			OR FBXX.LF_LST_DTS_FBXX >= &LAST_RUNPASS

	FOR READ ONLY WITH UR
	);
DISCONNECT FROM DBX;
QUIT;
%SSNXACC(FBXX,LN_SEQ LF_FOR_CTL_NUM LN_FOR_OCC_SEQ);

/*******************************************
* LOAN DATA
********************************************/
PROC SQL;
CONNECT TO DBX (DATABASE=&DB);
CREATE TABLE LNXX AS
	SELECT *
	FROM CONNECTION TO DBX 
	(
		SELECT 
			LNXX.BF_SSN,
			LNXX.LN_SEQ, 
			LNXX.LC_STA_LONXX, 
			LNXX.LA_CUR_PRI, 
			LNXX.LA_LON_AMT_GTR, 
			LNXX.LD_END_GRC_PRD,
			LNXX.IC_LON_PGM, 
			LNXX.LD_LON_X_DSB, 
			LNXX.LD_PIF_RPT,
			LNXX.LC_SST_LONXX,
			LNXX.LF_LON_CUR_OWN,
			LNXX.LF_DOE_SCL_ORG
		FROM 
			PKUB.LNXX_LON LNXX
		WHERE
			LNXX.LC_STA_LONXX NOT IN ('P','J')

	FOR READ ONLY WITH UR
	);
DISCONNECT FROM DBX;
QUIT;
%SSNXACC(LNXX,LN_SEQ);

/*********************************************
* DELINQUENCY DATA
**********************************************/
PROC SQL;
CONNECT TO DBX (DATABASE=&DB);
CREATE TABLE LNXX AS
	SELECT *
	FROM CONNECTION TO DBX
	(
		SELECT 
			LNXX.BF_SSN,
			LNXX.LN_SEQ,
			LNXX.LN_DLQ_SEQ,
			LNXX.LD_DLQ_OCC,
			CASE WHEN LNXX.LC_STA_LONXX ^= 'X' OR (LNXX.LC_STA_LONXX = 'X' AND LNXX.LD_DLQ_MAX ^= Current Date - X Day) THEN X ELSE LNXX.LN_DLQ_MAX END AS LN_DLQ_MAX,
			CASE WHEN LNXX.LC_STA_LONXX ^= 'X' OR (LNXX.LC_STA_LONXX = 'X' AND LNXX.LD_DLQ_MAX ^= Current Date - X Day) THEN NULL ELSE LNXX.LD_DLQ_MAX END AS LD_DLQ_MAX
		FROM
			PKUB.LNXX_LON_DLQ_HST LNXX
		WHERE
			LNXX.LF_LST_DTS_LNXX >= &LAST_RUNPASS

	FOR READ ONLY WITH UR
	);
DISCONNECT FROM DBX;
QUIT;
PROC SORT DATA=LNXX; BY BF_SSN LN_SEQ DESCENDING LN_DLQ_SEQ; RUN;

DATA LNXX;
	SET LNXX(DROP=LN_DLQ_SEQ);
	BY BF_SSN LN_SEQ;
	IF FIRST.LN_SEQ;
RUN;
%SSNXACC(LNXX,LN_SEQ);

/*********************************************
* DEMOGRAPHICS
**********************************************/
PROC SQL;
CONNECT TO DBX (DATABASE=&DB);
CREATE TABLE PDXX AS
	SELECT *
	FROM CONNECTION TO DBX 
	(
		SELECT DISTINCT 
			PDXX.DF_SPE_ACC_ID,
			PDXX.DF_PRS_ID AS BF_SSN,
			PDXX.DM_PRS_X,
			PDXX.DM_PRS_LST,
			PDXX.DM_PRS_MID,
			PDXX.DD_BRT
		FROM 
			PKUB.PDXX_PRS_NME PDXX
		WHERE 
			SUBSTR(DF_PRS_ID,X,X) != 'P'
			AND PDXX.DF_LST_DTS_PDXX >= &LAST_RUNPASS

	FOR READ ONLY WITH UR
	);
DISCONNECT FROM DBX;
QUIT;

PROC SQL;
CONNECT TO DBX (DATABASE=&DB);
CREATE TABLE PDXX AS
	SELECT *
	FROM CONNECTION TO DBX 
	(
		SELECT DISTINCT 
			PDXX.DF_PRS_ID AS BF_SSN,
			PDXX.DX_STR_ADR_X,
			PDXX.DX_STR_ADR_X,
			PDXX.DM_CT,
			PDXX.DC_DOM_ST,
			PDXX.DF_ZIP_CDE,
			PDXX.DM_FGN_ST,
			PDXX.DM_FGN_CNY,
			PDXX.DD_VER_ADR,
			PDXX.DI_VLD_ADR
		FROM 
			PKUB.PDXX_PRS_ADR PDXX
		WHERE 
			PDXX.DC_ADR = 'L'
			AND PDXX.DF_LST_DTS_PDXX >= &LAST_RUNPASS

	FOR READ ONLY WITH UR
	);
DISCONNECT FROM DBX;
QUIT;
%SSNXACC(PDXX,);

PROC SQL;
CONNECT TO DBX (DATABASE=&DB);
CREATE TABLE PDXX AS
	SELECT *
	FROM CONNECTION TO DBX
	(
		SELECT DISTINCT 
			PDXX.DF_PRS_ID AS BF_SSN,
			PDXX.DC_PHN,
			PDXX.DC_ALW_ADL_PHN,
			PDXX.DD_PHN_VER,
			PDXX.DI_PHN_VLD,
			PDXX.DN_DOM_PHN_ARA,
			PDXX.DN_DOM_PHN_XCH,
			PDXX.DN_DOM_PHN_LCL,
			PDXX.DN_PHN_XTN,
			PDXX.DN_FGN_PHN_CNY,
			PDXX.DN_FGN_PHN_CT,
			PDXX.DN_FGN_PHN_LCL
		FROM  
			PKUB.PDXX_PRS_PHN PDXX
		WHERE 
			PDXX.DF_LST_DTS_PDXX >= &LAST_RUNPASS

	FOR READ ONLY WITH UR
	);
DISCONNECT FROM DBX;
QUIT;
%SSNXACC(PDXX,DC_PHN);

PROC SQL;
CONNECT TO DBX (DATABASE=&DB);
CREATE TABLE PDXX AS
	SELECT *
	FROM CONNECTION TO DBX
	(
		SELECT DISTINCT
			PDXX.DF_PRS_ID AS BF_SSN,
			PDXX.DC_ADR_EML,
			PDXX.DX_ADR_EML,
			PDXX.DD_VER_ADR_EML,
			PDXX.DI_VLD_ADR_EML,
			PDXX.DC_STA_PDXX
		FROM 
			PKUB.PDXX_PRS_ADR_EML PDXX
		WHERE 
			PDXX.DF_LST_DTS_PDXX >= &LAST_RUNPASS
			AND PDXX.DC_STA_PDXX = 'A'

	FOR READ ONLY WITH UR
	);
DISCONNECT FROM DBX;
QUIT;
PROC SORT DATA=PDXX; BY BF_SSN DC_ADR_EML DC_STA_PDXX ; RUN;

DATA PDXX(DROP=DC_STA_PDXX);
	SET PDXX;
	BY BF_SSN DC_ADR_EML;
	IF FIRST.DC_ADR_EML;
RUN;
%SSNXACC(PDXX,DC_ADR_EML);

/*********************************************
* ADDITIONAL LOAN DATA
**********************************************/
PROC SQL;
CONNECT TO DBX (DATABASE=&DB);
CREATE TABLE DWXX AS
	SELECT *
	FROM CONNECTION TO DBX 
	(
		SELECT
			DWXX.BF_SSN,
			DWXX.LN_SEQ,
			DWXX.WC_DW_LON_STA,
			DWXX.WA_TOT_BRI_OTS,
			DWXX.WD_LON_RPD_SR,
			DWXX.WX_OVR_DW_LON_STA
		FROM
			PKUB.DWXX_DW_CLC_CLU DWXX

	FOR READ ONLY WITH UR
	);
DISCONNECT FROM DBX;
QUIT;
%SSNXACC(DWXX,LN_SEQ);

/*********************************************
* ACTIVITY HISTORY
**********************************************/
PROC SQL;
CONNECT TO DBX (DATABASE=&DB);
CREATE TABLE ARCS AS
	SELECT *
	FROM CONNECTION TO DBX 
	(
		SELECT 
			AYXX.BF_SSN,
			AYXX.LN_ATY_SEQ,
			AYXX.PF_REQ_ACT,
			AYXX.LC_STA_ACTYXX,
			LX_ATY
		FROM
			PKUB.AYXX_BR_LON_ATY AYXX
			LEFT JOIN PKUB.AYXX_ATY_CMT AYXX
				ON AYXX.BF_SSN = AYXX.BF_SSN 
				AND AYXX.LN_ATY_SEQ = AYXX.LN_ATY_SEQ
				AND AYXX.LN_ATY_CMT_SEQ = X
		 	LEFT JOIN PKUB.AYXX_ATY_TXT AYXX
				ON AYXX.BF_SSN = AYXX.BF_SSN 
				AND AYXX.LN_ATY_SEQ = AYXX.LN_ATY_SEQ
				AND AYXX.LN_ATY_CMT_SEQ = AYXX.LN_ATY_CMT_SEQ
		WHERE 
			AYXX.PF_REQ_ACT IN ('DRLFA','KXADD','KXPHN','MXXXX')
			AND AYXX.LC_STA_ACTYXX = 'A'
			AND 
			(
				AYXX.LF_LST_DTS_AYXX >= &LAST_RUNPASS 
				OR AYXX.PF_REQ_ACT = 'DRLFA'
			)

	FOR READ ONLY WITH UR
	);

/*******************************************
* REPAYMENT SCHEDULE DATA
********************************************/
PROC SQL;
CREATE TABLE LNXX AS
	SELECT 
		LNXX.BF_SSN,
		LNXX.LN_SEQ,
		LNXX.LN_GRD_RPS_SEQ,
		CASE WHEN DWXX.WX_OVR_DW_LON_STA = 'LITIGATION' THEN X
			 ELSE LNXX.LN_RPS_TRM
		END AS LN_RPS_TRM,
		CASE WHEN DWXX.WX_OVR_DW_LON_STA = 'LITIGATION' THEN .
			 ELSE RSXX.LD_RPS_X_PAY_DU
		END AS LD_RPS_X_PAY_DU,
		RSXX.LD_SNT_RPD_DIS,
		LNXX.LD_CRT_LONXX,
		LNXX.LC_TYP_SCH_DIS,
		CASE WHEN DWXX.WX_OVR_DW_LON_STA = 'LITIGATION' THEN X
			 ELSE LNXX.LA_RPS_ISL
		END AS LA_RPS_ISL
	FROM
		PKUB.RSXX_BR_RPD RSXX
		INNER JOIN PKUB.LNXX_LON_RPS LNXX
			ON RSXX.BF_SSN = LNXX.BF_SSN
			AND RSXX.LN_RPS_SEQ = LNXX.LN_RPS_SEQ
		INNER JOIN PKUB.LNXX_LON_RPS_SPF LNXX
			ON LNXX.BF_SSN = LNXX.BF_SSN
			AND LNXX.LN_SEQ = LNXX.LN_SEQ
			AND LNXX.LN_RPS_SEQ = LNXX.LN_RPS_SEQ
		INNER JOIN PKUB.DWXX_DW_CLC_CLU DWXX
			ON LNXX.BF_SSN = DWXX.BF_SSN
			AND LNXX.LN_SEQ = DWXX.LN_SEQ
	WHERE 
		LNXX.LC_STA_LONXX = 'A'
;
QUIT;
PROC SORT DATA=LNXX; BY BF_SSN LN_SEQ LN_GRD_RPS_SEQ; RUN;

DATA LNXX(DROP= A B C NEXT_SEQ LD_RPS_X_PAY_DU LN_GRD_RPS_SEQ);
	SET LNXX;
	FORMAT NEXT_SEQ DATEX.;
	BY BF_SSN LN_SEQ LN_GRD_RPS_SEQ;
	RETAIN NEXT_SEQ A C B;
	IF FIRST.LN_SEQ THEN DO;
		A = .;
		NEXT_SEQ = INTNX('MONTH',LD_RPS_X_PAY_DU,LN_RPS_TRM,'S');
		IF NEXT_SEQ > TODAY() THEN DO;
			A = LN_GRD_RPS_SEQ ;
			C = LA_RPS_ISL ;
		END;
	END;
	ELSE IF A= . THEN DO;
		NEXT_SEQ = INTNX('MONTH',NEXT_SEQ,LN_RPS_TRM,'S');
		IF NEXT_SEQ > TODAY() THEN DO;
			A = LN_GRD_RPS_SEQ ;
			C = LA_RPS_ISL ;
		END;
	END;
	IF FIRST.LN_SEQ THEN B = LN_RPS_TRM;
	ELSE B = B + LN_RPS_TRM;
	IF LAST.LN_SEQ THEN DO;
		LN_RPS_TRM = B;
		LA_RPS_ISL = C;
		LN_GRD_RPS_SEQ = A;
		DAY_DUE = DAY(LD_RPS_X_PAY_DU);
		OUTPUT;
	END;
RUN;
%SSNXACC(LNXX,LN_SEQ);

ENDRSUBMIT;

LIBNAME LEGEND 'T:\SAS\CDW';

DATA FBXX; SET LEGEND.FBXX; RUN; *X;
DATA PDXX; SET LEGEND.PDXX; RUN; *X;
DATA LNXX; SET LEGEND.LNXX; RUN; *XX;
DATA LNXX; SET LEGEND.LNXX; RUN; *XX;
DATA LNXX; SET LEGEND.LNXX; RUN; *XX;
DATA PDXX; SET LEGEND.PDXX; RUN; *XX;
DATA PDXX; SET LEGEND.PDXX; RUN; *XX;
DATA PDXX; SET LEGEND.PDXX; RUN; *XX;
DATA DWXX; SET LEGEND.DWXX; RUN; *XX;

DATA _NULL_;
	SET FBXX END = eof;
	FILE REPORTX DELIMITER=',' DSD DROPOVER LRECL=XXXXX;
	FORMAT LD_FOR_INF_CER LD_FOR_BEG LD_FOR_END MMDDYYXX. LA_REQ_RDC_PAY X.X;
	IF _N_ = X THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LF_FOR_CTL_NUM @;
		PUT LN_FOR_OCC_SEQ @;
		PUT LC_FOR_TYP @;
		PUT LD_FOR_INF_CER @;
		PUT LD_FOR_BEG @;
		PUT LD_FOR_END @;
		PUT LC_LON_LEV_FOR_CAP @;
		PUT LC_STA_LONXX @;
		PUT LC_FOR_STA @;
		PUT LC_STA_FORXX @;
		PUT LA_REQ_RDC_PAY @;
		PUT LI_FOR_VRB_DFL_RUL $;
	END;
	IF eof THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET PDXX END = eof;
	FILE REPORTX DELIMITER=',' DSD DROPOVER LRECL=XXXXX;
	FORMAT DD_BRT MMDDYYXX.;
	IF _N_ = X THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT BF_SSN @;
		PUT DM_PRS_X @;
		PUT DM_PRS_LST @;
		PUT DM_PRS_MID @;
		PUT DD_BRT $;
	END;
	IF eof THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET LNXX END = eof;
	FILE REPORTXX DELIMITER=',' DSD DROPOVER LRECL=XXXXX;
	FORMAT LD_END_GRC_PRD LD_LON_X_DSB  LD_PIF_RPT MMDDYYXX. ;
	IF _N_ = X THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LC_STA_LONXX @;
		PUT LA_CUR_PRI @;
		PUT LA_LON_AMT_GTR @;
		PUT LD_END_GRC_PRD @;
		PUT IC_LON_PGM @;
		PUT LD_LON_X_DSB @;
		PUT LD_PIF_RPT @;
		PUT LC_SST_LONXX @;
		PUT LF_LON_CUR_OWN @;
		PUT LF_DOE_SCL_ORG $;
	END;
	IF eof THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET LNXX END = eof;
	FILE REPORTXX DELIMITER=',' DSD DROPOVER LRECL=XXXXX;
	FORMAT LD_CRT_LONXX LD_SNT_RPD_DIS MMDDYYXX. ;
	IF _N_ = X THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ  @;
		PUT LD_CRT_LONXX @;	
		PUT LC_TYP_SCH_DIS @; 
		PUT LD_SNT_RPD_DIS @;
		PUT LA_RPS_ISL @;
		PUT DAY_DUE @;
		PUT LN_RPS_TRM $;
	END;
	IF eof THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET LNXX END = eof;
	FILE REPORTXX DELIMITER=',' DSD DROPOVER LRECL=XXXXX;
	FORMAT LD_DLQ_OCC LD_DLQ_MAX MMDDYYXX.;
	IF _N_ = X THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LD_DLQ_OCC @;
		PUT LN_DLQ_MAX @;
		PUT LD_DLQ_MAX $;
	END;
	IF eof THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET PDXX END = eof;
	FILE REPORTXX DELIMITER=',' DSD DROPOVER LRECL=XXXXX;
	FORMAT DD_VER_ADR_EML MMDDYYXX.;
	IF _N_ = X THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT DC_ADR_EML @;
		PUT DX_ADR_EML @;
		PUT DD_VER_ADR_EML @;
		PUT DI_VLD_ADR_EML $;
	END;
	IF eof THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET PDXX END = eof;
	FILE REPORTXX DELIMITER=',' DSD DROPOVER LRECL=XXXXX;
	FORMAT DD_VER_ADR MMDDYYXX.;
	IF _N_ = X THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT DX_STR_ADR_X @;
		PUT DX_STR_ADR_X @;
		PUT DM_CT @;
		PUT DC_DOM_ST @;
		PUT DF_ZIP_CDE @;
		PUT DM_FGN_ST @;
		PUT DM_FGN_CNY @;
		PUT DD_VER_ADR @;
		PUT DI_VLD_ADR $;
	END;
	IF eof THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET PDXX END = eof;
	FILE REPORTXX DELIMITER=',' DSD DROPOVER LRECL=XXXXX;
	FORMAT DD_PHN_VER MMDDYYXX.;
	IF _N_ = X THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT DC_PHN @;
		PUT DC_ALW_ADL_PHN @;
		PUT DD_PHN_VER @;
		PUT DI_PHN_VLD @;
		PUT DN_DOM_PHN_ARA @;
		PUT DN_DOM_PHN_XCH @;
		PUT DN_DOM_PHN_LCL @;
		PUT DN_PHN_XTN @;
		PUT DN_FGN_PHN_CNY @;
		PUT DN_FGN_PHN_CT @;
		PUT DN_FGN_PHN_LCL $;
	END;
	IF eof THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET DWXX END = eof;
	FILE REPORTXX DELIMITER=',' DSD DROPOVER LRECL=XXXXX;
	FORMAT WA_TOT_BRI_OTS X.X WD_LON_RPD_SR mmddyyXX.;
	IF _N_ = X THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ  @;
		PUT WC_DW_LON_STA  @;
		PUT WA_TOT_BRI_OTS @;
		PUT WD_LON_RPD_SR @;
		PUT WX_OVR_DW_LON_STA $;
	END;
	IF eof THEN PUT "-End-";
RUN;
