SELECT
	*
FROM
	OPENQUERY
	(
		LEGEND,
		'
			SELECT DISTINCT
				PDXX.DF_PRS_ID,
				PDXX.DM_PRS_X,
				PDXX.DM_PRS_LST,
				PDXX.DX_ADR_EML,
				PDXX.DI_VLD_ADR_EML,
				LNXX.LC_STA_LONXX,
				LNXX.LN_DLQ_MAX
			FROM
				PKUB.PDXX_PRS_NME PDXX
				LEFT JOIN PKUB.PDXX_PRS_ADR_EML PDXX ON PDXX.DF_PRS_ID = PDXX.DF_PRS_ID
				INNER JOIN PKUB.LNXX_LON_DLQ_HST LNXX ON LNXX.BF_SSN = PDXX.DF_PRS_ID
			WHERE
				LNXX.LN_DLQ_MAX BETWEEN X AND XXX -- between is inclusive
				AND
				PDXX.DI_VLD_ADR_EML = ''Y''
				AND
				LNXX.LC_STA_LONXX = X
		'
	)
