LIBNAME DUSTER REMOTE SERVER=DUSTER SLIBREF=WORK;
RSUBMIT;
LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;

PROC SQL;
	CREATE TABLE CURE AS
		SELECT
			PD10.DF_SPE_ACC_ID,
			LN10.LN_SEQ
		FROM
			OLWHRM1.PD10_PRS_NME PD10
			JOIN OLWHRM1.LN10_LON LN10
				ON PD10.DF_PRS_ID = LN10.BF_SSN
			JOIN OLWHRM1.DW01_DW_CLC_CLU DW01
				ON LN10.BF_SSN = DW01.BF_SSN
				AND LN10.LN_SEQ = DW01.LN_SEQ
		WHERE 
			LN10.LA_CUR_PRI > 0
			AND LN10.LC_STA_LON10 = 'R'
			AND DW01.WC_DW_LON_STA = '06'
	;
QUIT;

ENDRSUBMIT;

PROC EXPORT
		DATA=DUSTER.CURE
		OUTFILE='T:\SAS\NHUH 17928.XLSX'
		REPLACE;
RUN;
