SELECT DISTINCT
	LN38.BF_SSN,
	LN38.LN_SEQ,
	LN38.LN_CU_SEQ,
	LN38.LC_CU_STA,
	LN33.LD_CU_END
FROM
	UDW..LN38_CU_STA_HST LN38
	INNER JOIN 
	(
		SELECT
			BF_SSN,
			LN_SEQ,
			MAX(LF_LST_DTS_LN38) AS max_LF_LST_DTS_LN38
		FROM
			UDW..LN38_CU_STA_HST 
		GROUP BY
			BF_SSN,
			LN_SEQ
	) LN38_MAX
		ON LN38.BF_SSN = LN38_MAX.BF_SSN
		AND LN38.LN_SEQ = LN38_MAX.LN_SEQ
		AND LN38.LF_LST_DTS_LN38 = LN38_MAX.max_LF_LST_DTS_LN38
	INNER JOIN UDW..LN33_LON_CU_INF LN33
		ON LN38.BF_SSN = LN33.BF_SSN
		AND LN38.LN_SEQ = LN33.LN_SEQ
		AND LN38.LN_CU_SEQ = LN33.LN_CU_SEQ
WHERE
	LN38.LC_CU_STA = 'S'
	AND LN33.LD_CU_END IS NOT NULL
;



--DECLARE @SSN VARCHAR(9) = (
--SELECT DF_PRS_ID FROM UDW..PD10_PRS_NME WHERE DF_PRS_ID LIKE '%0543' AND DM_PRS_LST = 'PERREAULT' AND DM_PRS_1 = 'DOUGLAS'
--)

--SELECT * FROM UDW..LN38_CU_STA_HST WHERE BF_SSN = @SSN
--SELECT * FROM UDW..LN33_LON_CU_INF WHERE BF_SSN = @SSN
----SELECT * FROM UDW..LN10_LON WHERE BF_SSN LIKE '%0543'
--SELECT * FROM UDW..LK10_LS_CDE_LKP WHERE PM_ATR = 'LC-CU-STA' ORDER BY PX_ATR_VAL
--SELECT * FROM UDW..LK10_LS_CDE_LKP WHERE PM_ATR = 'WC-DW-LON-STA' ORDER BY PX_ATR_VAL
----SELECT * FROM UDW..DW01_DW_CLC_CLU WHERE BF_SSN = @SSN
--select TOP 10 * from udw..DW01_DW_CLC_CLU WHERE WC_DW_LON_STA = '06'
