LIBNAME BSYS ODBC %STR(REQUIRED="FILEDSN=X:\PADR\ODBC\BSYS.dsn; update_lock_typ=nolock; bl_keepnulls=no");

PROC SQL;
CREATE TABLE DOCDETAIL AS
	SELECT
	DET.ID AS LETTER_ID
	,DET.DocID AS DOC_ID
	,DET.DocName AS DOCUMENT_TITLE
	,DET.DocTyp AS DOCUMENT_TYPE
	,DET.Description AS DESCRIPTION
FROM
	BSYS.LTDB_DAT_DocDetail DET
WHERE
	DET.Status = 'Active'
ORDER BY
	DOCUMENT_TITLE;
QUIT;

PROC EXPORT 
	DATA= WORK.DOCDETAIL
	OUTFILE= "T:\SAS\UNH 57374.XLSX" 
	DBMS=XLSX
	REPLACE
	;
	SHEET="A"; 
RUN;
