LIBNAME  DUSTER  REMOTE  SERVER=DUSTER  SLIBREF=WORK;
RSUBMIT;

PROC SQL;
	CONNECT TO DB2 (DATABASE=DLGSUTWH);

	CREATE TABLE DEMO AS
		SELECT 
			*
		FROM 
			CONNECTION TO DB2 
				(
					SELECT DISTINCT
						LF_LON_CUR_OWN
					FROM	
						OLWHRM1.LN10_LON
					WHERE	
						LC_STA_LON10 = 'R'
						AND LA_CUR_PRI > 0

					FOR READ ONLY WITH UR
				)
	;

	DISCONNECT FROM DB2;
QUIT;

ENDRSUBMIT;

PROC EXPORT DATA = DUSTER.DEMO 
            OUTFILE = "T:\SAS\NH 18318.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="A"; 
RUN;
