LIBNAME XL 'T:\LN66 DCR.xlsx';

DATA DUSTER.LN66DCR; SET XL.'LN66$'N; RUN;

LIBNAME DUSTER REMOTE SERVER=DUSTER SLIBREF=WORK;
RSUBMIT;
LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
PROC SQL;
	CREATE TABLE LN66INFO AS
		SELECT
			DCR.*,
			LN66.LN_RPS_TRM
		FROM
			LN66DCR DCR
			JOIN OLWHRM1.LN66_LON_RPS_SPF LN66
				ON DCR.BF_SSN = LN66.BF_SSN
				AND DCR.LN_SEQ = LN66.LN_SEQ
				AND DCR.LN_RPS_SEQ = LN66.LN_RPS_SEQ
				AND DCR.LN_GRD_RPS_SEQ = LN66.LN_GRD_RPS_SEQ
	;
QUIT;
ENDRSUBMIT;

DATA LN66INFO; SET DUSTER.LN66INFO; RUN;

PROC EXPORT
		DATA=LN66INFO
		OUTFILE='T:\SAS\LN66 DCR Data Needed.xlsx'
		REPLACE;
RUN;
