DECLARE @BEGIN AS DATE = '2000-01-01'
DECLARE @END AS DATE = GETDATE()

DECLARE @Temp TABLE(BF_SSN CHAR(9), LF_DOE_SCL_ORG VARCHAR(8), PENDING INT, APPROVED INT, DENIED INT)
INSERT INTO @Temp 
--closed school
SELECT DISTINCT
	LN10.BF_SSN
	,LN10.LF_DOE_SCL_ORG
	,(CASE WHEN CSFSA.BF_SSN IS NOT NULL AND ADCSH.BF_SSN IS NULL AND CSDNY.BF_SSN IS NULL THEN 1 ELSE 0 END) AS PENDING
	,(CASE WHEN ADCSH.BF_SSN IS NOT NULL THEN 1 ELSE 0 END) AS APPROVED
	,(CASE WHEN CSDNY.BF_SSN IS NOT NULL AND ADCSH.BF_SSN IS NOT NULL THEN 0
	          WHEN CSDNY.BF_SSN IS NOT NULL THEN 1 ELSE 0 END) AS DENIED
FROM
	CDW..LN10_LON LN10
	INNER JOIN
	(
		SELECT DISTINCT
			AY10.BF_SSN
		FROM
			CDW..AY10_BR_LON_ATY AY10
		WHERE
			AY10.LD_ATY_REQ_RCV BETWEEN  @BEGIN AND @END
			AND AY10.PF_REQ_ACT = 'DICSK'
	) DICSK
		ON DICSK.BF_SSN = LN10.BF_SSN
	LEFT JOIN
	(
		SELECT DISTINCT
			AY10.BF_SSN
		FROM
			CDW..AY10_BR_LON_ATY AY10
		WHERE
			AY10.LD_ATY_REQ_RCV BETWEEN  @BEGIN AND @END
			AND AY10.PF_REQ_ACT = 'CSFSA'
	) CSFSA
		ON DICSK.BF_SSN = CSFSA.BF_SSN
	LEFT JOIN
	(
		SELECT DISTINCT
			AY10.BF_SSN
		FROM
			CDW..AY10_BR_LON_ATY AY10
		WHERE
			AY10.LD_ATY_REQ_RCV BETWEEN  @BEGIN AND @END
			AND AY10.PF_REQ_ACT = 'ADCSH'
	) ADCSH
		ON DICSK.BF_SSN = ADCSH.BF_SSN
	LEFT JOIN
	(
		SELECT DISTINCT
			AY10.BF_SSN
		FROM
			CDW..AY10_BR_LON_ATY AY10
		WHERE
			AY10.LD_ATY_REQ_RCV BETWEEN  @BEGIN AND @END
			AND AY10.PF_REQ_ACT = 'CSDNY'
	) CSDNY
		ON DICSK.BF_SSN = CSDNY.BF_SSN
WHERE
	LN10.LF_DOE_SCL_ORG IN ('00464208','00464201','00464209','00464206','00464204','00464203','00464205','00464207','00464202','00464200')


SELECT * FROM @Temp

SELECT DISTINCT
	LF_DOE_SCL_ORG
	,SUM(PENDING) AS PENDING
	,SUM(APPROVED) AS APPROVED
	,SUM(DENIED) AS DENIED
FROM
	@Temp
GROUP BY
	LF_DOE_SCL_ORG