
LIBNAME  DUSTER  REMOTE  SERVER=DUSTER  SLIBREF=WORK;
RSUBMIT;


PROC SQL;
	CONNECT TO DB2 (DATABASE=DLGSUTWH);

	CREATE TABLE DEMO AS
		SELECT 
			*
		FROM 
			CONNECTION TO DB2 
				(
					SELECT DISTINCT
						TRIM(PD10.DM_PRS_1) || ' ' || TRIM(PD10.DM_PRS_MID) || ' ' || TRIM(PD10.DM_PRS_LST) AS BORROWER_NAME,
						LN10.BF_SSN AS SSN,
						CASE 
							WHEN LN10.IC_LON_PGM = 'STFFRD' THEN 'SF'
							ELSE 'SU'
						END AS LOAN_TYP,
						LN10.LD_LON_1_DSB AS FIRST_DISBURSEMENT_DATE,
						LN10.LA_LON_AMT_GTR AS ORIGINAL_LOAN_AMOUNT,
						LN80.LA_BIL_CUR_DU AS AMOUNT_DUE,
						COALESCE(LN90.LA_FAT_CUR_PRI,0) + COALESCE(LN90.LA_FAT_NSI,0) + COALESCE(LN90.LA_FAT_LTE_FEE,0) AS PMT_AMT,
						LN90.LD_FAT_EFF AS PAYMENT_EFFECTIVE_DATE
					FROM
						OLWHRM1.PD10_PRS_NME PD10
						JOIN OLWHRM1.LN10_LON LN10
							ON PD10.DF_PRS_ID = LN10.BF_SSN
						JOIN OLWHRM1.LN90_FIN_ATY LN90
							ON LN10.BF_SSN = LN90.BF_SSN
							AND LN10.LN_SEQ = LN90.LN_SEQ
						JOIN OLWHRM1.LN80_LON_BIL_CRF LN80
							ON LN10.BF_SSN = LN80.BF_SSN
							AND LN10.LN_SEQ = LN80.LN_SEQ
						JOIN OLWHRM1.LN75_BIL_LON_FAT LN75
							ON LN80.BF_SSN = LN75.BF_SSN
							AND LN80.LN_SEQ = LN75.LN_SEQ
							AND LN80.LD_BIL_CRT = LN75.LD_BIL_CRT
							AND LN80.LN_SEQ_BIL_WI_DTE = LN75.LN_SEQ_BIL_WI_DTE
							AND LN90.LN_FAT_SEQ = LN75.LN_FAT_SEQ
					WHERE
						LN90.PC_FAT_TYP = '10'
						AND LN90.PC_FAT_SUB_TYP IN ('10','15','20')
						AND LN90.LD_FAT_EFF BETWEEN '2012-10-01' AND '2013-09-30'
						AND LN10.IC_LON_PGM IN ('STFFRD','UNSTFD')
						AND LN80.LA_BIL_DU_PRT < LN80.LA_BIL_CUR_DU - 1
						AND DAYS(LN80.LD_BIL_DU_LON) > DAYS(LN90.LD_FAT_EFF) + 20
						AND LN80.LC_STA_LON80 = 'A'
						AND ((COALESCE(LN90.LA_FAT_CUR_PRI,0) + COALESCE(LN90.LA_FAT_NSI,0) + COALESCE(LN90.LA_FAT_LTE_FEE,0)) * -1) - 1 > LN80.LA_BIL_CUR_DU /*payments are saved as negative numbers*/
					ORDER BY
						LN10.BF_SSN,
						LN10.LD_LON_1_DSB

					FOR READ ONLY WITH UR
				)
	;

	DISCONNECT FROM DB2;
QUIT;

ENDRSUBMIT;

DATA DEMO; SET DUSTER.DEMO; RUN;

PROC EXPORT
		DATA = DEMO
		OUTFILE = 'T:\SAS\NHUH 17792.XLSX'
		DBMS = EXCEL2007
		REPLACE;
RUN;
