USE UDW
GO

WITH BWR_DATA AS
(
SELECT 
	PD10.DF_SPE_ACC_ID,
	DD_CRT_PD31,
	DC_DOM_ST_HST,
	DI_VLD_ADR_HST,
	LEAD(DD_CRT_PD31,1) OVER(PARTITION BY PD30.DF_PRS_ID ORDER BY DD_CRT_PD31) AS NEXT_D
FROM UDW..PD31_PRS_INA PD30
	INNER JOIN UDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = PD30.DF_PRS_ID
	INNER JOIN UDW..LN10_LON LN10
		ON LN10.BF_SSN = PD30.DF_PRS_ID
WHERE

	 LN10.LA_CUR_PRI > 0
	AND LN10.LC_STA_LON10 = 'R'

)
SELECT DISTINCT DF_SPE_ACC_ID INTO #DATA FROM BWR_DATA WHERE '10-01-2019' BETWEEN DD_CRT_PD31 AND NEXT_D AND DI_VLD_ADR_HST = 'Y' AND DC_DOM_ST_HST = 'NY';

SELECT DISTINCT
	PD10.DF_SPE_ACC_ID
FROM
	UDW..PD30_PRS_ADR PD30
	INNER JOIN UDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = PD30.DF_PRS_ID
	INNER JOIN UDW..LN10_LON LN10
		ON LN10.BF_SSN = PD30.DF_PRS_ID
WHERE
	DC_DOM_ST = 'NY'
	AND DI_VLD_ADR = 'Y'
	AND DD_VER_ADR <= '10-01-2019'
	AND LN10.LA_CUR_PRI > 0
	AND LN10.LC_STA_LON10 = 'R'

UNION

SELECT * FROM #DATA

