LIBNAME DUSTER REMOTE SERVER=DUSTER SLIBREF=WORK;
RSUBMIT;
LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
PROC SQL;
	CREATE TABLE SCRA AS
		SELECT DISTINCT
			LN72.BF_SSN, 
			LN72.LN_SEQ, 
			LN72.LD_STA_LON72
		FROM
			OLWHRM1.LN72_INT_RTE_HST LN72
		WHERE
			LN72.LC_STA_LON72 = 'A'
			AND LN72.LC_INT_RDC_PGM = 'M'
			AND LN72.LR_ITR = 6
			AND LN72.LD_STA_LON72 > '05DEC2014'D
	;
QUIT;
ENDRSUBMIT;

PROC EXPORT
		DATA=DUSTER.SCRA
		OUTFILE='T:\Audit Query - SCRA Military Rate 05DEC2014.XLSX'
		REPLACE;
RUN;
