--IBR Count
SELECT 
	Portfolio, 
	IBR AS CountBorrowers, 
	[MonthName] FROM OPENQUERY(DUSTER,
'
	SELECT
		CASE WHEN LN10.LF_LON_CUR_OWN IN (''829769'',''82976901'',''82976902'',''82976903'',''82976904'',''82976905'',''82976906'',''82976907'',''82976908'') THEN ''BANA''
		     WHEN LN10.LF_LON_CUR_OWN IN (''826717'',''830248'') THEN ''Align''
			 WHEN LN10.LF_LON_CUR_OWN LIKE ''828476%'' THEN ''Legacy''
			 ELSE CAST(LN10.LF_LON_CUR_OWN AS VARCHAR(15)) 
		END AS Portfolio,
		COUNT(DISTINCT RS05.BF_SSN) AS IBR,
		MONTHNAME(RS05.BD_ANV_QLF_IBR, ''CLDR 1.5:en_US'') AS MonthName,
		MONTH(RS05.BD_ANV_QLF_IBR) AS MonthNumber
	FROM
		OLWHRM1.LN10_LON LN10
		INNER JOIN OLWHRM1.RS05_IBR_RPS RS05
			ON RS05.BF_SSN = LN10.BF_SSN
			AND RS05.BC_STA_RS05 = ''A''
		INNER JOIN OLWHRM1.LN65_LON_RPS LN65
			ON LN65.BF_SSN = LN10.BF_SSN
			AND LN65.LN_SEQ = LN10.LN_SEQ
			AND LN65.LC_TYP_SCH_DIS = ''IB''
			AND LN65.LC_STA_LON65 = ''A''
	WHERE
		LN10.LC_STA_LON10 = ''R''
		AND LN10.LA_CUR_PRI > 0
		AND LN10.IC_LON_PGM NOT IN(''TILP'')
		AND RS05.BD_ANV_QLF_IBR IS NOT NULL
	GROUP BY
		CASE WHEN LN10.LF_LON_CUR_OWN IN (''829769'',''82976901'',''82976902'',''82976903'',''82976904'',''82976905'',''82976906'',''82976907'',''82976908'') THEN ''BANA''
		     WHEN LN10.LF_LON_CUR_OWN IN (''826717'',''830248'') THEN ''Align''
			 WHEN LN10.LF_LON_CUR_OWN LIKE ''828476%'' THEN ''Legacy''
			 ELSE CAST(LN10.LF_LON_CUR_OWN AS VARCHAR(15))
		END,
		MONTHNAME(RS05.BD_ANV_QLF_IBR, ''CLDR 1.5:en_US''),
		MONTH(RS05.BD_ANV_QLF_IBR)
	ORDER BY
		PORTFOLIO,
		MONTH(RS05.BD_ANV_QLF_IBR)
'
) 

--Payment breakout for IBR borrowers
SELECT 
	Portfolio,  
	Payment0 AS [$0 Payment], 
	NegAm1 AS [NegAm > $1],
	LessThan50 AS [<$50],
	GreaterThan50 AS [>=$50]  
FROM OPENQUERY(DUSTER,
'
	SELECT
		CASE WHEN LN10.LF_LON_CUR_OWN IN (''829769'',''82976901'',''82976902'',''82976903'',''82976904'',''82976905'',''82976906'',''82976907'',''82976908'') THEN ''BANA''
		     WHEN LN10.LF_LON_CUR_OWN IN (''826717'',''830248'') THEN ''Align''
			 WHEN LN10.LF_LON_CUR_OWN LIKE ''828476%'' THEN ''Legacy''
			 ELSE CAST(LN10.LF_LON_CUR_OWN AS VARCHAR(15)) 
		END AS Portfolio,
		SUM(CASE WHEN LN66.LA_RPS_ISL = 0.00 THEN 1 ELSE 0 END) AS Payment0,
		SUM(CASE WHEN LN66.LA_RPS_ISL >= 1.00 AND LN65.LI_ICR_RPD_NEG_AMR = ''Y'' THEN 1 ELSE 0 END) AS NegAm1,
		SUM(CASE WHEN LN66.LA_RPS_ISL < 50.00 AND COALESCE(LN65.LI_ICR_RPD_NEG_AMR,''N'') = ''N'' THEN 1 ELSE 0 END) AS LessThan50,
		SUM(CASE WHEN LN66.LA_RPS_ISL >= 50.00 THEN 1 ELSE 0 END) AS GreaterThan50
	FROM
		OLWHRM1.LN10_LON LN10
		INNER JOIN OLWHRM1.RS05_IBR_RPS RS05
			ON RS05.BF_SSN = LN10.BF_SSN
			AND RS05.BC_STA_RS05 = ''A''
		INNER JOIN OLWHRM1.LN65_LON_RPS LN65
			ON LN65.BF_SSN = LN10.BF_SSN
			AND LN65.LN_SEQ = LN10.LN_SEQ
			AND LN65.LC_STA_LON65 = ''A''
			AND LN65.LC_TYP_SCH_DIS = ''IB''
		INNER JOIN OLWHRM1.LN66_LON_RPS_SPF LN66
			ON LN66.BF_SSN = LN65.BF_SSN
			AND LN66.LN_SEQ = LN65.LN_SEQ
			AND LN66.LN_RPS_SEQ = LN65.LN_RPS_SEQ
	WHERE
		LN10.LC_STA_LON10 = ''R''
		AND LN10.LA_CUR_PRI > 0
		AND LN10.IC_LON_PGM NOT IN(''TILP'')
	GROUP BY
		CASE WHEN LN10.LF_LON_CUR_OWN IN (''829769'',''82976901'',''82976902'',''82976903'',''82976904'',''82976905'',''82976906'',''82976907'',''82976908'') THEN ''BANA''
		     WHEN LN10.LF_LON_CUR_OWN IN (''826717'',''830248'') THEN ''Align''
			 WHEN LN10.LF_LON_CUR_OWN LIKE ''828476%'' THEN ''Legacy''
			 ELSE CAST(LN10.LF_LON_CUR_OWN AS VARCHAR(15))
		END
	ORDER BY
		PORTFOLIO
'
) 

--Non IBR Status
SELECT 
	Portfolio AS Portfolio,
	SUM(NOTIBR) AS CountBorrowers,
	CASE WHEN WC_DW_LON_STA ='01' THEN 'IN GRACE'
			WHEN WC_DW_LON_STA ='02' THEN 'IN SCHOOL'
			WHEN WC_DW_LON_STA ='03' THEN 
			CASE WHEN LC_TYP_SCH_DIS ='AG' THEN 'IN REPAYMENT-MODIFIED GRADUATED REPAY SCHED'
					WHEN LC_TYP_SCH_DIS ='EG' THEN 'IN REPAYMENT-EXTENDED GRAD'
					WHEN LC_TYP_SCH_DIS ='EL' THEN 'IN REPAYMENT-EXTENDED LEVEL'
					WHEN LC_TYP_SCH_DIS ='E2' THEN 'IN REPAYMENT-EXTENDED SELECT 2'
					WHEN LC_TYP_SCH_DIS ='E5' THEN 'IN REPAYMENT-EXTENDED SELECT 5'
					WHEN LC_TYP_SCH_DIS ='E7' THEN 'IN REPAYMENT-EXTENDED SELECT 7'
					WHEN LC_TYP_SCH_DIS ='E8' THEN 'IN REPAYMENT-EXTENDED SELECT 8'
					WHEN LC_TYP_SCH_DIS ='G' THEN 'IN REPAYMENT-GRADUATED'
					WHEN LC_TYP_SCH_DIS ='GT' THEN 'IN REPAYMENT-GATE REPAY'
					WHEN LC_TYP_SCH_DIS ='IB' THEN 'IN REPAYMENT-PARTIAL FINANCIAL HARDSHIP'
					WHEN LC_TYP_SCH_DIS ='IL' THEN 'IN REPAYMENT-PERMANENT STANDARD'
					WHEN LC_TYP_SCH_DIS ='IP' THEN 'IN REPAYMENT-IBR 2014 PS'
					WHEN LC_TYP_SCH_DIS ='IS' THEN 'IN REPAYMENT-INCOME SENSITIVE'
					WHEN LC_TYP_SCH_DIS ='I3' THEN 'IN REPAYMENT-IBR 2014 PFH'
					WHEN LC_TYP_SCH_DIS ='L' THEN 'IN REPAYMENT-LEVEL'
					WHEN LC_TYP_SCH_DIS ='LO' THEN 'IN REPAYMENT-LEVEL OPTION'
					WHEN LC_TYP_SCH_DIS ='L1' THEN 'IN REPAYMENT-8/10% LEVEL'
					WHEN LC_TYP_SCH_DIS ='MG' THEN 'IN REPAYMENT-MODIFIED GRADUATED'
					WHEN LC_TYP_SCH_DIS ='P1' THEN 'IN REPAYMENT-PROGRAM OPTION 1'
					WHEN LC_TYP_SCH_DIS ='P2' THEN 'IN REPAYMENT-PROGRAM OPTION 2'
					WHEN LC_TYP_SCH_DIS ='RP' THEN 'IN REPAYMENT-REDUCED PAYMENTS'
					WHEN LC_TYP_SCH_DIS ='S1' THEN 'IN REPAYMENT-SELECT OPTION 1'
					WHEN LC_TYP_SCH_DIS ='S2' THEN 'IN REPAYMENT-SELECT OPTION 2'
					WHEN LC_TYP_SCH_DIS ='S3' THEN 'IN REPAYMENT-SELECT OPTION 3'
					WHEN LC_TYP_SCH_DIS ='S4' THEN 'IN REPAYMENT-SELECT OPTION 4'
					WHEN LC_TYP_SCH_DIS ='S5' THEN 'IN REPAYMENT-SELECT OPTION 5'
					WHEN LC_TYP_SCH_DIS ='S7' THEN 'IN REPAYMENT-SELECT OPTION 7'
					WHEN LC_TYP_SCH_DIS ='S8' THEN 'IN REPAYMENT-SELECT OPTION 8'
					ELSE 'IN REPAYMENT-UNKNOWN SCHEDULE TYPE'
			END
			WHEN WC_DW_LON_STA ='04' THEN 'IN DEFERMENT'
			WHEN WC_DW_LON_STA ='05' THEN 'IN FORBEARANCE'
			WHEN WC_DW_LON_STA ='06' THEN 'IN CURE STATUS'
			WHEN WC_DW_LON_STA ='07' THEN 'CLAIM PENDING'
			WHEN WC_DW_LON_STA ='08' THEN 'CLAIM SUBMITTED'
			WHEN WC_DW_LON_STA ='09' THEN 'CLAIM CANCELLED'
			WHEN WC_DW_LON_STA ='10' THEN 'CLAIM REJECTED'
			WHEN WC_DW_LON_STA ='11' THEN 'CLAIM RETURNED'
			WHEN WC_DW_LON_STA ='12' THEN 'CLAIM PAID'
			WHEN WC_DW_LON_STA ='13' THEN 'PRE-CLAIM PENDING'
			WHEN WC_DW_LON_STA ='14' THEN 'PRE-CLAIM SUBMITTED'
			WHEN WC_DW_LON_STA ='15' THEN 'PRE_CLAIM CANCELLED'
			WHEN WC_DW_LON_STA ='16' THEN 'DEATH ALLEGED'
			WHEN WC_DW_LON_STA ='17' THEN 'DEATH VERIFIED'
			WHEN WC_DW_LON_STA ='18' THEN 'DISABILITY ALLEGED'
			WHEN WC_DW_LON_STA ='19' THEN 'DISABILITY VERIFIED'
			WHEN WC_DW_LON_STA ='20' THEN 'BANKRUPTCY ALLEGED'
			WHEN WC_DW_LON_STA ='21' THEN 'BANKRUPTCY VERIFIED'
			WHEN WC_DW_LON_STA ='22' THEN 'PAID IN FULL'
			WHEN WC_DW_LON_STA ='23' THEN 'NOT FULLY ORIGINATED'
			WHEN WC_DW_LON_STA ='88' THEN 'PROCESSING ERROR'
			WHEN WC_DW_LON_STA ='98' THEN 'UNKNOWN'
			ELSE 'UNKNOWN'
		END AS DW01Status 
FROM OPENQUERY(DUSTER,
'
	SELECT
		CASE WHEN LN10.LF_LON_CUR_OWN IN (''829769'',''82976901'',''82976902'',''82976903'',''82976904'',''82976905'',''82976906'',''82976907'',''82976908'') THEN ''BANA''
		     WHEN LN10.LF_LON_CUR_OWN IN (''826717'',''830248'') THEN ''Align''
			 WHEN LN10.LF_LON_CUR_OWN LIKE ''828476%'' THEN ''Legacy''
			 ELSE CAST(LN10.LF_LON_CUR_OWN AS VARCHAR(15))
		END AS Portfolio,
		COUNT(DISTINCT RS05.BF_SSN) AS NOTIBR,
		DW01.WC_DW_LON_STA,
		LN65.LC_TYP_SCH_DIS
	FROM
		OLWHRM1.LN10_LON LN10
		INNER JOIN 
		(
			SELECT
				RS05I.BF_SSN
			FROM 
				OLWHRM1.RS05_IBR_RPS RS05I
			WHERE
				RS05I.BF_SSN NOT IN (SELECT BF_SSN FROM OLWHRM1.RS05_IBR_RPS WHERE BC_STA_RS05 =''A'')
		) RS05
			ON RS05.BF_SSN = LN10.BF_SSN
		INNER JOIN OLWHRM1.DW01_DW_CLC_CLU DW01
			ON DW01.BF_SSN = LN10.BF_SSN
			AND DW01.LN_SEQ = LN10.LN_SEQ
		INNER JOIN OLWHRM1.LN65_LON_RPS LN65
			ON LN65.BF_SSN = LN10.BF_SSN
			AND LN65.LN_SEQ = LN10.LN_SEQ
			AND LN65.LC_STA_LON65 =''A''
	WHERE
		LN10.LC_STA_LON10 =''R''
		AND LN10.LA_CUR_PRI > 0
		AND LN10.IC_LON_PGM NOT IN(''TILP'')
	GROUP BY
		CASE WHEN LN10.LF_LON_CUR_OWN IN(''829769'',''82976901'',''82976902'',''82976903'',''82976904'',''82976905'',''82976906'',''82976907'',''82976908'') THEN ''BANA''
		     WHEN LN10.LF_LON_CUR_OWN IN(''826717'',''830248'') THEN ''Align''
			 WHEN LN10.LF_LON_CUR_OWN LIKE ''828476%'' THEN ''Legacy''
			 ELSE  CAST(LN10.LF_LON_CUR_OWN AS VARCHAR(15)) 
		END,
		DW01.WC_DW_LON_STA,
		LN65.LC_TYP_SCH_DIS
'
) D 
GROUP BY
	Portfolio,
	CASE WHEN WC_DW_LON_STA ='01' THEN 'IN GRACE'
		 WHEN WC_DW_LON_STA ='02' THEN 'IN SCHOOL'
		 WHEN WC_DW_LON_STA ='03' THEN 
		 CASE WHEN LC_TYP_SCH_DIS ='AG' THEN 'IN REPAYMENT-MODIFIED GRADUATED REPAY SCHED'
				WHEN LC_TYP_SCH_DIS ='EG' THEN 'IN REPAYMENT-EXTENDED GRAD'
				WHEN LC_TYP_SCH_DIS ='EL' THEN 'IN REPAYMENT-EXTENDED LEVEL'
				WHEN LC_TYP_SCH_DIS ='E2' THEN 'IN REPAYMENT-EXTENDED SELECT 2'
				WHEN LC_TYP_SCH_DIS ='E5' THEN 'IN REPAYMENT-EXTENDED SELECT 5'
				WHEN LC_TYP_SCH_DIS ='E7' THEN 'IN REPAYMENT-EXTENDED SELECT 7'
				WHEN LC_TYP_SCH_DIS ='E8' THEN 'IN REPAYMENT-EXTENDED SELECT 8'
				WHEN LC_TYP_SCH_DIS ='G' THEN 'IN REPAYMENT-GRADUATED'
				WHEN LC_TYP_SCH_DIS ='GT' THEN 'IN REPAYMENT-GATE REPAY'
				WHEN LC_TYP_SCH_DIS ='IB' THEN 'IN REPAYMENT-PARTIAL FINANCIAL HARDSHIP'
				WHEN LC_TYP_SCH_DIS ='IL' THEN 'IN REPAYMENT-PERMANENT STANDARD'
				WHEN LC_TYP_SCH_DIS ='IP' THEN 'IN REPAYMENT-IBR 2014 PS'
				WHEN LC_TYP_SCH_DIS ='IS' THEN 'IN REPAYMENT-INCOME SENSITIVE'
				WHEN LC_TYP_SCH_DIS ='I3' THEN 'IN REPAYMENT-IBR 2014 PFH'
				WHEN LC_TYP_SCH_DIS ='L' THEN 'IN REPAYMENT-LEVEL'
				WHEN LC_TYP_SCH_DIS ='LO' THEN 'IN REPAYMENT-LEVEL OPTION'
				WHEN LC_TYP_SCH_DIS ='L1' THEN 'IN REPAYMENT-8/10% LEVEL'
				WHEN LC_TYP_SCH_DIS ='MG' THEN 'IN REPAYMENT-MODIFIED GRADUATED'
				WHEN LC_TYP_SCH_DIS ='P1' THEN 'IN REPAYMENT-PROGRAM OPTION 1'
				WHEN LC_TYP_SCH_DIS ='P2' THEN 'IN REPAYMENT-PROGRAM OPTION 2'
				WHEN LC_TYP_SCH_DIS ='RP' THEN 'IN REPAYMENT-REDUCED PAYMENTS'
				WHEN LC_TYP_SCH_DIS ='S1' THEN 'IN REPAYMENT-SELECT OPTION 1'
				WHEN LC_TYP_SCH_DIS ='S2' THEN 'IN REPAYMENT-SELECT OPTION 2'
				WHEN LC_TYP_SCH_DIS ='S3' THEN 'IN REPAYMENT-SELECT OPTION 3'
				WHEN LC_TYP_SCH_DIS ='S4' THEN 'IN REPAYMENT-SELECT OPTION 4'
				WHEN LC_TYP_SCH_DIS ='S5' THEN 'IN REPAYMENT-SELECT OPTION 5'
				WHEN LC_TYP_SCH_DIS ='S7' THEN 'IN REPAYMENT-SELECT OPTION 7'
				WHEN LC_TYP_SCH_DIS ='S8' THEN 'IN REPAYMENT-SELECT OPTION 8'
				ELSE 'IN REPAYMENT-UNKNOWN SCHEDULE TYPE'
		 END
		 WHEN WC_DW_LON_STA ='04' THEN 'IN DEFERMENT'
		 WHEN WC_DW_LON_STA ='05' THEN 'IN FORBEARANCE'
		 WHEN WC_DW_LON_STA ='06' THEN 'IN CURE STATUS'
		 WHEN WC_DW_LON_STA ='07' THEN 'CLAIM PENDING'
		 WHEN WC_DW_LON_STA ='08' THEN 'CLAIM SUBMITTED'
		 WHEN WC_DW_LON_STA ='09' THEN 'CLAIM CANCELLED'
		 WHEN WC_DW_LON_STA ='10' THEN 'CLAIM REJECTED'
		 WHEN WC_DW_LON_STA ='11' THEN 'CLAIM RETURNED'
		 WHEN WC_DW_LON_STA ='12' THEN 'CLAIM PAID'
		 WHEN WC_DW_LON_STA ='13' THEN 'PRE-CLAIM PENDING'
		 WHEN WC_DW_LON_STA ='14' THEN 'PRE-CLAIM SUBMITTED'
		 WHEN WC_DW_LON_STA ='15' THEN 'PRE_CLAIM CANCELLED'
		 WHEN WC_DW_LON_STA ='16' THEN 'DEATH ALLEGED'
		 WHEN WC_DW_LON_STA ='17' THEN 'DEATH VERIFIED'
		 WHEN WC_DW_LON_STA ='18' THEN 'DISABILITY ALLEGED'
		 WHEN WC_DW_LON_STA ='19' THEN 'DISABILITY VERIFIED'
		 WHEN WC_DW_LON_STA ='20' THEN 'BANKRUPTCY ALLEGED'
		 WHEN WC_DW_LON_STA ='21' THEN 'BANKRUPTCY VERIFIED'
		 WHEN WC_DW_LON_STA ='22' THEN 'PAID IN FULL'
		 WHEN WC_DW_LON_STA ='23' THEN 'NOT FULLY ORIGINATED'
		 WHEN WC_DW_LON_STA ='88' THEN 'PROCESSING ERROR'
		 WHEN WC_DW_LON_STA ='98' THEN 'UNKNOWN'
		 ELSE 'UNKNOWN'
	END
ORDER BY
	Portfolio,
	DW01Status

--Error report
SELECT * FROM OPENQUERY(DUSTER,
'SELECT DISTINCT LN10.BF_SSN, RS05.BD_ANV_QLF_IBR FROM
		OLWHRM1.LN10_LON LN10
		INNER JOIN OLWHRM1.RS05_IBR_RPS RS05
			ON RS05.BF_SSN = LN10.BF_SSN
			AND RS05.BC_STA_RS05 = ''A''
		INNER JOIN OLWHRM1.LN65_LON_RPS LN65
			ON LN65.BF_SSN = LN10.BF_SSN
			AND LN65.LN_SEQ = LN10.LN_SEQ
			AND LN65.LC_TYP_SCH_DIS = ''IB''
			AND LN65.LC_STA_LON65 = ''A''
	WHERE
		LN10.LC_STA_LON10 = ''R''
		AND LN10.LA_CUR_PRI > 0
		AND RS05.BD_ANV_QLF_IBR IS NULL
		AND LN10.IC_LON_PGM NOT IN(''TILP'')
')

/*********************************************************************************************

BEGIN DETAIL REPORT

*********************************************************************************************/

--IBR Count
SELECT 
	*
 FROM OPENQUERY(DUSTER,
'
	SELECT DISTINCT
		CASE WHEN LN10.LF_LON_CUR_OWN IN (''829769'',''82976901'',''82976902'',''82976903'',''82976904'',''82976905'',''82976906'',''82976907'',''82976908'') THEN ''BANA''
		     WHEN LN10.LF_LON_CUR_OWN IN (''826717'',''830248'') THEN ''Align''
			 WHEN LN10.LF_LON_CUR_OWN LIKE ''828476%'' THEN ''Legacy''
			 ELSE CAST(LN10.LF_LON_CUR_OWN AS VARCHAR(15)) 
		END AS Portfolio,
		RS05.BF_SSN AS Borrower,
		MONTHNAME(RS05.BD_ANV_QLF_IBR, ''CLDR 1.5:en_US'') AS MonthName,
		MONTH(RS05.BD_ANV_QLF_IBR) AS MonthNumber
	FROM
		OLWHRM1.LN10_LON LN10
		INNER JOIN OLWHRM1.RS05_IBR_RPS RS05
			ON RS05.BF_SSN = LN10.BF_SSN
			AND RS05.BC_STA_RS05 = ''A''
		INNER JOIN OLWHRM1.LN65_LON_RPS LN65
			ON LN65.BF_SSN = LN10.BF_SSN
			AND LN65.LN_SEQ = LN10.LN_SEQ
			AND LN65.LC_TYP_SCH_DIS = ''IB''
			AND LN65.LC_STA_LON65 = ''A''
	WHERE
		LN10.LC_STA_LON10 = ''R''
		AND LN10.LA_CUR_PRI > 0
		AND LN10.IC_LON_PGM NOT IN(''TILP'')
		AND RS05.BD_ANV_QLF_IBR IS NOT NULL
	ORDER BY
		Portfolio,
		MONTH(RS05.BD_ANV_QLF_IBR)
'
) 

--Payment breakout for IBR borrowers
SELECT 
	*
FROM OPENQUERY(DUSTER,
'
	SELECT
		CASE WHEN LN10.LF_LON_CUR_OWN IN (''829769'',''82976901'',''82976902'',''82976903'',''82976904'',''82976905'',''82976906'',''82976907'',''82976908'') THEN ''BANA''
		     WHEN LN10.LF_LON_CUR_OWN IN (''826717'',''830248'') THEN ''Align''
			 WHEN LN10.LF_LON_CUR_OWN LIKE ''828476%'' THEN ''Legacy''
			 ELSE CAST(LN10.LF_LON_CUR_OWN AS VARCHAR(15)) 
		END AS Portfolio,
		LN10.BF_SSN,
		LN10.LN_SEQ,
		CASE WHEN LN66.LA_RPS_ISL = 0.00 THEN LN66.LA_RPS_ISL ELSE NULL END AS Payment0,
		CASE WHEN LN66.LA_RPS_ISL >= 1.00 AND LN65.LI_ICR_RPD_NEG_AMR = ''Y'' THEN LN66.LA_RPS_ISL ELSE NULL END AS NegAm1,
		CASE WHEN LN66.LA_RPS_ISL < 50.00 AND COALESCE(LN65.LI_ICR_RPD_NEG_AMR,''N'') = ''N'' THEN LN66.LA_RPS_ISL ELSE NULL END AS LessThan50,
		CASE WHEN LN66.LA_RPS_ISL >= 50.00 THEN LN66.LA_RPS_ISL ELSE NULL END AS GreaterThan50
	FROM
		OLWHRM1.LN10_LON LN10
		INNER JOIN OLWHRM1.RS05_IBR_RPS RS05
			ON RS05.BF_SSN = LN10.BF_SSN
			AND RS05.BC_STA_RS05 = ''A''
		INNER JOIN OLWHRM1.LN65_LON_RPS LN65
			ON LN65.BF_SSN = LN10.BF_SSN
			AND LN65.LN_SEQ = LN10.LN_SEQ
			AND LN65.LC_STA_LON65 = ''A''
			AND LN65.LC_TYP_SCH_DIS = ''IB''
		INNER JOIN OLWHRM1.LN66_LON_RPS_SPF LN66
			ON LN66.BF_SSN = LN65.BF_SSN
			AND LN66.LN_SEQ = LN65.LN_SEQ
			AND LN66.LN_RPS_SEQ = LN65.LN_RPS_SEQ
	WHERE
		LN10.LC_STA_LON10 = ''R''
		AND LN10.LA_CUR_PRI > 0
		AND LN10.IC_LON_PGM NOT IN(''TILP'')
	ORDER BY
		Portfolio
'
) 

--Non IBR Status
SELECT 
	PORTFOLIO AS Portfolio,
	NOTIBR AS Borrower,
	CASE WHEN WC_DW_LON_STA ='01' THEN 'IN GRACE'
			WHEN WC_DW_LON_STA ='02' THEN 'IN SCHOOL'
			WHEN WC_DW_LON_STA ='03' THEN 
			CASE WHEN LC_TYP_SCH_DIS ='AG' THEN 'IN REPAYMENT-MODIFIED GRADUATED REPAY SCHED'
					WHEN LC_TYP_SCH_DIS ='EG' THEN 'IN REPAYMENT-EXTENDED GRAD'
					WHEN LC_TYP_SCH_DIS ='EL' THEN 'IN REPAYMENT-EXTENDED LEVEL'
					WHEN LC_TYP_SCH_DIS ='E2' THEN 'IN REPAYMENT-EXTENDED SELECT 2'
					WHEN LC_TYP_SCH_DIS ='E5' THEN 'IN REPAYMENT-EXTENDED SELECT 5'
					WHEN LC_TYP_SCH_DIS ='E7' THEN 'IN REPAYMENT-EXTENDED SELECT 7'
					WHEN LC_TYP_SCH_DIS ='E8' THEN 'IN REPAYMENT-EXTENDED SELECT 8'
					WHEN LC_TYP_SCH_DIS ='G' THEN 'IN REPAYMENT-GRADUATED'
					WHEN LC_TYP_SCH_DIS ='GT' THEN 'IN REPAYMENT-GATE REPAY'
					WHEN LC_TYP_SCH_DIS ='IB' THEN 'IN REPAYMENT-PARTIAL FINANCIAL HARDSHIP'
					WHEN LC_TYP_SCH_DIS ='IL' THEN 'IN REPAYMENT-PERMANENT STANDARD'
					WHEN LC_TYP_SCH_DIS ='IP' THEN 'IN REPAYMENT-IBR 2014 PS'
					WHEN LC_TYP_SCH_DIS ='IS' THEN 'IN REPAYMENT-INCOME SENSITIVE'
					WHEN LC_TYP_SCH_DIS ='I3' THEN 'IN REPAYMENT-IBR 2014 PFH'
					WHEN LC_TYP_SCH_DIS ='L' THEN 'IN REPAYMENT-LEVEL'
					WHEN LC_TYP_SCH_DIS ='LO' THEN 'IN REPAYMENT-LEVEL OPTION'
					WHEN LC_TYP_SCH_DIS ='L1' THEN 'IN REPAYMENT-8/10% LEVEL'
					WHEN LC_TYP_SCH_DIS ='MG' THEN 'IN REPAYMENT-MODIFIED GRADUATED'
					WHEN LC_TYP_SCH_DIS ='P1' THEN 'IN REPAYMENT-PROGRAM OPTION 1'
					WHEN LC_TYP_SCH_DIS ='P2' THEN 'IN REPAYMENT-PROGRAM OPTION 2'
					WHEN LC_TYP_SCH_DIS ='RP' THEN 'IN REPAYMENT-REDUCED PAYMENTS'
					WHEN LC_TYP_SCH_DIS ='S1' THEN 'IN REPAYMENT-SELECT OPTION 1'
					WHEN LC_TYP_SCH_DIS ='S2' THEN 'IN REPAYMENT-SELECT OPTION 2'
					WHEN LC_TYP_SCH_DIS ='S3' THEN 'IN REPAYMENT-SELECT OPTION 3'
					WHEN LC_TYP_SCH_DIS ='S4' THEN 'IN REPAYMENT-SELECT OPTION 4'
					WHEN LC_TYP_SCH_DIS ='S5' THEN 'IN REPAYMENT-SELECT OPTION 5'
					WHEN LC_TYP_SCH_DIS ='S7' THEN 'IN REPAYMENT-SELECT OPTION 7'
					WHEN LC_TYP_SCH_DIS ='S8' THEN 'IN REPAYMENT-SELECT OPTION 8'
					ELSE 'IN REPAYMENT-UNKNOWN SCHEDULE TYPE'
			END
			WHEN WC_DW_LON_STA ='04' THEN 'IN DEFERMENT'
			WHEN WC_DW_LON_STA ='05' THEN 'IN FORBEARANCE'
			WHEN WC_DW_LON_STA ='06' THEN 'IN CURE STATUS'
			WHEN WC_DW_LON_STA ='07' THEN 'CLAIM PENDING'
			WHEN WC_DW_LON_STA ='08' THEN 'CLAIM SUBMITTED'
			WHEN WC_DW_LON_STA ='09' THEN 'CLAIM CANCELLED'
			WHEN WC_DW_LON_STA ='10' THEN 'CLAIM REJECTED'
			WHEN WC_DW_LON_STA ='11' THEN 'CLAIM RETURNED'
			WHEN WC_DW_LON_STA ='12' THEN 'CLAIM PAID'
			WHEN WC_DW_LON_STA ='13' THEN 'PRE-CLAIM PENDING'
			WHEN WC_DW_LON_STA ='14' THEN 'PRE-CLAIM SUBMITTED'
			WHEN WC_DW_LON_STA ='15' THEN 'PRE_CLAIM CANCELLED'
			WHEN WC_DW_LON_STA ='16' THEN 'DEATH ALLEGED'
			WHEN WC_DW_LON_STA ='17' THEN 'DEATH VERIFIED'
			WHEN WC_DW_LON_STA ='18' THEN 'DISABILITY ALLEGED'
			WHEN WC_DW_LON_STA ='19' THEN 'DISABILITY VERIFIED'
			WHEN WC_DW_LON_STA ='20' THEN 'BANKRUPTCY ALLEGED'
			WHEN WC_DW_LON_STA ='21' THEN 'BANKRUPTCY VERIFIED'
			WHEN WC_DW_LON_STA ='22' THEN 'PAID IN FULL'
			WHEN WC_DW_LON_STA ='23' THEN 'NOT FULLY ORIGINATED'
			WHEN WC_DW_LON_STA ='88' THEN 'PROCESSING ERROR'
			WHEN WC_DW_LON_STA ='98' THEN 'UNKNOWN'
			ELSE 'UNKNOWN'
		END AS DW01Status 
FROM OPENQUERY(DUSTER,
'
	SELECT DISTINCT
		CASE WHEN LN10.LF_LON_CUR_OWN IN (''829769'',''82976901'',''82976902'',''82976903'',''82976904'',''82976905'',''82976906'',''82976907'',''82976908'') THEN ''BANA''
		     WHEN LN10.LF_LON_CUR_OWN IN (''826717'',''830248'') THEN ''Align''
			 WHEN LN10.LF_LON_CUR_OWN LIKE ''828476%'' THEN ''Legacy''
			 ELSE CAST(LN10.LF_LON_CUR_OWN AS VARCHAR(15))
		END AS Portfolio,
		RS05.BF_SSN AS NOTIBR,
		DW01.WC_DW_LON_STA,
		LN65.LC_TYP_SCH_DIS
	FROM
		OLWHRM1.LN10_LON LN10
		INNER JOIN 
		(
			SELECT
				RS05I.BF_SSN
			FROM 
				OLWHRM1.RS05_IBR_RPS RS05I
			WHERE
				RS05I.BF_SSN NOT IN (SELECT BF_SSN FROM OLWHRM1.RS05_IBR_RPS WHERE BC_STA_RS05 =''A'')
		) RS05
			ON RS05.BF_SSN = LN10.BF_SSN
		INNER JOIN OLWHRM1.DW01_DW_CLC_CLU DW01
			ON DW01.BF_SSN = LN10.BF_SSN
			AND DW01.LN_SEQ = LN10.LN_SEQ
		INNER JOIN OLWHRM1.LN65_LON_RPS LN65
			ON LN65.BF_SSN = LN10.BF_SSN
			AND LN65.LN_SEQ = LN10.LN_SEQ
			AND LN65.LC_STA_LON65 =''A''
	WHERE
		LN10.LC_STA_LON10 =''R''
		AND LN10.LA_CUR_PRI > 0
		AND LN10.IC_LON_PGM NOT IN(''TILP'')
'
) D 
ORDER BY
	Portfolio,
	DW01Status



	