USE UDW
GO



SELECT
	POP.BF_SSN,
	POP.LN_ATY_SEQ,
	POP.LC_STA_ACTY10 AS OLD_LC_STA_ACTY10,
	'E' AS OLD_LC_STA_ACTY10,
	POP.LF_LST_DTS_AY10 AS OLD_LF_LST_DTS_AY10,
	'CURRENT DATE/TIME' AS NEW_LF_LST_DTS_AY10
FROM
(
	SELECT DISTINCT
		AY10.BF_SSN,
		AY10.LN_ATY_SEQ,
		AY10.LC_STA_ACTY10,
		AY10.LF_LST_DTS_AY10,
		RIGHT(REPLACE(AY20.LX_ATY, ' ',''), 60) AS LX_ATY, --we need to get rid of the noble call history id and extra spaces because of how sometime it adds a space
		ROW_NUMBER() OVER(PARTITION BY AY10.BF_SSN,	RIGHT(REPLACE(AY20.LX_ATY, ' ',''), 60) ORDER BY AY10.LN_ATY_SEQ) AS CallRank
	FROM
		PD10_PRS_NME PD10
		INNER JOIN AY10_BR_LON_ATY AY10
			ON AY10.BF_SSN = PD10.DF_PRS_ID
		INNER JOIN
		(
			SELECT 
				BF_SSN,
				LN_ATY_SEQ,
				STUFF(
				(
					SELECT 
						 ' ' + SUB.LX_ATY AS [text()]
					FROM 
						AY20_ATY_TXT SUB
					WHERE
						SUB.BF_SSN = AY20.BF_SSN
						AND SUB.LN_ATY_SEQ = AY20.LN_ATY_SEQ
				FOR XML PATH('')
				)
				,1,1, '')
				AS LX_ATY
			FROM	
				AY20_ATY_TXT AY20
		)AY20
			ON AY20.BF_SSN = AY10.BF_SSN
			AND AY20.LN_ATY_SEQ = AY10.LN_ATY_SEQ
	WHERE
		AY10.PF_REQ_ACT ='DDPHN'
		AND AY10.LC_STA_ACTY10 = 'A'
		AND AY10.LD_ATY_REQ_RCV BETWEEN '02/01/2018' AND  '02/04/2018'
) POP
WHERE
	POP.CallRank != 1
ORDER BY
	POP.BF_SSN,
	POP.LN_ATY_SEQ
