/*OUTPUT 1*/
SELECT * FROM OPENQUERY (DUSTER,'
	SELECT DISTINCT
		LN10.BF_SSN
		,LN10.LN_SEQ
		,LN10.IF_GTR
		,LN10.LC_STA_LON10 
		,(LN10.LA_CUR_PRI + DW01.LA_NSI_OTS) AS TOTAL
	FROM
		OLWHRM1.LN10_LON LN10
		INNER JOIN OLWHRM1.DW01_DW_CLC_CLU DW01
			ON LN10.BF_SSN = DW01.BF_SSN
			AND LN10.LN_SEQ = DW01.LN_SEQ
	WHERE
		LN10.LC_STA_LON10 = ''R''
		AND LN10.LA_CUR_PRI > ''0''

');

/*OUTPUT 2*/
SELECT * FROM OPENQUERY (DUSTER,'
	SELECT DISTINCT
		IF_GTR
		,COUNT(DISTINCT BF_SSN) AS BORROWERS
		,COUNT(LN_SEQ) AS LOANS
		,SUM(TOTAL) AS TOTAL_OUTSTANDING_BALANCE
	FROM (
			SELECT DISTINCT
				LN10.BF_SSN
				,LN10.LN_SEQ
				,LN10.IF_GTR
				,LN10.LC_STA_LON10 
				,(LN10.LA_CUR_PRI + DW01.LA_NSI_OTS) AS TOTAL
			FROM
				OLWHRM1.LN10_LON LN10
				INNER JOIN OLWHRM1.DW01_DW_CLC_CLU DW01
					ON LN10.BF_SSN = DW01.BF_SSN
					AND LN10.LN_SEQ = DW01.LN_SEQ
			WHERE
				LN10.LC_STA_LON10 = ''R''
				AND LN10.LA_CUR_PRI > ''0''
		)
	GROUP BY
		IF_GTR
');

/*OUTPUT 3*/
SELECT * FROM OPENQUERY (DUSTER,'
	SELECT DISTINCT
		GU10.IF_GTR
		,GU10.IM_GTR_FUL
		,LR10.IF_DOE_LDR
		,LR10.IM_LDR_FUL
		,COUNT(DISTINCT BF_SSN) AS BORROWERS
		,COUNT(LN_SEQ) AS LOANS
		,SUM(TOTAL) AS TOTAL_OUTSTANDING_BALANCE
	FROM (
			SELECT DISTINCT
				LN10.BF_SSN
				,LN10.LN_SEQ
				,LN10.IF_GTR
				,LN10.IF_DOE_LDR
				,LN10.LC_STA_LON10 
				,(LN10.LA_CUR_PRI + DW01.LA_NSI_OTS) AS TOTAL
			FROM
				OLWHRM1.LN10_LON LN10
				INNER JOIN OLWHRM1.DW01_DW_CLC_CLU DW01
					ON LN10.BF_SSN = DW01.BF_SSN
					AND LN10.LN_SEQ = DW01.LN_SEQ
			WHERE
				LN10.LC_STA_LON10 = ''R''
				AND LN10.LA_CUR_PRI > ''0''
		) SUBQ
		INNER JOIN OLWHRM1.GU10_GTR GU10
			ON SUBQ.IF_GTR = GU10.IF_GTR
		INNER JOIN OLWHRM1.LR10_LDR_DMO LR10
			ON SUBQ.IF_DOE_LDR = LR10.IF_DOE_LDR
	GROUP BY
		GU10.IF_GTR
		,GU10.IM_GTR_FUL
		,LR10.IF_DOE_LDR
		,LR10.IM_LDR_FUL
');