--query based on UNH 51252

/*
For each lender ID provide the following summary numbers. Use the first six characters of LN10.LF-LON-CUR-OWN to assign a lender to a loan.

When referencing LN10, Use LN10-LON-EOM

Total $ Sub stafford = Grand total for all loans as determined below:
LN10.IC-LON-PGM = STFFRD
LN10.LA-CUR-PRI + LN10.LA-NSI-OTS

Total $ of Unsub Stafford = Grand total for all loans as determined below:
LN10.IC-LON-PGM = UNSTFD
LN10.LA-CUR-PRI + LN10.LA-NSI-OTS

Total $ of PLUS = Grand total for all loans as determined below:
LN10.IC-LON-PGM = PLUS, PLUSGB
LN10.LA-CUR-PRI + LN10.LA-NSI-OTS

Total $ of CONSOL = Grand total for all loans as determined below:
LN10.IC-LON-PGM = CONSOL, CNSLDN, SPCNSL, SUBCNS, SUBSPC, UNCNS, UNSPC
LN10.LA-CUR-PRI + LN10.LA-NSI-OTS

Also, for each loan capture the LN10.IF-GTR and provide a unique list of all guarantors associated with these loans.
*/
SELECT
	A.*,
	B.LoanCount,
	C.BorrowerCount
FROM
	(	--loan $ totals
		SELECT
			LEFT(LN10.LF_LON_CUR_OWN, 6) AS LF_LON_CUR_OWN,
			SUM(CASE WHEN LN10.IC_LON_PGM = 'STFFRD' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END) AS SubStafford,
			SUM(CASE WHEN LN10.IC_LON_PGM = 'UNSTFD' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END) AS UnsubStafford,
			SUM(CASE WHEN LN10.IC_LON_PGM = 'PLUS' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END) AS PLUS,
			SUM(CASE WHEN LN10.IC_LON_PGM = 'PLUSGB' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END) AS PLUSGB,
			SUM(CASE WHEN LN10.IC_LON_PGM IN ('CONSOL', 'CNSLDN', 'SPCNSL', 'SUBCNS', 'SUBSPC', 'UNCNS', 'UNSPC') THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END) AS CONSOL
		FROM
			AuditUDW..LN10_LON_Dec2018 LN10
		WHERE
			LN10.LC_STA_LON10 = 'R'
			AND LN10.LA_CUR_PRI > 0.00
			AND	LEFT(LN10.LF_LON_CUR_OWN, 6) IN
			(
				'826717',
				'828476',
				'829769',
				'830248'
			)
		GROUP BY
			LEFT(LN10.LF_LON_CUR_OWN, 6)
	) A

FULL OUTER JOIN 

	(	--loan count
		SELECT
			LEFT(LN10.LF_LON_CUR_OWN, 6) AS LF_LON_CUR_OWN,
			COUNT(LN10.LN_SEQ) AS LoanCount
			--LN10.BF_SSN,
			--CASE WHEN LN10.IC_LON_PGM = 'STFFRD' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS SubStafford,
			--CASE WHEN LN10.IC_LON_PGM = 'UNSTFD' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS UnsubStafford,
			--CASE WHEN LN10.IC_LON_PGM = 'PLUS' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS PLUS,
			--CASE WHEN LN10.IC_LON_PGM = 'PLUSGB' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS PLUSGB,
			--CASE WHEN LN10.IC_LON_PGM IN ('CONSOL', 'CNSLDN', 'SPCNSL', 'SUBCNS', 'SUBSPC', 'UNCNS', 'UNSPC') THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS CONSOL,
			--LN10.IF_GTR
		FROM
			AuditUDW..LN10_LON_Dec2018 LN10
		WHERE
			LN10.LC_STA_LON10 = 'R'
			AND LN10.LA_CUR_PRI > 0.00
			AND	LEFT(LN10.LF_LON_CUR_OWN, 6) IN
			(
				'826717',
				'828476',
				'829769',
				'830248'
			)
		GROUP BY
			LEFT(LN10.LF_LON_CUR_OWN, 6)
	) B
	ON A.LF_LON_CUR_OWN = B.LF_LON_CUR_OWN

FULL OUTER JOIN

	(  --borrower count
		SELECT
			LEFT(LN10.LF_LON_CUR_OWN, 6) AS LF_LON_CUR_OWN,
			COUNT(DISTINCT LN10.BF_SSN) AS BorrowerCount
			--LN10.LN_SEQ,
			--CASE WHEN LN10.IC_LON_PGM = 'STFFRD' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS SubStafford,
			--CASE WHEN LN10.IC_LON_PGM = 'UNSTFD' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS UnsubStafford,
			--CASE WHEN LN10.IC_LON_PGM = 'PLUS' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS PLUS,
			--CASE WHEN LN10.IC_LON_PGM = 'PLUSGB' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS PLUSGB,
			--CASE WHEN LN10.IC_LON_PGM IN ('CONSOL', 'CNSLDN', 'SPCNSL', 'SUBCNS', 'SUBSPC', 'UNCNS', 'UNSPC') THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS CONSOL,
			--LN10.IF_GTR
		FROM
			AuditUDW..LN10_LON_Dec2018 LN10
		WHERE
			LN10.LC_STA_LON10 = 'R'
			AND LN10.LA_CUR_PRI > 0.00
			AND	LEFT(LN10.LF_LON_CUR_OWN, 6) IN
			(
				'826717',
				'828476',
				'829769',
				'830248'
			)
		GROUP BY
			LEFT(LN10.LF_LON_CUR_OWN, 6)
	) C
		ON A.LF_LON_CUR_OWN = C.LF_LON_CUR_OWN
ORDER BY
	A.LF_LON_CUR_OWN
;





--individual borrower data
SELECT
	LN10.BF_SSN,
	LN10.LN_SEQ,
	LEFT(LN10.LF_LON_CUR_OWN, 6) AS LF_LON_CUR_OWN,
	CASE WHEN LN10.IC_LON_PGM = 'STFFRD' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS SubStafford,
	CASE WHEN LN10.IC_LON_PGM = 'UNSTFD' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS UnsubStafford,
	CASE WHEN LN10.IC_LON_PGM = 'PLUS' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS PLUS,
	CASE WHEN LN10.IC_LON_PGM = 'PLUSGB' THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS PLUSGB,
	CASE WHEN LN10.IC_LON_PGM IN ('CONSOL', 'CNSLDN', 'SPCNSL', 'SUBCNS', 'SUBSPC', 'UNCNS', 'UNSPC') THEN (COALESCE(LN10.LA_CUR_PRI, 0) + COALESCE(LN10.LA_NSI_OTS, 0)) ELSE 0 END AS CONSOL,
	LN10.IF_GTR
FROM
	AuditUDW..LN10_LON_Dec2018 LN10
WHERE
	LN10.LC_STA_LON10 = 'R'
	AND LN10.LA_CUR_PRI > 0.00
	AND	LEFT(LN10.LF_LON_CUR_OWN, 6) IN
	(
		'826717',
		'828476',
		'829769',
		'830248'
	)
;

--guarantors
SELECT DISTINCT
	LN10.IF_GTR
FROM
	AuditUDW..LN10_LON_Dec2018 LN10
WHERE
	LN10.LC_STA_LON10 = 'R'
	AND LN10.LA_CUR_PRI > 0.00
	AND	LEFT(LN10.LF_LON_CUR_OWN, 6) IN 
	(
		'826717',
		'828476',
		'829769',
		'830248'
	)
;