DROP TABLE IF EXISTS #POP2
SELECT DISTINCT
	DC01.AF_APL_ID,
	DC01.AF_APL_ID_SFX,
	DC01.LF_CRT_DTS_DC10,
	BF_SSN
INTO #POP2
FROM
	ODW..DC01_LON_CLM_INF DC01
WHERE
    DC01.LC_STA_DC10 = '03'
    AND DC01.LD_LDR_POF >= '03/13/2020'
    AND DC01.LC_PCL_REA IN ('DB','DF','IN')

		SELECT DISTINCT
			DC01.BF_SSN AS SSN,
			DC01.AF_APL_ID + DC01.AF_APL_ID_SFX AS CLUID,
			ISNULL(CONVERT(VARCHAR, DC01.LD_IBR_RPD_SR, 101),'N/A') AS IBR_START_DATE,
			DC01.LN_IBR_QLF_FGV_MTH AS IBR_MONTHS,
			DC01.LN_IBR_DAY_EHD_DFR AS EHD_MONTHS,
			'UHEAA 700126' AS PRIOR_SERVICER
		FROM
			ODW..DC01_LON_CLM_INF DC01
			INNER JOIN #POP2 P
				ON DC01.BF_SSN = P.BF_SSN
				AND DC01.AF_APL_ID = P.AF_APL_ID
				AND DC01.AF_APL_ID_SFX = P.AF_APL_ID_SFX
			INNER JOIN ODW..DC02_BAL_INT DC02 --STILL CURRENTLY IN DEFAULT
				ON DC02.AF_APL_ID = DC01.AF_APL_ID
				AND DC02.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
				AND DC02.LF_CRT_DTS_DC10 = DC01.LF_CRT_DTS_DC10
				AND DC02.LA_CLM_BAL > 0.00
			INNER JOIN 
			(
				SELECT DISTINCT
					DC01.BF_SSN,
					DC01.AF_APL_ID,
					DC01.AF_APL_ID_SFX,
					MAX(DC01.LF_CRT_DTS_DC10) AS MaxDate
				FROM
					ODW..DC01_LON_CLM_INF DC01
				GROUP BY
					DC01.BF_SSN,
					DC01.AF_APL_ID,
					DC01.AF_APL_ID_SFX
				) DC01M
					ON DC01.AF_APL_ID = DC01M.AF_APL_ID
					AND DC01.AF_APL_ID_SFX = DC01M.AF_APL_ID_SFX
					AND DC01.LF_CRT_DTS_DC10 = DC01M.MaxDate
			WHERE
					DC01.LC_PCL_REA = 'DF'
					AND DC01.LC_STA_DC10 = '03'
					AND DC01.LD_CLM_ASN_DOE IS NULL
					AND ISNULL(DC01.LC_REA_CLM_ASN_DOE,'') in ('08')
