
SELECT DISTINCT
	PD10.DF_SPE_ACC_ID,
	LN10.LN_SEQ,
	ABS(ISNULL(LN90.LA_FAT_CUR_PRI,0.00) + ISNULL(LN90.LA_FAT_NSI,0.00)) AS PAYMENT_AMOUNT,
	LK10.PX_DSC_LNG AS TRANSACTION_TYPE,
	LK101.PX_DSC_LNG AS TRANSACTION_SUB_TYPE,
	CONVERT(VARCHAR,ISNULL(LD_PIF_RPT,ln10.LF_LST_DTS_LN10), 101)  AS LOAN_STATUS_DATE,
	CONVERT(VARCHAR, LN90.LD_FAT_EFF, 101) AS LAST_PAYMENT_EFFECTIVE_DATE,
	ISNULL(CONVERT(VARCHAR,MAX(ISNULL(PP.PrintedAt, PP.EcorrDocumentCreatedAt)) OVER (PARTITION BY PD10.DF_SPE_ACC_ID), 101),'N/A') AS  PIF_LETTER_SENT
FROM
	UDW..LN10_LON LN10
	INNER JOIN UDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = LN10.BF_SSN
	INNER JOIN
	(
		SELECT
			LN90.*,
			MLN90.RN
		FROM
			UDW..LN90_FIN_ATY LN90
			INNER JOIN 
			(
				SELECT
					LN90.BF_SSN,
					LN90.LN_SEQ,
					LN_FAT_SEQ,
					ROW_NUMBER() OVER (PARTITION BY LN90.BF_SSN, LN90.LN_SEQ ORDER BY LN_FAT_SEQ DESC) AS RN
				FROM
					UDW..LN90_FIN_ATY LN90
					LEFT JOIN 
					(
						SELECT 
							BF_SSN,
							LN_SEQ,
							MAX(LD_FAT_EFF) AS LD_FAT_EFF
						FROM
							UDW..LN90_FIN_ATY
						GROUP BY
							BF_SSN,
							LN_SEQ
						HAVING MAX(LD_FAT_EFF) > '08/01/2021'
					) EXLN90
						ON EXLN90.BF_SSN = LN90.BF_SSN
						AND EXLN90.LN_SEQ = LN90.LN_SEQ
				WHERE
					LN90.LD_FAT_EFF BETWEEN '08/01/2020' AND '08/01/2021'
					AND LC_STA_LON90 = 'A'
					AND ISNULL(LC_FAT_REV_REA,'') = ''
					AND PC_FAT_TYP NOT IN ('20','03')
					AND EXLN90.BF_SSN IS NULL
			) MLN90
				ON LN90.BF_SSN = MLN90.BF_SSN
				AND LN90.LN_SEQ = MLN90.LN_SEQ
				AND LN90.LN_FAT_SEQ = MLN90.LN_FAT_SEQ
				AND MLN90.RN = 1
	) LN90
		ON LN90.BF_SSN = LN10.BF_SSN
		AND LN10.LN_SEQ = LN90.LN_SEQ
	INNER JOIN UDW..LK10_LS_CDE_LKP LK10
		ON LK10.PM_ATR = 'PC-FAT-TYP'
		AND LK10.PX_ATR_VAL IN (LN90.PC_FAT_TYP)
	INNER JOIN UDW..LK10_LS_CDE_LKP LK101
		ON LK101.PM_ATR = 'PC-FAT-SUB-TYP'
		AND LK101.PX_ATR_VAL IN ( LN90.PC_FAT_SUB_TYP)
	LEFT JOIN ULS.[print].PrintProcessing PP
		ON PP.ScriptDataId IN (95,96)
		AND PP.AccountNumber = PD10.DF_SPE_ACC_ID
WHERE
	LA_CUR_PRI <= 0
	AND LN10.LC_STA_LON10 = 'R'
	AND LN90.RN = 1
ORDER BY
	PD10.DF_SPE_ACC_ID,
	LN10.LN_SEQ