SELECT
	Q.BF_SSN,
	IC_LON_PGM,
	CONVERT(VARCHAR(8),LD_LON_GTR,112) AS LD_LON_GTR,
	Parent_SSN,
	REPLACE(STR(CAST(ROUND(LA_LON_AMT_GTR,0) AS INT), 6), SPACE(1), '0') AS LA_LON_AMT_GTR,
	UniqueID
FROM
	OPENQUERY
	(
		DUSTER,
		'SELECT
				LN10.BF_SSN,
				CASE LN10.IC_LON_PGM
					WHEN ''STFFRD'' THEN ''SF''
					WHEN ''UNSTFD'' THEN ''SU''
					WHEN ''PLUSGB'' THEN ''GB''
					WHEN ''SUBCNS'' THEN ''CL''
					WHEN ''UNCNS '' THEN ''CL''
					WHEN ''SLS'' THEN ''SL''
					WHEN ''PLUS'' THEN ''PL''
					WHEN ''CNSLDN'' THEN ''CL''
					WHEN ''SUBSPC'' THEN ''CL''
					WHEN ''UNSPC'' THEN ''CL''
				END AS IC_LON_PGM,
				LN10.LD_LON_GTR,
				CASE WHEN LN10.IC_LON_PGM = ''PLUS'' THEN LN10.BF_SSN ELSE '''' END AS Parent_SSN,
				LN10.LA_LON_AMT_GTR,
				LN10.LN_SEQ  AS UniqueID
			FROM
				OLWHRM1.LN10_LON LN10
			WHERE
				LN10.LF_LON_CUR_OWN IN (''829769'', ''82976901'', ''82976902'', ''82976903'', ''82976904'', ''82976905'', ''82976906'', ''82976907'', ''82976908'')
				AND
				LN10.LA_CUR_PRI > 0.00'
	) Q ORDER BY Q.BF_SSN