SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SELECT
	LN60.BF_SSN,
	LN60.LN_SEQ,
	FB10.LD_FOR_REQ_BEG AS RequestedBegin,
	LN60.LD_FOR_BEG AS ActualBegin,
	FB10.LD_FOR_BR_REQ_END AS RequestedEnd,
	LN60.LD_FOR_END AS ActualEnd,
	LN60.LD_FOR_APL AS AppliedDate
FROM
	UDW..FB10_BR_FOR_REQ FB10
	INNER JOIN UDW..LN60_BR_FOR_APV LN60
		ON FB10.BF_SSN = LN60.BF_SSN
		AND FB10.LF_FOR_CTL_NUM = LN60.LF_FOR_CTL_NUM
WHERE
	FB10.LC_FOR_STA = 'A'
	AND FB10.LC_STA_FOR10 = 'A'
	AND FB10.LC_FOR_TYP = '40'
	AND LN60.LC_STA_LON60 = 'A'
	AND LN60.LC_FOR_RSP != '003' --Exclude denials
	AND
	(
		(
			MONTH(FB10.LD_FOR_REQ_BEG) IN(2,5)
			AND YEAR(FB10.LD_FOR_REQ_BEG) = 2018
		)
		OR
		(
			MONTH(FB10.LD_FOR_REQ_BEG) IN(3,5)
			AND YEAR(FB10.LD_FOR_REQ_BEG) = 2019
		)
	)
ORDER BY
	YEAR(FB10.LD_FOR_REQ_BEG),
	MONTH(FB10.LD_FOR_REQ_BEG),
	DAY(FB10.LD_FOR_REQ_BEG),
	LN60.BF_SSN,
	LN60.LN_SEQ


SELECT DISTINCT
	LN60.BF_SSN,
	LN60.LN_SEQ,
	FB10.LD_FOR_REQ_BEG AS RequestedBegin,
	LN60.LD_FOR_BEG AS ActualBegin,
	FB10.LD_FOR_BR_REQ_END AS RequestedEnd,
	LN60.LD_FOR_END AS ActualEnd,
	LN60.LD_FOR_APL AS AppliedDate
FROM
	UDW..FB10_BR_FOR_REQ FB10
	INNER JOIN UDW..LN60_BR_FOR_APV LN60
		ON FB10.BF_SSN = LN60.BF_SSN
		AND FB10.LF_FOR_CTL_NUM = LN60.LF_FOR_CTL_NUM
	INNER JOIN UDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = LN60.BF_SSN
	INNER JOIN ULS.dasforbfed.ProcessQueue PQ
		ON PQ.AccountNumber = PD10.DF_SPE_ACC_ID
		AND PQ.ForbearanceAddedOn >= '2018-02-01'
		AND LN60.LD_FOR_APL >= PQ.ForbearanceAddedOn
WHERE
	FB10.LC_FOR_STA = 'A'
	AND FB10.LC_STA_FOR10 = 'A'
	AND FB10.LC_FOR_TYP = '40'
	AND LN60.LC_STA_LON60 = 'A'
	AND LN60.LC_FOR_RSP != '003' --Exclude denials
ORDER BY
	FB10.LD_FOR_REQ_BEG,
	LN60.BF_SSN,
	LN60.LN_SEQ