SELECT DISTINCT
	SUM(LN10.LA_CUR_PRI + ISNULL(LN10.LA_NSI_OTS,0)) AS BALANCE,
	COUNT(*) AS LOAN_COUNT
FROM
(
	SELECT DISTINCT
		PD30.DF_PRS_ID
	FROM
		UDW..PD30_PRS_ADR PD30
		INNER JOIN AuditUDW..LN10_LON_Apr2018 LN10
			ON LN10.BF_SSN = PD30.DF_PRS_ID
	WHERE
		DC_DOM_ST = 'CA'
		AND DF_PRS_ID NOT LIKE 'P%'
		AND DI_VLD_ADR = 'Y'
		AND DF_LST_DTS_PD30 < '05/01/2018'
		AND LA_CUR_PRI > 0.00
		AND LN10.LC_STA_LON10 = 'R'


	UNION --NO UNION ALL BECASE WE WANT TO DEDUP

	SELECT DISTINCT
		F.DF_PRS_ID
	FROM
		(
			SELECT * FROM OPENQUERY(DUSTER,
			'
			SELECT
				PD31.DF_PRS_ID
			FROM
				OLWHRM1.PD31_PRS_INA PD31
				INNER JOIN 
				(
					SELECT
						DF_PRS_ID,
						MAX(DN_ADR_SEQ) AS DN_ADR_SEQ --GETS LAST VALID ADDRESS
					FROM
						OLWHRM1.PD31_PRS_INA PD31
					WHERE
						PD31.DF_PRS_ID NOT LIKE ''P%''
						AND PD31.DI_VLD_ADR_HST = ''Y''
						AND PD31.DF_LST_DTS_PD31 < ''05/01/2018''
					GROUP BY
						DF_PRS_ID
				) MS
					ON MS.DF_PRS_ID = PD31.DF_PRS_ID
					AND MS.DN_ADR_SEQ = PD31.DN_ADR_SEQ
			WHERE
				PD31.DC_DOM_ST_HST = ''CA''

			') P
		) F
		INNER JOIN AuditUDW..LN10_LON_Apr2018 LN10
			ON LN10.BF_SSN = F.DF_PRS_ID
	WHERE
		LA_CUR_PRI > 0.00
		AND LN10.LC_STA_LON10 = 'R'
) ALL_BWRS
INNER JOIN AuditCDW..LN10_LON_Apr2018 LN10
		ON LN10.BF_SSN = ALL_BWRS.DF_PRS_ID