SELECT DISTINCT
	COUNT(LN10.LN_SEQ) AS CompleteLoanBorrowers,
	SUM(LN10.LA_CUR_PRI) AS CompleteLoanPrincipalBalance,
	SUM(CASE WHEN DW01.WC_DW_LON_STA = '02' THEN 1 ELSE 0 END) AS CompleteLoanInSchool,
	SUM(CASE WHEN DW01.WC_DW_LON_STA = '01' THEN 1 ELSE 0 END) AS CompleteLoanGrace,
	SUM(CASE WHEN DW01.WC_DW_LON_STA NOT IN('01','02','04','05') THEN 1 ELSE 0 END) AS CompleteLoanRepayment,
	SUM(CASE WHEN DW01.WC_DW_LON_STA = '04' THEN 1 ELSE 0 END) AS CompleteLoanDeferment,
	SUM(CASE WHEN DW01.WC_DW_LON_STA = '05' THEN 1 ELSE 0 END) AS CompleteLoanForbearance,
	SUM(CASE WHEN RS.LN_SEQ IS NOT NULL THEN 1 ELSE 0 END) AS CompleteLoanAltRepaymentSchedules	
FROM
	UDW..PD10_PRS_NME PD10
	INNER JOIN UDW..LN10_LON LN10
		ON LN10.BF_SSN = PD10.DF_PRS_ID
		AND LN10.LC_STA_LON10 = 'R'
		AND LN10.LA_CUR_PRI > 0.00
	INNER JOIN UDW..DW01_DW_CLC_CLU DW01
		ON DW01.BF_SSN = LN10.BF_SSN
		AND DW01.LN_SEQ = LN10.LN_SEQ
	INNER JOIN UDW..PD30_PRS_ADR PD30
		ON PD30.DF_PRS_ID = PD10.DF_PRS_ID
		AND PD30.DC_ADR = 'L'
		AND PD30.DC_DOM_ST = 'CA'
	LEFT JOIN UDW.calc.RepaymentSchedules RS
		ON RS.BF_SSN = LN10.BF_SSN
		AND RS.LN_SEQ = LN10.LN_SEQ
		AND RS.CurrentGradation = 1
		AND RS.LC_TYP_SCH_DIS != 'L'
WHERE
	LN10.IC_LON_PGM = 'COMPLT'

SELECT DISTINCT
	COUNT(LN10.LN_SEQ) AS CommercialFFELPBorrowers,
	SUM(LN10.LA_CUR_PRI) AS CommercialFFELPPrincipalBalance,
	SUM(CASE WHEN DW01.WC_DW_LON_STA = '02' THEN 1 ELSE 0 END) AS CommercialFFELPInSchool,
	SUM(CASE WHEN DW01.WC_DW_LON_STA = '01' THEN 1 ELSE 0 END) AS CommercialFFELPGrace,
	SUM(CASE WHEN DW01.WC_DW_LON_STA NOT IN('01','02','04','05') THEN 1 ELSE 0 END) AS CommercialFFELPRepayment,
	SUM(CASE WHEN DW01.WC_DW_LON_STA = '04' THEN 1 ELSE 0 END) AS CommercialFFELPDeferment,
	SUM(CASE WHEN DW01.WC_DW_LON_STA = '05' THEN 1 ELSE 0 END) AS CommercialFFELPForbearance,
	SUM(CASE WHEN RS.LN_SEQ IS NOT NULL THEN 1 ELSE 0 END) AS CommercialFFELPAltRepaymentSchedules
FROM
	UDW..PD10_PRS_NME PD10
	INNER JOIN UDW..LN10_LON LN10
		ON LN10.BF_SSN = PD10.DF_PRS_ID
		AND LN10.LC_STA_LON10 = 'R'
		AND LN10.LA_CUR_PRI > 0.00
	INNER JOIN UDW..DW01_DW_CLC_CLU DW01
		ON DW01.BF_SSN = LN10.BF_SSN
		AND DW01.LN_SEQ = LN10.LN_SEQ
	INNER JOIN UDW..PD30_PRS_ADR PD30
		ON PD30.DF_PRS_ID = PD10.DF_PRS_ID
		AND PD30.DC_ADR = 'L'
		AND PD30.DC_DOM_ST = 'CA'
	LEFT JOIN UDW.calc.RepaymentSchedules RS
		ON RS.BF_SSN = LN10.BF_SSN
		AND RS.LN_SEQ = LN10.LN_SEQ
		AND RS.CurrentGradation = 1
		AND RS.LC_TYP_SCH_DIS != 'L'
WHERE
	LN10.IC_LON_PGM NOT IN('COMPLT','TILP')