USE UDW
GO


SELECT DISTINCT
	LN90.BF_SSN,
	LN90.LN_SEQ,
	LN90.LN_FAT_SEQ,
	LN90.PC_FAT_TYP,
	LN90.PC_FAT_SUB_TYP,
	MAX(CASE 
		WHEN ARCS.LX_ATY LIKE '%Death%' THEN 'A'
		ELSE ''
	END) AS WRITE_OFF_REASONA,
	MAX(CASE 
		WHEN ARCS.LX_ATY LIKE '%Penalties%' THEN 'O'
		WHEN ARCS.LX_ATY LIKE '%TPD%' THEN 'O'
		ELSE ''
	END) AS WRITE_OFF_REASONO,
	MAX(CASE 
		WHEN ARCS.LX_ATY LIKE '%small bal%' THEN 'Z'
		WHEN ARCS.LX_ATY LIKE '%small blan%' THEN 'Z'
		ELSE ''
	END) AS WRITE_OFF_REASONZ,
	MAX(CASE 
		WHEN ARCS.LX_ATY LIKE '%Death%' THEN '' 
		WHEN ARCS.LX_ATY LIKE '%Penalties%'THEN ''
		WHEN ARCS.LX_ATY LIKE '%TPD%' THEN ''
		WHEN ARCS.LX_ATY LIKE '%small bal%' THEN ''
		WHEN ARCS.LX_ATY LIKE '%small blan%' THEN ''
		ELSE ARCS.LX_ATY
	END) WRITE_OFF_REASONOTHER
FROM
	UDW..LN90_FIN_ATY LN90
	INNER JOIN AD20_PCV_ATY_ADJ AD20
		 ON AD20.BF_SSN = LN90.BF_SSN
		AND AD20.LN_SEQ = LN90.LN_SEQ
	LEFT JOIN 
	(
		SELECT DISTINCT
			AY20.BF_SSN,
			STUFF(
			(
				SELECT 
						' ' + SUB.LX_ATY AS [text()]
				FROM 
					AY20_ATY_TXT SUB
					INNER JOIN PD10_PRS_NME PD10
						ON PD10.DF_PRS_ID = AY20.BF_SSN
				WHERE
					SUB.BF_SSN = AY20.BF_SSN
					AND SUB.LN_ATY_SEQ = AY20.LN_ATY_SEQ
			FOR XML PATH('')
			)
			,1,1, '') AS LX_ATY
			
		FROM	
			AY10_BR_LON_ATY AY10
			INNER JOIN AY20_ATY_TXT AY20
				ON AY10.BF_SSN = AY20.BF_SSN
				AND AY10.LN_ATY_SEQ = AY20.LN_ATY_SEQ
			INNER JOIN PD10_PRS_NME PD10
				ON PD10.DF_PRS_ID = AY20.BF_SSN
		WHERE
			AY10.PF_REQ_ACT = 'LSADJ'
	) ARCS
		ON ARCS.BF_SSN = LN90.BF_SSN

	WHERE 
		AD20.LC_TYP_FAT_ADJ_REQ = '15'
  AND AD20.LC_STA_FAT_ADJ_REQ = 'A'
  AND LN90.PC_FAT_TYP = '50'
  AND LN90.LC_STA_LON90 = 'A'
  AND ISNULL(LN90.LC_FAT_REV_REA,'') = ''
  AND LN90.LD_FAT_APL between '01/01/2019' and '11-07-2019'
    AND AD20.LD_FAT_ADJ_REQ_BEG = LN90.LD_FAT_EFF

GROUP BY
	LN90.BF_SSN,
	LN90.LN_SEQ,
	LN90.LN_FAT_SEQ,
	LN90.PC_FAT_TYP,
	LN90.PC_FAT_SUB_TYP