USE UDW
GO

SELECT 
	PD10.DF_SPE_ACC_ID AS ACCOUNT_NUMBER,
	LN10.LN_SEQ AS LOAN_SEQ,
	LN10.LA_CUR_PRI AS PRINCIPAL_BALANCE,
	DW01.WA_TOT_BRI_OTS AS OUTSTANDING_INTEREST
FROM 
	UDW..DW01_DW_CLC_CLU DW01
	INNER JOIN UDW..LN10_LON LN10
		ON LN10.BF_SSN = DW01.BF_SSN
		AND LN10.LN_SEQ = DW01.LN_SEQ
	INNER JOIN UDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = DW01.BF_SSN
WHERE
	DW01.WX_OVR_DW_LON_STA = 'CNSLD-STOP PURSUIT'
	AND LN10.LA_CUR_PRI > 100
ORDER BY
	PD10.DF_SPE_ACC_ID,
	LN10.LN_SEQ	
