USE UDW
GO

DROP TABLE IF EXISTS #POP

SELECT DISTINCT
	PD10.DF_SPE_ACC_ID AS ACCOUNT_NUMBER,
	LN10.LN_SEQ AS LOAN_SEQ,
	LN10.IC_LON_PGM AS LOAN_TYPE,
	ISNULL(CONVERT(VARCHAR(10), LN90.LD_FAT_EFF, 101), 'N/A') AS INT_PAID_THROUGH,
	CASE WHEN dw01.WX_OVR_DW_LON_STA != '' THEN dw01.WX_OVR_DW_LON_STA ELSE lk10.PX_DSC_MDM END AS LOAN_STATUS,
	LN10.IF_GTR AS GUARANTOR_CODE,
	LN10.LF_LON_CUR_OWN AS OWNER_CODE,
	LN16.LN_DLQ_MAX AS DAYS_PAST_DUE
INTO #POP
FROM
	UDW..LN16_LON_DLQ_HST LN16
	INNER JOIN UDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = LN16.BF_SSN
	INNER JOIN UDW..LN10_LON LN10
		ON LN10.BF_SSN = LN16.BF_SSN
		AND LN10.LN_SEQ = LN16.LN_SEQ
		AND LN10.LA_CUR_PRI > 0
		AND LN10.LC_STA_LON10 = 'R'
	INNER JOIN UDW..DW01_DW_CLC_CLU DW01
		ON DW01.BF_SSN = LN10.BF_SSN
		AND DW01.LN_SEQ = LN10.LN_SEQ
	INNER JOIN UDW..LK10_LS_CDE_LKP LK10
		ON LK10.PM_ATR = 'WC-DW-LON-STA'
		AND LK10.PX_ATR_VAL = DW01.WC_DW_LON_STA
	LEFT JOIN
	(
		SELECT
			BF_SSN,
			LN_SEQ,
			MAX(LD_FAT_EFF) AS LD_FAT_EFF
		FROM
			UDW..LN90_FIN_ATY
		WHERE
			LC_STA_LON90 = 'A'
			AND ISNULL(LC_FAT_REV_REA,'') = ''
			AND PC_FAT_TYP = '10'
			AND LA_FAT_NSI IS NOT NULL
		GROUP BY
			BF_SSN,
			LN_SEQ
	) LN90
		ON LN90.BF_SSN = LN16.BF_SSN
		AND LN90.LN_SEQ = LN16.LN_SEQ

WHERE
	LC_STA_LON16 = '1'
	AND LN_DLQ_MAX >= 240
	AND DATEDIFF(DAY, LN16.LD_DLQ_MAX, GETDATE()) <=5
	AND DW01.WC_DW_LON_STA != '06'

SELECT 
	* 
FROM 
	#POP
ORDER BY 
	ACCOUNT_NUMBER,
	LOAN_SEQ

SELECT
	DAYS_PAST_DUE,
	COUNT(DISTINCT ACCOUNT_NUMBER) AS BORROWER_COUNT,
	COUNT(*) AS LOAN_COUNT
FROM
	#POP
GROUP BY
	DAYS_PAST_DUE
ORDER BY
	DAYS_PAST_DUE