SELECT * FROM OPENQUERY (DUSTER, '
	SELECT DISTINCT
		LN10.BF_SSN
		,LN10.LN_SEQ
		,LN65.LC_TYP_SCH_DIS
		,RS05.BD_CRT_RS05
		,LN10.LD_LON_IBR_ENT
	FROM
		OLWHRM1.LN10_LON LN10
		INNER JOIN OLWHRM1.LN65_LON_RPS LN65
			ON LN10.BF_SSN = LN65.BF_SSN
			AND LN10.LN_SEQ = LN65.LN_SEQ
		INNER JOIN OLWHRM1.RS05_IBR_RPS RS05
			ON LN10.BF_SSN = RS05.BF_SSN
	WHERE
		LN65.LC_TYP_SCH_DIS IN (''IB'', ''IL'')
		AND LN65.LC_STA_LON65 = ''A''
		AND LN10.LD_LON_IBR_ENT IS NULL
		AND LN10.LA_CUR_PRI > 0
		AND LN10.LC_STA_LON10 = ''R''
');

--table dump
SELECT * FROM OPENQUERY (DUSTER, '
	SELECT DISTINCT
		RS05.*
	FROM
		OLWHRM1.LN10_LON LN10
		INNER JOIN OLWHRM1.LN65_LON_RPS LN65
			ON LN10.BF_SSN = LN65.BF_SSN
			AND LN10.LN_SEQ = LN65.LN_SEQ
		INNER JOIN OLWHRM1.RS05_IBR_RPS RS05
			ON LN10.BF_SSN = RS05.BF_SSN
	WHERE
		LN65.LC_TYP_SCH_DIS IN (''IB'', ''IL'')
		AND LN65.LC_STA_LON65 = ''A''
		AND LN10.LD_LON_IBR_ENT IS NULL
		AND LN10.LA_CUR_PRI > 0
		AND LN10.LC_STA_LON10 = ''R''
');