SELECT DISTINCT
	BF_SSN,
	LN_ATY_SEQ,
	PF_REQ_ACT,
	LC_STA_ACTY10
FROM 
	UDW..AY10_BR_LON_ATY AY10
WHERE
	AY10.PF_REQ_ACT = 'CTQRT'

SELECT
	RM_APL_PGM_PRC,
	RT_RUN_SRT_DTS_PRC,
	RN_SEQ_LTR_CRT_PRC,
	RN_SEQ_REC_PRC,
	RM_DSC_LTR_PRC,
	RF_SBJ_PRC
FROM
	UDW..LT20_LTR_REQ_PRC
WHERE 
	RM_DSC_LTR_PRC = 'US06CTQRT'