SELECT DISTINCT
	DAY(LD_RPS_1_PAY_DU) AS DUE_DATE,
	COUNT(DISTINCT BF_SSN) AS BWR_COUNT
FROM 
	Udw.calc.RepaymentSchedules
WHERE
	CurrentGradation = 1
GROUP BY
	DAY(LD_RPS_1_PAY_DU)
ORDER BY
	DAY(LD_RPS_1_PAY_DU)