USE UDW
GO

SELECT DISTINCT -- TOP 10
	PD10.DF_SPE_ACC_ID
	,WQ20.WF_QUE
	,DW01.WC_DW_LON_STA
	,MAX(LN16.LN_DLQ_MAX) AS MAX_LN_DLQ_MAX
	,CASE
		 WHEN DW01.WC_DW_LON_STA  = '01' THEN 'IN GRACE'
		 WHEN DW01.WC_DW_LON_STA  = '02' THEN 'IN SCHOOL'
		 WHEN DW01.WC_DW_LON_STA  = '03' THEN 'IN REPAYMENT'
		 WHEN DW01.WC_DW_LON_STA  = '04' THEN 'IN DEFERMENT'
		 WHEN DW01.WC_DW_LON_STA  = '05' THEN 'IN FORBEARANCE'
		 WHEN DW01.WC_DW_LON_STA  = '06' THEN 'IN CURE'
		 WHEN DW01.WC_DW_LON_STA  = '07' THEN 'CLAIM PENDING'
		 WHEN DW01.WC_DW_LON_STA  = '08' THEN 'CLAIM SUBMITTED'
		 WHEN DW01.WC_DW_LON_STA  = '09' THEN 'CLAIM CANCLED'
		 WHEN DW01.WC_DW_LON_STA  = '10' THEN 'CLAIM REJECT'
		 WHEN DW01.WC_DW_LON_STA  = '11' THEN 'CLAIM RETURNED'
		 WHEN DW01.WC_DW_LON_STA  = '12' THEN 'CLAIM PAID'
		 WHEN DW01.WC_DW_LON_STA  = '13' THEN 'PRE-CLAIM PENDING'
		 WHEN DW01.WC_DW_LON_STA  = '14' THEN 'PRE-CLAIM SUBMITTED'
		 WHEN DW01.WC_DW_LON_STA  = '15' THEN 'PRE-CLAIM CANCELLED'
		 WHEN DW01.WC_DW_LON_STA  = '16' THEN 'DEATH ALLEGED'
		 WHEN DW01.WC_DW_LON_STA  = '17' THEN 'DEATH VERIFIED'
		 WHEN DW01.WC_DW_LON_STA  = '18' THEN 'DISABILITY ALLEGED'
		 WHEN DW01.WC_DW_LON_STA  = '19' THEN 'DISABILITY VERIFIED'
		 WHEN DW01.WC_DW_LON_STA  = '20' THEN 'BANKRUPTCY ALLEGED'
		 WHEN DW01.WC_DW_LON_STA  = '21' THEN 'BANKRUPTCY VERIFIED'
		 WHEN DW01.WC_DW_LON_STA  = '22' THEN 'PAID IN FULL'
		 WHEN DW01.WC_DW_LON_STA  = '23' THEN 'NOT FULLY ORIGINATED'
		 WHEN DW01.WC_DW_LON_STA  = '88' THEN 'PROCESSING ERROR'
		 WHEN DW01.WC_DW_LON_STA  = '98' THEN 'UNKNOWN'
		 ELSE 'UNKNOWN'
	END AS [Loan Status]
FROM
	LN10_LON LN10
	INNER JOIN LN16_LON_DLQ_HST LN16
		ON LN10.BF_SSN = LN16.BF_SSN
		AND LN10.LN_SEQ = LN16.LN_SEQ
	INNER JOIN PD10_PRS_NME PD10
		ON LN10.BF_SSN = PD10.DF_PRS_ID
	INNER JOIN DW01_DW_CLC_CLU DW01
		ON LN10.BF_SSN = DW01.BF_SSN
		AND LN10.LN_SEQ = DW01.LN_SEQ
	INNER JOIN WQ20_TSK_QUE WQ20
		ON LN10.BF_SSN = WQ20.BF_SSN
WHERE
	WQ20.WF_QUE = '3C'
	AND LN10.LA_CUR_PRI > 0.00
	AND LN10.LC_STA_LON10 = 'R'
GROUP BY
	PD10.DF_SPE_ACC_ID
	,WQ20.WF_QUE
	,DW01.WC_DW_LON_STA
ORDER BY
	[Loan Status]