USE UDW
GO

SELECT 
	'LOAN STATUS: ' + LK10.PX_DSC_MDM AS [STATUS],
	COUNT(DISTINCT LN10.BF_SSN) AS BORROWER_COUNT,
	COUNT(*) AS LOAN_COUNT,
	SUM(LA_CUR_PRI) AS PRINCIPAL,
	SUM(ISNULL(DW01.LA_NSI_OTS,0.00)) AS INTEREST
FROM
	UDW..LN10_LON LN10
	INNER JOIN UDW..DW01_DW_CLC_CLU DW01
		ON DW01.BF_SSN = LN10.BF_SSN
		AND DW01.LN_SEQ = LN10.LN_SEQ
	INNER JOIN UDW..LK10_LS_CDE_LKP LK10
		ON LK10.PM_ATR = 'WC-DW-LON-STA'
		AND LK10.PX_ATR_VAL = DW01.WC_DW_LON_STA
	LEFT JOIN
	(
		SELECT 
			DF10.LC_DFR_TYP,
			LN50.BF_SSN,
			LN50.LN_SEQ
		FROM
			LN50_BR_DFR_APV LN50
			INNER JOIN DF10_BR_DFR_REQ DF10
				ON DF10.BF_SSN = LN50.BF_SSN
				AND DF10.LF_DFR_CTL_NUM = LN50.LF_DFR_CTL_NUM
			INNER JOIN 
			(
				SELECT
					MAX(LN50.LD_STA_LON50) AS MaxLN50,
					LN50.BF_SSN,
					LN50.LN_SEQ
				FROM
					LN50_BR_DFR_APV LN50
					INNER JOIN DF10_BR_DFR_REQ DF10
						ON DF10.BF_SSN = LN50.BF_SSN
						AND DF10.LF_DFR_CTL_NUM = LN50.LF_DFR_CTL_NUM
				WHERE
					LN50.LC_STA_LON50 = 'A'
					AND DF10.LC_STA_DFR10 = 'A'
					AND DF10.LC_DFR_STA = 'A'
					AND GETDATE() BETWEEN LN50.LD_DFR_BEG AND LN50.LD_DFR_END
				GROUP BY
					LN50.BF_SSN,
					LN50.LN_SEQ
			) LN50Max
				ON LN50.BF_SSN = LN50Max.BF_SSN
				AND LN50.LN_SEQ = LN50Max.LN_SEQ
				AND LN50Max.MaxLN50 = LN50.LD_STA_LON50
		WHERE
			LN50.LC_STA_LON50 = 'A'
			AND DF10.LC_STA_DFR10 = 'A'
			AND DF10.LC_DFR_STA = 'A' --removing this to account for denied requests
			AND GETDATE() BETWEEN LN50.LD_DFR_BEG AND LN50.LD_DFR_END
	) Defer
		ON Defer.BF_SSN = LN10.BF_SSN
		AND Defer.LN_SEQ = LN10.LN_SEQ
	LEFT JOIN UDW..LK10_LS_CDE_LKP LK10D
		ON LK10D.PM_ATR = 'LC-DFR-TYP'
		AND LK10D.PX_ATR_VAL = DEFER.LC_DFR_TYP
WHERE
	LN10.IC_LON_PGM = 'TILP'
	AND LN10.LA_CUR_PRI > 0
	AND LN10.LC_STA_LON10 = 'R' 
GROUP BY
	'LOAN STATUS: ' + LK10.PX_DSC_MDM 
ORDER BY 
	'LOAN STATUS: ' + LK10.PX_DSC_MDM 


--For each loan status can a list be provided that includes the account number, loan sequence, loan status, prinicpal and interest balances
SELECT DISTINCT
	'LOAN STATUS: ' + LK10.PX_DSC_MDM AS [STATUS],
	RTRIM(PD10.DM_PRS_1) AS FirstName,
	RTRIM(PD10.DM_PRS_MID) AS MiddleName,
	RTRIM(PD10.DM_PRS_LST) AS LastName,
	PD30.DC_DOM_ST AS StateOfResidence,
	LN10.LF_DOE_SCL_ORG AS SchoolCode,
	RTRIM(SC10.IM_SCL_FUL) AS OriginalSchool,
	PD10.DF_SPE_ACC_ID AS AccountNumber,
	LN10.LN_SEQ AS LoanSequence,
	LN10.LA_CUR_PRI AS PRINCIPAL,
	ISNULL(DW01.LA_NSI_OTS,0.00) AS INTEREST
FROM
	UDW..LN10_LON LN10
	INNER JOIN UDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = LN10.BF_SSN
	INNER JOIN UDW..DW01_DW_CLC_CLU DW01
		ON DW01.BF_SSN = LN10.BF_SSN
		AND DW01.LN_SEQ = LN10.LN_SEQ
	INNER JOIN UDW..LK10_LS_CDE_LKP LK10
		ON LK10.PM_ATR = 'WC-DW-LON-STA'
		AND LK10.PX_ATR_VAL = DW01.WC_DW_LON_STA
	LEFT JOIN UDW..SC10_SCH_DMO SC10
		ON SC10.IF_DOE_SCL = LN10.LF_DOE_SCL_ORG
	LEFT JOIN UDW..PD30_PRS_ADR PD30
		ON PD30.DF_PRS_ID = PD10.DF_PRS_ID
		AND PD30.DC_ADR = 'L'
	LEFT JOIN
	(
		SELECT 
			DF10.LC_DFR_TYP,
			LN50.BF_SSN,
			LN50.LN_SEQ
		FROM
			LN50_BR_DFR_APV LN50
			INNER JOIN DF10_BR_DFR_REQ DF10
				ON DF10.BF_SSN = LN50.BF_SSN
				AND DF10.LF_DFR_CTL_NUM = LN50.LF_DFR_CTL_NUM
			INNER JOIN 
			(
				SELECT
					MAX(LN50.LD_STA_LON50) AS MaxLN50,
					LN50.BF_SSN,
					LN50.LN_SEQ
				FROM
					LN50_BR_DFR_APV LN50
					INNER JOIN DF10_BR_DFR_REQ DF10
						ON DF10.BF_SSN = LN50.BF_SSN
						AND DF10.LF_DFR_CTL_NUM = LN50.LF_DFR_CTL_NUM
				WHERE
					LN50.LC_STA_LON50 = 'A'
					AND DF10.LC_STA_DFR10 = 'A'
					AND DF10.LC_DFR_STA = 'A'
					AND GETDATE() BETWEEN LN50.LD_DFR_BEG AND LN50.LD_DFR_END
				GROUP BY
					LN50.BF_SSN,
					LN50.LN_SEQ
			) LN50Max
				ON LN50.BF_SSN = LN50Max.BF_SSN
				AND LN50.LN_SEQ = LN50Max.LN_SEQ
				AND LN50Max.MaxLN50 = LN50.LD_STA_LON50
		WHERE
			LN50.LC_STA_LON50 = 'A'
			AND DF10.LC_STA_DFR10 = 'A'
			AND DF10.LC_DFR_STA = 'A' --removing this to account for denied requests
			AND GETDATE() BETWEEN LN50.LD_DFR_BEG AND LN50.LD_DFR_END
	) Defer
		ON Defer.BF_SSN = LN10.BF_SSN
		AND Defer.LN_SEQ = LN10.LN_SEQ
	LEFT JOIN UDW..LK10_LS_CDE_LKP LK10D
		ON LK10D.PM_ATR = 'LC-DFR-TYP'
		AND LK10D.PX_ATR_VAL = DEFER.LC_DFR_TYP
WHERE
	LN10.IC_LON_PGM = 'TILP'
	AND LN10.LA_CUR_PRI > 0
	AND LN10.LC_STA_LON10 = 'R' 
ORDER BY 
	'LOAN STATUS: ' + LK10.PX_DSC_MDM 


USE UDW
GO

SELECT 
	CASE 
		WHEN LK10.PX_DSC_MDM = 'IN DEFERMENT' THEN 'DEFERMENT TYPE: ' + LK10D.PX_DSC_LNG
		ELSE 'LOAN STATUS: ' + LK10.PX_DSC_MDM
	END AS [DEFERMENT],
	COUNT(DISTINCT LN10.BF_SSN) AS BORROWER_COUNT,
	COUNT(*) AS LOAN_COUNT,
	SUM(LA_CUR_PRI) AS PRINCIPAL,
	SUM(ISNULL(DW01.LA_NSI_OTS,0.00)) AS INTEREST
FROM
	UDW..LN10_LON LN10
	INNER JOIN UDW..DW01_DW_CLC_CLU DW01
		ON DW01.BF_SSN = LN10.BF_SSN
		AND DW01.LN_SEQ = LN10.LN_SEQ
	INNER JOIN UDW..LK10_LS_CDE_LKP LK10
		ON LK10.PM_ATR = 'WC-DW-LON-STA'
		AND LK10.PX_ATR_VAL = DW01.WC_DW_LON_STA
	INNER JOIN
	(
		SELECT 
			DF10.LC_DFR_TYP,
			LN50.BF_SSN,
			LN50.LN_SEQ
		FROM
			LN50_BR_DFR_APV LN50
			INNER JOIN DF10_BR_DFR_REQ DF10
				ON DF10.BF_SSN = LN50.BF_SSN
				AND DF10.LF_DFR_CTL_NUM = LN50.LF_DFR_CTL_NUM
			INNER JOIN 
			(
				SELECT
					MAX(LN50.LD_STA_LON50) AS MaxLN50,
					LN50.BF_SSN,
					LN50.LN_SEQ
				FROM
					LN50_BR_DFR_APV LN50
					INNER JOIN DF10_BR_DFR_REQ DF10
						ON DF10.BF_SSN = LN50.BF_SSN
						AND DF10.LF_DFR_CTL_NUM = LN50.LF_DFR_CTL_NUM
				WHERE
					LN50.LC_STA_LON50 = 'A'
					AND DF10.LC_STA_DFR10 = 'A'
					AND DF10.LC_DFR_STA = 'A'
					AND GETDATE() BETWEEN LN50.LD_DFR_BEG AND LN50.LD_DFR_END
				GROUP BY
					LN50.BF_SSN,
					LN50.LN_SEQ
			) LN50Max
				ON LN50.BF_SSN = LN50Max.BF_SSN
				AND LN50.LN_SEQ = LN50Max.LN_SEQ
				AND LN50Max.MaxLN50 = LN50.LD_STA_LON50
		WHERE
			LN50.LC_STA_LON50 = 'A'
			AND DF10.LC_STA_DFR10 = 'A'
			AND DF10.LC_DFR_STA = 'A' --removing this to account for denied requests
			AND GETDATE() BETWEEN LN50.LD_DFR_BEG AND LN50.LD_DFR_END
	) Defer
		ON Defer.BF_SSN = LN10.BF_SSN
		AND Defer.LN_SEQ = LN10.LN_SEQ
	LEFT JOIN UDW..LK10_LS_CDE_LKP LK10D
		ON LK10D.PM_ATR = 'LC-DFR-TYP'
		AND LK10D.PX_ATR_VAL = DEFER.LC_DFR_TYP
WHERE
	LN10.IC_LON_PGM = 'TILP'
	AND LN10.LA_CUR_PRI > 0
	AND LN10.LC_STA_LON10 = 'R' 
GROUP BY
	CASE 
		WHEN LK10.PX_DSC_MDM = 'IN DEFERMENT' THEN 'DEFERMENT TYPE: ' + LK10D.PX_DSC_LNG
		ELSE 'LOAN STATUS: ' + LK10.PX_DSC_MDM
	END
ORDER BY 
	CASE 
		WHEN LK10.PX_DSC_MDM = 'IN DEFERMENT' THEN 'DEFERMENT TYPE: ' + LK10D.PX_DSC_LNG
		ELSE 'LOAN STATUS: ' + LK10.PX_DSC_MDM
	END DESC

SELECT 
	CASE 
		WHEN LK10.PX_DSC_MDM = 'IN DEFERMENT' THEN 'DEFERMENT TYPE: ' + LK10D.PX_DSC_LNG
		ELSE 'LOAN STATUS: ' + LK10.PX_DSC_MDM
	END AS [DEFERMENT],
	RTRIM(PD10.DM_PRS_1) AS FirstName,
	RTRIM(PD10.DM_PRS_MID) AS MiddleName,
	RTRIM(PD10.DM_PRS_LST) AS LastName,
	PD30.DC_DOM_ST AS StateOfResidence,
	LN10.LF_DOE_SCL_ORG AS SchoolCode,
	RTRIM(SC10.IM_SCL_FUL) AS OriginalSchool,
	PD10.DF_SPE_ACC_ID AS AccountNumber,
	LN10.LN_SEQ,
	LA_CUR_PRI AS PRINCIPAL,
	ISNULL(DW01.LA_NSI_OTS,0.00) AS INTEREST
FROM
	UDW..LN10_LON LN10
	INNER JOIN UDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = LN10.BF_SSN
	INNER JOIN UDW..DW01_DW_CLC_CLU DW01
		ON DW01.BF_SSN = LN10.BF_SSN
		AND DW01.LN_SEQ = LN10.LN_SEQ
	INNER JOIN UDW..LK10_LS_CDE_LKP LK10
		ON LK10.PM_ATR = 'WC-DW-LON-STA'
		AND LK10.PX_ATR_VAL = DW01.WC_DW_LON_STA
	INNER JOIN
	(
		SELECT 
			DF10.LC_DFR_TYP,
			LN50.BF_SSN,
			LN50.LN_SEQ
		FROM
			LN50_BR_DFR_APV LN50
			INNER JOIN DF10_BR_DFR_REQ DF10
				ON DF10.BF_SSN = LN50.BF_SSN
				AND DF10.LF_DFR_CTL_NUM = LN50.LF_DFR_CTL_NUM
			INNER JOIN 
			(
				SELECT
					MAX(LN50.LD_STA_LON50) AS MaxLN50,
					LN50.BF_SSN,
					LN50.LN_SEQ
				FROM
					LN50_BR_DFR_APV LN50
					INNER JOIN DF10_BR_DFR_REQ DF10
						ON DF10.BF_SSN = LN50.BF_SSN
						AND DF10.LF_DFR_CTL_NUM = LN50.LF_DFR_CTL_NUM
				WHERE
					LN50.LC_STA_LON50 = 'A'
					AND DF10.LC_STA_DFR10 = 'A'
					AND DF10.LC_DFR_STA = 'A'
					AND GETDATE() BETWEEN LN50.LD_DFR_BEG AND LN50.LD_DFR_END
				GROUP BY
					LN50.BF_SSN,
					LN50.LN_SEQ
			) LN50Max
				ON LN50.BF_SSN = LN50Max.BF_SSN
				AND LN50.LN_SEQ = LN50Max.LN_SEQ
				AND LN50Max.MaxLN50 = LN50.LD_STA_LON50
		WHERE
			LN50.LC_STA_LON50 = 'A'
			AND DF10.LC_STA_DFR10 = 'A'
			AND DF10.LC_DFR_STA = 'A' --removing this to account for denied requests
			AND GETDATE() BETWEEN LN50.LD_DFR_BEG AND LN50.LD_DFR_END
	) Defer
		ON Defer.BF_SSN = LN10.BF_SSN
		AND Defer.LN_SEQ = LN10.LN_SEQ
	LEFT JOIN UDW..SC10_SCH_DMO SC10
		ON SC10.IF_DOE_SCL = LN10.LF_DOE_SCL_ORG
	LEFT JOIN UDW..PD30_PRS_ADR PD30
		ON PD30.DF_PRS_ID = PD10.DF_PRS_ID
		AND PD30.DC_ADR = 'L'
	LEFT JOIN UDW..LK10_LS_CDE_LKP LK10D
		ON LK10D.PM_ATR = 'LC-DFR-TYP'
		AND LK10D.PX_ATR_VAL = DEFER.LC_DFR_TYP
WHERE
	LN10.IC_LON_PGM = 'TILP'
	AND LN10.LA_CUR_PRI > 0
	AND LN10.LC_STA_LON10 = 'R' 
ORDER BY 
	CASE 
		WHEN LK10.PX_DSC_MDM = 'IN DEFERMENT' THEN 'DEFERMENT TYPE: ' + LK10D.PX_DSC_LNG
		ELSE 'LOAN STATUS: ' + LK10.PX_DSC_MDM
	END DESC