/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;

LIBNAME  DUSTER  REMOTE  SERVER=DUSTER  SLIBREF=WORK; /*live*/
RSUBMIT;

%LET DB = DLGSUTWH; /*live*/

/*LD_DLQ_OCC = Set to blank if LC-STA_LON16 <> '1' (active) OR if (LC_STA_LON16 = '1' and LD_DLQ_MAX <> previous day).*/
/*LN_DLQ_MAX = Set to 0 if LC-STA_LON16 <> '1' (active) OR if (LC_STA_LON16 = '1' and LD_DLQ_MAX <> previous day).*/

PROC SQL;
CONNECT TO DB2 (DATABASE=&DB); 
	CREATE TABLE Demos AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
			SELECT DISTINCT
				PD10.DF_SPE_ACC_ID,
				LN10.LD_LON_ACL_ADD,
				CASE WHEN DAYS(LD_DLQ_MAX) <> DAYS(Current Date - 1 day) THEN 0 ELSE COALESCE(LN16.LN_DLQ_MAX,0) END AS LN_DLQ_MAX,
				LN16.LD_DLQ_MAX,
				SUM(LN80.LA_BIL_CUR_DU)
			FROM	
				OLWHRM1.PD10_PRS_NME PD10
				INNER JOIN OLWHRM1.LN10_LON LN10 
					ON LN10.BF_SSN = PD10.DF_PRS_ID
				INNER JOIN OLWHRM1.LN83_EFT_TO_LON LN83
					ON LN83.BF_SSN = LN10.BF_SSN
					AND LN83.LN_SEQ = LN10.LN_SEQ
					AND LN83.LC_STA_LN83 = 'A'
					AND LN83.LD_EFT_EFF_BEG >= '2016-02-01'
				LEFT JOIN
					(
						SELECT DISTINCT
							BF_SSN,
							LN_SEQ,
							MIN(LA_BIL_CUR_DU) AS LA_BIL_CUR_DU
						FROM
							OLWHRM1.LN80_LON_BIL_CRF
						WHERE
							LC_STA_LON80 = 'A'
						GROUP BY
							BF_SSN,
							LN_SEQ
					) LN80 ON LN80.BF_SSN = LN10.BF_SSN
					AND LN80.LN_SEQ = LN10.LN_SEQ
				LEFT JOIN 
					(
						SELECT DISTINCT
							BF_SSN,
							LN_SEQ,
							LD_DLQ_OCC,
							LN_DLQ_MAX,
							LD_DLQ_MAX
						FROM 
							OLWHRM1.LN16_LON_DLQ_HST
						WHERE
							LC_STA_LON16 = '1'
						
					) LN16 ON LN16.BF_SSN = LN10.BF_SSN
					AND LN16.LN_SEQ = LN10.LN_SEQ
				LEFT JOIN
					(
						SELECT DISTINCT
							BF_SSN,
							LN_SEQ
						FROM
							OLWHRM1.LN90_FIN_ATY
						WHERE
							LC_STA_LON90 = 'A'
    						AND (LC_FAT_REV_REA = '' OR LC_FAT_REV_REA IS NULL)
    						AND PC_FAT_TYP = '10'
    						AND PC_FAT_SUB_TYP = '10'
							AND LD_FAT_EFF = '2016-02-28'
					) LN90 ON LN90.BF_SSN = LN10.BF_SSN
					AND LN90.LN_SEQ = LN10.LN_SEQ
			WHERE	
				LN10.LD_LON_ACL_ADD >= '2016-02-01' AND LN10.LD_LON_ACL_ADD < '2016-02-26'
				AND LN10.LF_LON_CUR_OWN LIKE '829769%'
				AND LN90.BF_SSN IS NULL /*no posting on the 28th*/
				/*AND LN10.LA_CUR_PRI > 0*/
			GROUP BY
				PD10.DF_SPE_ACC_ID,
				LN10.LD_LON_ACL_ADD,
				CASE WHEN DAYS(LD_DLQ_MAX) <> DAYS(Current Date - 1 day) THEN 0 ELSE COALESCE(LN16.LN_DLQ_MAX,0) END,
				LN16.LD_DLQ_MAX
			)
	;
DISCONNECT FROM DB2;
QUIT;

ENDRSUBMIT;

DATA Demos;
	SET DUSTER.Demos;
	FORMAT LD_LON_ACL_ADD MMDDYY10.;
RUN;

PROC EXPORT
		DATA=Demos
		OUTFILE="&RPTLIB\UNH 26299.xlsx"
		DBMS = EXCEL
		REPLACE;
		SHEET="A";
RUN;
