/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;

LIBNAME  DUSTER  REMOTE  SERVER=DUSTER  SLIBREF=WORK;
RSUBMIT;
/*LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/

PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE DEMO AS
SELECT *
FROM 
	CONNECTION TO DB2 (
		SELECT
			GA11.AF_APL_ID,
			GA11.AF_APL_ID_SFX,
			GA11.AN_DSB_SEQ,
			GA11.AF_CRT_DTS_GA11
		FROM	
			OLWHRM1.GA11_LON_DSB_ATY GA11
		WHERE	
			GA11.AF_APL_ID = '0040270000M001483'
			AND GA11.AF_APL_ID_SFX = '02'
			AND GA11.AN_DSB_SEQ = '1'

			FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
ENDRSUBMIT;
DATA DEMO;
	SET DUSTER.DEMO;
RUN;

PROC EXPORT DATA= WORK.DEMO 
            OUTFILE= "T:\SAS\GA11_Query.xlsx" 
            DBMS=EXCEL REPLACE;
     SHEET="A"; 
RUN;
