%LET RPTLIB = T:\SAS;

LIBNAME  DUSTER  REMOTE  SERVER=DUSTER  SLIBREF=WORK; /*live*/
/*LIBNAME  DUSTER  REMOTE  SERVER=QADBD004 SLIBREF=WORK ; /*test*/
RSUBMIT;

%LET DB = DLGSUTWH; /*live*/
/*%LET DB = DLGSWQUT; /*test*/

%MACRO SQLCHECK ;
  %IF  &SQLXRC NE 0  %THEN  %DO  ;
    DATA _NULL_  ;
            FILE REPORTZ NOTITLES  ;
            PUT @01 " ********************************************************************* "
              / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
              / @01 " ****  THE SAS SHOULD BE REVIEWED.                                **** "       
              / @01 " ********************************************************************* "
              / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
              / @01 " ****  &SQLXMSG   **** "
              / @01 " ********************************************************************* "
            ;
         RUN  ;
  %END  ;
%MEND  ;

PROC SQL;
CONNECT TO DB2 (DATABASE=&DB); 
	CREATE TABLE BANA AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
				SELECT DISTINCT
					BF_SSN
					,LC_STA_LON10
					,LA_CUR_PRI
					,LF_LON_CUR_OWN
				FROM
					OLWHRM1.LN10_LON
				WHERE
					LC_STA_LON10 = 'R'
					AND LA_CUR_PRI > 0 
					AND LF_LON_CUR_OWN LIKE '829769%'
			)
	;
	CREATE TABLE BANA_IBR AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
				SELECT DISTINCT
					LN10.BF_SSN
					,LN10.LC_STA_LON10
					,LN10.LA_CUR_PRI
					,LN10.LF_LON_CUR_OWN
					,LN65.LC_TYP_SCH_DIS
					,LN65.LC_STA_LON65
				FROM
					OLWHRM1.LN10_LON LN10
					INNER JOIN OLWHRM1.LN65_LON_RPS LN65
					 ON LN10.BF_SSN = LN65.BF_SSN
					 AND LN10.LN_SEQ = LN65.LN_SEQ
				WHERE
					LN10.LC_STA_LON10 = 'R'
					AND LN10.LA_CUR_PRI > 0 
					AND LN10.LF_LON_CUR_OWN LIKE '829769%'
					AND LN65.LC_TYP_SCH_DIS IN ('IB','IL','IP','I3')
					AND	LN65.LC_STA_LON65 = 'A'

			)
	;
	CREATE TABLE NO_BANA AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
				SELECT DISTINCT
					BF_SSN
					,LC_STA_LON10
					,LA_CUR_PRI
					,LF_LON_CUR_OWN
				FROM
					OLWHRM1.LN10_LON
				WHERE
					LC_STA_LON10 = 'R'
					AND LA_CUR_PRI > 0 
					AND LF_LON_CUR_OWN NOT LIKE '829769%'
			)
	;
	CREATE TABLE NO_BANA_IBR AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
				SELECT DISTINCT
					LN10.BF_SSN
					,LN10.LC_STA_LON10
					,LN10.LA_CUR_PRI
					,LN10.LF_LON_CUR_OWN
					,LN65.LC_TYP_SCH_DIS
					,LN65.LC_STA_LON65
				FROM
					OLWHRM1.LN10_LON LN10
					INNER JOIN OLWHRM1.LN65_LON_RPS LN65
					 ON LN10.BF_SSN = LN65.BF_SSN
					 AND LN10.LN_SEQ = LN65.LN_SEQ
				WHERE
					LN10.LC_STA_LON10 = 'R'
					AND LN10.LA_CUR_PRI > 0 
					AND LN10.LF_LON_CUR_OWN NOT LIKE '829769%'
					AND LN65.LC_TYP_SCH_DIS IN ('IB','IL','IP','I3')
					AND	LN65.LC_STA_LON65 = 'A'
			)
	;
	CREATE TABLE Q2LEGACY AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
				SELECT DISTINCT
					LN10.BF_SSN
					,LN10.LF_LON_CUR_OWN
					,LN10.LC_STA_LON10
					,LN10.LA_CUR_PRI
					,WQ20.WF_QUE
					,WQ20.WC_STA_WQUE20
				FROM
					OLWHRM1.LN10_LON LN10
					INNER JOIN OLWHRM1.WQ20_TSK_QUE WQ20
						ON LN10.BF_SSN = WQ20.BF_SSN
				WHERE
					LN10.LF_LON_CUR_OWN NOT LIKE '829769%'
					AND LN10.LC_STA_LON10 = 'R'
					AND LN10.LA_CUR_PRI > 0 
					AND WQ20.WF_QUE = '2A' 
					AND WQ20.WC_STA_WQUE20 IN ('A','H','P','U','W') 
			)
	;
	CREATE TABLE Q2BANA AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
				SELECT DISTINCT
					LN10.BF_SSN
					,LN10.LF_LON_CUR_OWN
					,LN10.LC_STA_LON10
					,LN10.LA_CUR_PRI
					,WQ20.WF_QUE
					,WQ20.WC_STA_WQUE20
				FROM
					OLWHRM1.LN10_LON LN10
					INNER JOIN OLWHRM1.WQ20_TSK_QUE WQ20
						ON LN10.BF_SSN = WQ20.BF_SSN
				WHERE
					LF_LON_CUR_OWN LIKE '829769%'
					AND LN10.LC_STA_LON10 = 'R'
					AND LN10.LA_CUR_PRI > 0
					AND WQ20.WF_QUE = '2A' 
					AND WQ20.WC_STA_WQUE20 IN ('A','H','P','U','W') 
			)
	;

DISCONNECT FROM DB2;

%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>> ;  
%SQLCHECK;
QUIT;

ENDRSUBMIT;

DATA BANA;
	SET DUSTER.BANA;
RUN;

DATA BANA_IBR;
	SET DUSTER.BANA_IBR;
RUN;

DATA NO_BANA;
	SET DUSTER.NO_BANA;
RUN;

DATA NO_BANA_IBR;
	SET DUSTER.NO_BANA_IBR;
RUN;

DATA Q2LEGACY;
	SET DUSTER.Q2LEGACY;
RUN;

DATA Q2BANA;
	SET DUSTER.Q2BANA;
RUN;

PROC SQL NOPRINT;
	CREATE TABLE Q1_COUNTS 
		(
		WITH_BANA_COUNT INT
		,WITH_BANA_ON_IBR_COUNT INT
		,NO_BANA_COUNT INT
		,NO_BANA_ON_IBR_COUNT INT
		);
	INSERT INTO Q1_COUNTS (WITH_BANA_COUNT) 		
		SELECT COUNT(DISTINCT BF_SSN) 
		FROM WORK.BANA;
	INSERT INTO Q1_COUNTS (WITH_BANA_ON_IBR_COUNT) 	
		SELECT COUNT(DISTINCT BF_SSN) 
		FROM WORK.BANA_IBR;
	INSERT INTO Q1_COUNTS (NO_BANA_COUNT) 		
		SELECT COUNT(DISTINCT BF_SSN) 
		FROM WORK.NO_BANA;
	INSERT INTO Q1_COUNTS (NO_BANA_ON_IBR_COUNT) 
		SELECT COUNT(DISTINCT BF_SSN) 
		FROM WORK.NO_BANA_IBR;
QUIT;

PROC SQL NOPRINT;
	CREATE TABLE Q2_COUNTS 
		(
		LEGACY_COUNT INT
		,BANA_COUNT INT
		);
	INSERT INTO Q2_COUNTS (LEGACY_COUNT) 		
		SELECT COUNT(DISTINCT BF_SSN) 
		FROM WORK.Q2LEGACY;
	INSERT INTO Q2_COUNTS (BANA_COUNT) 	
		SELECT COUNT(DISTINCT BF_SSN) 
		FROM WORK.Q2BANA;
QUIT;

PROC EXPORT
		DATA=Q1_COUNTS
		OUTFILE="&RPTLIB\UNH 26639.xlsx"
		DBMS = EXCEL
		REPLACE;
		SHEET="Q1_COUNTS";
RUN;

PROC EXPORT
		DATA=Q2_COUNTS
		OUTFILE="&RPTLIB\UNH 26639.xlsx"
		DBMS = EXCEL
		REPLACE;
		SHEET="Q2_COUNTS";
RUN;

PROC EXPORT
		DATA=BANA
		OUTFILE="&RPTLIB\UNH 26639.xlsx"
		DBMS = EXCEL
		REPLACE;
		SHEET="Q1_with_BANA";
RUN;

PROC EXPORT
		DATA=BANA_IBR
		OUTFILE="&RPTLIB\UNH 26639.xlsx"
		DBMS = EXCEL
		REPLACE;
		SHEET="Q1_with_BANA_on_IBR";
RUN;

PROC EXPORT
		DATA=NO_BANA
		OUTFILE="&RPTLIB\UNH 26639.xlsx"
		DBMS = EXCEL
		REPLACE;
		SHEET="Q1_no_BANA";
RUN;

PROC EXPORT
		DATA=NO_BANA_IBR
		OUTFILE="&RPTLIB\UNH 26639.xlsx"
		DBMS = EXCEL
		REPLACE;
		SHEET="Q1_no_BANA_on_IBR";
RUN;

PROC EXPORT
		DATA=Q2LEGACY
		OUTFILE="&RPTLIB\UNH 26639.xlsx"
		DBMS = EXCEL
		REPLACE;
		SHEET="Q2_LEGACY";
RUN;

PROC EXPORT
		DATA=Q2BANA
		OUTFILE="&RPTLIB\UNH 26639.xlsx"
		DBMS = EXCEL
		REPLACE;
		SHEET="Q2_BANA";
RUN;
