USE ODW
GO

SELECT
	PD01.DF_SPE_ACC_ID,
	COUNT(*) AS LOAN_COUNT,
	SUM(ISNULL(LA_CLM_BAL,0.00) + ISNULL(LA_CLM_INT_ACR,0.00)) AS PRINCIPAL_INTEREST
FROM
	ODW..DC11_LON_FAT DC11
	INNER JOIN ODW..PD01_PDM_INF PD01
		ON PD01.DF_PRS_ID = DC11.BF_SSN
	LEFT JOIN ODW..DC02_BAL_INT DC02
			ON DC02.AF_APL_ID = DC11.AF_APL_ID
			AND DC02.AF_APL_ID_SFX = DC11.AF_APL_ID_SFX
WHERE 
	LD_TRX_EFF >= '03-13-2020'
	AND LC_TRX_TYP = 'DC'
	AND LC_REV_IND_TYP = ''
GROUP BY 
	PD01.DF_SPE_ACC_ID