LIBNAME DUSTER REMOTE SERVER=DUSTER SLIBREF=WORK;
RSUBMIT;
LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
PROC SQL;
	CREATE TABLE CLMS AS
		SELECT 	DISTINCT
			PD10.DF_SPE_ACC_ID
		FROM 
			OLWHRM1.PD10_PRS_NME PD10
			JOIN OLWHRM1.LN10_LON LN10
				ON PD10.DF_PRS_ID = LN10.BF_SSN	
				AND LN10.IF_GTR NE '000749'
			JOIN OLWHRM1.LN16_LON_DLQ_HST LN16
				ON LN10.BF_SSN = LN16.BF_SSN
				AND LN10.LN_SEQ = LN16.LN_SEQ
				AND LN16.LN_DLQ_MAX > 280
				AND LN16.LC_STA_LON16 = '1'
			JOIN OLWHRM1.FB10_BR_FOR_REQ FB10
				ON PD10.DF_PRS_ID = FB10.BF_SSN	
			JOIN OLWHRM1.LN60_BR_FOR_APV LN60
				ON FB10.BF_SSN = LN60.BF_SSN
				AND LN10.LN_SEQ = LN60.LN_SEQ
				AND FB10.LF_FOR_CTL_NUM = LN60.LF_FOR_CTL_NUM
				AND FB10.LC_FOR_TYP = '09'
				AND LN60.LC_STA_LON60 = 'A'
				AND FB10.LC_FOR_STA = 'A'
				AND FB10.LC_STA_FOR10 = 'A'
				AND LN60.LD_FOR_BEG = '30MAY2014'D
	;
QUIT;
ENDRSUBMIT;

PROC EXPORT
		DATA=DUSTER.CLMS
		OUTFILE='T:\Claim Filing Query - Align Loans.XLSX'
		REPLACE;
RUN;
