USE ODW
GO



SELECT DISTINCT
	sum(LA_CLM_PRI) as principal_defaulted,
	sum(AA_GTE_LON_AMT) as amount_guaranteed 
FROM
	ODW..PD01_PDM_INF PD01
	INNER JOIN ODW..GA01_APP GA01
		ON GA01.DF_PRS_ID_BR = PD01.DF_PRS_ID
	INNER JOIN ODW..GA10_LON_APP GA10
		ON GA10.AF_APL_ID = GA01.AF_APL_ID
	inner join odw..DC01_LON_CLM_INF DC01
		ON DC01.AF_APL_ID = GA10.AF_APL_ID
		AND DC01.AF_APL_ID_SFX = GA10.AF_APL_ID_SFX
WHERE

	  LC_STA_DC10 in('03','04')


	
