SELECT DISTINCT
	FB10.BF_SSN,
	RTRIM(PD10.DM_PRS_1) + ' ' + RTRIM(PD10.DM_PRS_LST) AS [NAME],
	FB10.LD_CRT_REQ_FOR, 
	FB10.LF_USR_CRT_REQ_FOR
FROM 
	ULS..ArcAddProcessing AAP
	INNER JOIN UDW..PD10_PRS_NME PD10
		ON PD10.DF_SPE_ACC_ID = AAP.AccountNumber
	INNER JOIN UDW..FB10_BR_FOR_REQ FB10
		ON FB10.BF_SSN = PD10.DF_PRS_ID
		AND CAST(FB10.LD_CRT_REQ_FOR AS DATE) = CAST(AAP.CreatedAt AS DATE)
		
WHERE 
	ScriptId LIKE 'VER%'
	AND CreatedAt > '04/01/2021'
	AND Comment LIKE 'Verbal forbearance Approved%'