LIBNAME DUSTER REMOTE SERVER=DUSTER SLIBREF=WORK;
RSUBMIT;
LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
PROC SQL;
	CREATE TABLE DEMO AS
		SELECT DISTINCT
			PD01.DF_SPE_ACC_ID AS Account_Number,
			AY01.BD_ATY_PRF AS MXADD_Time_Stamp,
			GA10.AX_LON_SRC_CDE AS Demographic_Source_Code,
			PD03.DC_PHN_SRC,
			AY01.BX_CMT,
			PD01.DX_SRC
		FROM
			OLWHRM1.PD01_PDM_INF PD01
			JOIN OLWHRM1.GA01_APP GA01
				ON PD01.DF_PRS_ID = GA01.DF_PRS_ID_BR
			JOIN OLWHRM1.GA10_LON_APP GA10
				ON GA01.AF_APL_ID = GA10.AF_APL_ID
			JOIN OLWHRM1.AY01_BR_ATY AY01
				ON PD01.DF_PRS_ID = AY01.DF_PRS_ID
			LEFT JOIN OLWHRM1.PD03_PRS_ADR_PHN PD03
				ON PD01.DF_PRS_ID = PD03.DF_PRS_ID
		WHERE
			AY01.PF_ACT = 'MXADD'
			AND AY01.BX_CMT LIKE ('%ACCEPT DEMOS FROM DUDE%')
			AND AY01.BD_ATY_PRF = TODAY() - 1
		ORDER BY
			PD01.DF_SPE_ACC_ID
	;
QUIT;
ENDRSUBMIT;

DATA DEMO; SET DUSTER.DEMO; RUN;

PROC EXPORT
		DATA=DEMO
		OUTFILE='T:\SAS\OneLINK Source For MD PDEM-Auto Demo.xlsx'
		REPLACE;
RUN;
