USE UDW;
GO

SELECT
	 RM10.LF_RMT_BCH_USR_INI
	,RM10.LD_RMT_BCH_INI
	,RM10.LC_RMT_BCH_SRC_IPT
	,RM10.LN_RMT_BCH_SEQ
	,CONVERT(DATE,'20180101') AS BEGIN_SEARCH
FROM
	RM10_RMT_BCH RM10
WHERE
	RM10.LF_RMT_BCH_USR_INI IN ('UT00111','UT02025')
	AND RM10.LD_RMT_BCH_INI >= CONVERT(DATE,'20180101')
;

SELECT
	 RM10.LF_RMT_BCH_USR_INI
	,MAX(RM10.LD_RMT_BCH_INI) AS max_LD_RMT_BCH_INI
FROM
	RM10_RMT_BCH RM10
WHERE
	RM10.LF_RMT_BCH_USR_INI = 'UT00111'
GROUP BY
	RM10.LF_RMT_BCH_USR_INI
;

SELECT
	 RM10.LF_RMT_BCH_USR_INI
	,MAX(RM10.LD_RMT_BCH_INI) AS max_LD_RMT_BCH_INI
FROM
	RM10_RMT_BCH RM10
WHERE
	RM10.LF_RMT_BCH_USR_INI = 'UT02025'
GROUP BY
	RM10.LF_RMT_BCH_USR_INI
;

SELECT * FROM OPENQUERY (DUSTER,'
SELECT
	 RM10.LF_RMT_BCH_USR_INI
	,MAX(RM10.LD_RMT_BCH_INI) AS max_LD_RMT_BCH_INI
FROM
	OLWHRM1.RM10_RMT_BCH RM10
WHERE
	RM10.LF_RMT_BCH_USR_INI = ''UT00111''
GROUP BY
	RM10.LF_RMT_BCH_USR_INI
')
;

SELECT * FROM OPENQUERY (DUSTER,'
SELECT
	 RM10.LF_RMT_BCH_USR_INI
	,MAX(RM10.LD_RMT_BCH_INI) AS max_LD_RMT_BCH_INI
FROM
	OLWHRM1.RM10_RMT_BCH RM10
WHERE
	RM10.LF_RMT_BCH_USR_INI = ''UT02025''
GROUP BY
	RM10.LF_RMT_BCH_USR_INI
')
;