%LET BANA = %STR(REQUIRED="FILEDSN=X:\PADR\ODBC\EA27_BANA.dsn; update_lock_typ=nolock; bl_keepnulls=no");
LIBNAME BANA ODBC &BANA ;

PROC SQL;
	CREATE TABLE POP AS 
		SELECT
			*
		FROM
			BANA._03PaymentDataRecord  P
			INNER JOIN BANA.COMPASSLOANMAPPING MAP
				ON P.BORROWERSSN = MAP.BORROWERSSN
				AND P.LOAN_NUMBER = MAP.LOAN_NUMBER
		WHERE
			RepaymentPlanCode IN ('D7', 'I1', 'I3', 'I4', 'Z1')
;
QUIT;

PROC SQL;
	CREATE TABLE SOURCE AS
		SELECT DISTINCT
			BORROWERSSN,
			LN_SEQ
		FROM
			POP
;
QUIT;


/*TEST*/
/*LIBNAME  DUSTER  REMOTE  SERVER=QADBD004 SLIBREF=WORK  ;*/

/*LIVE*/
LIBNAME  DUSTER  REMOTE  SERVER=DUSTER  SLIBREF=WORK;

DATA DUSTER.SOURCE; *Send data to Duster;
SET SOURCE;
RUN;

RSUBMIT;  

/*%let DB = DLGSWQUT;  *This is test;*/
%let DB = DLGSUTWH;  *This is live;

LIBNAME OLWHRM1 DB2 DATABASE=&DB OWNER=OLWHRM1;
PROC SQL;
	CREATE TABLE LN09 AS
		SELECT	
			REMOTE.*
		FROM
			 SOURCE S
		INNER JOIN OLWHRM1.LN09_RPD_PIO_CVN REMOTE
			ON S.BORROWERSSN = REMOTE.BF_SSN
			AND S.LN_SEQ = REMOTE.LN_SEQ
			
;
	CREATE TABLE LN65 AS
		SELECT	
			REMOTE.*
		FROM
			 SOURCE S
		INNER JOIN OLWHRM1.LN65_LON_RPS REMOTE
			ON S.BORROWERSSN = REMOTE.BF_SSN
			AND S.LN_SEQ = REMOTE.LN_SEQ
			
;
	CREATE TABLE LN66 AS
		SELECT	
			REMOTE.*
		FROM
			 SOURCE S
		INNER JOIN OLWHRM1.LN66_LON_RPS_SPF REMOTE
			ON S.BORROWERSSN = REMOTE.BF_SSN
			AND S.LN_SEQ = REMOTE.LN_SEQ
			
;
	CREATE TABLE RS05 AS
		SELECT	
			REMOTE.*
		FROM
			 SOURCE S
		INNER JOIN OLWHRM1.RS05_IBR_RPS REMOTE
			ON S.BORROWERSSN = REMOTE.BF_SSN
			
;
	CREATE TABLE RS10 AS
		SELECT	
			REMOTE.*
		FROM
			 SOURCE S
		INNER JOIN OLWHRM1.RS10_BR_RPD REMOTE
			ON S.BORROWERSSN = REMOTE.BF_SSN
;

QUIT;
ENDRSUBMIT;

DATA LN09; SET DUSTER.LN09; RUN;
DATA LN65; SET DUSTER.LN65; RUN;
DATA LN66; SET DUSTER.LN66; RUN;
DATA RS05; SET DUSTER.RS05; RUN;
DATA RS10; SET DUSTER.RS10; RUN;

PROC EXPORT DATA = WORK.POP 
            OUTFILE = "T:\NH 25604.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="03 RECORD"; 
RUN;

PROC EXPORT DATA = WORK.LN09 
            OUTFILE = "T:\NH 25604.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="LN09"; 
RUN;

PROC EXPORT DATA = WORK.LN65 
            OUTFILE = "T:\NH 25604.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="LN65"; 
RUN;

PROC EXPORT DATA = WORK.LN66 
            OUTFILE = "T:\NH 25604.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="LN66"; 
RUN;

PROC EXPORT DATA = WORK.RS05 
            OUTFILE = "T:\NH 25604.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="RS05"; 
RUN;

PROC EXPORT DATA = WORK.RS10 
            OUTFILE = "T:\NH 25604.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="RS10"; 
RUN;
