%LET RPTLIB = T:\SAS;
LIBNAME XL 'T:\52715 List.xlsx';
DATA WORK.XLSOURCE;
	SET XL.'Sheet1$'N;
	IF SSN ^= '';
RUN;
LIBNAME XL CLEAR;

LIBNAME  DUSTER  REMOTE  SERVER=DUSTER  SLIBREF=WORK;
DATA DUSTER.XLSOURCE;
	SET XLSOURCE;
RUN;

RSUBMIT;
%LET DB = DLGSUTWH;
LIBNAME OLWHRM1 DB2 DATABASE=&DB OWNER=OLWHRM1;

PROC SQL;
	CREATE TABLE LoanDetail AS
		SELECT DISTINCT
			XLS.SSN
			,LN10.LN_SEQ
			,LN10.IC_LON_PGM
		FROM
			WORK.XLSOURCE XLS
			INNER JOIN OLWHRM1.LN10_LON LN10
				ON XLS.SSN = LN10.BF_SSN
		WHERE
			LN10.LA_CUR_PRI > 0
	;
QUIT;
ENDRSUBMIT;

DATA LoanDetail;
	SET DUSTER.LoanDetail;
RUN;

PROC EXPORT
	DATA=LoanDetail
	OUTFILE="&RPTLIB\UNH 52715.xlsx"
	DBMS = EXCEL
	REPLACE;	
RUN;
