SELECT DISTINCT
	*
FROM
	OPENQUERY
	(
		DUSTER,
		'
			SELECT DISTINCT
				BR04.DF_PRS_ID_BR,
				DC19.*
			FROM
				OLWHRM1.DC19_DOE_RIN DC19
				INNER JOIN OLWHRM1.BR04_BR_REF_APL BR04 ON BR04.AF_APL_ID = DC19.AF_APL_ID
		'
	) D
	INNER JOIN tempdb.dbo.SSN S ON S.F1 = D.DF_PRS_ID_BR