LIBNAME DUSTER REMOTE SERVER=DUSTER SLIBREF=WORK;
RSUBMIT;
LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
PROC SQL;
	CREATE TABLE DF10 AS
		SELECT DISTINCT
			DF10.BF_SSN,
			DF10.LC_DFR_TYP,
			DF10.LD_DFR_REQ_BEG,
			DF10.LD_DFR_REQ_END,
			DF10.LF_USR_CRT_REQ_DFR,
			DF10.LD_CRT_REQ_DFR
		FROM
			OLWHRM1.DF10_BR_DFR_REQ DF10
		WHERE
			DF10.LD_CRT_REQ_DFR BETWEEN '12MAR2015'D AND '16MAR2015'D
	;
QUIT;
ENDRSUBMIT;

DATA DF10; SET DUSTER.DF10; RUN;

PROC EXPORT
		DATA=DF10
		OUTFILE='T:\DF10 Query.XLSX'
		REPLACE;
RUN;
