USE UDW
GO


MERGE 
	dbo.DT01_LN41_LON_CRB LOCAL
USING
	(
		SELECT
			*
		FROM
			OPENQUERY
			(
				QADBD004,
				'
					SELECT
						REMOTE.*
					FROM
						OLWHRM1.DT01_LN41_LON_CRB REMOTE
				'
			) 
	) R ON R.BF_SSN = LOCAL.BF_SSN AND R.LN_SEQ = LOCAL.LN_SEQ AND LOCAL.LD_RPT_CRB = R.LD_RPT_CRB AND LOCAL.LN_LON_CRB_RPT_DTA = R.LN_LON_CRB_RPT_DTA
	WHEN MATCHED THEN 
		UPDATE SET 			LOCAL.LN_LON_CRB_RPT_DTA = R.LN_LON_CRB_RPT_DTA,			LOCAL.LF_CRT_DTS_DT01 = R.LF_CRT_DTS_DT01,			LOCAL.LF_CRT_USR_DT01 = R.LF_CRT_USR_DT01,			LOCAL.LC_SPC_CMT = R.LC_SPC_CMT,			LOCAL.LC_SPC_CMT_UPD_TYP = R.LC_SPC_CMT_UPD_TYP,			LOCAL.LC_CRB_CSM_INF = R.LC_CRB_CSM_INF,			LOCAL.LC_CSM_INF_UPD_TYP = R.LC_CSM_INF_UPD_TYP,			LOCAL.LC_CRB_ECOA = R.LC_CRB_ECOA,			LOCAL.LC_ECOA_UPD_TYP = R.LC_ECOA_UPD_TYP,			LOCAL.LC_RPT_STA_CRB = R.LC_RPT_STA_CRB,			LOCAL.LC_STA_CRB_UPD_TYP = R.LC_STA_CRB_UPD_TYP,			LOCAL.LD_ACC_INF = R.LD_ACC_INF,			LOCAL.LC_ACC_INF_UPD_TYP = R.LC_ACC_INF_UPD_TYP,			LOCAL.LC_PRV_MTH_PAY_HST = R.LC_PRV_MTH_PAY_HST,			LOCAL.LC_PRV_PAY_UPD_TYP = R.LC_PRV_PAY_UPD_TYP,			LOCAL.LI_LON_CRB_FNL_STA = R.LI_LON_CRB_FNL_STA,			LOCAL.LC_FNL_STA_UPD_TYP = R.LC_FNL_STA_UPD_TYP,			LOCAL.LC_CLC_PRV_RPT_DIF = R.LC_CLC_PRV_RPT_DIF
			WHEN NOT MATCHED THEN
		INSERT 
		(
			BF_SSN,			LN_SEQ,			LD_RPT_CRB,			LN_LON_CRB_RPT_DTA,			LF_CRT_DTS_DT01,			LF_CRT_USR_DT01,			LC_SPC_CMT,			LC_SPC_CMT_UPD_TYP,			LC_CRB_CSM_INF,			LC_CSM_INF_UPD_TYP,			LC_CRB_ECOA,			LC_ECOA_UPD_TYP,			LC_RPT_STA_CRB,			LC_STA_CRB_UPD_TYP,			LD_ACC_INF,			LC_ACC_INF_UPD_TYP,			LC_PRV_MTH_PAY_HST,			LC_PRV_PAY_UPD_TYP,			LI_LON_CRB_FNL_STA,			LC_FNL_STA_UPD_TYP,			LC_CLC_PRV_RPT_DIF
		)
		VALUES 
		(
			R.BF_SSN,			R.LN_SEQ,			R.LD_RPT_CRB,			R.LN_LON_CRB_RPT_DTA,			R.LF_CRT_DTS_DT01,			R.LF_CRT_USR_DT01,			R.LC_SPC_CMT,			R.LC_SPC_CMT_UPD_TYP,			R.LC_CRB_CSM_INF,			R.LC_CSM_INF_UPD_TYP,			R.LC_CRB_ECOA,			R.LC_ECOA_UPD_TYP,			R.LC_RPT_STA_CRB,			R.LC_STA_CRB_UPD_TYP,			R.LD_ACC_INF,			R.LC_ACC_INF_UPD_TYP,			R.LC_PRV_MTH_PAY_HST,			R.LC_PRV_PAY_UPD_TYP,			R.LI_LON_CRB_FNL_STA,			R.LC_FNL_STA_UPD_TYP,			R.LC_CLC_PRV_RPT_DIF
		)
	WHEN NOT MATCHED BY SOURCE THEN
		DELETE;
GO


MERGE 
		dbo.DT02_LN63_CRB_ECK LOCAL
USING
	(
		SELECT
			*
		FROM
			OPENQUERY
			(
				QADBD004,
				'
					SELECT
						REMOTE.*
					FROM
						OLWHRM1.DT02_LN63_CRB_ECK REMOTE
				'
			) 
	) R ON R.BF_SSN = LOCAL.BF_SSN AND R.LN_SEQ = LOCAL.LN_SEQ
	WHEN MATCHED THEN 
		UPDATE SET 
	LOCAL.LD_RPT_CRB = R.LD_RPT_CRB,	LOCAL.LN_CRB_ECK_SEQ = R.LN_CRB_ECK_SEQ,	LOCAL.LN_CRB_ECK_CHG = R.LN_CRB_ECK_CHG,	LOCAL.LF_CRT_DTS_DT02 = R.LF_CRT_DTS_DT02,	LOCAL.LF_CRT_USR_DT02 = R.LF_CRT_USR_DT02,	LOCAL.LC_CRB_ECK_ECOA = R.LC_CRB_ECK_ECOA,	LOCAL.LC_ECOA_UPD_TYP = R.LC_ECOA_UPD_TYP,	LOCAL.LC_ECK_CSM_INF_IND = R.LC_ECK_CSM_INF_IND,	LOCAL.LC_CSM_IND_UPD_TYP = R.LC_CSM_IND_UPD_TYP,	LOCAL.LC_ECK_ADR_SGM_TYP = R.LC_ECK_ADR_SGM_TYP
	WHEN NOT MATCHED THEN
	INSERT 
	(
		BF_SSN,		LN_SEQ,		LD_RPT_CRB,		LN_CRB_ECK_SEQ,		LN_CRB_ECK_CHG,		LF_CRT_DTS_DT02,		LF_CRT_USR_DT02,		LC_CRB_ECK_ECOA,		LC_ECOA_UPD_TYP,		LC_ECK_CSM_INF_IND,		LC_CSM_IND_UPD_TYP,		LC_ECK_ADR_SGM_TYP
	)
	VALUES 
	(
		R.BF_SSN,		R.LN_SEQ,		R.LD_RPT_CRB,		R.LN_CRB_ECK_SEQ,		R.LN_CRB_ECK_CHG,		R.LF_CRT_DTS_DT02,		R.LF_CRT_USR_DT02,		R.LC_CRB_ECK_ECOA,		R.LC_ECOA_UPD_TYP,		R.LC_ECK_CSM_INF_IND,		R.LC_CSM_IND_UPD_TYP,		R.LC_ECK_ADR_SGM_TYP
		)
	WHEN NOT MATCHED BY SOURCE THEN
		DELETE
;
	
GO

MERGE 
	dbo.AYCD_CRB_LON_MDA LOCAL
USING
	(
		SELECT
			*
		FROM
			OPENQUERY
			(
				QADBD004,
				'
					SELECT
						REMOTE.*
					FROM
						OLWHRM1.AYCD_CRB_LON_MDA REMOTE
				'
			) 
	) R ON R.BF_SSN = LOCAL.BF_SSN AND R.LN_SEQ = LOCAL.LN_SEQ
	WHEN MATCHED THEN 
	UPDATE SET 
		LOCAL.LF_CRT_DTS_AYCD = R.LF_CRT_DTS_AYCD,		LOCAL.LF_CRT_USR_AYCD = R.LF_CRT_USR_AYCD,		LOCAL.LF_LST_DTS_AYCD = R.LF_LST_DTS_AYCD,		LOCAL.LF_LST_USR_AYCD = R.LF_LST_USR_AYCD,		LOCAL.LN_DFL_SEQ = R.LN_DFL_SEQ,		LOCAL.LD_1_SYS_DLQ_CVN = R.LD_1_SYS_DLQ_CVN,		LOCAL.LD_1_DLQ_CLC_SYS = R.LD_1_DLQ_CLC_SYS,		LOCAL.LD_ACC_OPN = R.LD_ACC_OPN,		LOCAL.LC_LON_HAS_PAY_DU = R.LC_LON_HAS_PAY_DU,		LOCAL.LN_SPC_TRM_DUR = R.LN_SPC_TRM_DUR,		LOCAL.LN_QA_RPT_SEQ = R.LN_QA_RPT_SEQ,		LOCAL.LC_TDL_PRG_REA = R.LC_TDL_PRG_REA
WHEN NOT MATCHED THEN
	INSERT 
	(
		BF_SSN,		LN_SEQ,		LF_CRT_DTS_AYCD,		LF_CRT_USR_AYCD,		LF_LST_DTS_AYCD,		LF_LST_USR_AYCD,		LN_DFL_SEQ,		LD_1_SYS_DLQ_CVN,		LD_1_DLQ_CLC_SYS,		LD_ACC_OPN,		LC_LON_HAS_PAY_DU,		LN_SPC_TRM_DUR,		LN_QA_RPT_SEQ,		LC_TDL_PRG_REA
	)
	VALUES 
	(
		R.BF_SSN,		R.LN_SEQ,		R.LF_CRT_DTS_AYCD,		R.LF_CRT_USR_AYCD,		R.LF_LST_DTS_AYCD,		R.LF_LST_USR_AYCD,		R.LN_DFL_SEQ,		R.LD_1_SYS_DLQ_CVN,		R.LD_1_DLQ_CLC_SYS,		R.LD_ACC_OPN,		R.LC_LON_HAS_PAY_DU,		R.LN_SPC_TRM_DUR,		R.LN_QA_RPT_SEQ,		R.LC_TDL_PRG_REA
	)
	WHEN NOT MATCHED BY SOURCE THEN
		DELETE
	;