USE UDW
GO


SELECT * FROM OPENQUERY(DUSTER,
'
	SELECT DISTINCT
		(
			SUM((LA_CLM_PRI + LA_CLM_INT- LA_PRI_COL + LA_INT_ACR + LA_CLM_INT_ACR - LA_INT_COL)) 
			+ 
			SUM(LA_LEG_CST_ACR - LA_LEG_CST_COL + LA_OTH_CHR_ACR - LA_OTH_CHR_COL + LA_COL_CST_ACR - LA_COL_CST_COL + LA_CLM_PRJ_COL_CST) 
		) as bal,     
		count(distinct dc01.af_apl_id)
	FROM 
		OLWHRM1.PD03_PRS_ADR_PHN PD03
		INNER JOIN OLWHRM1.DC01_LON_CLM_INF DC01
			ON DC01.BF_SSN = PD03.DF_PRS_ID
		INNER JOIN OLWHRM1.DC02_BAL_INT DC02
			ON DC02.BF_SSN = DC01.BF_SSN
	WHERE
		DC_DOM_ST = ''CA'' 
		AND DF_LST_DTS_PD03 < ''05/01/2018''
		AND DC01.LA_CLM_PRI > 0
		AND DC01.LC_STA_DC10 = ''03''
		AND DI_VLD_ADR = ''Y''

')


SELECT * FROM OPENQUERY(DUSTER,
'
	SELECT DISTINCT
	
	sum(	DC01.LA_CLM_PRI +
		DC01.LA_CLM_INT -
		DC01.LA_PRI_COL +
		DC01.LA_INT_ACR +
		COALESCE(DC02.LA_CLM_INT_ACR,0) -
		DC01.LA_INT_COL + 
		DC01.LA_LEG_CST_ACR -
		DC01.LA_LEG_CST_COL + 
		DC01.LA_OTH_CHR_ACR -
		DC01.LA_OTH_CHR_COL +
		DC01.LA_COL_CST_ACR -
		DC01.LA_COL_CST_COL +
		COALESCE(DC02.LA_CLM_PRJ_COL_CST,0))
	FROM 
		OLWHRM1.PD03_PRS_ADR_PHN PD03
		INNER JOIN OLWHRM1.DC01_LON_CLM_INF DC01
			ON DC01.BF_SSN = PD03.DF_PRS_ID
		INNER JOIN OLWHRM1.DC02_BAL_INT DC02
			ON DC02.BF_SSN = DC01.BF_SSN
	WHERE
		DC_DOM_ST = ''CA'' 
		AND DF_LST_DTS_PD03 < ''05/01/2018''
		AND DC01.LA_CLM_PRI > 0
		AND DC01.LC_STA_DC10 = ''03''
		AND DI_VLD_ADR = ''Y''

')