SELECT * FROM OPENQUERY (DUSTER,'
	SELECT DISTINCT
		PD10.DM_PRS_1			AS First_Name
		,PD10.DM_PRS_LST		AS Last_Name
		,LN10.BF_SSN			AS SSN
		,LN10.LN_SEQ
		,LN10.IC_LON_PGM		AS Loan_Type
		,LN10.LD_LON_1_DSB		AS First_Disburement_Date
		,LN10.LA_LON_AMT_GTR	AS Amount_Guaranteed
	FROM
		OLWHRM1.LN10_LON LN10
		INNER JOIN OLWHRM1.PD10_PRS_NME PD10
			ON LN10.BF_SSN = PD10.DF_PRS_ID
	WHERE
		IF_GTR = ''000740''
	ORDER BY
		PD10.DM_PRS_LST
		,PD10.DM_PRS_1			
		,LN10.BF_SSN			
		,LN10.LN_SEQ
		,LN10.IC_LON_PGM		
		,LN10.LD_LON_1_DSB		
		,LN10.LA_LON_AMT_GTR	

');

