PROC IMPORT OUT = WORK.SOURCE
            DATAFILE = "C:\SERF_File\2011_Indenture_2014.6.xlsx"
			REPLACE;
            SHEET = 'Sheet1$'n; 
RUN;

LIBNAME  DUSTER  REMOTE  SERVER=DUSTER SLIBREF=WORK;
DATA DUSTER.SOURCE; *Send data to Duster;
SET SOURCE;
RUN;

RSUBMIT DUSTER;
LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;

PROC SQL;
	CREATE TABLE IBR_LOANS AS
		SELECT DISTINCT 
			LN65.BF_SSN,
			LN65.LN_SEQ
		FROM
			SOURCE S
			
			INNER JOIN OLWHRM1.LN65_LON_RPS LN65	
				ON S.SSN = LN65.BF_SSN
				AND INPUT(S.LN_SEQ,BEST12.) = LN65.LN_SEQ
				AND LN65.LC_STA_LON65 = 'A'
		WHERE
			LN65.LC_TYP_SCH_DIS IN ('IB','IL')
			AND LD_CRT_LON65 < INPUT('07/01/2014', MMDDYY10.)
;
QUIT;
ENDRSUBMIT;

DATA IBR_LOANS; SET DUSTER.IBR_LOANS; RUN;

PROC SQL;
	CREATE TABLE BORROWERS AS
		SELECT DISTINCT
			BF_SSN 
		FROM
			IBR_LOANS 
			
;
PROC SQL;
	CREATE TABLE BORROWER_COUNT AS 
		SELECT 
			COUNT(BF_SSN) AS BORROWER_COUNT
		FROM
			BORROWERS
;
PROC SQL;
	CREATE TABLE LOAN_COUNT AS 	
		SELECT
			COUNT(LN_SEQ) AS LOAN_COUNT
		FROM
			IBR_LOANS
;
QUIT;
