SELECT
	LTRIM(RTRIM(PD10.DM_PRS_1)) + ' ' + LTRIM(RTRIM(PD10.DM_PRS_LST)) AS [NAME],
	PD10.DF_SPE_ACC_ID AS ACCOUNT_NUMBER,
	CONVERT(VARCHAR, WF_CRT_DTS_WQ21, 101) AS PROCESS_DATE,
	WF_USR_ASN_TSK AS PROCESSING_UT_AGENT
FROM
	UDW..WQ21_TSK_QUE_HST wq21
	INNER JOIN UDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = WQ21.BF_SSN
WHERE
	WF_QUE = '2B'
	AND WC_STA_WQUE20 IN ('C','X')
	AND WF_CRT_DTS_WQ21 > '03/01/2020'