LIBNAME DUSTER REMOTE SERVER=DUSTER SLIBREF=WORK;
RSUBMIT;
LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
PROC SQL;
	CREATE TABLE LN65 AS
		SELECT
			LN65.*
		FROM
			OLWHRM1.LN10_LON LN10
			JOIN OLWHRM1.LN65_LON_RPS LN65
				ON LN10.BF_SSN = LN65.BF_SSN
				AND LN10.LN_SEQ = LN65.LN_SEQ
			LEFT JOIN
				(
					SELECT
						RS20.BF_SSN,
						RS20.LN_SEQ
					FROM
						OLWHRM1.RS05_IBR_RPS RS05
						JOIN OLWHRM1.RS10_BR_RPD RS10	
							ON RS05.BF_SSN = RS10.BF_SSN
							AND RS05.BD_CRT_RS05 = RS10.BD_CRT_RS05
							AND RS05.BN_IBR_SEQ = RS10.BN_IBR_SEQ
						JOIN OLWHRM1.RS20_IBR_IRL_LON RS20
							ON RS05.BF_SSN = RS20.BF_SSN
							AND RS05.BD_CRT_RS05 = RS20.BD_CRT_RS05
							AND RS05.BN_IBR_SEQ = RS20.BN_IBR_SEQ
				) RS00
				ON LN10.BF_SSN = RS00.BF_SSN
				AND LN10.LN_SEQ = RS00.LN_SEQ
		WHERE
			LN10.LD_LON_ACL_ADD = '29MAY2014'D
			AND LN65.LC_TYP_SCH_DIS IN ('IB','IL')
			AND RS00.BF_SSN IS NULL
	;

	CREATE TABLE RS20 AS
		SELECT
			RS20.*
		FROM
			LN65
			JOIN OLWHRM1.RS20_IBR_IRL_LON RS20
				ON LN65.BF_SSN = RS20.BF_SSN
				AND LN65.LN_SEQ = RS20.LN_SEQ
	;

	CREATE TABLE RS10 AS
		SELECT
			RS10.*
		FROM
			LN65
			JOIN OLWHRM1.RS10_BR_RPD RS10
				ON LN65.BF_SSN = RS10.BF_SSN
	;

	CREATE TABLE RS05 AS
		SELECT
			RS05.*
		FROM
			LN65
			JOIN OLWHRM1.RS05_IBR_RPS RS05
				ON LN65.BF_SSN = RS05.BF_SSN
	;
QUIT;
ENDRSUBMIT;

PROC EXPORT
		DATA=DUSTER.LN65
		OUTFILE='T:\UHEAA Align IBR Missing RS Tables.XLSX'
		REPLACE;
RUN;

PROC EXPORT
		DATA=DUSTER.RS20
		OUTFILE='T:\UHEAA Align IBR Missing RS Tables.XLSX'
		REPLACE;
RUN;

PROC EXPORT
		DATA=DUSTER.RS10
		OUTFILE='T:\UHEAA Align IBR Missing RS Tables.XLSX'
		REPLACE;
RUN;

PROC EXPORT
		DATA=DUSTER.RS05
		OUTFILE='T:\UHEAA Align IBR Missing RS Tables.XLSX'
		REPLACE;
RUN;
