--run on UHEAASQLDB
USE ULS
GO

BEGIN TRANSACTION
	DECLARE @ERROR INT = 0
	DECLARE @ROWCOUNT INT = 0
	DECLARE @ExpectedRowCount INT = 179
	
	UPDATE ULS.scra.ScriptProcessing SET TS06Updated = '2018-05-11' WHERE (TS06Indicator = 0 AND TS06Updated IS NULL) --2
	
	SELECT @ROWCOUNT = @@ROWCOUNT, @ERROR = @@ERROR

	UPDATE ULS.scra.ScriptProcessing SET TS0NUpdated = '2018-05-11' WHERE (TS0NIndicator = 0 AND TS0NUpdated IS NULL) --131
	
	SELECT @ROWCOUNT = @ROWCOUNT + @@ROWCOUNT, @ERROR = @ERROR + @@ERROR

	UPDATE ULS.scra.ScriptProcessing SET TXCXUpdated = '2018-05-11' WHERE (TXCXIndicator = 0 AND TXCXUpdated IS NULL) --46

	SELECT @ROWCOUNT = @ROWCOUNT + @@ROWCOUNT, @ERROR = @ERROR + @@ERROR

IF @ROWCOUNT = @ExpectedRowCount AND @ERROR = 0
	BEGIN
		PRINT 'Transaction committed'
		COMMIT TRANSACTION
		--ROLLBACK TRANSACTION
	END
ELSE
	BEGIN
		PRINT 'ROWCOUNT:  ' + CAST(@ROWCOUNT AS VARCHAR(10))
		PRINT 'ERROR:  ' + CAST(@ERROR AS VARCHAR(10))
		PRINT 'Transaction NOT committed'
		ROLLBACK TRANSACTION
	END