RSUBMIT DUSTER;
LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
PROC SQL;
	CREATE TABLE LN10 AS
		SELECT DISTINCT
			LN10.BF_SSN,
			LN10.LN_SEQ,
			LN10.LD_EFF_LBR_RTE,
			LN10.LD_LON_EFF_ADD FORMAT MMDDYY10.
		FROM
			 OLWHRM1.LN10_LON LN10
		WHERE
			LN10.LF_LON_CUR_OWN IN ('826717','830248')
			
;
QUIT;
ENDRSUBMIT;

PROC EXPORT DATA = DUSTER.LN10 
            OUTFILE = "T:\NH 20230 LN10.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="LN10"; 
RUN;
