SELECT
	DR.WF_QUE,
	DR.WF_SUB_QUE,
	DR.WN_CTL_TSK,
	DR.PF_REQ_ACT,
	SZ.WF_QUE,
	SZ.WF_SUB_QUE,
	SZ.WN_CTL_TSK,
	SZ.PF_REQ_ACT
FROM
	UDW..WQ20_TSK_QUE DR
	INNER JOIN UDW..WQ20_TSK_QUE SZ
		ON DR.BF_SSN = SZ.BF_SSN
		AND SZ.WF_QUE = 'SZ'
WHERE
	DR.WF_QUE = 'DR'