SELECT DISTINCT
	WF_QUE,
	WF_SUB_QUE,
	WN_CTL_TSK,
	PF_REQ_ACT
FROM
	UDW..WQ20_TSK_QUE WQ20
	INNER JOIN 
	(
		SELECT	
			BF_SSN,
			SUM(LA_CUR_PRI) AS BAL
		FROM
			UDW..LN10_LON
		GROUP BY
			BF_SSN
	) LN10
		ON LN10.BF_SSN = WQ20.BF_SSN
		AND LN10.BAL <= 0
WHERE 
	WF_QUE = 'HN'
	AND PF_REQ_ACT IN ('MRIDR','PRIDR')