USE UDW
GO

SELECT 
	DF10.BF_SSN,
	RTRIM(PD10.DM_PRS_1) as [FirstName],
	RTRIM(PD10.DM_PRS_LST) AS [LastName],
	LN10.IC_LON_PGM as LoanType,
	LN10.LN_SEQ as LoanNumber,
	LN10.LA_CUR_PRI as CurrentPrincipalBalance,
	LN10.LD_LON_1_DSB AS FirstDisbDate,
	LN15.DSB_AMT AS OriginalPrincipalBalance,
	LN50.LD_DFR_BEG AS DefermentStart,
	LN50.LD_DFR_END AS DefermentEnd,
	LK10.PX_DSC_MDM AS CurrentLoanStatus
--into #pop
FROM 
	UDW..DF10_BR_DFR_REQ DF10
	INNER JOIN UDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = DF10.BF_SSN
	INNER JOIN UDW..LN50_BR_DFR_APV LN50
		ON LN50.BF_SSN = DF10.BF_SSN
		AND LN50.LF_DFR_CTL_NUM = DF10.LF_DFR_CTL_NUM
	INNER JOIN UDW..LN10_LON LN10
		ON LN10.BF_SSN = LN50.BF_SSN
		AND LN10.LN_SEQ = LN50.LN_SEQ
	INNER JOIN UDW..DW01_DW_CLC_CLU DW01
		ON DW01.BF_SSN = LN50.BF_SSN
		AND DW01.LN_SEQ = LN50.LN_SEQ
	INNER JOIN UDW..LK10_LS_CDE_LKP LK10
		ON LK10.PM_ATR = 'WC-DW-LON-STA'
		AND LK10.PX_ATR_VAL = DW01.WC_DW_LON_STA
	INNER JOIN
	(
		SELECT
			LN15.BF_SSN,
			LN15.LN_SEQ,
			SUM(ISNULL(LN15.LA_DSB,0) - ISNULL(LN15.LA_DSB_CAN,0)) AS  DSB_AMT
		FROM
			UDW..LN15_DSB LN15
		GROUP BY
			LN15.BF_SSN,
			LN15.LN_SEQ
	) LN15
		ON LN15.BF_SSN = LN50.BF_SSN
		AND LN15.LN_SEQ = LN50.LN_SEQ
WHERE 
	LC_DFR_TYP = '37'
	AND LC_DFR_SUB_TYP IN ('CT','CP')
	AND LD_CRT_REQ_DFR > '10/01/2018'

