%LET RPTLIB = T:\SAS;
/*LIBNAME  DUSTER  REMOTE  SERVER=DUSTER  SLIBREF=WORK; *live;*/
LIBNAME  DUSTER  REMOTE  SERVER=QADBD004 SLIBREF=WORK ; *test;
RSUBMIT;

/*%LET DB = DLGSUTWH; *live;*/
%LET DB = DLGSWQUT; *test;

PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);
	CREATE TABLE BR30 AS
		SELECT 
			*
		FROM 
			CONNECTION TO DB2 
				(
					SELECT
						PD10.DF_SPE_ACC_ID
						,BR30.*
					FROM
						OLWHRM1.BR30_BR_EFT BR30
						INNER JOIN OLWHRM1.PD10_PRS_NME PD10
							ON BR30.BF_SSN = PD10.DF_PRS_ID
					WHERE
						PD10.DF_SPE_ACC_ID IN (
							'4483537550',
							'5818062942',
							'5418625308'
							)
					FOR READ ONLY WITH UR
				)
	;
	CREATE TABLE LN83 AS
		SELECT 
			*
		FROM 
			CONNECTION TO DB2 
				(
					SELECT
						PD10.DF_SPE_ACC_ID
						,LN83.*
					FROM
						OLWHRM1.LN83_EFT_TO_LON LN83
						INNER JOIN OLWHRM1.PD10_PRS_NME PD10
							ON LN83.BF_SSN = PD10.DF_PRS_ID
					WHERE
						PD10.DF_SPE_ACC_ID IN (
							'4483537550',
							'5818062942',
							'5418625308'
							)
					FOR READ ONLY WITH UR
				)
	;
	DISCONNECT FROM DB2;
QUIT;
ENDRSUBMIT;

PROC EXPORT 
	DATA= DUSTER.BR30
	OUTFILE= "T:\SAS\UNH_28323.xlsx" 
	DBMS=EXCEL REPLACE;
	SHEET="BR30";
RUN;
PROC EXPORT 
	DATA= DUSTER.LN83
	OUTFILE= "T:\SAS\UNH_28323.xlsx" 
	DBMS=EXCEL REPLACE;
	SHEET="LN83";
RUN;
