USE UDW

GO


SELECT DISTINCT
	PD10.DF_SPE_ACC_ID,
	LTRIM(RTRIM(PD10.DM_PRS_LST)) + ', ' + LTRIM(RTRIM(PD10.DM_PRS_1)) AS Name,
	LN33.LD_CU_ENT AS Date_Entered_Cure,
	SUM(LN10.LA_CUR_PRI + DW01.WA_TOT_BRI_OTS) AS Total_Loan_Balance
	
FROM 
	DW01_DW_CLC_CLU DW01
	INNER JOIN LN10_LON LN10
		ON DW01.BF_SSN = LN10.BF_SSN
		AND DW01.LN_SEQ = LN10.LN_SEQ
	INNER JOIN LN33_LON_CU_INF LN33
		ON DW01.BF_SSN = LN33.BF_SSN
		AND DW01.LN_SEQ = LN33.LN_SEQ
	INNER JOIN PD10_PRS_NME PD10
		ON DW01.BF_SSN = PD10.DF_PRS_ID
	INNER JOIN PD30_PRS_ADR PD30
		ON DW01.BF_SSN = PD30.DF_PRS_ID
WHERE
	DW01.WC_DW_LON_STA = '06'
GROUP BY
	PD10.DF_SPE_ACC_ID,
	LTRIM(RTRIM(PD10.DM_PRS_LST)) + ', ' + LTRIM(RTRIM(PD10.DM_PRS_1)),
	LN33.LD_CU_ENT
ORDER BY
	PD10.DF_SPE_ACC_ID