SELECT
	POP.LD_CRT_REQ_FOR AS FORBEARANCE_CREATE_DATE,
	POP.FORBEARANCE_TYPE,
	COUNT(POP.BF_SSN) AS BWR_COUNT
FROM
(
	SELECT DISTINCT
			LN60.BF_SSN,
			FB10.LD_CRT_REQ_FOR,
			LTRIM(RTRIM(LK10.PX_DSC_LNG)) AS FORBEARANCE_TYPE
		FROM
			UDW..FB10_BR_FOR_REQ FB10
			INNER JOIN UDW..LN60_BR_FOR_APV LN60
				ON LN60.BF_SSN = FB10.BF_SSN
				AND LN60.LF_FOR_CTL_NUM = FB10.LF_FOR_CTL_NUM
			INNER JOIN UDW..LN10_LON LN10
				ON LN10.BF_SSN = LN60.BF_SSN
				AND LN10.LN_SEQ = LN60.LN_SEQ
			INNER JOIN CDW..LK10_LS_CDE_LKP LK10
				ON LK10.PM_ATR = 'LC-FOR-TYP'
				AND LK10.PX_ATR_VAL = FB10.LC_FOR_TYP 
		WHERE
			LN60.LC_STA_LON60 = 'A'
			AND FB10.LC_STA_FOR10 = 'A'	
			AND LN10.LC_STA_LON10 = 'R'
			AND LN10.LA_CUR_PRI > 0.00
			AND FB10.LD_CRT_REQ_FOR >= '03/01/2020'
) POP
GROUP BY 
	POP.LD_CRT_REQ_FOR,
	POP.FORBEARANCE_TYPE
ORDER BY 
	LD_CRT_REQ_FOR


SELECT
	POP.LD_CRT_REQ_FOR AS FORBEARANCE_CREATE_DATE,
	POP.FORBEARANCE_TYPE,
	COUNT(POP.BF_SSN) AS BWR_COUNT
FROM
(
	SELECT DISTINCT
			LN60.BF_SSN,
			FB10.LD_CRT_REQ_FOR,
			LTRIM(RTRIM(LK10.PX_DSC_LNG)) AS FORBEARANCE_TYPE
		FROM
			UDW..FB10_BR_FOR_REQ FB10
			INNER JOIN UDW..LN60_BR_FOR_APV LN60
				ON LN60.BF_SSN = FB10.BF_SSN
				AND LN60.LF_FOR_CTL_NUM = FB10.LF_FOR_CTL_NUM
			INNER JOIN UDW..LN10_LON LN10
				ON LN10.BF_SSN = LN60.BF_SSN
				AND LN10.LN_SEQ = LN60.LN_SEQ
			INNER JOIN CDW..LK10_LS_CDE_LKP LK10
				ON LK10.PM_ATR = 'LC-FOR-TYP'
				AND LK10.PX_ATR_VAL = FB10.LC_FOR_TYP 

		WHERE
			LN60.LC_STA_LON60 = 'A'
			AND FB10.LC_STA_FOR10 = 'A'	
			AND LN10.LC_STA_LON10 = 'R'
			AND LN10.LA_CUR_PRI > 0.00
			AND FB10.LD_CRT_REQ_FOR >= '03/01/2020'
			AND LK10.PX_DSC_EX_LNG = 'DISASTER ADMIN - FORBEARANCE'
) POP
GROUP BY 
	POP.LD_CRT_REQ_FOR,
	POP.FORBEARANCE_TYPE
ORDER BY 
	LD_CRT_REQ_FOR



SELECT
	DATEADD(dd, -1, DATEADD(wk, DATEDIFF(wk,0,LD_CRT_REQ_FOR), 0)) AS WEEK_OF,
	POP.FORBEARANCE_TYPE,
	COUNT(POP.BF_SSN) AS BWR_COUNT
FROM
(
	SELECT DISTINCT
			LN60.BF_SSN,
			FB10.LD_CRT_REQ_FOR,
			LTRIM(RTRIM(LK10.PX_DSC_LNG)) AS FORBEARANCE_TYPE
		FROM
			UDW..FB10_BR_FOR_REQ FB10
			INNER JOIN UDW..LN60_BR_FOR_APV LN60
				ON LN60.BF_SSN = FB10.BF_SSN
				AND LN60.LF_FOR_CTL_NUM = FB10.LF_FOR_CTL_NUM
			INNER JOIN UDW..LN10_LON LN10
				ON LN10.BF_SSN = LN60.BF_SSN
				AND LN10.LN_SEQ = LN60.LN_SEQ
			INNER JOIN CDW..LK10_LS_CDE_LKP LK10
				ON LK10.PM_ATR = 'LC-FOR-TYP'
				AND LK10.PX_ATR_VAL = FB10.LC_FOR_TYP 

		WHERE
			LN60.LC_STA_LON60 = 'A'
			AND FB10.LC_STA_FOR10 = 'A'	
			AND LN10.LC_STA_LON10 = 'R'
			AND LN10.LA_CUR_PRI > 0.00
			AND FB10.LD_CRT_REQ_FOR >= '03/01/2020'
) POP
GROUP BY 
	DATEDIFF(wk,0,LD_CRT_REQ_FOR),
	POP.FORBEARANCE_TYPE
ORDER BY 
	DATEDIFF(wk,0,LD_CRT_REQ_FOR)


SELECT
	DATEADD(dd, -1, DATEADD(wk, DATEDIFF(wk,0,LD_CRT_REQ_FOR), 0)) AS WEEK_OF,
	POP.FORBEARANCE_TYPE,
	COUNT(POP.BF_SSN) AS BWR_COUNT
FROM
(
	SELECT DISTINCT
			LN60.BF_SSN,
			FB10.LD_CRT_REQ_FOR,
			LTRIM(RTRIM(LK10.PX_DSC_LNG)) AS FORBEARANCE_TYPE
		FROM
			UDW..FB10_BR_FOR_REQ FB10
			INNER JOIN UDW..LN60_BR_FOR_APV LN60
				ON LN60.BF_SSN = FB10.BF_SSN
				AND LN60.LF_FOR_CTL_NUM = FB10.LF_FOR_CTL_NUM
			INNER JOIN UDW..LN10_LON LN10
				ON LN10.BF_SSN = LN60.BF_SSN
				AND LN10.LN_SEQ = LN60.LN_SEQ
			INNER JOIN CDW..LK10_LS_CDE_LKP LK10
				ON LK10.PM_ATR = 'LC-FOR-TYP'
				AND LK10.PX_ATR_VAL = FB10.LC_FOR_TYP 

		WHERE
			LN60.LC_STA_LON60 = 'A'
			AND FB10.LC_STA_FOR10 = 'A'	
			AND LN10.LC_STA_LON10 = 'R'
			AND LN10.LA_CUR_PRI > 0.00
			AND FB10.LD_CRT_REQ_FOR >= '03/01/2020'
			AND LK10.PX_DSC_EX_LNG = 'DISASTER ADMIN - FORBEARANCE'
) POP
GROUP BY 
	DATEDIFF(wk,0,LD_CRT_REQ_FOR),
	POP.FORBEARANCE_TYPE
ORDER BY 
	DATEDIFF(wk,0,LD_CRT_REQ_FOR)