LIBNAME DUSTER REMOTE SERVER=DUSTER SLIBREF=WORK;
RSUBMIT;
LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
PROC SQL;
	CREATE TABLE U4P5 AS
		SELECT DISTINCT
			WQ20.WD_ACT_REQ AS Task_Creation_Date,
			WQ20.WN_CTL_TSK AS Task_Control_No,
			PD10.DF_SPE_ACC_ID AS Account_No,
			LN10.IF_GTR AS Guarantor_Code,
			DW01.WC_DW_LON_STA AS Current_Status,
			LN16.LN_DLQ_MAX AS Days_Delinquent
		FROM
			OLWHRM1.WQ20_TSK_QUE WQ20
			JOIN OLWHRM1.PD10_PRS_NME PD10
				ON WQ20.BF_SSN = PD10.DF_PRS_ID
			JOIN OLWHRM1.LN10_LON LN10
				ON WQ20.BF_SSN = LN10.BF_SSN
			JOIN OLWHRM1.DW01_DW_CLC_CLU DW01
				ON LN10.BF_SSN = DW01.BF_SSN
				AND LN10.LN_SEQ = DW01.LN_SEQ
			LEFT JOIN OLWHRM1.LN16_LON_DLQ_HST LN16
				ON LN10.BF_SSN = LN16.BF_SSN
				AND LN10.LN_SEQ = LN16.LN_SEQ
				AND LC_STA_LON16 = '1'
		WHERE
			WQ20.WF_QUE = 'U4'
			AND WQ20.WF_SUB_QUE= 'P5'
	;
QUIT;

ENDRSUBMIT;

DATA U4P5; SET DUSTER.U4P5; RUN;

PROC EXPORT
		DATA=U4P5
		OUTFILE='T:\SAS\PreClaim U4 P5 Queue Query.XLSX'
		REPLACE;
RUN;
