--Population 1 includes outstanding loans on which a default claim was paid prior to March 13, 2020, 
--that are not subject to an active bankruptcy filing,and are still in default as of 05/24/2021.

DROP TABLE IF EXISTS #POP130
DROP TABLE IF EXISTS #POP330
DROP TABLE IF EXISTS #POP123
DROP TABLE IF EXISTS #POP323
DROP TABLE IF EXISTS #POP1
DROP TABLE IF EXISTS #POP1_1




DROP TABLE IF EXISTS #POP1
SELECT DISTINCT
	DC01.AF_APL_ID,
	DC01.AF_APL_ID_SFX,
	DC01.LF_CRT_DTS_DC10,
	BF_SSN
INTO #POP1
FROM
	ODW_08302021..DC01_LON_CLM_INF DC01
WHERE
    DC01.LC_STA_DC10 = '03'
    AND DC01.LD_LDR_POF < '03/13/2020'
    AND DC01.LC_PCL_REA IN ('DB','DF','IN')

SELECT
	BF_SSN,
	AF_APL_ID,
	AF_APL_ID_SFX
INTO #POP130
FROM
(
SELECT 
	CASE WHEN DC02.LR_CUR_INT = 0 THEN 1 ELSE 0 END AS CUR0,
	CASE WHEN DC02.LR_CUR_INT != 0 THEN 1 ELSE 0 END AS CUR1,
	DC02.*
FROM 
	#POP1 P
	INNER JOIN 
	(
		SELECT
			DC01.*
		FROM
			ODW_08302021..DC01_LON_CLM_INF DC01
			INNER JOIN 
			(
				SELECT DISTINCT
					DC01.BF_SSN,
					DC01.AF_APL_ID,
					DC01.AF_APL_ID_SFX,
					MAX(DC01.LF_CRT_DTS_DC10) AS MaxDate
				FROM
					ODW_08302021..DC01_LON_CLM_INF DC01
				GROUP BY
					DC01.BF_SSN,
					DC01.AF_APL_ID,
					DC01.AF_APL_ID_SFX
				) DC01M
					ON DC01.AF_APL_ID = DC01M.AF_APL_ID
					AND DC01.AF_APL_ID_SFX = DC01M.AF_APL_ID_SFX
					AND DC01.LF_CRT_DTS_DC10 = DC01M.MaxDate
			WHERE
					DC01.LC_PCL_REA = 'DF'
					AND DC01.LC_STA_DC10 = '03'
					AND DC01.LD_CLM_ASN_DOE IS NULL
					AND ISNULL(DC01.LC_REA_CLM_ASN_DOE,'') = ''
	) DC01
		ON DC01.BF_SSN = P.BF_SSN
		AND DC01.AF_APL_ID = P.AF_APL_ID
		AND DC01.AF_APL_ID_SFX = P.AF_APL_ID_SFX
	INNER JOIN ODW_08302021..DC02_BAL_INT DC02 --STILL CURRENTLY IN DEFAULT
		ON DC02.AF_APL_ID = P.AF_APL_ID
		AND DC02.AF_APL_ID_SFX = P.AF_APL_ID_SFX
		AND DC02.LF_CRT_DTS_DC10 = P.LF_CRT_DTS_DC10
		AND DC02.LA_CLM_BAL > 0.00
) P






SELECT
	DC01.BF_SSN,
	DC01.AF_APL_ID,
	DC01.AF_APL_ID_SFX
into #POP330
FROM
	ODW_08302021..DC01_LON_CLM_INF DC01
	INNER JOIN 
	(
		SELECT DISTINCT
			DC01.BF_SSN,
			DC01.AF_APL_ID,
			DC01.AF_APL_ID_SFX,
			MAX(DC01.LF_CRT_DTS_DC10) AS MaxDate
		FROM
			ODW_08302021..DC01_LON_CLM_INF DC01
		GROUP BY
			DC01.BF_SSN,
			DC01.AF_APL_ID,
			DC01.AF_APL_ID_SFX
		) DC01M
			ON DC01.AF_APL_ID = DC01M.AF_APL_ID
			AND DC01.AF_APL_ID_SFX = DC01M.AF_APL_ID_SFX
			AND DC01.LF_CRT_DTS_DC10 = DC01M.MaxDate
		INNER JOIN 
		(
			 SELECT 
				AF_APL_ID, 
				AF_APL_ID_SFX, 
				SUM(ISNULL(LA_PRI_AT_PST,0.00)) AS PRIN ,
				SUM(ISNULL(LA_INT_ACR_THS_PRD,0.00)) AS INTEREST 
			FROM 
				ODW_08302021..DC11_LON_FAT 
			WHERE 
				LC_TRX_TYP IN ('RH','DC','CP') 
				AND LD_TRX_EFF >= '03/13/2020' 
				AND LC_REV_IND_TYP = ''
			GROUP BY
				AF_APL_ID, 
				AF_APL_ID_SFX
		) PMT
			ON PMT.AF_APL_ID = DC01.AF_APL_ID
			AND PMT.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
WHERE
	DC01.LC_STA_DC10 = '04'

--Population 1 includes outstanding loans on which a default claim was paid prior to March 13, 2020, 
--that are not subject to an active bankruptcy filing,and are still in default as of 05/24/2021.


DROP TABLE IF EXISTS #POP1
SELECT DISTINCT
	DC01.AF_APL_ID,
	DC01.AF_APL_ID_SFX,
	DC01.LF_CRT_DTS_DC10,
	BF_SSN
INTO #POP1_1
FROM
	ODW_08232021..DC01_LON_CLM_INF DC01
WHERE
    DC01.LC_STA_DC10 = '03'
    AND DC01.LD_LDR_POF < '03/13/2020'
    AND DC01.LC_PCL_REA IN ('DB','DF','IN')

SELECT
	BF_SSN,
	AF_APL_ID,
	AF_APL_ID_SFX
INTO #POP123
FROM
(
SELECT 
	CASE WHEN DC02.LR_CUR_INT = 0 THEN 1 ELSE 0 END AS CUR0,
	CASE WHEN DC02.LR_CUR_INT != 0 THEN 1 ELSE 0 END AS CUR1,
	DC02.*
FROM 
	#POP1_1 P
	INNER JOIN 
	(
		SELECT
			DC01.*
		FROM
			ODW_08232021..DC01_LON_CLM_INF DC01
			INNER JOIN 
			(
				SELECT DISTINCT
					DC01.BF_SSN,
					DC01.AF_APL_ID,
					DC01.AF_APL_ID_SFX,
					MAX(DC01.LF_CRT_DTS_DC10) AS MaxDate
				FROM
					ODW_08232021..DC01_LON_CLM_INF DC01
				GROUP BY
					DC01.BF_SSN,
					DC01.AF_APL_ID,
					DC01.AF_APL_ID_SFX
				) DC01M
					ON DC01.AF_APL_ID = DC01M.AF_APL_ID
					AND DC01.AF_APL_ID_SFX = DC01M.AF_APL_ID_SFX
					AND DC01.LF_CRT_DTS_DC10 = DC01M.MaxDate
			WHERE
					DC01.LC_PCL_REA = 'DF'
					AND DC01.LC_STA_DC10 = '03'
					AND DC01.LD_CLM_ASN_DOE IS NULL
					AND ISNULL(DC01.LC_REA_CLM_ASN_DOE,'') = ''
	) DC01
		ON DC01.BF_SSN = P.BF_SSN
		AND DC01.AF_APL_ID = P.AF_APL_ID
		AND DC01.AF_APL_ID_SFX = P.AF_APL_ID_SFX
	INNER JOIN ODW_08232021..DC02_BAL_INT DC02 --STILL CURRENTLY IN DEFAULT
		ON DC02.AF_APL_ID = P.AF_APL_ID
		AND DC02.AF_APL_ID_SFX = P.AF_APL_ID_SFX
		AND DC02.LF_CRT_DTS_DC10 = P.LF_CRT_DTS_DC10
		AND DC02.LA_CLM_BAL > 0.00
) P






SELECT
	DC01.BF_SSN,
	DC01.AF_APL_ID,
	DC01.AF_APL_ID_SFX
into #POP323
FROM
	ODW_08232021..DC01_LON_CLM_INF DC01
	INNER JOIN 
	(
		SELECT DISTINCT
			DC01.BF_SSN,
			DC01.AF_APL_ID,
			DC01.AF_APL_ID_SFX,
			MAX(DC01.LF_CRT_DTS_DC10) AS MaxDate
		FROM
			ODW_08232021..DC01_LON_CLM_INF DC01
		GROUP BY
			DC01.BF_SSN,
			DC01.AF_APL_ID,
			DC01.AF_APL_ID_SFX
		) DC01M
			ON DC01.AF_APL_ID = DC01M.AF_APL_ID
			AND DC01.AF_APL_ID_SFX = DC01M.AF_APL_ID_SFX
			AND DC01.LF_CRT_DTS_DC10 = DC01M.MaxDate
		INNER JOIN 
		(
			 SELECT 
				AF_APL_ID, 
				AF_APL_ID_SFX, 
				SUM(ISNULL(LA_PRI_AT_PST,0.00)) AS PRIN ,
				SUM(ISNULL(LA_INT_ACR_THS_PRD,0.00)) AS INTEREST 
			FROM 
				ODW_08232021..DC11_LON_FAT 
			WHERE 
				LC_TRX_TYP IN ('RH','DC','CP') 
				AND LD_TRX_EFF >= '03/13/2020' 
				AND LC_REV_IND_TYP = ''
			GROUP BY
				AF_APL_ID, 
				AF_APL_ID_SFX
		) PMT
			ON PMT.AF_APL_ID = DC01.AF_APL_ID
			AND PMT.AF_APL_ID_SFX = DC01.AF_APL_ID_SFX
WHERE
	DC01.LC_STA_DC10 = '04'

select '23'
SELECT DISTINCT * FROM #POP123 --10680
SELECT DISTINCT * FROM #POP323 --890
select '30'
SELECT DISTINCT * FROM #POP130 --10678
SELECT DISTINCT * FROM #POP330 --848



SELECT
	*
FROM
	#POP123 O
	LEFT JOIN #POP130 T
		ON T.BF_SSN = O.BF_SSN
		AND T.AF_APL_ID = O.AF_APL_ID
		AND T.AF_APL_ID_SFX = O.AF_APL_ID_SFX
WHERE
	T.BF_SSN IS NULL

SELECT
	*
FROM
	#POP323 O
	LEFT JOIN #POP330 T
		ON T.BF_SSN = O.BF_SSN
		AND T.AF_APL_ID = O.AF_APL_ID
		AND T.AF_APL_ID_SFX = O.AF_APL_ID_SFX
WHERE
	T.BF_SSN IS NULL