USE UDW
GO
DROP TABLE IF EXISTS #MAIN_POP

SELECT
	PD10.DF_SPE_ACC_ID,
	FORB.*
INTO #MAIN_POP
FROM
	UDW..LN35_LON_OWN LN35
	INNER JOIN UDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = LN35.BF_SSN
	INNER JOIN UDW..LN10_LON LN10
		ON LN10.BF_SSN = LN35.BF_SSN
		AND LN10.LN_SEQ = LN10.LN_SEQ
	INNER JOIN
	(	
		SELECT
			FB10.BF_SSN,
			LN60.LN_SEQ,
			LN60.LD_FOR_BEG,
			LN60.LD_FOR_END,
			LN60.LF_LST_DTS_LN60,
			FB10.LF_LST_DTS_FB10
		FROM
			UDW..FB10_BR_FOR_REQ FB10
			INNER JOIN UDW..LN60_BR_FOR_APV LN60
				ON LN60.BF_SSN = FB10.BF_SSN
				AND LN60.LF_FOR_CTL_NUM = FB10.LF_FOR_CTL_NUM
		WHERE
			FB10.LC_FOR_TYP = '40'
			 AND LN60.LD_FOR_BEG BETWEEN '03/01/2020' AND '06/30/2020'
			 AND FB10.LC_FOR_STA = 'A'
			 AND LN60.LC_FOR_RSP  != '003'
	) FORB
		ON FORB.BF_SSN = LN35.BF_SSN
		AND FORB.LN_SEQ = LN35.LN_SEQ
	LEFT JOIN ULS.dasforbuh.ProcessQueue PQ
		ON PQ.AccountNumber = PD10.DF_SPE_ACC_ID
		AND PQ.AddedAt > '03/01/2020'
		AND PQ.DeletedOn IS NULL
WHERE
	LN35.IF_BND_ISS = '93002011'
	AND LN35.LC_STA_LON35 = 'A'
	AND CAST(GETDATE() AS DATE) BETWEEN LN35.LD_OWN_EFF_SR AND ISNULL(LN35.LD_OWN_EFF_END, '01/01/2099')
	AND PQ.AccountNumber IS NULL
DROP TABLE IF EXISTS #FINAL

SELECT DISTINCT
	MP.*,
	CASE WHEN DELQ.LN_DLQ_MAX IS NOT NULL THEN 1 ELSE 0 END AS DELQ,
	CASE WHEN RS.BF_SSN IS NOT NULL THEN 1 ELSE 0 END AS IN_REPAY,
	CASE WHEN FORB.BF_SSN IS NOT NULL THEN 1 ELSE 0 END AS IN_FORB,
	DATENAME(month, MP.LD_FOR_BEG) AS M,
	MONTH(MP.LD_FOR_BEG) AS N
INTO #FINAL
FROM 
	#MAIN_POP MP
	LEFT JOIN
	(
		SELECT	
			LN16.BF_SSN,
			LN16.LN_SEQ,
			MAX(LN_DLQ_MAX) AS LN_DLQ_MAX
		FROM
			UDW..LN16_LON_DLQ_HST LN16
			INNER JOIN UDW..LN10_LON LN10
				ON LN10.BF_SSN = LN16.BF_SSN
				AND LN10.LN_SEQ = LN16.LN_SEQ
				AND LN10.LA_CUR_PRI > 0
		WHERE
			LD_DLQ_OCC > '03/01/2020'
			AND LN_DLQ_MAX >= 30
			AND LC_STA_LON16 = '1'

		GROUP BY
			LN16.BF_SSN,
			LN16.LN_SEQ
	) DELQ
		ON DELQ.BF_SSN = MP.BF_SSN
		AND DELQ.LN_SEQ = MP.LN_SEQ
	LEFT JOIN UDW.CALC.RepaymentSchedules RS
		ON RS.BF_SSN = MP.BF_SSN
		AND RS.LN_SEQ = MP.LN_SEQ
	LEFT JOIN
	(	
		SELECT
			FB10.BF_SSN,
			LN60.LN_SEQ,
			LN60.LD_FOR_BEG,
			LN60.LD_FOR_END,
			LN60.LF_LST_DTS_LN60,
			FB10.LF_LST_DTS_FB10
		FROM
			UDW..FB10_BR_FOR_REQ FB10
			INNER JOIN UDW..LN60_BR_FOR_APV LN60
				ON LN60.BF_SSN = FB10.BF_SSN
				AND LN60.LF_FOR_CTL_NUM = FB10.LF_FOR_CTL_NUM
		WHERE
			GETDATE() BETWEEN LN60.LD_FOR_BEG AND LN60.LD_FOR_END 
			 AND FB10.LC_FOR_STA = 'A'
			 AND LN60.LC_STA_LON60 = 'A'
			 AND FB10.LC_STA_FOR10 = 'A'
			 AND LN60.LC_FOR_RSP  != '003'
	) FORB
		ON FORB.BF_SSN = MP.BF_SSN
		AND FORB.LN_SEQ = MP.LN_SEQ
ORDER BY
	MP.BF_SSN,
	MP.LN_SEQ

SELECT 
	 F.M,
	 F.N,
	 COUNT(DISTINCT DF_SPE_ACC_ID) AS TOTAL_COUNT
FROM 
	#FINAL F
GROUP BY
	F.M,
	F.N
ORDER BY
	F.N

SELECT
	P.M,
	P.N,
	COUNT(DISTINCT P.DF_SPE_ACC_ID) AS TOTAL_COUNT,
	SUM(P.DELQ) AS DELQ,
	SUM(P.IN_REPAY) AS IN_REPAY,
	SUM(P.IN_FORB) AS IN_FORB
FROM
(
SELECT DISTINCT
	F.DF_SPE_ACC_ID,
	F.M,
	F.N,
	MAX(DELQ) AS DELQ,
	MAX(IN_REPAY) AS IN_REPAY,
	MAX(IN_FORB) AS IN_FORB
FROM 
	#FINAL F
	
GROUP BY
	F.DF_SPE_ACC_ID,
	F.M,
	F.N
) P
GROUP BY
	P.M,
	P.N
ORDER BY
	P.N