SELECT
COUNT(DISTINCT P.DF_PRS_ID) AS BORROWER_COUNT,
COUNT(*) AS PHONE_COUNT
FROM
(
SELECT DISTINCT
	PD42.*
FROM 
	UDW..LN10_LON LN10
	INNER JOIN 
	(
		SELECT DISTINCT
			DF_PRS_ID,
			DN_DOM_PHN_ARA,
			DN_DOM_PHN_XCH,
			DN_DOM_PHN_LCL
		FROM
			UDW..PD42_PRS_PHN PD42
		WHERE
			DC_ALW_ADL_PHN IN ('L','P', 'X')
			AND PD42.DI_PHN_VLD = 'Y'
	) PD42
		ON PD42.DF_PRS_ID = LN10.BF_SSN
	INNER JOIN UDW..LN16_LON_DLQ_HST LN16
		ON LN16.BF_SSN = LN10.BF_SSN
		AND LN16.LN_SEQ = LN10.LN_SEQ
		AND LN16.LC_STA_LON16 = '1'
		AND LN16.LN_DLQ_MAX >= 16
	INNER JOIN 
	(
		SELECT DISTINCT
			BF_SSN
		FROM
			UDW..AY10_BR_LON_ATY AY10
		WHERE
			AY10.PF_REQ_ACT = 'DDPHN'
			AND AY10.LC_STA_ACTY10 = 'A'
	) AY10
		ON AY10.BF_SSN = LN10.BF_SSN
		
WHERE
	LN10.LA_CUR_PRI > 0.00
	AND LN10.LC_STA_LON10 = 'R'
) P
