DECLARE @StartDate VARCHAR(10) = '2017-12-31'
DECLARE @EndDate VARCHAR(10) = '2018-12-31'


DECLARE @Query VARCHAR(MAX) ='
SELECT DISTINCT
	CONVERT(VARCHAR,CAST(SUM(LN10.LA_CUR_PRI) AS MONEY),1) AS balance,
	COUNT(LN10.LN_SEQ) AS Loans,
	SUM(CASE WHEN DATEDIFF(DAY,CAST(LN16.LD_DLQ_OCC AS DATE), CASE WHEN CAST(LN16.LD_DLQ_MAX AS DATE) > CAST(''' + @EndDate +''' AS DATE) THEN CAST(''' + @EndDate +''' AS DATE) ELSE CAST(LN16.LD_DLQ_MAX AS DATE) END) > 270 THEN 1 ELSE 0 END) AS DelqGreaterThan270, --GET "AS OF" END DATE OF DELQ
	SUM(CASE WHEN DATEDIFF(DAY,CAST(LN16.LD_DLQ_OCC AS DATE), CASE WHEN CAST(LN16.LD_DLQ_MAX AS DATE) > CAST(''' + @EndDate +''' AS DATE) THEN CAST(''' + @EndDate +''' AS DATE) ELSE CAST(LN16.LD_DLQ_MAX AS DATE) END) BETWEEN 30 AND 270 THEN 1 ELSE 0 END) AS DelqGreaterThan30, --GET "AS OF" END DATE OF DELQ
	SUM(CASE WHEN DATEDIFF(DAY,CAST(LN16.LD_DLQ_OCC AS DATE), CASE WHEN CAST(LN16.LD_DLQ_MAX AS DATE) > CAST(''' + @EndDate +''' AS DATE) THEN CAST(''' + @EndDate +''' AS DATE) ELSE CAST(LN16.LD_DLQ_MAX AS DATE) END) < 30 THEN 1 ELSE 0 END) AS DelqLessThan30, --GET "AS OF" END DATE OF DELQ
	SUM(CASE WHEN LN16.BF_SSN IS NULL THEN 1 ELSE 0 END) AS NonDelq
FROM
(
	SELECT 
		* 
	FROM OPENQUERY(DUSTER,
	''
	SELECT DISTINCT
		PD31.DF_PRS_ID
	FROM 
		OLWHRM1.PD31_PRS_INA PD31
	WHERE
		DF_PRS_ID NOT LIKE ''''P%''''
		AND DC_DOM_ST_HST = ''''WA''''
		AND DI_VLD_ADR_HST = ''''Y''''
		AND 
		(
			CAST(DF_LST_DTS_PD31 AS DATE) BETWEEN CAST(''''' + @StartDate + ''''' AS DATE) AND CAST(''''' + @EndDate + ''''' AS DATE)
			OR CAST(DD_VER_ADR_HST AS DATE) BETWEEN CAST(''''' + @StartDate + ''''' AS DATE) AND CAST(''''' + @EndDate + ''''' AS DATE)
			OR CAST(DD_CRT_PD31 AS DATE) BETWEEN CAST(''''' + @StartDate + ''''' AS DATE) AND CAST(''''' + @EndDate + ''''' AS DATE)
		)
		
	'') OQ

UNION
	
SELECT
	DF_PRS_ID
FROM
	UDW..PD30_PRS_ADR
WHERE
	DF_PRS_ID NOT LIKE ''P%''
	AND DC_DOM_ST = ''WA''
	AND DI_VLD_ADR = ''Y''
	AND 
	(
		CAST(DF_LST_DTS_PD30 AS DATE) BETWEEN CAST(''' + @StartDate + ''' AS DATE) AND CAST(''' + @EndDate + ''' AS DATE)
		OR CAST(DD_VER_ADR AS DATE) BETWEEN CAST(''' + @StartDate + ''' AS DATE) AND CAST(''' + @EndDate + ''' AS DATE)
	)
) OQ
	INNER JOIN AuditUDW..LN10_LON_Dec2018 LN10 --TODO: change this to your max date corresponding table
		ON LN10.BF_SSN = OQ.DF_PRS_ID
	LEFT JOIN UDW..LN16_LON_DLQ_HST LN16
		ON LN16.BF_SSN = LN10.BF_SSN
		AND LN16.LN_SEQ = LN10.LN_SEQ
		AND CAST(LN16.LD_DLQ_OCC AS DATE) <= CAST(''' + @EndDate + ''' AS DATE)
		AND CAST(LN16.LD_DLQ_MAX AS DATE) >= CAST(''' + @StartDate + ''' AS DATE)
WHERE
	LN10.LC_STA_LON10 = ''R''
'
EXEC(@Query)
