LIBNAME DUSTER REMOTE SERVER=DUSTER SLIBREF=WORK;
RSUBMIT;
LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
PROC SQL;
	CREATE TABLE HISTCOMAKER AS
		SELECT
			LN20.BF_SSN,
			LN20.LN_SEQ,
			LN20.LF_EDS
		FROM
			OLWHRM1.LN10_LON LN10
			JOIN OLWHRM1.LN20_EDS LN20
				ON LN10.BF_SSN = LN20.BF_SSN
				AND LN10.LN_SEQ = LN20.LN_SEQ
				AND LN10.LA_CUR_PRI > 0
				AND LN10.LC_STA_LON10 = 'R'
		WHERE
			LN20.LC_EDS_TYP = 'M'
			AND LN20.LC_REL_TO_BR = '06'
			AND LN20.LC_REA_EDS_HST ^= ''
	;
QUIT;
ENDRSUBMIT;
DATA HISTCOMAKER; SET DUSTER.HISTCOMAKER; RUN;

PROC EXPORT
		DATA=HISTCOMAKER
		OUTFILE='T:\Borrowers with Co-Maker is Historied.xlsx'
		REPLACE;
RUN;

