USE UDW;
GO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
GO

SELECT DISTINCT 
	PD10.DF_SPE_ACC_ID,
	LN10.LN_SEQ,
	LN10.IF_GTR,
	CONVERT(DATE,LN16.LD_DLQ_OCC) AS LD_DLQ_OCC,
	LN16.LN_DLQ_MAX,
	LN40.LN_SEQ_CLM_PCL,
	LN40.LD_SBM_CLM_PCL,
	LN40.LD_CAN_CLM_PCL,
	LN40.LC_REA_CAN_CLM_PCL,
	AY10_DPH.PF_REQ_ACT,
	CL10.LC_GTR_CLM_ACK,
	LTRIM(RTRIM(CONCAT(COALESCE(AY20_1.LX_ATY,''),' ',COALESCE(AY20_2.LX_ATY,''),' ',COALESCE(AY20_3.LX_ATY,''),' ',COALESCE(AY20_4.LX_ATY,''),' ',COALESCE(AY20_5.LX_ATY,'')))) AS LX_ATY
FROM
	PD10_PRS_NME PD10
	INNER JOIN LN10_LON LN10
		ON LN10.BF_SSN = PD10.DF_PRS_ID
	INNER JOIN /*most recent active delinquency*/
	(
		SELECT
			BF_SSN,
			LN_SEQ,
			MAX(LD_DLQ_OCC) AS LD_DLQ_OCC,
			MAX(LN_DLQ_MAX) AS LN_DLQ_MAX
		FROM
			LN16_LON_DLQ_HST
		WHERE
			LC_STA_LON16 = 1
		GROUP BY
			BF_SSN,
			LN_SEQ
	) LN16
		ON LN16.BF_SSN = LN10.BF_SSN
		AND LN16.LN_SEQ = LN10.LN_SEQ
	INNER JOIN LN40_LON_CLM_PCL LN40
		ON LN40.BF_SSN = LN10.BF_SSN
		AND LN40.LN_SEQ = LN10.LN_SEQ
	INNER JOIN 
	(
		SELECT DISTINCT
			BF_SSN,
			LN_SEQ_CLM_PCL,
			LC_GTR_CLM_ACK,
			LF_USR_ASN_CLM_PCL,
			MAX(LF_LST_DTS_CL10) AS LF_LST_DTS_CL10
		FROM
			CL10_CLM_PCL
		GROUP BY
			BF_SSN,
			LN_SEQ_CLM_PCL,
			LC_GTR_CLM_ACK,
			LF_USR_ASN_CLM_PCL
	) CL10
		ON CL10.BF_SSN = LN40.BF_SSN
		AND CL10.LN_SEQ_CLM_PCL = LN40.LN_SEQ_CLM_PCL
		AND CL10.LC_GTR_CLM_ACK != 'A'	
		AND CL10.LF_USR_ASN_CLM_PCL NOT LIKE ('UT%')
		AND CL10.LF_USR_ASN_CLM_PCL != 'EXPRESS'
	LEFT JOIN 
	(
		SELECT DISTINCT
			AY10_CCP.BF_SSN,
			AY10_CCP.LD_ATY_RSP
		FROM
			AY10_BR_LON_ATY AY10_CCP
		WHERE
			AY10_CCP.PF_REQ_ACT = 'CCP00'
	) AY10_CCP
		ON AY10_CCP.BF_SSN = LN10.BF_SSN
		AND AY10_CCP.LD_ATY_RSP > LN16.LD_DLQ_OCC
	LEFT JOIN 
	(
		SELECT DISTINCT
			AY10_DPH.BF_SSN,
			AY10_DPH.LN_ATY_SEQ,
			AY10_DPH.PF_REQ_ACT,
			AY10_DPH.LD_ATY_RSP
		FROM
			AY10_BR_LON_ATY AY10_DPH
		WHERE
			AY10_DPH.PF_REQ_ACT = 'DPH91'
	) AY10_DPH
		ON AY10_DPH.BF_SSN = LN10.BF_SSN
		AND AY10_DPH.LD_ATY_RSP > LN16.LD_DLQ_OCC
	LEFT JOIN AY20_ATY_TXT AY20_1
		ON AY20_1.BF_SSN = AY10_DPH.BF_SSN
		AND AY20_1.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
		AND AY20_1.LN_ATY_CMT_SEQ = 1
	LEFT JOIN AY20_ATY_TXT AY20_2
		ON AY20_2.BF_SSN = AY10_DPH.BF_SSN
		AND AY20_2.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
		AND AY20_2.LN_ATY_CMT_SEQ = 2
	LEFT JOIN AY20_ATY_TXT AY20_3
		ON AY20_3.BF_SSN = AY10_DPH.BF_SSN
		AND AY20_3.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
		AND AY20_3.LN_ATY_CMT_SEQ = 3
	LEFT JOIN AY20_ATY_TXT AY20_4
		ON AY20_4.BF_SSN = AY10_DPH.BF_SSN
		AND AY20_4.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
		AND AY20_4.LN_ATY_CMT_SEQ = 4
	LEFT JOIN AY20_ATY_TXT AY20_5
		ON AY20_5.BF_SSN = AY10_DPH.BF_SSN
		AND AY20_5.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
		AND AY20_5.LN_ATY_CMT_SEQ = 5
WHERE
	LN10.IC_LON_PGM NOT IN ('TILP','COMPLT')
	AND LN16.LN_DLQ_MAX >= 90
	AND AY10_CCP.BF_SSN IS NULL
	AND LN10.IF_GTR != '000749'
	AND LN10.LA_CUR_PRI > 0
	AND (
			AY10_DPH.BF_SSN IS NULL /*missing dph*/
			OR /*comment exists: exclude specific comment types*/
			(
				LTRIM(RTRIM(CONCAT(COALESCE(AY20_1.LX_ATY,''), ' ', COALESCE(AY20_2.LX_ATY,''), ' ', COALESCE(AY20_3.LX_ATY,''), ' ', COALESCE(AY20_4.LX_ATY,''), ' ', COALESCE(AY20_5.LX_ATY,'')))) != ''
				AND LTRIM(RTRIM(CONCAT(COALESCE(AY20_1.LX_ATY,''), ' ', COALESCE(AY20_2.LX_ATY,''), ' ', COALESCE(AY20_3.LX_ATY,''), ' ', COALESCE(AY20_4.LX_ATY,''), ' ', COALESCE(AY20_5.LX_ATY,'')))) NOT LIKE '%ACTIVE%'
				AND LTRIM(RTRIM(CONCAT(COALESCE(AY20_1.LX_ATY,''), ' ', COALESCE(AY20_2.LX_ATY,''), ' ', COALESCE(AY20_3.LX_ATY,''), ' ', COALESCE(AY20_4.LX_ATY,''), ' ', COALESCE(AY20_5.LX_ATY,'')))) NOT LIKE '%COMPLETE%'
				AND LTRIM(RTRIM(CONCAT(COALESCE(AY20_1.LX_ATY,''), ' ', COALESCE(AY20_2.LX_ATY,''), ' ', COALESCE(AY20_3.LX_ATY,''), ' ', COALESCE(AY20_4.LX_ATY,''), ' ', COALESCE(AY20_5.LX_ATY,'')))) NOT LIKE '%DUP%'
			)
		)
ORDER BY 
	PD10.DF_SPE_ACC_ID,
	LN40.LN_SEQ_CLM_PCL,
	LN10.LN_SEQ
;

/* TESTING ******
--sums to check table consistency/ssn changes
SELECT SUM(CAST(BF_SSN AS numeric)) FROM UDW..CL10_CLM_PCL
SELECT * FROM OPENQUERY(DUSTER,'SELECT SUM(CAST(BF_SSN AS BIGINT)) FROM OLWHRM1.CL10_CLM_PCL')

--check if borrower is in local & remote
SELECT * FROM UDW..CL10_CLM_PCL WHERE BF_SSN = ''
SELECT * FROM OPENQUERY(DUSTER,'SELECT * FROM OLWHRM1.CL10_CLM_PCL WHERE BF_SSN = ''''')




--check borrowers pulled back remote vs local:

USE UDW;
GO

SELECT DISTINCT
	*
FROM
	OPENQUERY
	(DUSTER,
		'
			SELECT DISTINCT 
				PD10.DF_SPE_ACC_ID,
				LN10.LN_SEQ,
				LN10.IF_GTR,
				LN16.LD_DLQ_OCC,
				LN16.LN_DLQ_MAX,
				LN40.LN_SEQ_CLM_PCL,
				LN40.LD_SBM_CLM_PCL,
				LN40.LD_CAN_CLM_PCL,
				LN40.LC_REA_CAN_CLM_PCL,
				AY10_DPH.PF_REQ_ACT,
				CL10.LC_GTR_CLM_ACK,
				TRIM(COALESCE(AY20_1.LX_ATY,'''')||'' ''||COALESCE(AY20_2.LX_ATY,'''')||'' ''||COALESCE(AY20_3.LX_ATY,'''')||'' ''||COALESCE(AY20_4.LX_ATY,'''')||'' ''||COALESCE(AY20_5.LX_ATY,'''')) AS LX_ATY
			FROM
				OLWHRM1.PD10_PRS_NME PD10
				INNER JOIN OLWHRM1.LN10_LON LN10
					ON LN10.BF_SSN = PD10.DF_PRS_ID
				INNER JOIN /*most recent active delinquency*/
					(
						SELECT
							BF_SSN,
							LN_SEQ,
							MAX(LD_DLQ_OCC) AS LD_DLQ_OCC,
							MAX(LN_DLQ_MAX) AS LN_DLQ_MAX
						FROM
							OLWHRM1.LN16_LON_DLQ_HST
						WHERE
							LC_STA_LON16 = 1
						GROUP BY
							BF_SSN,
							LN_SEQ
					) LN16
					ON LN16.BF_SSN = LN10.BF_SSN
					AND LN16.LN_SEQ = LN10.LN_SEQ
				INNER JOIN OLWHRM1.LN40_LON_CLM_PCL LN40
					ON LN40.BF_SSN = LN10.BF_SSN
					AND LN40.LN_SEQ = LN10.LN_SEQ
				INNER JOIN 
					(
						SELECT DISTINCT
							BF_SSN,
							LN_SEQ_CLM_PCL,
							LC_GTR_CLM_ACK,
							LF_USR_ASN_CLM_PCL,
							MAX(LF_LST_DTS_CL10) AS LF_LST_DTS_CL10
						FROM
							OLWHRM1.CL10_CLM_PCL
						GROUP BY
							BF_SSN,
							LN_SEQ_CLM_PCL,
							LC_GTR_CLM_ACK,
							LF_USR_ASN_CLM_PCL
					)CL10
					ON CL10.BF_SSN = LN40.BF_SSN
					AND CL10.LN_SEQ_CLM_PCL = LN40.LN_SEQ_CLM_PCL
					AND CL10.LC_GTR_CLM_ACK != ''A''	
					AND CL10.LF_USR_ASN_CLM_PCL NOT LIKE (''UT%'')
					AND CL10.LF_USR_ASN_CLM_PCL != ''EXPRESS''
				LEFT OUTER JOIN 
					(
						SELECT DISTINCT
							AY10_CCP.BF_SSN,
							AY10_CCP.LD_ATY_RSP
						FROM
							OLWHRM1.AY10_BR_LON_ATY AY10_CCP
						WHERE
							AY10_CCP.PF_REQ_ACT = ''CCP00''
					) AY10_CCP
						ON AY10_CCP.BF_SSN = LN10.BF_SSN
						AND AY10_CCP.LD_ATY_RSP > LN16.LD_DLQ_OCC
				LEFT OUTER JOIN 
					(
						SELECT DISTINCT
							AY10_DPH.BF_SSN,
							AY10_DPH.LN_ATY_SEQ,
							AY10_DPH.PF_REQ_ACT,
							AY10_DPH.LD_ATY_RSP
						FROM
							OLWHRM1.AY10_BR_LON_ATY AY10_DPH
						WHERE
							AY10_DPH.PF_REQ_ACT = ''DPH91''
					) AY10_DPH
					ON AY10_DPH.BF_SSN = LN10.BF_SSN
					AND AY10_DPH.LD_ATY_RSP > LN16.LD_DLQ_OCC
				LEFT OUTER JOIN OLWHRM1.AY20_ATY_TXT AY20_1
					ON AY20_1.BF_SSN = AY10_DPH.BF_SSN
					AND AY20_1.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
					AND AY20_1.LN_ATY_CMT_SEQ = 1
				LEFT OUTER JOIN OLWHRM1.AY20_ATY_TXT AY20_2
					ON AY20_2.BF_SSN = AY10_DPH.BF_SSN
					AND AY20_2.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
					AND AY20_2.LN_ATY_CMT_SEQ = 2
				LEFT OUTER JOIN OLWHRM1.AY20_ATY_TXT AY20_3
					ON AY20_3.BF_SSN = AY10_DPH.BF_SSN
					AND AY20_3.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
					AND AY20_3.LN_ATY_CMT_SEQ = 3
				LEFT OUTER JOIN OLWHRM1.AY20_ATY_TXT AY20_4
					ON AY20_4.BF_SSN = AY10_DPH.BF_SSN
					AND AY20_4.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
					AND AY20_4.LN_ATY_CMT_SEQ = 4
				LEFT OUTER JOIN OLWHRM1.AY20_ATY_TXT AY20_5
					ON AY20_5.BF_SSN = AY10_DPH.BF_SSN
					AND AY20_5.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
					AND AY20_5.LN_ATY_CMT_SEQ = 5
			WHERE
				LN10.IC_LON_PGM NOT IN (''TILP'',''COMPLT'')
				AND LN16.LN_DLQ_MAX >= 90
				AND AY10_CCP.BF_SSN IS NULL
				AND LN10.IF_GTR != ''000749''
				AND LN10.LA_CUR_PRI > 0
				AND 
				(
					AY10_DPH.BF_SSN IS NULL /*missing dph*/
					OR /*comment exists: exclude specific comment types*/
					(
						TRIM(COALESCE(AY20_1.LX_ATY,'''')||'' ''||COALESCE(AY20_2.LX_ATY,'''')||'' ''||COALESCE(AY20_3.LX_ATY,'''')||'' ''||COALESCE(AY20_4.LX_ATY,'''')||'' ''||COALESCE(AY20_5.LX_ATY,'''')) != ''''
						AND TRIM(COALESCE(AY20_1.LX_ATY,'''')||'' ''||COALESCE(AY20_2.LX_ATY,'''')||'' ''||COALESCE(AY20_3.LX_ATY,'''')||'' ''||COALESCE(AY20_4.LX_ATY,'''')||'' ''||COALESCE(AY20_5.LX_ATY,'''')) NOT LIKE ''%ACTIVE%''
						AND TRIM(COALESCE(AY20_1.LX_ATY,'''')||'' ''||COALESCE(AY20_2.LX_ATY,'''')||'' ''||COALESCE(AY20_3.LX_ATY,'''')||'' ''||COALESCE(AY20_4.LX_ATY,'''')||'' ''||COALESCE(AY20_5.LX_ATY,'''')) NOT LIKE ''%COMPLETE%''
						AND TRIM(COALESCE(AY20_1.LX_ATY,'''')||'' ''||COALESCE(AY20_2.LX_ATY,'''')||'' ''||COALESCE(AY20_3.LX_ATY,'''')||'' ''||COALESCE(AY20_4.LX_ATY,'''')||'' ''||COALESCE(AY20_5.LX_ATY,'''')) NOT LIKE ''%DUP%''
					)
				)
			ORDER BY 
				PD10.DF_SPE_ACC_ID,
				LN40.LN_SEQ_CLM_PCL,
				LN10.LN_SEQ
		'
	)


EXCEPT


SELECT DISTINCT 
	PD10.DF_SPE_ACC_ID,
	LN10.LN_SEQ,
	LN10.IF_GTR,
	CONVERT(DATE,LN16.LD_DLQ_OCC) AS LD_DLQ_OCC,
	LN16.LN_DLQ_MAX,
	LN40.LN_SEQ_CLM_PCL,
	LN40.LD_SBM_CLM_PCL,
	LN40.LD_CAN_CLM_PCL,
	LN40.LC_REA_CAN_CLM_PCL,
	AY10_DPH.PF_REQ_ACT,
	CL10.LC_GTR_CLM_ACK,
	LTRIM(RTRIM(CONCAT(COALESCE(AY20_1.LX_ATY,''),' ',COALESCE(AY20_2.LX_ATY,''),' ',COALESCE(AY20_3.LX_ATY,''),' ',COALESCE(AY20_4.LX_ATY,''),' ',COALESCE(AY20_5.LX_ATY,'')))) AS LX_ATY
FROM
	PD10_PRS_NME PD10
	INNER JOIN LN10_LON LN10
		ON LN10.BF_SSN = PD10.DF_PRS_ID
	INNER JOIN /*most recent active delinquency*/
	(
		SELECT
			BF_SSN,
			LN_SEQ,
			MAX(LD_DLQ_OCC) AS LD_DLQ_OCC,
			MAX(LN_DLQ_MAX) AS LN_DLQ_MAX
		FROM
			LN16_LON_DLQ_HST
		WHERE
			LC_STA_LON16 = 1
		GROUP BY
			BF_SSN,
			LN_SEQ
	) LN16
		ON LN16.BF_SSN = LN10.BF_SSN
		AND LN16.LN_SEQ = LN10.LN_SEQ
	INNER JOIN LN40_LON_CLM_PCL LN40
		ON LN40.BF_SSN = LN10.BF_SSN
		AND LN40.LN_SEQ = LN10.LN_SEQ
	INNER JOIN 
	(
		SELECT DISTINCT
			BF_SSN,
			LN_SEQ_CLM_PCL,
			LC_GTR_CLM_ACK,
			LF_USR_ASN_CLM_PCL,
			MAX(LF_LST_DTS_CL10) AS LF_LST_DTS_CL10
		FROM
			CL10_CLM_PCL
		--	WHERE BF_SSN = '555839068'
		GROUP BY
			BF_SSN,
			LN_SEQ_CLM_PCL,
			LC_GTR_CLM_ACK,
			LF_USR_ASN_CLM_PCL
		) CL10
			ON CL10.BF_SSN = LN40.BF_SSN
			AND CL10.LN_SEQ_CLM_PCL = LN40.LN_SEQ_CLM_PCL
			AND CL10.LC_GTR_CLM_ACK != 'A'	
			AND CL10.LF_USR_ASN_CLM_PCL NOT LIKE ('UT%')
			AND CL10.LF_USR_ASN_CLM_PCL != 'EXPRESS'
	LEFT JOIN 
	(
		SELECT DISTINCT
			AY10_CCP.BF_SSN,
			AY10_CCP.LD_ATY_RSP
		FROM
			AY10_BR_LON_ATY AY10_CCP
		WHERE
			AY10_CCP.PF_REQ_ACT = 'CCP00'
	) AY10_CCP
		ON AY10_CCP.BF_SSN = LN10.BF_SSN
		AND AY10_CCP.LD_ATY_RSP > LN16.LD_DLQ_OCC
	LEFT JOIN 
	(
		SELECT DISTINCT
			AY10_DPH.BF_SSN,
			AY10_DPH.LN_ATY_SEQ,
			AY10_DPH.PF_REQ_ACT,
			AY10_DPH.LD_ATY_RSP
		FROM
			AY10_BR_LON_ATY AY10_DPH
		WHERE
			AY10_DPH.PF_REQ_ACT = 'DPH91'
	) AY10_DPH
		ON AY10_DPH.BF_SSN = LN10.BF_SSN
		AND AY10_DPH.LD_ATY_RSP > LN16.LD_DLQ_OCC
	LEFT JOIN AY20_ATY_TXT AY20_1
		ON AY20_1.BF_SSN = AY10_DPH.BF_SSN
		AND AY20_1.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
		AND AY20_1.LN_ATY_CMT_SEQ = 1
	LEFT JOIN AY20_ATY_TXT AY20_2
		ON AY20_2.BF_SSN = AY10_DPH.BF_SSN
		AND AY20_2.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
		AND AY20_2.LN_ATY_CMT_SEQ = 2
	LEFT JOIN AY20_ATY_TXT AY20_3
		ON AY20_3.BF_SSN = AY10_DPH.BF_SSN
		AND AY20_3.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
		AND AY20_3.LN_ATY_CMT_SEQ = 3
	LEFT JOIN AY20_ATY_TXT AY20_4
		ON AY20_4.BF_SSN = AY10_DPH.BF_SSN
		AND AY20_4.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
		AND AY20_4.LN_ATY_CMT_SEQ = 4
	LEFT JOIN AY20_ATY_TXT AY20_5
		ON AY20_5.BF_SSN = AY10_DPH.BF_SSN
		AND AY20_5.LN_ATY_SEQ = AY10_DPH.LN_ATY_SEQ
		AND AY20_5.LN_ATY_CMT_SEQ = 5
WHERE
	LN10.IC_LON_PGM NOT IN ('TILP','COMPLT')
	AND LN16.LN_DLQ_MAX >= 90
	AND AY10_CCP.BF_SSN IS NULL
	AND LN10.IF_GTR != '000749'
	AND LN10.LA_CUR_PRI > 0
	AND (
			AY10_DPH.BF_SSN IS NULL /*missing dph*/
			OR /*comment exists: exclude specific comment types*/
			(
				LTRIM(RTRIM(CONCAT(COALESCE(AY20_1.LX_ATY,''), COALESCE(AY20_2.LX_ATY,''), COALESCE(AY20_3.LX_ATY,''), COALESCE(AY20_4.LX_ATY,''), COALESCE(AY20_5.LX_ATY,'')))) != ''
				AND CONCAT(COALESCE(AY20_1.LX_ATY,''), COALESCE(AY20_2.LX_ATY,''), COALESCE(AY20_3.LX_ATY,''), COALESCE(AY20_4.LX_ATY,''), COALESCE(AY20_5.LX_ATY,'')) NOT LIKE '%ACTIVE%'
				AND CONCAT(COALESCE(AY20_1.LX_ATY,''), COALESCE(AY20_2.LX_ATY,''), COALESCE(AY20_3.LX_ATY,''), COALESCE(AY20_4.LX_ATY,''), COALESCE(AY20_5.LX_ATY,'')) NOT LIKE '%COMPLETE%'
				AND CONCAT(COALESCE(AY20_1.LX_ATY,''), COALESCE(AY20_2.LX_ATY,''), COALESCE(AY20_3.LX_ATY,''), COALESCE(AY20_4.LX_ATY,''), COALESCE(AY20_5.LX_ATY,'')) NOT LIKE '%DUP%'
			)
		)
--ORDER BY 
--	PD10.DF_SPE_ACC_ID,
--	LN40.LN_SEQ_CLM_PCL,
--	LN10.LN_SEQ
