/*CREATE LIBNAME FOR REMOTE SERVER'S WORK FOLDER*/
LIBNAME WORKLOCL REMOTE SERVER=DUSTER SLIBREF=WORK;

/*CREATE FILENAME FOR OUTPUT*/
%LET RPTLIB = T:\SAS;
FILENAME REPORT1 "&RPTLIB/UNH_58874.XLSX";

/*CREATE LIBRARY OF EXCEL DATA*/
LIBNAME XLIB XLSX 'T:\533581 LN72 DCR.xlsx';

/*CREATE DATA SET FROM A SPECIFIC SHEET IN THE EXCEL FILE*/
DATA XLDATA; SET XLIB.LN72; RUN;

/*CAST CHAR SEQ ATTRIBUTE TO NUMERIC ATTRIBUTE WITH THE SAME NAME AND COPY NEW DATA SET TO REMOTE SERVER*/
/*TODO: update attributes names or delete this block if unneeded*/
DATA XDATA (DROP = CHAR_SEQ);
	RETAIN BF_SSN WN_SEQ_GR10; /*only the attribute that was cast and any attributes to the left of it are needed*/
	SET XLDATA (RENAME = (WN_SEQ_GR10 = CHAR_SEQ));
	WN_SEQ_GR10 = INPUT(CHAR_SEQ, 2.);
RUN;
DATA WORKLOCL.XDATA; SET XDATA; RUN;

/*COPY EXCEL DATA TO REMOTE SERVER*/
/*TODO: delete this block if the CAST block above was used*/
DATA WORKLOCL.XDATA; SET XLDATA; RUN;

/*SUBMIT CODE TO REMOTE SERVER*/
/*TODO: delete the unneeded block*/
RSUBMIT DUSTER;
LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
%let DB = DLGSUTWH;
%let OWNR = OLWHRM1;

PROC SQL STIMER;
	CONNECT TO DB2 (DATABASE=&DB); 

/*TODO: update SQL below*/
/*	GET DATA FOR ALL LOANS*/
	CREATE TABLE JOINDATA AS
		SELECT 
			XDAT.*
			,DB2D.LD_LON_ACL_ADD

		FROM 
			CONNECTION TO DB2 
			(
				SELECT DISTINCT 
					LN10.BF_SSN 
					,LN10.LN_SEQ
					,LN10.LD_LON_ACL_ADD
				FROM 
					&OWNR..LN10_LON LN10
				WHERE 
					LN10.LA_CUR_PRI > 0.00
		
				FOR READ ONLY WITH UR
			) DB2D
			INNER JOIN XDATA XDAT
				ON DB2D.BF_SSN = XDAT.BF_SSN
				AND DB2D.LN_SEQ = XDAT.LN_SEQ
	;
	DISCONNECT FROM DB2;


QUIT;

ENDRSUBMIT;

/*COPY JOINED DATA TO WORK*/
DATA JOINDATA; SET WORKLOCL.JOINDATA; RUN;

/*EXPORT JOINED DATA TO A REPORT*/
PROC EXPORT DATA= WORK.JOINDATA
	OUTFILE= REPORT1 
	REPLACE
	DBMS=XLSX;
RUN;
