USE ODW
GO

SELECT
	PD01.DF_PRS_ID,
	PD01.DF_SPE_ACC_ID,
	COUNT(PD01.LOAN) AS Loans,
	SUM(PD01.Principal) AS Principal
FROM
	(
		SELECT DISTINCT
			DF_PRS_ID,
			DF_SPE_ACC_ID,
			ISNULL(GA01.AF_APL_ID,'') + ISNULL(AF_APL_ID_SFX,'') AS LOAN,
			SUM(GA10.AA_CUR_PRI) AS [Principal]
		FROM
			PD01_PDM_INF PD01
			INNER JOIN GA01_APP GA01
				ON GA01.DF_PRS_ID_BR = PD01.DF_PRS_ID
			INNER JOIN GA10_LON_APP GA10
				ON GA10.AF_APL_ID = GA01.AF_APL_ID
		GROUP BY
			DF_PRS_ID,
			DF_SPE_ACC_ID,
			ISNULL(GA01.AF_APL_ID,'') + ISNULL(AF_APL_ID_SFX,'')
	) PD01
	INNER JOIN @POP P 
		ON P.SSN = PD01.DF_PRS_ID
GROUP BY
	DF_PRS_ID,
	DF_SPE_ACC_ID