%LET numdate = %SYSFUNC(today(), yymmddn8.);
%LET RPTLIB = X:\PADD\Finance\Borrower Benefits\;
/*%LET RPTLIB = T:\SAS;*/
FILENAME REPORTZ "&RPTLIB/ULWA39.LWA39RZ.&numdate";
FILENAME REPORT2 "&RPTLIB/ULWA39.LWA39R2.&numdate";
LIBNAME  DUSTER  REMOTE  SERVER=DUSTER  SLIBREF=WORK;

/*LIBNAME  DUSTER  REMOTE  SERVER=QADBD004 SLIBREF=WORK;*/

DATA _NULL_;
     CALL SYMPUT('EFFDATE',"'"||PUT(INTNX('MONTH',TODAY(),0,'END'), MMDDYYD10.)||"'");
RUN;

%SYSLPUT EFFDATE = &EFFDATE;
%SYSLPUT LOADDATE = '02/01/2016';
RSUBMIT;
/*LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/

%MACRO SQLCHECK ;
  %IF  &SQLXRC NE 0  %THEN  %DO  ;
    DATA _NULL_  ;
            FILE REPORTZ NOTITLES  ;
            PUT @01 " ********************************************************************* "
              / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
              / @01 " ****  THE SAS SHOULD BE REVIEWED.                                **** "       
              / @01 " ********************************************************************* "
              / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
              / @01 " ****  &SQLXMSG   **** "
              / @01 " ********************************************************************* "
            ;
         RUN  ;
  %END  ;
%MEND SQLCHECK ;

PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);/*DLGSWQUT (test)*/ /*DLGSUTWH (live)*/

CREATE TABLE BorrBenefits AS
SELECT 
*
FROM 
CONNECTION TO DB2 
(
	SELECT DISTINCT
		LN10.BF_SSN,
		LN10.LN_SEQ,
		CONCAT(LN10.LF_LON_ALT,LPAD(LN10.LN_LON_ALT_SEQ,2,'0')) AS CLUID,
		LN10.LF_GTR_RFR_XTN,
		LN10.LF_LON_CUR_OWN,
		LN10.IC_LON_PGM,
		CASE
			WHEN LN83.LC_STA_LN83 = 'A' AND LN83.LC_EFT_SUS_REA = ' ' THEN 'Y'
			ELSE 'N'
		END AS ACH_STATUS,
		LN83.LD_EFT_EFF_BEG,
		LN83.LD_EFT_EFF_END,
		CASE
			WHEN LN83.LC_STA_LN83 = 'A' AND LN83.LC_EFT_SUS_REA = ' ' THEN LN83.LR_EFT_RDC
			ELSE NULL
		END AS LR_EFT_RDC,
		CASE
			WHEN LN54.PM_BBS_PGM = 'BT1' THEN 'BANA Tier 1'
			WHEN LN54.PM_BBS_PGM = 'BT2' THEN 'BANA Tier 2'
			WHEN LN54.PM_BBS_PGM = 'BT3' THEN 'BANA Tier 3'
			WHEN LN54.PM_BBS_PGM = 'BI1' THEN 'BANA Int 1'
			WHEN LN54.PM_BBS_PGM = 'BI2' THEN 'BANA Int 2'
			WHEN LN54.PM_BBS_PGM = 'BI3' THEN 'BANA Int 3'
			WHEN LN54.PM_BBS_PGM = 'BI4' THEN 'BANA Int 4'
			WHEN LN54.PM_BBS_PGM = 'BI5' THEN 'BANA Int 5'
			WHEN LN54.PM_BBS_PGM = 'BI6' THEN 'BANA Int 6'
			WHEN LN54.PM_BBS_PGM = 'BI7' THEN 'BANA Int 7'
			WHEN LN54.PM_BBS_PGM = 'BI8' THEN 'BANA Int 8'
			WHEN LN54.PM_BBS_PGM = 'BI9' THEN 'BANA Int 9'
			WHEN LN54.PM_BBS_PGM = 'BIA' THEN 'BANA Int A'
			WHEN LN54.PM_BBS_PGM = 'BIB' THEN 'BANA Int B'
			WHEN LN54.PM_BBS_PGM = 'BIC' THEN 'BANA Int C'
			WHEN LN54.PM_BBS_PGM = 'BID' THEN 'BANA Int D'
			WHEN LN54.PM_BBS_PGM = 'BIE' THEN 'BANA Int E'
			WHEN LN54.PM_BBS_PGM = 'BR1' THEN 'BANA Rbt 1'
			ELSE 'N/A'
		END AS TIMELY_PMT_PLAN,
		CASE
			WHEN LN54.LC_BBS_ELG IN('N','X') THEN 'NOT ELIGIBLE'
			WHEN LN54.LC_BBS_ELG = 'Y' THEN 'ELIGIBLE'
			ELSE 'NOT ELIGIBLE'
		END AS TIMELY_PMT_ELIG,
		MAX(CASE
			WHEN LN55.LF_LON_BBS_TIR ='01' THEN
				CASE
					WHEN LN55.LD_LON_BBT_BEG > CURRENT DATE THEN 'ELIGIBLE'
					WHEN LN55.LC_LON_BBT_STA = 'A' THEN 'REBATE'
					WHEN LN55.LC_LON_BBT_STA = 'D' THEN 'DISQUALIFIED'
					WHEN LN55.LC_LON_BBT_STA = 'N' THEN 'NOT ELIGIBLE'
					WHEN LN55.LC_LON_BBT_STA = 'Q' THEN 'ELIGIBLE'
					WHEN LN55.LC_LON_BBT_STA = 'R' THEN 'REDUCED'
					ELSE 'N/A'
				END
			ELSE NULL 
		END) AS TIMELY_T1_STA,
		MAX(CASE
			WHEN LN55.LF_LON_BBS_TIR ='01' 
				THEN LN90.LA_FAT_CUR_PRI 
				ELSE NULL 
		END) AS TIMELY_T1_AMT,
		MAX(CASE
			WHEN LN55.LF_LON_BBS_TIR ='01' 
				THEN LN90.LD_FAT_EFF 
				ELSE NULL 
		END) AS TIMELY_T1_DTE,
		MAX(CASE
			WHEN LN55.LF_LON_BBS_TIR ='02' THEN
				CASE
					WHEN LN55.LD_LON_BBT_BEG > CURRENT DATE THEN 'ELIGIBLE'
					WHEN LN55.LC_LON_BBT_STA = 'A' THEN 'REBATE'
					WHEN LN55.LC_LON_BBT_STA = 'D' THEN 'DISQUALIFIED'
					WHEN LN55.LC_LON_BBT_STA = 'N' THEN 'NOT ELIGIBLE'
					WHEN LN55.LC_LON_BBT_STA = 'Q' THEN 'ELIGIBLE'
					WHEN LN55.LC_LON_BBT_STA = 'R' THEN 'REDUCED'
					ELSE 'N/A'
				END
			ELSE NULL 
		END) AS TIMELY_T2_STA,
		MAX(CASE
			WHEN LN55.LF_LON_BBS_TIR ='02' 
				THEN LN90.LA_FAT_CUR_PRI 
				ELSE NULL 
		END) AS TIMELY_T2_AMT,
		MAX(CASE
			WHEN LN55.LF_LON_BBS_TIR ='02' 
				THEN LN90.LD_FAT_EFF 
				ELSE NULL 
		END) AS TIMELY_T2_DTE,
		MAX(CASE
			WHEN LN55.LF_LON_BBS_TIR ='03' THEN
				CASE
					WHEN LN55.LD_LON_BBT_BEG > CURRENT DATE THEN 'ELIGIBLE'
					WHEN LN55.LC_LON_BBT_STA = 'A' THEN 'REBATE'
					WHEN LN55.LC_LON_BBT_STA = 'D' THEN 'DISQUALIFIED'
					WHEN LN55.LC_LON_BBT_STA = 'N' THEN 'NOT ELIGIBLE'
					WHEN LN55.LC_LON_BBT_STA = 'Q' THEN 'ELIGIBLE'
					WHEN LN55.LC_LON_BBT_STA = 'R' THEN 'REDUCED'
					ELSE 'N/A'
				END
			ELSE NULL 
		END) AS TIMELY_T3_STA,
		MAX(CASE
			WHEN LN55.LF_LON_BBS_TIR ='03' 
				THEN LN90.LA_FAT_CUR_PRI 
				ELSE NULL 
		END) AS TIMELY_T3_AMT,
		MAX(CASE
			WHEN LN55.LF_LON_BBS_TIR ='03' 
				THEN LN90.LD_FAT_EFF 
				ELSE NULL 
		END) AS TIMELY_T3_DTE,
		MAX(CASE
			WHEN LN55.LF_LON_BBS_TIR ='04' THEN
				CASE
					WHEN LN55.LD_LON_BBT_BEG > CURRENT DATE THEN 'ELIGIBLE'
					WHEN LN55.LC_LON_BBT_STA = 'A' THEN 'REBATE'
					WHEN LN55.LC_LON_BBT_STA = 'D' THEN 'DISQUALIFIED'
					WHEN LN55.LC_LON_BBT_STA = 'N' THEN 'NOT ELIGIBLE'
					WHEN LN55.LC_LON_BBT_STA = 'Q' THEN 'ELIGIBLE'
					WHEN LN55.LC_LON_BBT_STA = 'R' THEN 'REDUCED'
					ELSE 'N/A'
				END
			ELSE NULL 
		END) AS TIMELY_T4_STA,
		MAX(CASE
			WHEN LN55.LF_LON_BBS_TIR ='04' 
				THEN LN90.LA_FAT_CUR_PRI 
				ELSE NULL 
		END) AS TIMELY_T4_AMT,
		MAX(CASE
			WHEN LN55.LF_LON_BBS_TIR ='04' 
				THEN LN90.LD_FAT_EFF 
				ELSE NULL 
		END) AS TIMELY_T4_DTE,
		LN84.LD_RDC_EFF_BEG,
		LN84.LD_RDC_EFF_END,
		LN84.LR_RDC,
		LN72.LR_ITR,
		LN72.LR_INT_RDC_PGM_ORG,
		LN72.LD_ITR_EFF_BEG,
		LN72.LD_ITR_EFF_END
	FROM  
		OLWHRM1.LN10_LON LN10
		LEFT JOIN 
		(
			SELECT
				BF_SSN,
				LN_SEQ,
				MAX(BN_EFT_SEQ) AS BN_EFT_SEQ
			FROM
				OLWHRM1.LN83_EFT_TO_LON LN83
			WHERE
				LN83.LC_STA_LN83 = 'A'
				AND 
				(
					&EFFDATE BETWEEN LN83.LD_EFT_EFF_BEG AND LN83.LD_EFT_EFF_END 
					OR &EFFDATE > LN83.LD_EFT_EFF_BEG AND LN83.LD_EFT_EFF_END IS NULL
				)
			GROUP BY
				BF_SSN,
				LN_SEQ
		)LN83Max
			ON LN10.BF_SSN = LN83Max.BF_SSN
			AND LN10.LN_SEQ = LN83Max.LN_SEQ
		LEFT JOIN OLWHRM1.LN83_EFT_TO_LON LN83
			ON LN10.BF_SSN = LN83.BF_SSN
			AND LN10.LN_SEQ = LN83.LN_SEQ
			AND LN83Max.BN_EFT_SEQ = LN83.BN_EFT_SEQ
			AND LN83.LC_STA_LN83 = 'A'
			AND 
			(
				&EFFDATE BETWEEN LN83.LD_EFT_EFF_BEG AND LN83.LD_EFT_EFF_END 
				OR &EFFDATE > LN83.LD_EFT_EFF_BEG AND LN83.LD_EFT_EFF_END IS NULL
			)
		LEFT JOIN OLWHRM1.LN54_LON_BBS LN54
			ON LN10.BF_SSN = LN54.BF_SSN
			AND LN10.LN_SEQ = LN54.LN_SEQ
			AND LN54.LC_STA_LN54 = 'A'
		LEFT JOIN OLWHRM1.LN55_LON_BBS_TIR LN55
			ON LN55.BF_SSN = LN54.BF_SSN
			AND LN55.LN_SEQ = LN54.LN_SEQ
			AND LN55.LN_LON_BBS_SEQ = LN54.LN_LON_BBS_PGM_SEQ
			AND LN55.LC_STA_LN55 = 'A'
		LEFT JOIN OLWHRM1.LN57_LON_BBT_FAT LN57
			ON LN57.BF_SSN = LN55.BF_SSN
			AND LN57.LN_SEQ = LN55.LN_SEQ
			AND LN57.LN_LON_BBS_SEQ = LN55.LN_LON_BBS_SEQ
			AND LN57.LN_LON_BBT_SEQ = LN55.LN_LON_BBT_SEQ
		LEFT JOIN 
		(
			SELECT
				LN84.BF_SSN,
				LN84.LN_SEQ,
				LN84.LD_RDC_EFF_BEG,
				LN84.LD_RDC_EFF_END,
				LN84.LR_RDC
			FROM
				OLWHRM1.LN84_LON_RTE_RDC LN84
				INNER JOIN
				(
					SELECT
						BF_SSN,
						LN_SEQ,
						MAX(COALESCE(LD_RDC_EFF_END,'2099-01-01')) AS LD_RDC_EFF_END
					FROM
						OLWHRM1.LN84_LON_RTE_RDC
					WHERE
						LC_STA_LON84 = 'A'
					GROUP BY
						BF_SSN,
						LN_SEQ
				)LN84MAX 
					ON LN84MAX.BF_SSN = LN84.BF_SSN
					AND LN84MAX.LN_SEQ = LN84.LN_SEQ
					AND LN84MAX.LD_RDC_EFF_END = COALESCE(LN84.LD_RDC_EFF_END,'2099-01-01')
			WHERE
				LN84.LC_STA_LON84 = 'A'
		) LN84
			ON LN10.BF_SSN = LN84.BF_SSN
			AND LN10.LN_SEQ = LN84.LN_SEQ
		LEFT JOIN
		(
			SELECT
				Interest.BF_SSN,
				Interest.LN_SEQ,
				Interest.LR_ITR,
				Interest.LC_INT_RDC_PGM,
				Interest.LR_INT_RDC_PGM_ORG,
				Interest.LD_ITR_EFF_BEG,
				Interest.LD_ITR_EFF_END
			FROM
			(
				SELECT
					LN72.BF_SSN,
					LN72.LN_SEQ,
					LN72.LR_ITR,
					LN72.LC_INT_RDC_PGM,
					LN72.LR_INT_RDC_PGM_ORG,
					LN72.LD_ITR_EFF_BEG,
					LN72.LD_ITR_EFF_END,
					ROW_NUMBER() OVER (PARTITION BY LN72.BF_SSN, LN72.LN_SEQ ORDER BY LN72.LD_STA_LON72 DESC) AS CurrentRow
				FROM
					OLWHRM1.LN72_INT_RTE_HST LN72
					INNER JOIN OLWHRM1.LN10_LON LN10
						ON LN10.BF_SSN = LN72.BF_SSN
						AND LN10.LN_SEQ = LN72.LN_SEQ
				WHERE
					LN72.LC_STA_LON72 = 'A'
					AND &EFFDATE BETWEEN LN72.LD_ITR_EFF_BEG AND LN72.LD_ITR_EFF_END
					AND LN10.LC_STA_LON10 = 'R'
			) Interest
			WHERE
				Interest.CurrentRow = 1
		) LN72
			ON LN72.BF_SSN = LN10.BF_SSN
			AND LN72.LN_SEQ = LN10.LN_SEQ
		LEFT JOIN OLWHRM1.LN90_FIN_ATY LN90
			ON LN90.BF_SSN = LN57.BF_SSN
			AND LN90.LN_SEQ = LN57.LN_SEQ
			AND LN90.LN_FAT_SEQ = LN57.LN_FAT_SEQ
			AND LN90.LC_STA_LON90 = 'A'
			AND LN90.LC_FAT_REV_REA = ' '
			AND LN90.PC_FAT_TYP = '18'
			AND LN90.PC_FAT_SUB_TYP = '01'
	WHERE 
		LN10.LF_LON_CUR_OWN LIKE '829769%'
		AND LN10.LD_LON_EFF_ADD >= &LOADDATE
	GROUP BY
		LN10.BF_SSN,
		LN10.LN_SEQ,
		CONCAT(LN10.LF_LON_ALT,LPAD(LN10.LN_LON_ALT_SEQ,2,'0')),
		LN10.LF_GTR_RFR_XTN,
		LN10.LF_LON_CUR_OWN,
		LN10.IC_LON_PGM,
		CASE
			WHEN LN83.LC_STA_LN83 = 'A' AND LN83.LC_EFT_SUS_REA = ' ' THEN 'Y'
			ELSE 'N'
		END,
		LN83.LD_EFT_EFF_BEG,
		LN83.LD_EFT_EFF_END,
		CASE
			WHEN LN83.LC_STA_LN83 = 'A' AND LN83.LC_EFT_SUS_REA = ' ' THEN LN83.LR_EFT_RDC
			ELSE NULL
		END,
		CASE
			WHEN LN54.PM_BBS_PGM = 'BT1' THEN 'BANA Tier 1'
			WHEN LN54.PM_BBS_PGM = 'BT2' THEN 'BANA Tier 2'
			WHEN LN54.PM_BBS_PGM = 'BT3' THEN 'BANA Tier 3'
			WHEN LN54.PM_BBS_PGM = 'BI1' THEN 'BANA Int 1'
			WHEN LN54.PM_BBS_PGM = 'BI2' THEN 'BANA Int 2'
			WHEN LN54.PM_BBS_PGM = 'BI3' THEN 'BANA Int 3'
			WHEN LN54.PM_BBS_PGM = 'BI4' THEN 'BANA Int 4'
			WHEN LN54.PM_BBS_PGM = 'BI5' THEN 'BANA Int 5'
			WHEN LN54.PM_BBS_PGM = 'BI6' THEN 'BANA Int 6'
			WHEN LN54.PM_BBS_PGM = 'BI7' THEN 'BANA Int 7'
			WHEN LN54.PM_BBS_PGM = 'BI8' THEN 'BANA Int 8'
			WHEN LN54.PM_BBS_PGM = 'BI9' THEN 'BANA Int 9'
			WHEN LN54.PM_BBS_PGM = 'BIA' THEN 'BANA Int A'
			WHEN LN54.PM_BBS_PGM = 'BIB' THEN 'BANA Int B'
			WHEN LN54.PM_BBS_PGM = 'BIC' THEN 'BANA Int C'
			WHEN LN54.PM_BBS_PGM = 'BID' THEN 'BANA Int D'
			WHEN LN54.PM_BBS_PGM = 'BIE' THEN 'BANA Int E'
			WHEN LN54.PM_BBS_PGM = 'BR1' THEN 'BANA Rbt 1'
			ELSE 'N/A'
		END,
		CASE
			WHEN LN54.LC_BBS_ELG IN('N','X') THEN 'NOT ELIGIBLE'
			WHEN LN54.LC_BBS_ELG = 'Y' THEN 'ELIGIBLE'
			ELSE 'NOT ELIGIBLE'
		END,
		LN84.LD_RDC_EFF_BEG,
		LN84.LD_RDC_EFF_END,
		LN84.LR_RDC,
		LN72.LR_ITR,
		LN72.LR_INT_RDC_PGM_ORG,
		LN72.LD_ITR_EFF_BEG,
		LN72.LD_ITR_EFF_END
	ORDER BY
		LN10.BF_SSN,
		LN10.LN_SEQ

	FOR READ ONLY WITH UR
)
;

DISCONNECT FROM DB2;

      /*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>> ;  ** INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
      /*%SQLCHECK;*/
QUIT;

ENDRSUBMIT;

DATA BorrBenefits;
      SET DUSTER.BorrBenefits;
RUN;
 DATA _NULL_;
 SET  WORK.BorrBenefits; 
 FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
 	FORMAT BF_SSN $9. ;
 	FORMAT LN_SEQ $3. ;
 	FORMAT CLUID $19. ;
 	FORMAT LF_GTR_RFR_XTN $23. ;
 	FORMAT LF_LON_CUR_OWN $8. ;
 	FORMAT IC_LON_PGM $6. ;
 	FORMAT ACH_STATUS $1. ;
 	FORMAT LD_EFT_EFF_BEG DATE9. ;
 	FORMAT LD_EFT_EFF_END DATE9. ;
 	FORMAT LR_EFT_RDC BEST12. ;
 	FORMAT TIMELY_PMT_PLAN $11. ;
 	FORMAT TIMELY_PMT_ELIG $12. ;
 	FORMAT TIMELY_T1_STA $12. ;
 	FORMAT TIMELY_T1_AMT BEST12. ;
 	FORMAT TIMELY_T1_DTE DATE9. ;
 	FORMAT TIMELY_T2_STA $12. ;
 	FORMAT TIMELY_T2_AMT BEST12. ;
 	FORMAT TIMELY_T2_DTE DATE9. ;
 	FORMAT TIMELY_T3_STA $12. ;
 	FORMAT TIMELY_T3_AMT BEST12. ;
 	FORMAT TIMELY_T3_DTE DATE9. ;
 	FORMAT TIMELY_T4_STA $12. ;
 	FORMAT TIMELY_T4_AMT BEST12. ;
 	FORMAT TIMELY_T4_DTE DATE9. ;
 	FORMAT LD_RDC_EFF_BEG DATE9. ;
 	FORMAT LD_RDC_EFF_END DATE9. ;
 	FORMAT LR_RDC BEST12. ;
 	FORMAT LR_ITR BEST12. ;
 	FORMAT LR_INT_RDC_PGM_ORG BEST12. ;
 	FORMAT LD_ITR_EFF_BEG DATE9. ;
 	FORMAT LD_ITR_EFF_END DATE9. ;
 	  IF _N_ = 1 THEN   PUT 'BF_SSN,LN_SEQ,CLUID,LF_GTR_RFR_XTN,IF_OWN,IC_LON_PGM,ACH_STATUS,LD_EFT_EFF_BEG,LD_RDC_EFF_END,LR_EFT_RDC,TIMELY_PAY_PLAN,TIMELY_PMT_ELIG,TIMELY_T1_STA,TIMELY_T1_AMT,TIMELY_T1_DTE,TIMELY_T2_STA,TIMELY_T2_AMT,TIMELY_T2_DTE,TIMELY_T3_STA,TIMELY_T3_AMT,TIMELY_T3_DTE,TIMELY_T4_STA,TIMELY_T4_AMT,TIMELY_T4_DTE,LR_RDC_EFF_BEG,LR_RDC_EFF_END,LR_RDC,LR_ITR,LR_ITR_ORG,LD_ITR_EFF_BEG,LD_ITR_EFF_END';
 
 DO;
 	PUT BF_SSN $ @;
 	PUT LN_SEQ $ @;
 	PUT CLUID $ @;
 	PUT LF_GTR_RFR_XTN $ @;
 	PUT LF_LON_CUR_OWN $ @;
 	PUT IC_LON_PGM $ @;
 	PUT ACH_STATUS $ @;
 	PUT LD_EFT_EFF_BEG @;
 	PUT LD_EFT_EFF_END @;
 	PUT LR_EFT_RDC @;
 	PUT TIMELY_PMT_PLAN $ @;
 	PUT TIMELY_PMT_ELIG $ @;
 	PUT TIMELY_T1_STA $ @;
 	PUT TIMELY_T1_AMT @;
 	PUT TIMELY_T1_DTE @;
 	PUT TIMELY_T2_STA $ @;
 	PUT TIMELY_T2_AMT @;
 	PUT TIMELY_T2_DTE @;
 	PUT TIMELY_T3_STA $ @;
 	PUT TIMELY_T3_AMT @;
 	PUT TIMELY_T3_DTE @;
 	PUT TIMELY_T4_STA $ @;
 	PUT TIMELY_T4_AMT @;
 	PUT TIMELY_T4_DTE @;
 	PUT LD_RDC_EFF_BEG @;
 	PUT LD_RDC_EFF_END @;
 	PUT LR_RDC @;
 	PUT LR_ITR @;
 	PUT LR_INT_RDC_PGM_ORG @;
 	PUT LD_ITR_EFF_BEG @;
 	PUT LD_ITR_EFF_END;
 END;
 RUN;
