/*TEST*/
/*%LET TESTMSG = - THIS IS A TEST;
%LET RPTLIB = T:\SAS;
%LET LOGLIB = Y:\Batch\Logs;
%LET CODELIB = Y:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS_TEST;
%LET DB = CDW_test;
%LET ODBCFILE_CSYS = CSYSTest;*/

/*LIVE*/
%LET TESTMSG = - THIS IS LIVE;
%LET RPTLIB = Z:\Batch\FTP;
%LET LOGLIB = Z:\Batch\Logs;
%LET CODELIB = Z:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS;
%LET DB = CDW;
%LET ODBCFILE_CSYS = CSYS;

%INCLUDE "&CODELIB\UTNWDW1 CDW DAILY UPDATE.FOLDER AND DATABASE.SAS";
%FILECHECK(36);

DATA LN54(drop=trunc);
	INFILE REPORT36 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
	INPUT 
		DF_SPE_ACC_ID :$10. 
		LN_SEQ :6.
		PM_BBS_PGM :$3. 
		PN_BBS_PGM_SEQ :6.
		LN_LON_BBS_PGM_SEQ :6.
		LD_EFF_BEG_LN54 :$10.
		LI_BBS_ITD_LTR_SNT :$1.
		LN_BBS_STS_PCV_PAY :3.0
		LC_BBS_REB_MTD :$1.
		LC_STA_LN54 :$1.
		LD_STA_LN54 :$10.
		LC_BBS_DSQ_REA :$2.
		LD_BBS_DSQ :$10.
		LC_BBS_ELG :$11.
	;
%TRUNCAT(36);
RUN;
%COPYERROR;
PROC SORT DATA=LN54; BY DF_SPE_ACC_ID LN_SEQ PM_BBS_PGM PN_BBS_PGM_SEQ LN_LON_BBS_PGM_SEQ; RUN;
DATA LN54; SET LN54; BY DF_SPE_ACC_ID LN_SEQ PM_BBS_PGM PN_BBS_PGM_SEQ LN_LON_BBS_PGM_SEQ; IF LAST.LN_LON_BBS_PGM_SEQ; RUN;

%ENCHILADA
	(
		LN54,
		LN54_BENEFITPROGRAM, 
/*		primary key fields*/
		DF_SPE_ACC_ID 
		LN_SEQ 
		PM_BBS_PGM 
		PN_BBS_PGM_SEQ 
		LN_LON_BBS_PGM_SEQ, 
/*		other fields*/
		LD_EFF_BEG_LN54
		LI_BBS_ITD_LTR_SNT
		LN_BBS_STS_PCV_PAY
		LC_BBS_REB_MTD
		LC_STA_LN54
		LD_STA_LN54
		LC_BBS_DSQ_REA
		LD_BBS_DSQ
		LC_BBS_ELG,
/*		no filter*/
	)
;

%GOODBYE_NULL(LN54_BENEFITPROGRAM,LD_EFF_BEG_LN54,'');
%GOODBYE_NULL(LN54_BENEFITPROGRAM,LI_BBS_ITD_LTR_SNT,'');
%GOODBYE_NULL(LN54_BENEFITPROGRAM,LN_BBS_STS_PCV_PAY,0);
%GOODBYE_NULL(LN54_BENEFITPROGRAM,LC_BBS_REB_MTD,'');
%GOODBYE_NULL(LN54_BENEFITPROGRAM,LC_STA_LN54,'');
%GOODBYE_NULL(LN54_BENEFITPROGRAM,LD_STA_LN54,'');
%GOODBYE_NULL(LN54_BENEFITPROGRAM,LC_BBS_DSQ_REA,'');
%GOODBYE_NULL(LN54_BENEFITPROGRAM,LD_BBS_DSQ,'');
%GOODBYE_NULL(LN54_BENEFITPROGRAM,LC_BBS_ELG,'');

%FINISH(SOURCE=BenefitProgram);
