/*TEST*/
/*%LET TESTMSG = - THIS IS A TEST;
%LET RPTLIB = T:\SAS;
%LET LOGLIB = Y:\Batch\Logs;
%LET CODELIB = Y:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS_TEST;
%LET DB = CDW_test;
%LET ODBCFILE_CSYS = CSYSTest;*/

/*LIVE*/
%LET TESTMSG = - THIS IS LIVE;
%LET RPTLIB = Z:\Batch\FTP;
%LET LOGLIB = Z:\Batch\Logs;
%LET CODELIB = Z:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS;
%LET DB = CDW;
%LET ODBCFILE_CSYS = CSYS;

%INCLUDE "&CODELIB\UTNWDW1 CDW DAILY UPDATE.FOLDER AND DATABASE.SAS";
%FILECHECK(7);

DATA FB10(drop=trunc);
INFILE REPORT7 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
INPUT DF_SPE_ACC_ID :$10. LN_SEQ :6. LF_FOR_CTL_NUM :$3. LN_FOR_OCC_SEQ :6. LC_FOR_TYP :$2. 
	LD_FOR_INF_CER :$10. LD_FOR_BEG :$10. LD_FOR_END :$10. LI_CAP_FOR_INT_REQ :$1. 
	LC_STA_LON60 :$1. LC_FOR_STA :$1. LC_STA_FOR10 :$1. LA_REQ_RDC_PAY :9.2 ;
	LA_REQ_RDC_PAY = COALESCE(LA_REQ_RDC_PAY,0);
	FOR_TYP = PUT(LC_FOR_TYP,$FORSTA.);
	MONTHS_USED = ROUND((INPUT(LD_FOR_END,MMDDYY10.) - INPUT(LD_FOR_BEG,MMDDYY10.)+1)/365 * 12,.1);
 %TRUNCAT(7);
RUN;
%COPYERROR;
PROC SORT DATA=FB10; BY DF_SPE_ACC_ID LN_SEQ LF_FOR_CTL_NUM LN_FOR_OCC_SEQ ; RUN;
DATA FB10; SET FB10; BY DF_SPE_ACC_ID LN_SEQ LF_FOR_CTL_NUM LN_FOR_OCC_SEQ; IF LAST.LN_FOR_OCC_SEQ; RUN;

%ENCHILADA(FB10,FB10_FORBEARANCE,DF_SPE_ACC_ID LN_SEQ LF_FOR_CTL_NUM LN_FOR_OCC_SEQ,LC_FOR_TYP FOR_TYP LD_FOR_INF_CER 
	LD_FOR_BEG LD_FOR_END LI_CAP_FOR_INT_REQ LC_STA_LON60 LC_FOR_STA LC_STA_FOR10 MONTHS_USED LA_REQ_RDC_PAY,
	WHERE LC_STA_LON60 = 'A'
	  	AND LC_FOR_STA = 'A'
		AND LC_STA_FOR10 = 'A');

%GOODBYE_NULL(FB10_FORBEARANCE,LC_FOR_TYP,'');
%GOODBYE_NULL(FB10_FORBEARANCE,FOR_TYP,'');
%GOODBYE_NULL(FB10_FORBEARANCE,LD_FOR_INF_CER,'');
%GOODBYE_NULL(FB10_FORBEARANCE,LD_FOR_BEG,'');
%GOODBYE_NULL(FB10_FORBEARANCE,LD_FOR_END,'');
%GOODBYE_NULL(FB10_FORBEARANCE,LI_CAP_FOR_INT_REQ,'');
%GOODBYE_NULL(FB10_FORBEARANCE,LC_STA_LON60,'');
%GOODBYE_NULL(FB10_FORBEARANCE,LC_FOR_STA,'');
%GOODBYE_NULL(FB10_FORBEARANCE,LC_STA_FOR10,'');
%GOODBYE_NULL(FB10_FORBEARANCE,MONTHS_USED,0);	
%GOODBYE_NULL(FB10_FORBEARANCE,LA_REQ_RDC_PAY,0);

%FINISH(SOURCE=Forbearance);
