/*TEST*/
/*%LET TESTMSG = - THIS IS A TEST;
%LET RPTLIB = T:\SAS;
%LET LOGLIB = Y:\Batch\Logs;
%LET CODELIB = Y:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS_TEST;
%LET DB = CDW_test;
%LET ODBCFILE_CSYS = CSYSTest;*/

/*LIVE*/
%LET TESTMSG = - THIS IS LIVE;
%LET RPTLIB = Z:\Batch\FTP;
%LET LOGLIB = Z:\Batch\Logs;
%LET CODELIB = Z:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS;
%LET DB = CDW;
%LET ODBCFILE_CSYS = CSYS;

%INCLUDE "&CODELIB\UTNWDW1 CDW DAILY UPDATE.FOLDER AND DATABASE.SAS"  ;
%FILECHECK(51);


DATA LN10(drop=trunc);
	INFILE REPORT51 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof LRECL = 32767;
	INPUT 
		BF_SSN :$9.
		LN_SEQ :2.
		LC_STA_LON10 :$1.
		LI_FGV_PGM :$1.
		LF_LON_SLE_PND :$7.
		LA_CUR_PRI :8.2
		LI_ELG_CPN_BOK :$1.
		LA_LON_AMT_GTR :8.2
		LD_LON_GTR :DATE9.
		LD_PIF_PNT_RTN :DATE9.
		LD_PNT_SIG :DATE9.
		LC_INT_BIL_OPT :$1.
		LI_CAP_ALW :$1.
		LD_END_GRC_PRD :DATE9.
		LN_MTH_GRC_PRD_DSC :3.0
		LA_R78_INT_PD :7.2
		LA_R78_INT_MAX :7.2
		LD_CAP_LST_PIO_CVN :DATE9.
		LD_TRM_END :DATE9.
		LD_TRM_BEG :DATE9.
		LI_GTR_NAT :1.
		LF_GTR_RFR :$12.
		LI_ELG_SPA :1.
		LD_GTE_LOS :DATE9.
		LA_SCL_CLS :8.2
		LA_CUR_ILG :8.2
		LA_ILG :8.2
		LD_PIF_RPT :DATE9.
		LA_NSI_OTS :7.2
		LD_NSI_ACR_THU :DATE9.
		LD_STA_LON10 :DATE9.
		LD_LON_ACL_ADD :DATE9.
		LD_LON_EFF_ADD :DATE9.
		LF_DOE_SCL_ORG :$8.
		LC_PCV_DIS_STA :$1.
		LC_RPR_TYP :$1.
		LF_RGL_CAT_LP19 :$7.
		LF_RGL_CAT_LP18 :$7.
		LF_RGL_CAT_LP17 :$7.
		LF_RGL_CAT_LP13 :$7.
		LF_RGL_CAT_LP12 :$7.
		LF_RGL_CAT_LP11 :$7.
		LF_RGL_CAT_LP10 :$7.
		LF_RGL_CAT_LP08 :$7.
		LF_RGL_CAT_LP07 :$7.
		LF_RGL_CAT_LP06 :$7.
		LF_RGL_CAT_LP05 :$7.
		LF_RGL_CAT_LP04 :$7.
		LF_RGL_CAT_LP03 :$7.
		LF_RGL_CAT_LP02 :$7.
		LF_RGL_CAT_LP01 :$7.
		LD_SCL_CLS_NTF :DATE9.
		LD_ILG_NTF :DATE9.
		LF_LON_CUR_OWN :$8.
		LF_LST_DTS_LN10 :DATETIME25.
		LC_STA_NEW_BR :$3.
		LC_SCY_PGA :$2.
		LD_SIN_LST_PD_PCV :DATE9.
		LD_SIN_ACR_THU_PCV :DATE9.
		LA_SIN_OTS_PCV :7.2
		IC_LON_PGM :$6.
		PF_MAJ_BCH :$10.
		PF_MNR_BCH :5.0
		IF_DOE_LDR :$8.
		IF_GTR :$6.
		LF_STU_SSN :$9.
		LD_LON_1_DSB :DATE9.
		LC_ACA_GDE_LEV :$2.
		LD_NEW_SYS_CVN :DATE9.
		LC_SCY_PGA_PGM_YR :$1.
		IC_HSP_CSE :$3.
		LI_TL4_793_XCL_CON :$1.
		LI_DFR_REQ_ON_APL :$1.
		LI_LN_PT_COM_APL :$1.
		LN_SEQ_RPR :2.
		LR_WIR_CON_LON :5.3
		LR_INT_RDC_PGM_DSU :5.3
		LI_1_TME_BR :$1.
		BF_SSN_RPR :$9.
		LC_ELG_RDC_PGM :$1.
		LD_ELG_RDC_PGM :DATE9.
		LC_RPD_SLE :$1.
		LR_ITR_ORG :5.3
		LC_ITR_TYP_ORG :$2.
		LC_RDC_PGM :$2.
		LC_TIR_GRP :$1.
		LD_SER_RSB_BEG :DATE9.
		LC_EFT_RDC :$1.
		LD_LTS_STS_BIL :DATE9.
		IF_TIR_PCE :$3.
		LF_RGL_CAT_LP20 :$7.
		LN_RDC_PGM_PAY_PCV :3.0
		LC_REA_PIF_PCV :$1.
		LD_FAT_PIF_TOL_PCV :DATE9.
		LA_FAT_PIF_TOL_PCV :9.2
		LI_RTE_RDC_ELG :$1.
		LD_LTE_FEE_ELG :DATE9.
		LA_LTE_FEE_OTS :7.2
		LD_LON_LTE_FEE_WAV :DATE9.
		LC_CUR_RDC_PGM_NME :$3.
		LI_RIR_SCY_ELG :$1.
		LD_END_RIR_DSQ_OVR :DATE9.
		LF_LON_ALT :$17.
		LN_LON_ALT_SEQ :2.
		LI_LDR_LST_RST_DSB :1.
		LC_ST_BR_RSD_APL :$2.
		LI_PIF_RPT_REQ :$1.
		LD_AMR_BEG :DATE9.
		LD_ORG_XPC_GRD :DATE9.
		LD_CON_LST_RPY_BEG :DATE9.
		LN_CON_MTH_DFR_FOR :4.0
		LD_LON_APL_RCV :DATE9.
		LR_SCL_SUB :6.3
		LI_BLL_PAY_SES_OVR :$1.
		LC_MPN_TYP :$1.
		LD_MPN_EXP :DATE9.
		LC_MPN_SRL_LON :$1.
		LC_MPN_REV_REA :$2.
		LF_ORG_RGN :$8.
		LC_CAM_LON_STA :$2.
		LD_DFR_FOR_END :DATE9.
		LC_DFR_FOR_TYP :$2.
		LF_CAM_DFR_SCL_ENR :$8.
		LD_DFR_FOR_BEG :DATE9.
		LD_CAM_DFR_INF_CER :DATE9.
		LI_BR_DET_RPD_XTN :$1.
		DD_DTH_VER :DATE9.
		DD_DSA_VER :DATE9.
		LI_CON_PAY_STP_PUR :$1.
		LD_FSE_CER_NTF :DATE9.
		LA_TOT_EDU_DET :10.2
		LI_LDR_BG_APL :$1.
		LD_RIR_CSC_BIL_STS :DATE9.
		LI_ESG :$1.
		LC_RIR_DSQ_REA :$2.
		LF_MN_MST_NTE :$11.
		LN_MN_MST_NTE_SEQ :2.
		LC_LON_SND_CHC :$1.
		LC_SST_LON10 :$1.
		LF_RGL_CAT_LP09 :$7.
		LI_MN_PSD_BS :$1.
		LF_CRD_RTE_SRE :$4.
		LF_ESG_SRC :$9.
		PC_PNT_YR :$7.
		LF_OWN_BND_ISS_TE1 :$8.
		LF_OWN_BND_ISS_TE2 :$8.
		LF_OWN_BND_ISS_TE3 :$8.
		LD_MPN_STM_SNT :DATE9.
		LI_MNT_BIL_RCP :1.
		LX_BS_POI :$4.
		LA_BS_POI :6.4
		LA_INT_FEE_URP_IRS :8.2
		LC_BR_ALW_SCL_DFR :$1.
		LD_BR_ALW_SCL_DFR :DATE9.
		LC_LON_DFR_SUB_TYP :$2.
		LD_FAT_PRI_BAL_ZRO :DATE9.
		LC_ST_SCL_ATD_APL :$2.
		LD_EFT_DSQ_NSF_LMT :DATE9.
		LD_CLM_PD :DATE9.
		LC_STP_PUR :$1.
		LD_CON_PAY_EFF :DATE9.
		LD_CON_PAY_APL :DATE9.
		LC_ESG :$1.
		LC_LON_RPE_CVN_REA :$1.
		LC_UDL_DSB_COF :$1.
		LI_BR_LT_HT :$1.
		LI_ALL_PAY_FLG_SPS :$1.
		LN_MFY_GRS_PAY :2.0
		LC_ESP_RPD_OPT_SEL :$2.
		LC_ELG_95_SPA_BIL :$1.
		LC_SGM_COS_PRC :$2.
		LD_GTR_DR_DCH_CER :DATE9.
		LD_RPD_ELY_CL_BEG :DATE9.
		LD_RPD_ELY_CL_END :DATE9.
		LF_GTR_RFR_XTN :$23.
		LA_MSC_FEE_OTS :12.2
		LA_MSC_FEE_PCV_OTS :12.2
		LF_LON_GRP_WI_BR :2.
		LC_TL4_IBR_ELG :$1.
		LD_LON_IBR_ENT :DATE9.
		LC_LON_IBR_RPY_TYP :$1.
		LI_BYP_COL_OUT_SRC :$1.
		LI_BR_GRP_RLP :$1.
		LI_OO_PST_ENR_DFR :$1.
		LD_OO_PST_ENR_DFR :DATE9.
		LF_FED_CLC_RSK :$6.
		LF_FED_FFY_1_DSB :$4.
		LF_PRV_GTR :$6.
		LC_FED_PGM_YR :$3.
		LA_INT_RCV_GOV :12.2
		LC_WOF_WUP_REA :$1.
		LC_VRS_ALT_APL :$4.
		LF_LON_DCV_CLI :$2.
		LN_LON_SEQ_DCV_CLI :2.
		LI_EDS_BKR_STP_PUR :$1.
		LF_EDS :$9.
		LD_EFF_LBR_RTE :DATE9.
		LA_STD_STD_PAY :12.2
		LI_FRC_IBR :$1.
		LC_STP_PUR_REA :$1.
		LD_IDR_ELG_CHG :DATE9.
		LC_IDR_ELG_CRI :$2.
	;
	%TRUNCAT1(51, BF_SSN);
RUN;

/*convert SAS dates to SQL Server datetime*/
DATA LN10;
	SET LN10;
		LD_LON_GTR = LD_LON_GTR * 86400;
		LD_PIF_PNT_RTN = LD_PIF_PNT_RTN * 86400;
		LD_PNT_SIG = LD_PNT_SIG * 86400;
		LD_END_GRC_PRD = LD_END_GRC_PRD * 86400;
		LD_CAP_LST_PIO_CVN = LD_CAP_LST_PIO_CVN * 86400;
		LD_TRM_END = LD_TRM_END * 86400;
		LD_TRM_BEG = LD_TRM_BEG * 86400;
		LD_GTE_LOS = LD_GTE_LOS * 86400;
		LD_PIF_RPT = LD_PIF_RPT * 86400;
		LD_NSI_ACR_THU = LD_NSI_ACR_THU * 86400;
		LD_STA_LON10 = LD_STA_LON10 * 86400;
		LD_LON_ACL_ADD = LD_LON_ACL_ADD * 86400;
		LD_LON_EFF_ADD = LD_LON_EFF_ADD * 86400;
		LD_SCL_CLS_NTF = LD_SCL_CLS_NTF * 86400;
		LD_ILG_NTF = LD_ILG_NTF * 86400;
		LD_SIN_LST_PD_PCV = LD_SIN_LST_PD_PCV * 86400;
		LD_SIN_ACR_THU_PCV = LD_SIN_ACR_THU_PCV * 86400;
		LD_LON_1_DSB = LD_LON_1_DSB * 86400;
		LD_NEW_SYS_CVN = LD_NEW_SYS_CVN * 86400;
		LD_ELG_RDC_PGM = LD_ELG_RDC_PGM * 86400;
		LD_SER_RSB_BEG = LD_SER_RSB_BEG * 86400;
		LD_LTS_STS_BIL = LD_LTS_STS_BIL * 86400;
		LD_FAT_PIF_TOL_PCV = LD_FAT_PIF_TOL_PCV * 86400;
		LD_LTE_FEE_ELG = LD_LTE_FEE_ELG * 86400;
		LD_LON_LTE_FEE_WAV = LD_LON_LTE_FEE_WAV * 86400;
		LD_END_RIR_DSQ_OVR = LD_END_RIR_DSQ_OVR * 86400;
		LD_AMR_BEG = LD_AMR_BEG * 86400;
		LD_ORG_XPC_GRD = LD_ORG_XPC_GRD * 86400;
		LD_CON_LST_RPY_BEG = LD_CON_LST_RPY_BEG * 86400;
		LD_LON_APL_RCV = LD_LON_APL_RCV * 86400;
		LD_MPN_EXP = LD_MPN_EXP * 86400;
		LD_DFR_FOR_END = LD_DFR_FOR_END * 86400;
		LD_DFR_FOR_BEG = LD_DFR_FOR_BEG * 86400;
		LD_CAM_DFR_INF_CER = LD_CAM_DFR_INF_CER * 86400;
		DD_DTH_VER = DD_DTH_VER * 86400;
		DD_DSA_VER = DD_DSA_VER * 86400;
		LD_FSE_CER_NTF = LD_FSE_CER_NTF * 86400;
		LD_RIR_CSC_BIL_STS = LD_RIR_CSC_BIL_STS * 86400;
		LD_MPN_STM_SNT = LD_MPN_STM_SNT * 86400;
		LD_BR_ALW_SCL_DFR = LD_BR_ALW_SCL_DFR * 86400;
		LD_FAT_PRI_BAL_ZRO = LD_FAT_PRI_BAL_ZRO * 86400;
		LD_EFT_DSQ_NSF_LMT = LD_EFT_DSQ_NSF_LMT * 86400;
		LD_CLM_PD = LD_CLM_PD * 86400;
		LD_CON_PAY_EFF = LD_CON_PAY_EFF * 86400;
		LD_CON_PAY_APL = LD_CON_PAY_APL * 86400;
		LD_GTR_DR_DCH_CER = LD_GTR_DR_DCH_CER * 86400;
		LD_RPD_ELY_CL_BEG = LD_RPD_ELY_CL_BEG * 86400;
		LD_RPD_ELY_CL_END = LD_RPD_ELY_CL_END * 86400;
		LD_LON_IBR_ENT = LD_LON_IBR_ENT * 86400;
		LD_OO_PST_ENR_DFR = LD_OO_PST_ENR_DFR * 86400;
		LD_EFF_LBR_RTE = LD_EFF_LBR_RTE * 86400;
		LD_IDR_ELG_CHG = LD_IDR_ELG_CHG * 86400;
RUN;

%COPYERROR;

%ENCHILADA
	(
		LN10,
		LN10_LON,
		BF_SSN  
		LN_SEQ,
		LC_STA_LON10  
		LI_FGV_PGM  
		LF_LON_SLE_PND  
		LA_CUR_PRI  
		LI_ELG_CPN_BOK  
		LA_LON_AMT_GTR  
		LD_LON_GTR  
		LD_PIF_PNT_RTN  
		LD_PNT_SIG  
		LC_INT_BIL_OPT  
		LI_CAP_ALW  
		LD_END_GRC_PRD  
		LN_MTH_GRC_PRD_DSC  
		LA_R78_INT_PD  
		LA_R78_INT_MAX  
		LD_CAP_LST_PIO_CVN  
		LD_TRM_END  
		LD_TRM_BEG  
		LI_GTR_NAT  
		LF_GTR_RFR  
		LI_ELG_SPA  
		LD_GTE_LOS  
		LA_SCL_CLS  
		LA_CUR_ILG  
		LA_ILG  
		LD_PIF_RPT  
		LA_NSI_OTS  
		LD_NSI_ACR_THU  
		LD_STA_LON10  
		LD_LON_ACL_ADD  
		LD_LON_EFF_ADD  
		LF_DOE_SCL_ORG  
		LC_PCV_DIS_STA  
		LC_RPR_TYP  
		LF_RGL_CAT_LP19  
		LF_RGL_CAT_LP18  
		LF_RGL_CAT_LP17  
		LF_RGL_CAT_LP13  
		LF_RGL_CAT_LP12  
		LF_RGL_CAT_LP11  
		LF_RGL_CAT_LP10  
		LF_RGL_CAT_LP08  
		LF_RGL_CAT_LP07  
		LF_RGL_CAT_LP06  
		LF_RGL_CAT_LP05  
		LF_RGL_CAT_LP04  
		LF_RGL_CAT_LP03  
		LF_RGL_CAT_LP02  
		LF_RGL_CAT_LP01  
		LD_SCL_CLS_NTF  
		LD_ILG_NTF  
		LF_LON_CUR_OWN  
		LF_LST_DTS_LN10  
		LC_STA_NEW_BR  
		LC_SCY_PGA  
		LD_SIN_LST_PD_PCV  
		LD_SIN_ACR_THU_PCV  
		LA_SIN_OTS_PCV  
		IC_LON_PGM  
		PF_MAJ_BCH  
		PF_MNR_BCH  
		IF_DOE_LDR  
		IF_GTR  
		LF_STU_SSN  
		LD_LON_1_DSB  
		LC_ACA_GDE_LEV  
		LD_NEW_SYS_CVN  
		LC_SCY_PGA_PGM_YR  
		IC_HSP_CSE  
		LI_TL4_793_XCL_CON  
		LI_DFR_REQ_ON_APL  
		LI_LN_PT_COM_APL  
		LN_SEQ_RPR  
		LR_WIR_CON_LON  
		LR_INT_RDC_PGM_DSU  
		LI_1_TME_BR  
		BF_SSN_RPR  
		LC_ELG_RDC_PGM  
		LD_ELG_RDC_PGM  
		LC_RPD_SLE  
		LR_ITR_ORG  
		LC_ITR_TYP_ORG  
		LC_RDC_PGM  
		LC_TIR_GRP  
		LD_SER_RSB_BEG  
		LC_EFT_RDC  
		LD_LTS_STS_BIL  
		IF_TIR_PCE  
		LF_RGL_CAT_LP20  
		LN_RDC_PGM_PAY_PCV  
		LC_REA_PIF_PCV  
		LD_FAT_PIF_TOL_PCV  
		LA_FAT_PIF_TOL_PCV  
		LI_RTE_RDC_ELG  
		LD_LTE_FEE_ELG  
		LA_LTE_FEE_OTS  
		LD_LON_LTE_FEE_WAV  
		LC_CUR_RDC_PGM_NME  
		LI_RIR_SCY_ELG  
		LD_END_RIR_DSQ_OVR  
		LF_LON_ALT  
		LN_LON_ALT_SEQ  
		LI_LDR_LST_RST_DSB  
		LC_ST_BR_RSD_APL  
		LI_PIF_RPT_REQ  
		LD_AMR_BEG  
		LD_ORG_XPC_GRD  
		LD_CON_LST_RPY_BEG  
		LN_CON_MTH_DFR_FOR  
		LD_LON_APL_RCV  
		LR_SCL_SUB  
		LI_BLL_PAY_SES_OVR  
		LC_MPN_TYP  
		LD_MPN_EXP  
		LC_MPN_SRL_LON  
		LC_MPN_REV_REA  
		LF_ORG_RGN  
		LC_CAM_LON_STA  
		LD_DFR_FOR_END  
		LC_DFR_FOR_TYP  
		LF_CAM_DFR_SCL_ENR  
		LD_DFR_FOR_BEG  
		LD_CAM_DFR_INF_CER  
		LI_BR_DET_RPD_XTN  
		DD_DTH_VER  
		DD_DSA_VER  
		LI_CON_PAY_STP_PUR  
		LD_FSE_CER_NTF  
		LA_TOT_EDU_DET  
		LI_LDR_BG_APL  
		LD_RIR_CSC_BIL_STS  
		LI_ESG  
		LC_RIR_DSQ_REA  
		LF_MN_MST_NTE  
		LN_MN_MST_NTE_SEQ  
		LC_LON_SND_CHC  
		LC_SST_LON10  
		LF_RGL_CAT_LP09  
		LI_MN_PSD_BS  
		LF_CRD_RTE_SRE  
		LF_ESG_SRC  
		PC_PNT_YR  
		LF_OWN_BND_ISS_TE1  
		LF_OWN_BND_ISS_TE2  
		LF_OWN_BND_ISS_TE3  
		LD_MPN_STM_SNT  
		LI_MNT_BIL_RCP  
		LX_BS_POI  
		LA_BS_POI  
		LA_INT_FEE_URP_IRS  
		LC_BR_ALW_SCL_DFR  
		LD_BR_ALW_SCL_DFR  
		LC_LON_DFR_SUB_TYP  
		LD_FAT_PRI_BAL_ZRO  
		LC_ST_SCL_ATD_APL  
		LD_EFT_DSQ_NSF_LMT  
		LD_CLM_PD  
		LC_STP_PUR  
		LD_CON_PAY_EFF  
		LD_CON_PAY_APL  
		LC_ESG  
		LC_LON_RPE_CVN_REA  
		LC_UDL_DSB_COF  
		LI_BR_LT_HT  
		LI_ALL_PAY_FLG_SPS  
		LN_MFY_GRS_PAY  
		LC_ESP_RPD_OPT_SEL  
		LC_ELG_95_SPA_BIL  
		LC_SGM_COS_PRC  
		LD_GTR_DR_DCH_CER  
		LD_RPD_ELY_CL_BEG  
		LD_RPD_ELY_CL_END  
		LF_GTR_RFR_XTN  
		LA_MSC_FEE_OTS  
		LA_MSC_FEE_PCV_OTS  
		LF_LON_GRP_WI_BR  
		LC_TL4_IBR_ELG  
		LD_LON_IBR_ENT  
		LC_LON_IBR_RPY_TYP  
		LI_BYP_COL_OUT_SRC  
		LI_BR_GRP_RLP  
		LI_OO_PST_ENR_DFR  
		LD_OO_PST_ENR_DFR  
		LF_FED_CLC_RSK  
		LF_FED_FFY_1_DSB  
		LF_PRV_GTR  
		LC_FED_PGM_YR  
		LA_INT_RCV_GOV  
		LC_WOF_WUP_REA  
		LC_VRS_ALT_APL  
		LF_LON_DCV_CLI  
		LN_LON_SEQ_DCV_CLI  
		LI_EDS_BKR_STP_PUR  
		LF_EDS  
		LD_EFF_LBR_RTE  
		LA_STD_STD_PAY  
		LI_FRC_IBR  
		LC_STP_PUR_REA  
		LD_IDR_ELG_CHG  
		LC_IDR_ELG_CRI  
/*		no filter*/
	);

%FINISH(SOURCE=LN10_LON);
