USE [UDW]
GO
/****** Object:  StoredProcedure [dbo].[GetPaymentAmountRPF]    Script Date: 5/2/2016 9:55:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[GetPaymentAmountRPF]
	@SSN CHAR(9),
	@EffectiveDate DATETIME
AS
SELECT DISTINCT TOP 1 
	FB10.LA_REQ_RDC_PAY AS RPF_Amount 
FROM 
	UDW..FB10_Forbearance FB10
	INNER JOIN UDW..PD10_Borrower PD10
		ON PD10.DF_SPE_ACC_ID = FB10.DF_SPE_ACC_ID
WHERE 
	FB10.LC_FOR_TYP = '31' 
	AND FB10.LC_FOR_STA = 'A' 
	AND FB10.LC_STA_FOR10 = 'A'
	AND FB10.LC_STA_LON60 = 'A'
	AND @EffectiveDate BETWEEN FB10.LD_FOR_BEG AND FB10.LD_FOR_END
	AND PD10.BF_SSN = @SSN

RETURN 0