--INSERT INTO CDW..CS_Transfer2
SELECT DISTINCT
	POP.BF_SSN,
	'DirectDebit' AS [POPULATION],
	SUM(CASE WHEN LN10.LC_FED_PGM_YR = 'LNC' THEN 1 ELSE 0 END) AS LNC_Count,
	SUM(CASE WHEN LN10.LC_FED_PGM_YR = 'DLO' THEN 1 ELSE 0 END) AS DLO_Count,
	NULL AS LNC_SaleId,
	NULL AS DLO_SaleId
FROM
	CDW..LN10_LON LN10
	INNER JOIN
	(
		SELECT DISTINCT
			LN10.BF_SSN,
			'DirectDebit' AS [POPULATION]
		FROM
			CDW..LN10_LON LN10
			INNER JOIN CDW..DW01_DW_CLC_CLU DW01
				ON DW01.BF_SSN = LN10.BF_SSN
				AND DW01.LN_SEQ = LN10.LN_SEQ
				AND DW01.WC_DW_LON_STA = '03'
			INNER JOIN CDW..LN83_EFT_TO_LON LN83
				ON LN83.BF_SSN = LN10.BF_SSN
				AND LN83.LN_SEQ = LN10.LN_SEQ
				AND LN83.LC_STA_LN83 = 'A'
				AND LN83.LD_EFT_EFF_END IS NULL --still active
			INNER JOIN CDW..BR30_BR_EFT BR30
				ON BR30.BF_SSN = LN83.BF_SSN
				AND BR30.BN_EFT_SEQ = LN83.BN_EFT_SEQ
				AND BR30.BC_EFT_STA = 'A'
				AND BR30.BN_EFT_DAY_DUE IN(1,2,3,4,22,23,24,25,26,27,28,29,30,31) --avoid 5th through 21st
			LEFT JOIN CDW..CS_Transfer2_Exclusions EX
				ON EX.BF_SSN = LN10.BF_SSN
			LEFT JOIN CDW..CS_Transfer1 T1
				ON T1.BF_SSN = LN10.BF_SSN
			LEFT JOIN CDW..CS_Transfer2 T2
				ON T2.BF_SSN = LN10.BF_SSN
		WHERE
			LN10.LC_STA_LON10 = 'R'
			AND LN10.LA_CUR_PRI > 0.00
			AND T2.BF_SSN IS NULL --dont re-add loans already added by IDR pop
			AND EX.BF_SSN IS NULL --dont include specific exclusion acccounts
			AND T1.BF_SSN IS NULL --dont re-add loans already IN THE FIRST TRANSFER
	) POP
		ON POP.BF_SSN = LN10.BF_SSN
WHERE
	LN10.LC_STA_LON10 = 'R'
	AND LN10.LA_CUR_PRI > 0.00
GROUP BY
	POP.BF_SSN