CREATE TABLE [dbo].[BORR_AmountDue] (
    [DF_SPE_ACC_ID] VARCHAR (10)    NOT NULL,
    [CUR_DUE]       NUMERIC (12, 2) NOT NULL,
    [PAST_DUE]      NUMERIC (12, 2) NOT NULL,
    [TOT_DUE]       NUMERIC (12, 2) NOT NULL,
    [TOT_DUE_FEE]   NUMERIC (12, 2) NOT NULL,
    CONSTRAINT [PK_BORR_AmountDue1] PRIMARY KEY CLUSTERED ([DF_SPE_ACC_ID] ASC) WITH (FILLFACTOR = 95)
);

