CREATE TABLE [dbo].[WK1J_LON_SLE_PLR_History] (
    [IF_LON_SLE]         VARCHAR (7)    NOT NULL,
    [ID_LON_SLE_LST_PLR] DATE           NOT NULL,
    [IT_SLE_LST_PLR]     TIME (0)       NOT NULL,
    [BF_SSN]             CHAR (9)       NOT NULL,
    [LN_SEQ]             SMALLINT       NOT NULL,
    [LA_CUR_PRI]         NUMERIC (8, 2) NULL,
    [LA_NSI_OTS]         NUMERIC (7, 2) NULL,
    [LA_LTE_FEE_OTS]     NUMERIC (7, 2) NULL,
    CONSTRAINT [PK_WK1J_LON_SLE_PLR_History] PRIMARY KEY CLUSTERED ([IF_LON_SLE] ASC, [ID_LON_SLE_LST_PLR] ASC, [IT_SLE_LST_PLR] ASC, [BF_SSN] ASC, [LN_SEQ] ASC) WITH (FILLFACTOR = 95)
);

