CREATE PROCEDURE [espqueues].[HasOpenQueueTask]
	@Arc VARCHAR(5),
	@BorrowerSsn CHAR(9)
AS

DECLARE @Queue CHAR(2) = (SELECT DISTINCT WF_QUE FROM UDW..AC10_ACT_REQ WHERE PF_REQ_ACT = @Arc)

SELECT
	CASE 
		WHEN @Queue IS NOT NULL AND EXISTS(SELECT WN_CTL_TSK FROM UDW..WQ20_TSK_QUE WHERE WF_QUE = @Queue AND BF_SSN = @BorrowerSsn AND WC_STA_WQUE20 IN ('U', 'A', 'H')) THEN 1 
		ELSE 0 
	END AS TaskExists

RETURN 0
