//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegentsApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegentsApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _2012_Header_No_Back {
            get {
                object obj = ResourceManager.GetObject("_2012_Header_No_Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=ROSS-SQL;Initial Catalog=RegentsApp;Persist Security Info=True;User ID=procauto;Password=procauto.
        /// </summary>
        internal static string ConnStringLive {
            get {
                return ResourceManager.GetString("ConnStringLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=ROSS-SQL;Initial Catalog=RegentsAppTest;Persist Security Info=True;User ID=procauto;Password=procauto.
        /// </summary>
        internal static string ConnStringTest {
            get {
                return ResourceManager.GetString("ConnStringTest", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap get_adobe_reader {
            get {
                object obj = ResourceManager.GetObject("get_adobe_reader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Header {
            get {
                object obj = ResourceManager.GetObject("Header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Header_No_Back {
            get {
                object obj = ResourceManager.GetObject("Header_No_Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Regents&apos; Scholarship&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///
        ///
        ///img
        ///{
        ///	border-style:none;
        ///}
        ///
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;text-align: left; width: 600px;&quot;&gt;
        ///        &lt;p&gt;
        ///            Greetings [FirstName],&lt;/p&gt;
        ///        &lt;p&gt;
        ///            Thank you for completing the online portion of the Regents&amp;#39; Scholarship application
        ///            for 2011 high school graduates. Please be advised in order to complete your application,
        ///            you are responsible for s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Regents_Email {
            get {
                return ResourceManager.GetString("Regents_Email", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap USHE {
            get {
                object obj = ResourceManager.GetObject("USHE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap USHE_Logo_CMYK {
            get {
                object obj = ResourceManager.GetObject("USHE_Logo_CMYK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
