/*
LOANS GUARANTEED

Lists gross guaranteed numbers and amounts up to the current date.

*/


/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
%LET RPTLIB = %SYSGET(reportdir);
FILENAME REPORT2 "&RPTLIB/ULWG04.LWG04R2";*/

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
OPTIONS MPRINT SYMBOLGEN;

PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE CUMGUARS AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT
	COUNT(A.AF_APL_ID||A.AF_APL_ID_SFX)		AS NUMBER,				
	SUM(A.aa_gte_lon_amt)					AS GROSS,
	SUM(A.aa_tot_rfd)						AS REFUND,
	SUM(A.aa_tot_can)						AS CANCEL,
	A.ac_lon_typ							AS TYPE
FROM	OLWHRM1.GA10_LON_APP A			

WHERE	A.ac_prc_sta = 'A' /*AND
		(A.aa_tot_can IS NULL AND A.aa_gte_lon_amt - A.aa_tot_rfd > 0 OR
		 A.aa_tot_can IS NOT NULL AND A.aa_gte_lon_amt - A.aa_tot_rfd - A.aa_tot_can > 0)*/

GROUP BY A.ac_lon_typ
);
DISCONNECT FROM DB2;

ENDRSUBMIT;
DATA WORKLOCL.CUMGUARS;
	SET WORKLOCL.CUMGUARS;
	IF CANCEL = . THEN CANCEL = 0;
	NET = GROSS - REFUND - CANCEL;
RUN;
DATA _NULL_;
     EFFDT = PUT(TODAY()-1, MMDDYY10.);
     CALL SYMPUT('EFFDATE',EFFDT);
RUN;
/*PROC PRINTTO PRINT=REPORT2;
RUN;*/
OPTIONS CENTER NODATE PAGENO=1 LS=80;
PROC PRINT NOOBS DATA = WORKLOCL.CUMGUARS;
VAR	TYPE
	NUMBER
	GROSS
	REFUND
	CANCEL
	NET;
SUM	NUMBER
	GROSS
	REFUND
	CANCEL
	NET;
FORMAT	GROSS DOLLAR15.
		REFUND DOLLAR13.
		CANCEL DOLLAR13.
		NET DOLLAR15.
		NUMBER COMMA10.0;
TITLE1 'CUMULATIVE GUARANTEES';
TITLE2 "AS OF &EFFDATE";
FOOTNOTE	'JOB = UTLWG04     REPORT = ULWG04.LWG04R2';
RUN;
