SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
DECLARE @TODAY AS DATE = CONVERT(DATE, GETDATE())

--REPORT 1 In School
SELECT
	YEAR(SEPDT.LD_SCL_SPR) AS SEPYR,
	MONTH(SEPDT.LD_SCL_SPR) AS SEPMO,
	ROW_NUMBER() OVER(ORDER BY 	YEAR(SEPDT.LD_SCL_SPR),	MONTH(SEPDT.LD_SCL_SPR)) AS [MONTH],
	COUNT(DISTINCT SEPDT.BF_SSN) AS BORROWERS
FROM -- borrower separation date
	(
	SELECT
		DISTINCT
		DW01.BF_SSN,
		SD10.LD_SCL_SPR --separation date
	FROM
		CDW..LN10_LON LN10
		INNER JOIN CDW..DW01_DW_CLC_CLU DW01
			ON LN10.BF_SSN = DW01.BF_SSN
			AND LN10.LN_SEQ = DW01.LN_SEQ
		INNER JOIN CDW..LN13_LON_STU_OSD LN13
			ON DW01.BF_SSN = LN13.BF_SSN
			AND DW01.LN_SEQ = LN13.LN_SEQ
		INNER JOIN CDW..SD10_STU_SPR SD10
			ON LN13.LF_STU_SSN = SD10.LF_STU_SSN
			AND LN13.LN_STU_SPR_SEQ = SD10.LN_STU_SPR_SEQ
	WHERE
		LN10.LA_CUR_PRI > 0.00
		AND LN10.LC_STA_LON10 = 'R'
		AND DW01.WC_DW_LON_STA = '02'
		AND LN13.LC_STA_LON13 = 'A'
		AND SD10.LC_STA_STU10 = 'A'
		AND CONVERT(DATE,SD10.LD_SCL_SPR) >= @TODAY
		AND CONVERT(DATE,SD10.LD_SCL_SPR) < DATEADD(MONTH, 47, @TODAY) -- limit results to 48 months
	) SEPDT --separation date
GROUP BY
	YEAR(SEPDT.LD_SCL_SPR),
	MONTH(SEPDT.LD_SCL_SPR)
ORDER BY 
	YEAR(SEPDT.LD_SCL_SPR),
	MONTH(SEPDT.LD_SCL_SPR)
	

--REPORT 2 In Grace
SELECT
	YEAR(LN10.LD_END_GRC_PRD) AS GRCYR,
	MONTH(LN10.LD_END_GRC_PRD) AS GRCMO,
	ROW_NUMBER() OVER(ORDER BY 	YEAR(LN10.LD_END_GRC_PRD),	MONTH(LN10.LD_END_GRC_PRD)) AS [MONTH],
	COUNT(DISTINCT LN10.BF_SSN) AS BORROWERS
FROM
	CDW..LN10_LON LN10
	INNER JOIN CDW..DW01_DW_CLC_CLU DW01
		ON LN10.BF_SSN = DW01.BF_SSN
		AND LN10.LN_SEQ = DW01.LN_SEQ
WHERE
	LN10.LA_CUR_PRI > 0.00
	AND LN10.LC_STA_LON10 = 'R'
	AND DW01.WC_DW_LON_STA = '01'
	AND CONVERT(DATE,LN10.LD_END_GRC_PRD) >= @TODAY
	AND CONVERT(DATE,LN10.LD_END_GRC_PRD) <= DATEADD(MONTH, 5, @TODAY) -- limit results to 6 months
GROUP BY
	YEAR(LN10.LD_END_GRC_PRD),
	MONTH(LN10.LD_END_GRC_PRD)
ORDER BY
	YEAR(LN10.LD_END_GRC_PRD),
	MONTH(LN10.LD_END_GRC_PRD)

--REPORT 3 In Repayment
SELECT
	RPS.MonthsLeftBorr,
	COUNT(DISTINCT LN10.BF_SSN) AS BORROWERS
FROM
	CDW..LN10_LON LN10
	INNER JOIN CDW..DW01_DW_CLC_CLU DW01
		ON LN10.BF_SSN = DW01.BF_SSN
		AND LN10.LN_SEQ = DW01.LN_SEQ
	INNER JOIN --months left borrower in repayment
		(
			SELECT
				BF_SSN,
				MAX(TermsToDate - GradationMonths) AS MonthsLeftBorr
			FROM
				CDW.calc.RepaymentSchedules
			GROUP BY
				BF_SSN
		) RPS
			ON LN10.BF_SSN = RPS.BF_SSN
WHERE
	LN10.LA_CUR_PRI > 0.00
	AND LN10.LC_STA_LON10 = 'R'
	AND DW01.WC_DW_LON_STA = '03'
	AND RPS.MonthsLeftBorr BETWEEN 1 AND 48 -- limit results to 48 months
GROUP BY
	RPS.MonthsLeftBorr
ORDER BY
	RPS.MonthsLeftBorr


--REPORT 4 In Deferment
SELECT
	YEAR(LN50.LD_DFR_END) AS DEFYR,
	MONTH(LN50.LD_DFR_END) AS DEFMO,
	ROW_NUMBER() OVER(ORDER BY 	YEAR(LN50.LD_DFR_END),	MONTH(LN50.LD_DFR_END)) AS [MONTH],
	COUNT(DISTINCT LN10.BF_SSN) AS BORROWERS
FROM
	CDW..LN10_LON LN10
	INNER JOIN CDW..DW01_DW_CLC_CLU DW01
		ON LN10.BF_SSN = DW01.BF_SSN
		AND LN10.LN_SEQ = DW01.LN_SEQ
	INNER JOIN CDW..LN50_BR_DFR_APV LN50
		ON LN10.BF_SSN = LN50.BF_SSN
		AND LN10.LN_SEQ = LN50.LN_SEQ
	INNER JOIN CDW..DF10_BR_DFR_REQ DF10
		ON LN50.BF_SSN = DF10.BF_SSN
		AND LN50.LF_DFR_CTL_NUM = DF10.LF_DFR_CTL_NUM
WHERE
	LN10.LA_CUR_PRI > 0.00
	AND LN10.LC_STA_LON10 = 'R'
	AND DW01.WC_DW_LON_STA = '04'
	AND LN50.LC_DFR_RSP != '003'
	AND LN50.LC_STA_LON50 = 'A'
	AND DF10.LC_DFR_STA = 'A'
	AND DF10.LC_STA_DFR10 = 'A'
	AND CONVERT(DATE,LN50.LD_DFR_BEG) <= @TODAY
	AND CONVERT(DATE,LN50.LD_DFR_END) >= @TODAY
	AND CONVERT(DATE,LN50.LD_DFR_END) <= DATEADD(MONTH, 11, @TODAY)  -- limit results to 12 months
GROUP BY
	YEAR(LN50.LD_DFR_END),
	MONTH(LN50.LD_DFR_END)
ORDER BY
	YEAR(LN50.LD_DFR_END),
	MONTH(LN50.LD_DFR_END)


--REPORT 5 In Forbearance
SELECT
	YEAR(LN60.LD_FOR_END) AS FORYR,
	MONTH(LN60.LD_FOR_END) AS FORMO,
	ROW_NUMBER() OVER(ORDER BY 	YEAR(LN60.LD_FOR_END),	MONTH(LN60.LD_FOR_END)) AS [MONTH],
	COUNT(DISTINCT LN10.BF_SSN) AS BORROWERS
FROM
	CDW..LN10_LON LN10
	INNER JOIN CDW..DW01_DW_CLC_CLU DW01
		ON LN10.BF_SSN = DW01.BF_SSN
		AND LN10.LN_SEQ = DW01.LN_SEQ
	INNER JOIN CDW..LN60_BR_FOR_APV LN60
		ON LN10.BF_SSN = LN60.BF_SSN
		AND LN10.LN_SEQ = LN60.LN_SEQ
	INNER JOIN CDW..FB10_BR_FOR_REQ FB10
		ON LN60.BF_SSN = FB10.BF_SSN
		AND LN60.LF_FOR_CTL_NUM = FB10.LF_FOR_CTL_NUM
WHERE
	LN10.LA_CUR_PRI > 0.00
	AND LN10.LC_STA_LON10 = 'R'
	AND DW01.WC_DW_LON_STA = '05'
	AND LN60.LC_FOR_RSP != '003'
	AND LN60.LC_STA_LON60 = 'A'
	AND FB10.LC_FOR_STA = 'A'
	AND FB10.LC_STA_FOR10 = 'A'
	AND CONVERT(DATE,LN60.LD_FOR_BEG) <= @TODAY
	AND CONVERT(DATE,LN60.LD_FOR_END) >= @TODAY
	AND CONVERT(DATE,LN60.LD_FOR_END) <= DATEADD(MONTH, 11, @TODAY) -- limit results to 12 months
GROUP BY
	YEAR(LN60.LD_FOR_END),
	MONTH(LN60.LD_FOR_END)
ORDER BY
	YEAR(LN60.LD_FOR_END),
	MONTH(LN60.LD_FOR_END)
