/*UTLWQ04 DISBURSEMENTS CHANGED TO BE GUARANTY + 2 YEARS*/
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/ULWQ04.LWQ04R2";
libname  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=work  ;
RSUBMIT;
OPTIONS NOCENTER NODATE NONUMBER LS=132;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE DSB2YR AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT integer(A.DF_PRS_ID_BR) as SSN
	,B.AF_APL_ID||B.AF_APL_ID_SFX as CLUID
	,B.AC_LON_TYP
	,B.AD_PRC
	,C.AC_DSB_ADJ
	,C.AD_DSB_ADJ
	,C.AF_LST_USR_GA11
	,D.DF_SPE_ACC_ID
FROM  OLWHRM1.GA01_APP A 
INNER JOIN OLWHRM1.GA10_LON_APP B
	ON A.AF_APL_ID = B.AF_APL_ID
INNER JOIN OLWHRM1.GA11_LON_DSB_ATY C
	ON B.AF_APL_ID = C.AF_APL_ID
	AND B.AF_APL_ID_SFX = C.AF_APL_ID_SFX
INNER JOIN OLWHRM1.PD01_PDM_INF D
	ON A.DF_PRS_ID_BR = D.DF_PRS_ID
WHERE B.AC_PRC_STA = 'A'
AND C.AC_DSB_ADJ IN ('A','E')
AND C.AC_DSB_ADJ_STA = 'A'
AND DAYS(C.AD_DSB_ADJ) > DAYS(B.AD_PRC) + 730
ORDER BY A.DF_PRS_ID_BR, B.AF_APL_ID||B.AF_APL_ID_SFX
);
DISCONNECT FROM DB2;
endrsubmit  ;

DATA DSB2YR; 
SET WORKLOCL.DSB2YR; 
RUN;

PROC PRINTTO PRINT=REPORT2 NEW;
RUN;
OPTIONS CENTER NODATE NUMBER PAGENO=1 LS=126 /*LS=132*/;
PROC PRINT NOOBS SPLIT='/' DATA=DSB2YR WIDTH=UNIFORM WIDTH=MIN N='TOTAL:  ';
VAR DF_SPE_ACC_ID	AC_LON_TYP AD_PRC AC_DSB_ADJ AD_DSB_ADJ AF_LST_USR_GA11;
LABEL DF_SPE_ACC_ID="ACCT #" AC_LON_TYP="LOAN TYPE" AD_PRC="GUARANTY DATE"
AC_DSB_ADJ="DISBURSEMENT CODE" AD_DSB_ADJ="DISBURSEMENT DATE"
AF_LST_USR_GA11="LAST USER TO UPDATE";
FORMAT SSN SSN11. AD_PRC AD_DSB_ADJ MMDDYY10.;
TITLE "DISBURSEMENTS CHANGED TO BE GUARANTY + 2 YEARS";
FOOTNOTE  'JOB = UTLWQ04     REPORT = ULWQ04.LWQ04R2';
RUN;
PROC PRINTTO;
RUN;
