//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public Attribute()
        {
            this.AttributeAllowedValues = new HashSet<AttributeAllowedValue>();
            this.AttributeAllowedValuesHistories = new HashSet<AttributeAllowedValuesHistory>();
            this.EntityAttributeValues = new HashSet<EntityAttributeValue>();
            this.EntityAttributeValuesHistories = new HashSet<EntityAttributeValuesHistory>();
            this.EntityTypeAttributes = new HashSet<EntityTypeAttribute>();
            this.RoleAttributePermissions = new HashSet<RoleAttributePermission>();
        }
    
        public int AttributeId { get; set; }
        public string AttributeDescription { get; set; }
        public int AttributeDataTypeId { get; set; }
        public int AttributeSelectionTypeId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> InactivatedAt { get; set; }
        public Nullable<int> InactivatedBy { get; set; }
        public string AttributeLongDescription { get; set; }
        public Nullable<bool> InternalActive { get; set; }
    
        public virtual ICollection<AttributeAllowedValue> AttributeAllowedValues { get; set; }
        public virtual ICollection<AttributeAllowedValuesHistory> AttributeAllowedValuesHistories { get; set; }
        public virtual AttributeDataType AttributeDataType { get; set; }
        public virtual AttributeSelectionType AttributeSelectionType { get; set; }
        public virtual ICollection<EntityAttributeValue> EntityAttributeValues { get; set; }
        public virtual ICollection<EntityAttributeValuesHistory> EntityAttributeValuesHistories { get; set; }
        public virtual ICollection<EntityTypeAttribute> EntityTypeAttributes { get; set; }
        public virtual ICollection<RoleAttributePermission> RoleAttributePermissions { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual Entity Entity1 { get; set; }
    }
}
