//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeAllowedValuesHistory
    {
        public int AttributeAllowedValuesHistoryId { get; set; }
        public int AttributeAllowedValueId { get; set; }
        public int AttributeId { get; set; }
        public int ValueId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> InactivatedAt { get; set; }
        public Nullable<int> InactivatedBy { get; set; }
        public int Action { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Value Value { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual Entity Entity1 { get; set; }
    }
}
