//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeDataType
    {
        public AttributeDataType()
        {
            this.Attributes = new HashSet<Attribute>();
        }
    
        public int AttributeDataTypeId { get; set; }
        public string AttributeDataTypeDescription { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> InactivatedAt { get; set; }
        public Nullable<int> InactivatedBy { get; set; }
        private Nullable<bool> InternalActive { get; set; }
    
        public virtual ICollection<Attribute> Attributes { get; set; }
    }
}
