//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Value
    {
        public Value()
        {
            this.AttributeAllowedValues = new HashSet<AttributeAllowedValue>();
            this.AttributeAllowedValuesHistories = new HashSet<AttributeAllowedValuesHistory>();
            this.EntityAttributeValues = new HashSet<EntityAttributeValue>();
            this.EntityAttributeValuesHistories = new HashSet<EntityAttributeValuesHistory>();
        }
    
        public int ValueId { get; set; }
        public string StringValue { get; set; }
    
        public virtual ICollection<AttributeAllowedValue> AttributeAllowedValues { get; set; }
        public virtual ICollection<AttributeAllowedValuesHistory> AttributeAllowedValuesHistories { get; set; }
        public virtual ICollection<EntityAttributeValue> EntityAttributeValues { get; set; }
        public virtual ICollection<EntityAttributeValuesHistory> EntityAttributeValuesHistories { get; set; }
    }
}
