CREATE PROCEDURE [verforbfed].[BorrowerHasSpousalLoans]
	@Ssn CHAR(9)
AS
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT 
		CAST(CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END AS BIT)
	FROM
		LN10_LON LN10
	WHERE
		LN10.LC_STA_LON10 = 'R'
		AND 
		LN10.LA_CUR_PRI > 0
		AND 
		(
			DB_NAME() = 'CDW' AND LN10.IC_LON_PGM IN ('DLSSPL ','DLUSPL')
			OR
			DB_NAME() = 'UDW' AND LN10.IC_LON_PGM IN ('SUBSPC','UNSPC')
		)
		AND
		LN10.BF_SSN = @Ssn


RETURN 0
