CREATE TABLE [dbo].[DAT_BorrowerDataInvolved] (
    [TicketNumber]                              BIGINT        NOT NULL,
    [TicketType]                                VARCHAR (50)  NOT NULL,
    [Name]                                      VARCHAR (100) NULL,
    [AccountNumber]                             VARCHAR (10)  NULL,
    [State]                                     CHAR (2)      NULL,
    [DataRegion]                                VARCHAR (15)  NOT NULL,
    [BorrowerInformationIsVerified]             BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_BorrowerInformationIsVerified] DEFAULT ((0)) NOT NULL,
    [NotifierKnowsPiiOwner]                     BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_NotifierKnowsPiiOwner] DEFAULT ((0)) NOT NULL,
    [NotifierRelationshipToPiiOwner]            VARCHAR (50)  NULL,
    [AddressWasReleased]                        BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_AddressWasReleased] DEFAULT ((0)) NOT NULL,
    [BankAccountNumbersWereReleased]            BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_BankAccountNumbersWereReleased] DEFAULT ((0)) NOT NULL,
    [CreditReportOrScoreWasReleased]            BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_CreditReportOrScoreWasReleased] DEFAULT ((0)) NOT NULL,
    [DateOfBirthWasReleased]                    BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_DateOfBirthWasReleased] DEFAULT ((0)) NOT NULL,
    [EmployeeIdNumberWasReleased]               BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_EmployeeIdNumberWasReleased] DEFAULT ((0)) NOT NULL,
    [EmployerIdNumberWasReleased]               BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_EmployerIdNumberWasReleased] DEFAULT ((0)) NOT NULL,
    [LoanAmountsOrBalancesWereReleased]         BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_LoanAmountsOrBalancesWereReleased] DEFAULT ((0)) NOT NULL,
    [LoanApplicationsWereReleased]              BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_LoanApplicationsWereReleased] DEFAULT ((0)) NOT NULL,
    [LoanIdsOrNumbersWereReleased]              BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_LoanIdsOrNumbersWereReleased] DEFAULT ((0)) NOT NULL,
    [LoanPaymentHistoriesWereReleased]          BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_LoanPaymentHistoriesWereReleased] DEFAULT ((0)) NOT NULL,
    [MedicalOrConditionalDisabilityWasReleased] BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_MedicalOrConditionalDisabilityWasReleased] DEFAULT ((0)) NOT NULL,
    [PayoffAmountsWereReleased]                 BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_PayoffAmountsWereReleased] DEFAULT ((0)) NOT NULL,
    [PhoneNumberWasReleased]                    BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_PhoneNumberWasReleased] DEFAULT ((0)) NOT NULL,
    [PromissoryNotesWereReleased]               BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_PromissoryNotesWereReleased] DEFAULT ((0)) NOT NULL,
    [SocialSecurityNumbersWereReleased]         BIT           CONSTRAINT [DF_DAT_BorrowerDataInvolved_SocialSecurityNumbersWereReleased] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_DAT_BorrowerDataInvolved] PRIMARY KEY CLUSTERED ([TicketNumber] ASC, [TicketType] ASC),
    CONSTRAINT [FK_DAT_BorrowerDataInvolved_DAT_Ticket] FOREIGN KEY ([TicketNumber], [TicketType]) REFERENCES [dbo].[DAT_Ticket] ([TicketNumber], [TicketType]) ON UPDATE CASCADE,
    CONSTRAINT [FK_DAT_BorrowerDataInvolved_LST_Region] FOREIGN KEY ([DataRegion]) REFERENCES [dbo].[LST_Region] ([Region]) ON UPDATE CASCADE
);

