/*UTLWG13 - PLUS LOANS IN REPAYMENT BUT NOT FULLY DISBURSED*/
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/ULWG13.LWG13R2";
libname  WORKLOCL  REMOTE  SERVER=DUSTER  SLIBREF=work  ;
RSUBMIT;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE G13 AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT
INTEGER(A.BF_SSN) AS BF_SSN
,B.DM_PRS_1
,B.DM_PRS_LST
,A.LN_SEQ
,A.IC_LON_PGM
FROM OLWHRM1.LN10_LON A 
INNER JOIN OLWHRM1.PD10_PRS_NME B
	ON A.BF_SSN = B.DF_PRS_ID
INNER JOIN OLWHRM1.DW01_DW_CLC_CLU C
	ON A.BF_SSN = C.BF_SSN
	AND A.LN_SEQ = C.LN_SEQ
INNER JOIN OLWHRM1.LN15_DSB D
	ON A.BF_SSN = D.BF_SSN
	AND A.LN_SEQ = D.LN_SEQ
WHERE A.IC_LON_PGM IN ('PLUS','PLUSGB')
AND C.WC_DW_LON_STA = '03' /*IN REPAYMENT*/
AND D.LC_STA_LON15 IN ('1','3') /*ACTIVE OR ACTIVE/REISSUE ROW*/
AND D.LC_DSB_TYP = '1' /*ANTICIPATED DISB*/
AND (D.LD_DSB_CAN IS NULL
	OR D.LA_DSB_CAN <> D.LA_DSB)
AND A.LC_STA_LON10 = 'R'
);
DISCONNECT FROM DB2;

PROC SORT DATA=G13;
BY IC_LON_PGM BF_SSN LN_SEQ;
RUN;

endrsubmit  ;
DATA G13; 
SET WORKLOCL.G13; 
RUN;

DATA _NULL_;
CALL SYMPUT('RUNDATE',PUT(INTNX('DAY',TODAY(),0,'beginning'), MMDDYY10.));
RUN;

PROC PRINTTO PRINT=REPORT2 NEW;
RUN;
TITLE 'PLUS & PLUSGB LOANS IN REPAYMENT BUT NOT FULLY DISBURSED';
TITLE2 "RUN DATE:  &RUNDATE";

PROC CONTENTS DATA=G13 OUT=EMPTYSET NOPRINT;
DATA _NULL_;
SET EMPTYSET;
FILE PRINT;
IF  NOBS=0 AND _N_ =1 THEN DO;
	PUT // /*132*/126*'-';
	PUT      ////////
		@51 '**** NO OBSERVATIONS FOUND ****';
	PUT ////////
		@57 '-- END OF REPORT --';
	PUT ////////////////
		@46 "JOB = UTLWG13     REPORT = ULWG13.LWG13R2";
	END;
RETURN;
FOOTNOTE  'JOB = UTLWG13     REPORT = ULWG13.LWG13R2';
run;

OPTIONS CENTER NODATE NUMBER PAGENO=1 LS=/*132*/126;
PROC PRINT NOOBS SPLIT='/' DATA=G13 WIDTH=UNIFORM WIDTH=MIN;
VAR BF_SSN DM_PRS_1 DM_PRS_LST LN_SEQ;
LABEL BF_SSN="BORROWER SSN" DM_PRS_1="FIRST NAME" 
DM_PRS_LST="LAST NAME" LN_SEQ="LOAN SEQUENCE";
FORMAT BF_SSN SSN11.;
FOOTNOTE  'JOB = UTLWG13     REPORT = ULWG13.LWG13R2';
RUN;

PROC PRINTTO;
RUN;
