/*===============================================*/
/*UTLWBK8 BANKRUPTCY ACCOUNT AND TWO OPEN RECORDS*/
/*===============================================*/
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/ULWBK8.LWBK8RZ";
FILENAME REPORT2 "&RPTLIB/ULWBK8.LWBK8R2";

DATA _NULL_;
     CALL SYMPUT('RUNDT',PUT(INTNX('DAY',TODAY(),0,'BEGINNING'), MMDDYYD10.));
RUN;
LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;

%MACRO SQLCHECK (SQLRPT= );
%IF &SQLXRC NE 0 %THEN %DO;
	FILENAME REPORTZ "&RPTLIB/&SQLRPT";
	DATA _NULL_;
    FILE REPORTZ NOTITLES;
    PUT @01 " ********************************************************************* "
      / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
      / @01 " ****  THE SAS LOG IN &SQLRPT SHOULD BE REVIEWED.          **** "       
      / @01 " ********************************************************************* "
      / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
      / @01 " ****  &SQLXMSG   **** "
      / @01 " ********************************************************************* ";
	RUN;
%END;
%MEND;

PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE BATOBR AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT B.BF_SSN
	,C.DF_SPE_ACC_ID
	,B.LF_CLM_ID
	,A.AF_APL_ID||A.AF_APL_ID_SFX AS CLUID
	,A.LD_BKR_FIL
	,A.LF_BKR_DKT
	,A.LC_BKR_STA
	,DATE(A.LF_LST_DTS_DC18) AS ACT_DATE
	,A.LF_LST_USR_DC18
FROM OLWHRM1.DC18_BKR A
INNER JOIN OLWHRM1.DC01_LON_CLM_INF B
	ON A.AF_APL_ID = B.AF_APL_ID
	AND A.AF_APL_ID_SFX = B.AF_APL_ID_SFX
	AND A.LF_CRT_DTS_DC10 = B.LF_CRT_DTS_DC10
INNER JOIN OLWHRM1.PD01_PDM_INF C
	ON B.BF_SSN = C.DF_PRS_ID
WHERE A.LC_BKR_STA IN ('01','06')
	AND B.LF_CLM_ID != ''
FOR READ ONLY WITH UR
);

DISCONNECT FROM DB2;

/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>>  ;  * INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK (SQLRPT=ULWBK8.LWBK8RZ);*/
/*QUIT;*/

ENDRSUBMIT;

DATA BATOBR1 BATOBR6;
SET WORKLOCL.BATOBR;
	IF LC_BKR_STA = '01' THEN OUTPUT BATOBR1;
	IF LC_BKR_STA = '06' THEN OUTPUT BATOBR6;
RUN;

PROC SQL;
CREATE TABLE BATOBR_FINAL AS
SELECT DISTINCT A.*
FROM BATOBR1 A
	INNER JOIN BATOBR6 B 
		ON A.DF_SPE_ACC_ID = B.DF_SPE_ACC_ID
		AND A.LD_BKR_FIL = B.LD_BKR_FIL
		AND A.LF_BKR_DKT = B.LF_BKR_DKT;
QUIT;

PROC SORT DATA=BATOBR_FINAL;
BY DF_SPE_ACC_ID;
RUN;

DATA _NULL_;
SET BATOBR_FINAL ;
LENGTH DESCRIPTION $600.;
USER = LF_LST_USR_DC18;
ACT_DT = ACT_DATE;
DESCRIPTION = CATX(',',
		DF_SPE_ACC_ID,
		LF_CLM_ID,
		CLUID,
		PUT(LD_BKR_FIL, MMDDYY10.),
		LF_BKR_DKT
);
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
FORMAT USER $10. ;
FORMAT ACT_DT MMDDYY10. ;
FORMAT DESCRIPTION $600. ;
IF _N_ = 1 THEN DO;
	PUT "USER,ACT_DT,DESCRIPTION";
END;
DO;
   PUT USER $ @;
   PUT ACT_DT @;
   PUT DESCRIPTION $ ;
END;
RUN;
