*--------------------------------*
|UTLWI04 BANKKRUPTCY CASE NUMBER |
*--------------------------------*;
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/ULWI04.LWI04R2";
FILENAME REPORTZ "&RPTLIB/ULWI04.LWI04RZ";
DATA _NULL_;
     CALL SYMPUT('DVAL',"'"||PUT(INTNX('YEAR',TODAY(),-10,'S'), MMDDYYD10.)||"'");
RUN;
%SYSLPUT DVAL = &DVAL;
LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
%MACRO SQLCHECK (SQLRPT= );
%IF &SQLXRC NE 0 %THEN %DO;
	DATA _NULL_;
    FILE REPORTZ NOTITLES;
    PUT @01 " ********************************************************************* "
      / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
      / @01 " ****  THE SAS LOG IN &SQLRPT SHOULD BE REVIEWED.          **** "       
      / @01 " ********************************************************************* "
      / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
      / @01 " ****  &SQLXMSG   **** "
      / @01 " ********************************************************************* ";
	RUN;
%END;
%MEND;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE OLBK AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT C.DF_SPE_ACC_ID
	,C.DM_PRS_1
	,C.DM_PRS_LST
	,B.LF_BKR_DKT AS BK_CASE
FROM OLWHRM1.DC01_LON_CLM_INF A
INNER JOIN OLWHRM1.DC18_BKR B
	ON A.AF_APL_ID = B.AF_APL_ID
	AND A.AF_APL_ID_SFX = B.AF_APL_ID_SFX
	AND A.LF_CRT_DTS_DC10 = B.LF_CRT_DTS_DC10
INNER JOIN OLWHRM1.PD01_PDM_INF C
	ON A.BF_SSN = C.DF_PRS_ID
WHERE B.LD_BKR_FIL > &DVAL
FOR READ ONLY WITH UR
);

CREATE TABLE COBK AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT B.DF_SPE_ACC_ID
	,B.DM_PRS_1
	,B.DM_PRS_LST
	,A.DF_COU_DKT AS BK_CASE
FROM OLWHRM1.PD24_PRS_BKR A
INNER JOIN OLWHRM1.PD10_PRS_NME B
	ON A.DF_PRS_ID = B.DF_PRS_ID
WHERE A.DD_BKR_FIL > &DVAL
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>>  ;  * INCLUDES ERROR MESSAGES TO SAS LOG  ;
%SQLCHECK (SQLRPT=ULWI04.LWI04RZ);
QUIT;
DATA BK;
SET OLBK COBK;
RUN;
ENDRSUBMIT;
DATA BK;SET WORKLOCL.BK;RUN;
DATA BK;
SET BK;
BK_CASE = TRANSLATE(BK_CASE,' ','-');
BK_CASE = TRIM(LEFT(BK_CASE));
RUN;
DATA BK (drop=j) ;
SET BK;
DO UNTIL(J=0);  
	J=ANYSPACE(BK_CASE,J+1);
	BK_CASE=SUBSTR(BK_CASE,1,J-1)||SUBSTR(BK_CASE,J+1,LENGTH(BK_CASE)-J);
	_ERROR_ = 0;
END;
RUN;
PROC SORT DATA=BK NODUPKEY;BY DF_SPE_ACC_ID BK_CASE;RUN;
DATA _NULL_;
SET  WORK.BK;
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
FORMAT DF_SPE_ACC_ID $10. 
	DM_PRS_1 $12. 
	DM_PRS_LST $35. 
	BK_CASE $15.;
DO;
	PUT DF_SPE_ACC_ID $ @;
	PUT BK_CASE $ @;
	PUT DM_PRS_1 $ @;
	PUT DM_PRS_LST $ ;	
END;
RUN;
