CREATE PROCEDURE [dbo].[LT_US09B110CP_Loans]
	@LetterId VARCHAR(10),
	@BF_SSN  VARCHAR(9),
	@IsCoborrower BIT = 0,
	@RN_ATY_SEQ_PRC INT
AS
BEGIN

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @PF_REQ_ACT VARCHAR(5) = (SELECT AC11.PF_REQ_ACT FROM AC11_ACT_REQ_LTR AC11 WHERE PF_LTR = @LetterId)

IF @IsCoborrower = 0
	BEGIN
		SELECT
			ISNULL(FT.Label, LN10.IC_LON_PGM) AS IC_LON_PGM,
			CONVERT(VARCHAR(10), LN10.LD_LON_1_DSB, 101) AS LD_LON_1_DSB,
			'$' + CONVERT(VARCHAR(15), LN10.LA_LON_AMT_GTR, 1) AS OPAFEL,
			CONVERT(VARCHAR(10), LN72.LR_ITR,0) + '%' AS LR_INT_BIL,
			'$' + CONVERT(VARCHAR(15), LN10.LA_CUR_PRI, 1) AS LA_CUR_PRN_BIL,
			'$' + CONVERT(VARCHAR(15), ISNULL(LN80.LN_LTE_FEE, 0.00), 1) AS LN_LTE_FEE,
			ISNULL(LN16.LN_DLQ_MAX,0) AS DAYS_DELQ,
			'$' + CONVERT(VARCHAR(15),ISNULL(LN80.LA_BIL_PAS_DU,0.00), 1) AS LA_BIL_PAS_DU,
			'$' + CONVERT(VARCHAR(15),ISNULL(LN80.LA_BIL_CUR_DU,0.00), 1) AS CURRENT_AMOUNT_DUE,
			'$' + CONVERT(VARCHAR(15),ISNULL(LN90.TAPTP,0.00), 1) AS TAPTP,
			'$' + CONVERT(VARCHAR(15),ISNULL(LN90.TAPTI,0.00), 1) AS TAPTI,
			'$' + CONVERT(VARCHAR(15),ISNULL(LN90.TAPTF,0.00), 1) AS TAPTF,
			'$' + CONVERT(VARCHAR(15),ISNULL(LN90.TAGAP,0.00), 1) AS TAGAP
		FROM
			LN10_LON LN10
			INNER JOIN
			(
				SELECT
					LN85.BF_SSN,
					LN85.LN_SEQ
				FROM
					LN85_LON_ATY LN85
					INNER JOIN AY10_BR_LON_ATY AY10
						ON AY10.BF_SSN = LN85.BF_SSN
						AND AY10.LN_ATY_SEQ = LN85.LN_ATY_SEQ
				WHERE   
					AY10.PF_REQ_ACT = @PF_REQ_ACT
					AND AY10.BF_SSN = @BF_SSN
					AND AY10.LN_ATY_SEQ = @RN_ATY_SEQ_PRC
					--Active flag ignored, as LT20 provides the exact record that is tied to this request
			)LN85
				ON LN85.BF_SSN = LN10.BF_SSN
				AND LN85.LN_SEQ = LN10.LN_SEQ 
			INNER JOIN
			(	--Adding Active Interest Rate
				SELECT
					LN72.BF_SSN, 
					LN72.LN_SEQ,
					LN72.LR_ITR,
					ROW_NUMBER() OVER (PARTITION BY LN72.BF_SSN, LN72.LN_SEQ ORDER BY LD_STA_LON72 DESC) AS SEQ
				FROM
					LN72_INT_RTE_HST LN72
				WHERE
					LN72.LC_STA_LON72 = 'A'
					AND	CAST(GETDATE() AS DATE) BETWEEN LN72.LD_ITR_EFF_BEG AND LN72.LD_ITR_EFF_END
					AND	LN72.BF_SSN = @BF_SSN
			) LN72 
				ON LN10.BF_SSN = LN72.BF_SSN
				AND LN10.LN_SEQ = LN72.LN_SEQ
				AND LN72.SEQ = 1
			LEFT JOIN 
			(
				SELECT	
					LN80.BF_SSN,
					LN80.LN_SEQ,
					ISNULL(LN80.LA_LTE_FEE_OTS_PRT,0.00) AS LN_LTE_FEE,
					LN80.LA_BIL_PAS_DU,
					LN80.LA_BIL_CUR_DU
				FROM
					LN80_LON_BIL_CRF LN80
					INNER JOIN
					(
						SELECT	
							LN80.BF_SSN,
							MAX(LN80.LD_BIL_CRT) AS MAX_LD_BIL_CRT
						FROM
							LN80_LON_BIL_CRF LN80
						WHERE
							LN80.LC_STA_LON80 = 'A'
							AND LN80.LC_BIL_TYP_LON ='P'
						GROUP BY
							LN80.BF_SSN
					)LN80_MAX
						ON LN80_MAX.BF_SSN = LN80.BF_SSN
						AND LN80_MAX.MAX_LD_BIL_CRT = LN80.LD_BIL_CRT
				WHERE
					LN80.LC_STA_LON80 = 'A'
					AND LN80.LC_BIL_TYP_LON ='P'
			)LN80
				ON LN80.BF_SSN = LN10.BF_SSN
				AND LN80.LN_SEQ = LN10.LN_SEQ
			LEFT JOIN
			(
				SELECT
					LN90.BF_SSN,
					LN90.LN_SEQ,
					SUM(ABS(CAST(ISNULL(LN90.LA_FAT_CUR_PRI,0.00) AS DECIMAL (18,2)))) AS TAPTP,
					SUM(ABS(CAST(ISNULL(LN90.LA_FAT_NSI,0.00) AS DECIMAL (18,2)))) AS TAPTI,
					SUM(ABS(CAST(ISNULL(LN90.LA_FAT_LTE_FEE,0.00) AS DECIMAL (18,2)))) AS TAPTF, /*cumulative late fees paid*/
					SUM(ABS(CAST(ISNULL(LN90.LA_FAT_CUR_PRI,0.00) AS DECIMAL(18,2)) + CAST(ISNULL(LN90.LA_FAT_NSI,0.00) AS DECIMAL(18,2)) + CAST(ISNULL(LN90.LA_FAT_LTE_FEE,0.00) AS DECIMAL(18,2)))) AS TAGAP
				FROM 
					LN90_FIN_ATY LN90
				WHERE
					LN90.PC_FAT_TYP = '10'
					AND ISNULL(LN90.LC_FAT_REV_REA,'') = ''
					AND LN90.LC_STA_LON90 = 'A'
				GROUP BY
					LN90.BF_SSN,
					LN90.LN_SEQ
			)LN90
				ON LN90.BF_SSN = LN10.BF_SSN
				AND LN90.LN_SEQ = LN10.LN_SEQ
			LEFT JOIN LN16_LON_DLQ_HST LN16
				ON LN16.BF_SSN = LN10.BF_SSN
				AND LN16.LN_SEQ = LN10.LN_SEQ
				AND LN16.LC_STA_LON16 = '1'
				AND LN16.LC_DLQ_TYP = 'P'
				AND CAST(LN16.LD_DLQ_MAX AS DATE) BETWEEN CAST(DATEADD(DAY,-5,GETDATE()) AS DATE) AND CAST(GETDATE() AS DATE)
			LEFT JOIN FormatTranslation FT
				ON FT.Start = LN10.IC_LON_PGM
				AND FT.FmtName = '$LNPROG'
		WHERE 
			LN10.BF_SSN = @BF_SSN
	END
ELSE
	BEGIN
		SELECT
			ISNULL(FT.Label, LN10.IC_LON_PGM) AS IC_LON_PGM,
			CONVERT(VARCHAR(10), LN10.LD_LON_1_DSB, 101) AS LD_LON_1_DSB,
			'$' + CONVERT(VARCHAR(15), LN10.LA_LON_AMT_GTR, 1) AS OPAFEL,
			CONVERT(VARCHAR(10), LN72.LR_ITR,0) + '%' AS LR_INT_BIL,
			'$' + CONVERT(VARCHAR(15), LN10.LA_CUR_PRI, 1) AS LA_CUR_PRN_BIL,
			'$' + CONVERT(VARCHAR(15), ISNULL(LN80.LN_LTE_FEE, 0.00), 1) AS LN_LTE_FEE,
			ISNULL(LN16.LN_DLQ_MAX,0) AS DAYS_DELQ,
			'$' + CONVERT(VARCHAR(15),ISNULL(LN80.LA_BIL_PAS_DU,0.00), 1) AS LA_BIL_PAS_DU,
			'$' + CONVERT(VARCHAR(15),ISNULL(LN80.LA_BIL_CUR_DU,0.00), 1) AS CURRENT_AMOUNT_DUE,
			'$' + CONVERT(VARCHAR(15),ISNULL(LN90.TAPTP,0.00), 1) AS TAPTP,
			'$' + CONVERT(VARCHAR(15),ISNULL(LN90.TAPTI,0.00), 1) AS TAPTI,
			'$' + CONVERT(VARCHAR(15),ISNULL(LN90.TAPTF,0.00), 1) AS TAPTF,
			'$' + CONVERT(VARCHAR(15),ISNULL(LN90.TAGAP,0.00), 1) AS TAGAP
		FROM
			LN10_LON LN10
			INNER JOIN LN20_EDS LN20
				ON LN20.BF_SSN = LN10.BF_SSN
				AND LN20.LN_SEQ = LN10.LN_SEQ
				AND LN20.LC_STA_LON20 = 'A'
				AND LN20.LC_EDS_TYP = 'S'
			INNER JOIN
			(
				SELECT
					LN85.BF_SSN,
					LN85.LN_SEQ
				FROM
					LN85_LON_ATY LN85
					INNER JOIN AY10_BR_LON_ATY AY10
						ON AY10.BF_SSN = LN85.BF_SSN
						AND AY10.LN_ATY_SEQ = LN85.LN_ATY_SEQ
					INNER JOIN LN20_EDS LN20
						ON LN20.BF_SSN = LN85.BF_SSN
						AND LN20.LF_EDS = AY10.LF_ATY_RCP
						AND LN20.LC_STA_LON20 = 'A'
						AND LN20.LC_EDS_TYP = 'S'
				WHERE   
					AY10.PF_REQ_ACT = @PF_REQ_ACT
					AND LN20.LF_EDS = @BF_SSN
					AND AY10.LN_ATY_SEQ = @RN_ATY_SEQ_PRC
					--Active flag ignored, as LT20 provides the exact record that is tied to this request
			)LN85
				ON LN85.BF_SSN = LN10.BF_SSN
				AND LN85.LN_SEQ = LN10.LN_SEQ 
			INNER JOIN
			(	--Adding Active Interest Rate
				SELECT
					LN72.BF_SSN, 
					LN72.LN_SEQ,
					LN72.LR_ITR,
					ROW_NUMBER() OVER (PARTITION BY LN72.BF_SSN, LN72.LN_SEQ ORDER BY LD_STA_LON72 DESC) AS SEQ
				FROM
					LN72_INT_RTE_HST LN72
					INNER JOIN LN20_EDS LN20
						ON LN20.BF_SSN = LN72.BF_SSN
						AND LN20.LN_SEQ = LN72.LN_SEQ
						AND LN20.LC_STA_LON20 = 'A'
						AND LN20.LC_EDS_TYP = 'S'
				WHERE
					LN72.LC_STA_LON72 = 'A'
					AND	CAST(GETDATE() AS DATE) BETWEEN LN72.LD_ITR_EFF_BEG AND LN72.LD_ITR_EFF_END
					AND	LN20.LF_EDS = @BF_SSN
			) LN72 
				ON LN10.BF_SSN = LN72.BF_SSN
				AND LN10.LN_SEQ = LN72.LN_SEQ
				AND LN72.SEQ = 1
			LEFT JOIN 
			(
				SELECT	
					LN80.BF_SSN,
					LN80.LN_SEQ,
					ISNULL(LN80.LA_LTE_FEE_OTS_PRT,0.00) AS LN_LTE_FEE,
					LN80.LA_BIL_PAS_DU,
					LN80.LA_BIL_CUR_DU
				FROM
					LN80_LON_BIL_CRF LN80
					INNER JOIN
					(
						SELECT	
							LN80.BF_SSN,
							MAX(LN80.LD_BIL_CRT) AS MAX_LD_BIL_CRT
						FROM
							LN80_LON_BIL_CRF LN80
						WHERE
							LN80.LC_STA_LON80 = 'A'
							AND LN80.LC_BIL_TYP_LON ='P'
						GROUP BY
							LN80.BF_SSN
					)LN80_MAX
						ON LN80_MAX.BF_SSN = LN80.BF_SSN
						AND LN80_MAX.MAX_LD_BIL_CRT = LN80.LD_BIL_CRT
				WHERE
					LN80.LC_STA_LON80 = 'A'
					AND LN80.LC_BIL_TYP_LON ='P'
			)LN80
				ON LN80.BF_SSN = LN10.BF_SSN
				AND LN80.LN_SEQ = LN10.LN_SEQ
			LEFT JOIN
			(
				SELECT
					LN90.BF_SSN,
					LN90.LN_SEQ,
					SUM(ABS(CAST(ISNULL(LN90.LA_FAT_CUR_PRI,0.00) AS DECIMAL (18,2)))) AS TAPTP,
					SUM(ABS(CAST(ISNULL(LN90.LA_FAT_NSI,0.00) AS DECIMAL (18,2)))) AS TAPTI,
					SUM(ABS(CAST(ISNULL(LN90.LA_FAT_LTE_FEE,0.00) AS DECIMAL (18,2)))) AS TAPTF, /*cumulative late fees paid*/
					SUM(ABS(CAST(ISNULL(LN90.LA_FAT_CUR_PRI,0.00) AS DECIMAL(18,2)) + CAST(ISNULL(LN90.LA_FAT_NSI,0.00) AS DECIMAL(18,2)) + CAST(ISNULL(LN90.LA_FAT_LTE_FEE,0.00) AS DECIMAL(18,2)))) AS TAGAP
				FROM 
					LN90_FIN_ATY LN90
				WHERE
					LN90.PC_FAT_TYP = '10'
					AND ISNULL(LN90.LC_FAT_REV_REA,'') = ''
					AND LN90.LC_STA_LON90 = 'A'
				GROUP BY
					LN90.BF_SSN,
					LN90.LN_SEQ
			)LN90
				ON LN90.BF_SSN = LN10.BF_SSN
				AND LN90.LN_SEQ = LN10.LN_SEQ
			LEFT JOIN LN16_LON_DLQ_HST LN16
				ON LN16.BF_SSN = LN10.BF_SSN
				AND LN16.LN_SEQ = LN10.LN_SEQ
				AND LN16.LC_STA_LON16 = '1'
				AND LN16.LC_DLQ_TYP = 'P'
				AND CAST(LN16.LD_DLQ_MAX AS DATE) BETWEEN CAST(DATEADD(DAY,-5,GETDATE()) AS DATE) AND CAST(GETDATE() AS DATE)
			LEFT JOIN FormatTranslation FT
				ON FT.Start = LN10.IC_LON_PGM
				AND FT.FmtName = '$LNPROG'
		WHERE 
			LN20.LF_EDS = @BF_SSN
	END
END