/*TEST*/
/*%LET TESTMSG = - THIS IS A TEST;
%LET RPTLIB = T:\SAS;
%LET LOGLIB = Y:\Batch\Logs;
%LET CODELIB = Y:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS_TEST;
%LET DB = CDW_test;
%LET ODBCFILE_CSYS = CSYSTest;*/

/*LIVE*/
%LET TESTMSG = - THIS IS LIVE;
%LET RPTLIB = Z:\Batch\FTP;
%LET LOGLIB = Z:\Batch\Logs;
%LET CODELIB = Z:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS;
%LET DB = CDW;
%LET ODBCFILE_CSYS = CSYS;

%INCLUDE "&CODELIB\UTNWDW1 CDW DAILY UPDATE.FOLDER AND DATABASE.SAS";
%FILECHECK(17);

DATA LN65(drop=LC_TYP_SCH_DIS trunc);
	INFILE REPORT17 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
	INPUT DF_SPE_ACC_ID :$10. LN_SEQ :6. LD_CRT_LON65 :$10. LC_TYP_SCH_DIS :$2. 
		LD_SNT_RPD_DIS :$10. LA_RPS_ISL :9.2 DUE_DAY :$2. LN_RPS_TRM :3.0;
	TYP_SCH_DIS = PUT(LC_TYP_SCH_DIS,$SCHTYP.);
	LA_RPS_ISL = coalesce(LA_RPS_ISL,0);
	LN_RPS_TRM = coalesce(LN_RPS_TRM,0);
%TRUNCAT(17);
RUN;
%COPYERROR;
proc sort data=LN65; by df_spe_acc_id ln_seq; run;
DATA LN65; set LN65; by df_spe_acc_id ln_seq; if last.ln_seq ;run;

%ENCHILADA(LN65,LN65_REPAYMENTSCHED,DF_SPE_ACC_ID LN_SEQ,LD_CRT_LON65 TYP_SCH_DIS LD_SNT_RPD_DIS LN_RPS_TRM DUE_DAY LA_RPS_ISL,);

%GOODBYE_NULL(LN65_REPAYMENTSCHED,LD_CRT_LON65,'');
%GOODBYE_NULL(LN65_REPAYMENTSCHED,TYP_SCH_DIS,'');
%GOODBYE_NULL(LN65_REPAYMENTSCHED,LD_SNT_RPD_DIS,'');
%GOODBYE_NULL(LN65_REPAYMENTSCHED,LN_RPS_TRM,0);
%GOODBYE_NULL(LN65_REPAYMENTSCHED,LA_RPS_ISL,0);
%GOODBYE_NULL(LN65_REPAYMENTSCHED,DUE_DAY,'');

%FINISH(SOURCE=RPS);
