/*TEST*/
/*%LET TESTMSG = - THIS IS A TEST;
%LET RPTLIB = T:\SAS;
%LET LOGLIB = Y:\Batch\Logs;
%LET CODELIB = Y:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS_TEST;
%LET DB = CDW_test;
%LET ODBCFILE_CSYS = CSYSTest;*/

/*LIVE*/
%LET TESTMSG = - THIS IS LIVE;
%LET RPTLIB = Z:\Batch\FTP;
%LET LOGLIB = Z:\Batch\Logs;
%LET CODELIB = Z:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS;
%LET DB = CDW;
%LET ODBCFILE_CSYS = CSYS;

%INCLUDE "&CODELIB\UTNWDW1 CDW DAILY UPDATE.FOLDER AND DATABASE.SAS";
%FILECHECK(15);

DATA LN55(drop=trunc);
	INFILE REPORT15 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
	INPUT DF_SPE_ACC_ID :$10. LN_SEQ :6. LD_BBS_DSQ :$10. LC_BBS_ELG :$1. PR_EFT_RIR :5.3 PM_BBS_PGM :$3. 
		LN_BBS_STS_PCV_PAY :6. PN_BBT_DLQ_MOT :6. ;
%TRUNCAT(15);
RUN;
%COPYERROR;
PROC SORT DATA=LN55 ; BY DF_SPE_ACC_ID LN_SEQ; RUN;
DATA LN55;SET LN55;BY DF_SPE_ACC_ID LN_SEQ;IF LAST.LN_SEQ ;RUN;

%ENCHILADA(LN55,LN55_BENEFIT,DF_SPE_ACC_ID LN_SEQ,LD_BBS_DSQ LC_BBS_ELG PR_EFT_RIR PM_BBS_PGM 
		LN_BBS_STS_PCV_PAY PN_BBT_DLQ_MOT ,);

%GOODBYE_NULL(LN55_BENEFIT,LD_BBS_DSQ,'');
%GOODBYE_NULL(LN55_BENEFIT,LN_BBS_STS_PCV_PAY,0);
%GOODBYE_NULL(LN55_BENEFIT,PN_BBT_DLQ_MOT,0);

%FINISH(SOURCE=Borrower_Benefit);
