CREATE PROCEDURE [idruserpro].[GetTotalLoanDebt]
	@AccountIdentifier VARCHAR(10)
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	SELECT
		SUM(LN10.LA_CUR_PRI)
	FROM
		PD10_PRS_NME PD10
		INNER JOIN LN10_LON LN10 
			ON LN10.BF_SSN = PD10.DF_PRS_ID
	WHERE
		LN10.LC_STA_LON10 = 'R'
		AND (PD10.DF_PRS_ID = @AccountIdentifier OR PD10.DF_SPE_ACC_ID = @AccountIdentifier)

RETURN 0
