/*CRI Audit Files - Current Lender & Guarantor*/
*Note for end-users: just run the script. A pop-up screen will appear to input query paramaters. Do not alter this code.;

*initialize input variables if run multiple times;
%SYMDEL LENDER GUARANTOR B1 B2 B3 E1 E2 E3 BEGIN END / NOWARN;

*pop-up input screen;
%WINDOW USER_INPUT
	#2 @15 'CRI Audit Files - Current Lender & Guarantor'
	#5 @5 '1) Enter LENDER code(s):'
	#5 @33 LENDER 75 ATTR=UNDERLINE
	#8 @5 '2) Enter GUARANTOR code(s):'
	#8 @33 GUARANTOR 75 ATTR=UNDERLINE
	#11 @5 'note: enclose each code with single quotation marks and separate multiple code entries with a comma'
	#17 @5 '3) Enter BEGIN date:'
	#17 @27 B1 2 ATTR=UNDERLINE '/' B2 2 ATTR=UNDERLINE '/' B3 4 ATTR=UNDERLINE
	#20 @5 '4) Enter END date:'
	#20 @27 E1 2 ATTR=UNDERLINE '/' E2 2 ATTR=UNDERLINE '/' E3 4 ATTR=UNDERLINE
	#23 @5 'please use this date format:  07/31/2016  (MM/DD/YYYY)'
	#30 @5 'FYI: This query takes a few hours to run. A pop-up window will appear when it is finished.'
;
%DISPLAY USER_INPUT;

*writes notes in log;
%PUT NOTE: LENDER entered was &LENDER;
%PUT NOTE: GUARANTOR entered was &GUARANTOR;

*putn allows for formatting within sysfunc;
*use two sysfuncs with slash to concatenate two variables into desired date format for %let;
%LET BEGIN = %SYSFUNC(PUTN(&B1,Z2))/%SYSFUNC(PUTN(&B2,Z2))/&B3;
%LET END = %SYSFUNC(PUTN(&E1,Z2))/%SYSFUNC(PUTN(&E2,Z2))/&E3;
%PUT NOTE: BEGIN date entered was &BEGIN;
%PUT NOTE: END date entered was &END;

/*sample LENDERS*/
/* 829769,813285,828476,831474,898502,999775*/
/*sample GUARANTORS*/
/* 722,723,726,740,744,753,800*/

%LET RPTLIB = T:\SAS;
LIBNAME PROGREVW 'Q:\Support Services\Test Files\SAS\PROGREVW';

OPTIONS SYMBOLGEN NOCENTER NODATE NONUMBER LS=132;

DATA _NULL_;  
	*adds single quote marks to variables to pass as character values;
	CALL SYMPUT('BEGIN', "'&BEGIN'" );
	CALL SYMPUT('END', "'&END'");
	*removes leading and trailing blank spaces;
	CALL SYMPUTX('LENDER',"&LENDER");
	CALL SYMPUTX('GUARANTOR',"&GUARANTOR");
RUN;

%SYSLPUT BEGIN = %BQUOTE(&BEGIN);
%SYSLPUT END = %BQUOTE(&END);
%SYSLPUT LENDER = &LENDER;
%SYSLPUT GUARANTOR = &GUARANTOR;

LIBNAME WORKLOCL REMOTE SERVER=DUSTER SLIBREF=WORK; *LIVE;
/*LIBNAME WORKLOCL REMOTE SERVER=QADBD004 SLIBREF=WORK; *TEST;*/

RSUBMIT;

%LET DB = DLGSUTWH; *LIVE;
/*%LET DB = DLGSWQUT; *TEST;*/

PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);
	CREATE TABLE DEMO_LON AS
	SELECT *
	FROM CONNECTION TO DB2 
	(
		SELECT DISTINCT
			LN10.BF_SSN 
	        ,COALESCE(RTRIM(PD10.DM_PRS_LST), 'NLN') AS LAST_NAME
		    ,COALESCE(RTRIM(PD10.DM_PRS_1), 'NFN')	 AS FIRST_NAME
		    ,COALESCE(RTRIM(PD10.DM_PRS_MID), ' ')	 AS MIDDLE_INITIAL
	        ,PD10.DD_BRT 
			,LN10.LN_SEQ
			,LN10.LF_LON_CUR_OWN
			,LN35.LD_OWN_EFF_SR
			,CASE
				WHEN LN10.IF_DOE_LDR = LN10.LF_LON_CUR_OWN 
					THEN '      '
				ELSE COALESCE(LN35P.IF_OWN, '000000') 
			 END AS PREVIOUS_LENDER_CODE
			,COALESCE(LN35P.LD_OWN_EFF_SR, '9999-12-31') AS PREVIOUS_HOLDER_EFFECTIVE_DATE
			,CASE
				WHEN LN10.IF_DOE_LDR = ' ' 
					THEN '000000'
				WHEN LN10.IF_DOE_LDR = LN10.LF_LON_CUR_OWN 
					THEN '      '
				ELSE LN10.IF_DOE_LDR
			 END AS ORIGINAL_HOLDER
			,COALESCE(LN10.LD_LON_1_DSB, '9999-12-31') 	AS ORIGINAL_HOLDER_EFFECTIVE_DATE
			,SUBSTR(LN10.IF_GTR,4,3) AS CURRENT_GUARANTOR_CODE
			,LN10.LD_LON_1_DSB 		AS CURRENT_GUARANTOR_EFFECTIVE_DATE
			,'000' 					AS PREVIOUS_GUARANTOR_CODE
			,'00000000' 			AS PREVIOUS_GUARANTOR_EFF_DTE
			,'000' 					AS ORIGINAL_GUARANTOR_CODE
			,'00000000' 			AS ORIGINAL_GUARANTOR_EFF_DTE
			,'700126' 				AS CURRENT_SERVICER_CODE
			,LN10.LD_LON_EFF_ADD 	AS CURRENT_SERVICER_EFFECTIVE_DATE
			,'000000' 				AS PREVIOUS_SERVICER_CODE
			,'00000000' 			AS PREVIOUS_SERVICER_EFFECTIVE_DATE
			,'000000' 				AS ORIGINAL_SERVICER_CODE
			,'00000000' 			AS ORG_SERVICER_CODE_EFF_DTE
			,LN10.LI_ESG 			AS BWR_ELECTRONIC_SIG_INDICATOR_CDE
			,LN10.LF_ESG_SRC 		AS E_SIGNATURE_SOURCE_TYPE_CODE
			,LN10.LF_LON_ALT 		AS COMMONLINE_UNIQUE_ID
			,LN10.LN_LON_ALT_SEQ 	AS COMMONLINE_UNIQUE_ID_SEQUENCE
			,'                ' 	AS UNIQUE_LOAN_ID
			,LN10.LD_LON_GTR 		AS GUARANTY_DATE
			,LN10.LD_TRM_BEG 		AS LOAN_PERIOD_BEGIN_DATE
			,LN10.LD_TRM_END 		AS LOAN_PERIOD_END_DATE
			,LN10.LD_LON_1_DSB 		AS FIRST_DISBURSEMENT_DATE
			,LN15.LA_DSB 			AS FIRST_DISBURSEMENT_AMOUNT
			,CASE
				WHEN DW01.WC_DW_LON_STA = '22' 
					AND CANC.BF_SSN IS NOT NULL 
					AND CANC.LN_SEQ IS NOT NULL 
					THEN 'CA'
				WHEN DW01.WC_DW_LON_STA = '04' 
					THEN 'DA'
				WHEN DW01.WC_DW_LON_STA = '05' 
					THEN 'FB'
				WHEN DW01.WC_DW_LON_STA IN ('02','23') 
					THEN 'IA'
				WHEN DW01.WC_DW_LON_STA = '01' 
					THEN 'IG'
				WHEN DW01.WC_DW_LON_STA = '22' 
					AND PIF.BF_SSN IS NOT NULL 
					AND PIF.LN_SEQ IS NOT NULL 
					AND PIF.LD_FAT_EFF <= '12/31/2001' 
					THEN 'PC'
				WHEN DW01.WC_DW_LON_STA = '22' 
					AND PIF.BF_SSN IS NOT NULL 
					AND PIF.LN_SEQ IS NOT NULL 
					AND PIF.LD_FAT_EFF > '12/31/2001' 
					THEN 'PN'
				WHEN DW01.WC_DW_LON_STA = '22' 
					AND PIF.BF_SSN IS NULL 
					AND PIF.LN_SEQ IS NULL 
					AND CANC.BF_SSN IS NULL 
					AND CANC.LN_SEQ IS NULL
					THEN 'PF'
				WHEN DW01.WC_DW_LON_STA IN ('03','06','07','08','09','10','11','12','13','14','15') 
					THEN 'RP'
				WHEN DW01.WC_DW_LON_STA IN ('16','17') 
					THEN 'DE'
				WHEN DW01.WC_DW_LON_STA IN ('18','19') 
					THEN 'DI'
				WHEN DW01.WC_DW_LON_STA IN ('20','21') 
					THEN 'BK'
				ELSE ' '
			 END AS LOAN_STATUS_CODE
			,CASE
				WHEN DW01.WC_DW_LON_STA = '01'
					THEN SD10.LD_SCL_SPR
				WHEN DW01.WC_DW_LON_STA IN ('02','23')
					THEN LN10.LD_LON_1_DSB
				WHEN DW01.WC_DW_LON_STA IN ('03','07','08','09','10','11','12','13','14','15') 
					THEN DW01.WD_LON_RPD_SR
				WHEN DW01.WC_DW_LON_STA = '06'
					THEN LN38.LD_CU_STA_ENT
				WHEN DW01.WC_DW_LON_STA = '04'
					AND DFR.BF_SSN IS NOT NULL
					AND DFR.LN_SEQ IS NOT NULL
					THEN DFR.LD_DFR_BEG
				WHEN DW01.WC_DW_LON_STA = '05'
					AND FORB.BF_SSN IS NOT NULL
					AND FORB.LN_SEQ IS NOT NULL
					THEN FORB.LD_FOR_BEG
				WHEN DW01.WC_DW_LON_STA = '22'
					AND CANC.BF_SSN IS NOT NULL
					AND CANC.LN_SEQ IS NOT NULL
					THEN CANC.LD_FAT_EFF
				WHEN DW01.WC_DW_LON_STA = '22'
					AND PIF.BF_SSN IS NOT NULL
					AND PIF.LN_SEQ IS NOT NULL
					THEN PIF.LD_FAT_EFF
				WHEN DW01.WC_DW_LON_STA = '22'
					AND CANC.BF_SSN IS NULL
					AND CANC.LN_SEQ IS NULL
					AND PIF.BF_SSN IS NULL
					AND PIF.LN_SEQ IS NULL
					THEN LN10.LD_PIF_RPT
				WHEN DW01.WC_DW_LON_STA = '16'
					THEN PD21.DD_DTH_STA
				WHEN DW01.WC_DW_LON_STA = '17'
					THEN PD20.DD_DTH_NTF
				WHEN DW01.WC_DW_LON_STA = '18'
					THEN DIS_ALG.DD_PRS_DSA_SPS_SR
				WHEN DW01.WC_DW_LON_STA = '19'
					THEN DIS_VRF.DD_DSA_RPT 
				WHEN DW01.WC_DW_LON_STA = '20'
					AND PD24.DC_BKR_STA = '04'
					THEN PD24.DD_BKR_FIL
				WHEN DW01.WC_DW_LON_STA = '21'
					AND PD24.DC_BKR_STA = '06'
					THEN PD24.DD_BKR_VER
				ELSE '9999-12-31'
			 END AS LOAN_STATUS_DATE
			,CANC.LD_FAT_EFF 				AS CANCELLATION_DATE
			,TOT_CAN.LA_FAT_CUR_PRI * -1 	AS CANCELLATION_AMOUNT
			,REFM.LD_FAT_EFF 				AS RETURN_TO_LENDER_DATE
			,TOT_REF.LA_FAT_CUR_PRI * -1 	AS RETURN_TO_LENDER_AMOUNT
			,GR10.LD_SCL_SPR 				AS OUT_OF_SCHOOL_DATE
			,LN10.LD_END_GRC_PRD + 1 DAY 	AS DATE_ENTERED_REPAYMENT
			,LN72.LR_ITR * 1000 			AS CURRENT_INTEREST_RATE
			,CASE
				WHEN LN65.LC_TYP_SCH_DIS IN ('IB','IL')
					THEN 'Y'
				ELSE 'N'
			 END AS IBR_CODE
			,CASE
				WHEN LN65.LC_TYP_SCH_DIS = 'IB'
					THEN 'PF'
				WHEN LN65.LC_TYP_SCH_DIS = 'IL'
					THEN 'PS'
				WHEN LN65.LC_TYP_SCH_DIS = 'L'
					THEN 'SS'
				WHEN LN65.LC_TYP_SCH_DIS = 'G'
					THEN 'OP'
				ELSE LN65.LC_TYP_SCH_DIS
			END AS PFH_IBR_PAYMENT_PLAN_TYPE_CODE 			
			,CASE
				WHEN LN65.LC_TYP_SCH_DIS IN ('IB','I3') 
					THEN LN65.LD_CRT_LON65
				ELSE '9999-12-31'
			END AS PFH_START_DT								
			,TOT_BRW.AMT 		AS TOTAL_BORROWER_PAYMENTS 	/*Total Amount of Borrower Payments*/
			,LN10.LA_CUR_PRI 	AS CURRENT_PRINCIPAL_BALANCE
			,TOT_FEES.AMT 		AS LATE_FEES_ASSESSED 		/*Total Amount of Late Fees Assessed 48*/
			,COALESCE(DELQ.LN_DLQ_MAX,0) AS DAYS_DELINQUENT
			,LN10.IC_LON_PGM 	AS LOAN_TYPE
			,CLM.LD_FAT_EFF 	AS CLAIM_PAID_DATE
			,INT_CAP.AMT 		AS CAPITALIZED_INTEREST
/*			Loan Purchase Date added later after remote submit as it uses a local permanent data set*/
			,COALESCE(LOAN_SOLD.LD_FAT_EFF, '9999-12-31') AS DATE_LOAN_SOLD
			,'        ' 		AS LOAN_TRANSFER_DATE
			,DFR.LD_DFR_BEG 	AS DEFERMENT_BEGIN_DATE
			,DFR.LD_DFR_END 	AS DEFERMENT_END_DATE
			,FORB.LD_FOR_BEG 	AS FORBEARANCE_BEGIN_DATE
			,FORB.LD_FOR_END 	AS FORBEARANCE_END_DATE
			,DFR.LC_DFR_TYP 	AS DEFERMENT_TYPE
			,CASE
				WHEN LN10.IC_LON_PGM IN ('UNSPC','SUBSPC') 
					THEN 'Y'
				ELSE 'N'
			 END AS SPOUSAL_CONSOLIDATION_LOAN
			,' ' AS FILLER
		FROM 
			OLWHRM1.PD10_PRS_NME PD10
			INNER JOIN OLWHRM1.LN10_LON LN10
				ON PD10.DF_PRS_ID = LN10.BF_SSN
				AND (
						SUBSTR(LN10.LF_LON_CUR_OWN,1,6) IN (&LENDER) /*always first 6 digit lender ID*/
						OR SUBSTR(LN10.IF_GTR,4) IN (&GUARANTOR) /*always last 3 digits of 6 digit guarantor ID*/
					)
				AND LN10.LC_STA_LON10 = 'R'
			INNER JOIN OLWHRM1.DW01_DW_CLC_CLU DW01
				ON DW01.BF_SSN = LN10.BF_SSN
				AND DW01.LN_SEQ = LN10.LN_SEQ
			INNER JOIN OLWHRM1.LN35_LON_OWN LN35
				ON LN10.BF_SSN = LN35.BF_SSN
				AND LN10.LN_SEQ = LN35.LN_SEQ
				AND LN35.LC_STA_LON35 = 'A'
				AND LN35.LD_OWN_EFF_SR < &END
				AND (
						LN35.LD_OWN_EFF_END >= &END 
						OR LN35.LD_OWN_EFF_END IS NULL
					)
			LEFT JOIN OLWHRM1.LN38_CU_STA_HST LN38
				ON LN10.BF_SSN = LN38.BF_SSN
				AND LN10.LN_SEQ = LN38.LN_SEQ
			LEFT JOIN
			(
				SELECT
					LN35.BF_SSN
					,LN35.LN_SEQ
					,LN35.IF_OWN
					,LN35.LD_OWN_EFF_SR
				FROM 
					OLWHRM1.LN35_LON_OWN LN35
					INNER JOIN
					(
						SELECT
							LN35.BF_SSN
							,LN35.LN_SEQ
							,MAX(LN35.LD_OWN_EFF_END) AS LD_OWN_EFF_END
						FROM 
							OLWHRM1.LN35_LON_OWN LN35
						WHERE 
							LN35.LD_OWN_EFF_END IS NOT NULL
						GROUP BY 
							LN35.BF_SSN
							,LN35.LN_SEQ
					) LN35M
						ON LN35.BF_SSN = LN35M.BF_SSN
						AND LN35.LN_SEQ = LN35M.LN_SEQ
						AND LN35.LD_OWN_EFF_END = LN35M.LD_OWN_EFF_END
			) LN35P
				ON LN10.BF_SSN = LN35P.BF_SSN
				AND LN10.LN_SEQ = LN35P.LN_SEQ
			LEFT JOIN OLWHRM1.LN15_DSB LN15
			      ON LN15.BF_SSN = LN10.BF_SSN
			      AND LN15.LN_SEQ = LN10.LN_SEQ
			      AND LN15.LN_LON_DSB_SEQ = 1
/*Loans PIF with cancellation*/
			LEFT JOIN 
			(
				SELECT
					LN90.BF_SSN
					,LN90.LN_SEQ
					,LN90.LD_FAT_EFF
				FROM 
					OLWHRM1.LN90_FIN_ATY LN90
					INNER JOIN
					(
						SELECT
							LN90.BF_SSN
							,LN90.LN_SEQ
							,MAX(LN90.LD_FAT_EFF) AS LD_FAT_EFF
						FROM 
							OLWHRM1.LN90_FIN_ATY LN90
						WHERE
							LN90.PC_FAT_TYP = '10'
							AND LN90.PC_FAT_SUB_TYP = '45'
							AND LN90.LC_FAT_REV_REA = ' '
							AND LN90.LC_STA_LON90 = 'A'
						GROUP BY 
							LN90.BF_SSN
							,LN90.LN_SEQ
					) MAX
						ON LN90.BF_SSN = MAX.BF_SSN
						AND LN90.LN_SEQ = MAX.LN_SEQ
						AND LN90.LD_FAT_EFF = MAX.LD_FAT_EFF
			) CANC
				ON LN10.BF_SSN = CANC.BF_SSN
				AND LN10.LN_SEQ = CANC.LN_SEQ
/*Loans PIF with 10/70 or 10/80 payments (consolodation)*/
			LEFT JOIN 
			(
				SELECT
					LN90.BF_SSN
					,LN90.LN_SEQ
					,LN90.LD_FAT_EFF
				FROM 
					OLWHRM1.LN90_FIN_ATY LN90
					INNER JOIN 
					(
						SELECT
							LN90.BF_SSN
							,LN90.LN_SEQ
							,MAX(LN90.LD_FAT_EFF) AS LD_FAT_EFF
						FROM
							OLWHRM1.LN90_FIN_ATY LN90
						WHERE 
							LN90.PC_FAT_TYP = '10'
							AND LN90.PC_FAT_SUB_TYP IN ('70','80')
							AND LN90.LC_FAT_REV_REA = ' '
							AND LN90.LC_STA_LON90 = 'A'
						GROUP BY
							LN90.BF_SSN
							,LN90.LN_SEQ
					) MAX
						ON LN90.BF_SSN = MAX.BF_SSN
						AND LN90.LN_SEQ = MAX.LN_SEQ
						AND LN90.LD_FAT_EFF = MAX.LD_FAT_EFF
			) PIF
				ON LN10.BF_SSN = PIF.BF_SSN
				AND LN10.LN_SEQ = PIF.LN_SEQ
/*Getting graduation dates*/
			LEFT JOIN
			( 
				SELECT
					SD10.LF_STU_SSN
					,SD10.LD_SCL_SPR
				FROM
					OLWHRM1.SD10_STU_SPR SD10
					INNER JOIN 
					(	
						SELECT
							SD10.LF_STU_SSN
							,MAX(SD10.LD_SCL_SPR) AS LD_SCL_SPR
						FROM 
							OLWHRM1.SD10_STU_SPR SD10
						GROUP BY 
							SD10.LF_STU_SSN
					) MAX
						ON SD10.LF_STU_SSN = MAX.LF_STU_SSN
						AND SD10.LD_SCL_SPR = MAX.LD_SCL_SPR
			) SD10
				ON LN10.BF_SSN = SD10.LF_STU_SSN
/*Pulling active deferments*/
			LEFT JOIN 
			(
				SELECT
					LN50.BF_SSN
					,LN50.LN_SEQ
					,DF10.LC_DFR_TYP
					,MAX(LN50.LD_DFR_BEG) AS LD_DFR_BEG
					,MAX(LN50.LD_DFR_END) AS LD_DFR_END
				FROM 
					OLWHRM1.LN50_BR_DFR_APV LN50
					INNER JOIN OLWHRM1.DF10_BR_DFR_REQ DF10
						ON LN50.BF_SSN = DF10.BF_SSN
						AND LN50.LF_DFR_CTL_NUM = DF10.LF_DFR_CTL_NUM
				WHERE 
					LN50.LC_STA_LON50 = 'A'
					AND DF10.LC_DFR_STA = 'A'
					AND DF10.LC_STA_DFR10 = 'A'
				GROUP BY 
					LN50.BF_SSN
					,LN50.LN_SEQ
					,DF10.LC_DFR_TYP
			) DFR
				ON LN10.BF_SSN = DFR.BF_SSN
				AND LN10.LN_SEQ = DFR.LN_SEQ
/*Pulling active forbearances*/
			LEFT JOIN
			(
				SELECT
					LN60.BF_SSN
					,LN60.LN_SEQ
					,MAX(LN60.LD_FOR_BEG) AS LD_FOR_BEG
					,MAX(LN60.LD_FOR_END) AS LD_FOR_END
				FROM 
					OLWHRM1.LN60_BR_FOR_APV LN60
					INNER JOIN OLWHRM1.FB10_BR_FOR_REQ FB10
						ON LN60.BF_SSN = FB10.BF_SSN
						AND LN60.LF_FOR_CTL_NUM = FB10.LF_FOR_CTL_NUM
				WHERE 
					LN60.LC_STA_LON60 = 'A'
					AND FB10.LC_FOR_STA= 'A'
					AND FB10.LC_STA_FOR10 = 'A'
				GROUP BY 
					LN60.BF_SSN
					,LN60.LN_SEQ
			) FORB
				ON LN10.BF_SSN = FORB.BF_SSN
				AND LN10.LN_SEQ = FORB.LN_SEQ
			LEFT JOIN OLWHRM1.PD21_GTR_DTH PD21
				ON LN10.BF_SSN = PD21.DF_PRS_ID
			LEFT JOIN OLWHRM1.PD20_PRS_DTH PD20
				ON LN10.BF_SSN = PD20.DF_PRS_ID
/*Alleged disability*/
			LEFT JOIN 
			(
				SELECT
					PD22.DF_PRS_ID
					,PD22.DD_PRS_DSA_SPS_SR 
				FROM 
					OLWHRM1.PD22_PRS_DSA PD22
					INNER JOIN OLWHRM1.PD23_GTR_DSA PD23
						ON PD22.DF_PRS_ID = PD23.DF_PRS_ID
						AND PD22.DD_DSA_RPT = PD23.DD_DSA_RPT
				WHERE 
					PD23.DC_DSA_STA = '07'
			) DIS_ALG
				ON LN10.BF_SSN = DIS_ALG.DF_PRS_ID
/*Verified disability*/
			LEFT JOIN 
			(
				SELECT
					PD22.DF_PRS_ID
					,PD22.DD_DSA_RPT 
				FROM 
					OLWHRM1.PD22_PRS_DSA PD22
					INNER JOIN OLWHRM1.PD23_GTR_DSA PD23
						ON PD22.DF_PRS_ID = PD23.DF_PRS_ID
						AND PD22.DD_DSA_RPT = PD23.DD_DSA_RPT
				WHERE 
					PD23.DC_DSA_STA = '09'
			) DIS_VRF
				ON LN10.BF_SSN = DIS_ALG.DF_PRS_ID
			LEFT JOIN OLWHRM1.PD24_PRS_BKR PD24
				ON LN10.BF_SSN = PD24.DF_PRS_ID
/*Totalling PIF cancelled amounts*/
			LEFT JOIN
			(
				SELECT
					LN90.BF_SSN
					,LN90.LN_SEQ
					,SUM(LN90.LA_FAT_CUR_PRI) AS LA_FAT_CUR_PRI
				FROM 
					OLWHRM1.LN90_FIN_ATY LN90
				WHERE 
					LN90.PC_FAT_TYP = '10'
					AND LN90.PC_FAT_SUB_TYP = '45'
				GROUP BY 
					LN90.BF_SSN
					,LN90.LN_SEQ
			) TOT_CAN
				ON LN10.BF_SSN = TOT_CAN.BF_SSN
				AND LN10.LN_SEQ = TOT_CAN.LN_SEQ
/*Max refund date*/
			LEFT JOIN 
			(
				SELECT
					LN90.BF_SSN
					,LN90.LN_SEQ
					,LN90.LD_FAT_EFF
				FROM 
					OLWHRM1.LN90_FIN_ATY LN90
					INNER JOIN 
					(
						SELECT
							LN90.BF_SSN
							,LN90.LN_SEQ
							,MAX(LN90.LD_FAT_EFF) AS LD_FAT_EFF
						FROM 
							OLWHRM1.LN90_FIN_ATY LN90
						WHERE 
							LN90.PC_FAT_TYP = '10'
							AND LN90.PC_FAT_SUB_TYP = '40'
							AND LN90.LC_FAT_REV_REA = ' '
							AND LN90.LC_STA_LON90 = 'A'
						GROUP BY 
							LN90.BF_SSN
							,LN90.LN_SEQ
					) MAX
						ON LN90.BF_SSN = MAX.BF_SSN
						AND LN90.LN_SEQ = MAX.LN_SEQ
						AND LN90.LD_FAT_EFF = MAX.LD_FAT_EFF
			) REFM
				ON LN10.BF_SSN = REFM.BF_SSN
				AND LN10.LN_SEQ = REFM.LN_SEQ
/*Totalling 10/40 payments by loan*/
			LEFT JOIN
			(
				SELECT
					LN90.BF_SSN
					,LN90.LN_SEQ
					,SUM(LN90.LA_FAT_CUR_PRI) AS LA_FAT_CUR_PRI
				FROM 
					OLWHRM1.LN90_FIN_ATY LN90
				WHERE 
					LN90.PC_FAT_TYP = '10'
					AND LN90.PC_FAT_SUB_TYP = '40'
				GROUP BY 
					LN90.BF_SSN
					,LN90.LN_SEQ
			) TOT_REF
				ON LN10.BF_SSN = TOT_REF.BF_SSN
				AND LN10.LN_SEQ = TOT_REF.LN_SEQ
/*enrollment (out of school date)*/
			LEFT JOIN OLWHRM1.GR10_RPT_LON_APL GR10
				ON LN10.BF_SSN = GR10.BF_SSN
				AND LN10.LN_SEQ = GR10.LN_SEQ
/*Totalling 10/10 (borrower) payments by loan*/
			LEFT JOIN 
			(
				SELECT
					LN90.BF_SSN
					,LN90.LN_SEQ
					,SUM(COALESCE(LN90.LA_FAT_CUR_PRI,0) + COALESCE(LN90.LA_FAT_NSI,0) + COALESCE(LN90.LA_FAT_LTE_FEE,0)) AS AMT
				FROM 
					OLWHRM1.LN90_FIN_ATY LN90
				WHERE 
					LN90.PC_FAT_TYP = '10'
					AND LN90.PC_FAT_SUB_TYP = '10'
				GROUP BY 
					LN90.BF_SSN
					,LN90.LN_SEQ
			) TOT_BRW
				ON LN10.BF_SSN = TOT_BRW.BF_SSN
				AND LN10.LN_SEQ = TOT_BRW.LN_SEQ
/*Totalling 29 (late fee) payments by loan*/
			LEFT JOIN
			(
				SELECT
					LN90.BF_SSN
					,LN90.LN_SEQ
					,SUM(COALESCE(LN90.LA_FAT_LTE_FEE,0)) AS AMT
				FROM 
					OLWHRM1.LN90_FIN_ATY LN90
				WHERE 
					LN90.PC_FAT_TYP = '26'
				GROUP BY 
					LN90.BF_SSN
					,LN90.LN_SEQ
			) TOT_FEES
				ON LN10.BF_SSN = TOT_FEES.BF_SSN
				AND LN10.LN_SEQ = TOT_FEES.LN_SEQ
/*delinquency*/
			LEFT JOIN
			(
				SELECT
					LN16.BF_SSN
					,LN16.LN_SEQ
					,LN16.LN_DLQ_MAX
				FROM
					OLWHRM1.LN16_LON_DLQ_HST LN16
				WHERE
					LN16.LC_STA_LON16 = '1'
					AND DAYS(LN16.LF_LST_DTS_LN16) = DAYS(CURRENT_DATE) - 1
			) DELQ
				ON LN10.BF_SSN = DELQ.BF_SSN
				AND LN10.LN_SEQ = DELQ.LN_SEQ
/*Totalling 70/01 (interest capitalization) payments by loan*/
			LEFT JOIN
			(
				SELECT
					LN90.BF_SSN
					,LN90.LN_SEQ
					,SUM(COALESCE(LA_FAT_NSI,0)) AS AMT
				FROM 
					OLWHRM1.LN90_FIN_ATY LN90
				WHERE 
					LN90.PC_FAT_TYP = '70'
					AND LN90.PC_FAT_SUB_TYP = '01'
				GROUP BY 
					LN90.BF_SSN
					,LN90.LN_SEQ
			) INT_CAP
				ON LN10.BF_SSN = INT_CAP.BF_SSN
				AND LN10.LN_SEQ = INT_CAP.LN_SEQ
/*date loan sold*/
			LEFT JOIN
			(
				SELECT DISTINCT
					LN90.BF_SSN
					,LN90.LN_SEQ
					,LN90.LD_FAT_EFF
				FROM 
					OLWHRM1.LN90_FIN_ATY LN90
				WHERE 
					LN90.PC_FAT_TYP = '03'
					AND LN90.PC_FAT_SUB_TYP = '95'
			) LOAN_SOLD
				ON LN10.BF_SSN = LOAN_SOLD.BF_SSN
				AND LN10.LN_SEQ = LOAN_SOLD.LN_SEQ		
				AND LN10.LF_LON_CUR_OWN IN ('826717','830248')
/*Getting current interest rate*/
			LEFT JOIN 
			(
				SELECT
					LN72.BF_SSN
					,LN72.LN_SEQ
					,LN72.LR_ITR
				FROM 
					OLWHRM1.LN72_INT_RTE_HST LN72
					INNER JOIN 
					(
						SELECT 
							LN72.BF_SSN
						    ,LN72.LN_SEQ
						    ,MAX(LN72.LN_ITR_SEQ) AS LN_ITR_SEQ
						FROM 
							OLWHRM1.LN72_INT_RTE_HST LN72 
						WHERE 
							LN72.LC_STA_LON72 = 'A'
						GROUP BY 
							LN72.BF_SSN
							,LN72.LN_SEQ
					) LN72M
						ON LN72.BF_SSN = LN72M.BF_SSN
						AND LN72.LN_SEQ = LN72M.LN_SEQ
						AND LN72.LN_ITR_SEQ = LN72M.LN_ITR_SEQ
			) LN72
				ON LN10.BF_SSN = LN72.BF_SSN
				AND LN10.LN_SEQ = LN72.LN_SEQ
/*Get RPS info*/
			LEFT JOIN 
			(
				SELECT 
					LN65.BF_SSN
					,LN65.LN_SEQ
					,LN65.LD_CRT_LON65
					,LN65.LC_TYP_SCH_DIS 
				FROM 
					OLWHRM1.LN65_LON_RPS LN65
					INNER JOIN 
					(
						SELECT
							LN65.BF_SSN
							,LN65.LN_SEQ
							,MAX(LN65.LN_RPS_SEQ) AS LN_RPS_SEQ
						FROM 
							OLWHRM1.LN65_LON_RPS LN65
						WHERE
							LN65.LD_CRT_LON65 < &END
						GROUP BY 
							LN65.BF_SSN
							,LN65.LN_SEQ
					) LN65M
						ON LN65.BF_SSN = LN65M.BF_SSN
						AND LN65.LN_SEQ = LN65M.LN_SEQ
						AND LN65.LN_RPS_SEQ = LN65M.LN_RPS_SEQ
			) LN65
				ON LN10.BF_SSN = LN65.BF_SSN
				AND LN10.LN_SEQ = LN65.LN_SEQ
/*Latest Claim Paid Date*/
			LEFT JOIN 
			(
				SELECT
					LN90.BF_SSN
					,LN90.LN_SEQ
					,LN90.LD_FAT_EFF
				FROM 
					OLWHRM1.LN90_FIN_ATY LN90
					INNER JOIN 
					(
						SELECT
							LN90.BF_SSN
							,LN90.LN_SEQ
							,MAX(LN90.LD_FAT_EFF) AS LD_FAT_EFF
						FROM 
							OLWHRM1.LN90_FIN_ATY LN90
						WHERE
							LN90.PC_FAT_TYP = '10'
							AND LN90.PC_FAT_SUB_TYP = '30'
							AND LN90.LC_FAT_REV_REA = ' '
							AND LN90.LC_STA_LON90 = 'A'
						GROUP BY
							LN90.BF_SSN
							,LN90.LN_SEQ
					) MAX
						ON LN90.BF_SSN = MAX.BF_SSN
						AND LN90.LN_SEQ = MAX.LN_SEQ
						AND LN90.LD_FAT_EFF = MAX.LD_FAT_EFF
			) CLM
				ON LN10.BF_SSN = CLM.BF_SSN
				AND LN10.LN_SEQ = CLM.LN_SEQ
	);
QUIT;
ENDRSUBMIT;

DATA _DEMO; 
	SET DUSTER.DEMO_LON; 
RUN;

PROC SORT DATA=_DEMO; 
	BY BF_SSN LN_SEQ;
RUN;

/*get loan purchase date from local permanent data set based on lender id*/
PROC SQL;
	CREATE TABLE DEMO AS
		SELECT
			_DEMO.*
			,COALESCE(LP.PURCHASE_DATE,'31DEC9999'D) AS LOAN_PURCHASE_DATE
		FROM
			_DEMO
			LEFT JOIN PROGREVW.LOAN_PURCHASE_DATE LP
				ON _DEMO.LF_LON_CUR_OWN = LP.LENDER_ID
	;
QUIT;

PROC FORMAT;
	VALUE $LON_STA
		'STFFRD' = 'SF'
		'UNSTFRD' = 'SU'
		'PLUS' = 'PL'
		'PLUSGB' = 'GB'
		'CONSOL' = 'CL'
		'SUBCNS' = 'CL'
		'UNCNS' = 'CL'
		'SUBSPC' = 'CL'
		'UNSPC' = 'CL'
		'SLS' = 'SL'
	;
RUN;

PROC FORMAT;
	VALUE $DEF_TYP
		'05' = 'AC'
		'04' = 'AP' 
		'29' = 'EH' 
		'15' = 'FT'
		'06' = 'GF'
		'18' = 'HT'
		'08' = 'IR'
		'09' = 'IR'
		'38' = 'MO'
		'40' = 'MO'
		'01' = 'NO'
		'07' = 'PC'
		'45' = 'PD'
		'46' = 'PE'
		'12' = 'PL'
		'19' = 'PP'
		'20' = 'PP'
		'21' = 'PP'
		'22' = 'PP'
		'03' = 'RT'
		'02' = 'TD'
		'10' = 'TE'
		'14' = 'TS'
		'13' = 'UE'
		'11' = 'WM'
	;
RUN;

/*generates datetime stamp*/
DATA _NULL_;
	%LET RUNDATE = %SYSFUNC(TODAY(),DATE9.)_%SYSFUNC(TIME(),TIMEAMPM.);
	%LET RUNDATE2 = %SYSFUNC(TRANSLATE(&RUNDATE,'-', ':'));
RUN;
%PUT &RUNDATE2;

/*************EXPORTS AS COMMA-DELIMITED TEXT FILE********************************/
*text file must then be manually imported into the first column of a .csv in order to preserve exact formatting;
FILENAME REPORT2 "&RPTLIB/CRI_Audit_Files_-_Current_Lender_&RUNDATE2..txt";
DATA _NULL_ 
	(DROP=
		FIRST_DISBURSEMENT_AMT
		CANCELLATION_AMT
		RETURN_TO_LENDER_AMT
		CURRENT_PRINCIPAL_BAL
		LATE_FEES_ASS
		CAPITALIZED_INT
		TOTAL_BORROWER_PMT
	);
	SET WORK.DEMO (RENAME =
		(
			FIRST_DISBURSEMENT_AMOUNT = FIRST_DISBURSEMENT_AMT
			CANCELLATION_AMOUNT = CANCELLATION_AMT
			RETURN_TO_LENDER_AMOUNT = RETURN_TO_LENDER_AMT
			CURRENT_PRINCIPAL_BALANCE = CURRENT_PRINCIPAL_BAL
			LATE_FEES_ASSESSED = LATE_FEES_ASS
			CAPITALIZED_INTEREST = CAPITALIZED_INT
			TOTAL_BORROWER_PAYMENTS = TOTAL_BORROWER_PMT
		)
	);
	FILE REPORT2 DELIMITER=',' DROPOVER LRECL=32767;
	FORMAT
 		BF_SSN $9.
		FIRST_DISBURSEMENT_AMOUNT Z8.
		CANCELLATION_AMOUNT Z8.
		RETURN_TO_LENDER_AMOUNT Z8.
		CURRENT_PRINCIPAL_BALANCE Z8.
		LATE_FEES_ASSESSED Z8.
		CAPITALIZED_INTEREST Z8.
		TOTAL_BORROWER_PAYMENTS Z8.
		CURRENT_INTEREST_RATE Z5.
		LAST_NAME $QUOTE35. 
		FIRST_NAME $QUOTE15. 
		MIDDLE_INITIAL $1. 
		DD_BRT YYMMDDn8. 
		LF_LON_CUR_OWN $6. 
		LD_OWN_EFF_SR YYMMDDn8. 
		PREVIOUS_LENDER_CODE $6. 
		ORIGINAL_HOLDER $6. 
		CURRENT_GUARANTOR_CODE $3. 
		CURRENT_GUARANTOR_EFFECTIVE_DATE YYMMDDn8. 
		PREVIOUS_GUARANTOR_EFF_DTE $8. 
		ORIGINAL_GUARANTOR_CODE $3. 
		ORIGINAL_GUARANTOR_EFF_DTE $8. 
		CURRENT_SERVICER_CODE $6. 
		CURRENT_SERVICER_EFFECTIVE_DATE YYMMDDn8. 
		PREVIOUS_SERVICER_CODE $6. 
		PREVIOUS_SERVICER_EFFECTIVE_DATE $8. 
		ORIGINAL_SERVICER_CODE $6. 
		ORG_SERVICER_CODE_EFF_DTE $8. 
		BWR_ELECTRONIC_SIG_INDICATOR_CDE $1. 
		E_SIGNATURE_SOURCE_TYPE_CODE $7. 
		COMMONLINE_UNIQUE_ID $17. 
		COMMONLINE_UNIQUE_ID_SEQUENCE 2. 
		UNIQUE_LOAN_ID $16. 
		GUARANTY_DATE YYMMDDn8. 
		LOAN_PERIOD_BEGIN_DATE YYMMDDn8. 
		LOAN_PERIOD_END_DATE YYMMDDn8. 
		FIRST_DISBURSEMENT_DATE YYMMDDn8. 
		LOAN_STATUS_CODE $2. 
		CANCELLATION_DATE YYMMDDn8. 
		RETURN_TO_LENDER_DATE YYMMDDn8. 
		OUT_OF_SCHOOL_DATE YYMMDDn8. 
		DATE_ENTERED_REPAYMENT YYMMDDn8. 
		IBR_CODE $1. 
		PFH_IBR_PAYMENT_PLAN_TYPE_CODE $2. 
		DAYS_DELINQUENT 8. 
		LOAN_TYPE $LON_STA. 
		CLAIM_PAID_DATE YYMMDDn8. 
		LOAN_TRANSFER_DATE $8. 
		DEFERMENT_BEGIN_DATE YYMMDDn8. 
		DEFERMENT_END_DATE YYMMDDn8. 
		FORBEARANCE_BEGIN_DATE YYMMDDn8. 
		FORBEARANCE_END_DATE YYMMDDn8. 
		DEFERMENT_TYPE $DEF_TYP.
		SPOUSAL_CONSOLIDATION_LOAN $1. 
		FILLER $75. 
	;

/*	replace dummy dates with all zeros, since all zeros is not a valid date, a new character variable has to be created*/
	IF PREVIOUS_HOLDER_EFFECTIVE_DATE = '31DEC9999'D THEN PREV_HOLDER_EFFECTIVE_DATE = '00000000'; ELSE PREV_HOLDER_EFFECTIVE_DATE = PUT(PREVIOUS_HOLDER_EFFECTIVE_DATE,YYMMDDn8.);
	IF ORIGINAL_HOLDER_EFFECTIVE_DATE = '31DEC9999'D THEN ORIG_HOLDER_EFFECTIVE_DATE = '00000000'; ELSE ORIG_HOLDER_EFFECTIVE_DATE = PUT(ORIGINAL_HOLDER_EFFECTIVE_DATE,YYMMDDn8.);
	IF LOAN_STATUS_DATE = '31DEC9999'D THEN LN_STATUS_DATE = '00000000'; ELSE LN_STATUS_DATE = PUT(LOAN_STATUS_DATE,YYMMDDn8.);
	IF DATE_LOAN_SOLD = '31DEC9999'D THEN DT_LOAN_SOLD = '00000000'; ELSE DT_LOAN_SOLD = PUT(DATE_LOAN_SOLD,YYMMDDn8.);
	IF LOAN_PURCHASE_DATE = '31DEC9999'D THEN LN_PURCHASE_DATE = '00000000'; ELSE LN_PURCHASE_DATE = PUT(LOAN_PURCHASE_DATE,YYMMDDn8.);
	IF PFH_START_DT = '31DEC9999'D THEN PFH_START_DATE = '00000000'; ELSE PFH_START_DATE = PUT(PFH_START_DT,YYMMDDn8.);

/*	prepares for z. padding*/
	FIRST_DISBURSEMENT_AMOUNT = FIRST_DISBURSEMENT_AMT * 100 ;
	CANCELLATION_AMOUNT = CANCELLATION_AMT * 100 ;
	RETURN_TO_LENDER_AMOUNT = RETURN_TO_LENDER_AMT * 100 ;
	CURRENT_PRINCIPAL_BALANCE = CURRENT_PRINCIPAL_BAL * 100 ;
	LATE_FEES_ASSESSED = LATE_FEES_ASS * 100 ;
	CAPITALIZED_INTEREST = CAPITALIZED_INT * 100 ;
	TOTAL_BORROWER_PAYMENTS = TOTAL_BORROWER_PMT * 100 ;

	IF _N_ = 1 THEN        /* WRITE COLUMN NAMES */
		DO;
			PUT
				'BF_SSN,'
				'LAST_NAME,'
				'FIRST_NAME,'
				'MIDDLE_INITIAL,'
				'DATE_OF_BIRTH,'
				'CURRENT_LENDER_CODE,'
				'CURRENT_HOLDER_EFFECTIVE_DATE,'
				'PREVIOUS_LENDER_CODE,'
				'PREVIOUS_HOLDER_EFFECTIVE_DATE,'
				'ORIGINAL_HOLDER,'
				'ORIGINAL_HOLDER_EFFECTIVE_DATE,'
				'CURRENT_GUARANTOR_CODE,'
				'CURRENT_GUARANTOR_EFFECTIVE_DATE,'
				'PREVIOUS_GUARANTOR_CODE,'
				'PREVIOUS_GUARANTOR_EFFECTIVE_DATE,'
				'ORIGINAL_GUARANTOR_CODE,'
				'ORIGINAL_GUARANTOR_EFFECTIVE_DATE,'
				'CURRENT_SERVICER_CODE,'
				'CURRENT_SERVICER_EFFECTIVE_DATE,'
				'PREVIOUS_SERVICER_CODE,'
				'PREVIOUS_SERVICER_EFFECTIVE_DATE,'
				'ORIGINAL_SERVICER_CODE,'
				'ORIGINAL_SERVICER_CODE_EFFECTIVE_DATE,'
				'BORROWER_ELECTRONIC_SIGNATURE_INDICATOR_CODE,'
				'E_SIGNATURE_SOURCE_TYPE_CODE,'
				'COMMONLINE_UNIQUE_ID,'
				'COMMONLINE_UNIQUE_ID_SEQUENCE,'
				'UNIQUE_LOAN_ID,'
				'GUARANTY_DATE,'
				'LOAN_PERIOD_BEGIN_DATE,'
				'LOAN_PERIOD_END_DATE,'
				'FIRST_DISBURSEMENT_DATE,'
				'FIRST_DISBURSEMENT_AMOUNT,'
				'LOAN_STATUS_CODE,'
				'LOAN_STATUS_DATE,'
				'CANCELLATION_DATE,'
				'CANCELLATION_AMOUNT,'
				'RETURN_TO_LENDER_DATE,'
				'RETURN_TO_LENDER_AMOUNT,'
				'OUT_OF_SCHOOL_DATE,'
				'DATE_ENTERED_REPAYMENT,'
				'CURRENT_INTEREST_RATE,'
				'IBR_CODE,'
				'PFH_IBR_PAYMENT_PLAN_TYPE_CODE,'
				'PFH_START_DATE,'
				'TOTAL_BORROWER_PAYMENTS,'
				'CURRENT_PRINCIPAL_BALANCE,'
				'LATE_FEES_ASSESSED,'
				'DAYS_DELINQUENT,'
				'LOAN_TYPE,'
				'CLAIM_PAID_DATE,'
				'CAPITALIZED_INTEREST,'
				'LOAN_PURCHASE_DATE,'
				'DATE_LOAN_SOLD,'
				'LOAN_TRANSFER_DATE,'
				'DEFERMENT_BEGIN_DATE,'
				'DEFERMENT_END_DATE,'
				'FORBEARANCE_BEGIN_DATE,'
				'FORBEARANCE_END_DATE,'
				'DEFERMENT_TYPE,'
				'SPOUSAL_CONSOLIDATION_LOAN,'
				'FILLER'
				;
		END;

	DO;
		EFIOUT + 1;
		PUT BF_SSN $ @;
		PUT LAST_NAME $ @;
		PUT FIRST_NAME $ @;
		PUT MIDDLE_INITIAL $ @;
		PUT DD_BRT @;
		PUT LF_LON_CUR_OWN $ @;
		PUT LD_OWN_EFF_SR @;
		PUT PREVIOUS_LENDER_CODE $ @;
		PUT PREV_HOLDER_EFFECTIVE_DATE $ @;
		PUT ORIGINAL_HOLDER $ @;
		PUT ORIG_HOLDER_EFFECTIVE_DATE @;
		PUT CURRENT_GUARANTOR_CODE $ @;
		PUT CURRENT_GUARANTOR_EFFECTIVE_DATE @;
		PUT PREVIOUS_GUARANTOR_CODE $ @;
		PUT PREVIOUS_GUARANTOR_EFF_DTE $ @;
		PUT ORIGINAL_GUARANTOR_CODE $ @;
		PUT ORIGINAL_GUARANTOR_EFF_DTE $ @;
		PUT CURRENT_SERVICER_CODE $ @;
		PUT CURRENT_SERVICER_EFFECTIVE_DATE @;
		PUT PREVIOUS_SERVICER_CODE $ @;
		PUT PREVIOUS_SERVICER_EFFECTIVE_DATE $ @;
		PUT ORIGINAL_SERVICER_CODE $ @;
		PUT ORG_SERVICER_CODE_EFF_DTE $ @;
		PUT BWR_ELECTRONIC_SIG_INDICATOR_CDE $ @;
		PUT E_SIGNATURE_SOURCE_TYPE_CODE $ @;
		PUT COMMONLINE_UNIQUE_ID $ @;
		PUT COMMONLINE_UNIQUE_ID_SEQUENCE @;
		PUT UNIQUE_LOAN_ID $ @;
		PUT GUARANTY_DATE @;
		PUT LOAN_PERIOD_BEGIN_DATE @;
		PUT LOAN_PERIOD_END_DATE @;
		PUT FIRST_DISBURSEMENT_DATE @;
		PUT FIRST_DISBURSEMENT_AMOUNT @;
		PUT LOAN_STATUS_CODE $ @;
		PUT LN_STATUS_DATE @;
		PUT CANCELLATION_DATE @;
		PUT CANCELLATION_AMOUNT @;
		PUT RETURN_TO_LENDER_DATE @;
		PUT RETURN_TO_LENDER_AMOUNT @;
		PUT OUT_OF_SCHOOL_DATE @;
		PUT DATE_ENTERED_REPAYMENT @;
		PUT CURRENT_INTEREST_RATE @;
		PUT IBR_CODE $ @;
		PUT PFH_IBR_PAYMENT_PLAN_TYPE_CODE $ @;
		PUT PFH_START_DATE @;
		PUT TOTAL_BORROWER_PAYMENTS @;
		PUT CURRENT_PRINCIPAL_BALANCE @;
		PUT LATE_FEES_ASSESSED @;
		PUT DAYS_DELINQUENT @;
		PUT LOAN_TYPE $ @;
		PUT CLAIM_PAID_DATE @;
		PUT CAPITALIZED_INTEREST @;
		PUT LN_PURCHASE_DATE $ @;
		PUT DT_LOAN_SOLD $ @;
		PUT LOAN_TRANSFER_DATE @;
		PUT DEFERMENT_BEGIN_DATE @;
		PUT DEFERMENT_END_DATE @;
		PUT FORBEARANCE_BEGIN_DATE @;
		PUT FORBEARANCE_END_DATE @;
		PUT DEFERMENT_TYPE $ @;
		PUT SPOUSAL_CONSOLIDATION_LOAN $ @;
		PUT FILLER $ ;
		;
	END;
RUN;

/***********EXPORTS AS CSV*********************/
*TODO: DOUBLE-CHECK CSV OUTPUT FORMATTING (not checked due to strict time constraint);
 *This section produces a .csv file whose formatting probably depends on the local machine's regional settings 
Control Panel > Region and Language > Formats > Additional Settings... > List separator: > and then choose | ;
/*FILENAME REPORT3 "&RPTLIB/CRI_Audit_Files_-_Current_Lender_&RUNDATE2..csv";*/
/*DATA _NULL_ */
/*	(DROP=*/
/*		FIRST_DISBURSEMENT_AMT*/
/*		CANCELLATION_AMT*/
/*		RETURN_TO_LENDER_AMT*/
/*		CURRENT_PRINCIPAL_BAL*/
/*		LATE_FEES_ASS*/
/*		CAPITALIZED_INT*/
/*		TOTAL_BORROWER_PMT*/
/*	);*/
/*	SET WORK.DEMO (RENAME =*/
/*		(*/
/*			FIRST_DISBURSEMENT_AMOUNT = FIRST_DISBURSEMENT_AMT*/
/*			CANCELLATION_AMOUNT = CANCELLATION_AMT*/
/*			RETURN_TO_LENDER_AMOUNT = RETURN_TO_LENDER_AMT*/
/*			CURRENT_PRINCIPAL_BALANCE = CURRENT_PRINCIPAL_BAL*/
/*			LATE_FEES_ASSESSED = LATE_FEES_ASS*/
/*			CAPITALIZED_INTEREST = CAPITALIZED_INT*/
/*			TOTAL_BORROWER_PAYMENTS = TOTAL_BORROWER_PMT*/
/*		)*/
/*	);*/
/*	FILE REPORT3;*/
/*	FORMAT*/
/* 		BF_SSN $9.*/
/*		FIRST_DISBURSEMENT_AMOUNT Z8.*/
/*		CANCELLATION_AMOUNT Z8.*/
/*		RETURN_TO_LENDER_AMOUNT Z8.*/
/*		CURRENT_PRINCIPAL_BALANCE Z8.*/
/*		LATE_FEES_ASSESSED Z8.*/
/*		CAPITALIZED_INTEREST Z8.*/
/*		TOTAL_BORROWER_PAYMENTS Z8.*/
/*		CURRENT_INTEREST_RATE Z5.*/
/**/
/*		LAST_NAME $QUOTE35. */
/*		FIRST_NAME $QUOTE15. */
/*		MIDDLE_INITIAL $1. */
/*		DD_BRT YYMMDDn8. */
/*		LF_LON_CUR_OWN $6. */
/*		LD_OWN_EFF_SR YYMMDDn8. */
/*		PREVIOUS_LENDER_CODE $6. */
/*		ORIGINAL_HOLDER $6. */
/*		CURRENT_GUARANTOR_CODE $3. */
/*		CURRENT_GUARANTOR_EFFECTIVE_DATE YYMMDDn8. */
/*		PREVIOUS_GUARANTOR_EFF_DTE $8. */
/*		ORIGINAL_GUARANTOR_CODE $3. */
/*		ORIGINAL_GUARANTOR_EFF_DTE $8. */
/*		CURRENT_SERVICER_CODE $6. */
/*		CURRENT_SERVICER_EFFECTIVE_DATE YYMMDDn8. */
/*		PREVIOUS_SERVICER_CODE $6. */
/*		PREVIOUS_SERVICER_EFFECTIVE_DATE $8. */
/*		ORIGINAL_SERVICER_CODE $6. */
/*		ORG_SERVICER_CODE_EFF_DTE $8. */
/*		BWR_ELECTRONIC_SIG_INDICATOR_CDE $1. */
/*		E_SIGNATURE_SOURCE_TYPE_CODE $7. */
/*		COMMONLINE_UNIQUE_ID $17. */
/*		COMMONLINE_UNIQUE_ID_SEQUENCE 2. */
/*		UNIQUE_LOAN_ID $16. */
/*		GUARANTY_DATE YYMMDDn8. */
/*		LOAN_PERIOD_BEGIN_DATE YYMMDDn8. */
/*		LOAN_PERIOD_END_DATE YYMMDDn8. */
/*		FIRST_DISBURSEMENT_DATE YYMMDDn8. */
/*		LOAN_STATUS_CODE $2. */
/*		CANCELLATION_DATE YYMMDDn8. */
/*		RETURN_TO_LENDER_DATE YYMMDDn8. */
/*		OUT_OF_SCHOOL_DATE YYMMDDn8. */
/*		DATE_ENTERED_REPAYMENT YYMMDDn8. */
/*		IBR_CODE $1. */
/*		PFH_IBR_PAYMENT_PLAN_TYPE_CODE $2. */
/*		DAYS_DELINQUENT 8. */
/*		LOAN_TYPE $LON_STA. */
/*		CLAIM_PAID_DATE YYMMDDn8. */
/*		LOAN_TRANSFER_DATE $8. */
/*		DEFERMENT_BEGIN_DATE YYMMDDn8. */
/*		DEFERMENT_END_DATE YYMMDDn8. */
/*		FORBEARANCE_BEGIN_DATE YYMMDDn8. */
/*		FORBEARANCE_END_DATE YYMMDDn8. */
/*		DEFERMENT_TYPE $DEF_TYP.*/
/*		SPOUSAL_CONSOLIDATION_LOAN $1. */
/*		FILLER $75. */
/*	;*/
/**/
/*/*	replace dummy dates with all zeros, since all zeros is not a valid date, a new character variable has to be created*/*/
/*	IF PREVIOUS_HOLDER_EFFECTIVE_DATE = '31DEC9999'D THEN PREV_HOLDER_EFFECTIVE_DATE = '00000000'; */
/*		ELSE PREV_HOLDER_EFFECTIVE_DATE = PUT(PREVIOUS_HOLDER_EFFECTIVE_DATE,YYMMDDn8.);*/
/*	IF ORIGINAL_HOLDER_EFFECTIVE_DATE = '31DEC9999'D THEN ORIG_HOLDER_EFFECTIVE_DATE = '00000000'; */
/*		ELSE ORIG_HOLDER_EFFECTIVE_DATE = PUT(ORIGINAL_HOLDER_EFFECTIVE_DATE,YYMMDDn8.);*/
/*	IF LOAN_STATUS_DATE = '31DEC9999'D THEN LN_STATUS_DATE = '00000000'; */
/*		ELSE LN_STATUS_DATE = PUT(LOAN_STATUS_DATE,YYMMDDn8.);*/
/*	IF DATE_LOAN_SOLD = '31DEC9999'D THEN DT_LOAN_SOLD = '00000000'; */
/*		ELSE DT_LOAN_SOLD = PUT(DATE_LOAN_SOLD,YYMMDDn8.);*/
/*	IF LOAN_PURCHASE_DATE = '31DEC9999'D THEN LN_PURCHASE_DATE = '00000000'; */
/*		ELSE LN_PURCHASE_DATE = PUT(LOAN_PURCHASE_DATE,YYMMDDn8.);*/
/*	IF PFH_START_DT = '31DEC9999'D THEN PFH_START_DATE = '00000000'; */
/*		ELSE PFH_START_DATE = PUT(PFH_START_DT,YYMMDDn8.);*/
/**/
/*/*	prepares for z. padding*/*/
/*	FIRST_DISBURSEMENT_AMOUNT = FIRST_DISBURSEMENT_AMT * 100 ;*/
/*	CANCELLATION_AMOUNT = CANCELLATION_AMT * 100 ;*/
/*	RETURN_TO_LENDER_AMOUNT = RETURN_TO_LENDER_AMT * 100 ;*/
/*	CURRENT_PRINCIPAL_BALANCE = CURRENT_PRINCIPAL_BAL * 100 ;*/
/*	LATE_FEES_ASSESSED = LATE_FEES_ASS * 100 ;*/
/*	CAPITALIZED_INTEREST = CAPITALIZED_INT * 100 ;*/
/*	TOTAL_BORROWER_PAYMENTS = TOTAL_BORROWER_PMT * 100 ;*/
/**/
/*	IF _N_ = 1 THEN        /* WRITE COLUMN NAMES */*/
/*		DO;			*/
/*			PUT 'BF_SSN,' @;*/
/*			PUT 'LAST_NAME,' @;*/
/*			PUT 'FIRST_NAME,' @;*/
/*			PUT 'MIDDLE_INITIAL,' @;*/
/*			PUT 'DATE_OF_BIRTH,' @;*/
/*			PUT 'CURRENT_LENDER_CODE,' @;*/
/*			PUT 'CURRENT_HOLDER_EFFECTIVE_DATE,' @;*/
/*			PUT 'PREVIOUS_LENDER_CODE,' @;*/
/*			PUT 'PREVIOUS_HOLDER_EFFECTIVE_DATE,' @;*/
/*			PUT 'ORIGINAL_HOLDER,' @;*/
/*			PUT 'ORIGINAL_HOLDER_EFFECTIVE_DATE,' @;*/
/*			PUT 'CURRENT_GUARANTOR_CODE,' @;*/
/*			PUT 'CURRENT_GUARANTOR_EFFECTIVE_DATE,' @;*/
/*			PUT 'PREVIOUS_GUARANTOR_CODE,' @;*/
/*			PUT 'PREVIOUS_GUARANTOR_EFFECTIVE_DATE,' @;*/
/*			PUT 'ORIGINAL_GUARANTOR_CODE,' @;*/
/*			PUT 'ORIGINAL_GUARANTOR_EFFECTIVE_DATE,' @;*/
/*			PUT 'CURRENT_SERVICER_CODE,' @;*/
/*			PUT 'CURRENT_SERVICER_EFFECTIVE_DATE,' @;*/
/*			PUT 'PREVIOUS_SERVICER_CODE,' @;*/
/*			PUT 'PREVIOUS_SERVICER_EFFECTIVE_DATE,' @;*/
/*			PUT 'ORIGINAL_SERVICER_CODE,' @;*/
/*			PUT 'ORIGINAL_SERVICER_CODE_EFFECTIVE_DATE,' @;*/
/*			PUT 'BORROWER_ELECTRONIC_SIGNATURE_INDICATOR_CODE,' @;*/
/*			PUT 'E_SIGNATURE_SOURCE_TYPE_CODE,' @;*/
/*			PUT 'COMMONLINE_UNIQUE_ID,' @;*/
/*			PUT 'COMMONLINE_UNIQUE_ID_SEQUENCE,' @;*/
/*			PUT 'UNIQUE_LOAN_ID,' @;*/
/*			PUT 'GUARANTY_DATE,' @;*/
/*			PUT 'LOAN_PERIOD_BEGIN_DATE,' @;*/
/*			PUT 'LOAN_PERIOD_END_DATE,' @;*/
/*			PUT 'FIRST_DISBURSEMENT_DATE,' @;*/
/*			PUT 'FIRST_DISBURSEMENT_AMOUNT,' @;*/
/*			PUT 'LOAN_STATUS_CODE,' @;*/
/*			PUT 'LOAN_STATUS_DATE,' @;*/
/*			PUT 'CANCELLATION_DATE,' @;*/
/*			PUT 'CANCELLATION_AMOUNT,' @;*/
/*			PUT 'RETURN_TO_LENDER_DATE,' @;*/
/*			PUT 'RETURN_TO_LENDER_AMOUNT,' @;*/
/*			PUT 'OUT_OF_SCHOOL_DATE,' @;*/
/*			PUT 'DATE_ENTERED_REPAYMENT,' @;*/
/*			PUT 'CURRENT_INTEREST_RATE,' @;*/
/*			PUT 'IBR_CODE,' @;*/
/*			PUT 'PFH_IBR_PAYMENT_PLAN_TYPE_CODE,' @;*/
/*			PUT 'PFH_START_DATE,' @;*/
/*			PUT 'TOTAL_BORROWER_PAYMENTS,' @;*/
/*			PUT 'CURRENT_PRINCIPAL_BALANCE,' @;*/
/*			PUT 'LATE_FEES_ASSESSED,' @;*/
/*			PUT 'DAYS_DELINQUENT,' @;*/
/*			PUT 'LOAN_TYPE,' @;*/
/*			PUT 'CLAIM_PAID_DATE,' @;*/
/*			PUT 'CAPITALIZED_INTEREST,' @;*/
/*			PUT 'LOAN_PURCHASE_DATE,' @;*/
/*			PUT 'DATE_LOAN_SOLD,' @;*/
/*			PUT 'LOAN_TRANSFER_DATE,' @;*/
/*			PUT 'DEFERMENT_BEGIN_DATE,' @;*/
/*			PUT 'DEFERMENT_END_DATE,' @;*/
/*			PUT 'FORBEARANCE_BEGIN_DATE,' @;*/
/*			PUT 'FORBEARANCE_END_DATE,' @;*/
/*			PUT 'DEFERMENT_TYPE,' @;*/
/*			PUT 'SPOUSAL_CONSOLIDATION_LOAN,' @;*/
/*			PUT 'FILLER'*/
/*			;*/
/*		END;*/
/*;*/
/*	DO;*/
/*		EFIOUT + 1;*/
/*		PUT BF_SSN $ @; */
/*		PUT',' LAST_NAME $ @; */
/*		PUT',' FIRST_NAME $ @; */
/*		PUT',' MIDDLE_INITIAL $ @; */
/*		PUT',' DD_BRT @;*/
/*		PUT',' LF_LON_CUR_OWN $ @; */
/*		PUT',' LD_OWN_EFF_SR @;*/
/*		PUT',' PREVIOUS_LENDER_CODE $ @; */
/*		PUT',' PREV_HOLDER_EFFECTIVE_DATE $ @; */
/*		PUT',' ORIGINAL_HOLDER $ @; */
/*		PUT',' ORIG_HOLDER_EFFECTIVE_DATE @;*/
/*		PUT',' CURRENT_GUARANTOR_CODE $ @; */
/*		PUT',' CURRENT_GUARANTOR_EFFECTIVE_DATE @;*/
/*		PUT',' PREVIOUS_GUARANTOR_CODE $ @; */
/*		PUT',' PREVIOUS_GUARANTOR_EFF_DTE $ @; */
/*		PUT',' ORIGINAL_GUARANTOR_CODE $ @; */
/*		PUT',' ORIGINAL_GUARANTOR_EFF_DTE $ @; */
/*		PUT',' CURRENT_SERVICER_CODE $ @; */
/*		PUT',' CURRENT_SERVICER_EFFECTIVE_DATE @;*/
/*		PUT',' PREVIOUS_SERVICER_CODE $ @; */
/*		PUT',' PREVIOUS_SERVICER_EFFECTIVE_DATE $ @; */
/*		PUT',' ORIGINAL_SERVICER_CODE $ @; */
/*		PUT',' ORG_SERVICER_CODE_EFF_DTE $ @; */
/*		PUT',' BWR_ELECTRONIC_SIG_INDICATOR_CDE $ @; */
/*		PUT',' E_SIGNATURE_SOURCE_TYPE_CODE $ @; */
/*		PUT',' COMMONLINE_UNIQUE_ID $ @; */
/*		PUT',' COMMONLINE_UNIQUE_ID_SEQUENCE @;*/
/*		PUT',' UNIQUE_LOAN_ID $ @; */
/*		PUT',' GUARANTY_DATE @;*/
/*		PUT',' LOAN_PERIOD_BEGIN_DATE @;*/
/*		PUT',' LOAN_PERIOD_END_DATE @;*/
/*		PUT',' FIRST_DISBURSEMENT_DATE @;*/
/*		PUT',' FIRST_DISBURSEMENT_AMOUNT @;*/
/*		PUT',' LOAN_STATUS_CODE $ @; */
/*		PUT',' LN_STATUS_DATE @;*/
/*		PUT',' CANCELLATION_DATE @;*/
/*		PUT',' CANCELLATION_AMOUNT @;*/
/*		PUT',' RETURN_TO_LENDER_DATE @;*/
/*		PUT',' RETURN_TO_LENDER_AMOUNT @;*/
/*		PUT',' OUT_OF_SCHOOL_DATE @;*/
/*		PUT',' DATE_ENTERED_REPAYMENT @;*/
/*		PUT',' CURRENT_INTEREST_RATE @;*/
/*		PUT',' IBR_CODE $ @; */
/*		PUT',' PFH_IBR_PAYMENT_PLAN_TYPE_CODE $ @; */
/*		PUT',' PFH_START_DATE @;*/
/*		PUT',' TOTAL_BORROWER_PAYMENTS @;*/
/*		PUT',' CURRENT_PRINCIPAL_BALANCE @;*/
/*		PUT',' LATE_FEES_ASSESSED @;*/
/*		PUT',' DAYS_DELINQUENT @;*/
/*		PUT',' LOAN_TYPE $ @; */
/*		PUT',' CLAIM_PAID_DATE @;*/
/*		PUT',' CAPITALIZED_INTEREST @;*/
/*		PUT',' LN_PURCHASE_DATE $ @; */
/*		PUT',' DT_LOAN_SOLD $ @; */
/*		PUT',' LOAN_TRANSFER_DATE @;*/
/*		PUT',' DEFERMENT_BEGIN_DATE @;*/
/*		PUT',' DEFERMENT_END_DATE @;*/
/*		PUT',' FORBEARANCE_BEGIN_DATE @;*/
/*		PUT',' FORBEARANCE_END_DATE @;*/
/*		PUT',' DEFERMENT_TYPE $ @; */
/*		PUT',' SPOUSAL_CONSOLIDATION_LOAN $ @; */
/*		PUT',' FILLER $ */
/*		;*/
/*	END;*/
/*RUN;*/
;
%WINDOW Message 
	COLUMNS=100 ROWS=20 IROW=15 ICOLUMN=15
	#4 @ 5 'CRI Audit Reports query has finished running.'
	#6 @ 5 'A text file has been produced in your T:\SAS\ folder.'
	#8 @ 5 'It must be manually imported into the first column of a .csv prior to submission.'
; 
%DISPLAY Message; 
%PUT NOTE: CRI Audit Reports query has finished running.;

*initialize input variables;
%SYMDEL LENDER GUARANTOR B1 B2 B3 E1 E2 E3 BEGIN END / NOWARN;
