/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/ULWS51.LWS51R2";
LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
PROC SQL;
CREATE TABLE DEMO AS
SELECT A.DF_SPE_ACC_ID
	,TRIM(A.DM_PRS_1) || COALESCE(' ' || TRIM(A.DM_PRS_MID) || ' ',' ') || TRIM(A.DM_PRS_LST) AS B_NAME
	,C.DX_ADR_EML
	,CASE
		WHEN DC_ADR_EML = 'H' THEN '1'
		ELSE '2'
	END AS EML_CODE
FROM DLGSUTWH.FB10_BR_FOR_REQ B 
INNER JOIN DLGSUTWH.PD10_PRS_NME A
	ON A.DF_PRS_ID = B.BF_SSN
INNER JOIN DLGSUTWH.PD32_PRS_ADR_EML C
	ON A.DF_PRS_ID = C.DF_PRS_ID
WHERE B.LC_FOR_STA = 'A'
	AND B.LC_STA_FOR10 = 'A'
	AND B.LD_CRT_REQ_FOR >= TODAY()-30
	AND B.LC_FOR_TYP IN ('01','05','07','21','22','31','43')
	AND C.DI_VLD_ADR_EML = 'Y'
	AND C.DC_STA_PD32 = 'A';
QUIT;
PROC SORT DATA=DEMO; BY DF_SPE_ACC_ID EML_CODE; RUN;
DATA DEMO(DROP=EML_CODE); SET DEMO; BY DF_SPE_ACC_ID; IF FIRST.DF_SPE_ACC_ID; RUN;
ENDRSUBMIT;
DATA DEMO;
	SET WORKLOCL.DEMO;
RUN;
DATA _NULL_;
SET DEMO  ;
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
IF _N_ = 1 THEN DO;
	PUT "ACCOUNTNUMBER,NAME,RECIPIENT";
END;
DO;
   PUT DF_SPE_ACC_ID @;
   PUT B_NAME @;
   PUT DX_ADR_EML $ ;
END;
RUN;
