PROC SQL;
CONNECT TO ODBC AS REGENT (REQUIRED="FILEDSN=X:\PADR\ODBC\REGENTS.dsn;");
CREATE TABLE REGENTS_DATA AS
SELECT *
FROM CONNECTION TO REGENT (
SELECT A.STATESTUDENTID
	,A.FIRSTNAME
	,A.MIDDLENAME
	,A.LASTNAME
	,J.ADDRESS1
	,J.ADDRESS2
	,J.CITY
	,K.ABBREVIATION AS STATE
	,J.ZIP
	,J.COUNTRY
		,N.DESCRIPTION AS COLLEGE	
		,O.APPLICATIONYEAR			
		,Q.DESCRIPTION AS TERM
		,O.COLLEGECREDITSENROLLED	
/*		PAYMENT TYPE(AWARD)*/
		,CASE
			WHEN O.BASEAWARDAMOUNTCODE IN (5,6) THEN 'Base Award'
		END	AS BASEAWARD
/*		,O.BASEAWARDAMOUNTCODE	*/
		,CASE
			WHEN O.EXEMPLARYAWARDISEARNED = 1 THEN 'Exemplary Award'
		END	AS EXEMPLAR
		,CASE 
			WHEN O.UESPSUPPLEMENTALAWARDISAPPROVED = 1 THEN 'UESP Supplemental Award'
		END	AS UESPSUPP
FROM SCHOLARSHIPAPPLICATION O
LEFT OUTER JOIN COLLEGELOOKUP N
	ON O.PLANNEDCOLLEGETOATTENDCODE = N.CODE
LEFT OUTER JOIN STUDENT A
	ON A.STATESTUDENTID = O.STATESTUDENTID
LEFT OUTER JOIN COLLEGETERMLOOKUP Q
	ON O.COLLEGETERMCODE = Q.CODE
LEFT OUTER JOIN STUDENTADDRESS J
	ON O.STATESTUDENTID = J.STATESTUDENTID
LEFT OUTER JOIN STATELOOKUP K
	ON J.STATECODE = K.CODE
WHERE O.APPLICATIONYEAR = '2010'
	AND O.AWARDSTATUSCODE = '1'
);

DISCONNECT FROM REGENT;
QUIT;

PROC EXPORT DATA= WORK.REGENTS_DATA 
            OUTFILE= "J:\Regents Scholarships\Regents_SCHOLARSHIP_APPROVAL_2010.csv" 
            DBMS=CSV REPLACE;
     PUTNAMES=YES;
RUN;
