CREATE PROCEDURE [dbo].[GetAllUnprocessedLt20Records]
	
AS
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT DISTINCT
	LT20.DF_SPE_ACC_ID,
	LT20.RM_APL_PGM_PRC,
	LT20.RT_RUN_SRT_DTS_PRC,
	LT20.RN_SEQ_LTR_CRT_PRC, 
	LT20.RM_DSC_LTR_PRC,
	LT20.RF_SBJ_PRC,
	CASE WHEN DW01.BF_SSN IS NULL 
		THEN 0
		ELSE 1
	END AS InvalidLoanStatus,
	CASE WHEN LTR.LF_ATY_RCP != LT20.RF_SBJ_PRC 
		THEN LTR.LF_ATY_RCP
		ELSE ''
	END AS EndorsersSsn,
	LT20.OnEcorr,
	ISNULL(PH05.DX_CNC_EML_ADR, 'ecorr@utahsbr.edu') AS EmailAddress,
	sr.Recipient,
	LT20.PrintedAt,
	LT20.EcorrDocumentCreatedAt,
	0 AS IsCoborrower,
	'' AS CoborrowerSSN,
	CASE WHEN sr.Recipient IS NULL 
		THEN LT20.DF_SPE_ACC_ID
	    ELSE LTR.LF_ATY_RCP 
	END AS LetterAccountNumber,
	LT20.ProcessingAttempts
FROM
	LT20_LTR_REQ_PRC LT20
	INNER JOIN PD10_PRS_NME PD10
		ON PD10.DF_SPE_ACC_ID = LT20.DF_SPE_ACC_ID
	INNER JOIN
	(
		SELECT
			LT20_I.DF_SPE_ACC_ID,
			LT20_I.RM_APL_PGM_PRC,
			LT20_I.RT_RUN_SRT_DTS_PRC,
			LT20_I.RN_SEQ_LTR_CRT_PRC,
			MIN(LT20_I.RN_SEQ_REC_PRC) OVER(PARTITION BY LT20_I.DF_SPE_ACC_ID, LT20_I.RM_APL_PGM_PRC, LT20_I.RT_RUN_SRT_DTS_PRC, LT20_I.RN_SEQ_LTR_CRT_PRC, LT20_I.RM_DSC_LTR_PRC) AS RN_SEQ_REC_PRC,
			LT20_I.RM_DSC_LTR_PRC
		FROM
			LT20_LTR_REQ_PRC LT20_I
		WHERE
			DATEDIFF(MONTH,LT20_I.CreatedAt,GETDATE()) <= 6
	) MIN_REC
		ON MIN_REC.DF_SPE_ACC_ID = LT20.DF_SPE_ACC_ID
		AND MIN_REC.RM_APL_PGM_PRC = LT20.RM_APL_PGM_PRC
		AND MIN_REC.RT_RUN_SRT_DTS_PRC = LT20.RT_RUN_SRT_DTS_PRC
		AND MIN_REC.RN_SEQ_LTR_CRT_PRC = LT20.RN_SEQ_LTR_CRT_PRC
		AND MIN_REC.RN_SEQ_REC_PRC = LT20.RN_SEQ_REC_PRC
		AND MIN_REC.RM_DSC_LTR_PRC = LT20.RM_DSC_LTR_PRC
	LEFT JOIN CLS.dbo.SystemLetterExclusions SLE
		ON SLE.LetterId = LT20.RM_DSC_LTR_PRC
	LEFT JOIN PH05_CNC_EML PH05
		ON PH05.DF_SPE_ID = LT20.DF_SPE_ACC_ID
	LEFT JOIN 
	(
		SELECT DISTINCT
			BF_SSN
		FROM
			DW01_DW_CLC_CLU
		WHERE
			WC_DW_LON_STA IN ('17','19','21')
	) DW01
	ON DW01.BF_SSN = PD10.DF_PRS_ID
	LEFT JOIN
	(
		SELECT
			AY10.BF_SSN,
			AY10.LF_ATY_RCP,
			MST_RCT_ARC.PF_LTR,
			AY10.LD_ATY_REQ_RCV
		FROM
			AY10_BR_LON_ATY AY10
			INNER JOIN 
			(
				SELECT	
					AY10.BF_SSN,
					AY10.PF_REQ_ACT,
					AC11.PF_LTR,
					MAX(AY10.LN_ATY_SEQ) AS LN_ATY_SEQ
				FROM
					AY10_BR_LON_ATY AY10
					INNER JOIN AC11_ACT_REQ_LTR AC11
						ON AC11.PF_REQ_ACT = AY10.PF_REQ_ACT
				WHERE
					DATEDIFF(DAY, AY10.LF_LST_DTS_AY10, GETDATE()) <= 14
				GROUP BY
					AY10.BF_SSN,
					AY10.PF_REQ_ACT,
					AC11.PF_LTR
			)MST_RCT_ARC
				ON MST_RCT_ARC.BF_SSN = AY10.BF_SSN
				AND MST_RCT_ARC.LN_ATY_SEQ = AY10.LN_ATY_SEQ
	)LTR
		ON LTR.BF_SSN = LT20.RF_SBJ_PRC
		AND LTR.PF_LTR = LT20.RM_DSC_LTR_PRC
	LEFT JOIN CLS.dbo.SpecialLetterRecipients SR
		ON SR.LetterId = lt20.RM_DSC_LTR_PRC
	LEFT JOIN CLS.dbo.LetterDelay LD
		ON LD.Letter = LT20.RM_DSC_LTR_PRC
WHERE
	(
		(
			LT20.PrintedAt IS NULL 
			AND LT20.OnEcorr = 0
		) 
		OR 
		(
			LT20.EcorrDocumentCreatedAt IS NULL
			AND SR.LetterId IS NULL --Dont care about ecorr for special letters
		)
		OR
		(
			LT20.PrintedAt IS NULL
			AND SR.LetterId IS NOT NULL
		)
	)
	AND LT20.InactivatedAt IS NULL
	AND LT20.RI_LTR_REQ_DEL_PRC = 'N'
	AND SLE.LetterId IS NULL
	AND DATEDIFF(MONTH,LT20.CreatedAt,GETDATE()) <= 6
	AND GETDATE() > DATEADD(HOUR, 4 * LT20.ProcessingAttempts, LT20.CreatedAt)
	--Don't process TSIDHDPFED letters on the day the ARC is received
	AND
	(
		LD.LetterDelayId IS NULL
		OR
		(
			DATEDIFF(DAY, LTR.LD_ATY_REQ_RCV, GETDATE()) >= LD.[Days] 
		)
	)

UNION ALL

SELECT DISTINCT
	LT20.DF_SPE_ACC_ID,
	LT20.RM_APL_PGM_PRC,
	LT20.RT_RUN_SRT_DTS_PRC,
	LT20.RN_SEQ_LTR_CRT_PRC, 
	LT20.RM_DSC_LTR_PRC,
	LT20.RF_SBJ_PRC,
	CASE WHEN DW01.BF_SSN IS NULL 
		THEN 0
		ELSE 1
	END AS InvalidLoanStatus,
	CASE WHEN LN20.LF_EDS != LT20.RF_SBJ_PRC 
		THEN LN20.LF_EDS
		ELSE ''
	END AS EndorsersSsn,
	LT20.OnEcorr,
	ISNULL(PH05.DX_CNC_EML_ADR, 'ecorr@utahsbr.edu') AS EmailAddress,
	sr.Recipient,
	LT20.PrintedAt,
	LT20.EcorrDocumentCreatedAt,
	1 AS IsCoborrower,
	LN20.LF_EDS AS CoborrowerSSN,
	LT20.Borrower_DF_SPE_ACC_ID AS LetterAccountNumber,
	LT20.ProcessingAttempts
FROM
	LT20_LTR_REQ_PRC_Coborrower LT20
	INNER JOIN PD10_PRS_NME PD10
		ON PD10.DF_SPE_ACC_ID = LT20.DF_SPE_ACC_ID
	INNER JOIN
	(
		SELECT
			LT20_I.DF_SPE_ACC_ID,
			LT20_I.RM_APL_PGM_PRC,
			LT20_I.RT_RUN_SRT_DTS_PRC,
			LT20_I.RN_SEQ_LTR_CRT_PRC,
			MIN(LT20_I.RN_SEQ_REC_PRC) OVER(PARTITION BY LT20_I.DF_SPE_ACC_ID, LT20_I.RM_APL_PGM_PRC, LT20_I.RT_RUN_SRT_DTS_PRC, LT20_I.RN_SEQ_LTR_CRT_PRC, LT20_I.RM_DSC_LTR_PRC) AS RN_SEQ_REC_PRC,
			LT20_I.RM_DSC_LTR_PRC
		FROM
			LT20_LTR_REQ_PRC_Coborrower LT20_I
		WHERE
			DATEDIFF(MONTH,LT20_I.CreatedAt,GETDATE()) <= 6
	) MIN_REC
		ON MIN_REC.DF_SPE_ACC_ID = LT20.DF_SPE_ACC_ID
		AND MIN_REC.RM_APL_PGM_PRC = LT20.RM_APL_PGM_PRC
		AND MIN_REC.RT_RUN_SRT_DTS_PRC = LT20.RT_RUN_SRT_DTS_PRC
		AND MIN_REC.RN_SEQ_LTR_CRT_PRC = LT20.RN_SEQ_LTR_CRT_PRC
		AND MIN_REC.RN_SEQ_REC_PRC = LT20.RN_SEQ_REC_PRC
		AND MIN_REC.RM_DSC_LTR_PRC = LT20.RM_DSC_LTR_PRC
	INNER JOIN LN20_EDS LN20
		ON LN20.LF_EDS = PD10.DF_PRS_ID
		AND LN20.LC_STA_LON20 = 'A'
		AND LN20.LC_EDS_TYP = 'M' --coborrower
	INNER JOIN PD10_PRS_NME BorrowerPD10
		ON BorrowerPD10.DF_PRS_ID = LN20.BF_SSN
	LEFT JOIN CLS.dbo.SystemLetterExclusions SLE
		ON SLE.LetterId = LT20.RM_DSC_LTR_PRC
	LEFT JOIN PH05_CNC_EML PH05
		ON PH05.DF_SPE_ID = LT20.DF_SPE_ACC_ID
	LEFT JOIN 
	( 
		SELECT DISTINCT
			BF_SSN
		FROM
			DW01_DW_CLC_CLU
		WHERE
			WC_DW_LON_STA IN ('17','19','21')
	) DW01
		ON DW01.BF_SSN = BorrowerPD10.DF_PRS_ID
	LEFT JOIN
	(
		SELECT
			AY10.BF_SSN,
			AY10.LF_ATY_RCP,
			MST_RCT_ARC.PF_LTR,
			AY10.LD_ATY_REQ_RCV
		FROM
			AY10_BR_LON_ATY AY10
			INNER JOIN 
			(
				SELECT	
					AY10.BF_SSN,
					AY10.PF_REQ_ACT,
					AC11.PF_LTR,
					MAX(AY10.LN_ATY_SEQ) AS LN_ATY_SEQ
				FROM
					AY10_BR_LON_ATY AY10
					INNER JOIN AC11_ACT_REQ_LTR AC11
						ON AC11.PF_REQ_ACT = AY10.PF_REQ_ACT
				WHERE
					DATEDIFF(DAY, AY10.LF_LST_DTS_AY10, GETDATE()) <= 14
				GROUP BY
					AY10.BF_SSN,
					AY10.PF_REQ_ACT,
					AC11.PF_LTR
			)MST_RCT_ARC
				ON MST_RCT_ARC.BF_SSN = AY10.BF_SSN
				AND MST_RCT_ARC.LN_ATY_SEQ = AY10.LN_ATY_SEQ
	)LTR
		ON LTR.BF_SSN = BorrowerPD10.DF_PRS_ID
		AND LTR.PF_LTR = LT20.RM_DSC_LTR_PRC
	LEFT JOIN CLS.dbo.SpecialLetterRecipients SR
		ON SR.LetterId = lt20.RM_DSC_LTR_PRC
	LEFT JOIN CLS.dbo.LetterDelay LD
		ON LD.Letter = LT20.RM_DSC_LTR_PRC
WHERE
	(
		(
			LT20.PrintedAt IS NULL 
			AND LT20.OnEcorr = 0
		) 
		OR 
		(
			LT20.EcorrDocumentCreatedAt IS NULL
			AND SR.LetterId IS NULL --Dont care about ecorr for special letters
		)
		OR
		(
			LT20.PrintedAt IS NULL
			AND SR.LetterId IS NOT NULL
		)
	)
	AND LT20.InactivatedAt IS NULL
	AND LT20.RI_LTR_REQ_DEL_PRC = 'N'
	AND SLE.LetterId IS NULL
	AND DATEDIFF(MONTH,LT20.CreatedAt,GETDATE()) <= 6
	AND GETDATE() > DATEADD(HOUR, 4 * LT20.ProcessingAttempts, LT20.CreatedAt)
	--Don't process TSIDHDPFED letters on the day the ARC is received
	AND
	(
		LD.LetterDelayId IS NULL
		OR
		(
			DATEDIFF(DAY, LTR.LD_ATY_REQ_RCV, GETDATE()) >= LD.[Days] 
		)
	)
