CREATE FUNCTION [tcpapns].[JulianDateConversion]
(
	@GroupKey VARCHAR(50),
	@Date DATETIME
)
RETURNS VARCHAR(10)
AS
BEGIN
	RETURN CASE WHEN @GroupKey LIKE '%RF@%' OR @GroupKey LIKE '%P%' THEN @GroupKey
		ELSE RIGHT('0000000000' + RTRIM(CAST(CAST((CAST(@GroupKey AS BIGINT) / CAST(CONCAT((YEAR(@Date) % 100 ) , RIGHT('000' + CAST(DATEPART(DAYOFYEAR, @Date) AS VARCHAR(3)), 3)) AS BIGINT)) AS BIGINT) AS VARCHAR(MAX))) ,10) --Julian Conversion
	END	
END	