/*UTLWK08 COMPASS REFERENCE NOT ON ONELINK*/

/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
/*FILENAME REPORT2 "&RPTLIB/ULWK08.LWK08R2";*/
/*FILENAME REPORTZ "&RPTLIB/ULWK08.LWK08RZ";*/

LIBNAME  WORKLOCL  REMOTE  SERVER=DUSTER  SLIBREF=WORK;
RSUBMIT;

%MACRO SQLCHECK (SQLRPT= );
%IF &SQLXRC NE 0 %THEN %DO;
	DATA _NULL_;
    FILE REPORTZ NOTITLES;
    PUT @01 " ********************************************************************* "
      / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
      / @01 " ****  THE SAS LOG IN &SQLRPT SHOULD BE REVIEWED.          **** "       
      / @01 " ********************************************************************* "
      / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
      / @01 " ****  &SQLXMSG   **** "
      / @01 " ********************************************************************* ";
	RUN;
%END;
%MEND;

PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE CREF AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT A.BF_SSN
	,C.BF_RFR 		AS CO_REF_ID
	,D.DM_PRS_1 	AS CO_REF_1NM
	,D.DM_PRS_MID	AS CO_REF_MNM
	,D.DM_PRS_LST 	AS CO_REF_LNM
	,F.DX_STR_ADR_1 AS CO_REF_ADD
	,F.DX_STR_ADR_2 
	,F.DC_DOM_ST
	,F.DI_VLD_ADR
	,F.DF_ZIP_CDE
	,F.DM_CT
	,G.DI_PHN_VLD
	,G.DN_DOM_PHN_LCL
	,G.DN_DOM_PHN_XCH
	,G.DN_DOM_PHN_ARA
	,C.BC_RFR_REL_BR 
FROM OLWHRM1.LN10_LON A
INNER JOIN OLWHRM1.PD26_PRS_SKP_PRC B
	ON A.BF_SSN = B.DF_PRS_ID_BR
	AND B.DC_SKP_STA IN ('W','P')
INNER JOIN OLWHRM1.RF10_RFR C 
	ON A.BF_SSN = C.BF_SSN
	AND C.BC_STA_REFR10 = 'A'
INNER JOIN OLWHRM1.PD10_PRS_NME D
	ON C.BF_RFR = D.DF_PRS_ID
INNER JOIN OLWHRM1.BR03_BR_REF E
	ON B.DF_PRS_ID_BR = E.DF_PRS_ID_BR
INNER JOIN OLWHRM1.PD30_PRS_ADR F
	ON C.BF_RFR = F.DF_PRS_ID
LEFT OUTER JOIN OLWHRM1.PD42_PRS_PHN G
	ON C.BF_RFR = G.DF_PRS_ID
WHERE A.LA_CUR_PRI > 0
AND C.BC_RFR_REL_BR NOT IN ('05','13','15')
AND A.LC_STA_LON10 = 'R'
);

CREATE TABLE OREF AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT A.BF_SSN
	,E.DF_PRS_ID_RFR	AS OL_REF_ID 
	,E.BM_RFR_1		 	AS OL_REF_1NM				
	,E.BM_RFR_MID		AS OL_REF_MNM
	,E.BM_RFR_LST		AS OL_REF_LNM
	,E.BX_RFR_STR_ADR_1 AS OL_REF_ADD
FROM OLWHRM1.LN10_LON A
INNER JOIN OLWHRM1.PD26_PRS_SKP_PRC B
	ON A.BF_SSN = B.DF_PRS_ID_BR
	AND B.DC_SKP_STA IN ('W','P')
INNER JOIN OLWHRM1.RF10_RFR C 
	ON A.BF_SSN = C.BF_SSN
	AND C.BC_STA_REFR10 = 'A'
INNER JOIN OLWHRM1.PD10_PRS_NME D
	ON C.BF_RFR = D.DF_PRS_ID
INNER JOIN OLWHRM1.BR03_BR_REF E
	ON B.DF_PRS_ID_BR = E.DF_PRS_ID_BR
WHERE A.LA_CUR_PRI > 0
AND C.BC_RFR_REL_BR NOT IN ('05','13','15')
AND A.LC_STA_LON10 = 'R'
);
DISCONNECT FROM DB2;

/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>>  ;  * INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK (SQLRPT=ULWK08.LWK08RZ);*/
/*QUIT;*/

ENDRSUBMIT;

DATA CREF;SET WORKLOCL.CREF;RUN;
DATA OREF;SET WORKLOCL.OREF;RUN;

%MACRO REF(DS,SYS);
DATA &DS;
LENGTH REF_1NM_ID $ 4. REF_LNM_ID $ 4. REF_ADD_ID $ 4.;
SET &DS;
REF_1NM_ID = SUBSTR(&SYS._REF_1NM,1,4);
REF_LNM_ID = SUBSTR(&SYS._REF_LNM,1,4);
REF_ADD_ID = SUBSTR(&SYS._REF_ADD,1,4);
RUN;
PROC SORT DATA=&DS;
BY BF_SSN REF_1NM_ID REF_LNM_ID REF_ADD_ID;
RUN;
%MEND REF;

%REF(CREF,CO);
%REF(OREF,OL);

DATA CREF_ONLY;
MERGE CREF (IN=A) OREF (IN=B);
BY BF_SSN REF_1NM_ID REF_LNM_ID REF_ADD_ID;
IF A AND NOT B THEN OUTPUT CREF_ONLY;
ELSE DELETE;
RUN;

DATA CREF_ONLY (DROP=BC_RFR_REL_BR);
SET CREF_ONLY;
LENGTH REL $ 21.;
IF BC_RFR_REL_BR = '01' THEN REL = 'OTHER';
ELSE IF BC_RFR_REL_BR = '02' THEN REL = 'PARENT';
ELSE IF BC_RFR_REL_BR = '03' THEN REL = 'RELATIVE';
ELSE IF BC_RFR_REL_BR = '04' THEN REL = 'NON-RELATIVE / FRIEND';
ELSE IF BC_RFR_REL_BR = '06' THEN REL = 'SPOUSE';
ELSE IF BC_RFR_REL_BR = '07' THEN REL = 'SIBLING';
ELSE IF BC_RFR_REL_BR = '08' THEN REL = 'ROOM MATE';
ELSE IF BC_RFR_REL_BR = '09' THEN REL = 'NEIGHBOR';
ELSE IF BC_RFR_REL_BR = '10' THEN REL = 'CHILD';
ELSE IF BC_RFR_REL_BR = '11' THEN REL = 'OTHER';
ELSE IF BC_RFR_REL_BR = '12' THEN REL = 'GUARDIAN';
ELSE IF BC_RFR_REL_BR = '14' THEN REL = 'OTHER';
ELSE IF BC_RFR_REL_BR = '16' THEN REL = 'OTHER';
RUN;

DATA _NULL_;
SET  WORK.CREF_ONLY;
FILE 'T:\SAS\ULWK08.LWK08R2' DELIMITER=',' DSD DROPOVER LRECL=32767;
*FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
FORMAT BF_SSN $9. ;
FORMAT CO_REF_1NM $13. ;
FORMAT CO_REF_MNM $13. ;
FORMAT CO_REF_LNM $23. ;
FORMAT CO_REF_ADD $30. ;
FORMAT DX_STR_ADR_2 $30. ;
FORMAT DC_DOM_ST $2. ;
FORMAT DI_VLD_ADR $1. ;
FORMAT DF_ZIP_CDE $9. ;
FORMAT DM_CT $20. ;
FORMAT DI_PHN_VLD $1. ;
FORMAT DN_DOM_PHN_LCL $4. ;
FORMAT DN_DOM_PHN_XCH $3. ;
FORMAT DN_DOM_PHN_ARA $3. ;
FORMAT REL $21.;
DO;
	PUT BF_SSN $ @;
	PUT CO_REF_1NM $ @;
	PUT CO_REF_LNM $ @;
	PUT CO_REF_MNM $ @;
	PUT DI_VLD_ADR $ @;
	PUT DF_ZIP_CDE $ @;
	PUT DM_CT $ @;
	PUT CO_REF_ADD $ @;
	PUT DX_STR_ADR_2 $ @;
	PUT DC_DOM_ST $ @;
	PUT DI_PHN_VLD $ @;
	PUT DN_DOM_PHN_ARA $ @;
	PUT DN_DOM_PHN_XCH $ @;
	PUT DN_DOM_PHN_LCL $ @;
	PUT REL $;
END;
RUN;
