/*LPP SERVICING DATA FILE FOR FINANCE - MR51 TABLE*/
/*PLEASE NOTE: THIS DIRECTORY HAS BEEN CHANGED TO PROGREVW BECAUSE OF THE SIZE OF THE OUTPUT FILE*/
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = /sas/whse/progrevw   ; */
/*FILENAME REPORT2 "&RPTLIB/ULWE10.LWE10R2";*/

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE LPPFMR51 AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT	A.IF_OWN_PRN,
		A.BF_SSN,
		A.LN_SEQ,
		A.IF_OWN, 
		A.IF_BND_ISS, 
		A.IC_LON_PGM, 
		A.IF_GTR, 
		A.LF_CUR_POR, 
		A.WC_TYP_SCL_ORG, 
		A.WR_ITR_1, 
		A.WC_ITR_TYP_1, 
		A.LD_LON_1_DSB, 
		A.WC_ELG_SIN_1, 
		A.WA_CUR_PRI, 
		A.WA_CUR_BR_INT, 
		A.WA_CUR_GOV_INT, 
		A.WA_CUR_OTH_CHR, 
		A.WD_SAR_ATY_EFF, 
		A.WA_AVG_DAY_BAL, 
		A.WN_SQ_FOR_APL, 
		A.WX_TYP_REC_CLP_LON, 
		A.WF_SUP_ATY_RPT_LN1, 
		A.WF_SUP_ATY_RPT_LN2, 
		A.WF_SUP_ATY_RPT_LN3, 
		A.WF_SUP_ATY_RPT_LN4, 
		A.WF_SUP_ATY_RPT_LN5, 
		A.WF_SUP_ATY_RPT_LN6, 
		A.WF_SUP_ATY_RPT_LN7, 
		A.WF_SUP_ATY_RPT_LN8, 
		A.WF_SUP_ATY_RPT_LN9, 
		A.WF_SAR_LN10, 
		A.LC_SCY_PGA_PGM_YR, 
		A.LC_CU_LIA, 
		A.WA_PRI_CU_BEG, 
		A.WA_BRI_ACR_CU_BEG, 
		A.WA_CLM_PRI_BKR, 
		A.WA_CLM_INT_BKR, 
		A.WA_CLM_PRI_DTH, 
		A.WA_CLM_INT_DTH, 
		A.WA_CLM_PRI_DSA, 
		A.WA_CLM_INT_DSA, 
		A.WA_CLM_PRI_ILG, 
		A.WA_CLM_INT_ILG, 
		A.WA_CLM_PRI_ISL_DLQ, 
		A.WA_CLM_INT_ISL_DLQ, 
		A.WA_CLM_PRI_INT_DLQ, 
		A.WA_CLM_INT_INT_DLQ, 
		A.WA_CLM_PRI_CLS, 
		A.WA_CLM_INT_CLS, 
		A.WA_CLM_PRI_CU, 
		A.WA_CLM_INT_CU, 
		A.WA_CLM_PRI_SUP, 
		A.WA_CLM_INT_SUP, 
		A.WA_CLM_PRI_SKP, 
		A.WA_CLM_INT_SKP, 
		A.WA_CLM_PRI_OTH, 
		A.WA_CLM_INT_OTH, 
		A.WA_ORG_CHK, 
		A.WA_ORG_EFT, 
		A.WN_DSB_CHK_SQ, 
		A.WA_DSB_CHK_SQ, 
		A.WA_DSB_CAN_EFT_1, 
		A.WA_DSB_CAN_CHK_1, 
		A.WN_DSB_CAN_EFT_SQ, 
		A.WA_DSB_CAN_EFT_SQ, 
		A.WN_DSB_CAN_CHK_SQ, 
		A.WA_DSB_CAN_CHK_SQ, 
		A.WA_FAT_CUR_PRI_DCV, 
		A.WA_FAT_NSI_DCV, 
		A.WA_FAT_CUR_PRI_CVN, 
		A.WA_FAT_NSI_CVN, 
		A.WA_FAT_CUR_PRI_TRF, 
		A.WA_FAT_NSI_TRF, 
		A.WA_FAT_CUR_PRI_RPR, 
		A.WA_FAT_NSI_RPR, 
		A.WA_FAT_CUR_PRI_EXT, 
		A.WA_FAT_NSI_EXT, 
		A.WA_FAT_CUR_PRI_NEW, 
		A.WA_FAT_NSI_NEW, 
		A.WA_DSB_EFT_1, 
		A.WA_DSB_CHK_1, 
		A.WN_DSB_EFT_SQ, 
		A.WA_DSB_EFT_SQ, 
		A.LF_DOE_SCL_ORG, 
		A.WF_TIR_PCE_LN35, 
		A.LD_CU_ENT, 
		A.WD_CLM_BKR_SBM, 
		A.WD_CLM_DTH_SBM,
		A.WD_CLM_DSA_SBM, 
		A.WD_CLM_ILG_SBM, 
		A.WD_CLM_ISL_DLQ_SBM, 
		A.WD_CLM_INT_DLQ_SBM,
		A.WD_CLM_CLS_SBM, 
		A.WD_CLM_SKP_SBM, 
		A.WD_CLM_CU_SBM, 
		A.WD_CLM_SUP_SBM, 
		A.WD_CLM_OTH_SBM, 
		A.LD_FOR_BEG, 
		A.LD_END_GRC_PRD, 
		A.WD_DCV_EFF, 
		A.WD_ORG_EFT_EFF, 
		A.WD_ORG_CHK_EFF, 
		A.WD_TRF_EFF,
		A.WD_CVN_EFF, 
		A.WD_RPR_EFF, 
		A.WD_EXT_ORG_EFF, 
		A.WD_NEW_ORG_EFF, 
		A.WD_DSB_EFT_1, 
		A.WD_DSB_CHK_1, 
		A.WD_DSB_EFT_SQ, 
		A.WD_DSB_CHK_SQ, 
		A.WD_DSB_CAN_EFT_1, 
		A.WD_DSB_CAN_CHK_1, 
		A.WD_DSB_CAN_EFT_SQ, 
		A.WD_DSB_CAN_CHK_SQ
FROM	OLWHRM1.MR51_MR_SUP_ATY A

);
DISCONNECT FROM DB2;
ENDRSUBMIT;

DATA LPPFMR51;
SET WORKLOCL.LPPFMR51;
RUN;

PROC SORT DATA=LPPFMR51 NODUPKEY;
BY BF_SSN LN_SEQ;
RUN;

DATA _NULL_;
SET  WORK.LPPFMR51;                               
FILE 'T:\SAS\ULWE10.LWE10R2' DELIMITER=',' DSD DROPOVER LRECL=32767;
*FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
FORMAT IF_OWN_PRN $8. ;
FORMAT BF_SSN $9. ;
FORMAT LN_SEQ 6. ;
FORMAT IF_OWN $8. ;
FORMAT IF_BND_ISS $8. ;
FORMAT IC_LON_PGM $6. ;
FORMAT IF_GTR $6. ;
FORMAT LF_CUR_POR $20. ;
FORMAT WC_TYP_SCL_ORG $2. ;
FORMAT WR_ITR_1 7.3 ;
FORMAT WC_ITR_TYP_1 $2. ;
FORMAT LD_LON_1_DSB MMDDYY10. ;
FORMAT WC_ELG_SIN_1 $1. ;
FORMAT WA_CUR_PRI 10.2 ;
FORMAT WA_CUR_BR_INT 10.2 ;
FORMAT WA_CUR_GOV_INT 9.2 ;
FORMAT WA_CUR_OTH_CHR 9.2 ;
FORMAT WD_SAR_ATY_EFF MMDDYY10. ;
FORMAT WA_AVG_DAY_BAL 10.2 ;
FORMAT WN_SQ_FOR_APL 4. ;
FORMAT WX_TYP_REC_CLP_LON $20. ;
FORMAT WF_SUP_ATY_RPT_LN1 $3. ;
FORMAT WF_SUP_ATY_RPT_LN2 $3. ;
FORMAT WF_SUP_ATY_RPT_LN3 $3. ;
FORMAT WF_SUP_ATY_RPT_LN4 $3. ;
FORMAT WF_SUP_ATY_RPT_LN5 $3. ;
FORMAT WF_SUP_ATY_RPT_LN6 $3. ;
FORMAT WF_SUP_ATY_RPT_LN7 $3. ;
FORMAT WF_SUP_ATY_RPT_LN8 $3. ;
FORMAT WF_SUP_ATY_RPT_LN9 $3. ;
FORMAT WF_SAR_LN10 $3. ;
FORMAT LC_SCY_PGA_PGM_YR $1. ;
FORMAT LC_CU_LIA $1. ;
FORMAT WA_PRI_CU_BEG 10.2 ;
FORMAT WA_BRI_ACR_CU_BEG 9.2 ;
FORMAT WA_CLM_PRI_BKR 10.2 ;
FORMAT WA_CLM_INT_BKR 9.2 ;
FORMAT WA_CLM_PRI_DTH 10.2 ;
FORMAT WA_CLM_INT_DTH 9.2 ;
FORMAT WA_CLM_PRI_DSA 10.2 ;
FORMAT WA_CLM_INT_DSA 9.2 ;
FORMAT WA_CLM_PRI_ILG 10.2 ;
FORMAT WA_CLM_INT_ILG 9.2 ;
FORMAT WA_CLM_PRI_ISL_DLQ 10.2 ;
FORMAT WA_CLM_INT_ISL_DLQ 9.2 ;
FORMAT WA_CLM_PRI_INT_DLQ 10.2 ;
FORMAT WA_CLM_INT_INT_DLQ 9.2 ;
FORMAT WA_CLM_PRI_CLS 10.2 ;
FORMAT WA_CLM_INT_CLS 9.2 ;
FORMAT WA_CLM_PRI_CU 10.2 ;
FORMAT WA_CLM_INT_CU 9.2 ;
FORMAT WA_CLM_PRI_SUP 10.2 ;
FORMAT WA_CLM_INT_SUP 9.2 ;
FORMAT WA_CLM_PRI_SKP 10.2 ;
FORMAT WA_CLM_INT_SKP 9.2 ;
FORMAT WA_CLM_PRI_OTH 10.2 ;
FORMAT WA_CLM_INT_OTH 9.2 ;
FORMAT WA_ORG_CHK 10.2 ;
FORMAT WA_ORG_EFT 10.2 ;
FORMAT WN_DSB_CHK_SQ 4. ;
FORMAT WA_DSB_CHK_SQ 10.2 ;
FORMAT WA_DSB_CAN_EFT_1 10.2 ;
FORMAT WA_DSB_CAN_CHK_1 10.2 ;
FORMAT WN_DSB_CAN_EFT_SQ 4. ;
FORMAT WA_DSB_CAN_EFT_SQ 10.2 ;
FORMAT WN_DSB_CAN_CHK_SQ 4. ;
FORMAT WA_DSB_CAN_CHK_SQ 10.2 ;
FORMAT WA_FAT_CUR_PRI_DCV 10.2 ;
FORMAT WA_FAT_NSI_DCV 9.2 ;
FORMAT WA_FAT_CUR_PRI_CVN 10.2 ;
FORMAT WA_FAT_NSI_CVN 9.2 ;
FORMAT WA_FAT_CUR_PRI_TRF 10.2 ;
FORMAT WA_FAT_NSI_TRF 9.2 ;
FORMAT WA_FAT_CUR_PRI_RPR 10.2 ;
FORMAT WA_FAT_NSI_RPR 9.2 ;
FORMAT WA_FAT_CUR_PRI_EXT 10.2 ;
FORMAT WA_FAT_NSI_EXT 9.2 ;
FORMAT WA_FAT_CUR_PRI_NEW 10.2 ;
FORMAT WA_FAT_NSI_NEW 9.2 ;
FORMAT WA_DSB_EFT_1 10.2 ;
FORMAT WA_DSB_CHK_1 10.2 ;
FORMAT WN_DSB_EFT_SQ 4. ;
FORMAT WA_DSB_EFT_SQ 10.2 ;
FORMAT LF_DOE_SCL_ORG $8. ;
FORMAT WF_TIR_PCE_LN35 $3. ;
FORMAT LD_CU_ENT MMDDYY10. ;
FORMAT WD_CLM_BKR_SBM MMDDYY10. ;
FORMAT WD_CLM_DTH_SBM MMDDYY10. ;
FORMAT WD_CLM_DSA_SBM MMDDYY10. ;
FORMAT WD_CLM_ILG_SBM MMDDYY10. ;
FORMAT WD_CLM_ISL_DLQ_SBM MMDDYY10. ;
FORMAT WD_CLM_INT_DLQ_SBM MMDDYY10. ;
FORMAT WD_CLM_CLS_SBM MMDDYY10. ;
FORMAT WD_CLM_SKP_SBM MMDDYY10. ;
FORMAT WD_CLM_CU_SBM MMDDYY10. ;
FORMAT WD_CLM_SUP_SBM MMDDYY10. ;
FORMAT WD_CLM_OTH_SBM MMDDYY10. ;
FORMAT LD_FOR_BEG MMDDYY10. ;
FORMAT LD_END_GRC_PRD MMDDYY10. ;
FORMAT WD_DCV_EFF MMDDYY10. ;
FORMAT WD_ORG_EFT_EFF MMDDYY10. ;
FORMAT WD_ORG_CHK_EFF MMDDYY10. ;
FORMAT WD_TRF_EFF MMDDYY10. ;
FORMAT WD_CVN_EFF MMDDYY10. ;
FORMAT WD_RPR_EFF MMDDYY10. ;
FORMAT WD_EXT_ORG_EFF MMDDYY10. ;
FORMAT WD_NEW_ORG_EFF MMDDYY10. ;
FORMAT WD_DSB_EFT_1 MMDDYY10. ;
FORMAT WD_DSB_CHK_1 MMDDYY10. ;
FORMAT WD_DSB_EFT_SQ MMDDYY10. ;
FORMAT WD_DSB_CHK_SQ MMDDYY10. ;
FORMAT WD_DSB_CAN_EFT_1 MMDDYY10. ;
FORMAT WD_DSB_CAN_CHK_1 MMDDYY10. ;
FORMAT WD_DSB_CAN_EFT_SQ MMDDYY10. ;
FORMAT WD_DSB_CAN_CHK_SQ MMDDYY10. ;
IF _N_ = 1 THEN        /* WRITE COLUMN NAMES */
DO;
PUT
'IF_OWN_PRN'
','
'BF_SSN'
','
'LN_SEQ'
','
'IF_OWN'
','
'IF_BND_ISS'
','
'IC_LON_PGM'
','
'IF_GTR'
','
'LF_CUR_POR'
','
'WC_TYP_SCL_ORG'
','
'WR_ITR_1'
','
'WC_ITR_TYP_1'
','
'LD_LON_1_DSB'
','
'WC_ELG_SIN_1'
','
'WA_CUR_PRI'
','
'WA_CUR_BR_INT'
','
'WA_CUR_GOV_INT'
','
'WA_CUR_OTH_CHR'
','
'WD_SAR_ATY_EFF'
','
'WA_AVG_DAY_BAL'
','
'WN_SQ_FOR_APL'
','
'WX_TYP_REC_CLP_LON'
','
'WF_SUP_ATY_RPT_LN1'
','
'WF_SUP_ATY_RPT_LN2'
','
'WF_SUP_ATY_RPT_LN3'
','
'WF_SUP_ATY_RPT_LN4'
','
'WF_SUP_ATY_RPT_LN5'
','
'WF_SUP_ATY_RPT_LN6'
','
'WF_SUP_ATY_RPT_LN7'
','
'WF_SUP_ATY_RPT_LN8'
','
'WF_SUP_ATY_RPT_LN9'
','
'WF_SAR_LN10'
','
'LC_SCY_PGA_PGM_YR'
','
'LC_CU_LIA'
','
'WA_PRI_CU_BEG'
','
'WA_BRI_ACR_CU_BEG'
','
'WA_CLM_PRI_BKR'
','
'WA_CLM_INT_BKR'
','
'WA_CLM_PRI_DTH'
','
'WA_CLM_INT_DTH'
','
'WA_CLM_PRI_DSA'
','
'WA_CLM_INT_DSA'
','
'WA_CLM_PRI_ILG'
','
'WA_CLM_INT_ILG'
','
'WA_CLM_PRI_ISL_DLQ'
','
'WA_CLM_INT_ISL_DLQ'
','
'WA_CLM_PRI_INT_DLQ'
','
'WA_CLM_INT_INT_DLQ'
','
'WA_CLM_PRI_CLS'
','
'WA_CLM_INT_CLS'
','
'WA_CLM_PRI_CU'
','
'WA_CLM_INT_CU'
','
'WA_CLM_PRI_SUP'
','
'WA_CLM_INT_SUP'
','
'WA_CLM_PRI_SKP'
','
'WA_CLM_INT_SKP'
','
'WA_CLM_PRI_OTH'
','
'WA_CLM_INT_OTH'
','
'WA_ORG_CHK'
','
'WA_ORG_EFT'
','
'WN_DSB_CHK_SQ'
','
'WA_DSB_CHK_SQ'
','
'WA_DSB_CAN_EFT_1'
','
'WA_DSB_CAN_CHK_1'
','
'WN_DSB_CAN_EFT_SQ'
','
'WA_DSB_CAN_EFT_SQ'
','
'WN_DSB_CAN_CHK_SQ'
','
'WA_DSB_CAN_CHK_SQ'
','
'WA_FAT_CUR_PRI_DCV'
','
'WA_FAT_NSI_DCV'
','
'WA_FAT_CUR_PRI_CVN'
','
'WA_FAT_NSI_CVN'
','
'WA_FAT_CUR_PRI_TRF'
','
'WA_FAT_NSI_TRF'
','
'WA_FAT_CUR_PRI_RPR'
','
'WA_FAT_NSI_RPR'
','
'WA_FAT_CUR_PRI_EXT'
','
'WA_FAT_NSI_EXT'
','
'WA_FAT_CUR_PRI_NEW'
','
'WA_FAT_NSI_NEW'
','
'WA_DSB_EFT_1'
','
'WA_DSB_CHK_1'
','
'WN_DSB_EFT_SQ'
','
'WA_DSB_EFT_SQ'
','
'LF_DOE_SCL_ORG'
','
'WF_TIR_PCE_LN35'
','
'LD_CU_ENT'
','
'WD_CLM_BKR_SBM'
','
'WD_CLM_DTH_SBM'
','
'WD_CLM_DSA_SBM'
','
'WD_CLM_ILG_SBM'
','
'WD_CLM_ISL_DLQ_SBM'
','
'WD_CLM_INT_DLQ_SBM'
','
'WD_CLM_CLS_SBM'
','
'WD_CLM_SKP_SBM'
','
'WD_CLM_CU_SBM'
','
'WD_CLM_SUP_SBM'
','
'WD_CLM_OTH_SBM'
','
'LD_FOR_BEG'
','
'LD_END_GRC_PRD'
','
'WD_DCV_EFF'
','
'WD_ORG_EFT_EFF'
','
'WD_ORG_CHK_EFF'
','
'WD_TRF_EFF'
','
'WD_CVN_EFF'
','
'WD_RPR_EFF'
','
'WD_EXT_ORG_EFF'
','
'WD_NEW_ORG_EFF'
','
'WD_DSB_EFT_1'
','
'WD_DSB_CHK_1'
','
'WD_DSB_EFT_SQ'
','
'WD_DSB_CHK_SQ'
','
'WD_DSB_CAN_EFT_1'
','
'WD_DSB_CAN_CHK_1'
','
'WD_DSB_CAN_EFT_SQ'
','
'WD_DSB_CAN_CHK_SQ'
;
END;
DO;
PUT IF_OWN_PRN $ @;
PUT BF_SSN $ @;
PUT LN_SEQ @;
PUT IF_OWN $ @;
PUT IF_BND_ISS $ @;
PUT IC_LON_PGM $ @;
PUT IF_GTR $ @;
PUT LF_CUR_POR $ @;
PUT WC_TYP_SCL_ORG $ @;
PUT WR_ITR_1 @;
PUT WC_ITR_TYP_1 $ @;
PUT LD_LON_1_DSB @;
PUT WC_ELG_SIN_1 $ @;
PUT WA_CUR_PRI @;
PUT WA_CUR_BR_INT @;
PUT WA_CUR_GOV_INT @;
PUT WA_CUR_OTH_CHR @;
PUT WD_SAR_ATY_EFF @;
PUT WA_AVG_DAY_BAL @;
PUT WN_SQ_FOR_APL @;
PUT WX_TYP_REC_CLP_LON $ @;
PUT WF_SUP_ATY_RPT_LN1 $ @;
PUT WF_SUP_ATY_RPT_LN2 $ @;
PUT WF_SUP_ATY_RPT_LN3 $ @;
PUT WF_SUP_ATY_RPT_LN4 $ @;
PUT WF_SUP_ATY_RPT_LN5 $ @;
PUT WF_SUP_ATY_RPT_LN6 $ @;
PUT WF_SUP_ATY_RPT_LN7 $ @;
PUT WF_SUP_ATY_RPT_LN8 $ @;
PUT WF_SUP_ATY_RPT_LN9 $ @;
PUT WF_SAR_LN10 $ @;
PUT LC_SCY_PGA_PGM_YR $ @;
PUT LC_CU_LIA $ @;
PUT WA_PRI_CU_BEG @;
PUT WA_BRI_ACR_CU_BEG @;
PUT WA_CLM_PRI_BKR @;
PUT WA_CLM_INT_BKR @;
PUT WA_CLM_PRI_DTH @;
PUT WA_CLM_INT_DTH @;
PUT WA_CLM_PRI_DSA @;
PUT WA_CLM_INT_DSA @;
PUT WA_CLM_PRI_ILG @;
PUT WA_CLM_INT_ILG @;
PUT WA_CLM_PRI_ISL_DLQ @;
PUT WA_CLM_INT_ISL_DLQ @;
PUT WA_CLM_PRI_INT_DLQ @;
PUT WA_CLM_INT_INT_DLQ @;
PUT WA_CLM_PRI_CLS @;
PUT WA_CLM_INT_CLS @;
PUT WA_CLM_PRI_CU @;
PUT WA_CLM_INT_CU @;
PUT WA_CLM_PRI_SUP @;
PUT WA_CLM_INT_SUP @;
PUT WA_CLM_PRI_SKP @;
PUT WA_CLM_INT_SKP @;
PUT WA_CLM_PRI_OTH @;
PUT WA_CLM_INT_OTH @;
PUT WA_ORG_CHK @;
PUT WA_ORG_EFT @;
PUT WN_DSB_CHK_SQ @;
PUT WA_DSB_CHK_SQ @;
PUT WA_DSB_CAN_EFT_1 @;
PUT WA_DSB_CAN_CHK_1 @;
PUT WN_DSB_CAN_EFT_SQ @;
PUT WA_DSB_CAN_EFT_SQ @;
PUT WN_DSB_CAN_CHK_SQ @;
PUT WA_DSB_CAN_CHK_SQ @;
PUT WA_FAT_CUR_PRI_DCV @;
PUT WA_FAT_NSI_DCV @;
PUT WA_FAT_CUR_PRI_CVN @;
PUT WA_FAT_NSI_CVN @;
PUT WA_FAT_CUR_PRI_TRF @;
PUT WA_FAT_NSI_TRF @;
PUT WA_FAT_CUR_PRI_RPR @;
PUT WA_FAT_NSI_RPR @;
PUT WA_FAT_CUR_PRI_EXT @;
PUT WA_FAT_NSI_EXT @;
PUT WA_FAT_CUR_PRI_NEW @;
PUT WA_FAT_NSI_NEW @;
PUT WA_DSB_EFT_1 @;
PUT WA_DSB_CHK_1 @;
PUT WN_DSB_EFT_SQ @;
PUT WA_DSB_EFT_SQ @;
PUT LF_DOE_SCL_ORG $ @;
PUT WF_TIR_PCE_LN35 $ @;
PUT LD_CU_ENT @;
PUT WD_CLM_BKR_SBM @;
PUT WD_CLM_DTH_SBM @;
PUT WD_CLM_DSA_SBM @;
PUT WD_CLM_ILG_SBM @;
PUT WD_CLM_ISL_DLQ_SBM @;
PUT WD_CLM_INT_DLQ_SBM @;
PUT WD_CLM_CLS_SBM @;
PUT WD_CLM_SKP_SBM @;
PUT WD_CLM_CU_SBM @;
PUT WD_CLM_SUP_SBM @;
PUT WD_CLM_OTH_SBM @;
PUT LD_FOR_BEG @;
PUT LD_END_GRC_PRD @;
PUT WD_DCV_EFF @;
PUT WD_ORG_EFT_EFF @;
PUT WD_ORG_CHK_EFF @;
PUT WD_TRF_EFF @;
PUT WD_CVN_EFF @;
PUT WD_RPR_EFF @;
PUT WD_EXT_ORG_EFF @;
PUT WD_NEW_ORG_EFF @;
PUT WD_DSB_EFT_1 @;
PUT WD_DSB_CHK_1 @;
PUT WD_DSB_EFT_SQ @;
PUT WD_DSB_CHK_SQ @;
PUT WD_DSB_CAN_EFT_1 @;
PUT WD_DSB_CAN_CHK_1 @;
PUT WD_DSB_CAN_EFT_SQ @;
PUT WD_DSB_CAN_CHK_SQ ;
;
END;
RUN;


