CREATE PROCEDURE [dbo].[LT_TS06BSCRAE_ExpirationDate]
	@AccountNumber CHAR(10)
AS
BEGIN
	SELECT
		CONVERT(VARCHAR(10), L.LD_ITR_EFF_END, 101) [SCRA_RATE_EXPIRATION_DATE]
	FROM
		OPENQUERY
		(
			LEGEND,
			'
				SELECT DISTINCT
					--PD10.DF_PRS_ID,
					--LN10.LN_SEQ,
					--LN72.LR_ITR,
					LN72.LD_ITR_EFF_END
				FROM
					PKUB.PD10_PRS_NME PD10
					INNER JOIN PKUB.LN10_LON LN10 ON LN10.BF_SSN = PD10.DF_PRS_ID
					INNER JOIN PKUB.LN72_INT_RTE_HST LN72 ON LN72.BF_SSN = PD10.DF_PRS_ID AND LN72.LN_SEQ = LN10.LN_SEQ
				WHERE
					LN10.LA_CUR_PRI > 0
					AND 
					LN72.LD_ITR_EFF_END != ''01/01/9999''
					AND 
					PD10.DF_SPE_ACC_ID = ''5034597664''
					AND
					LN72.LC_STA_LON72 = ''A''
					AND
					LN72.LC_INT_RDC_PGM IN (''M'', ''P'')
					AND
					CURRENT DATE BETWEEN LN72.LD_ITR_EFF_BEG AND LN72.LD_ITR_EFF_END
			'
		) L 
	END

	IF @@ROWCOUNT = 0 
		BEGIN
			RAISERROR('No data returned for account %s. ([dbo].[LT_TS06BSCRAE_ExpirationDate])',11,2, @AccountNumber)
		END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[LT_TS06BSCRAE_ExpirationDate] TO [db_executor]
    AS [dbo];
