CREATE TABLE [dbo].[PD32_PRS_ADR_EML] (
    [DF_PRS_ID]          CHAR (9)      NOT NULL,
    [DC_ADR_EML]         CHAR (1)      NOT NULL,
    [DF_CRT_DTS_PD32]    DATETIME2 (7) NOT NULL,
    [DC_STA_PD32]        CHAR (1)      NOT NULL,
    [DD_STA_PD32]        DATE          NULL,
    [DD_VER_ADR_EML]     DATE          NULL,
    [DD_CRT_PD32]        DATE          NULL,
    [DC_SRC_ADR]         VARCHAR (2)   NOT NULL,
    [DI_VLD_ADR_EML]     CHAR (1)      NOT NULL,
    [DF_LST_USR_PD32]    CHAR (8)      NOT NULL,
    [DF_LST_DTS_PD32]    DATETIME2 (7) NOT NULL,
    [DX_ADR_EML]         VARCHAR (254) NOT NULL,
    [DI_SND_LTR_EML]     CHAR (1)      NOT NULL,
    [DC_REA_EML_NOT_SND] CHAR (1)      NOT NULL,
    [DC_DL_COR_TYP]      CHAR (1)      NOT NULL,
    CONSTRAINT [PK_PD32_PRS_ADR_EML] PRIMARY KEY CLUSTERED ([DF_PRS_ID] ASC, [DC_ADR_EML] ASC, [DF_CRT_DTS_PD32] ASC) WITH (FILLFACTOR = 95)
);


GO
CREATE NONCLUSTERED INDEX [IX_DFPRSID_DCSTAPD32]
    ON [dbo].[PD32_PRS_ADR_EML]([DF_PRS_ID] ASC, [DC_STA_PD32] ASC)
    INCLUDE([DC_ADR_EML], [DD_VER_ADR_EML], [DI_VLD_ADR_EML], [DX_ADR_EML]) WITH (FILLFACTOR = 95);


GO
CREATE NONCLUSTERED INDEX [IX_DCSTAPD32]
    ON [dbo].[PD32_PRS_ADR_EML]([DC_STA_PD32] ASC)
    INCLUDE([DF_PRS_ID], [DC_ADR_EML], [DD_VER_ADR_EML], [DI_VLD_ADR_EML], [DX_ADR_EML]) WITH (FILLFACTOR = 95);


GO
CREATE NONCLUSTERED INDEX [IX_DCSTAPD32_DIVLDADREML]
    ON [dbo].[PD32_PRS_ADR_EML]([DC_STA_PD32] ASC, [DI_VLD_ADR_EML] ASC)
    INCLUDE([DF_PRS_ID], [DC_ADR_EML], [DX_ADR_EML]) WITH (FILLFACTOR = 95);

