CREATE PROCEDURE [verforbfed].[GetTotalForbDaysUsed]
	@Ssn CHAR(9)
AS

	SELECT
		ISNULL(
			SUM(DATEDIFF(DAY, LD_FOR_BEG, LD_FOR_END) + 1) / COUNT(DISTINCT ln60.ln_seq)
		, 0) 
	FROM
		FB10_BR_FOR_REQ FB10
		INNER JOIN LN60_BR_FOR_APV LN60 on LN60.BF_SSN = FB10.BF_SSN AND FB10.LF_FOR_CTL_NUM = LN60.LF_FOR_CTL_NUM
	WHERE
		FB10.LC_FOR_TYP = '05'
		AND
		FB10.LC_FOR_STA = 'A'
		AND
		FB10.LC_STA_FOR10 = 'A'
		AND
		LN60.LC_STA_LON60 = 'A' 
		AND
		FB10.BF_SSN = @Ssn

RETURN 0