CREATE TABLE [dbo].[LN85_LON_ATY] (
    [BF_SSN]          CHAR (9)      NOT NULL,
    [LN_SEQ]          SMALLINT      NOT NULL,
    [LN_ATY_SEQ]      INT           NOT NULL,
    [LF_LST_DTS_LN85] DATETIME2 (7) NOT NULL
);




GO
CREATE NONCLUSTERED INDEX [CIX_BF_SSN_LN_SEQ]
    ON [dbo].[LN85_LON_ATY]([BF_SSN] ASC, [LN_SEQ] ASC)
    INCLUDE([LN_ATY_SEQ]) WITH (FILLFACTOR = 95);


GO
CREATE NONCLUSTERED INDEX [CIX_BF_SSN_LN_ATY_SEQ]
    ON [dbo].[LN85_LON_ATY]([BF_SSN] ASC, [LN_ATY_SEQ] ASC)
    INCLUDE([LN_SEQ]) WITH (FILLFACTOR = 95);


GO
CREATE NONCLUSTERED INDEX [CIX_BF_SSN]
    ON [dbo].[LN85_LON_ATY]([BF_SSN] ASC)
    INCLUDE([LN_SEQ], [LN_ATY_SEQ]) WITH (FILLFACTOR = 95);

