/*UTLWQ09 INHOUSE BORROWERS WITH PIF STATUS*/
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
%LET RPTLIB = %SYSGET(reportdir);
FILENAME REPORT2 "&RPTLIB/ULWQ09.LWQ09R2";*/

/*MONTHLY CODE*/
/*DATA _NULL_;*/
/*     CALL SYMPUT('BEGIN',"'"||PUT(INTNX('MONTH',TODAY()+3,-1,'beginning'), MMDDYYD10.)||"'");*/
/*     CALL SYMPUT('END',"'"||PUT(INTNX('MONTH',TODAY()+3,-1,'end'), MMDDYYD10.)||"'");*/
/*     CALL SYMPUT('EFFDATE',TRIM(LEFT(UPCASE(*/
/*		PUT(INTNX('MONTH',TODAY()+3,-1), MONNAME9.)||' '||*/
/*		PUT(INTNX('MONTH',TODAY()+3,-1), YEAR4.)))));*/
/*RUN;*/
/*%SYSLPUT BEGIN = &BEGIN;*/
/*%SYSLPUT END = &END;*/

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE IBPIFS AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT   DISTINCT A.BF_SSN AS SSN
		,RTRIM(C.DM_PRS_LST)||' '||RTRIM(C.DM_PRS_1)||' '||RTRIM(C.DM_PRS_MID) AS NAME
		,A.LN_SEQ
		,A.IC_LON_PGM
		,RTRIM(A.LF_LON_ALT)||''||(CHAR(A.LN_LON_ALT_SEQ)) AS UID
		,B.PC_FAT_TYP||' '||B.PC_FAT_SUB_TYP AS TRNS_TYP
		,F.LA_DSB_CAN
		,F.LA_DSB
		,A.LD_PIF_RPT

FROM	 OLWHRM1.LN10_LON A 
		INNER JOIN OLWHRM1.LN90_FIN_ATY B
		 ON A.BF_SSN = B.BF_SSN
		 AND A.LN_SEQ = B.LN_SEQ
		INNER JOIN OLWHRM1.LN15_DSB F
		 ON A.BF_SSN = F.BF_SSN
		 AND A.LN_SEQ = F.LN_SEQ
		INNER JOIN OLWHRM1.DW01_DW_CLC_CLU D
		 ON A.BF_SSN = D.BF_SSN
		 AND A.LN_SEQ = D.LN_SEQ
		INNER JOIN OLWHRM1.PD10_PRS_NME C
		 ON A.BF_SSN = C.DF_PRS_ID 
		
WHERE	A.LF_LON_CUR_OWN = '828476'
/* THE UNDERLYING CODE WAS USED IN TESTING 
WHERE A.LF_LON_CUR_OWN IN ('811698', '813760UT', '813894', '817455', '817545',
 						   '817546', '819628', '820200', '822373', '829123',
 						   '829158', '829505', '830132', '830146', '830791',
                           '832241', '833828','828476')*/
AND 	A.IC_LON_PGM = 'PLUS'
AND 	A.LC_STA_LON10 = 'R'
AND 	D.WC_DW_LON_STA = '22'
AND 	F.LC_STA_LON15 IN ('1', '3')
AND 	F.LD_DSB BETWEEN '07/01/1999' AND '06/30/2004'
AND     (F.LA_DSB_CAN IS NULL 
		 OR	
		(F.LA_DSB_CAN = F.LA_DSB
		 AND EXISTS	   (SELECT *
						FROM OLWHRM1.LN90_FIN_ATY X 
						WHERE X.LN_SEQ = A.LN_SEQ 
						AND   X.BF_SSN = A.BF_SSN
						AND   (X.PC_FAT_TYP = '10'
				  			   AND X.PC_FAT_SUB_TYP = '41')
		 				AND	  X.LC_FAT_REV_REA = ' ')))
/*AND		A.LD_PIF_RPT BETWEEN &BEGIN AND &END monthly code*/
AND		DAYS(A.LD_PIF_RPT) = DAYS(CURRENT DATE) - 7
/*THIS CODE WAS ALSO USED IN TESTING
AND 	YEAR(A.LD_PIF_RPT) = YEAR(CURRENT DATE) 
AND 	MONTH(A.LD_PIF_RPT) = MONTH(CURRENT DATE)*/
);
DISCONNECT FROM DB2;
ENDRSUBMIT;

DATA IBPIFS;
SET WORKLOCL.IBPIFS;
RUN;
PROC SORT DATA=IBPIFS OUT=IBPIFS_U NODUPKEY;
BY SSN LN_SEQ;
RUN;

data _null_;                                      
current=today();                                  
call symput('curdate',put(current,MMDDYY10.));       
run;  

/*PROC PRINTTO PRINT=REPORT2;
RUN;*/
OPTIONS PAGENO=1 ORIENTATION=LANDSCAPE NODATE CENTER;
OPTIONS PS=39 LS=128;

PROC PRINT NOOBS SPLIT='/' DATA=IBPIFS_U WIDTH=MIN;
VAR SSN
	NAME
	LN_SEQ
	IC_LON_PGM
	UID;
LABEL	SSN = 'SSN'
		NAME = 'BORROWER NAME'
		LN_SEQ = 'LOAN SEQ'
		IC_LON_PGM = 'LOAN TYPE'
		UID = 'UNIQUE ID';
TITLE	"INHOUSE BORROWERS WITH PIF STATUS &curdate";
FOOTNOTE ' JOB=UTLWQ09     REPORT=ULWQ09.LWQ09R2';
RUN;
