%LET RPTLIB = T:\SAS;
LIBNAME  DUSTER  REMOTE  SERVER=DUSTER  SLIBREF=WORK;
RSUBMIT;
/*LIBNAME OLWHRM1 DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
PROC SQL;
	CONNECT TO DB2 (DATABASE=DLGSUTWH);
	CREATE TABLE _PD01_PDM_INF AS
	SELECT 
		*
	FROM 
		CONNECTION TO DB2 
		(
			SELECT DISTINCT
				DF_PRS_ID
			FROM	
				OLWHRM1.PD01_PDM_INF
				
			FOR READ ONLY WITH UR
		)
	;
	DISCONNECT FROM DB2;
QUIT;
ENDRSUBMIT;
DATA _PD01_PDM_INF;
	SET DUSTER._PD01_PDM_INF;
RUN;

/*send data to OPSDEV SQL Server*/
LIBNAME SQL_OPS ODBC REQUIRED="FILEDSN=X:\PADR\ODBC\CSYSTEST.dsn; bl_keepnulls=no; READ_ISOLATION_LEVEL=RU" SCHEMA= DBO;
DATA SQL_OPS._PD01_PDM_INF;
	SET _PD01_PDM_INF;
RUN;
