/*
RELEASE JUDICIAL GARNISHMENT

This report lists legal borrowers with a current garnishment where the account
balance is zero meaning the garnishment needs to be released.
Collections uses this report to release judicial garnishments so extra payments
are not remitted.

*/

/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
%LET RPTLIB = %SYSGET(reportdir);
FILENAME REPORT2 "&RPTLIB/ULWJD4.LWJD4R2";*/

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE RELGARN AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT
	A.DF_PRS_ID			AS SSN,
	A.DM_PRS_1,
	A.DM_PRS_LST,
	A.DX_STR_ADR_1,
	A.DX_STR_ADR_2,
	A.DM_CT,
	A.DC_DOM_ST,
	A.DF_ZIP,
	A.BF_EMP_ID_1,
	B.IM_IST_FUL,
	B.IX_GEN_STR_ADR_1,
	B.IX_GEN_STR_ADR_2,
	B.IX_GEN_STR_ADR_3,
	B.IM_GEN_CT,
	B.IC_GEN_ST,
	B.IF_GEN_ZIP,
	C.BF_LEG_ACT_DKT,
	F.BF_LEG_ACT_ATY_DKT,
	F.BD_LEG_ACT_ATY_FIL/*,
	G.BX_CMT*/
FROM 	OLWHRM1.PD01_PDM_INF A INNER JOIN
		OLWHRM1.IN01_LGS_IDM_MST B ON
			A.BF_EMP_ID_1 = B.IF_IST INNER JOIN
		OLWHRM1.LA10_LEG_ACT C ON
			A.DF_PRS_ID = C.DF_PRS_ID_BR INNER JOIN
		OLWHRM1.DC01_LON_CLM_INF D ON
			A.DF_PRS_ID = D.BF_SSN INNER JOIN
		OLWHRM1.DC02_BAL_INT E ON
			D.AF_APL_ID = E.AF_APL_ID AND
			D.AF_APL_ID_SFX = E.AF_APL_ID_SFX INNER JOIN
		OLWHRM1.LA11_LEG_ACT_ATY F ON
			A.DF_PRS_ID = F.DF_PRS_ID_BR AND
			C.BF_CRT_DTS_LA10 = F.BF_CRT_DTS_LA10 AND
			F.BC_EXE_TYP = '04' /*INNER JOIN
		OLWHRM1.AY01_BR_ATY G ON
			A.DF_PRS_ID = G.DF_PRS_ID AND
			G.PF_ACT = 'DJGNM'*/
WHERE	C.BC_WDR_REA = '' AND
		C.BC_INA_REA = '' AND
		C.BC_LEG_ACT_REC_TYP = '2'AND
		D.LC_GRN = '07' AND
		E.LA_CLM_BAL = 0 AND
		C.BF_CRT_DTS_LA10 = (SELECT MIN(X.BF_CRT_DTS_LA10)
									FROM OLWHRM1.LA10_LEG_ACT X
									WHERE	A.DF_PRS_ID = X.DF_PRS_ID_BR AND
											X.BC_WDR_REA = '' AND
											X.BC_INA_REA = '' AND
											X.BC_LEG_ACT_REC_TYP = '2'
									GROUP BY X.DF_PRS_ID_BR)
);

DISCONNECT FROM DB2;
ENDRSUBMIT;
DATA WORKLOCL.RELGARN (KEEP = SSN GARN_INFO FILED FIRST LAST ADDRESS CITY ST ZIP EMP_NO EMP_NAME EMP_ADD EMP_CITY EMP_ST EMP_ZIP DOCKNO /*JUDG*/);
	SET WORKLOCL.RELGARN;
		GARN_INFO = BF_LEG_ACT_ATY_DKT;
		FILED = BD_LEG_ACT_ATY_FIL;
		FIRST = TRIM(DM_PRS_1);
		LAST = TRIM(DM_PRS_LST);
		ADDRESS = TRIM(DX_STR_ADR_1)||TRIM(DX_STR_ADR_2);
		CITY = TRIM(DM_CT);
		ST = DC_DOM_ST;
		ZIP = TRIM(DF_ZIP);
		EMP_NO = BF_EMP_ID_1;
		EMP_NAME = TRIM(IM_IST_FUL);
		EMP_ADD = TRIM(IX_GEN_STR_ADR_1)||TRIM(IX_GEN_STR_ADR_2)||TRIM(IX_GEN_STR_ADR_3);
		EMP_CITY = TRIM(IM_GEN_CT);
		EMP_ST = TRIM(IC_GEN_ST);
		EMP_ZIP = TRIM(IF_GEN_ZIP);
		DOCKNO = BF_LEG_ACT_DKT;
	/*		JUDG = TRIM(BX_CMT);
			RX = RXPARSE("' '");
			UIBP = RXMATCH(RX,JUDG);
   			JUDG = SUBSTR(JUDG,1,UIBP-1);*/
RUN;
PROC SORT DATA = WORKLOCL.RELGARN;
	BY SSN;
RUN;
/*PROC PRINTTO PRINT=REPORT2;
RUN;*/
OPTIONS NOCENTER PAGENO=1 LS=132;
PROC PRINT SPLIT='/' DATA=WORKLOCL.RELGARN;
VAR GARN_INFO
	FILED
	SSN
	FIRST
	LAST
	ADDRESS
	CITY
	ST
	ZIP
	EMP_NO
	EMP_NAME
	EMP_ADD
	EMP_CITY
	EMP_ST
	EMP_ZIP
	DOCKNO;
	*JUDG;
FORMAT FILED MMDDYY10.;
TITLE1 'JUDICIAL GARNISHMENT';
TITLE2 'ACCOUNT PAID';
FOOTNOTE 'JOB = UTLWJD4     REPORT = ULWJD4.LWJD4R2';
RUN;
