*-----------------------------------------------------*
|   UTLWU02 - DOB DISCREPANCIES FOR ONELINK-COMPASS   |
*-----------------------------------------------------*;
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/ULWU02.LWU02R2";
FILENAME REPORTZ "&RPTLIB/ULWU02.LWU02RZ";
DATA _NULL_;
	CALL SYMPUT('RUNDATE',PUT(INTNX('DAY',TODAY(),0,'beginning'), MMDDYY10.));
	CALL SYMPUT('RUNTIME',PUT(TIME(), TIME.));
RUN;
LIBNAME  WORKLOCL  REMOTE  SERVER=DUSTER  SLIBREF=WORK;
RSUBMIT;
%MACRO SQLCHECK (SQLRPT= );
%IF &SQLXRC NE 0 %THEN %DO;
	DATA _NULL_;
    FILE REPORTZ NOTITLES;
    PUT @01 " ********************************************************************* "
      / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
      / @01 " ****  THE SAS LOG IN &SQLRPT SHOULD BE REVIEWED.          **** "       
      / @01 " ********************************************************************* "
      / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
      / @01 " ****  &SQLXMSG   **** "
      / @01 " ********************************************************************* ";
	RUN;
%END;
%MEND;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE BDESC AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT ONELINK.DF_SPE_ACC_ID
	,ONELINK.DD_BRT AS OL_DD_BRT
	,COMPASS.DD_BRT AS CO_DD_BRT
	,DATE(ONELINK.DF_LST_DTS_PD01) AS ONEDATE
	,DATE(COMPASS.DF_LST_DTS_PD10) AS COMDATE
FROM OLWHRM1.PD01_PDM_INF ONELINK
INNER JOIN OLWHRM1.PD10_PRS_NME COMPASS
	ON ONELINK.DF_PRS_ID = COMPASS.DF_PRS_ID
INNER JOIN OLWHRM1.LN10_LON LN10	
	ON COMPASS.DF_PRS_ID = LN10.BF_SSN
	AND LN10.LA_CUR_PRI <> 0
INNER JOIN OLWHRM1.GA01_APP GA01
	ON GA01.DF_PRS_ID_BR = ONELINK.DF_PRS_ID
INNER JOIN OLWHRM1.GA14_LON_STA GA14
	ON GA01.AF_APL_ID = GA14.AF_APL_ID
	AND GA14.AC_LON_STA_TYP IN ('UA', 'UB', 'RP', 'IM', 'IG', 'ID', 'IA', 'CP', 'DA', 'FB', 'CR')

WHERE ONELINK.DD_BRT <> COMPASS.DD_BRT
AND LN10.IF_GTR = '000749'
AND LN10.LC_STA_LON10 = 'R'
ORDER BY ONELINK.DF_SPE_ACC_ID
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>>  ;  * INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK (SQLRPT=ULWU02.LWU02RZ);*/
/*QUIT;*/
ENDRSUBMIT;
DATA BDESC;
SET WORKLOCL.BDESC;
RUN;
DATA BDESC(DROP=ONEDATE COMDATE);
SET BDESC;
	IF ONEDATE >= COMDATE THEN ACT_DATE = ONEDATE;
	IF ONEDATE < COMDATE THEN ACT_DATE = COMDATE;
RUN;

DATA _NULL_;
SET BDESC ;
LENGTH DESCRIPTION $600.;
USER = ' ';
ACT_DT = ACT_DATE;
DESCRIPTION = CATX(',',
		DF_SPE_ACC_ID
		,PUT(OL_DD_BRT,MMDDYY10.)
		,PUT(CO_DD_BRT,MMDDYY10.)
);
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
FORMAT USER $10. ;
FORMAT ACT_DT MMDDYY10. ;
FORMAT DESCRIPTION $600. ;
IF _N_ = 1 THEN DO;
	PUT "USER,ACT_DT,DESCRIPTION";
END;
DO;
   PUT USER $ @;
   PUT ACT_DT @;
   PUT DESCRIPTION $ ;
END;
RUN;
