/****** Object:  StoredProcedure [dbo].[spMD_GetDemographicData]    Script Date: 09/02/2016 09:19:11 ******/
CREATE  PROCEDURE [dbo].[spMD_GetDemographicData]

	@AccountNumber			VARCHAR(10) 
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SELECT DISTINCT
		--borrower info
		LTRIM(RTRIM(PD10.DF_SPE_ACC_ID)) AS AccountNumber,
		LTRIM(RTRIM(PD10.DF_PRS_ID)) AS SSN,
		LTRIM(RTRIM(PD10.DM_PRS_1)) AS FirstName,
		LTRIM(RTRIM(PD10.DM_PRS_LST)) AS LastName,
		LTRIM(RTRIM(PD10.DM_PRS_MID )) AS MI,
		CASE PD10.DM_PRS_MID
			WHEN '' THEN LTRIM(RTRIM(PD10.DM_PRS_1)) + ' ' + LTRIM(RTRIM(PD10.DM_PRS_LST))
			ELSE LTRIM(RTRIM(PD10.DM_PRS_1)) + ' ' + LTRIM(RTRIM(PD10.DM_PRS_MID)) + ' ' + LTRIM(RTRIM(PD10.DM_PRS_LST))
		END	AS FullName,
		CONVERT(VARCHAR, PD10.DD_BRT, 101) AS DOB,
		--address info
		LTRIM(RTRIM(PD30.DX_STR_ADR_1)) AS Address1,
		LTRIM(RTRIM(PD30.DX_STR_ADR_2)) AS Address2,
		LTRIM(RTRIM(PD30.DM_CT)) AS City,
		LTRIM(RTRIM(PD30.DC_DOM_ST)) AS State,
		LTRIM(RTRIM(PD30.DF_ZIP_CDE)) AS Zip,
		LTRIM(RTRIM(PD30.DM_FGN_ST)) AS ForeignState,
		LTRIM(RTRIM(PD30.DM_FGN_CNY)) AS Country,
		CONVERT(VARCHAR, PD30.DD_VER_ADR, 101) AS AddressVerifiedDate,
		PD30.DI_VLD_ADR AS AddressValidityIndicator,
		--home phone info
		MAX(CASE 
			WHEN PD42.DC_PHN = 'H' THEN CASE 
											WHEN PD42.DC_ALW_ADL_PHN IN ('N','P') THEN 'M' 
											WHEN PD42.DC_ALW_ADL_PHN IN ('L','Q') THEN 'L' 
											WHEN PD42.DC_ALW_ADL_PHN IN ('U','X') THEN 'U' 
										END
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS HomePhoneMBLIndicator,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'H' THEN CASE 
											WHEN PD42.DC_ALW_ADL_PHN IN ('L','P','X') THEN 'Y' 
											ELSE 'N'
										END
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS HomePhoneConsentIndicator,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'H' THEN ISNULL(CONVERT(VARCHAR, PD42.DD_PHN_VER, 101), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS HomePhoneVerifiedDate,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'H' THEN ISNULL(PD42.DI_PHN_VLD, '') 
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS HomePhoneValidityIndicator,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'H' THEN ISNULL(LTRIM(RTRIM(PD42.DN_DOM_PHN_ARA)) + LTRIM(RTRIM(PD42.DN_DOM_PHN_XCH)) + LTRIM(RTRIM(PD42.DN_DOM_PHN_LCL)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS HomePhone,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'H' THEN ISNULL(LTRIM(RTRIM(PD42.DN_PHN_XTN)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS HomePhoneExtension,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'H' THEN ISNULL(LTRIM(RTRIM(PD42.DN_FGN_PHN_CNY)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS HomePhoneForeignCountry,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'H' THEN ISNULL(LTRIM(RTRIM(PD42.DN_FGN_PHN_CT)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS HomePhoneForeignCity,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'H' THEN ISNULL(LTRIM(RTRIM(PD42.DN_FGN_PHN_LCL)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS HomePhoneForeignLocalNumber,
		--alternate phone info
		MAX(CASE 
			WHEN PD42.DC_PHN = 'A' THEN CASE 
											WHEN PD42.DC_ALW_ADL_PHN IN ('N','P') THEN 'M' 
											WHEN PD42.DC_ALW_ADL_PHN IN ('L','Q') THEN 'L' 
											WHEN PD42.DC_ALW_ADL_PHN IN ('U','X') THEN 'U' 
										END
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS AlternatePhoneMBLIndicator,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'A' THEN CASE 
											WHEN PD42.DC_ALW_ADL_PHN IN ('L','P','X') THEN 'Y' 
											ELSE 'N'
										END
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS AlternatePhoneConsentIndicator,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'A' THEN ISNULL(CONVERT(VARCHAR, PD42.DD_PHN_VER,101), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS AlternatePhoneVerifiedDate,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'A' THEN ISNULL(PD42.DI_PHN_VLD, '') 
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS AlternatePhoneValidityIndicator,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'A' THEN ISNULL(LTRIM(RTRIM(PD42.DN_DOM_PHN_ARA)) + LTRIM(RTRIM(PD42.DN_DOM_PHN_XCH)) + LTRIM(RTRIM(PD42.DN_DOM_PHN_LCL)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS AlternatePhone,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'A' THEN ISNULL(LTRIM(RTRIM(PD42.DN_PHN_XTN)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS AlternatePhoneExtension,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'A' THEN ISNULL(LTRIM(RTRIM(PD42.DN_FGN_PHN_CNY)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS AlternatePhoneForeignCountry,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'A' THEN ISNULL(LTRIM(RTRIM(PD42.DN_FGN_PHN_CT)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS AlternatePhoneForeignCity,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'A' THEN ISNULL(LTRIM(RTRIM(PD42.DN_FGN_PHN_LCL)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS AlternatePhoneForeignLocalNumber,
		--work phone info
		MAX(CASE 
			WHEN PD42.DC_PHN = 'W' THEN CASE 
											WHEN PD42.DC_ALW_ADL_PHN IN ('N','P') THEN 'M' 
											WHEN PD42.DC_ALW_ADL_PHN IN ('L','Q') THEN 'L' 
											WHEN PD42.DC_ALW_ADL_PHN IN ('U','X') THEN 'U' 
										END
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS WorkPhoneMBLIndicator,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'W' THEN CASE 
											WHEN PD42.DC_ALW_ADL_PHN IN ('L','P','X') THEN 'Y' 
											ELSE 'N'
										END
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS WorkPhoneConsentIndicator,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'W' THEN ISNULL(CONVERT(VARCHAR, PD42.DD_PHN_VER, 101), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS WorkPhoneVerifiedDate,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'W' THEN ISNULL(PD42.DI_PHN_VLD, '') 
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS WorkPhoneValidityIndicator,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'W' THEN ISNULL(LTRIM(RTRIM(PD42.DN_DOM_PHN_ARA)) + LTRIM(RTRIM(PD42.DN_DOM_PHN_XCH)) + LTRIM(RTRIM(PD42.DN_DOM_PHN_LCL)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS WorkPhone,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'W' THEN ISNULL(LTRIM(RTRIM(PD42.DN_PHN_XTN)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS WorkPhoneExtension,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'W' THEN ISNULL(LTRIM(RTRIM(PD42.DN_FGN_PHN_CNY)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS WorkPhoneForeignCountry,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'W' THEN ISNULL(LTRIM(RTRIM(PD42.DN_FGN_PHN_CT)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS WorkPhoneForeignCity,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'W' THEN ISNULL(LTRIM(RTRIM(PD42.DN_FGN_PHN_LCL)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS WorkPhoneForeignLocalNumber,
		--mobile phone info
		MAX(CASE 
			WHEN PD42.DC_PHN = 'M' THEN CASE 
											WHEN PD42.DC_ALW_ADL_PHN IN ('N','P') THEN 'M' 
											WHEN PD42.DC_ALW_ADL_PHN IN ('L','Q') THEN 'L' 
											WHEN PD42.DC_ALW_ADL_PHN IN ('U','X') THEN 'U' 
										END
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS MobilePhoneMBLIndicator,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'M' THEN CASE 
											WHEN PD42.DC_ALW_ADL_PHN IN ('L','P','X') THEN 'Y' 
											ELSE 'N'
										END
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS MobilePhoneConsentIndicator,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'M' THEN ISNULL(CONVERT(VARCHAR, PD42.DD_PHN_VER, 101), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS MobilePhoneVerifiedDate,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'M' THEN ISNULL(PD42.DI_PHN_VLD, '') 
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS MobilePhoneValidityIndicator,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'M' THEN ISNULL(LTRIM(RTRIM(PD42.DN_DOM_PHN_ARA)) + LTRIM(RTRIM(PD42.DN_DOM_PHN_XCH)) + LTRIM(RTRIM(PD42.DN_DOM_PHN_LCL)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS MobilePhone,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'M' THEN ISNULL(LTRIM(RTRIM(PD42.DN_PHN_XTN)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS MobilePhoneExtension,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'M' THEN ISNULL(LTRIM(RTRIM(PD42.DN_FGN_PHN_CNY)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS MobilePhoneForeignCountry,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'M' THEN ISNULL(LTRIM(RTRIM(PD42.DN_FGN_PHN_CT)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS MobilePhoneForeignCity,
		MAX(CASE 
			WHEN PD42.DC_PHN = 'M' THEN ISNULL(LTRIM(RTRIM(PD42.DN_FGN_PHN_LCL)), '')
			ELSE ''
		END) OVER (PARTITION BY PD42.DF_PRS_ID) AS MobilePhoneForeignLocalNumber,
		--home email info
		MAX(CASE WHEN PD32.DC_ADR_EML = 'H' THEN ISNULL(PD32.DX_ADR_EML, '') ELSE '' END) OVER (PARTITION BY PD32.DF_PRS_ID) AS HomeEmail,
		MAX(CASE WHEN PD32.DC_ADR_EML = 'H' THEN ISNULL(CONVERT(VARCHAR,PD32.DD_VER_ADR_EML,101), '') ELSE '' END) OVER (PARTITION BY PD32.DF_PRS_ID) AS HomeEmailVerifiedDate,
		MAX(CASE WHEN PD32.DC_ADR_EML = 'H' THEN ISNULL(PD32.DI_VLD_ADR_EML, '') ELSE '' END) OVER (PARTITION BY PD32.DF_PRS_ID) AS HomeEmailValidityIndicator,
		--alternate email info
		MAX(CASE WHEN PD32.DC_ADR_EML = 'A' THEN ISNULL(PD32.DX_ADR_EML, '') ELSE '' END) OVER (PARTITION BY PD32.DF_PRS_ID) AS AlternateEmail,
		MAX(CASE WHEN PD32.DC_ADR_EML = 'A' THEN ISNULL(CONVERT(VARCHAR,PD32.DD_VER_ADR_EML, 101), '') ELSE '' END) OVER (PARTITION BY PD32.DF_PRS_ID) AS AlternateEmailVerifiedDate,
		MAX(CASE WHEN PD32.DC_ADR_EML = 'A' THEN ISNULL(PD32.DI_VLD_ADR_EML, '') ELSE '' END) OVER (PARTITION BY PD32.DF_PRS_ID) AS AlternateEmailValidityIndicator,
		--work email info
		MAX(CASE WHEN PD32.DC_ADR_EML = 'W' THEN ISNULL(PD32.DX_ADR_EML, '') ELSE '' END) OVER (PARTITION BY PD32.DF_PRS_ID) AS WorkEmail,
		MAX(CASE WHEN PD32.DC_ADR_EML = 'W' THEN ISNULL(CONVERT(VARCHAR, PD32.DD_VER_ADR_EML,101), '') ELSE '' END) OVER (PARTITION BY PD32.DF_PRS_ID) AS WorkEmailVerifiedDate,
		MAX(CASE WHEN PD32.DC_ADR_EML = 'W' THEN ISNULL(PD32.DI_VLD_ADR_EML, '') ELSE '' END) OVER (PARTITION BY PD32.DF_PRS_ID) AS WorkEmailValidityIndicator,
		--E-CORR Indicator
		CAST(CASE WHEN PH05.DI_CNC_ELT_OPI = 'Y' THEN 1 ELSE 0 END AS BIT) as EcorrCorrespondence,
		CAST(CASE WHEN PH05.DI_CNC_EBL_OPI = 'Y' THEN 1 ELSE 0 END AS BIT) as EcorrBilling,
		CAST(CASE WHEN PH05.DI_CNC_TAX_OPI = 'Y' THEN 1 ELSE 0 END AS BIT) as EcorrTax,
		CAST(CASE WHEN AD20.BF_SSN IS NOT NULL AND AD20.LC_TYP_FAT_ADJ_REQ = '71'THEN 1 ELSE 0 END AS BIT) AS HasPendingDisbursementCancellation,
		 CAST(0 AS BIT) AS HasSulaLoans,
		CAST(CASE WHEN LOANS.TOTAL_LOAN_COUNT = LOANS.DCON_LOAN_COUNT THEN 1 ELSE 0 END AS BIT) as NeedsDeconArc,
		LOANS.RelationshipStartDate,
		CAST(CASE WHEN LOANS.TOTAL_LOAN_COUNT = LOANS.PCON_LOAN_COUNT THEN 1 ELSE 0 END AS BIT) AS EndProcessingAfterDemosPage
	FROM
		PD10_PRS_NME PD10 
		INNER JOIN PD30_PRS_ADR PD30 ON
			PD10.DF_PRS_ID = PD30.DF_PRS_ID
		LEFT JOIN PD42_PRS_PHN PD42
			ON PD42.DF_PRS_ID = PD10.DF_PRS_ID
		LEFT JOIN PD32_PRS_ADR_EML PD32
			ON PD32.DF_PRS_ID = PD10.DF_PRS_ID
			AND PD32.DC_STA_PD32 = 'A'
		LEFT JOIN PH05_CNC_EML PH05 
			ON PH05.DF_SPE_ID = PD10.DF_SPE_ACC_ID
		LEFT JOIN AD20_PCV_ATY_ADJ AD20
			ON AD20.BF_SSN = PD10.DF_PRS_ID	
		LEFT JOIN
		(
			SELECT
				BF_SSN,
				COUNT(*) OVER (PARTITION BY LN10.BF_SSN) AS TOTAL_LOAN_COUNT,
				SUM(CASE WHEN LN10.LC_STA_LON10 = 'D' THEN 1 ELSE 0 END) OVER (PARTITION BY LN10.BF_SSN) AS DCON_LOAN_COUNT,
				SUM(CASE WHEN LN10.LC_STA_LON10 = 'P' THEN 1 ELSE 0 END) OVER (PARTITION BY LN10.BF_SSN) AS PCON_LOAN_COUNT,
				MIN(LD_LON_ACL_ADD) OVER (PARTITION BY LN10.BF_SSN) AS RelationshipStartDate
			FROM
				LN10_LON LN10
				INNER JOIN PD10_PRS_NME PD10
					ON LN10.BF_SSN = PD10.DF_PRS_ID
			WHERE
				PD10.DF_SPE_ACC_ID = @AccountNumber
		) LOANS
			ON LOANS.BF_SSN = PD10.DF_PRS_ID								  
	WHERE 
		PD10.DF_SPE_ACC_ID = @AccountNumber
		AND PD30.DC_ADR = 'L'
			
END
GO
GRANT EXECUTE
    ON OBJECT::[dbo].[spMD_GetDemographicData] TO [UHEAA\Imaging Users]
    AS [dbo];

