--WE ARE TRUNCATING THE TABLE BECAUSE THIS WILL BE THE FIRST QUERY TO INSERT DATA
--TRUNCATE TABLE CDW..CS_Transfer4
--TRUNCATE TABLE CDW..CS_Transfer4Loans
--INSERT INTO CDW..CS_Transfer4
SELECT
	POP.*,
	SUM(CASE WHEN LN10.LC_FED_PGM_YR = 'LNC' THEN 1 ELSE 0 END) AS LNC_Count,
	SUM(CASE WHEN LN10.LC_FED_PGM_YR = 'DLO' THEN 1 ELSE 0 END) AS DLO_Count,
	NULL AS LNC_SaleId,
	NULL AS DLO_SaleId,
	NULL,
	NULL
FROM
(
SELECT DISTINCT 
	LN10.BF_SSN,
	'ALL BORROWERS' AS [POPULATION]
FROM 
	CDW..LN10_LON LN10
	LEFT JOIN CDW..CS_Transfer3 T3
		ON T3.BF_SSN = LN10.BF_SSN
WHERE
	LN10.LA_CUR_PRI > 0.00
	AND LN10.LC_STA_LON10 = 'R'
	AND T3.BF_SSN IS NULL
) POP
INNER JOIN CDW..LN10_LON LN10
	ON LN10.BF_SSN = POP.BF_SSN
	AND LN10.LA_CUR_PRI > 0
	AND LN10.LC_STA_LON10 = 'R'
GROUP BY
	POP.BF_SSN,
	POP.[POPULATION]
--229044