
CREATE PROCEDURE [dbo].[LT_US09B60CP_FormFields]
	@BF_SSN  CHAR(9)
AS

	SELECT
		RTRIM(PD10.DM_PRS_1) + ' ' + RTRIM(PD10.DM_PRS_LST) AS BorName
	FROM
		[dbo].[AY10_BR_LON_ATY] AY10
		JOIN [dbo].[PD10_PRS_NME] PD10 ON AY10.BF_SSN = PD10.DF_PRS_ID
	WHERE
		AY10.BF_SSN = @BF_SSN
		AND AY10.PF_REQ_ACT = 'END60'
		AND AY10.LF_LST_DTS_AY10 > DATEADD(DAY, -14, GETDATE())

RETURN 0