
CREATE PROCEDURE [dbo].[LT_US10BTREFC_FormFields]
	@BF_SSN  CHAR(9)
AS

	SELECT
		RTRIM(PD10.[DM_PRS_1]) + ' ' + RTRIM(PD10.[DM_PRS_LST]) [BorrName]
	FROM
		[dbo].[PD10_PRS_NME] PD10
	WHERE
		PD10.DF_PRS_ID = @BF_SSN

RETURN 0