CREATE PROCEDURE [acurintc].[GetBorrowerRecentPhoneHistory]
	@Ssn CHAR(9)
AS

	SELECT
		RTRIM(PD41.DN_DOM_PHN_ARA_HST + PD41.DN_DOM_PHN_XCH_HST + PD41.DN_DOM_PHN_LCL_HST + PD41.DN_PHN_XTN_HST) [PhoneNumber],
		CAST(CASE WHEN PD41.DI_PHN_VLD_HST = 'Y' THEN 1 ELSE 0 END AS BIT) [PhoneIsValid],
		PD41.DD_PHN_VER_HST [VerificationDate]
	FROM
		UDW..PD41_PHN_HST PD41
	WHERE
		PD41.DD_PHN_VER_HST > DATEADD(YEAR, -1, GETDATE())
		AND
		PD41.DC_PHN_HST IN ('H', 'A', 'W', 'M')
		AND
		PD41.DF_PRS_ID = @Ssn

RETURN 0
