/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/UNWS08.NWS08RZ";
FILENAME REPORT2 "&RPTLIB/UNWS08.NWS08R2";
FILENAME REPORT3 "&RPTLIB/UNWS08.NWS08R3";
LIBNAME  LEGEND  REMOTE  SERVER=LEGEND SLIBREF=work  ;
RSUBMIT;
LIBNAME pkub DB2 DATABASE=DNFPUTDL OWNER=pkub;
PROC SQL;
CONNECT TO DB2 (DATABASE=DNFPUTDL);
CREATE TABLE RPS_DIS AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT F.DF_SPE_ACC_ID
	,A.BA_EFT_ADD_WDR
FROM pkub.PD10_PRS_NME F
	INNER JOIN pkub.BR30_BR_EFT A
		ON F.DF_PRS_ID = A.BF_SSN
	INNER JOIN pkub.LN10_LON B
		ON B.BF_SSN = A.BF_SSN
	INNER JOIN pkub.LN65_LON_RPS C
		ON B.BF_SSN = C.BF_SSN
		AND B.LN_SEQ = C.LN_SEQ
	INNER JOIN pkub.LN66_LON_RPS_SPF D
		ON C.BF_SSN = D.BF_SSN
		AND C.LN_SEQ = D.LN_SEQ
		AND C.LN_RPS_SEQ = D.LN_RPS_SEQ
	INNER JOIN pkub.LN66_LON_RPS_SPF E
		ON D.BF_SSN = E.BF_SSN
		AND D.LN_SEQ = E.LN_SEQ
		AND D.LN_GRD_RPS_SEQ = E.LN_GRD_RPS_SEQ 
		AND D.LN_RPS_SEQ - 1 = E.LN_RPS_SEQ 

WHERE BC_EFT_STA = 'A'
	AND C.LC_STA_LON65 = 'A'
	AND DAYS(C.LD_CRT_LON65) = DAYS(CURRENT DATE) - 1
	AND A.BA_EFT_ADD_WDR > 0
/*	AND D.LN_GRD_RPS_SEQ = 1*/
/*	AND E.LN_GRD_RPS_SEQ = 1*/
	AND D.LA_RPS_ISL <> E.LA_RPS_ISL
);
DISCONNECT FROM DB2;
QUIT;
 
ENDRSUBMIT;
DATA RPS_DIS; SET LEGEND.RPS_DIS; RUN;

PROC SORT DATA=RPS_DIS; BY DF_SPE_ACC_ID; RUN;

DATA _NULL_;
SET RPS_DIS ;
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
/*IF _N_ = 1 THEN DO;*/
/*	PUT "TARGET_ID,ARC_NAME,FROM_DATE,TO_DATE,NEEDED_BY_DATE,RECIPIENT_ID,REGARDS_TO_CODE,REGARDS_TO_ID,LOAN_SEQ,COMMENTS";*/
/*END;*/
DO;
   PUT DF_SPE_ACC_ID 'RPACH,,,,,,,ALL,' BA_EFT_ADD_WDR ;
END;
RUN;
