CREATE PROCEDURE [dbo].[LT_Header_Footer]
	@BF_SSN VARCHAR(9),
	@IsCoborrower BIT = 0
AS
BEGIN

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

IF @IsCoborrower = 0
	BEGIN
		SELECT
			--borrower info
			REPLACE(LTRIM(RTRIM(BORR.DM_PRS_1)),',','')  + ' ' + REPLACE(LTRIM(RTRIM(BORR.DM_PRS_LST)),',','') + ' ' + REPLACE(LTRIM(RTRIM(BORR.DM_PRS_LST_SFX)),',','')  AS Name,
			--address info
			REPLACE(LTRIM(RTRIM(ADDR.DX_STR_ADR_1)),',','')  AS Address1,
			REPLACE(LTRIM(RTRIM(ADDR.DX_STR_ADR_2)),',','')  AS Address2,
			REPLACE(LTRIM(RTRIM(ADDR.DM_FGN_CNY)),',','') AS Country,
			BORR.DF_SPE_ACC_ID AS AccountNumber,
			REPLACE(LTRIM(RTRIM(ADDR.DM_CT)),',','')  AS City,
			CASE
				WHEN LEN(RTRIM(ADDR.DM_FGN_ST)) > 0 THEN  RTRIM(ADDR.DM_FGN_ST)
				ELSE RTRIM(ADDR.DC_DOM_ST)
			END AS [State],
			CASE WHEN LEN(ADDR.DF_ZIP_CDE) = 9 
				THEN LEFT(LTRIM(RTRIM(ADDR.DF_ZIP_CDE)), 5) + '-' + RIGHT(LTRIM(RTRIM(ADDR.DF_ZIP_CDE)), 4)
				ELSE LTRIM(RTRIM(ADDR.DF_ZIP_CDE))
			END AS Zip,
			CASE WHEN DI_VLD_ADR = 'Y' 
				THEN 1
				ELSE 0
			END AS HasValidAddress,
			'Monday - Friday 8 AM - 5 PM MT.' AS Hours1,
			'' AS Hours2
		FROM
			PD10_PRS_NME BORR
			INNER JOIN PD30_PRS_ADR ADDR 
				ON ADDR.DF_PRS_ID = BORR.DF_PRS_ID
		WHERE
			BORR.DF_PRS_ID = @BF_SSN
			AND ADDR.DC_ADR = 'L'
	END
ELSE
	BEGIN
		SELECT DISTINCT
			--borrower info
			REPLACE(LTRIM(RTRIM(ENDR.DM_PRS_1)),',','')  + ' ' + REPLACE(LTRIM(RTRIM(ENDR.DM_PRS_LST)),',','') + ' ' + REPLACE(LTRIM(RTRIM(ENDR.DM_PRS_LST_SFX)),',','')  AS Name,
			--address info
			REPLACE(LTRIM(RTRIM(ADDR.DX_STR_ADR_1)),',','')  AS Address1,
			REPLACE(LTRIM(RTRIM(ADDR.DX_STR_ADR_2)),',','')  AS Address2,
			REPLACE(LTRIM(RTRIM(ADDR.DM_FGN_CNY)),',','') AS Country,
			BORR.DF_SPE_ACC_ID AS AccountNumber,
			REPLACE(LTRIM(RTRIM(ADDR.DM_CT)),',','')  AS City,
			CASE
				WHEN LEN(RTRIM(ADDR.DM_FGN_ST)) > 0 THEN  RTRIM(ADDR.DM_FGN_ST)
				ELSE RTRIM(ADDR.DC_DOM_ST)
			END AS [State],
			CASE WHEN LEN(ADDR.DF_ZIP_CDE) = 9 
				THEN LEFT(LTRIM(RTRIM(ADDR.DF_ZIP_CDE)), 5) + '-' + RIGHT(LTRIM(RTRIM(ADDR.DF_ZIP_CDE)), 4)
				ELSE LTRIM(RTRIM(ADDR.DF_ZIP_CDE))
			END AS Zip,
			CASE WHEN DI_VLD_ADR = 'Y' 
				THEN 1
				ELSE 0
			END AS HasValidAddress,
			'Monday - Friday 8 AM - 5 PM MT.' AS Hours1,
			'' AS Hours2
		FROM
			PD10_PRS_NME ENDR 
			INNER JOIN LN20_EDS LN20
				ON LN20.LF_EDS = ENDR.DF_PRS_ID
				AND LN20.LC_EDS_TYP = 'M'
				AND LN20.LC_STA_LON20 = 'A'
			INNER JOIN PD30_PRS_ADR ADDR 
				ON ADDR.DF_PRS_ID = ENDR.DF_PRS_ID
				AND ADDR.DC_ADR = 'L'
			INNER JOIN PD10_PRS_NME BORR
				ON BORR.DF_PRS_ID = LN20.BF_SSN
			INNER JOIN LT20_LTR_REQ_PRC_Coborrower LT20Pending --coborrowers that coborrower for multiple borrowers handling
				ON LT20Pending.Borrower_DF_SPE_ACC_ID = BORR.DF_SPE_ACC_ID
				AND LT20Pending.DF_SPE_ACC_ID = ENDR.DF_SPE_ACC_ID
				AND 
				(
					(
						LT20Pending.PrintedAt IS NULL 
						AND LT20Pending.OnEcorr = 0
					) 
					OR LT20Pending.EcorrDocumentCreatedAt IS NULL
				)
				AND LT20Pending.InactivatedAt IS NULL
		WHERE 
			ENDR.DF_PRS_ID = @BF_SSN
	END
END
