
--********
--MAKE SURE THIS IS THE DATE YOU ARE LOOKING AT
--********
DECLARE @ERROR_DATE DATE = CAST(GETDATE() AS DATE)

SELECT DISTINCT
	CD.*
FROM
	CLS.emailbtcf.CampaignData CD
	INNER JOIN CDW..PD10_PRS_NME PD10
		ON CD.AccountNumber = PD10.DF_SPE_ACC_ID
	INNER JOIN CDW..DW01_DW_CLC_CLU DW01
		ON DW01.BF_SSN = PD10.DF_PRS_ID
WHERE
	DW01.WC_DW_LON_STA IN ('17','19','21')
	AND CD.AddedAt > @ERROR_DATE



--print processing
SELECT
	LK10.PX_DSC_MDM,
	sd.ScriptId,
	PP.*
FROM
	CDW..DW01_DW_CLC_CLU DW01
	INNER JOIN CDW..LK10_LS_CDE_LKP LK10
		ON LK10.PM_ATR = 'WC-DW-LON-STA'
		AND LK10.PX_ATR_VAL = DW01.WC_DW_LON_STA
	INNER JOIN CDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = DW01.BF_SSN
	INNER JOIN CLS.[print].PrintProcessing PP
		ON PP.AccountNumber = PD10.DF_SPE_ACC_ID
	INNER JOIN CLS.[print].ScriptData SD
		ON SD.ScriptDataId = pp.ScriptDataId
WHERE
	DW01.WC_DW_LON_STA IN ('17','19','21')
	AND PP.ADDEDAT > @ERROR_DATE


SELECT
	LK10.PX_DSC_MDM,
	PP.*
FROM
	CDW..DW01_DW_CLC_CLU DW01
	INNER JOIN CDW..LK10_LS_CDE_LKP LK10
		ON LK10.PM_ATR = 'WC-DW-LON-STA'
		AND LK10.PX_ATR_VAL = DW01.WC_DW_LON_STA
	INNER JOIN CDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = DW01.BF_SSN
	INNER JOIN CLS.[billing].PrintProcessing PP
		ON PP.AccountNumber = PD10.DF_SPE_ACC_ID
WHERE
	DW01.WC_DW_LON_STA IN ('17','19','21')
	AND PP.ADDEDAT > @ERROR_DATE

SELECT
	LK10.PX_DSC_MDM,
	PP.*
FROM
	CDW..DW01_DW_CLC_CLU DW01
	INNER JOIN CDW..LK10_LS_CDE_LKP LK10
		ON LK10.PM_ATR = 'WC-DW-LON-STA'
		AND LK10.PX_ATR_VAL = DW01.WC_DW_LON_STA
	INNER JOIN CDW..PD10_PRS_NME PD10
		ON PD10.DF_PRS_ID = DW01.BF_SSN
	INNER JOIN cdw..LT20_LTR_REQ_PRC PP
		ON PP.DF_SPE_ACC_ID = PD10.DF_SPE_ACC_ID
WHERE
	DW01.WC_DW_LON_STA IN ('17','19','21')
	AND PP.CreatedAt > @ERROR_DATE
	AND
	(
		PP.EcorrDocumentCreatedAt IS NOT NULL
		OR 
		PP.PrintedAt IS NOT NULL
	)

