/*TEST*/
/*%LET TESTMSG = - THIS IS A TEST;
%LET RPTLIB = T:\SAS;
%LET LOGLIB = Y:\Batch\Logs;
%LET CODELIB = Y:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS_TEST;
%LET DB = CDW_test;
%LET ODBCFILE_CSYS = CSYSTest;*/

/*LIVE*/
%LET TESTMSG = - THIS IS LIVE;
%LET RPTLIB = Z:\Batch\FTP;
%LET LOGLIB = Z:\Batch\Logs;
%LET CODELIB = Z:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS;
%LET DB = CDW;
%LET ODBCFILE_CSYS = CSYS;

%INCLUDE "&CODELIB\UTNWDW1 CDW DAILY UPDATE.FOLDER AND DATABASE.SAS";
%FILECHECK(29);


DATA DW01(DROP=WX_OVR_DW_LON_STA trunc) ;
	INFILE REPORT29 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
	INPUT DF_SPE_ACC_ID :$10. LN_SEQ :6. WC_DW_LON_STA :$2. WA_TOT_BRI_OTS :14.2 WD_LON_RPD_SR :$10. WX_OVR_DW_LON_STA :$20. ;
	FORMAT DW_LON_STA $25.;

	IF WX_OVR_DW_LON_STA = 'LITIGATION' THEN DW_LON_STA = 'DEFAULT - PRIOR REHAB';
	ELSE IF WX_OVR_DW_LON_STA ^= '' THEN DW_LON_STA = WX_OVR_DW_LON_STA;
	ELSE DW_LON_STA = PUT(WC_DW_LON_STA,$LONSTA.);

%TRUNCAT(29);
RUN;
%COPYERROR;
PROC SORT DATA=DW01 ; BY DF_SPE_ACC_ID LN_SEQ; RUN;
DATA DW01; SET DW01; BY DF_SPE_ACC_ID LN_SEQ; IF LAST.LN_SEQ; RUN;

%ENCHILADA(DW01,DW01_LOAN,DF_SPE_ACC_ID LN_SEQ,WC_DW_LON_STA WA_TOT_BRI_OTS WD_LON_RPD_SR DW_LON_STA,);

%GOODBYE_NULL(DW01_LOAN,WC_DW_LON_STA,'');
%GOODBYE_NULL(DW01_LOAN,DW_LON_STA,'');
%GOODBYE_NULL(DW01_LOAN,WA_TOT_BRI_OTS,0);
%GOODBYE_NULL(DW01_LOAN,WD_LON_RPD_SR,'');

%FINISH(SOURCE=Loan2);
