/*TEST*/
/*%LET TESTMSG = - THIS IS A TEST;
%LET RPTLIB = T:\SAS;
%LET LOGLIB = Y:\Batch\Logs;
%LET CODELIB = Y:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS_TEST;
%LET DB = CDW_test;
%LET ODBCFILE_CSYS = CSYSTest;*/

/*LIVE*/
%LET TESTMSG = - THIS IS LIVE;
%LET RPTLIB = Z:\Batch\FTP;
%LET LOGLIB = Z:\Batch\Logs;
%LET CODELIB = Z:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS;
%LET DB = CDW;
%LET ODBCFILE_CSYS = CSYS;

%INCLUDE "&CODELIB\UTNWDW1 CDW DAILY UPDATE.FOLDER AND DATABASE.SAS"  ;
%FILECHECK(42);

DATA IDR_REPAY(drop=trunc);
	INFILE REPORT42 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof LRECL = 32767;
	INPUT 
		DF_SPE_ACC_ID :$10.
		BD_CRT_RS05 :DATE9.
		BN_IBR_SEQ :6.
		BF_CRY_YR :$4.
		BC_ST_IBR :$2.
		BC_STA_RS05 :$1.
		BA_AGI :12.2
		BN_MEM_HSE_HLD :6.
		BA_PMN_STD_TOT_PAY :12.2
		BC_IBR_INF_SRC_VER :$3.
		BF_SSN_SPO :$9.
		BC_IRS_TAX_FIL_STA :$1.
		BI_JNT_BR_SPO_RPY :$1.
		BD_ANV_QLF_IBR :DATE9.
	;
	%TRUNCAT(42);
RUN;

/*convert SAS dates to SQL Server datetime*/
DATA IDR_REPAY;
	SET IDR_REPAY;
	BD_CRT_RS05 = BD_CRT_RS05*86400;
	BD_ANV_QLF_IBR = BD_ANV_QLF_IBR*86400;
RUN;

%COPYERROR;

%ENCHILADA
	(
		IDR_REPAY,
		RS05_IDR_Repayment,
		DF_SPE_ACC_ID
		BD_CRT_RS05
		BN_IBR_SEQ,
		BF_CRY_YR
		BC_ST_IBR
		BC_STA_RS05
		BA_AGI
		BN_MEM_HSE_HLD
		BA_PMN_STD_TOT_PAY
		BC_IBR_INF_SRC_VER
		BF_SSN_SPO
		BC_IRS_TAX_FIL_STA
		BI_JNT_BR_SPO_RPY
		BD_ANV_QLF_IBR,
/*		no filter*/
	);

%FINISH(SOURCE=RS05IDRRepayment);
