/*TEST*/
/*%LET TESTMSG = - THIS IS A TEST;
%LET RPTLIB = T:\SAS;
%LET LOGLIB = Y:\Batch\Logs;
%LET CODELIB = Y:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS_TEST;
%LET DB = CDW_test;
%LET ODBCFILE_CSYS = CSYSTest;*/

/*LIVE*/
%LET TESTMSG = - THIS IS LIVE;
%LET RPTLIB = Z:\Batch\FTP;
%LET LOGLIB = Z:\Batch\Logs;
%LET CODELIB = Z:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS;
%LET DB = CDW;
%LET ODBCFILE_CSYS = CSYS;

%INCLUDE "&CODELIB\UTNWDW1 CDW DAILY UPDATE.FOLDER AND DATABASE.SAS";
%FILECHECK(2);

DATA LN20(drop=trunc);
INFILE REPORT2 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
INPUT DF_SPE_ACC_ID :$10. LN_SEQ :6. LC_STA_LON20 :$1. ;
%TRUNCAT(2);
RUN;
%COPYERROR;
PROC SORT DATA=LN20; BY DF_SPE_ACC_ID LN_SEQ; RUN;
DATA LN20; SET LN20; BY DF_SPE_ACC_ID LN_SEQ; IF LAST.LN_SEQ; RUN;

%ENCHILADA(LN20,LN20_ENDORSER,DF_SPE_ACC_ID LN_SEQ,LC_STA_LON20,WHERE LC_STA_LON20 = 'A');

%FINISH(SOURCE=Endorser);
