/*TEST*/
/*%LET TESTMSG = - THIS IS A TEST;
%LET RPTLIB = T:\SAS;
%LET LOGLIB = Y:\Batch\Logs;
%LET CODELIB = Y:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS_TEST;
%LET DB = CDW_test;
%LET ODBCFILE_CSYS = CSYSTest;*/

/*LIVE*/
%LET TESTMSG = - THIS IS LIVE;
%LET RPTLIB = Z:\Batch\FTP;
%LET LOGLIB = Z:\Batch\Logs;
%LET CODELIB = Z:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS;
%LET DB = CDW;
%LET ODBCFILE_CSYS = CSYS;

%INCLUDE "&CODELIB\UTNWDW1 CDW DAILY UPDATE.FOLDER AND DATABASE.SAS"  ;
%FILECHECK(39);

options mprint;

DATA DFR_LTR(drop=trunc);
	INFILE REPORT39 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof LRECL = 32767;
	INPUT 
		DF_SPE_ACC_ID :$10.
		LN_SEQ :6.
		LF_DFR_CTL_NUM :$3.
		LN_DFR_OCC_SEQ :6.
		LC_DFR_TYP :$2.
		LD_DFR_INF_CER :DATE9.
		LD_CRT_REQ_DFR :DATE9.
		LC_DFR_STA :$1.
		LC_STA_DFR10 :$1.
		LD_STA_DFR10 :DATE9.
		LF_LST_DTS_DF10 :DATETIME25.3
		LD_DFR_BEG :DATE9.
		LD_DFR_END :DATE9.
		LC_STA_LON50 :$1.
		LC_LON_LEV_DFR_CAP :$1.
		LF_LST_DTS_LN50 :DATETIME25.3
		LD_STA_LON50 :DATE9.
		LD_DFR_APL :DATE9.
	;
	%TRUNCAT(39);
RUN;

/*convert SAS dates to SQL Server datetime*/
DATA DFR_LTR;
	SET DFR_LTR;
	LD_DFR_INF_CER = LD_DFR_INF_CER*86400;
	LD_CRT_REQ_DFR = LD_CRT_REQ_DFR*86400;
	LD_STA_DFR10 = LD_STA_DFR10*86400;
	LD_DFR_BEG = LD_DFR_BEG*86400;
	LD_DFR_END = LD_DFR_END*86400;
	LD_STA_LON50 = LD_STA_LON50*86400;
	LD_DFR_APL = LD_DFR_APL*86400;
RUN;

%COPYERROR;

%ENCHILADA
	(
		DFR_LTR,
		DF10_DefermentLetter,
		DF_SPE_ACC_ID
		LN_SEQ
		LF_DFR_CTL_NUM
		LN_DFR_OCC_SEQ,
		LC_DFR_TYP
		LD_DFR_INF_CER
		LD_CRT_REQ_DFR
		LC_DFR_STA
		LC_STA_DFR10
		LD_STA_DFR10
		LF_LST_DTS_DF10
		LD_DFR_BEG
		LD_DFR_END
		LC_STA_LON50
		LC_LON_LEV_DFR_CAP
		LF_LST_DTS_LN50
		LD_STA_LON50
		LD_DFR_APL,
/*		no filter*/
	);

%FINISH(SOURCE=DF10DefermentLetter);
