CREATE PROCEDURE [dbo].[LT_TS06RPYE45_Deadline]
	@AccountNumber		char(10)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	
SELECT DISTINCT
	CONVERT(CHAR(10),DATEADD(DAY, -25, RS05.BD_ANV_QLF_IBR),101) AS HardDeadline,
	PD10.DM_PRS_1 AS FirstName,
	LN66.LA_PRI_ATU_PAY AS EstAltPayAmt
FROM 
	PD10_Borrower PD10
	INNER JOIN RS05_IBR_RPS RS05
		ON PD10.BF_SSN = RS05.BF_SSN
	INNER JOIN LN65_LON_RPS LN65 
		ON LN65.BF_SSN = RS05.BF_SSN
		AND LN65.LC_STA_LON65 = 'A'
	INNER JOIN 
		(
			SELECT
				BF_SSN,
				LN_SEQ,
				LN_RPS_SEQ,
				SUM(ISNULL(LA_PRI_ATU_PAY,0)) AS LA_PRI_ATU_PAY
			FROM
				LN66_LON_RPS_SPF
			GROUP BY
				BF_SSN,
				LN_SEQ,
				LN_RPS_SEQ
		)LN66 ON LN66.BF_SSN = LN65.BF_SSN
		AND LN66.LN_SEQ = LN65.LN_SEQ
		AND LN66.LN_RPS_SEQ = LN65.LN_RPS_SEQ
	
WHERE 
	RS05.BC_STA_RS05 = 'A' 
	AND (LN65.LC_TYP_SCH_DIS LIKE '%I5%')
	AND PD10.DF_SPE_ACC_ID = @AccountNumber
	
END

IF @@ROWCOUNT = 0 
	BEGIN
		RAISERROR('No data returned.',11,2)
	END