CREATE PROCEDURE [dbo].[LT_TS06BAPIDR_TERMS]
	@AccountNumber VARCHAR(10)
AS
	DECLARE @QUERY VARCHAR(MAX), @TSQL VARCHAR(MAX)
	
	SELECT @TSQL = 'SELECT pop.RyeTermStart, DATEADD(YEAR, 1,pop.RyeTermStart) AS RyeTermEnd FROM OPENQUERY(LEGEND,'
	  SELECT  @QUERY = @TSQL + 
	  '''
		SELECT
			MAX(LD_RPS_1_PAY_DU) AS RyeTermStart
		FROM
			PKUB.LN65_LON_RPS LN65
			INNER JOIN PKUB.RS10_BR_RPD RS10
				ON RS10.BF_SSN = LN65.BF_SSN
				AND RS10.LN_RPS_SEQ = LN65.LN_RPS_SEQ
			INNER JOIN PKUB.PD10_PRS_NME PD10
				ON PD10.DF_PRS_ID = LN65.BF_SSN
		WHERE
			PD10.DF_SPE_ACC_ID = ''''' + @AccountNumber + '''''
			AND LN65.LC_STA_LON65 = ''''A''''
			AND RS10.LC_STA_RPST10 = ''''A''''
			AND LN65.LC_TYP_SCH_DIS = ''''I5''''
	  '')pop'
	  
	  EXEC(@QUERY)
	 
		IF(@@ROWCOUNT = 0)
			BEGIN
				RAISERROR('LT_TS06BAPIDR_TERMS RETURNED 0 RECORDS FOR ACCOUNT NUMBER:%s', 16, 1, @AccountNumber) 
			END
RETURN 0
