CREATE PROCEDURE [dbo].[LT_TS11BISF_Reversed_Transaction]
	@AccountNumber CHAR(10)
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;


	SELECT TOP 1
		PD10.DF_SPE_ACC_ID,
		LN90.LN_FAT_SEQ,
		SUM(ISNULL(LN90.LA_FAT_CUR_PRI, 0) + ISNULL(LN90.LA_FAT_ILG_PRI, 0) + ISNULL(LN90.LA_FAT_LTE_FEE, 0) + ISNULL(LN90.LA_FAT_NSI, 0) + ISNULL(LN90.LA_FAT_PCL_FEE, 0)) [LA_TRAN],
		CONVERT(VARCHAR(10), LN90.LD_FAT_EFF, 101) [LD_MAX_TRAN]
	FROM
		PD10_PRS_NME PD10
		INNER JOIN LN90_FIN_ATY LN90 ON LN90.BF_SSN = PD10.DF_PRS_ID
	WHERE
		PD10.DF_SPE_ACC_ID = @AccountNumber
		AND LN90.LC_FAT_REV_REA = '1'
		AND LN90.PC_FAT_TYP = '10'
		AND LN90.LC_STA_LON90 = 'A'
	GROUP BY
		PD10.DF_SPE_ACC_ID,
		LN90.LN_FAT_SEQ,
		LN90.LD_FAT_EFF
	ORDER BY
		LN90.LN_FAT_SEQ DESC

END

IF @@ROWCOUNT = 0 
	BEGIN
		RAISERROR('No data returned for Account Number: %s. ([dbo].[LT_TS11BISF_Reversed_Transaction])',16,2, @AccountNumber)
	END

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[LT_TS11BISF_Reversed_Transaction] TO [db_executor]
    AS [dbo];
