CREATE PROCEDURE [dbo].[LT_Header_Reference]
	@AccountNumber VARCHAR(10),
	@IsCoborrower BIT = 0
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT DISTINCT
		--borrower info
			REPLACE(LTRIM(RTRIM(PD10.DM_PRS_1)),',','')  + ' ' + REPLACE(LTRIM(RTRIM(PD10.DM_PRS_LST)),',','') + ' ' + REPLACE(LTRIM(RTRIM(PD10.DM_PRS_LST_SFX)),',','')  AS Name,
			--address info
			REPLACE(LTRIM(RTRIM(ADDR.DX_STR_ADR_1)),',','')  AS Address1,
			REPLACE(LTRIM(RTRIM(ADDR.DX_STR_ADR_2)),',','')  AS Address2,
			CASE WHEN LEN(LTRIM(RTRIM(ADDR.DF_ZIP_CDE))) = 9 
				THEN REPLACE(LTRIM(RTRIM(ADDR.DM_CT)),',','')  + ' ' + REPLACE(LTRIM(RTRIM(ADDR.DC_DOM_ST)),',','')  + '  ' + LEFT(LTRIM(RTRIM(ADDR.DF_ZIP_CDE)), 5) + '-' + RIGHT(LTRIM(RTRIM(ADDR.DF_ZIP_CDE)), 4)
				ELSE REPLACE(LTRIM(RTRIM(ADDR.DM_CT)),',','') + ' ' + REPLACE(LTRIM(RTRIM(ADDR.DC_DOM_ST)),',','') + '  ' + REPLACE(LTRIM(RTRIM(ADDR.DF_ZIP_CDE)),',','')
			END AS CityStateZip,
			REPLACE(LTRIM(RTRIM(ADDR.DM_FGN_ST)),',','')  AS ForeignState,
			REPLACE(LTRIM(RTRIM(ADDR.DM_FGN_CNY)),',','') AS Country,
			RF10.BF_RFR AS AccountNumber,
			REPLACE(LTRIM(RTRIM(ADDR.DM_CT)),',','')  AS City,
			REPLACE(LTRIM(RTRIM(ADDR.DC_DOM_ST)),',','')  AS [State],
			CASE WHEN LEN(ADDR.DF_ZIP_CDE) = 9 
				THEN LEFT(LTRIM(RTRIM(ADDR.DF_ZIP_CDE)), 5) + '-' + RIGHT(LTRIM(RTRIM(ADDR.DF_ZIP_CDE)), 4)
				ELSE LTRIM(RTRIM(ADDR.DF_ZIP_CDE))
			END AS Zip,
			CASE WHEN DI_VLD_ADR = 'Y' 
				THEN 1
				ELSE 0
			END AS HasValidAddress
	FROM
		LT20_LTR_REQ_PRC LT20
		INNER JOIN AY10_BR_LON_ATY AY10
			ON LT20.RF_SBJ_PRC = AY10.BF_SSN
			AND LT20.RN_ATY_SEQ_PRC = AY10.LN_ATY_SEQ
		INNER JOIN RF10_RFR RF10
			ON RF10.BF_RFR = AY10.LF_ATY_RCP
			AND RF10.BC_STA_REFR10 = 'A'
		INNER JOIN PD30_PRS_ADR ADDR 
			ON ADDR.DF_PRS_ID = RF10.BF_RFR
			AND ADDR.DC_ADR = 'L'
		INNER JOIN PD10_PRS_NME PD10
			ON PD10.DF_PRS_ID = ADDR.DF_PRS_ID
	WHERE
		RF10.BF_RFR = @AccountNumber
		AND
		(
			(
				LT20.PrintedAt IS NULL 
				AND LT20.OnEcorr = 0
			) 
			OR LT20.EcorrDocumentCreatedAt IS NULL
		)
		AND LT20.InactivatedAt IS NULL
		AND LT20.RI_LTR_REQ_DEL_PRC = 'N'
		AND DI_VLD_ADR = 'Y'
GO