CREATE TABLE [dbo].[AD20_FinActAdjustment]
(
	[DF_SPE_ACC_ID] VARCHAR(10) NOT NULL , 
    [LD_FAT_ADJ_REQ] VARCHAR(10) NOT NULL, 
    [LN_SEQ_FAT_ADJ_REQ] INT NOT NULL, 
    [LC_TYP_FAT_ADJ_REQ] VARCHAR(2) NULL DEFAULT (' '), 
    [LC_STA_FAT_ADJ_REQ] VARCHAR NULL DEFAULT (' '), 
    PRIMARY KEY ([DF_SPE_ACC_ID], [LN_SEQ_FAT_ADJ_REQ], [LD_FAT_ADJ_REQ])
)
