CREATE TABLE [dbo].[DF10_DefermentLetter]
(
	[DF_SPE_ACC_ID] VARCHAR(10) NOT NULL , 
    [LN_SEQ] INT NOT NULL, 
    [LF_DFR_CTL_NUM] VARCHAR(3) NOT NULL, 
	[LN_DFR_OCC_SEQ] INT NOT NULL, 
    [LC_DFR_TYP] VARCHAR(2) NULL, 
    [LD_DFR_INF_CER] DATETIME NULL, 
    [LD_CRT_REQ_DFR] DATETIME NULL, 
    [LC_DFR_STA] VARCHAR NULL, 
    [LC_STA_DFR10] VARCHAR NULL, 
    [LD_STA_DFR10] DATETIME NULL, 
    [LF_LST_DTS_DF10] DATETIME NULL, 
    [LD_DFR_BEG] DATETIME NULL, 
    [LD_DFR_END] DATETIME NULL, 
    [LC_STA_LON50] VARCHAR NULL, 
    [LC_LON_LEV_DFR_CAP] VARCHAR NULL, 
    [LF_LST_DTS_LN50] DATETIME NULL, 
    [LD_STA_LON50] DATETIME NULL, 
    [LD_DFR_APL] DATETIME NULL, 
    PRIMARY KEY ([DF_SPE_ACC_ID], [LN_DFR_OCC_SEQ], [LN_SEQ], [LF_DFR_CTL_NUM])
)
