CREATE PROCEDURE [payhistlpp].[GetLoans]
	@BF_SSN VARCHAR(9),
	@Lender VARCHAR(6),
	@IsTilp BIT
AS
	SELECT DISTINCT
		LN10.IC_LON_PGM AS [LoanProgram],
		LN10.LD_LON_1_DSB AS [DisbursementDate],
		CASE
			WHEN @IsTilp = 0 THEN RTRIM(COALESCE(LN10.LF_LON_ALT + RIGHT('00' + CAST(LN10.LN_LON_ALT_SEQ AS VARCHAR(2)),2), LN10.LF_GTR_RFR_XTN))
			ELSE CONCAT(PD10.DF_SPE_ACC_ID, FORMAT(LN10.LD_LON_1_DSB, 'yyyyMMdd'))
		END AS [LoanId],
		'PAYH' AS [DocType],
		CASE
			WHEN LN10.IC_LON_PGM IN ('STFFRD','UNSTFD') THEN 'STAF'
			WHEN LN10.IC_LON_PGM = 'PLUSGB' THEN 'GRAD'
			WHEN LN10.IC_LON_PGM IN ('SUBCNS','UNCNS') THEN 'CONS'
			WHEN LN10.IC_LON_PGM IN ('SUBSPC','UNSPC') THEN 'SCON'
			WHEN LN10.IC_LON_PGM = 'CNSLDN' AND LN20.BF_SSN IS NOT NULL THEN 'SCON'
			WHEN LN10.IC_LON_PGM = 'CNSLDN' AND LN20.BF_SSN IS NULL THEN 'CONS'
			ELSE LN10.IC_LON_PGM
		END AS [LoanProgramType],
		COALESCE(LN10.LD_LON_GTR,'') AS [GuarantyDate],
		'DEALS' AS [DealId], --TBD
		CASE
			WHEN @IsTilp = 1 THEN LN10.LN_SEQ
			ELSE NULL
		END AS [LN_SEQ]
	FROM
		UDW..LN10_LON LN10
		INNER JOIN UDW..LN90_FIN_ATY LN90
			ON LN90.BF_SSN = LN10.BF_SSN
			AND LN90.LN_SEQ = LN10.LN_SEQ
		INNER JOIN UDW..PD10_PRS_NME PD10
			ON PD10.DF_PRS_ID = LN10.BF_SSN
		LEFT JOIN UDW..LN20_EDS LN20
			ON LN20.BF_SSN = LN10.BF_SSN
			AND LN20.LN_SEQ = LN10.LN_SEQ
			AND LN20.LC_STA_LON20 = 'A'
	WHERE
		LEFT(LN10.LF_LON_CUR_OWN, 6) = @Lender
		AND LN10.LA_CUR_PRI > 0.00
		AND LN10.LC_STA_LON10 = 'R'
		AND LN90.LC_STA_LON90 = 'A'
		AND ISNULL(LN90.LC_FAT_REV_REA,'') = ''
		AND LN90.LA_FAT_CUR_PRI > 0.00
		AND LN10.BF_SSN = @BF_SSN
		AND
			CASE
				WHEN @IsTilp = 0 THEN RTRIM(COALESCE(LN10.LF_LON_ALT + RIGHT('00' + CAST(LN10.LN_LON_ALT_SEQ AS VARCHAR(2)),2), LN10.LF_GTR_RFR_XTN))
				ELSE CONCAT(PD10.DF_SPE_ACC_ID, FORMAT(LN10.LD_LON_1_DSB, 'yyyyMMdd'))
			END != ''
		