
LIBNAME  WORKLOCL  REMOTE  SERVER=LEGEND  SLIBREF=WORK;
RSUBMIT;

PROC SQL;
CONNECT TO DB2 (DATABASE=DNFPUTDL);
CREATE TABLE DEMO AS
SELECT *
FROM CONNECTION TO DB2 (

SELECT A.RM_LTR_DSC AS LETTER_ID
	,B.PF_REQ_ACT AS ARC
	,A.RX_LTR_DSC_CMT AS DESCRIPTION
FROM pkub.LT40_LTR_DSC A
LEFT OUTER JOIN pkub.AC11_ACT_REQ_LTR B	
	ON A.RM_LTR_DSC = B.PF_LTR
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
ENDRSUBMIT;

DATA DEMO; SET WORKLOCL.DEMO; RUN;


PROC SORT DATA=DEMO;
BY LETTER_ID;
RUN;

DATA _NULL_;
SET demo;

FILE "T:\SAS\Letters_in_Letter_Writer - Federal.csv"  DELIMITER=',' DSD DROPOVER LRECL=32767;
FORMAT LETTER_VALIDITY_END_DATE MMDDYY10. ;
IF _N_ = 1 THEN DO;
	PUT "LETTER ID,ARC,LETTER DESCRIPTION,LETTER VALIDITY END DATE";
END;
DO;
   PUT LETTER_ID  @;
   PUT ARC @;
   PUT DESCRIPTION @ ;
   PUT LETTER_VALIDITY_END_DATE $;
END;
RUN;
