%LET BANA = %STR(REQUIRED="FILEDSN=X:\PADR\ODBC\EA27_BANA.dsn; update_lock_typ=nolock; bl_keepnulls=no");
LIBNAME BANA ODBC &BANA ;

PROC SQL;
	CREATE TABLE POP AS 
		SELECT DISTINCT
			BORROWERSSN
		FROM
			BANA.COMPASSLOANMAPPING
		WHERE
			LN_SEQ IS NULL
;
QUIT;

LIBNAME  DUSTER  REMOTE  SERVER=DUSTER  SLIBREF=WORK;

DATA DUSTER.SOURCE; *Send data to Duster;
SET POP;
RUN;

RSUBMIT;  

/*%let DB = DLGSWQUT;  *This is test;*/
%let DB = DLGSUTWH;  *This is live;

LIBNAME OLWHRM1 DB2 DATABASE=&DB OWNER=OLWHRM1;
PROC SQL;
	CREATE TABLE RESULT AS
		SELECT DISTINCT
			LN10.BF_SSN, 
			LN10.LN_SEQ, 
			LN10.PF_MAJ_BCH, 
			LN10.PF_MNR_BCH
		FROM
			OLWHRM1.LN10_LON LN10
			INNER JOIN SOURCE S
				ON S.BORROWERSSN = LN10.BF_SSN
;
QUIT;

ENDRSUBMIT;

DATA RESULT;
SET DUSTER.RESULT;
RUN;

PROC SQL;
	CREATE TABLE FINAL AS
		SELECT DISTINCT
			R.*
		FROM
			RESULT R
			LEFT JOIN BANA.COMPASSLOANMAPPING CLM
				ON CLM.BORROWERSSN = R.BF_SSN
				AND R.LN_SEQ = CLM.LN_SEQ
			INNER JOIN BANA.COMPASSLOANMAPPING CLM1
				ON CLM1.BORROWERSSN = R.BF_SSN
		WHERE
			CLM.LN_SEQ IS NULL
;
QUIT;

PROC EXPORT DATA = WORK.FINAL 
            OUTFILE = "T:\LOAN SPLIT WITH BATCHES.xlsx" 
            DBMS = EXCEL
			REPLACE;
     SHEET="Sheet1"; 
RUN;
