CREATE PROCEDURE [verforbuh].[GetDaysPastDue]
	@AccountNumber CHAR(10)
AS
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SELECT
		ISNULL(CAST(MAX(LN16.LN_DLQ_MAX) AS INT) + 1, 0)
	FROM
		PD10_PRS_NME PD10 
		INNER JOIN LN16_LON_DLQ_HST LN16 ON LN16.BF_SSN = PD10.DF_PRS_ID
		INNER JOIN LN10_Lon LN10 ON LN10.BF_SSN = PD10.DF_PRS_ID AND LN10.LN_SEQ = LN16.LN_SEQ
	WHERE
		PD10.DF_SPE_ACC_ID = @AccountNumber
		AND 
		LN16.LC_STA_LON16 = '1'
		AND
		LN10.LA_CUR_PRI > 0
		AND
		LN10.IC_LON_PGM <> 'TILP' 

RETURN 0
