/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/UNWDW1.NWDW1R2.&sysdate";
FILENAME REPORTZ "&RPTLIB/UNWDW1.NWDW1RZ";
FILENAME REPORT3 "&RPTLIB/UNWDW1.NWDW1R3.&sysdate";
FILENAME REPORT4 "&RPTLIB/UNWDW1.NWDW1R4.&sysdate";
FILENAME REPORT5 "&RPTLIB/UNWDW1.NWDW1R5.&sysdate";
FILENAME REPORT6 "&RPTLIB/UNWDW1.NWDW1R6.&sysdate";
FILENAME REPORT7 "&RPTLIB/UNWDW1.NWDW1R7.&sysdate";
FILENAME REPORT8 "&RPTLIB/UNWDW1.NWDW1R8.&sysdate";
FILENAME REPORT9 "&RPTLIB/UNWDW1.NWDW1R9.&sysdate";
FILENAME REPORT10 "&RPTLIB/UNWDW1.NWDW1R10.&sysdate";
FILENAME REPORT11 "&RPTLIB/UNWDW1.NWDW1R11.&sysdate";
FILENAME REPORT12 "&RPTLIB/UNWDW1.NWDW1R12.&sysdate";
FILENAME REPORT13 "&RPTLIB/UNWDW1.NWDW1R13.&sysdate";
FILENAME REPORT14 "&RPTLIB/UNWDW1.NWDW1R14.&sysdate";
FILENAME REPORT15 "&RPTLIB/UNWDW1.NWDW1R15.&sysdate";
FILENAME REPORT16 "&RPTLIB/UNWDW1.NWDW1R16.&sysdate";
FILENAME REPORT17 "&RPTLIB/UNWDW1.NWDW1R17.&sysdate";
FILENAME REPORT18 "&RPTLIB/UNWDW1.NWDW1R18.&sysdate";
FILENAME REPORT19 "&RPTLIB/UNWDW1.NWDW1R19.&sysdate";
FILENAME REPORT20 "&RPTLIB/UNWDW1.NWDW1R20.&sysdate";
FILENAME REPORT21 "&RPTLIB/UNWDW1.NWDW1R21.&sysdate";
FILENAME REPORT22 "&RPTLIB/UNWDW1.NWDW1R22.&sysdate";
FILENAME REPORT23 "&RPTLIB/UNWDW1.NWDW1R23.&sysdate";
FILENAME REPORT24 "&RPTLIB/UNWDW1.NWDW1R24.&sysdate";
FILENAME REPORT25 "&RPTLIB/UNWDW1.NWDW1R25.&sysdate";
FILENAME REPORT26 "&RPTLIB/UNWDW1.NWDW1R26.&sysdate";
FILENAME REPORT27 "&RPTLIB/UNWDW1.NWDW1R27.&sysdate";
FILENAME REPORT28 "&RPTLIB/UNWDW1.NWDW1R28.&sysdate";
FILENAME REPORT29 "&RPTLIB/UNWDW1.NWDW1R29.&sysdate";
FILENAME REPORT30 "&RPTLIB/UNWDW1.NWDW1R30.&sysdate";
FILENAME REPORT31 "&RPTLIB/UNWDW1.NWDW1R31.&sysdate";
FILENAME REPORT32 "&RPTLIB/UNWDW1.NWDW1R32.&sysdate";
FILENAME REPORT33 "&RPTLIB/UNWDW1.NWDW1R33.&sysdate";
FILENAME REPORT34 "&RPTLIB/UNWDW1.NWDW1R34.&sysdate";
FILENAME REPORT35 "&RPTLIB/UNWDW1.NWDW1R35.&sysdate";
FILENAME REPORT36 "&RPTLIB/UNWDW1.NWDW1R36.&sysdate";
FILENAME REPORT37 "&RPTLIB/UNWDW1.NWDW1R37.&sysdate";
FILENAME REPORT38 "&RPTLIB/UNWDW1.NWDW1R38.&sysdate";
FILENAME REPORT39 "&RPTLIB/UNWDW1.NWDW1R39.&sysdate";
FILENAME REPORT40 "&RPTLIB/UNWDW1.NWDW1R40.&sysdate";
FILENAME REPORT41 "&RPTLIB/UNWDW1.NWDW1R41.&sysdate";
FILENAME REPORT42 "&RPTLIB/UNWDW1.NWDW1R42.&sysdate";
FILENAME REPORT43 "&RPTLIB/UNWDW1.NWDW1R43.&sysdate";
FILENAME REPORT44 "&RPTLIB/UNWDW1.NWDW1R44.&sysdate";
FILENAME REPORT45 "&RPTLIB/UNWDW1.NWDW1R45.&sysdate";
FILENAME REPORT46 "&RPTLIB/UNWDW1.NWDW1R46.&sysdate";
FILENAME REPORT47 "&RPTLIB/UNWDW1.NWDW1R47.&sysdate";
FILENAME REPORT48 "&RPTLIB/UNWDW1.NWDW1R48.&sysdate";
FILENAME REPORT49 "&RPTLIB/UNWDW1.NWDW1R49.&sysdate";
FILENAME REPORT50 "&RPTLIB/UNWDW1.NWDW1R50.&sysdate";
FILENAME REPORT51 "&RPTLIB/UNWDW1.NWDW1R51.&sysdate";

LIBNAME  LEGEND  REMOTE  SERVER=LEGEND SLIBREF=WORK;
RSUBMIT; 
%LET DB = DNFPRQUT;  *This is test;
/*%LET DB = DNFPUTDL;  *This is live;*/

LIBNAME PKUB DB2 DATABASE=&DB OWNER=PKUB; 
LIBNAME PKUS DB2 DATABASE=&DB OWNER=PKUS; 
LIBNAME SAS_TAB V8 '/sas/whse/progrevw';

/*get last run date*/
DATA _NULL_; 
	SET SAS_TAB.LASTRUN_JOBS;

	/*If the job must be run manually set this macro to the last day it successfully ran(last business day).*/
	LAST_RUN = TODAY() - 10;	*COMMENT FOR PROD, IT WILL READ THE DATE FROM A TABLE;

/*	IF JOB = 'UTNWDW1' THEN DO;*/
		CALL SYMPUT('LAST_RUN',"'"||TRIM(LEFT(PUT(LAST_RUN,DATE10.)))|| "'D");
		CALL SYMPUT('LAST_RUNPASS',"'"|| PUT(LAST_RUN,MMDDYY10.) || "'");
/*	END;*/
RUN;
%PUT &LAST_RUN; 

/*THE TABLES ARE GOING TO HAVE THE ACCOUNT NUMBER RATHER THAN SSN AS A PRIMARY KEY*/
/*THE ACCOUNT NUMBER IS BEING TAKEN FROM THE PD10 TABLE WHILE SSN IS DROPPED*/
%MACRO SSN2ACC(TBL,ADKEY);
	PROC SORT DATA=&TBL; BY BF_SSN &ADKEY; RUN;

	DATA &TBL(DROP=BF_SSN);
		MERGE SSN2ACC(IN=B) &TBL(IN=A);
		BY BF_SSN;
		IF A AND B;
	RUN;

	PROC SORT DATA=&TBL; BY DF_SPE_ACC_ID &ADKEY; RUN;
%MEND;

/*******************************************
* BORROWER DATA
********************************************/
PROC SQL;
	CREATE TABLE SSN2ACC AS
		SELECT DISTINCT 
			PD10.DF_SPE_ACC_ID AS DF_SPE_ACC_ID,
			PD10.DF_PRS_ID AS BF_SSN
		FROM 
			PKUB.PD10_PRS_NME PD10
			LEFT JOIN PKUB.LN10_LON LN10
				ON PD10.DF_PRS_ID = LN10.BF_SSN
		WHERE 
			COALESCE(LN10.LC_STA_LON10,'') NOT IN ('P','J')
			AND PD10.DF_SPE_ACC_ID ^= ''
	;
QUIT;
PROC SORT DATA=SSN2ACC; BY BF_SSN; RUN;

/*******************************************
* ENDORSER DATA
********************************************/

DATA LN20(DROP=LF_LST_DTS_LN20);
	SET PKUB.LN20_EDS(KEEP=BF_SSN LC_STA_LON20 LC_EDS_TYP LF_LST_DTS_LN20 LN_SEQ);
	IF DATEPART(LF_LST_DTS_LN20) >= &LAST_RUN ;
RUN; 
%SSN2ACC(LN20,LN_SEQ);

/*******************************************
* REFERENCE DATA
********************************************/
PROC SQL;
CONNECT TO DB2 (DATABASE=&DB);
	CREATE TABLE BR03 AS
		SELECT *
		FROM CONNECTION TO DB2 (
			SELECT A.BF_SSN
				,A.BF_RFR
				,A.BC_STA_REFR10
				,A.BI_ATH_3_PTY
				,A.BC_RFR_REL_BR
				,B.DM_PRS_1
				,B.DM_PRS_LST
				,CASE 
					WHEN C.PF_RSP_ACT IN ('CNTCT') THEN 'CNC'
					WHEN C.PF_RSP_ACT IN ('NOCTC','INVPH') THEN 'ATT'
					ELSE ''
				END AS CONTACT
				,C.LD_ATY_RSP
			FROM PKUB.RF10_RFR A
				INNER JOIN PKUB.PD10_PRS_NME B
					ON A.BF_RFR = B.DF_PRS_ID
				LEFT OUTER JOIN PKUB.AY10_BR_LON_ATY C
					ON C.LF_ATY_RCP = A.BF_RFR
					AND C.LC_STA_ACTY10 = 'A'
					AND C.PF_RSP_ACT IN ('CNTCT','NOCTC','INVPH')
		WHERE BF_LST_DTS_RF10 >= &LAST_RUNPASS 
			OR LF_LST_DTS_AY10 >= &LAST_RUNPASS
			
	FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
QUIT;
PROC SORT DATA=BR03; BY BF_SSN BF_RFR CONTACT LD_ATY_RSP; RUN;
DATA BR03(DROP=CONTACT);
	SET BR03;
	BY BF_SSN BF_RFR CONTACT LD_ATY_RSP;
	IF FIRST.CONTACT THEN DO;
		LST_ATT = .;
		LST_CNC = .;
	END;;
	RETAIN LST_CNC LST_ATT;
	IF CONTACT = 'CNC' THEN LST_CNC = MAX(LD_ATY_RSP,LST_CNC);
	ELSE IF CONTACT = 'ATT' THEN LST_ATT = MAX(LD_ATY_RSP,LST_ATT);
	IF LAST.BF_RFR THEN do;
		LST_ATT = MAX(LST_ATT,LST_CNC);
		OUTPUT;
	end;
RUN;

%SSN2ACC(BR03,BF_RFR);

/*******************************************
* TRANSACTION DATA
********************************************/
DATA LN90(DROP=LF_LST_DTS_LN90 ) ;
	SET PKUB.LN90_FIN_ATY(KEEP=BF_SSN LN_SEQ LN_FAT_SEQ LD_FAT_PST
		LD_FAT_EFF LC_STA_LON90 LA_FAT_CUR_PRI LA_FAT_NSI LA_FAT_LTE_FEE 
		LF_LST_DTS_LN90 PC_FAT_TYP PC_FAT_SUB_TYP LC_FAT_REV_REA );
	WHERE LC_FAT_REV_REA ^= '0'
		AND DATEPART(LF_LST_DTS_LN90) >= &LAST_RUN
;
	LA_FAT_CUR_PRI = COALESCE(LA_FAT_CUR_PRI,0);
	LA_FAT_NSI = COALESCE(LA_FAT_NSI,0);
	LA_FAT_LTE_FEE = COALESCE(LA_FAT_LTE_FEE,0);
	IF  PC_FAT_TYP IN ('05','10','14','15','17','26','50','51','55','60');
RUN;
%SSN2ACC(LN90,LN_SEQ LN_FAT_SEQ);

/*******************************************
* BILLING DATA
********************************************/
PROC SQL;
CONNECT TO DB2 (DATABASE=&DB);
	CREATE TABLE LN80 AS
	SELECT *
	FROM CONNECTION TO DB2 (
		SELECT B.BF_SSN
			,B.LN_SEQ
			,B.LD_BIL_CRT
			,B.LN_SEQ_BIL_WI_DTE
			,B.LN_BIL_OCC_SEQ
			,B.LD_BIL_DU_LON
			,B.LC_STA_LON80
			,COALESCE(b.la_bil_cur_du,0) AS LA_BIL_CUR_DU
			,COALESCE(b.la_bil_pas_du,0) AS la_bil_pas_du
			,COALESCE(b.la_tot_bil_sts,0) AS la_tot_bil_sts
			,LC_BIL_MTD
			,LC_IND_BIL_SNT
			,LC_STA_BIL10
			,E.LN_FAT_SEQ
			,E.LD_FAT_EFF
			,b.LC_LON_STA_BIL
			,C.LA_INT_PD_LST_STM
			,C.LA_FEE_PD_LST_STM
			,C.LA_PRI_PD_LST_STM
			,C.LA_INT_PD_LST_STM + C.LA_FEE_PD_LST_STM + C.LA_PRI_PD_LST_STM AS LA_TTL_PD_LST_STM
			,B.LA_LTE_FEE_OTS_PRT
		FROM pkub.BL10_BR_BIL C
			INNER JOIN pkub.LN80_LON_BIL_CRF B
				ON B.BF_SSN = C.BF_SSN
				AND B.LD_BIL_CRT = C.LD_BIL_CRT
				AND B.LN_SEQ_BIL_WI_DTE = C.LN_SEQ_BIL_WI_DTE
			LEFT OUTER JOIN pkub.LN75_BIL_LON_FAT D
				ON D.BF_SSN = B.BF_SSN
				AND D.LN_SEQ = B.LN_SEQ
				AND D.LD_BIL_CRT = B.LD_BIL_CRT
				AND D.LN_SEQ_BIL_WI_DTE = B.LN_SEQ_BIL_WI_DTE
				AND D.LN_BIL_OCC_SEQ = B.LN_BIL_OCC_SEQ
				AND B.LA_BIL_CUR_DU = B.LA_TOT_BIL_STS
			LEFT OUTER JOIN pkub.LN90_FIN_ATY E
				ON D.BF_SSN = E.BF_SSN
				AND D.LN_SEQ = E.LN_SEQ
				AND D.LN_FAT_SEQ = E.LN_FAT_SEQ
		WHERE B.LC_BIL_TYP_LON = 'P' 
			AND B.LD_LST_DTS_LN80 >= &LAST_RUNPASS
	);
	DISCONNECT FROM DB2;
QUIT; 

proc sort data=ln80; by bf_ssn ln_seq LD_BIL_CRT LN_SEQ_BIL_WI_DTE LN_BIL_OCC_SEQ LN_FAT_SEQ; run;

data ln80(drop=LN_BIL_OCC_SEQ LN_FAT_SEQ); 
	set ln80;
	by bf_ssn ln_seq LD_BIL_CRT LN_SEQ_BIL_WI_DTE ;
	if last.ln_seq_bil_wi_dte;
run;

%SSN2ACC(LN80,LN_SEQ LD_BIL_CRT LN_SEQ_BIL_WI_DTE);

/*******************************************
* DEFERMENT DATA
********************************************/
PROC SQL;
CREATE TABLE DF10 AS
	SELECT B.BF_SSN
		,B.LN_SEQ
		,B.LF_DFR_CTL_NUM
		,B.LN_DFR_OCC_SEQ
		,C.LC_DFR_TYP
		,C.LD_DFR_INF_CER
		,B.LD_DFR_BEG
		,B.LD_DFR_END
		,B.LC_LON_LEV_DFR_CAP
		,B.LC_STA_LON50
		,C.LC_DFR_STA
		,C.LC_STA_DFR10
	FROM PKUB.LN50_BR_DFR_APV B
		INNER JOIN PKUB.DF10_BR_DFR_REQ C
			ON B.BF_SSN = C.BF_SSN
			AND B.LF_DFR_CTL_NUM = C.LF_DFR_CTL_NUM
	WHERE (DATEPART(B.LF_LST_DTS_LN50) >= &LAST_RUN 
			OR DATEPART(C.LF_LST_DTS_DF10) >= &LAST_RUN)
;
/*******************************************
* FORBEARANCE DATA
********************************************/
CREATE TABLE FB10 AS
	SELECT B.BF_SSN
		,B.LN_SEQ
		,B.LF_FOR_CTL_NUM
		,B.LN_FOR_OCC_SEQ
		,C.LC_FOR_TYP
		,C.LD_FOR_INF_CER
		,B.LD_FOR_BEG
		,B.LD_FOR_END
		,B.LC_LON_LEV_FOR_CAP 
		,B.LC_STA_LON60
		,C.LC_FOR_STA
		,C.LC_STA_FOR10
		,coalesce(C.LA_REQ_RDC_PAY,0) as LA_REQ_RDC_PAY
		,B.LI_FOR_VRB_DFL_RUL
	FROM PKUB.LN60_BR_FOR_APV B
		INNER JOIN PKUB.FB10_BR_FOR_REQ C
			ON B.BF_SSN = C.BF_SSN
			AND B.LF_FOR_CTL_NUM = C.LF_FOR_CTL_NUM
	WHERE (DATEPART(B.LF_LST_DTS_LN60) >= &LAST_RUN
			OR DATEPART(C.LF_LST_DTS_FB10) >= &LAST_RUN)
;
QUIT;
%SSN2ACC(DF10,LN_SEQ LF_DFR_CTL_NUM LN_DFR_OCC_SEQ);
%SSN2ACC(FB10,LN_SEQ LF_FOR_CTL_NUM LN_FOR_OCC_SEQ);

/*******************************************
* LOAN DATA
********************************************/
DATA LN10(DROP=	LF_LST_DTS_LN10 ) ;
	SET PKUB.LN10_LON (KEEP= BF_SSN LN_SEQ LC_STA_LON10 LA_CUR_PRI LA_LON_AMT_GTR LD_END_GRC_PRD
		IC_LON_PGM LD_LON_1_DSB LF_LST_DTS_LN10 LD_PIF_RPT LC_SST_LON10 LF_LON_CUR_OWN LF_DOE_SCL_ORG);
	WHERE LC_STA_LON10 NOT IN ('P','J')
/*		AND DATEPART(LF_LST_DTS_LN10) >= &LAST_RUN*/

;
RUN;
%SSN2ACC(LN10,LN_SEQ);

/*******************************************
* ACH DATA
********************************************/
DATA LN83(DROP=LF_LST_DTS_LN83 );
	SET PKUB.LN83_EFT_TO_LON(KEEP=BF_SSN LN_SEQ BN_EFT_SEQ LF_LST_DTS_LN83 
		LD_EFT_EFF_END LC_STA_LN83 );
	IF DATEPART(LF_LST_DTS_LN83) >= &LAST_RUN;
RUN;
PROC SORT DATA=LN83; BY BF_SSN LN_SEQ DESCENDING BN_EFT_SEQ; RUN;
DATA LN83;
	SET LN83;
	BY BF_SSN LN_SEQ;
	IF FIRST.LN_SEQ;
RUN;
%SSN2ACC(LN83,LN_SEQ);

/*******************************************
* REHAB DATA 
********************************************/
DATA LN09(DROP= LF_LST_DTS_LN09);
	SET PKUB.LN09_RPD_PIO_CVN (KEEP= BF_SSN LN_SEQ LF_LST_DTS_LN09 LD_LON_RHB_PCV);
	WHERE LD_LON_RHB_PCV ^= .
		and DATEPART(LF_LST_DTS_LN09) >= &LAST_RUN
;
RUN;
%SSN2ACC(LN09,LN_SEQ);

/*********************************************
* DISBURSEMENT
**********************************************/
PROC SQL;
CONNECT TO DB2 (DATABASE=&DB);
CREATE TABLE LN15 AS
	SELECT *
	FROM CONNECTION TO DB2 (
		SELECT BF_SSN
			,LN_BR_DSB_SEQ
			,LA_DSB - COALESCE(LA_DSB_CAN,0) AS LA_DSB
			,LD_DSB
			,LC_DSB_TYP
			,LC_STA_LON15
			,LN_SEQ
			,COALESCE(LA_DL_DSB_REB,0) - COALESCE(LA_DSB_REB_CAN,0) AS LA_DL_REBATE
		FROM pkub.LN15_DSB 
		WHERE LF_LST_DTS_LN15 >= &LAST_RUNPASS
FOR READ ONLY WITH UR
);
QUIT;
%SSN2ACC(LN15,LN_BR_DSB_SEQ);

/*******************************************
* BORROWER BENEFIT ELIGIBILITY
********************************************/
PROC SQL;
CONNECT TO DB2 (DATABASE=&DB);
CREATE TABLE LN55 AS
	SELECT *
	FROM CONNECTION TO DB2 (
		SELECT b.bf_ssn
			,B.LN_SEQ
			,c.PR_EFT_RIR
			,F.PM_BBS_PGM
			,COALESCE(F.LN_BBS_STS_PCV_PAY,0) AS LN_BBS_STS_PCV_PAY
			,E.PN_BBT_DLQ_MOT
			,F.LC_STA_LN54
			,F.LD_BBS_DSQ
			,F.LC_BBS_ELG 
		FROM  pkub.LN10_LON B
			inner join pkub.RP30_EFT_RIR_PAR c
				on b.lf_lon_cur_own = c.if_own
				and b.ic_lon_pgm = c.ic_lon_pgm
			INNER JOIN pkub.LN54_LON_BBS f
				on b.bf_ssn = f.bf_ssn
				and b.ln_seq = f.ln_seq
			inner join pkub.LN55_LON_BBS_TIR D
				ON B.BF_SSN = D.BF_SSN
				AND B.LN_SEQ = D.LN_SEQ
			INNER JOIN PKUB.RP02_BBS_PGM_TIR E
				ON F.PM_BBS_PGM = E.PM_BBS_PGM 
				AND F.PN_BBS_PGM_SEQ = E.PN_BBS_PGM_SEQ
		where c.pc_eft_rir_sta = 'A'
			and e.pc_sta_rp02 = 'A'
			and LF_LST_DTS_LN54 >= &LAST_RUNPASS
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
QUIT;
PROC SORT DATA=LN55; BY BF_SSN LN_SEQ LC_STA_LN54 ; RUN;
DATA LN55(drop=LC_STA_LN54);
	SET LN55;
	BY BF_SSN LN_SEQ LC_STA_LN54 ;
	IF FIRST.LN_SEQ;
RUN;
%SSN2ACC(LN55,LN_SEQ);

/*******************************************
* REPAYMENT SCHEDULE DATA
********************************************/
PROC SQL;
	CREATE TABLE LN65 AS
		SELECT 
			LN65.BF_SSN
			,LN65.LN_SEQ
			,LN66.LN_GRD_RPS_SEQ
			,CASE
				WHEN DW01.WX_OVR_DW_LON_STA = 'LITIGATION' THEN 0
				ELSE LN66.LN_RPS_TRM
			END AS LN_RPS_TRM
			,CASE
				WHEN DW01.WX_OVR_DW_LON_STA = 'LITIGATION' THEN .
				ELSE RS10.LD_RPS_1_PAY_DU
			END AS LD_RPS_1_PAY_DU
			,RS10.LD_SNT_RPD_DIS
			,LN65.LD_CRT_LON65
			,LN65.LC_TYP_SCH_DIS
			,CASE
				WHEN DW01.WX_OVR_DW_LON_STA = 'LITIGATION' THEN 0
				ELSE LN66.LA_RPS_ISL
			END AS LA_RPS_ISL
		FROM
			PKUB.RS10_BR_RPD RS10
			JOIN PKUB.LN65_LON_RPS LN65
				ON RS10.BF_SSN = LN65.BF_SSN
				AND RS10.LN_RPS_SEQ = LN65.LN_RPS_SEQ
			JOIN PKUB.LN66_LON_RPS_SPF LN66
				ON LN65.BF_SSN = LN66.BF_SSN
				AND LN65.LN_SEQ = LN66.LN_SEQ
				AND LN65.LN_RPS_SEQ = LN66.LN_RPS_SEQ
			JOIN PKUB.DW01_DW_CLC_CLU DW01
				ON LN65.BF_SSN = DW01.BF_SSN
				AND LN65.LN_SEQ = DW01.LN_SEQ
		WHERE 
			LN65.LC_STA_LON65 = 'A'
	;
QUIT;

PROC SORT DATA=LN65; BY BF_SSN LN_SEQ LN_GRD_RPS_SEQ; RUN;

DATA LN65(DROP= A B C NEXT_SEQ LD_RPS_1_PAY_DU LN_GRD_RPS_SEQ);
	SET LN65;
	FORMAT NEXT_SEQ DATE9.;
	BY BF_SSN LN_SEQ LN_GRD_RPS_SEQ;
	RETAIN NEXT_SEQ A C B;
	IF FIRST.LN_SEQ THEN DO;
		A = .;
		NEXT_SEQ = INTNX('MONTH',LD_RPS_1_PAY_DU,LN_RPS_TRM,'S');
		IF NEXT_SEQ > TODAY() THEN DO;
			A = LN_GRD_RPS_SEQ ;
			C = LA_RPS_ISL ;
		END;
	END;
	ELSE IF A= . THEN DO;
		NEXT_SEQ = INTNX('MONTH',NEXT_SEQ,LN_RPS_TRM,'S');
		IF NEXT_SEQ > TODAY() THEN DO;
			A = LN_GRD_RPS_SEQ ;
			C = LA_RPS_ISL ;
		END;
	END;
	IF FIRST.LN_SEQ THEN B = LN_RPS_TRM;
	ELSE B = B + LN_RPS_TRM;
	IF LAST.LN_SEQ THEN DO;
		LN_RPS_TRM = B;
		LA_RPS_ISL = C;
		LN_GRD_RPS_SEQ = A;
		DAY_DUE = DAY(LD_RPS_1_PAY_DU);
		OUTPUT;
	END;
RUN;
%SSN2ACC(LN65,LN_SEQ);

/*******************************************
* INTEREST RATE DATA
********************************************/
DATA LN72(DROP=LC_STA_LON72 LF_LST_DTS_LN72);
	SET PKUB.LN72_INT_RTE_HST(KEEP=BF_SSN LN_SEQ LC_STA_LON72 
		LD_ITR_EFF_BEG LD_ITR_EFF_END LF_LST_DTS_LN72 LR_ITR LR_INT_RDC_PGM_ORG
		LC_ITR_TYP LD_ITR_EFF_BEG LD_ITR_EFF_END);
	WHERE LC_STA_LON72 = 'A'
		AND LD_ITR_EFF_BEG <= TODAY() 
		AND LD_ITR_EFF_END >= TODAY() 
		AND DATEPART(LF_LST_DTS_LN72) >= &LAST_RUN;
	LR_ITR = COALESCE(LR_ITR,0);
	LR_INT_RDC_PGM_ORG = COALESCE(LR_INT_RDC_PGM_ORG,LR_ITR);
RUN;
%SSN2ACC(LN72,LN_SEQ);

/*********************************************
* ENROLLMENT - LOAN LEVEL
**********************************************/
PROC SQL;
CREATE TABLE SD10 AS
	SELECT A.BF_SSN
		,A.LN_SEQ
		,B.LN_STU_SPR_SEQ
		,B.LD_SCL_SPR
		,D.IM_SCL_FUL
	FROM PKUB.SD10_STU_SPR B
		INNER JOIN PKUB.SC10_SCH_DMO D
			ON B.LF_DOE_SCL_ENR_CUR = D.IF_DOE_SCL
		INNER JOIN PKUB.LN13_LON_STU_OSD C
			ON B.LF_STU_SSN = C.LF_STU_SSN
			AND B.LN_STU_SPR_SEQ = C.LN_STU_SPR_SEQ
		INNER JOIN PKUB.LN10_LON A
			ON C.BF_SSN = A.BF_SSN
			AND C.LN_SEQ = A.LN_SEQ
	WHERE B.LC_STA_STU10 = 'A'
		AND C.LC_STA_LON13 = 'A'
		AND (DATEPART(B.LF_LST_DTS_SD10) >= &LAST_RUN
			OR DATEPART(C.LF_CRT_DTS_LN13) >= &LAST_RUN)
;
QUIT;
PROC SORT DATA=SD10; BY BF_SSN LN_SEQ LN_STU_SPR_SEQ;RUN;
DATA SD10(DROP=LN_STU_SPR_SEQ);
	SET SD10;
		BY BF_SSN LN_SEQ LN_STU_SPR_SEQ;
	IF LAST.LN_SEQ;
RUN;
%SSN2ACC(SD10,LN_SEQ);

/*********************************************
* DELINQUENCY DATA
**********************************************/
DATA LN16(DROP=LF_LST_DTS_LN16 LC_STA_LON16);
	SET PKUB.LN16_LON_DLQ_HST(KEEP=BF_SSN LN_SEQ LN_DLQ_SEQ LD_DLQ_OCC
		LF_LST_DTS_LN16 LC_STA_LON16 LN_DLQ_MAX LD_DLQ_MAX);
	IF DATEPART(LF_LST_DTS_LN16) >= &LAST_RUN;
	IF LC_STA_LON16 ^= '1' OR (LC_STA_LON16 = '1' AND LD_DLQ_MAX ^= TODAY() - 1) THEN DO;
		LN_DLQ_MAX = 0;
		LD_DLQ_OCC = .;
	END;
RUN;
PROC SORT DATA=LN16; BY BF_SSN LN_SEQ DESCENDING LN_DLQ_SEQ; RUN;
DATA LN16 ;
	SET LN16(DROP=LN_DLQ_SEQ);
	BY BF_SSN LN_SEQ;
	IF FIRST.LN_SEQ;
RUN;
%SSN2ACC(LN16,LN_SEQ);

/*********************************************
* AUTOPAY DATA
**********************************************/
DATA BR30(DROP=BF_LST_DTS_BR30 );
	SET PKUB.BR30_BR_EFT(KEEP=BF_SSN BN_EFT_SEQ BF_EFT_ABA BF_EFT_ACC BC_EFT_STA
		BD_EFT_STA BA_EFT_ADD_WDR BN_EFT_NSF_CTR BC_EFT_DNL_REA BF_LST_DTS_BR30);
	IF DATEPART(BF_LST_DTS_BR30) >= &LAST_RUN ;
	BA_EFT_ADD_WDR = COALESCE(BA_EFT_ADD_WDR,0);
RUN;
PROC SORT DATA=BR30; BY BF_SSN BC_EFT_STA DESCENDING BN_EFT_SEQ; RUN;
DATA BR30; 
	SET BR30; 
	BY BF_SSN BC_EFT_STA DESCENDING BN_EFT_SEQ;
	IF FIRST.BF_SSN OR BC_EFT_STA = 'A';
RUN;
PROC SORT DATA=BR30; BY BF_SSN BN_EFT_SEQ; RUN;
DATA BR30(DROP=B);
	SET BR30;
	BY BF_SSN;
	RETAIN B;
	IF FIRST.BF_SSN AND LAST.BF_SSN THEN OUTPUT;
	ELSE IF FIRST.BF_SSN AND LAST.BF_SSN = 0 AND BC_EFT_STA = 'A' THEN B = BA_EFT_ADD_WDR;
	ELSE IF FIRST.BF_SSN = 0 AND BC_EFT_STA = 'A' THEN B = B + BA_EFT_ADD_WDR;
	IF FIRST.BF_SSN = 0 AND LAST.BF_SSN THEN DO;
		BA_EFT_ADD_WDR = B;
		OUTPUT; 
	END;
RUN;
%SSN2ACC(BR30,);

/*********************************************
* DEMOGRAPHICS
**********************************************/
PROC SQL;
CREATE TABLE PD10 AS
	SELECT distinct A.DF_SPE_ACC_ID
		,a.df_prs_id as bf_ssn
		,A.DM_PRS_1
		,A.DM_PRS_LST
		,A.DM_PRS_MID
		,A.DD_BRT
	FROM PKUB.PD10_PRS_NME A
	WHERE substr(df_prs_id,1,1) ^= 'P'
	and DATEPART(A.DF_LST_DTS_PD10) >= &LAST_RUN
;

CREATE TABLE PD30 AS
	SELECT distinct c.df_prs_id as bf_ssn
		,C.DX_STR_ADR_1
		,C.DX_STR_ADR_2
		,C.DM_CT
		,C.DC_DOM_ST
		,C.DF_ZIP_CDE
		,C.DM_FGN_ST
		,C.DM_FGN_CNY
		,C.DD_VER_ADR
		,C.DI_VLD_ADR
	FROM PKUB.PD30_PRS_ADR C
	WHERE C.DC_ADR = 'L'
		AND DATEPART(C.DF_LST_DTS_PD30) >= &LAST_RUN
;

CREATE TABLE PD42 AS
	SELECT DISTINCT d.df_prs_id as bf_ssn
		,D.DC_PHN
		,D.DC_ALW_ADL_PHN
		,D.DD_PHN_VER
		,D.DI_PHN_VLD
		,D.DN_DOM_PHN_ARA
		,D.DN_DOM_PHN_XCH
		,D.DN_DOM_PHN_LCL
		,D.DN_PHN_XTN
		,D.DN_FGN_PHN_CNY
		,D.DN_FGN_PHN_CT
		,D.DN_FGN_PHN_LCL
	FROM  PKUB.PD40_PRS_PHN D
	WHERE DATEPART(D.DF_LST_DTS_PD40) >= &LAST_RUN 
;

CREATE TABLE PD32 AS
	SELECT DISTINCT g.df_prs_id as bf_ssn
		,G.DC_ADR_EML
		,G.DX_ADR_EML 
		,G.DD_VER_ADR_EML
		,G.DI_VLD_ADR_EML
		,G.DC_STA_PD32
	FROM PKUB.PD32_PRS_ADR_EML G
	WHERE 
		DATEPART(G.DF_LST_DTS_PD32) >= &LAST_RUN
		AND G.DC_STA_PD32 = 'A'
;
QUIT;
proc sort data=pd32; by bf_ssn dc_adr_eml DC_STA_PD32 ; run;
	data pd32(DROP=DC_STA_PD32);
	set pd32;
	by bf_ssn dc_adr_eml;
	if first.dc_adr_eml;
run;

%SSN2ACC(PD30,);
%SSN2ACC(PD42,DC_PHN);
%SSN2ACC(PD32,DC_ADR_EML);

/*********************************************
* SUSPENSE PAYMENTS
**********************************************/
PROC SQL;
CREATE TABLE RM31 AS
	SELECT DISTINCT A.BF_SSN
		,SUM(A.LA_BR_RMT_PST) AS LA_BR_RMT_PST
	FROM PKUB.RM31_BR_RMT_PST A
	WHERE LC_RMT_STA_PST = 'S'
	GROUP BY BF_SSN;
QUIT;
%SSN2ACC(RM31,);

/*********************************************
* AMOUNTS DUE INFORMATION
**********************************************/
PROC SQL ;
CREATE TABLE CUR_DUE AS
	SELECT A.BF_SSN
		,B.LD_BIL_CRT
		,B.LN_SEQ_BIL_WI_DTE
		,B.LD_BIL_DU_LON
		,SUM(COALESCE(B.LA_BIL_CUR_DU,0) - COALESCE(B.LA_TOT_BIL_STS,0)) AS Cur_Due
		,A.LA_LTE_FEE_OTS
	from (SELECT BF_SSN
				,LN_SEQ
				,LA_CUR_PRI
				,LC_STA_LON10
				,SUM(COALESCE(LA_LTE_FEE_OTS,0)) AS LA_LTE_FEE_OTS
			FROM PKUB.LN10_LON 
			GROUP BY BF_SSN) A
		LEFT OUTER JOIN PKUB.LN80_LON_BIL_CRF b
			ON A.BF_SSN = B.BF_SSN
			AND A.LN_SEQ = B.LN_SEQ
			AND b.lc_sta_lon80 = 'A'
			AND B.LC_LON_STA_BIL = '1'
			AND A.LC_STA_LON10 = 'R'
			AND A.LA_CUR_PRI > 0
	GROUP BY A.BF_SSN
		,B.LD_BIL_CRT
		,B.LN_SEQ_BIL_WI_DTE
		,B.LD_BIL_DU_LON
;
QUIT;
PROC SORT DATA=CUR_DUE; BY BF_SSN LD_BIL_CRT LN_SEQ_BIL_WI_DTE; RUN;
DATA CUR_DUE(keep=bf_ssn cur_due past_due tot_due tot_due_fee); 
	SET CUR_DUE;
	BY BF_SSN ;
	RETAIN PAST_DUE a 0 ;
	IF FIRST.BF_SSN THEN do;
		PAST_DUE = 0;
		a = 0;
	end;
	IF LD_BIL_DU_LON < TODAY() THEN PAST_DUE = PAST_DUE + CUR_DUE;
	else do;
		if ld_bil_du_lon > intnx('month',today(),+1,'s') then cur_due = 0;
		a = a + cur_due;
	end;

	IF LAST.BF_SSN THEN DO;
		cur_due = a;
		if intnx('month',today(),-1,'s') >= ld_bil_du_lon then do;
			cur_due = 0;
			past_due = 0;
			LA_LTE_FEE_OTS = 0;
		end;
		if intnx('month',ld_bil_du_lon,-1,'s') > ld_bil_crt then do;
			past_due = 0;
			LA_LTE_FEE_OTS = 0;
		end;
		TOT_DUE = PAST_DUE + CUR_DUE;
		TOT_DUE_FEE = TOT_DUE + LA_LTE_FEE_OTS;

		OUTPUT;
	END;
RUN;
%SSN2ACC(CUR_DUE,);

/*********************************************
* ADDITIONAL LOAN DATA
**********************************************/
DATA DW01;
	SET PKUB.DW01_DW_CLC_CLU(KEEP=BF_SSN LN_SEQ WC_DW_LON_STA WA_TOT_BRI_OTS WD_LON_RPD_SR WX_OVR_DW_LON_STA );
RUN;
%SSN2ACC(DW01,LN_SEQ);

/*********************************************
* CREDIT REPORTING INFORMATION
**********************************************/
PROC SQL;
CREATE TABLE LN56 AS
	SELECT A.BF_SSN 
		,A.LN_SEQ
		,A.LC_RPT_STA_CRB
		,A.LD_RPT_CRB
		,B.LD_STA_LN56 AS DT_ADJ
	FROM pkus.LN56_LON_CRB_RPT A
		LEFT OUTER JOIN pkus.LN56_LON_CRB_RPT B
			ON A.BF_SSN = B.BF_SSN
			AND A.LN_SEQ = B.LN_SEQ
			AND A.LD_RPT_CRB = B.LD_RPT_CRB
			AND SUBSTR(A.LF_LST_USR_LN56,1,2) = 'UT'
			AND B.LC_STA_LN56 = 'I'
	WHERE A.LD_RPT_CRB > INTNX('YEAR',TODAY(),-1,'S')
		AND A.LC_STA_LN56 = 'A'
		AND DATEPART(A.LF_LST_DTS_LN56) >= &LAST_RUN 
;
QUIT;
%SSN2ACC(LN56,LN_SEQ);

/*********************************************
* ACTIVITY HISTORY
**********************************************/
PROC SQL;
CONNECT TO DB2 (DATABASE=&DB);
	CREATE TABLE ARCS AS
	SELECT *
	FROM CONNECTION TO DB2 (
		SELECT AY10.BF_SSN
			,AY10.LN_ATY_SEQ
			,AY10.PF_REQ_ACT
			,AY10.LC_STA_ACTY10
			,LX_ATY
		FROM pkub.AY10_BR_LON_ATY AY10
			LEFT OUTER JOIN pkub.AY15_ATY_CMT AY15
				ON AY10.BF_SSN = AY15.BF_SSN 
				AND AY10.LN_ATY_SEQ = AY15.LN_ATY_SEQ
				AND AY15.LN_ATY_CMT_SEQ = 1
		 	LEFT OUTER JOIN pkub.AY20_ATY_TXT AY20
				ON AY15.BF_SSN = AY20.BF_SSN 
				AND AY15.LN_ATY_SEQ = AY20.LN_ATY_SEQ
				AND AY15.LN_ATY_CMT_SEQ = AY20.LN_ATY_CMT_SEQ
		WHERE AY10.PF_REQ_ACT IN ('DRLFA','K0ADD','K0PHN','M1411')
			AND AY10.LC_STA_ACTY10 = 'A'
			AND (AY10.LF_LST_DTS_AY10 >= &LAST_RUNPASS or AY10.PF_REQ_ACT = 'DRLFA')
FOR READ ONLY WITH UR
);

CREATE TABLE ARC_IND AS
	SELECT *
	FROM CONNECTION TO DB2 (
		SELECT AY10.BF_SSN
			,AY10.LN_ATY_SEQ
			,AY10.PF_REQ_ACT
			,AY10.LC_STA_ACTY10
		FROM pkub.AY10_BR_LON_ATY AY10
		WHERE AY10.PF_REQ_ACT IN ('SPHAN','VIPSS')
			AND AY10.LC_STA_ACTY10 = 'A'
			AND AY10.LF_LST_DTS_AY10 >= &LAST_RUNPASS
FOR READ ONLY WITH UR
);

CREATE TABLE DL200 AS
	SELECT *
	FROM CONNECTION TO DB2 (
		SELECT AY10.BF_SSN
			,LN_ATY_SEQ
			,LD_ATY_REQ_RCV
			,LC_STA_ACTY10
		FROM pkub.AY10_BR_LON_ATY AY10
		WHERE PF_REQ_ACT = 'DL200'
			AND AY10.LF_LST_DTS_AY10 >= &LAST_RUNPASS
);

CREATE TABLE ARCHIST AS
	SELECT *
	FROM CONNECTION TO DB2 (
		SELECT A.BF_SSN
			,A.LN_ATY_SEQ
			,D.LN_ATY_CMT_SEQ
			,A.LC_STA_ACTY10
			,A.PF_REQ_ACT
			,A.PF_RSP_ACT
			,A.LD_ATY_REQ_RCV
			,A.LD_ATY_RSP
			,A.LF_USR_REQ_ATY
			,A.LT_ATY_RSP
			,D.LC_STA_AY15
			,COALESCE(B.LX_ATY, ' ') as LX_ATY_1
			,c.px_act_dsc_req
				,LC_ATY_RCP
			,CASE 	
				WHEN A.LF_ATY_RCP = A.BF_SSN THEN ''
				ELSE A.LF_ATY_RCP
			END AS LF_ATY_RCP
	FROM pkub.AY10_BR_LON_ATY A
		LEFT OUTER JOIN pkub.AY15_ATY_CMT D
			ON A.BF_SSN = D.BF_SSN 
			AND A.LN_ATY_SEQ = D.LN_ATY_SEQ
		LEFT OUTER JOIN pkub.AY20_ATY_TXT B
			ON D.BF_SSN = B.BF_SSN 
			AND D.LN_ATY_SEQ = B.LN_ATY_SEQ
			AND D.LN_ATY_CMT_SEQ = B.LN_ATY_CMT_SEQ
			AND B.LN_ATY_TXT_SEQ = 1
		LEFT OUTER JOIN pkub.AC10_ACT_REQ c
			on a.pf_req_act = c.pf_req_act
	WHERE a.LC_ATY_RCP in ('B','R')
		and a.LF_LST_DTS_AY10 >= &LAST_RUNPASS
);
DISCONNECT FROM DB2;
QUIT;
PROC SORT DATA=ARCHIST; BY BF_SSN LN_ATY_SEQ LN_ATY_CMT_SEQ; RUN;
DATA ARCHIST;
	SET ARCHIST; 
	BY BF_SSN LN_ATY_SEQ;
	LENGTH LX_ATY $5000.;
	RETAIN LX_ATY;

	IF FIRST.LN_ATY_SEQ THEN LX_ATY=' '; 

	IF PF_RSP_ACT = 'CNTCT' THEN
	DO;
		LX_ATY=trim(left(LX_ATY))||trim(left(LX_ATY_1));
		IF LAST.LN_ATY_SEQ;
	END;
	ELSE DO;
		LX_ATY = LX_ATY_1;
		IF FIRST.LN_ATY_SEQ;
	END;
RUN;

DATA DRLFA ARCS(DROP=DOL) ;
	SET ARCS;
	IF PF_REQ_ACT = 'DRLFA' THEN DO;
		IF SUBSTR(LX_ATY,1,1) = '{' and lc_sta_acty10 = 'A' THEN DO;
			DOL = INPUT(SCAN(LX_ATY,1,'{}'),DOLLAR8.2);
			OUTPUT DRLFA;
		END;
	END;
	ELSE OUTPUT ARCS;
RUN;

PROC SORT DATA=DRLFA; BY BF_SSN;RUN;
DATA DRLFA (KEEP=BF_SSN FEE_WAV_DOL FEE_WAV_CT);
	SET DRLFA;
	RETAIN FEE_WAV_DOL FEE_WAV_CT;
	BY BF_SSN;
	IF FIRST.BF_SSN THEN DO;
		FEE_WAV_DOL = DOL;
		FEE_WAV_CT = 1;
	END;
	ELSE DO;
		FEE_WAV_DOL + DOL;
		FEE_WAV_CT + 1;
	END;
	IF LAST.BF_SSN THEN OUTPUT;	
RUN;

DATA K0ADD(KEEP=BF_SSN LN_ATY_SEQ LC_STA_ACTY10 DX_STR_ADR_1 DX_STR_ADR_2 DM_CT DC_DOM_ST DF_ZIP_CDE DM_FGN_CNY COMMENTS)
	K0PHN(KEEP=BF_SSN LN_ATY_SEQ LC_STA_ACTY10 PHN1 PHN2 PHN3 COMMENTS)
	ARC_M1411(KEEP=BF_SSN LN_ATY_SEQ LC_STA_ACTY10 LX_ATY);
	SET ARCS;
	LENGTH DX_STR_ADR_1 $30. DX_STR_ADR_2 $30. DM_CT $20. DC_DOM_ST $2. DF_ZIP_CDE $17. DM_FGN_CNY $25. COMMENTS $300.;
	LENGTH  PHN1 PHN2 PHN3 $25.;
	ARRAY ADR{7} $ DX_STR_ADR_1 DX_STR_ADR_2 DM_CT DC_DOM_ST DF_ZIP_CDE DM_FGN_CNY COMMENTS;
	ARRAY PHN{4} $ PHN1 PHN2 PHN3 COMMENTS;
	IF PF_REQ_ACT = 'K0ADD' THEN DO;
		DO I = 1 TO 7;
			ADR(I) = SCAN(LX_ATY,I,',');
		END;
		OUTPUT K0ADD;
	END;
	ELSE if pf_req_act = 'K0PHN' THEN DO;
		DO I = 1 TO 4;
			PHN(I) = SCAN(LX_ATY,I,',');
		END;
		OUTPUT K0PHN;
	END;
	ELSE IF PF_REQ_ACT = 'M1411' THEN OUTPUT ARC_M1411;
RUN;


%SSN2ACC(K0ADD,LN_ATY_SEQ);
%SSN2ACC(K0PHN,LN_ATY_SEQ);
%SSN2ACC(ARC_M1411,LN_ATY_SEQ);

%SSN2ACC(DL200,LN_ATY_SEQ);
%SSN2ACC(DRLFA,);
%SSN2ACC(ARCHIST,LN_ATY_SEQ); 
%SSN2ACC(ARC_IND,LN_ATY_SEQ); 

/*********************************************
* FINANCIAL HISTORY
**********************************************/

DATA LN90_HIST
		(KEEP=
			BF_SSN
			LN_SEQ
			LN_FAT_SEQ
			LC_FAT_REV_REA
			LD_FAT_APL
			LD_FAT_PST
			LD_FAT_EFF
			LD_STA_LON90
			LC_STA_LON90
			LA_FAT_PCL_FEE
			LA_FAT_NSI
			LA_FAT_LTE_FEE
			LA_FAT_ILG_PRI
			LA_FAT_CUR_PRI
			PC_FAT_TYP
			PC_FAT_SUB_TYP
			LA_FAT_NSI_ACR
		)
	;
	SET PKUB.LN90_FIN_ATY;
	WHERE DATEPART(LF_LST_DTS_LN90) >= &LAST_RUN;
RUN;
%SSN2ACC(LN90_HIST,LN_SEQ LN_FAT_SEQ);

/*********************************************
* LT20 LETTER REQUESTS
**********************************************/
PROC SQL;
	CREATE TABLE LT20 AS
		SELECT
			RF_SBJ_PRC AS BF_SSN, 
			RT_RUN_SRT_DTS_PRC,
			RN_SEQ_LTR_CRT_PRC, 
			RN_SEQ_REC_PRC, 
			RM_DSC_LTR_PRC, 
			RC_TYP_SBJ_PRC,
			RF_SBJ_PRC ,
			RN_ENT_REQ_PRC,
			RN_ATY_SEQ_PRC, 
			RI_REC_PRC, 
			RX_REQ_ARA_1_PRC,
			RI_LTR_REQ_DEL_PRC, 
			RC_LTR_REQ_SRC_PRC, 
			RI_PRV_RUN_ERR_PRC, 
			RF_COR_DOC_PRC, 
			RI_LTR_OPT_ENC_PRC 
		FROM
			PKUB.LT20_LTR_REQ_PRC
		WHERE
			DATEPART(RT_RUN_SRT_DTS_PRC) >= &LAST_RUN
			AND RI_LTR_REQ_DEL_PRC <> 'Y'
	;
QUIT;
%SSN2ACC(LT20, RT_RUN_SRT_DTS_PRC RN_SEQ_LTR_CRT_PRC RN_SEQ_REC_PRC);

/*********************************************
* BORROWER BENEFIT PROGRAM TIERS
**********************************************/
PROC SQL;
	CREATE TABLE RP02 AS
		SELECT
			'0000000000' AS DF_SPE_ACC_ID, /*required by .L load job common macros*/
			PM_BBS_PGM,
			PN_BBS_PGM_SEQ,
			PF_BBS_PGM_TIR,
			PN_BBS_PGM_TIR_SEQ,
			PC_BBT_ICV,
			PN_BBT_PAY_ICV,
			PR_BBT_RDC,
			PC_BBT_REB_APL,
			PA_BBT_REB
		FROM
			PKUB.RP02_BBS_PGM_TIR RP02
		WHERE
			DATEPART(PF_LST_DTS_RP02) >= &LAST_RUN
	;
QUIT;

/*********************************************
* LOAN BORROWER BENEFIT PROGRAM TIERS
**********************************************/
PROC SQL;
	CREATE TABLE LN54 AS
		SELECT
			BF_SSN,
			LN_SEQ,
			PM_BBS_PGM,
			PN_BBS_PGM_SEQ,
			LN_LON_BBS_PGM_SEQ,
			LD_EFF_BEG_LN54,
			LI_BBS_ITD_LTR_SNT,
			LN_BBS_STS_PCV_PAY,
			LC_BBS_REB_MTD,
			LC_STA_LN54,
			LD_STA_LN54,
			LC_BBS_DSQ_REA,
			LD_BBS_DSQ,
			LC_BBS_ELG
		FROM
			PKUB.LN54_LON_BBS LN54
		WHERE
			DATEPART(LF_LST_DTS_LN54) >= &LAST_RUN
	;
QUIT;
%SSN2ACC(LN54,LN_SEQ PM_BBS_PGM PN_BBS_PGM_SEQ LN_LON_BBS_PGM_SEQ);

/*********************************************
* FINANCIAL ACTIVITY ADJUSTMENT
**********************************************/
PROC SQL;
	CREATE TABLE AD20 AS
		SELECT
			BF_SSN,
			LD_FAT_ADJ_REQ,
			LN_SEQ_FAT_ADJ_REQ,
			LC_TYP_FAT_ADJ_REQ,  
			LC_STA_FAT_ADJ_REQ
		FROM
			PKUB.AD20_PCV_ATY_ADJ AD20
		WHERE
			DATEPART(LF_LST_DTS_AD20) >= &LAST_RUN
	;
QUIT;
%SSN2ACC(AD20,LD_FAT_ADJ_REQ LN_SEQ_FAT_ADJ_REQ);

/*********************************************
* NEG AM
**********************************************/
PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);

	CREATE TABLE FS12 AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
				SELECT
					FS12.BF_SSN,
					FS12.LN_SEQ,
					FS12.LD_CRT_NEG_AMR_LTR,
					FS12.LA_PRJ_NEG_AMR_INT
				FROM
					PKUB.FS12_ICR_NEG_AMR FS12
				WHERE
					FS12.LF_LST_DTS_FS12 >= &LAST_RUNPASS	
			)
	;

	DISCONNECT FROM DB2;
QUIT;
%SSN2ACC(FS12,LN_SEQ LD_CRT_NEG_AMR_LTR);

/***************************************************************
* DEFER & FORBEAR APPROVED/CHANGED/DENIED LETTER – DEFER TABLE
***************************************************************/
PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);

	CREATE TABLE DFR_LTR AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
				SELECT
					DF10.BF_SSN,
					LN50.LN_SEQ,
					DF10.LF_DFR_CTL_NUM,
					LN50.LN_DFR_OCC_SEQ,
					DF10.LC_DFR_TYP,
					DF10.LD_DFR_INF_CER,
					DF10.LD_CRT_REQ_DFR,
					DF10.LC_DFR_STA,
					DF10.LC_STA_DFR10,
					DF10.LD_STA_DFR10,
					DF10.LF_LST_DTS_DF10,
					LN50.LD_DFR_BEG,
					LN50.LD_DFR_END,
					LN50.LC_STA_LON50,
					LN50.LC_LON_LEV_DFR_CAP,
					LN50.LF_LST_DTS_LN50,
					LN50.LD_STA_LON50,
					LN50.LD_DFR_APL
				FROM 
					PKUB.DF10_BR_DFR_REQ DF10
					JOIN PKUB.LN50_BR_DFR_APV LN50
						ON DF10.BF_SSN = LN50.BF_SSN
						AND DF10.LF_DFR_CTL_NUM = LN50.LF_DFR_CTL_NUM
				WHERE
					DF10.LF_LST_DTS_DF10 >= &LAST_RUNPASS
					OR LN50.LF_LST_DTS_LN50 >= &LAST_RUNPASS	
			)
	;

	DISCONNECT FROM DB2;
QUIT;
%SSN2ACC(DFR_LTR,LN_SEQ LF_DFR_CTL_NUM LN_DFR_OCC_SEQ);

/***************************************************************
* DEFER & FORBEAR APPROVED/CHANGED/DENIED LETTER – FORB TABLE
***************************************************************/
PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);

	CREATE TABLE FOR_LTR AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
				SELECT
					FB10.BF_SSN,
					LN60.LN_SEQ,
					FB10.LF_FOR_CTL_NUM,
					LN60.LN_FOR_OCC_SEQ,
					FB10.LC_FOR_TYP,
					FB10.LD_FOR_INF_CER,
					FB10.LD_CRT_REQ_FOR,
					FB10.LC_FOR_STA,
					FB10.LC_STA_FOR10,
					FB10.LD_STA_FOR10,
					FB10.LF_LST_DTS_FB10,
					LN60.LD_FOR_BEG,
					LN60.LD_FOR_END,
					LN60.LC_STA_LON60,
					LN60.LC_LON_LEV_FOR_CAP,
					LN60.LF_LST_DTS_LN60,
					LN60.LD_STA_LON60,
					LN60.LD_FOR_APL
				FROM
					PKUB.FB10_BR_FOR_REQ FB10
					JOIN PKUB.LN60_BR_FOR_APV LN60
						ON FB10.BF_SSN = LN60.BF_SSN
						AND FB10.LF_FOR_CTL_NUM = LN60.LF_FOR_CTL_NUM
				WHERE
					 FB10.LF_LST_DTS_FB10 >= &LAST_RUNPASS
					 OR LN60.LF_LST_DTS_LN60 >= &LAST_RUNPASS
			)
	;

	DISCONNECT FROM DB2;
QUIT;
%SSN2ACC(FOR_LTR,LN_SEQ LF_FOR_CTL_NUM LN_FOR_OCC_SEQ);

/*********************************************
* REPAYMENT SUMMARY LETTER
**********************************************/
PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);

	CREATE TABLE REPAY_SUM AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
				SELECT
					RS10.BF_SSN,
					LN65.LN_SEQ,
					LN65.LN_RPS_SEQ,
					LN66.LN_GRD_RPS_SEQ,
					LN65.LD_CRT_LON65,
					LN65.LC_TYP_SCH_DIS,
					LN65.LA_TOT_RPD_DIS,
					LN65.LR_INT_RPD_DIS,
					LN65.LA_ANT_CAP,
					LN65.LC_STA_LON65,
					LN65.LF_LST_DTS_LN65,
					LN66.LA_RPS_ISL,
					LN66.LD_CRT_LON66,
					LN66.LN_RPS_TRM,
					LN66.LF_LST_DTS_LN66,
					RS10.LD_RPS_1_PAY_DU
				FROM
					PKUB.RS10_BR_RPD RS10
					JOIN PKUB.LN65_LON_RPS LN65
						ON RS10.BF_SSN = LN65.BF_SSN
						AND RS10.LN_RPS_SEQ = LN65.LN_RPS_SEQ
					JOIN PKUB.LN66_LON_RPS_SPF LN66
						ON LN65.BF_SSN = LN66.BF_SSN
						AND LN65.LN_SEQ = LN66.LN_SEQ
						AND LN65.LN_RPS_SEQ = LN66.LN_RPS_SEQ
				WHERE
					LN65.LF_LST_DTS_LN65 >= &LAST_RUNPASS	
			)
	;

	DISCONNECT FROM DB2;
QUIT;
%SSN2ACC(REPAY_SUM,LN_SEQ LN_RPS_SEQ LN_GRD_RPS_SEQ);

/*********************************************
* IDR REPAYMENT INFORMATION
**********************************************/
PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);

	CREATE TABLE RS05 AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
				SELECT DISTINCT
					RS05.BF_SSN,
					RS05.BD_CRT_RS05,
					RS05.BN_IBR_SEQ,
					RS05.BF_CRY_YR,
					RS05.BC_ST_IBR,
					RS05.BC_STA_RS05,
					RS05.BA_AGI,
					RS05.BN_MEM_HSE_HLD,
					RS05.BA_PMN_STD_TOT_PAY,
					RS05.BC_IBR_INF_SRC_VER,
					RS05.BF_SSN_SPO,
					RS05.BC_IRS_TAX_FIL_STA,
					RS05.BI_JNT_BR_SPO_RPY,
					RS05.BD_ANV_QLF_IBR
				FROM
					PKUB.RS05_IBR_RPS RS05
				WHERE
					RS05.BF_LST_DTS_RS05 >= &LAST_RUNPASS	
			)
	;

	DISCONNECT FROM DB2;
QUIT;
%SSN2ACC(RS05,BN_IBR_SEQ);


/*********************************************
* SCHOOL DATA
**********************************************/
PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);

	CREATE TABLE SC10 AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
				SELECT DISTINCT
					'0000000000' AS DF_SPE_ACC_ID, /*required by .L load job common macros*/
					SC10.IF_DOE_SCL,
					SC10.IM_SCL_SHO,
					SC10.IM_SCL_FUL,
					SC10.IC_TYP_SCL,
					SC10.IC_PRV_SCL_STA,
					SC10.IC_CUR_SCL_STA,
					SC10.II_SCL_CHS_PTC,
					SC10.IC_LEN_LNG_PGM_STY

				FROM
					PKUB.SC10_SCH_DMO SC10
				WHERE
					SC10.IF_LST_DTS_SC10 >= &LAST_RUNPASS	
			)
	;

	DISCONNECT FROM DB2;
QUIT;

/*********************************************
* LOAN SUBSIDY
**********************************************/
PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);

	CREATE TABLE FS14 AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
				SELECT DISTINCT
					FS14.BF_SSN,
					FS14.LN_SEQ,
					FS14.LN_INC_SUB_EVT_SEQ,
					FS14.LD_INC_SUB_EFF_BEG,
					FS14.LD_INC_SUB_EFF_END,
					FS14.LC_INC_SUB_STA,
					FS14.LR_SUB_RMN,
					FS14.LF_LST_USR_FS14,
					FS14.LF_LST_DTS_FS14,
					FS14.LF_CRT_USR_FS14,
					FS14.LD_CRT_FS14,
					FS14.LC_STA_FS14,
					FS14.LD_STA_FS14

				FROM
					PKUB.FS14_SUB_LOS_RNS FS14
				WHERE
					FS14.LF_LST_DTS_FS14 >= &LAST_RUNPASS	
			)
	;

	DISCONNECT FROM DB2;
QUIT;
%SSN2ACC(FS14, LN_SEQ);

/*********************************************
* QUEUE TASKS
**********************************************/
PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);

	CREATE TABLE WQ20 AS
		SELECT 
			*
		FROM CONNECTION TO DB2 
			(
				SELECT DISTINCT
					WQ20.BF_SSN,
					WQ20.WF_QUE,
					WQ20.WF_SUB_QUE,
					WQ20.WN_CTL_TSK,
					WQ20.PF_REQ_ACT,
					WQ20.WD_ACT_REQ,
					WQ20.WD_ACT_RQR,
					WQ20.WC_CND_CTC,
					WQ20.WD_INI_TSK,
					WQ20.WT_INI_TSK,
					WQ20.WF_USR_ASN_TSK,
					WQ20.WF_USR_ASN_BY_TSK,
					WQ20.WX_MSG_1_TSK,
					WQ20.WX_MSG_2_TSK,
					WQ20.WC_STA_WQUE20,
					WQ20.WF_LST_DTS_WQ20,
					WQ20.LN_ATY_SEQ,
					WQ20.WF_CRT_DTS_WQ20
				FROM
					PKUB.WQ20_TSK_QUE WQ20
				WHERE
					WQ20.WF_LST_DTS_WQ20  >= &LAST_RUNPASS	
			)
	;

	DISCONNECT FROM DB2;
QUIT;
%SSN2ACC(WQ20,WF_QUE WF_SUB_QUE WN_CTL_TSK);

/*********************************************
* LN83
**********************************************/
PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);

	CREATE TABLE LN83 AS
		SELECT 
			*
		FROM 
			CONNECTION TO DB2 
				(
					SELECT
						*
					FROM
						PKUB.LN83_EFT_TO_LON LN83
					WHERE
						LN83.LF_LST_DTS_LN33 >= &LAST_RUNPASS

					FOR READ ONLY WITH UR
				)
	;

	DISCONNECT FROM DB2;
QUIT;
%SSN2ACC(LN83,);

/*********************************************
* OW30
**********************************************/
PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);

	CREATE TABLE OW30 AS
		SELECT 
			*
		FROM 
			CONNECTION TO DB2 
				(
					SELECT
						IF_LON_SLE ,
						IC_LON_SLE_STA ,
						IC_LON_SLE_TYP ,
						ID_LON_SLE ,
						IF_SLL_OWN ,
						IM_SLL_CNC_1 ,
						IM_SLL_CNC_LST ,
						IN_SLL_CNC_PHN_ARA ,
						IN_SLL_CNC_PHN_XCH ,
						IN_SLL_CNC_PHN_LCL ,
						IN_SLL_CNC_PHN_XTN ,
						IF_SLL_BND_ISS ,
						ID_SLL_LON_SLE_APV ,
						IF_BUY_OWN ,
						IM_BUY_CNC_1 ,
						IM_BUY_CNC_LST ,
						IN_BUY_CNC_PHN_ARA ,
						IN_BUY_CNC_PHN_XCH ,
						IN_BUY_CNC_PHN_LCL ,
						IN_BUY_CNC_PHN_XTN ,
						IF_BUY_BND_ISS ,
						ID_BUY_LON_SLE_APV ,
						IM_MKT_CNC_1 ,
						IM_MKT_CNC_LST ,
						IN_MKT_CNC_PHN_ARA ,
						IN_MKT_CNC_PHN_XCH ,
						IN_MKT_CNC_PHN_LCL ,
						IN_MKT_CNC_PHN_XTN ,
						IM_TRF_CNC_1 ,
						IM_TRF_CNC_LST ,
						IN_TRF_CNC_PHN_ARA ,
						IN_TRF_CNC_PHN_XCH ,
						IN_TRF_CNC_PHN_LCL ,
						IN_TRF_CNC_PHN_XTN ,
						IM_LEG_CNC_1 ,
						IM_LEG_CNC_LST ,
						IN_LEG_CNC_PHN_ARA ,
						IN_LEG_CNC_PHN_XCH ,
						IN_LEG_CNC_PHN_LCL ,
						IN_LEG_CNC_PHN_XTN ,
						IC_FEE_ORG_RSB ,
						II_ACP_NEW_LON_SLE ,
						IA_LON_TOT_MAX ,
						II_INT_ICL ,
						IN_LON_MAX ,
						CASE WHEN II_SLE_LTR_TRG = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
						IF_SLE_LTR_SPC ,
						IF_LST_DTS_OW30 ,
						IF_BUY_POR ,
						IC_SLL_PNT_LOC ,
						IC_BUY_PNT_LOC ,
						IC_TIR_PCE_ASN ,
						CASE WHEN II_LTE_FEE_WOF = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
						IC_LON_SLE_SEL_TYP ,
						II_LTE_FEE_MAX_VAL ,
						II_STP_SLE_LON_MAX ,
						II_LEV_BR_LON_ELG ,
						IC_SEL_CRI_USR_APV ,
						ID_SEL_CRI_USR_APV ,
						IF_SEL_CRI_USR_APV ,
						ID_SEL_NXT_PLR ,
						ID_LON_SLE_LST_PLR ,
						IT_SLE_LST_PLR ,
						IN_LON_SLE_BR_ELG ,
						IN_LON_SLE_LON_ELG ,
						IA_CUR_PRI_ELG_LON ,
						IA_NSI_ELG_LON ,
						IA_LTE_FEE_ELG_LON ,
						IN_IVL_SCH_NXT_SLE ,
						IC_IVL_SCH_NXT_SLE ,
						IN_IVL_SCH_NXT_PLR ,
						IC_IVL_SCH_NXT_PLR ,
						IX_TRG_FIL_SEL_CRI ,
						IC_RGN_RCV_DCV_LON ,
						IX_DSC_BUY_OWN ,
						LA_BR_PRI_BAL_SLE ,
						LC_BR_PRI_REL_SLE ,
						II_ORG_RGT_PUR_SLE ,
						IF_GRP_SLE_KEY ,
						IC_EFT_RIR_RSB ,
						IX_LON_SLE_CMT ,
						IC_BBS_RSB ,
						IC_LON_SLE_SUB_TYP ,
						IA_SLE_LVL_TRF_FEE ,
						IC_TRF_FEE_TYP ,
						IR_PRI_PER_FEE_RTE ,
						CASE WHEN II_ICL_CON_STP_PUR = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
						ID_ECA_DCV_CRT_FIL ,
						II_ECA_PUT_DCV_APV ,
						ID_ECA_CRT_BIL_SLE ,
						ID_CDU_REM_NTF ,
						IC_FED_PGM_YR ,
						IF_FLS_DEA ,
						IF_DEA_IST_LIN_HLD ,
						CASE WHEN II_LON_SLE_ICL_IDT = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
						CASE WHEN II_ICL_CON_GRP_RLP = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
						CASE WHEN LI_PCV_OWN_EFF_DTE = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
						CASE WHEN II_PRE_SLE_LTR = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
						IC_DLA_CAN_LTR ,
						IC_PRE_SLE_LST_PRC 
					FROM
						PKUB.OW30_LON_SLE_CTL OW30
					WHERE
						OW30.LF_LST_DTS_OW30 >= &LAST_RUNPASS

					FOR READ ONLY WITH UR
				)
	;

	DISCONNECT FROM DB2;
QUIT;
/*%SSN2ACC(OW30,);*/

/*********************************************
* WK1J
**********************************************/
PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);

	CREATE TABLE WK1J AS
		SELECT 
			*
		FROM 
			CONNECTION TO DB2 
				(
					SELECT
						*
					FROM
						PKUB.WK1J_LON_SLE_PLR WK1J
					WHERE
						WK1J.IT_SLE_LST_PLR >= &LAST_RUNPASS

					FOR READ ONLY WITH UR
				)
	;

	DISCONNECT FROM DB2;
QUIT;
%SSN2ACC(WK1J,);

/*********************************************
* LN94
**********************************************/
PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);

	CREATE TABLE LN94 AS
		SELECT 
			*
		FROM 
			CONNECTION TO DB2 
				(
					SELECT
						*
					FROM
						PKUB.LN94_LON_PAY_FAT LN94
					WHERE
						LN94.LF_LST_DTS_LN94 >= &LAST_RUNPASS

					FOR READ ONLY WITH UR
				)
	;

	DISCONNECT FROM DB2;
QUIT;
%SSN2ACC(LN94,);

/*********************************************
* RM30
**********************************************/
PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);

	CREATE TABLE RM30 AS
		SELECT 
			LD_RMT_BCH_INI ,
			LC_RMT_BCH_SRC_IPT ,
			LN_RMT_BCH_SEQ ,
			LN_RMT_SEQ ,
			LN_RMT_ITM ,
			LN_RMT_ITM_SEQ ,
			LC_RMT_STA ,
			LA_BR_RMT ,
			LC_RMT_REV_REA ,
			CASE WHEN LI_RMT_PD_AHD = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
			LD_RMT_PAY_EFF ,
			LF_RMT_EDS ,
			LF_RMT_IST ,
			LX_SPS_REA ,
			LD_RMT_SPS ,
			LD_RMT_PST ,
			LD_UPD_REMT30 ,
			LD_CRT_REMT30 ,
			LD_RMT_BCH_INI_REV ,
			LC_RMT_BCH_IPT_REV ,
			LN_RMT_BCH_SEQ_REV ,
			LN_RMT_SEQ_REV ,
			LN_RMT_ITM_REV ,
			LN_RMT_ITM_SEQ_REV ,
			LF_LST_DTS_RM30 ,
			PC_FAT_TYP ,
			PC_FAT_SUB_TYP ,
			DF_SPE_ACC_ID ,
			LD_BIL_CRT ,
			LN_SEQ_BIL_WI_DTE ,
			LI_DPS_RMT_PIO_CVN ,
			BN_CPN_BK_SEQ ,
			LD_BIL_CPN_DU ,
			CASE WHEN LI_PHD_PAS_DU = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
			CASE WHEN LI_PHD_PAS_RPS = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
			CASE WHEN LI_PHD_PAS_OPT = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
			LI_PHD_BCH_OVR ,
			LC_RMT_REV_REA_REJ ,
			LC_STP_SPS_OVR ,
			LC_RMT_PAY_SRC ,
			CASE WHEN LC_RMT_SPS_OVR_FRD = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
			LI_DPL_ACC_RMT ,
			CASE WHEN LC_WAV_MSC_FEE_ASS = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
			LD_SCH_RMT_PAY ,
			LF_LCK_BOX_TRC ,
			LF_BR_RMT_SCH_NUM ,
			LC_BR_RMT_SCH_TYP ,
			LI_CON_SPS_OVR ,
			LD_RMT_SCH_NUM_DPS 
		FROM 
			CONNECTION TO DB2 
				(
					SELECT
						*
					FROM
						PKUB.RM30_LON_PAY_FAT RM30
					WHERE
						RM30.LF_LST_DTS_RM30 >= &LAST_RUNPASS

					FOR READ ONLY WITH UR
				)
	;

	DISCONNECT FROM DB2;
QUIT;
/*%SSN2ACC(RM30,);*/

/*********************************************
* LN10
**********************************************/
PROC SQL;
	CONNECT TO DB2 (DATABASE=&DB);

	CREATE TABLE LN10 AS
		SELECT 
			*
		FROM 
			CONNECTION TO DB2 
				(
					SELECT
						DF_SPE_ACC_ID ,
						LN_SEQ ,
						LC_STA_LON10 ,
						LI_FGV_PGM ,
						LF_LON_SLE_PND ,
						LA_CUR_PRI ,
						LI_ELG_CPN_BOK ,
						LA_LON_AMT_GTR ,
						LD_LON_GTR ,
						LD_PIF_PNT_RTN ,
						LD_PNT_SIG ,
						LC_INT_BIL_OPT ,
						LI_CAP_ALW ,
						LD_END_GRC_PRD ,
						LN_MTH_GRC_PRD_DSC ,
						LA_R78_INT_PD ,
						LA_R78_INT_MAX ,
						LD_CAP_LST_PIO_CVN ,
						LD_TRM_END ,
						LD_TRM_BEG ,
						CASE WHEN LI_GTR_NAT = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
						LF_GTR_RFR ,
						CASE WHEN LI_ELG_SPA = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
						LD_GTE_LOS ,
						LA_SCL_CLS ,
						LA_CUR_ILG ,
						LA_ILG ,
						LD_PIF_RPT ,
						LA_NSI_OTS ,
						LD_NSI_ACR_THU ,
						LD_STA_LON10 ,
						LD_LON_ACL_ADD ,
						LD_LON_EFF_ADD ,
						LF_DOE_SCL_ORG ,
						LC_PCV_DIS_STA ,
						LC_RPR_TYP ,
						LF_RGL_CAT_LP19 ,
						LF_RGL_CAT_LP18 ,
						LF_RGL_CAT_LP17 ,
						LF_RGL_CAT_LP13 ,
						LF_RGL_CAT_LP12 ,
						LF_RGL_CAT_LP11 ,
						LF_RGL_CAT_LP10 ,
						LF_RGL_CAT_LP08 ,
						LF_RGL_CAT_LP07 ,
						LF_RGL_CAT_LP06 ,
						LF_RGL_CAT_LP05 ,
						LF_RGL_CAT_LP04 ,
						LF_RGL_CAT_LP03 ,
						LF_RGL_CAT_LP02 ,
						LF_RGL_CAT_LP01 ,
						LD_SCL_CLS_NTF ,
						LD_ILG_NTF ,
						LF_LON_CUR_OWN ,
						LF_LST_DTS_LN10 ,
						LC_STA_NEW_BR ,
						LC_SCY_PGA ,
						LD_SIN_LST_PD_PCV ,
						LD_SIN_ACR_THU_PCV ,
						LA_SIN_OTS_PCV ,
						IC_LON_PGM ,
						PF_MAJ_BCH ,
						PF_MNR_BCH ,
						IF_DOE_LDR ,
						IF_GTR ,
						LF_STU_SSN ,
						LD_LON_1_DSB ,
						LC_ACA_GDE_LEV ,
						LD_NEW_SYS_CVN ,
						LC_SCY_PGA_PGM_YR ,
						IC_HSP_CSE ,
						LI_TL4_793_XCL_CON ,
						LI_DFR_REQ_ON_APL ,
						LI_LN_PT_COM_APL ,
						LN_SEQ_RPR ,
						LR_WIR_CON_LON ,
						LR_INT_RDC_PGM_DSU ,
						LI_1_TME_BR ,
						BF_SSN_RPR ,
						LC_ELG_RDC_PGM ,
						LD_ELG_RDC_PGM ,
						LC_RPD_SLE ,
						LR_ITR_ORG ,
						LC_ITR_TYP_ORG ,
						LC_RDC_PGM ,
						LC_TIR_GRP ,
						LD_SER_RSB_BEG ,
						LC_EFT_RDC ,
						LD_LTS_STS_BIL ,
						IF_TIR_PCE ,
						LF_RGL_CAT_LP20 ,
						LN_RDC_PGM_PAY_PCV ,
						LC_REA_PIF_PCV ,
						LD_FAT_PIF_TOL_PCV ,
						LA_FAT_PIF_TOL_PCV ,
						LI_RTE_RDC_ELG ,
						LD_LTE_FEE_ELG ,
						LA_LTE_FEE_OTS ,
						LD_LON_LTE_FEE_WAV ,
						LC_CUR_RDC_PGM_NME ,
						LI_RIR_SCY_ELG ,
						LD_END_RIR_DSQ_OVR ,
						LF_LON_ALT ,
						LN_LON_ALT_SEQ ,
						CASE WHEN LI_LDR_LST_RST_DSB = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
						LC_ST_BR_RSD_APL ,
						LI_PIF_RPT_REQ ,
						LD_AMR_BEG ,
						LD_ORG_XPC_GRD ,
						LD_CON_LST_RPY_BEG ,
						LN_CON_MTH_DFR_FOR ,
						LD_LON_APL_RCV ,
						LR_SCL_SUB ,
						LI_BLL_PAY_SES_OVR ,
						LC_MPN_TYP ,
						LD_MPN_EXP ,
						LC_MPN_SRL_LON ,
						LC_MPN_REV_REA ,
						LF_ORG_RGN ,
						LC_CAM_LON_STA ,
						LD_DFR_FOR_END ,
						LC_DFR_FOR_TYP ,
						LF_CAM_DFR_SCL_ENR ,
						LD_DFR_FOR_BEG ,
						LD_CAM_DFR_INF_CER ,
						LI_BR_DET_RPD_XTN ,
						DD_DTH_VER ,
						DD_DSA_VER ,
						LI_CON_PAY_STP_PUR ,
						LD_FSE_CER_NTF ,
						LA_TOT_EDU_DET ,
						LI_LDR_BG_APL ,
						LD_RIR_CSC_BIL_STS ,
						LI_ESG ,
						LC_RIR_DSQ_REA ,
						LF_MN_MST_NTE ,
						LN_MN_MST_NTE_SEQ ,
						LC_LON_SND_CHC ,
						LC_SST_LON10 ,
						LF_RGL_CAT_LP09 ,
						LI_MN_PSD_BS ,
						LF_CRD_RTE_SRE ,
						LF_ESG_SRC ,
						PC_PNT_YR ,
						LF_OWN_BND_ISS_TE1 ,
						LF_OWN_BND_ISS_TE2 ,
						LF_OWN_BND_ISS_TE3 ,
						LD_MPN_STM_SNT ,
						CASE WHEN LI_MNT_BIL_RCP = 'Y' THEN 1 ELSE 0 END AS AI_MN_ORG_RGT_SLD,
						LX_BS_POI ,
						LA_BS_POI ,
						LA_INT_FEE_URP_IRS ,
						LC_BR_ALW_SCL_DFR ,
						LD_BR_ALW_SCL_DFR ,
						LC_LON_DFR_SUB_TYP ,
						LD_FAT_PRI_BAL_ZRO ,
						LC_ST_SCL_ATD_APL ,
						LD_EFT_DSQ_NSF_LMT ,
						LD_CLM_PD ,
						LC_STP_PUR ,
						LD_CON_PAY_EFF ,
						LD_CON_PAY_APL ,
						LC_ESG ,
						LC_LON_RPE_CVN_REA ,
						LC_UDL_DSB_COF ,
						LI_BR_LT_HT ,
						LI_ALL_PAY_FLG_SPS ,
						LN_MFY_GRS_PAY ,
						LC_ESP_RPD_OPT_SEL ,
						LC_ELG_95_SPA_BIL ,
						LC_SGM_COS_PRC ,
						LD_GTR_DR_DCH_CER ,
						LD_RPD_ELY_CL_BEG ,
						LD_RPD_ELY_CL_END ,
						LF_GTR_RFR_XTN ,
						LA_MSC_FEE_OTS ,
						LA_MSC_FEE_PCV_OTS ,
						LF_LON_GRP_WI_BR ,
						LC_TL4_IBR_ELG ,
						LD_LON_IBR_ENT ,
						LC_LON_IBR_RPY_TYP ,
						LI_BYP_COL_OUT_SRC ,
						LI_BR_GRP_RLP ,
						LI_OO_PST_ENR_DFR ,
						LD_OO_PST_ENR_DFR ,
						LF_FED_CLC_RSK ,
						LF_FED_FFY_1_DSB ,
						LF_PRV_GTR ,
						LC_FED_PGM_YR ,
						LA_INT_RCV_GOV ,
						LC_WOF_WUP_REA ,
						LC_VRS_ALT_APL ,
						LF_LON_DCV_CLI ,
						LN_LON_SEQ_DCV_CLI ,
						LI_EDS_BKR_STP_PUR ,
						LF_EDS ,
						LD_EFF_LBR_RTE ,
						LA_STD_STD_PAY ,
						LI_FRC_IBR ,
						LC_STP_PUR_REA ,
						LD_IDR_ELG_CHG ,
						LC_IDR_ELG_CRI
					FROM
						PKUB.LN10_LON LN10
					WHERE
						LN10.LF_LST_DTS_LN10 >= &LAST_RUNPASS

					FOR READ ONLY WITH UR
				)
	;

	DISCONNECT FROM DB2;
QUIT;
%SSN2ACC(LN10,);


/*DATA SAS_TAB.LASTRUN_JOBS;*/
/*SET SAS_TAB.LASTRUN_JOBS;*/
/*IF JOB = 'UTNWDW1' THEN LAST_RUN = TODAY();*/
/*RUN;*/
ENDRSUBMIT;

DATA LN20; SET LEGEND.LN20; RUN; *2;
DATA BR03; SET LEGEND.BR03; RUN; *3;
DATA LN80; SET LEGEND.LN80; RUN; *4;
DATA LN90; SET LEGEND.LN90; RUN; *5;
DATA DF10; SET LEGEND.DF10; RUN; *6;
DATA FB10; SET LEGEND.FB10; RUN; *7;
DATA PD10; SET LEGEND.PD10; RUN; *8;
DATA DL200; SET LEGEND.DL200; RUN; *9; 
DATA DRLFA; SET LEGEND.DRLFA; RUN; *10;
DATA LN10; SET LEGEND.LN10; RUN; *11;
DATA LN83; SET LEGEND.LN83; RUN; *12;
DATA LN09; SET LEGEND.LN09; RUN; *13;
DATA LN15; SET LEGEND.LN15; RUN; *14;
DATA LN55; SET LEGEND.LN55; RUN; *15;
DATA ARC_IND; SET LEGEND.ARC_IND; RUN; *16;  
DATA LN65; SET LEGEND.LN65; RUN; *17;
DATA LN72; SET LEGEND.LN72; RUN; *18;
DATA SD10; SET LEGEND.SD10; RUN; *19;
DATA LN16; SET LEGEND.LN16; RUN; *20;
DATA K0PHN; SET LEGEND.K0PHN; RUN; *21;  
DATA BR30; SET LEGEND.BR30; RUN; *22;
DATA PD32; SET LEGEND.PD32; RUN; *23;
DATA RM31; SET LEGEND.RM31; RUN; *24;
DATA PD30; SET LEGEND.PD30; RUN; *25;
DATA PD42; SET LEGEND.PD42; RUN; *26;
DATA K0ADD; SET LEGEND.K0ADD; RUN; *27;
DATA ARCHIST; SET LEGEND.ARCHIST; RUN; *28;
DATA DW01; SET LEGEND.DW01; RUN; *29;
DATA LN56; SET LEGEND.LN56; RUN; *30;
DATA CUR_DUE; SET LEGEND.CUR_DUE; RUN; *31;
DATA ARC_M1411; SET LEGEND.ARC_M1411; RUN; *32;
DATA LN90_HIST; SET LEGEND.LN90_HIST; RUN; *33;
DATA LT20; SET LEGEND.LT20; RUN; *34;
DATA RP02; SET LEGEND.RP02; RUN; *35;
DATA LN54; SET LEGEND.LN54; RUN; *36;
DATA AD20; SET LEGEND.AD20; RUN; *37;
DATA FS12; SET LEGEND.FS12; RUN; *38;
DATA DFR_LTR; SET LEGEND.DFR_LTR; RUN; *39;
DATA FOR_LTR; SET LEGEND.FOR_LTR; RUN; *40;
DATA REPAY_SUM; SET LEGEND.REPAY_SUM; RUN; *41;
DATA RS05; SET LEGEND.RS05; RUN; *42;
DATA SC10; SET LEGEND.SC10; RUN; *43;
DATA FS14; SET LEGEND.FS14; RUN; *44;
DATA WQ20; SET LEGEND.WQ20; RUN; *45;
DATA LN83; SET LEGEND.LN83; RUN; *46;
DATA OW30; SET LEGEND.OW30; RUN; *47;
DATA WK1J; SET LEGEND.WK1J; RUN; *48;
DATA LN94; SET LEGEND.LN94; RUN; *49;
DATA RM30; SET LEGEND.RM30; RUN; *50;
DATA LN10; SET LEGEND.LN10; RUN; *51;

DATA _NULL_;
	SET LN20 end = eof;
	FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LC_STA_LON20 $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET BR03 end = eof;
	FILE REPORT3 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LST_CNC LST_ATT MMDDYY10.;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT BF_RFR  @;
		PUT BC_STA_REFR10 @;
		PUT BI_ATH_3_PTY @;
		PUT BC_RFR_REL_BR @;
		PUT DM_PRS_1 @;
		PUT DM_PRS_LST @;
		PUT LST_CNC @;
		PUT LST_ATT $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET LN80 end = eof;
	FILE REPORT4 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_BIL_CRT LD_FAT_EFF LD_BIL_DU_LON MMDDYY10. ;
	FORMAT 	LA_BIL_CUR_DU LA_BIL_PAS_DU	LA_TOT_BIL_STS LA_INT_PD_LST_STM LA_FEE_PD_LST_STM LA_PRI_PD_LST_STM LA_TTL_PD_LST_STM LA_LTE_FEE_OTS_PRT 9.2;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LD_BIL_CRT @;
		PUT LN_SEQ_BIL_WI_DTE @;
		PUT LD_FAT_EFF @;
		PUT LD_BIL_DU_LON @;
		PUT LC_STA_LON80 @;
		PUT LA_BIL_CUR_DU @;
		PUT LA_BIL_PAS_DU @;
		PUT LC_BIL_MTD @;
		PUT LC_IND_BIL_SNT @;
		PUT LC_STA_BIL10 @;
		PUT LA_TOT_BIL_STS @;
		PUT LA_INT_PD_LST_STM @;
		PUT LA_FEE_PD_LST_STM @;
		PUT LA_PRI_PD_LST_STM @;
		PUT LA_TTL_PD_LST_STM @;
		PUT LA_LTE_FEE_OTS_PRT $;
	END;
	if eof then put "-End-";
RUN; 

DATA _NULL_;
	SET LN90 end = eof;
	FILE REPORT5 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_FAT_PST LD_FAT_EFF MMDDYY10. ;
	FORMAT LA_FAT_CUR_PRI LA_FAT_LTE_FEE LA_FAT_NSI 10.2 ;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LN_FAT_SEQ @;
		PUT LD_FAT_PST @;
		PUT LD_FAT_EFF  @;
		PUT LC_STA_LON90 @;
		PUT LA_FAT_CUR_PRI @;
		PUT LA_FAT_LTE_FEE @;
		PUT PC_FAT_TYP @;
		PUT PC_FAT_SUB_TYP @;
		PUT LA_FAT_NSI @;
		PUT LC_FAT_REV_REA $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET DF10 end = eof;
	FILE REPORT6 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_DFR_INF_CER LD_DFR_BEG LD_DFR_END MMDDYY10. ;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LF_DFR_CTL_NUM @;
		PUT LN_DFR_OCC_SEQ @;
		PUT LC_DFR_TYP @;
		PUT LD_DFR_INF_CER @;
		PUT LD_DFR_BEG @;
		PUT LD_DFR_END @;
		PUT LC_LON_LEV_DFR_CAP @;
		PUT LC_STA_LON50 @;
		PUT LC_DFR_STA @;
		PUT LC_STA_DFR10 $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET FB10 end = eof;
	FILE REPORT7 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_FOR_INF_CER LD_FOR_BEG LD_FOR_END MMDDYY10. LA_REQ_RDC_PAY 9.2;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LF_FOR_CTL_NUM @;
		PUT LN_FOR_OCC_SEQ @;
		PUT LC_FOR_TYP @;
		PUT LD_FOR_INF_CER @;
		PUT LD_FOR_BEG @;
		PUT LD_FOR_END @;
		PUT LC_LON_LEV_FOR_CAP @;
		PUT LC_STA_LON60 @;
		PUT LC_FOR_STA @;
		PUT LC_STA_FOR10 @;
		PUT LA_REQ_RDC_PAY @;
		PUT LI_FOR_VRB_DFL_RUL $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET PD10 end = eof;
	FILE REPORT8 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT DD_BRT MMDDYY10.;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT BF_SSN @;
		PUT DM_PRS_1 @;
		PUT DM_PRS_LST @;
		PUT DM_PRS_MID @;
		PUT DD_BRT $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET DL200 end = eof;
	FILE REPORT9 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_ATY_REQ_RCV MMDDYY10.;
	IF _N_ = 1 THEN put "-Begin-";
	DO;	
		PUT DF_SPE_ACC_ID @;
		PUT LN_ATY_SEQ @;
		PUT LC_STA_ACTY10 @;
		PUT LD_ATY_REQ_RCV $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET DRLFA end = eof;
	FILE REPORT10 DELIMITER=',' DSD DROPOVER LRECL=32767;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT FEE_WAV_DOL @;
		PUT FEE_WAV_CT $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET LN10 end = eof;
	FILE REPORT11 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_END_GRC_PRD LD_LON_1_DSB  LD_PIF_RPT MMDDYY10. ;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LC_STA_LON10 @;
		PUT LA_CUR_PRI @;
		PUT LA_LON_AMT_GTR @;
		PUT LD_END_GRC_PRD @;
		PUT IC_LON_PGM @;
		PUT LD_LON_1_DSB @;
		PUT LD_PIF_RPT @;
		PUT LC_SST_LON10 @;
		PUT LF_LON_CUR_OWN @;
		PUT LF_DOE_SCL_ORG $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET LN83 end = eof;
	FILE REPORT12 DELIMITER=',' DSD DROPOVER LRECL=32767;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ  @;
		PUT BN_EFT_SEQ @;
		PUT LC_STA_LN83 $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET LN09 end = eof;
	FILE REPORT13 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_LON_RHB_PCV MMDDYY10. ;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LD_LON_RHB_PCV $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET LN15 end = eof;
	FILE REPORT14 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_DSB MMDDYY10.;
	FORMAT LA_DSB LA_DL_REBATE 9.2;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_BR_DSB_SEQ @;
		PUT LA_DSB @;
		PUT LD_DSB @;
		PUT LC_DSB_TYP @;
		PUT LC_STA_LON15 @;
		PUT LN_SEQ @;
		PUT LA_DL_REBATE $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET LN55 end = eof;
	FILE REPORT15 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_BBS_DSQ MMDDYY10. ;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ  @;
		PUT LD_BBS_DSQ  @;
		PUT LC_BBS_ELG @;
		PUT PR_EFT_RIR @;
		PUT PM_BBS_PGM @;
		PUT LN_BBS_STS_PCV_PAY @;
		PUT PN_BBT_DLQ_MOT $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET ARC_IND end = eof;
	FILE REPORT16 DELIMITER=',' DSD DROPOVER LRECL=32767;
	IF _N_ = 1 THEN put "-Begin-";
	DO;	
		PUT DF_SPE_ACC_ID @;
		PUT LN_ATY_SEQ @;
		PUT PF_REQ_ACT @;
		PUT LC_STA_ACTY10 $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET LN65 end = eof;
	FILE REPORT17 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_CRT_LON65 LD_SNT_RPD_DIS MMDDYY10. ;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ  @;
		PUT LD_CRT_LON65 @;	
		PUT LC_TYP_SCH_DIS @; 
		PUT LD_SNT_RPD_DIS @;
		PUT LA_RPS_ISL @;
		PUT DAY_DUE @;
		PUT LN_RPS_TRM $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET LN72 end = eof;
	FILE REPORT18 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_ITR_EFF_BEG LD_ITR_EFF_END MMDDYY10.;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ  @;
		PUT LR_ITR @;
		PUT LR_INT_RDC_PGM_ORG @;
		PUT LC_ITR_TYP @;
		PUT LD_ITR_EFF_BEG @;
		PUT LD_ITR_EFF_END $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET SD10 end = eof;
	FILE REPORT19 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_SCL_SPR MMDDYY10.;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ  @;
		PUT LD_SCL_SPR @;
		PUT IM_SCL_FUL $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET LN16 end = eof;
	FILE REPORT20 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_DLQ_OCC LD_DLQ_MAX MMDDYY10.;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LD_DLQ_OCC @;
		PUT LN_DLQ_MAX @;
		PUT LD_DLQ_MAX $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET K0PHN end = eof;
	FILE REPORT21 DELIMITER=',' DSD DROPOVER LRECL=32767;
	IF _N_ = 1 THEN put "-Begin-";
	DO;	
		PUT DF_SPE_ACC_ID @;
		PUT LN_ATY_SEQ @;
		PUT LC_STA_ACTY10 @;
		PUT PHN1 @;
		PUT PHN2 @;
		PUT PHN3 @;
		PUT COMMENTS $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET BR30 end = eof;
	FILE REPORT22 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT BD_EFT_STA MMDDYY10.;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT BN_EFT_SEQ @;
		PUT BF_EFT_ABA @;
		PUT BF_EFT_ACC @;
		PUT BC_EFT_STA @;
		PUT BD_EFT_STA @;
		PUT BA_EFT_ADD_WDR @;
		PUT BN_EFT_NSF_CTR @;
		PUT BC_EFT_DNL_REA $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET PD32 end = eof;
	FILE REPORT23 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT DD_VER_ADR_EML MMDDYY10.;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT DC_ADR_EML @;
		PUT DX_ADR_EML @;
		PUT DD_VER_ADR_EML @;
		PUT DI_VLD_ADR_EML $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET RM31 end = eof;
	FILE REPORT24 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LA_BR_RMT_PST 10.2 ;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LA_BR_RMT_PST $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET PD30 end = eof;
	FILE REPORT25 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT DD_VER_ADR MMDDYY10.;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT DX_STR_ADR_1 @;
		PUT DX_STR_ADR_2 @;
		PUT DM_CT @;
		PUT DC_DOM_ST @;
		PUT DF_ZIP_CDE @;
		PUT DM_FGN_ST @;
		PUT DM_FGN_CNY @;
		PUT DD_VER_ADR @;
		PUT DI_VLD_ADR $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET PD42 end = eof;
	FILE REPORT26 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT DD_PHN_VER MMDDYY10.;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT DC_PHN @;
		PUT DC_ALW_ADL_PHN @;
		PUT DD_PHN_VER @;
		PUT DI_PHN_VLD @;
		PUT DN_DOM_PHN_ARA @;
		PUT DN_DOM_PHN_XCH @;
		PUT DN_DOM_PHN_LCL @;
		PUT DN_PHN_XTN @;
		PUT DN_FGN_PHN_CNY @;
		PUT DN_FGN_PHN_CT @;
		PUT DN_FGN_PHN_LCL $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET K0ADD end = eof;
	FILE REPORT27 DELIMITER=',' DSD DROPOVER LRECL=32767;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_ATY_SEQ  @;
		PUT LC_STA_ACTY10 @;
		PUT DX_STR_ADR_1 @;
		PUT DX_STR_ADR_2 @;
		PUT DM_CT @;
		PUT DC_DOM_ST @;
		PUT DF_ZIP_CDE @;
		PUT DM_FGN_CNY @;
		PUT COMMENTS $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET ARCHIST end = eof;
	FILE REPORT28 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_ATY_REQ_RCV LD_ATY_RSP MMDDYY10.;
	FORMAT LT_ATY_RSP TIME8.;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_ATY_SEQ @;
		PUT LC_STA_ACTY10 @;
		PUT PF_REQ_ACT @;
		PUT PF_RSP_ACT @;
		PUT PX_ACT_DSC_REQ @;
		PUT LD_ATY_REQ_RCV @;
		PUT LD_ATY_RSP @;
		PUT LF_USR_REQ_ATY @;
		PUT LT_ATY_RSP @;
		PUT LX_ATY @;
		PUT LC_ATY_RCP @;
		PUT LF_ATY_RCP $;
	END;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET DW01 end = eof;
	FILE REPORT29 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT WA_TOT_BRI_OTS 9.2 WD_LON_RPD_SR mmddyy10.;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ  @;
		PUT WC_DW_LON_STA  @;
		PUT WA_TOT_BRI_OTS @;
		PUT WD_LON_RPD_SR @;
		PUT WX_OVR_DW_LON_STA $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET LN56 end = eof;
	FILE REPORT30 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT DT_ADJ LD_RPT_CRB MMDDYY10. ;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ  @;
		PUT LC_RPT_STA_CRB  @;
		PUT LD_RPT_CRB @;
		PUT DT_ADJ $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET CUR_DUE end = eof;
	FILE REPORT31 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT cur_due past_due tot_due tot_due_fee 9.2 ;
	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT cur_due @;
		PUT past_due @;
		PUT tot_due @;
		PUT tot_due_fee $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET ARC_M1411 end = eof;
	FILE REPORT32 DELIMITER=',' DSD DROPOVER LRECL=32767;
	IF _N_ = 1 THEN put "-Begin-";
	DO;	
		PUT DF_SPE_ACC_ID @;
		PUT LN_ATY_SEQ @;
		PUT LC_STA_ACTY10 @;
		PUT LX_ATY $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET LN90_HIST end = eof;
	FILE REPORT33 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_FAT_APL LD_FAT_PST LD_FAT_EFF LD_STA_LON90 MMDDYY10. ;
	FORMAT LA_FAT_PCL_FEE LA_FAT_NSI LA_FAT_LTE_FEE LA_FAT_ILG_PRI LA_FAT_CUR_PRI LA_FAT_NSI_ACR 10.2 ;
	IF _N_ = 1 THEN put "-Begin-";
	DO;	
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LN_FAT_SEQ @;
		PUT LC_FAT_REV_REA @;
		PUT LD_FAT_APL @;
		PUT LD_FAT_PST @;
		PUT LD_FAT_EFF @;
		PUT LD_STA_LON90 @;
		PUT LC_STA_LON90 @;
		PUT LA_FAT_PCL_FEE @;
		PUT LA_FAT_NSI @;
		PUT LA_FAT_LTE_FEE @;
		PUT LA_FAT_ILG_PRI @;
		PUT LA_FAT_CUR_PRI @;
		PUT PC_FAT_TYP @;
		PUT PC_FAT_SUB_TYP @;
		PUT LA_FAT_NSI_ACR $;
	end;
	if eof then put "-End-";
RUN;

DATA _NULL_;
	SET LT20 end = eof;
	FILE REPORT34 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT RT_RUN_SRT_DTS_PRC DATETIME25.3 ;

	IF _N_ = 1 THEN put "-Begin-";
	DO;	
		PUT DF_SPE_ACC_ID @;
		PUT RT_RUN_SRT_DTS_PRC @; /*ends up in SQL server as a string because joins on the numeric date value weren't working*/
		PUT RN_SEQ_LTR_CRT_PRC @; 
		PUT RN_SEQ_REC_PRC @;
		PUT RT_RUN_SRT_DTS_PRC @; /*ends up in SQL server as a datetime*/
		PUT RM_DSC_LTR_PRC @;
		PUT RC_TYP_SBJ_PRC @;
		PUT RF_SBJ_PRC @;
		PUT RN_ENT_REQ_PRC @;
		PUT RN_ATY_SEQ_PRC @;
		PUT RI_REC_PRC @;
		PUT RX_REQ_ARA_1_PRC @;
		PUT RI_LTR_REQ_DEL_PRC @;
		PUT RC_LTR_REQ_SRC_PRC @;
		PUT RI_PRV_RUN_ERR_PRC @;
		PUT RF_COR_DOC_PRC @;
		PUT RI_LTR_OPT_ENC_PRC $;
	END;
	IF EOF THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET RP02 end = eof;
	FILE REPORT35 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT PA_BBT_REB 10.2;

	IF _N_ = 1 THEN put "-Begin-";
	DO;	
		PUT DF_SPE_ACC_ID @;
		PUT PM_BBS_PGM @;
		PUT PN_BBS_PGM_SEQ @;
		PUT PF_BBS_PGM_TIR @;
		PUT PN_BBS_PGM_TIR_SEQ @;
		PUT PC_BBT_ICV @;
		PUT PN_BBT_PAY_ICV @;
		PUT PR_BBT_RDC @;
		PUT PC_BBT_REB_APL @;
		PUT PA_BBT_REB $;
	END;
	IF EOF THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET LN54 end = eof;
	FILE REPORT36 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_EFF_BEG_LN54 LD_STA_LN54 LD_BBS_DSQ MMDDYY10.;

	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT PM_BBS_PGM @;
		PUT PN_BBS_PGM_SEQ @;
		PUT LN_LON_BBS_PGM_SEQ @;
		PUT LD_EFF_BEG_LN54 @;
		PUT LI_BBS_ITD_LTR_SNT @;
		PUT LN_BBS_STS_PCV_PAY @;
		PUT LC_BBS_REB_MTD @;
		PUT LC_STA_LN54 @;
		PUT LD_STA_LN54 @;
		PUT LC_BBS_DSQ_REA @;
		PUT LD_BBS_DSQ @;
		PUT LC_BBS_ELG $;
	END;
	IF EOF THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET AD20 end = eof;
	FILE REPORT37 DELIMITER=',' DSD DROPOVER LRECL=32767;
	FORMAT LD_FAT_ADJ_REQ MMDDYY10.;

	IF _N_ = 1 THEN put "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LD_FAT_ADJ_REQ @;
		PUT LN_SEQ_FAT_ADJ_REQ @;
		PUT LC_TYP_FAT_ADJ_REQ @;
		PUT LC_STA_FAT_ADJ_REQ;
	END;
	IF EOF THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET FS12 END = EOF;
	FILE REPORT38 DELIMITER=',' DSD DROPOVER LRECL=32767;

	FORMAT LD_CRT_NEG_AMR_LTR DATE9.;

	IF _N_ = 1 THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LD_CRT_NEG_AMR_LTR @;
		PUT LA_PRJ_NEG_AMR_INT;
	END;
	IF EOF THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET DFR_LTR END = EOF;
	FILE REPORT39 DELIMITER=',' DSD DROPOVER LRECL=32767;

	FORMAT LD_DFR_INF_CER DATE9.;
	FORMAT LD_CRT_REQ_DFR DATE9.;
	FORMAT LD_STA_DFR10 DATE9.;
	FORMAT LF_LST_DTS_DF10 DATETIME25.3;
	FORMAT LD_DFR_BEG DATE9.;
	FORMAT LD_DFR_END DATE9.;
	FORMAT LF_LST_DTS_LN50 DATETIME25.3;
	FORMAT LD_STA_LON50 DATE9.;
	FORMAT LD_DFR_APL DATE9.;

	IF _N_ = 1 THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LF_DFR_CTL_NUM @;
		PUT LN_DFR_OCC_SEQ @;
		PUT LC_DFR_TYP @;
		PUT LD_DFR_INF_CER @;
		PUT LD_CRT_REQ_DFR @;
		PUT LC_DFR_STA @;
		PUT LC_STA_DFR10 @;
		PUT LD_STA_DFR10 @;
		PUT LF_LST_DTS_DF10 @;
		PUT LD_DFR_BEG @;
		PUT LD_DFR_END @;
		PUT LC_STA_LON50 @;
		PUT LC_LON_LEV_DFR_CAP @;
		PUT LF_LST_DTS_LN50 @;
		PUT LD_STA_LON50 @;
		PUT LD_DFR_APL ;
	END;
	IF EOF THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET FOR_LTR END = EOF;
	FILE REPORT40 DELIMITER=',' DSD DROPOVER LRECL=32767;

	FORMAT LD_FOR_INF_CER DATE9.;
	FORMAT LD_CRT_REQ_FOR DATE9.;
	FORMAT LD_STA_FOR10 DATE9.;
	FORMAT LF_LST_DTS_FB10 DATETIME25.3;
	FORMAT LD_FOR_BEG DATE9.;
	FORMAT LD_FOR_END DATE9.;
	FORMAT LF_LST_DTS_LN60 DATETIME25.3;
	FORMAT LD_STA_LON60 DATE9.;
	FORMAT LD_FOR_APL DATE9.;

	IF _N_ = 1 THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LF_FOR_CTL_NUM @;
		PUT LN_FOR_OCC_SEQ @;
		PUT LC_FOR_TYP @;
		PUT LD_FOR_INF_CER @;
		PUT LD_CRT_REQ_FOR @;
		PUT LC_FOR_STA @;
		PUT LC_STA_FOR10 @;
		PUT LD_STA_FOR10 @;
		PUT LF_LST_DTS_FB10 @;
		PUT LD_FOR_BEG @;
		PUT LD_FOR_END @;
		PUT LC_STA_LON60 @;
		PUT LC_LON_LEV_FOR_CAP @;
		PUT LF_LST_DTS_LN60 @;
		PUT LD_STA_LON60 @;
		PUT LD_FOR_APL ;
	END;
	IF EOF THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET REPAY_SUM END = EOF;
	FILE REPORT41 DELIMITER=',' DSD DROPOVER LRECL=32767;

	FORMAT LD_CRT_LON65 DATE9.;
	FORMAT LF_LST_DTS_LN65 DATETIME25.3;
	FORMAT LD_CRT_LON66 DATE9.;
	FORMAT LF_LST_DTS_LN66 DATETIME25.3;
	FORMAT LD_RPS_1_PAY_DU DATE9.;

	IF _N_ = 1 THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LN_RPS_SEQ @;
		PUT LN_GRD_RPS_SEQ @;
		PUT LD_CRT_LON65 @;
		PUT LC_TYP_SCH_DIS @;
		PUT LA_TOT_RPD_DIS @;
		PUT LR_INT_RPD_DIS @;
		PUT LA_ANT_CAP @;
		PUT LC_STA_LON65 @;
		PUT LF_LST_DTS_LN65 @;
		PUT LA_RPS_ISL @;
		PUT LD_CRT_LON66 @;
		PUT LN_RPS_TRM @;
		PUT LF_LST_DTS_LN66 @;
		PUT LD_RPS_1_PAY_DU ;
	END;
	IF EOF THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET RS05 END = EOF;
	FILE REPORT42 DELIMITER=',' DSD DROPOVER LRECL=32767;

	FORMAT BA_AGI BA_PMN_STD_TOT_PAY 12.2;
	FORMAT BD_CRT_RS05 BD_ANV_QLF_IBR DATE9.;

	IF _N_ = 1 THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT BD_CRT_RS05 @;
		PUT BN_IBR_SEQ @;
		PUT BF_CRY_YR @;
		PUT BC_ST_IBR @;
		PUT BC_STA_RS05 @;
		PUT BA_AGI @;
		PUT BN_MEM_HSE_HLD @;
		PUT BA_PMN_STD_TOT_PAY @;
		PUT BC_IBR_INF_SRC_VER @;
		PUT BF_SSN_SPO @;
		PUT BC_IRS_TAX_FIL_STA @;
		PUT BI_JNT_BR_SPO_RPY @;
		PUT BD_ANV_QLF_IBR ;
	END;
	IF EOF THEN PUT "-End-";
RUN;


DATA _NULL_;
	SET SC10 END = EOF;
	FILE REPORT43 DELIMITER=',' DSD DROPOVER LRECL=32767;

	IF _N_ = 1 THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT IF_DOE_SCL @;
		PUT IM_SCL_SHO @;
		PUT IM_SCL_FUL @;
		PUT IC_TYP_SCL @;
		PUT IC_PRV_SCL_STA @;
		PUT IC_CUR_SCL_STA @;
		PUT II_SCL_CHS_PTC @;
		PUT IC_LEN_LNG_PGM_STY ;
	END;
	IF EOF THEN PUT "-End-";
RUN;


DATA _NULL_;
	SET FS14 END = EOF;
	FILE REPORT44 DELIMITER=',' DSD DROPOVER LRECL=32767;

	IF _N_ = 1 THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT LN_SEQ @;
		PUT LN_INC_SUB_EVT_SEQ @;
		PUT LD_INC_SUB_EFF_BEG @;
		PUT LD_INC_SUB_EFF_END @;
		PUT LC_INC_SUB_STA @;
		PUT LR_SUB_RMN @;
		PUT LF_LST_USR_FS14 @;
		PUT LF_LST_DTS_FS14 @;
		PUT LF_CRT_USR_FS14 @;
		PUT LD_CRT_FS14 @;
		PUT LC_STA_FS14 @;
		PUT LD_STA_FS14 ;
	END;
	IF EOF THEN PUT "-End-";
RUN;


DATA _NULL_;
	SET WQ20 END = EOF;
	FILE REPORT45 DELIMITER=',' DSD DROPOVER LRECL=32767;

	IF _N_ = 1 THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @;
		PUT WF_QUE @;
		PUT WF_SUB_QUE @;
		PUT WN_CTL_TSK @;
		PUT PF_REQ_ACT @;
		PUT WD_ACT_REQ @;
		PUT WD_ACT_RQR @;
		PUT WC_CND_CTC @;
		PUT WD_INI_TSK @;
		PUT WT_INI_TSK @;
		PUT WF_USR_ASN_TSK @;
		PUT WF_USR_ASN_BY_TSK @;
		PUT WX_MSG_1_TSK @;
		PUT WX_MSG_2_TSK @;
		PUT WC_STA_WQUE20 @;
		PUT WF_LST_DTS_WQ20 @;
		PUT LN_ATY_SEQ @;
		PUT WF_CRT_DTS_WQ20;
	END;
	IF EOF THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET LN83 END = EOF;
	FILE REPORT46 DELIMITER=',' DSD DROPOVER LRECL=32767;

	IF _N_ = 1 THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @ ;
		PUT LN_SEQ @ ;
		PUT BN_EFT_SEQ @ ;
		PUT LF_EFT_OCC_DTS @ ;
		PUT LF_LST_DTS_LN83 @ ;
		PUT LD_EFT_EFF_BEG @ ;
		PUT LD_EFT_EFF_END @ ;
		PUT LC_EFT_SUS_REA @ ;
		PUT LC_STA_LN83 @ ;
		PUT LR_EFT_RDC @ ;
		PUT LI_EFT_RIR_MNL_OVR @ ;
		PUT LI_EFT_RST @ ;
		PUT LF_LST_USR_LN83 @ ;
		PUT LF_LST_SRC_LN83;
	END;
	IF EOF THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET OW30 END = EOF;
	FILE REPORT47 DELIMITER=',' DSD DROPOVER LRECL=32767;

	IF _N_ = 1 THEN PUT "-Begin-";
	DO;
		PUT IF_LON_SLE @ ;
		PUT IC_LON_SLE_STA @ ;
		PUT IC_LON_SLE_TYP @ ;
		PUT ID_LON_SLE @ ;
		PUT IF_SLL_OWN @ ;
		PUT IM_SLL_CNC_1 @ ;
		PUT IM_SLL_CNC_LST @ ;
		PUT IN_SLL_CNC_PHN_ARA @ ;
		PUT IN_SLL_CNC_PHN_XCH @ ;
		PUT IN_SLL_CNC_PHN_LCL @ ;
		PUT IN_SLL_CNC_PHN_XTN @ ;
		PUT IF_SLL_BND_ISS @ ;
		PUT ID_SLL_LON_SLE_APV @ ;
		PUT IF_BUY_OWN @ ;
		PUT IM_BUY_CNC_1 @ ;
		PUT IM_BUY_CNC_LST @ ;
		PUT IN_BUY_CNC_PHN_ARA @ ;
		PUT IN_BUY_CNC_PHN_XCH @ ;
		PUT IN_BUY_CNC_PHN_LCL @ ;
		PUT IN_BUY_CNC_PHN_XTN @ ;
		PUT IF_BUY_BND_ISS @ ;
		PUT ID_BUY_LON_SLE_APV @ ;
		PUT IM_MKT_CNC_1 @ ;
		PUT IM_MKT_CNC_LST @ ;
		PUT IN_MKT_CNC_PHN_ARA @ ;
		PUT IN_MKT_CNC_PHN_XCH @ ;
		PUT IN_MKT_CNC_PHN_LCL @ ;
		PUT IN_MKT_CNC_PHN_XTN @ ;
		PUT IM_TRF_CNC_1 @ ;
		PUT IM_TRF_CNC_LST @ ;
		PUT IN_TRF_CNC_PHN_ARA @ ;
		PUT IN_TRF_CNC_PHN_XCH @ ;
		PUT IN_TRF_CNC_PHN_LCL @ ;
		PUT IN_TRF_CNC_PHN_XTN @ ;
		PUT IM_LEG_CNC_1 @ ;
		PUT IM_LEG_CNC_LST @ ;
		PUT IN_LEG_CNC_PHN_ARA @ ;
		PUT IN_LEG_CNC_PHN_XCH @ ;
		PUT IN_LEG_CNC_PHN_LCL @ ;
		PUT IN_LEG_CNC_PHN_XTN @ ;
		PUT IC_FEE_ORG_RSB @ ;
		PUT II_ACP_NEW_LON_SLE @ ;
		PUT IA_LON_TOT_MAX @ ;
		PUT II_INT_ICL @ ;
		PUT IN_LON_MAX @ ;
		PUT II_SLE_LTR_TRG @ ;
		PUT IF_SLE_LTR_SPC @ ;
		PUT IF_LST_DTS_OW30 @ ;
		PUT IF_BUY_POR @ ;
		PUT IC_SLL_PNT_LOC @ ;
		PUT IC_BUY_PNT_LOC @ ;
		PUT IC_TIR_PCE_ASN @ ;
		PUT II_LTE_FEE_WOF @ ;
		PUT IC_LON_SLE_SEL_TYP @ ;
		PUT II_LTE_FEE_MAX_VAL @ ;
		PUT II_STP_SLE_LON_MAX @ ;
		PUT II_LEV_BR_LON_ELG @ ;
		PUT IC_SEL_CRI_USR_APV @ ;
		PUT ID_SEL_CRI_USR_APV @ ;
		PUT IF_SEL_CRI_USR_APV @ ;
		PUT ID_SEL_NXT_PLR @ ;
		PUT ID_LON_SLE_LST_PLR @ ;
		PUT IT_SLE_LST_PLR @ ;
		PUT IN_LON_SLE_BR_ELG @ ;
		PUT IN_LON_SLE_LON_ELG @ ;
		PUT IA_CUR_PRI_ELG_LON @ ;
		PUT IA_NSI_ELG_LON @ ;
		PUT IA_LTE_FEE_ELG_LON @ ;
		PUT IN_IVL_SCH_NXT_SLE @ ;
		PUT IC_IVL_SCH_NXT_SLE @ ;
		PUT IN_IVL_SCH_NXT_PLR @ ;
		PUT IC_IVL_SCH_NXT_PLR @ ;
		PUT IX_TRG_FIL_SEL_CRI @ ;
		PUT IC_RGN_RCV_DCV_LON @ ;
		PUT IX_DSC_BUY_OWN @ ;
		PUT LA_BR_PRI_BAL_SLE @ ;
		PUT LC_BR_PRI_REL_SLE @ ;
		PUT II_ORG_RGT_PUR_SLE @ ;
		PUT IF_GRP_SLE_KEY @ ;
		PUT IC_EFT_RIR_RSB @ ;
		PUT IX_LON_SLE_CMT @ ;
		PUT IC_BBS_RSB @ ;
		PUT IC_LON_SLE_SUB_TYP @ ;
		PUT IA_SLE_LVL_TRF_FEE @ ;
		PUT IC_TRF_FEE_TYP @ ;
		PUT IR_PRI_PER_FEE_RTE @ ;
		PUT II_ICL_CON_STP_PUR @ ;
		PUT ID_ECA_DCV_CRT_FIL @ ;
		PUT II_ECA_PUT_DCV_APV @ ;
		PUT ID_ECA_CRT_BIL_SLE @ ;
		PUT ID_CDU_REM_NTF @ ;
		PUT IC_FED_PGM_YR @ ;
		PUT IF_FLS_DEA @ ;
		PUT IF_DEA_IST_LIN_HLD @ ;
		PUT II_LON_SLE_ICL_IDT @ ;
		PUT II_ICL_CON_GRP_RLP @ ;
		PUT LI_PCV_OWN_EFF_DTE @ ;
		PUT II_PRE_SLE_LTR @ ;
		PUT IC_DLA_CAN_LTR @ ;
		PUT IC_PRE_SLE_LST_PRC;
	END;
	IF EOF THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET WK1J END = EOF;
	FILE REPORT48 DELIMITER=',' DSD DROPOVER LRECL=32767;

	IF _N_ = 1 THEN PUT "-Begin-";
	DO;
		PUT IF_LON_SLE @ ;
		PUT ID_LON_SLE_LST_PLR @ ;
		PUT IT_SLE_LST_PLR @ ;
		PUT DF_SPE_ACC_ID @ ;
		PUT LN_SEQ @ ;
		PUT LA_CUR_PRI @ ;
		PUT LA_NSI_OTS @ ;
		PUT LA_LTE_FEE_OTS ;
	END;
	IF EOF THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET LN94 END = EOF;
	FILE REPORT49 DELIMITER=',' DSD DROPOVER LRECL=32767;

	IF _N_ = 1 THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @ ;
		PUT LN_SEQ @ ;
		PUT LN_FAT_SEQ @ ;
		PUT LD_RMT_BCH_INI @ ;
		PUT LC_RMT_BCH_SRC_IPT @ ;
		PUT LN_RMT_BCH_SEQ @ ;
		PUT LN_RMT_SEQ @ ;
		PUT LN_RMT_ITM @ ;
		PUT LN_RMT_ITM_SEQ @ ;
		PUT LF_LST_DTS_LN94 ;
	END;
	IF EOF THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET RM30 END = EOF;
	FILE REPORT50 DELIMITER=',' DSD DROPOVER LRECL=32767;

	IF _N_ = 1 THEN PUT "-Begin-";
	DO;
		PUT LD_RMT_BCH_INI @ ;
		PUT LC_RMT_BCH_SRC_IPT @ ;
		PUT LN_RMT_BCH_SEQ @ ;
		PUT LN_RMT_SEQ @ ;
		PUT LN_RMT_ITM @ ;
		PUT LN_RMT_ITM_SEQ @ ;
		PUT LC_RMT_STA @ ;
		PUT LA_BR_RMT @ ;
		PUT LC_RMT_REV_REA @ ;
		PUT LI_RMT_PD_AHD @ ;
		PUT LD_RMT_PAY_EFF @ ;
		PUT LF_RMT_EDS @ ;
		PUT LF_RMT_IST @ ;
		PUT LX_SPS_REA @ ;
		PUT LD_RMT_SPS @ ;
		PUT LD_RMT_PST @ ;
		PUT LD_UPD_REMT30 @ ;
		PUT LD_CRT_REMT30 @ ;
		PUT LD_RMT_BCH_INI_REV @ ;
		PUT LC_RMT_BCH_IPT_REV @ ;
		PUT LN_RMT_BCH_SEQ_REV @ ;
		PUT LN_RMT_SEQ_REV @ ;
		PUT LN_RMT_ITM_REV @ ;
		PUT LN_RMT_ITM_SEQ_REV @ ;
		PUT LF_LST_DTS_RM30 @ ;
		PUT PC_FAT_TYP @ ;
		PUT PC_FAT_SUB_TYP @ ;
		PUT DF_SPE_ACC_ID @ ;
		PUT LD_BIL_CRT @ ;
		PUT LN_SEQ_BIL_WI_DTE @ ;
		PUT LI_DPS_RMT_PIO_CVN @ ;
		PUT BN_CPN_BK_SEQ @ ;
		PUT LD_BIL_CPN_DU @ ;
		PUT LI_PHD_PAS_DU @ ;
		PUT LI_PHD_PAS_RPS @ ;
		PUT LI_PHD_PAS_OPT @ ;
		PUT LI_PHD_BCH_OVR @ ;
		PUT LC_RMT_REV_REA_REJ @ ;
		PUT LC_STP_SPS_OVR @ ;
		PUT LC_RMT_PAY_SRC @ ;
		PUT LC_RMT_SPS_OVR_FRD @ ;
		PUT LI_DPL_ACC_RMT @ ;
		PUT LC_WAV_MSC_FEE_ASS @ ;
		PUT LD_SCH_RMT_PAY @ ;
		PUT LF_LCK_BOX_TRC @ ;
		PUT LF_BR_RMT_SCH_NUM @ ;
		PUT LC_BR_RMT_SCH_TYP @ ;
		PUT LI_CON_SPS_OVR @ ;
		PUT LD_RMT_SCH_NUM_DPS ;
	END;
	IF EOF THEN PUT "-End-";
RUN;

DATA _NULL_;
	SET LN10 END = EOF;
	FILE REPORT51 DELIMITER=',' DSD DROPOVER LRECL=32767;

	IF _N_ = 1 THEN PUT "-Begin-";
	DO;
		PUT DF_SPE_ACC_ID @ ;
		PUT LN_SEQ @ ;
		PUT LC_STA_LON10 @ ;
		PUT LI_FGV_PGM @ ;
		PUT LF_LON_SLE_PND @ ;
		PUT LA_CUR_PRI @ ;
		PUT LI_ELG_CPN_BOK @ ;
		PUT LA_LON_AMT_GTR @ ;
		PUT LD_LON_GTR @ ;
		PUT LD_PIF_PNT_RTN @ ;
		PUT LD_PNT_SIG @ ;
		PUT LC_INT_BIL_OPT @ ;
		PUT LI_CAP_ALW @ ;
		PUT LD_END_GRC_PRD @ ;
		PUT LN_MTH_GRC_PRD_DSC @ ;
		PUT LA_R78_INT_PD @ ;
		PUT LA_R78_INT_MAX @ ;
		PUT LD_CAP_LST_PIO_CVN @ ;
		PUT LD_TRM_END @ ;
		PUT LD_TRM_BEG @ ;
		PUT LI_GTR_NAT @ ;
		PUT LF_GTR_RFR @ ;
		PUT LI_ELG_SPA @ ;
		PUT LD_GTE_LOS @ ;
		PUT LA_SCL_CLS @ ;
		PUT LA_CUR_ILG @ ;
		PUT LA_ILG @ ;
		PUT LD_PIF_RPT @ ;
		PUT LA_NSI_OTS @ ;
		PUT LD_NSI_ACR_THU @ ;
		PUT LD_STA_LON10 @ ;
		PUT LD_LON_ACL_ADD @ ;
		PUT LD_LON_EFF_ADD @ ;
		PUT LF_DOE_SCL_ORG @ ;
		PUT LC_PCV_DIS_STA @ ;
		PUT LC_RPR_TYP @ ;
		PUT LF_RGL_CAT_LP19 @ ;
		PUT LF_RGL_CAT_LP18 @ ;
		PUT LF_RGL_CAT_LP17 @ ;
		PUT LF_RGL_CAT_LP13 @ ;
		PUT LF_RGL_CAT_LP12 @ ;
		PUT LF_RGL_CAT_LP11 @ ;
		PUT LF_RGL_CAT_LP10 @ ;
		PUT LF_RGL_CAT_LP08 @ ;
		PUT LF_RGL_CAT_LP07 @ ;
		PUT LF_RGL_CAT_LP06 @ ;
		PUT LF_RGL_CAT_LP05 @ ;
		PUT LF_RGL_CAT_LP04 @ ;
		PUT LF_RGL_CAT_LP03 @ ;
		PUT LF_RGL_CAT_LP02 @ ;
		PUT LF_RGL_CAT_LP01 @ ;
		PUT LD_SCL_CLS_NTF @ ;
		PUT LD_ILG_NTF @ ;
		PUT LF_LON_CUR_OWN @ ;
		PUT LF_LST_DTS_LN10 @ ;
		PUT LC_STA_NEW_BR @ ;
		PUT LC_SCY_PGA @ ;
		PUT LD_SIN_LST_PD_PCV @ ;
		PUT LD_SIN_ACR_THU_PCV @ ;
		PUT LA_SIN_OTS_PCV @ ;
		PUT IC_LON_PGM @ ;
		PUT PF_MAJ_BCH @ ;
		PUT PF_MNR_BCH @ ;
		PUT IF_DOE_LDR @ ;
		PUT IF_GTR @ ;
		PUT LF_STU_SSN @ ;
		PUT LD_LON_1_DSB @ ;
		PUT LC_ACA_GDE_LEV @ ;
		PUT LD_NEW_SYS_CVN @ ;
		PUT LC_SCY_PGA_PGM_YR @ ;
		PUT IC_HSP_CSE @ ;
		PUT LI_TL4_793_XCL_CON @ ;
		PUT LI_DFR_REQ_ON_APL @ ;
		PUT LI_LN_PT_COM_APL @ ;
		PUT LN_SEQ_RPR @ ;
		PUT LR_WIR_CON_LON @ ;
		PUT LR_INT_RDC_PGM_DSU @ ;
		PUT LI_1_TME_BR @ ;
		PUT BF_SSN_RPR @ ;
		PUT LC_ELG_RDC_PGM @ ;
		PUT LD_ELG_RDC_PGM @ ;
		PUT LC_RPD_SLE @ ;
		PUT LR_ITR_ORG @ ;
		PUT LC_ITR_TYP_ORG @ ;
		PUT LC_RDC_PGM @ ;
		PUT LC_TIR_GRP @ ;
		PUT LD_SER_RSB_BEG @ ;
		PUT LC_EFT_RDC @ ;
		PUT LD_LTS_STS_BIL @ ;
		PUT IF_TIR_PCE @ ;
		PUT LF_RGL_CAT_LP20 @ ;
		PUT LN_RDC_PGM_PAY_PCV @ ;
		PUT LC_REA_PIF_PCV @ ;
		PUT LD_FAT_PIF_TOL_PCV @ ;
		PUT LA_FAT_PIF_TOL_PCV @ ;
		PUT LI_RTE_RDC_ELG @ ;
		PUT LD_LTE_FEE_ELG @ ;
		PUT LA_LTE_FEE_OTS @ ;
		PUT LD_LON_LTE_FEE_WAV @ ;
		PUT LC_CUR_RDC_PGM_NME @ ;
		PUT LI_RIR_SCY_ELG @ ;
		PUT LD_END_RIR_DSQ_OVR @ ;
		PUT LF_LON_ALT @ ;
		PUT LN_LON_ALT_SEQ @ ;
		PUT LI_LDR_LST_RST_DSB @ ;
		PUT LC_ST_BR_RSD_APL @ ;
		PUT LI_PIF_RPT_REQ @ ;
		PUT LD_AMR_BEG @ ;
		PUT LD_ORG_XPC_GRD @ ;
		PUT LD_CON_LST_RPY_BEG @ ;
		PUT LN_CON_MTH_DFR_FOR @ ;
		PUT LD_LON_APL_RCV @ ;
		PUT LR_SCL_SUB @ ;
		PUT LI_BLL_PAY_SES_OVR @ ;
		PUT LC_MPN_TYP @ ;
		PUT LD_MPN_EXP @ ;
		PUT LC_MPN_SRL_LON @ ;
		PUT LC_MPN_REV_REA @ ;
		PUT LF_ORG_RGN @ ;
		PUT LC_CAM_LON_STA @ ;
		PUT LD_DFR_FOR_END @ ;
		PUT LC_DFR_FOR_TYP @ ;
		PUT LF_CAM_DFR_SCL_ENR @ ;
		PUT LD_DFR_FOR_BEG @ ;
		PUT LD_CAM_DFR_INF_CER @ ;
		PUT LI_BR_DET_RPD_XTN @ ;
		PUT DD_DTH_VER @ ;
		PUT DD_DSA_VER @ ;
		PUT LI_CON_PAY_STP_PUR @ ;
		PUT LD_FSE_CER_NTF @ ;
		PUT LA_TOT_EDU_DET @ ;
		PUT LI_LDR_BG_APL @ ;
		PUT LD_RIR_CSC_BIL_STS @ ;
		PUT LI_ESG @ ;
		PUT LC_RIR_DSQ_REA @ ;
		PUT LF_MN_MST_NTE @ ;
		PUT LN_MN_MST_NTE_SEQ @ ;
		PUT LC_LON_SND_CHC @ ;
		PUT LC_SST_LON10 @ ;
		PUT LF_RGL_CAT_LP09 @ ;
		PUT LI_MN_PSD_BS @ ;
		PUT LF_CRD_RTE_SRE @ ;
		PUT LF_ESG_SRC @ ;
		PUT PC_PNT_YR @ ;
		PUT LF_OWN_BND_ISS_TE1 @ ;
		PUT LF_OWN_BND_ISS_TE2 @ ;
		PUT LF_OWN_BND_ISS_TE3 @ ;
		PUT LD_MPN_STM_SNT @ ;
		PUT LI_MNT_BIL_RCP @ ;
		PUT LX_BS_POI @ ;
		PUT LA_BS_POI @ ;
		PUT LA_INT_FEE_URP_IRS @ ;
		PUT LC_BR_ALW_SCL_DFR @ ;
		PUT LD_BR_ALW_SCL_DFR @ ;
		PUT LC_LON_DFR_SUB_TYP @ ;
		PUT LD_FAT_PRI_BAL_ZRO @ ;
		PUT LC_ST_SCL_ATD_APL @ ;
		PUT LD_EFT_DSQ_NSF_LMT @ ;
		PUT LD_CLM_PD @ ;
		PUT LC_STP_PUR @ ;
		PUT LD_CON_PAY_EFF @ ;
		PUT LD_CON_PAY_APL @ ;
		PUT LC_ESG @ ;
		PUT LC_LON_RPE_CVN_REA @ ;
		PUT LC_UDL_DSB_COF @ ;
		PUT LI_BR_LT_HT @ ;
		PUT LI_ALL_PAY_FLG_SPS @ ;
		PUT LN_MFY_GRS_PAY @ ;
		PUT LC_ESP_RPD_OPT_SEL @ ;
		PUT LC_ELG_95_SPA_BIL @ ;
		PUT LC_SGM_COS_PRC @ ;
		PUT LD_GTR_DR_DCH_CER @ ;
		PUT LD_RPD_ELY_CL_BEG @ ;
		PUT LD_RPD_ELY_CL_END @ ;
		PUT LF_GTR_RFR_XTN @ ;
		PUT LA_MSC_FEE_OTS @ ;
		PUT LA_MSC_FEE_PCV_OTS @ ;
		PUT LF_LON_GRP_WI_BR @ ;
		PUT LC_TL4_IBR_ELG @ ;
		PUT LD_LON_IBR_ENT @ ;
		PUT LC_LON_IBR_RPY_TYP @ ;
		PUT LI_BYP_COL_OUT_SRC @ ;
		PUT LI_BR_GRP_RLP @ ;
		PUT LI_OO_PST_ENR_DFR @ ;
		PUT LD_OO_PST_ENR_DFR @ ;
		PUT LF_FED_CLC_RSK @ ;
		PUT LF_FED_FFY_1_DSB @ ;
		PUT LF_PRV_GTR @ ;
		PUT LC_FED_PGM_YR @ ;
		PUT LA_INT_RCV_GOV @ ;
		PUT LC_WOF_WUP_REA @ ;
		PUT LC_VRS_ALT_APL @ ;
		PUT LF_LON_DCV_CLI @ ;
		PUT LN_LON_SEQ_DCV_CLI @ ;
		PUT LI_EDS_BKR_STP_PUR @ ;
		PUT LF_EDS @ ;
		PUT LD_EFF_LBR_RTE @ ;
		PUT LA_STD_STD_PAY @ ;
		PUT LI_FRC_IBR @ ;
		PUT LC_STP_PUR_REA @ ;
		PUT LD_IDR_ELG_CHG @ ;
		PUT LC_IDR_ELG_CRI ;
	END;
	IF EOF THEN PUT "-End-";
RUN;
