/*TEST*/
/*%LET TESTMSG = - THIS IS A TEST;
%LET RPTLIB = T:\SAS;
%LET LOGLIB = Y:\Batch\Logs;
%LET CODELIB = Y:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS_TEST;
%LET DB = CDW_test;
%LET ODBCFILE_CSYS = CSYSTest;*/

/*LIVE*/
%LET TESTMSG = - THIS IS LIVE;
%LET RPTLIB = Z:\Batch\FTP;
%LET LOGLIB = Z:\Batch\Logs;
%LET CODELIB = Z:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS;
%LET DB = CDW;
%LET ODBCFILE_CSYS = CSYS;

%INCLUDE "&CODELIB\UTNWDW1 CDW DAILY UPDATE.FOLDER AND DATABASE.SAS";
%FILECHECK(3);

DATA BR03(drop=trunc);
INFILE REPORT3 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
INPUT DF_SPE_ACC_ID :$10. DF_PRS_ID_RFR :$9. BC_STA_BR03 :$1. BI_ATH_3_PTY :$1. BC_RFR_REL_BR :$2.
	BM_RFR_1 :$12. BM_RFR_LST :$35. LST_CNC :$10. LST_ATT :$10. ;
	RFR_REL_BR = PUT(BC_RFR_REL_BR, $RFRTYP.);
 %TRUNCAT(3);
RUN;
%COPYERROR;
PROC SORT DATA=BR03; BY DF_SPE_ACC_ID DF_PRS_ID_RFR; RUN;
DATA BR03; SET BR03; BY DF_SPE_ACC_ID DF_PRS_ID_RFR; IF LAST.DF_PRS_ID_RFR; RUN;

%ENCHILADA(BR03,BR03_REFERENCE,DF_SPE_ACC_ID DF_PRS_ID_RFR,BC_STA_BR03 BI_ATH_3_PTY BC_RFR_REL_BR RFR_REL_BR BM_RFR_1
	BM_RFR_LST LST_CNC LST_ATT,WHERE BC_STA_BR03 = 'A');

%GOODBYE_NULL(BR03_REFERENCE,BC_STA_BR03,'');
%GOODBYE_NULL(BR03_REFERENCE,BI_ATH_3_PTY,'');
%GOODBYE_NULL(BR03_REFERENCE,BM_RFR_1,'');
%GOODBYE_NULL(BR03_REFERENCE,BM_RFR_LST,'');
%GOODBYE_NULL(BR03_REFERENCE,LST_CNC,'');
%GOODBYE_NULL(BR03_REFERENCE,LST_ATT,'');
%GOODBYE_NULL(BR03_REFERENCE,RFR_REL_BR,''); 
%GOODBYE_NULL(BR03_REFERENCE,BC_RFR_REL_BR,''); 

%FINISH(SOURCE=Reference);
