/*TEST*/
/*%LET TESTMSG = - THIS IS A TEST;
%LET RPTLIB = T:\SAS;
%LET LOGLIB = Y:\Batch\Logs;
%LET CODELIB = Y:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS_TEST;
%LET DB = CDW_test;
%LET ODBCFILE_CSYS = CSYSTest;*/

/*LIVE*/
%LET TESTMSG = - THIS IS LIVE;
%LET RPTLIB = Z:\Batch\FTP;
%LET LOGLIB = Z:\Batch\Logs;
%LET CODELIB = Z:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS;
%LET DB = CDW;
%LET ODBCFILE_CSYS = CSYS;

%INCLUDE "&CODELIB\UTNWDW1 CDW DAILY UPDATE.FOLDER AND DATABASE.SAS";
%FILECHECK(43);

options mprint;

DATA SC10 (drop=trunc);
	INFILE REPORT43 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
	INPUT 
		DF_SPE_ACC_ID :$10. 
		IF_DOE_SCL :$8. 
		IM_SCL_SHO :$20.
		IM_SCL_FUL :$40. 
		IC_TYP_SCL :$2. 
/*		TYPE_DESCRIPTION :$17. */
		IC_PRV_SCL_STA :$1.
		IC_CUR_SCL_STA :$1. 
		II_SCL_CHS_PTC :$1. 
		IC_LEN_LNG_PGM_STY :$2. ;
		SchoolTypeDescrption = PUT(IC_TYP_SCL,$SCLTYP.)
;
%TRUNCAT(43);
RUN;
%COPYERROR;

%ENCHILADA(
			SC10,
			SC10_SchoolDemos,
			DF_SPE_ACC_ID IF_DOE_SCL,
			IM_SCL_SHO 
			IM_SCL_FUL
			IC_TYP_SCL 
			SchoolTypeDescrption 
			IC_PRV_SCL_STA 
			IC_CUR_SCL_STA 
			II_SCL_CHS_PTC 
			IC_LEN_LNG_PGM_STY  
		);
		
%FINISH(SOURCE=SchoolDemos);

