/*TEST*/
/*%LET TESTMSG = - THIS IS A TEST;
%LET RPTLIB = T:\SAS;
%LET LOGLIB = Y:\Batch\Logs;
%LET CODELIB = Y:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS_TEST;
%LET DB = CDW_test;
%LET ODBCFILE_CSYS = CSYSTest;*/

/*LIVE*/
%LET TESTMSG = - THIS IS LIVE;
%LET RPTLIB = Z:\Batch\FTP;
%LET LOGLIB = Z:\Batch\Logs;
%LET CODELIB = Z:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS;
%LET DB = CDW;
%LET ODBCFILE_CSYS = CSYS;

%INCLUDE "&CODELIB\UTNWDW1 CDW DAILY UPDATE.FOLDER AND DATABASE.SAS";
%FILECHECK(24);

DATA RM31(drop=trunc);
	INFILE REPORT24 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
	INPUT DF_SPE_ACC_ID :$10. LA_BR_RMT_PST :8.2 ;
%TRUNCAT(24);
RUN;
%COPYERROR;
PROC SORT DATA=RM31 ; BY DF_SPE_ACC_ID ; RUN;
DATA RM31; SET RM31; BY DF_SPE_ACC_ID; IF LAST.DF_SPE_ACC_ID; RUN;

%ENCHILADA(RM31,RM31_SUSPENSE,DF_SPE_ACC_ID,LA_BR_RMT_PST,);

%GOODBYE_NULL(RM31_SUSPENSE,LA_BR_RMT_PST,0);

%FINISH(SOURCE=Suspense);
