/*TEST*/
/*%LET TESTMSG = - THIS IS A TEST;
%LET RPTLIB = T:\SAS;
%LET LOGLIB = Y:\Batch\Logs;
%LET CODELIB = Y:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS_TEST;
%LET DB = CDW_test;
%LET ODBCFILE_CSYS = CSYSTest;*/

/*LIVE*/
%LET TESTMSG = - THIS IS LIVE;
%LET RPTLIB = Z:\Batch\FTP;
%LET LOGLIB = Z:\Batch\Logs;
%LET CODELIB = Z:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS;
%LET DB = CDW;
%LET ODBCFILE_CSYS = CSYS;


%INCLUDE "&CODELIB\UTNWDW1 CDW DAILY UPDATE.FOLDER AND DATABASE.SAS";
%FILECHECK(44);

options mprint;

DATA FS14 (drop=trunc);
	INFILE REPORT44 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
	INPUT 
		DF_SPE_ACC_ID :$10. 
		LN_SEQ :4. 
		LN_INC_SUB_EVT_SEQ :8.
		LD_INC_SUB_EFF_BEG :DATE9. 
		LD_INC_SUB_EFF_END :DATE9.
		LC_INC_SUB_STA :$1. 
		LR_SUB_RMN :10.2
		LF_LST_USR_FS14 :$12. 
		LF_LST_DTS_FS14 :DATETIME25. 
		LF_CRT_USR_FS14 :$12.
		LD_CRT_FS14 :DATE9. 
		LC_STA_FS14 :$1.
		LD_STA_FS14 :DATE9. 
		
;
%TRUNCAT(44);
RUN;
%COPYERROR;

DATA FS14_FINAL;
SET FS14;
	LD_INC_SUB_EFF_BEG = LD_INC_SUB_EFF_BEG*86400;
	LD_INC_SUB_EFF_END = LD_INC_SUB_EFF_END*86400;
	LD_CRT_FS14 = LD_CRT_FS14*86400;
	LD_STA_FS14 = LD_STA_FS14*86400;
RUN;

%ENCHILADA(
			FS14_FINAL,
			FS14_LoanSubsidy,
			DF_SPE_ACC_ID LN_SEQ LN_INC_SUB_EVT_SEQ,
			LD_INC_SUB_EFF_BEG 
			LD_INC_SUB_EFF_END
			LC_INC_SUB_STA 
			LR_SUB_RMN 
			LF_LST_USR_FS14 
			LF_LST_DTS_FS14 
			LF_CRT_USR_FS14 
			LD_CRT_FS14
			LC_STA_FS14
 			LD_STA_FS14
		);

%FINISH(SOURCE=LoanSubsidy);

