/*TEST*/
/*%LET TESTMSG = - THIS IS A TEST;
%LET RPTLIB = T:\SAS;
%LET LOGLIB = Y:\Batch\Logs;
%LET CODELIB = Y:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS_TEST;
%LET DB = CDW_test;
%LET ODBCFILE_CSYS = CSYSTest;*/

/*LIVE*/
%LET TESTMSG = - THIS IS LIVE;
%LET RPTLIB = Z:\Batch\FTP;
%LET LOGLIB = Z:\Batch\Logs;
%LET CODELIB = Z:\Codebase\SAS\CDW;
%LET ODBCFILE = BSYS;
%LET DB = CDW;
%LET ODBCFILE_CSYS = CSYS;

%INCLUDE "&CODELIB\UTNWDW1 CDW DAILY UPDATE.FOLDER AND DATABASE.SAS";
%FILECHECK(12);

DATA LN83(drop=trunc);
      INFILE REPORT12 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
      INPUT DF_SPE_ACC_ID :$10. LN_SEQ :6. BN_EFT_SEQ :6. LC_STA_LN83 :$1. 	;
%TRUNCAT(12);
RUN;
%COPYERROR;
PROC SORT DATA=LN83; BY DF_SPE_ACC_ID LN_SEQ BN_EFT_SEQ; RUN;
DATA LN83; SET LN83(drop=bn_eft_seq); BY DF_SPE_ACC_ID LN_SEQ; IF LAST.LN_SEQ; RUN;

%ENCHILADA(LN83,LN83_EFTSTATUS,DF_SPE_ACC_ID LN_SEQ,LC_STA_LN83,WHERE LC_STA_LN83 = 'A');

%GOODBYE_NULL(LN83_EFTSTATUS,LC_STA_LN83,'');

%FINISH(SOURCE=EFT);
