/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/UNWS13.NWS13RZ";
FILENAME REPORT2 "&RPTLIB/UNWS13.NWS13R2";

LIBNAME  WORKLOCL  REMOTE  SERVER=LEGEND SLIBREF=work  ;
RSUBMIT;
/*%let DB = DNFPRQUT;  *This is test;*/
/*%let DB = DNFPRUUT;  *This is VUK3 test;*/
%let DB = DNFPUTDL;  *This is live;
LIBNAME pkub DB2 DATABASE=DNFPUTDL OWNER=pkub;

PROC SQL ;
CONNECT TO DB2 (DATABASE=&DB);
CREATE TABLE EXIT_IN_TEN AS
/*	SELECT	**/
/*	FROM	CONNECTION TO DB2 (*/
		SELECT DISTINCT PD10.DF_SPE_ACC_ID,
			PD10.DM_PRS_1,
			PD10.DM_PRS_LST,
			COALESCE(PD32A.DX_ADR_EML,COALESCE(PD32B.DX_ADR_EML,COALESCE(PD32C.DX_ADR_EML,' '))) AS DX_ADR_EML,
			COALESCE(GRACE.END_DATE,COALESCE(DFR.END_DATE,FRB.END_DATE)) AS END_DATE,
			LN10.BF_SSN,
			LN10.LN_SEQ
		FROM PKUB.LN10_LON LN10
			INNER JOIN PKUB.PD10_PRS_NME PD10
				ON LN10.BF_SSN = PD10.DF_PRS_ID
			LEFT OUTER JOIN PKUB.AY10_BR_LON_ATY AY10
				ON LN10.BF_SSN = AY10.BF_SSN
				AND AY10.PF_REQ_ACT = 'ERPMT'
				AND AY10.LD_ATY_REQ_RCV > TODAY() - 10
			LEFT OUTER JOIN PKUB.PD32_PRS_ADR_EML PD32A
				ON LN10.BF_SSN = PD32A.DF_PRS_ID
				AND PD32A.DC_ADR_EML = 'H'
				AND PD32A.DC_STA_PD32 = 'A'
				AND PD32A.DI_VLD_ADR_EML = 'Y'
			LEFT OUTER JOIN PKUB.PD32_PRS_ADR_EML PD32B
				ON LN10.BF_SSN = PD32B.DF_PRS_ID
				AND PD32B.DC_ADR_EML = 'A'
				AND PD32B.DC_STA_PD32 = 'A'
				AND PD32B.DI_VLD_ADR_EML = 'Y'
			LEFT OUTER JOIN PKUB.PD32_PRS_ADR_EML PD32C
				ON LN10.BF_SSN = PD32C.DF_PRS_ID
				AND PD32C.DC_ADR_EML = 'W'
				AND PD32C.DC_STA_PD32 = 'A'
				AND PD32C.DI_VLD_ADR_EML = 'Y'
			LEFT OUTER JOIN PKUB.LN50_BR_DFR_APV LN50
				ON LN10.BF_SSN = LN50.BF_SSN
				AND LN10.LN_SEQ = LN50.LN_SEQ
			LEFT OUTER JOIN PKUB.LN60_BR_FOR_APV LN60
				ON	LN10.BF_SSN = LN60.BF_SSN
				AND	LN10.LN_SEQ = LN60.LN_SEQ
			LEFT OUTER JOIN (SELECT	LN10G.BF_SSN,
									LN10G.LN_SEQ,
									LN10G.LD_END_GRC_PRD AS END_DATE
							FROM	PKUB.LN10_LON LN10G
							WHERE 	LN10G.LD_END_GRC_PRD BETWEEN TODAY() AND TODAY() + 10) GRACE
				ON LN10.BF_SSN = GRACE.BF_SSN
				AND LN10.LN_SEQ = GRACE.LN_SEQ
			LEFT OUTER JOIN (SELECT LN50D.BF_SSN,
									LN50D.LN_SEQ,
									LN50D.LD_DFR_END AS END_DATE
							FROM	PKUB.LN50_BR_DFR_APV LN50D
								INNER JOIN	PKUB.DF10_BR_DFR_REQ DF10
									ON LN50D.BF_SSN = DF10.BF_SSN
									AND LN50D.LF_DFR_CTL_NUM = DF10.LF_DFR_CTL_NUM
							WHERE	LN50D.LC_STA_LON50 = 'A'
							AND 	DF10.LC_DFR_STA = 'A'
							AND 	DF10.LC_STA_DFR10 = 'A'
							AND 	LN50D.LD_DFR_END BETWEEN TODAY() AND TODAY() + 10) DFR
				ON 	LN10.BF_SSN = DFR.BF_SSN
				AND LN10.LN_SEQ = DFR.LN_SEQ	
			LEFT OUTER JOIN (SELECT	LN60F.BF_SSN,
									LN60F.LN_SEQ,
									LN60F.LD_FOR_END AS END_DATE
							FROM	PKUB.LN60_BR_FOR_APV LN60F
								INNER JOIN	PKUB.FB10_BR_FOR_REQ FB10
									ON LN60F.BF_SSN = FB10.BF_SSN
									AND LN60F.LF_FOR_CTL_NUM = FB10.LF_FOR_CTL_NUM
							WHERE	LN60F.LC_STA_LON60 = 'A'
							AND 	FB10.LC_FOR_STA = 'A'
							AND 	FB10.LC_STA_FOR10 = 'A'
							AND 	LN60F.LD_FOR_END BETWEEN TODAY() AND TODAY() + 10
							AND 	FB10.LC_FOR_TYP NOT IN ('09','13','14','28','43')) FRB
				ON 	LN10.BF_SSN = FRB.BF_SSN
				AND	LN10.LN_SEQ = FRB.LN_SEQ
		WHERE 	(GRACE.BF_SSN IS NOT NULL 
				OR
				DFR.BF_SSN IS NOT NULL
				OR
				FRB.BF_SSN IS NOT NULL)
			AND	LN10.LC_STA_LON10 = 'R'
			AND LN10.LA_CUR_PRI > 0
			AND AY10.BF_SSN IS NULL
			AND (PD32A.DF_PRS_ID IS NOT NULL
				OR 
				PD32B.DF_PRS_ID IS NOT NULL
				OR 
				PD32C.DF_PRS_ID IS NOT NULL)
			;

CREATE TABLE FINAL AS
	SELECT DISTINCT	ET.DF_SPE_ACC_ID,
			ET.DM_PRS_1,
			ET.DM_PRS_LST,
			ET.DX_ADR_EML
	FROM EXIT_IN_TEN ET
		LEFT OUTER JOIN(SELECT ETA.BF_SSN
						FROM EXIT_IN_TEN ETA
						 	INNER JOIN PKUB.LN50_BR_DFR_APV LN50
							ON 	ETA.BF_SSN = LN50.BF_SSN
							AND ETA.LN_SEQ = LN50.LN_SEQ
						WHERE	LN50.LD_DFR_BEG BETWEEN TODAY() AND ETA.END_DATE + 30) DB
		ON ET.BF_SSN = DB.BF_SSN
		LEFT OUTER JOIN(SELECT ETB.BF_SSN
						FROM EXIT_IN_TEN ETB
						 	INNER JOIN PKUB.LN60_BR_FOR_APV LN60
							ON 	ETB.BF_SSN = LN60.BF_SSN
							AND ETB.LN_SEQ = LN60.LN_SEQ
						WHERE	LN60.LD_FOR_BEG BETWEEN TODAY() AND ETB.END_DATE + 30) FB
		ON ET.BF_SSN = FB.BF_SSN
	WHERE 	DB.BF_SSN IS NULL
		AND FB.BF_SSN IS NULL
		;
/*DISCONNECT FROM DB2;*/

/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>> ;  ** INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK;*/
QUIT;
ENDRSUBMIT;

DATA FINAL; 
SET LEGEND.FINAL;
RUN;

PROC SORT DATA=FINAL;
	BY DF_SPE_ACC_ID;
RUN;

/*write to comma delimited file*/
DATA _NULL_;
	SET		WORK.FINAL;
	FILE
		REPORT2
		DELIMITER = ','
		DSD
		DROPOVER
		LRECL = 32767
	;
	/* write column names, remove this to create a file without a header row */
	IF _N_ = 1 THEN
		DO;
			PUT	
				'DF_SPE_ACC_ID'
				','
				'DM_PRS_1'
				','
				'DM_PRS_LST'
				','
				'DX_ADR_EML'
			;
		END;

	/* write data*/	
	DO;
		PUT DF_SPE_ACC_ID $ @;
		PUT DM_PRS_1 $ @;
		PUT DM_PRS_LST $ @;
		PUT DX_ADR_EML $;
		;
	END;
RUN;
