/*THIS SPECIFICIES WHAT DIRECTORY TO READ REPORTS FROM AND WHICH DATABASE TO UPDATE.*/
/*LIVE*/
%INCLUDE "X:\Sessions\Local SAS Schedule\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas";
%LET REPORT = X:\PADD\FTP;

/*TEST*/
/*%INCLUDE "X:\PADU\SAS\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas" ;
%LET REPORT = T:\SAS;*/


%FILECHECK(53);

DATA GU10;
	INFILE REPORT53 DSD DLM = ',' FIRSTOBS=1 MISSOVER END = EOF;
	INPUT
		IF_GTR :$7.
		IF_ACC_EFT_GTR :$17.
		IF_ABA_EFT_GTR :$9.
		IM_GTR_SHO :$20.
		IM_GTR_FUL :$40.
		II_RPT_GTR_SCL :1.
		II_RPT_GTR_LDR :1.
		II_ASN_RFR_NUM :1.
		IC_RPT_DSB_TYP :$1.
		II_GTR_NAT_PTC :$1.
		IF_LST_USR_GU10 :$8.
		IF_LST_DTS_GU10 :DATETIME25.
		IF_GTR_PRN :$6.
		IC_GTR_TYP :$1.
		II_GTR_PRE_DSB_M :$1.
		II_GTR_NOG_REQ :$1.
		II_GTR_CNL_PTC :$1.
		II_GTR_MNF_DSB_RSN :$1.
		IC_GTR_FEE_RPT_MTH :$1.
		II_RAL_SCY_OVR :$1.
		II_GTR_ALW_PSB_MPN :$1.
		II_GTR_CHS_PTC :$1.
		II_GTR_VER_FEE_RQR :$1.
		II_GTR_WHL_DOL_DSB :$1.

	;
	%TRUNCAT(53, IF_GTR);
RUN;
%copyerror;

PROC SORT DATA=GU10; BY IF_GTR ; RUN;

%ENCHILADA
	(
		GU10,
		GU10_GTR,
		IF_GTR,  
		IF_ACC_EFT_GTR  
		IF_ABA_EFT_GTR  
		IM_GTR_SHO  
		IM_GTR_FUL  
		II_RPT_GTR_SCL  
		II_RPT_GTR_LDR  
		II_ASN_RFR_NUM  
		IC_RPT_DSB_TYP  
		II_GTR_NAT_PTC  
		IF_LST_USR_GU10  
		IF_LST_DTS_GU10  
		IF_GTR_PRN  
		IC_GTR_TYP  
		II_GTR_PRE_DSB_M  
		II_GTR_NOG_REQ  
		II_GTR_CNL_PTC  
		II_GTR_MNF_DSB_RSN  
		IC_GTR_FEE_RPT_MTH  
		II_RAL_SCY_OVR  
		II_GTR_ALW_PSB_MPN  
		II_GTR_CHS_PTC  
		II_GTR_VER_FEE_RQR  
		II_GTR_WHL_DOL_DSB 
	)
;

%FINISH;
