/*THIS SPECIFICIES WHAT DIRECTORY TO READ REPORTS FROM AND WHICH DATABASE TO UPDATE.*/
/*LIVE*/
%INCLUDE "X:\Sessions\Local SAS Schedule\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas";
%LET REPORT = X:\PADD\FTP;

/*TEST*/
/*%INCLUDE "X:\PADU\SAS\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas" ;
%LET REPORT = T:\SAS;*/


%FILECHECK(33);

DATA M1411(drop=trunc);
	INFILE REPORT33 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
	INPUT DF_SPE_ACC_ID :$10. LN_ATY_SEQ :6. LC_STA_ACTY10 :$1. LX_ATY :$360. ;
%TRUNCAT(33,DF_SPE_ACC_ID);
RUN;
%copyerror;

PROC SORT DATA=M1411 ; BY DF_SPE_ACC_ID LN_ATY_SEQ; RUN;
DATA M1411; SET M1411; BY DF_SPE_ACC_ID LN_ATY_SEQ; IF LAST.LN_ATY_SEQ; RUN;

%ENCHILADA(M1411,AY10_M1411,DF_SPE_ACC_ID LN_ATY_SEQ,LC_STA_ACTY10 LX_ATY,WHERE LC_STA_ACTY10 = 'A');

%GOODBYE_NULL(AY10_M1411,LX_ATY,'');

%FINISH;
