/*THIS SPECIFICIES WHAT DIRECTORY TO READ REPORTS FROM AND WHICH DATABASE TO UPDATE.*/
/*LIVE*/
%INCLUDE "X:\Sessions\Local SAS Schedule\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas";
%LET REPORT = X:\PADD\FTP;

/*TEST*/
/*%INCLUDE "X:\PADU\SAS\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas" ;
%LET REPORT = T:\SAS;*/

%FILECHECK(21);

DATA BR02(drop=trunc);
	INFILE REPORT21 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
	INPUT DF_SPE_ACC_ID :$10. IM_IST_FUL :$40. IX_GEN_STR_ADR_1 :$40.
		 IX_GEN_STR_ADR_2 :$40. IM_GEN_CT :$30. IC_GEN_ST :$2.
		 IF_GEN_ZIP :$14. IN_GEN_PHN :$17. ;
%TRUNCAT(21,DF_SPE_ACC_ID);
RUN;
%copyerror;

PROC SORT DATA=BR02 ; BY DF_SPE_ACC_ID; RUN;
DATA BR02; SET BR02; BY DF_SPE_ACC_ID; IF LAST.DF_SPE_ACC_ID; RUN;

%ENCHILADA(BR02,BR02_EMPLOYER,DF_SPE_ACC_ID,IM_IST_FUL IX_GEN_STR_ADR_1 IX_GEN_STR_ADR_2 IM_GEN_CT IC_GEN_ST IF_GEN_ZIP IN_GEN_PHN,);

%GOODBYE_NULL(BR02_EMPLOYER,IM_IST_FUL,'');
%GOODBYE_NULL(BR02_EMPLOYER,IX_GEN_STR_ADR_1,'');
%GOODBYE_NULL(BR02_EMPLOYER,IX_GEN_STR_ADR_2,'');
%GOODBYE_NULL(BR02_EMPLOYER,IM_GEN_CT,'');
%GOODBYE_NULL(BR02_EMPLOYER,IC_GEN_ST,'');
%GOODBYE_NULL(BR02_EMPLOYER,IF_GEN_ZIP,'');
%GOODBYE_NULL(BR02_EMPLOYER,IN_GEN_PHN,'');

%FINISH;
