/*THIS SPECIFICIES WHAT DIRECTORY TO READ REPORTS FROM AND WHICH DATABASE TO UPDATE.*/
/*LIVE*/
%INCLUDE "X:\Sessions\Local SAS Schedule\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas";
%LET REPORT = X:\PADD\FTP;

/*TEST*/
/*%INCLUDE "X:\PADU\SAS\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas" ;
%LET REPORT = T:\SAS;*/

%FILECHECK(5);

DATA LN90(drop=trunc);
INFILE REPORT5 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
INPUT DF_SPE_ACC_ID :$10. LN_SEQ :6. LN_FAT_SEQ :6. LD_FAT_PST :$10. 
	LD_FAT_EFF :$10. LC_STA_LON90 :$1. LA_FAT_CUR_PRI :10.2 LA_FAT_LTE_FEE :9.2 
	PC_FAT_TYP :$2. PC_FAT_SUB_TYP :$2. LA_FAT_NSI :7.2
	LC_FAT_REV_REA :$1. ;
	FAT_REV_REA = PUT(LC_FAT_REV_REA,$REVREA.);
%TRUNCAT(5,DF_SPE_ACC_ID);
RUN;
%copyerror;

PROC SORT DATA=LN90; BY DF_SPE_ACC_ID LN_SEQ LN_FAT_SEQ ; RUN;
DATA LN90; SET LN90; BY DF_SPE_ACC_ID LN_SEQ LN_FAT_SEQ; IF LAST.LN_FAT_SEQ; RUN;

%ENCHILADA(LN90,LN90_FINANCIALTRAN,DF_SPE_ACC_ID LN_SEQ LN_FAT_SEQ,LD_FAT_PST LD_FAT_EFF LC_STA_LON90 LA_FAT_CUR_PRI
	LA_FAT_LTE_FEE PC_FAT_TYP PC_FAT_SUB_TYP LC_FAT_REV_REA FAT_REV_REA LA_FAT_NSI,WHERE LC_STA_LON90 = 'A');

%GOODBYE_NULL(LN90_FINANCIALTRAN,LD_FAT_PST,'');
%GOODBYE_NULL(LN90_FINANCIALTRAN,LD_FAT_EFF,'');
%GOODBYE_NULL(LN90_FINANCIALTRAN,LC_FAT_REV_REA,'');
%GOODBYE_NULL(LN90_FINANCIALTRAN,FAT_REV_REA,'');

%FINISH;
