/*THIS SPECIFICIES WHAT DIRECTORY TO READ REPORTS FROM AND WHICH DATABASE TO UPDATE.*/
/*LIVE*/
%INCLUDE "X:\Sessions\Local SAS Schedule\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas";
%LET REPORT = X:\PADD\FTP;

/*TEST*/
/*%INCLUDE "X:\PADU\SAS\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas" ;
%LET REPORT = T:\SAS;*/

%FILECHECK(16);

DATA LN55(drop=trunc);
	INFILE REPORT16 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
	INPUT DF_SPE_ACC_ID :$10. LN_SEQ :6. LN_LON_BBT_PAY :4. 	
		PN_BBT_PAY_ICV : ;
	RIR_CT = TRIM(LEFT(PUT(COALESCE(LN_LON_BBT_PAY,0),2.0))) || '/' || 
		LEFT(PUT(PN_BBT_PAY_ICV,2.));
%TRUNCAT(16,DF_SPE_ACC_ID);
RUN;
%copyerror;

PROC SORT DATA=LN55 ; BY DF_SPE_ACC_ID LN_SEQ; RUN;
DATA LN55;SET LN55;BY DF_SPE_ACC_ID LN_SEQ;IF LAST.LN_SEQ ;RUN;

%ENCHILADA(LN55,LN55_BENEFIT,DF_SPE_ACC_ID LN_SEQ,LN_LON_BBT_PAY PN_BBT_PAY_ICV RIR_CT,);

%GOODBYE_NULL(LN55_BENEFIT,LN_LON_BBT_PAY,0);
%GOODBYE_NULL(LN55_BENEFIT,PN_BBT_PAY_ICV,0);

%FINISH;
