/*THIS SPECIFICIES WHAT DIRECTORY TO READ REPORTS FROM AND WHICH DATABASE TO UPDATE.*/
/*LIVE*/
%INCLUDE "X:\Sessions\Local SAS Schedule\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas";
%LET REPORT = X:\PADD\FTP;

/*TEST*/
/*%INCLUDE "X:\PADU\SAS\UDW\UTLWDW1 UHEAA Data Warehouse Load.Folder and Database.sas" ;
%LET REPORT = T:\SAS;*/

%FILECHECK(15);

DATA LN54(drop=trunc);
      INFILE REPORT15 DSD DLM = ',' FIRSTOBS=1 MISSOVER end = eof;
      INPUT DF_SPE_ACC_ID :$10. LN_SEQ :6. LD_BBS_DSQ :$10. 
		LC_BBS_ELG :$1. ;
%TRUNCAT(15,DF_SPE_ACC_ID);
RUN;
%copyerror;

PROC SORT DATA=LN54 ; BY DF_SPE_ACC_ID LN_SEQ; RUN;
DATA LN54; SET LN54; BY DF_SPE_ACC_ID LN_SEQ; IF LAST.LN_SEQ ; RUN;

%ENCHILADA(LN54,LN54_ELIGIBILITY,DF_SPE_ACC_ID LN_SEQ,LD_BBS_DSQ LC_BBS_ELG,);

%GOODBYE_NULL(LN54_ELIGIBILITY,LD_BBS_DSQ,'');
%GOODBYE_NULL(LN54_ELIGIBILITY,LC_BBS_ELG,'');

%FINISH;
