'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DataSet1
    Inherits DataSet
    
    Private tablelstFunctions As lstFunctionsDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("lstFunctions")) Is Nothing) Then
                Me.Tables.Add(New lstFunctionsDataTable(ds.Tables("lstFunctions")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property lstFunctions As lstFunctionsDataTable
        Get
            Return Me.tablelstFunctions
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DataSet1 = CType(MyBase.Clone,DataSet1)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("lstFunctions")) Is Nothing) Then
            Me.Tables.Add(New lstFunctionsDataTable(ds.Tables("lstFunctions")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tablelstFunctions = CType(Me.Tables("lstFunctions"),lstFunctionsDataTable)
        If (Not (Me.tablelstFunctions) Is Nothing) Then
            Me.tablelstFunctions.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DataSet1"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DataSet1.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tablelstFunctions = New lstFunctionsDataTable
        Me.Tables.Add(Me.tablelstFunctions)
    End Sub
    
    Private Function ShouldSerializelstFunctions() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub lstFunctionsRowChangeEventHandler(ByVal sender As Object, ByVal e As lstFunctionsRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class lstFunctionsDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnFunctionName As DataColumn
        
        Private columnDescription As DataColumn
        
        Friend Sub New()
            MyBase.New("lstFunctions")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property FunctionNameColumn As DataColumn
            Get
                Return Me.columnFunctionName
            End Get
        End Property
        
        Friend ReadOnly Property DescriptionColumn As DataColumn
            Get
                Return Me.columnDescription
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As lstFunctionsRow
            Get
                Return CType(Me.Rows(index),lstFunctionsRow)
            End Get
        End Property
        
        Public Event lstFunctionsRowChanged As lstFunctionsRowChangeEventHandler
        
        Public Event lstFunctionsRowChanging As lstFunctionsRowChangeEventHandler
        
        Public Event lstFunctionsRowDeleted As lstFunctionsRowChangeEventHandler
        
        Public Event lstFunctionsRowDeleting As lstFunctionsRowChangeEventHandler
        
        Public Overloads Sub AddlstFunctionsRow(ByVal row As lstFunctionsRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddlstFunctionsRow(ByVal FunctionName As String, ByVal Description As String) As lstFunctionsRow
            Dim rowlstFunctionsRow As lstFunctionsRow = CType(Me.NewRow,lstFunctionsRow)
            rowlstFunctionsRow.ItemArray = New Object() {FunctionName, Description}
            Me.Rows.Add(rowlstFunctionsRow)
            Return rowlstFunctionsRow
        End Function
        
        Public Function FindByFunctionName(ByVal FunctionName As String) As lstFunctionsRow
            Return CType(Me.Rows.Find(New Object() {FunctionName}),lstFunctionsRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As lstFunctionsDataTable = CType(MyBase.Clone,lstFunctionsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New lstFunctionsDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnFunctionName = Me.Columns("FunctionName")
            Me.columnDescription = Me.Columns("Description")
        End Sub
        
        Private Sub InitClass()
            Me.columnFunctionName = New DataColumn("FunctionName", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnFunctionName)
            Me.columnDescription = New DataColumn("Description", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDescription)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnFunctionName}, true))
            Me.columnFunctionName.AllowDBNull = false
            Me.columnFunctionName.Unique = true
        End Sub
        
        Public Function NewlstFunctionsRow() As lstFunctionsRow
            Return CType(Me.NewRow,lstFunctionsRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New lstFunctionsRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(lstFunctionsRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.lstFunctionsRowChangedEvent) Is Nothing) Then
                RaiseEvent lstFunctionsRowChanged(Me, New lstFunctionsRowChangeEvent(CType(e.Row,lstFunctionsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.lstFunctionsRowChangingEvent) Is Nothing) Then
                RaiseEvent lstFunctionsRowChanging(Me, New lstFunctionsRowChangeEvent(CType(e.Row,lstFunctionsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.lstFunctionsRowDeletedEvent) Is Nothing) Then
                RaiseEvent lstFunctionsRowDeleted(Me, New lstFunctionsRowChangeEvent(CType(e.Row,lstFunctionsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.lstFunctionsRowDeletingEvent) Is Nothing) Then
                RaiseEvent lstFunctionsRowDeleting(Me, New lstFunctionsRowChangeEvent(CType(e.Row,lstFunctionsRow), e.Action))
            End If
        End Sub
        
        Public Sub RemovelstFunctionsRow(ByVal row As lstFunctionsRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class lstFunctionsRow
        Inherits DataRow
        
        Private tablelstFunctions As lstFunctionsDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tablelstFunctions = CType(Me.Table,lstFunctionsDataTable)
        End Sub
        
        Public Property FunctionName As String
            Get
                Return CType(Me(Me.tablelstFunctions.FunctionNameColumn),String)
            End Get
            Set
                Me(Me.tablelstFunctions.FunctionNameColumn) = value
            End Set
        End Property
        
        Public Property Description As String
            Get
                Try 
                    Return CType(Me(Me.tablelstFunctions.DescriptionColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablelstFunctions.DescriptionColumn) = value
            End Set
        End Property
        
        Public Function IsDescriptionNull() As Boolean
            Return Me.IsNull(Me.tablelstFunctions.DescriptionColumn)
        End Function
        
        Public Sub SetDescriptionNull()
            Me(Me.tablelstFunctions.DescriptionColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class lstFunctionsRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As lstFunctionsRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As lstFunctionsRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As lstFunctionsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
