CREATE TABLE [dbo].[LN15_DSB] (
    [BF_SSN]             CHAR (9)        NOT NULL,
    [LN_BR_DSB_SEQ]      SMALLINT        NOT NULL,
    [LA_DSB]             NUMERIC (8, 2)  NOT NULL,
    [LA_DSB_CAN]         NUMERIC (8, 2)  NULL,
    [LC_DSB_CAN_TYP]     CHAR (1)        NOT NULL,
    [LC_RCP_CHK_DSB]     CHAR (1)        NOT NULL,
    [LD_CAN_RPT_GTR]     DATE            NULL,
    [LD_DSB]             DATE            NOT NULL,
    [LD_DSB_RPT_GTR]     DATE            NULL,
    [LF_DSB_CHK]         VARCHAR (10)    NOT NULL,
    [LC_DSB_TYP]         CHAR (1)        NOT NULL,
    [LD_DSB_CAN]         DATE            NULL,
    [LI_LTE_DSB_APV]     CHAR (1)        NOT NULL,
    [LF_RCP_DSB_CHK]     VARCHAR (9)     NOT NULL,
    [LC_LDR_DSB_MDM]     CHAR (1)        NOT NULL,
    [LI_RDS]             CHAR (1)        NOT NULL,
    [LD_DSB_ROS_PRT]     DATE            NULL,
    [LR_DSB_ITR]         NUMERIC (5, 3)  NULL,
    [LD_STA_LON15]       DATE            NULL,
    [LC_STA_LON15]       CHAR (1)        NOT NULL,
    [LD_EFT_FND_RLS]     DATE            NULL,
    [LD_EFT_RLS]         DATE            NULL,
    [LF_LST_DTS_LN15]    DATETIME2 (7)   NOT NULL,
    [LR_IRM_APR]         NUMERIC (5, 3)  NULL,
    [LI_IDF_SIG]         CHAR (1)        NOT NULL,
    [AF_DSB_RPT]         VARCHAR (8)     NOT NULL,
    [LN_SEQ]             SMALLINT        NULL,
    [AN_SEQ]             SMALLINT        NULL,
    [IC_LON_PGM]         VARCHAR (6)     NULL,
    [LR_RPD_APR]         NUMERIC (5, 3)  NULL,
    [LA_PCV_LDR_CHK]     NUMERIC (8, 2)  NULL,
    [LC_DSB_RLS_STA]     CHAR (1)        NULL,
    [LC_LON_EXT_ORG_SRC] CHAR (1)        NOT NULL,
    [LN_LON_DSB_SEQ]     SMALLINT        NOT NULL,
    [LA_DSB_ORG_CHK_EFT] NUMERIC (8, 2)  NULL,
    [LA_DSB_CAN_PCV]     NUMERIC (8, 2)  NULL,
    [LD_PRE_DSB_ROS_SNT] DATE            NULL,
    [LD_SCL_DSB_ATH_RCV] DATE            NULL,
    [LC_DSB_CAN_PCV]     CHAR (1)        NOT NULL,
    [LC_CMN_LN_HLD_RLS]  CHAR (1)        NOT NULL,
    [LC_PAY_DSB_CAN_LTR] VARCHAR (2)     NOT NULL,
    [LD_PAY_DSB_CAN_LTR] DATE            NULL,
    [LD_PRE_DSB_PRE_ROS] DATE            NULL,
    [LA_PRE_DSB_CAN]     NUMERIC (8, 2)  NULL,
    [LD_PRE_DSB_CAN]     DATE            NULL,
    [LN_CMN_LN_DSB_SEQ]  SMALLINT        NULL,
    [AF_APL_ID]          VARCHAR (9)     NULL,
    [LD_NTF_SCL_CDA]     DATE            NULL,
    [LD_NTF_OWN]         DATE            NULL,
    [LN_DSB_SUM_SEQ]     SMALLINT        NULL,
    [LC_REU_REA]         VARCHAR (2)     NOT NULL,
    [IF_CDA]             VARCHAR (8)     NOT NULL,
    [LC_DSB_CAN_REA]     VARCHAR (4)     NOT NULL,
    [LC_DSB_EVT_LN15]    VARCHAR (2)     NOT NULL,
    [LF_LST_USR_LN15]    VARCHAR (8)     NOT NULL,
    [LF_DSB_EVT_LN15]    DATETIME2 (7)   NULL,
    [LD_DSB_RLS_STA]     DATE            NULL,
    [LA_DSB_RAL]         NUMERIC (8, 2)  NULL,
    [LD_DSB_RAL]         DATE            NULL,
    [LC_DSB_TYP_RAL]     CHAR (1)        NOT NULL,
    [LC_DSB_SRC_RAL]     CHAR (1)        NOT NULL,
    [LC_LO_AUT_RAL]      VARCHAR (2)     NOT NULL,
    [LC_DSB_IN_ERR]      CHAR (1)        NOT NULL,
    [LI_DSB_DIR_BR]      CHAR (1)        NOT NULL,
    [LC_DSB_DIR_BR_VER]  CHAR (1)        NOT NULL,
    [AN_LC_APL_SEQ]      SMALLINT        NULL,
    [LA_DSB_CAN_PCV_RFD] NUMERIC (8, 2)  NULL,
    [LA_DSB_CAN_RFD]     NUMERIC (8, 2)  NULL,
    [LD_DSB_CAN_RFD]     DATE            NULL,
    [LD_DSB_RFD_RPT_GTR] DATE            NULL,
    [LF_ECA_LON_SCH_BCH] VARCHAR (3)     NOT NULL,
    [LF_ECA_CTD]         VARCHAR (8)     NOT NULL,
    [LD_ECA_LON_SCH_CRT] DATE            NULL,
    [LD_ECA_DSB_FUD]     DATE            NULL,
    [LC_DSB_ACH_OWN]     VARCHAR (3)     NOT NULL,
    [LC_DSB_ACH_SCL]     VARCHAR (3)     NOT NULL,
    [LA_DL_DSB_REB]      NUMERIC (12, 2) NULL,
    [LA_DSB_REB_CAN]     NUMERIC (12, 2) NULL,
    [LA_PCV_DSB_REB_CAN] NUMERIC (12, 2) NULL,
    [LC_CNL_DSB_CAN_REA] VARCHAR (1)     NOT NULL,
    [LA_PRE_DSB_CAN_RPT] NUMERIC (12, 2) NULL,
    [LD_PRE_DSB_CAN_RPT] DATE            NULL,
    [LD_DSB_ACP_FR_COD]  DATE            NULL,
    [LN_DL_DSB_PAY_SEQ]  SMALLINT        NULL,
    [LF_DL_SCL_ENR_DSB]  VARCHAR (8)     NOT NULL,
    [LD_COD_DSB_PST]     DATE            NULL,
    [LC_CIP]             VARCHAR (7)     NOT NULL,
    [LC_DSB_ACP_MTD]     VARCHAR (2)     NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_BFSSN_LNSEQ]
    ON [dbo].[LN15_DSB]([BF_SSN] ASC, [LN_SEQ] ASC) WITH (FILLFACTOR = 95);


GO
CREATE NONCLUSTERED INDEX [IX_LCSTALON15_LDDSB]
    ON [dbo].[LN15_DSB]([LC_STA_LON15] ASC, [LD_DSB] ASC)
    INCLUDE([BF_SSN], [LD_DSB_CAN], [LN_SEQ]) WITH (FILLFACTOR = 95);

