'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class LivDSTILPVoids
    Inherits DataSet
    
    Private tableTILPVoids As TILPVoidsDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("TILPVoids")) Is Nothing) Then
                Me.Tables.Add(New TILPVoidsDataTable(ds.Tables("TILPVoids")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property TILPVoids As TILPVoidsDataTable
        Get
            Return Me.tableTILPVoids
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As LivDSTILPVoids = CType(MyBase.Clone,LivDSTILPVoids)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("TILPVoids")) Is Nothing) Then
            Me.Tables.Add(New TILPVoidsDataTable(ds.Tables("TILPVoids")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableTILPVoids = CType(Me.Tables("TILPVoids"),TILPVoidsDataTable)
        If (Not (Me.tableTILPVoids) Is Nothing) Then
            Me.tableTILPVoids.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "LivDSTILPVoids"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/LivDSTILPVoids.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableTILPVoids = New TILPVoidsDataTable
        Me.Tables.Add(Me.tableTILPVoids)
    End Sub
    
    Private Function ShouldSerializeTILPVoids() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub TILPVoidsRowChangeEventHandler(ByVal sender As Object, ByVal e As TILPVoidsRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TILPVoidsDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnReceiptNumber As DataColumn
        
        Private columnNotes As DataColumn
        
        Private columnDateVoided As DataColumn
        
        Friend Sub New()
            MyBase.New("TILPVoids")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property ReceiptNumberColumn As DataColumn
            Get
                Return Me.columnReceiptNumber
            End Get
        End Property
        
        Friend ReadOnly Property NotesColumn As DataColumn
            Get
                Return Me.columnNotes
            End Get
        End Property
        
        Friend ReadOnly Property DateVoidedColumn As DataColumn
            Get
                Return Me.columnDateVoided
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As TILPVoidsRow
            Get
                Return CType(Me.Rows(index),TILPVoidsRow)
            End Get
        End Property
        
        Public Event TILPVoidsRowChanged As TILPVoidsRowChangeEventHandler
        
        Public Event TILPVoidsRowChanging As TILPVoidsRowChangeEventHandler
        
        Public Event TILPVoidsRowDeleted As TILPVoidsRowChangeEventHandler
        
        Public Event TILPVoidsRowDeleting As TILPVoidsRowChangeEventHandler
        
        Public Overloads Sub AddTILPVoidsRow(ByVal row As TILPVoidsRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddTILPVoidsRow(ByVal ReceiptNumber As Long, ByVal Notes As String, ByVal DateVoided As Date) As TILPVoidsRow
            Dim rowTILPVoidsRow As TILPVoidsRow = CType(Me.NewRow,TILPVoidsRow)
            rowTILPVoidsRow.ItemArray = New Object() {ReceiptNumber, Notes, DateVoided}
            Me.Rows.Add(rowTILPVoidsRow)
            Return rowTILPVoidsRow
        End Function
        
        Public Function FindByReceiptNumber(ByVal ReceiptNumber As Long) As TILPVoidsRow
            Return CType(Me.Rows.Find(New Object() {ReceiptNumber}),TILPVoidsRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As TILPVoidsDataTable = CType(MyBase.Clone,TILPVoidsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New TILPVoidsDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnReceiptNumber = Me.Columns("ReceiptNumber")
            Me.columnNotes = Me.Columns("Notes")
            Me.columnDateVoided = Me.Columns("DateVoided")
        End Sub
        
        Private Sub InitClass()
            Me.columnReceiptNumber = New DataColumn("ReceiptNumber", GetType(System.Int64), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnReceiptNumber)
            Me.columnNotes = New DataColumn("Notes", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNotes)
            Me.columnDateVoided = New DataColumn("DateVoided", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDateVoided)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnReceiptNumber}, true))
            Me.columnReceiptNumber.AllowDBNull = false
            Me.columnReceiptNumber.Unique = true
        End Sub
        
        Public Function NewTILPVoidsRow() As TILPVoidsRow
            Return CType(Me.NewRow,TILPVoidsRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New TILPVoidsRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(TILPVoidsRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.TILPVoidsRowChangedEvent) Is Nothing) Then
                RaiseEvent TILPVoidsRowChanged(Me, New TILPVoidsRowChangeEvent(CType(e.Row,TILPVoidsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.TILPVoidsRowChangingEvent) Is Nothing) Then
                RaiseEvent TILPVoidsRowChanging(Me, New TILPVoidsRowChangeEvent(CType(e.Row,TILPVoidsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.TILPVoidsRowDeletedEvent) Is Nothing) Then
                RaiseEvent TILPVoidsRowDeleted(Me, New TILPVoidsRowChangeEvent(CType(e.Row,TILPVoidsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.TILPVoidsRowDeletingEvent) Is Nothing) Then
                RaiseEvent TILPVoidsRowDeleting(Me, New TILPVoidsRowChangeEvent(CType(e.Row,TILPVoidsRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveTILPVoidsRow(ByVal row As TILPVoidsRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TILPVoidsRow
        Inherits DataRow
        
        Private tableTILPVoids As TILPVoidsDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableTILPVoids = CType(Me.Table,TILPVoidsDataTable)
        End Sub
        
        Public Property ReceiptNumber As Long
            Get
                Return CType(Me(Me.tableTILPVoids.ReceiptNumberColumn),Long)
            End Get
            Set
                Me(Me.tableTILPVoids.ReceiptNumberColumn) = value
            End Set
        End Property
        
        Public Property Notes As String
            Get
                Try 
                    Return CType(Me(Me.tableTILPVoids.NotesColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTILPVoids.NotesColumn) = value
            End Set
        End Property
        
        Public Property DateVoided As Date
            Get
                Try 
                    Return CType(Me(Me.tableTILPVoids.DateVoidedColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableTILPVoids.DateVoidedColumn) = value
            End Set
        End Property
        
        Public Function IsNotesNull() As Boolean
            Return Me.IsNull(Me.tableTILPVoids.NotesColumn)
        End Function
        
        Public Sub SetNotesNull()
            Me(Me.tableTILPVoids.NotesColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDateVoidedNull() As Boolean
            Return Me.IsNull(Me.tableTILPVoids.DateVoidedColumn)
        End Function
        
        Public Sub SetDateVoidedNull()
            Me(Me.tableTILPVoids.DateVoidedColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TILPVoidsRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As TILPVoidsRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As TILPVoidsRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As TILPVoidsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
