CREATE TABLE [dbo].[CL10_CLM_PCL]
(
	[BF_SSN] VARCHAR(9) NOT NULL, 
	[LN_SEQ_CLM_PCL] SMALLINT NOT NULL, 
	[LC_REA_CLM_PCL] VARCHAR(2) NULL, 
	[LC_TYP_REC_CLM_PCL] CHAR(1) NULL, 
	[LF_USR_ASN_CLM_PCL] VARCHAR(8) NULL, 
	[LI_CLM_GTR_RCV] CHAR(1) NULL, 
	[LD_CLM_RQR] DATETIME NULL, 
	[LF_CLM_BCH] VARCHAR(7) NULL, 
	[LF_LST_DTS_CL10] DATETIME NULL, 
	[LI_CLM_QA] CHAR(1) NULL, 
	[LD_GTR_CLM_RCI] DATETIME NULL, 
	[LC_GTR_CLM_ACK] CHAR(1) NULL, 
	[LC_CAN_STA_CCI] CHAR(1) NULL, 
	[LI_CLM_CLL_RCV] CHAR(1) NULL, 
	[LC_XCP_PRF] CHAR(1) NULL, 
 
    PRIMARY KEY ([BF_SSN], 
				[LN_SEQ_CLM_PCL] 
				)
)
