CREATE TABLE [dbo].[LN54_LON_BBS]
(
	[BF_SSN] VARCHAR(9) NOT NULL, 
	[LN_SEQ] SMALLINT NOT NULL, 
	[PM_BBS_PGM] VARCHAR(3) NOT NULL, 
	[PN_BBS_PGM_SEQ] SMALLINT NOT NULL, 
	[LN_LON_BBS_PGM_SEQ] SMALLINT NOT NULL, 
	[LD_EFF_BEG_LN54] DATETIME NULL, 
	[LI_BBS_ITD_LTR_SNT] BIT NULL, 
	[LN_BBS_STS_PCV_PAY] DECIMAL(3,0) NULL, 
	[LC_BBS_REB_MTD] CHAR(1) NULL, 
	[LC_STA_LN54] CHAR(1) NULL, 
	[LD_STA_LN54] DATETIME NULL, 
	[LC_BBT_TYS_ASS] BIT NULL, 
	[LC_BBS_DSQ_REA] VARCHAR(2) NULL, 
	[LD_BBS_DSQ] DATETIME NULL, 
	[LC_BBS_ELG] CHAR(1) NULL, 
	[LC_BBT_PRC_RBD] CHAR(1) NULL, 
	[LD_BBS_RPD_WDO_END] DATETIME NULL, 
	[LC_BBS_BCH_PRC] CHAR(1) NULL, 
	[LF_LST_USR_LN54] VARCHAR(8) NULL, 
	[LF_LST_DTS_LN54] DATETIME NULL, 
	[LN_BBS_PCV_PAY_MOT] SMALLINT NULL, 
	[LD_BBS_ICV_REQ] DATETIME NULL, 
	[LD_BBS_DSQ_APL] DATETIME NULL, 
	[LI_BBS_PCV_LTE_PAY] CHAR(1) NULL
	
	PRIMARY KEY ([BF_SSN], 
				 [LN_SEQ],
				 [PM_BBS_PGM],
				 [PN_BBS_PGM_SEQ],
				 [LN_LON_BBS_PGM_SEQ]
				)
)

    