CREATE TABLE [dbo].[ZDEL_LN80_LON_BIL_CRF]
(
	[BF_SSN] VARCHAR(9) NOT NULL, 
	[LN_SEQ] SMALLINT NOT NULL, 
	[LD_BIL_CRT] DATETIME NOT NULL, 
	[LN_SEQ_BIL_WI_DTE] SMALLINT NOT NULL, 
	[LN_BIL_OCC_SEQ] SMALLINT NOT NULL, 
)
