/*LPP SERVICING DATA FILE FOR FINANCE - MR50 TABLE - MR5A,MR5B,MR5C */
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*THIS DIRECTORY HAS BEEN HARD CODED AT THE REQUEST OF AES*/
/*%LET RPTLIB = /sas/whse/progrevw ;*/
/*FILENAME REPORT2 "&RPTLIB/ULWE13.LWE13R2";*/

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE LPPFMR50 AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT A.BF_SSN, 
		A.LN_SEQ, 
		A.LD_END_GRC_PRD, 
		C.LN_MTH_GRC_PRD_DSC, 
		B.LD_TRM_END, 
		B.LD_TRM_BEG, 
		B.LF_GTR_RFR, 
		A.LF_DOE_SCL_ORG, 
		C.WX_SCY_PGA,
		A.IC_LON_PGM, 
		C.LF_RGL_CAT_LP06, 
		B.IF_DOE_LDR, 
		B.IF_GTR, 
		A.LF_STU_SSN, 
		A.LD_LON_1_DSB, 
		B.LC_ACA_GDE_LEV,
		C.WX_SCY_PGA_PGM_YR, 
		B.IF_OWN, 
		B.LD_LON_EFF_ADD, 
		C.LA_R78_INT_MAX, 
		A.WN_DAY_GRC_RMN, 
		A.WN_DAY_ENR_ELP, 
		A.WD_RPY_BEG, 
		A.WN_DAY_RPD_ELP, 
		A.WN_MTH_RPD_ELP, 
		C.IM_PGA_SHO, 
		C.IM_GTR_SHO, 
		A.WA_CUR_PRI, 
		A.WA_CUR_BR_INT, 
		A.WA_CUR_GOV_INT, 
		A.WA_CUR_OTH_CHR, 
		A.WA_AVG_DAY_BAL, 
		A.WA_PRV_MTH_PRI, 
		A.WA_PRV_MTH_BR_INT, 
		A.WA_PRV_MTH_GOV_INT, 
		A.WA_PRV_MTH_OTH_CHR, 
		A.WM_BR_1, 
		A.WM_BR_MID, 
		A.WM_BR_LST, 
		A.WM_BR_LST_SFX, 
		B.DD_BRT, 
		B.WM_STU_1, 
		B.WM_STU_MID, 
		B.WM_STU_LST, 
		B.WM_STU_LST_SFX, 
		B.WX_STR_ADR_1, 
		B.WX_STR_ADR_2, 
		B.WX_STR_ADR_3, 
		B.WM_CT, 
		B.DC_DOM_ST, 
		B.DF_ZIP_CDE, 
		B.DI_VLD_ADR, 
		B.DM_FGN_CNY, 
		B.DM_FGN_ST, 
		B.DN_PHN_XTN, 
		B.DN_DOM_PHN_LCL, 
		B.DN_DOM_PHN_XCH, 
		B.DN_DOM_PHN_ARA, 
		B.DN_FGN_PHN_INL, 
		B.DN_FGN_PHN_CNY, 
		B.DN_FGN_PHN_CT, 
		B.DN_FGN_PHN_LCL, 
		B.DI_PHN_VLD, 
		C.DD_SKP_BEG, 
		B.WI_LON_COS, 
		B.WI_LON_CMK, 
		B.WI_LON_CBR, 
		B.WI_OTH_EDS_TYP, 
		A.WM_DOE_SCL_ORG, 
		A.WC_TYP_SCL_ORG, 
		A.WI_PPR_SCL_ORG, 
		B.LF_DOE_SCL_ENR_CUR, 
		A.LD_SCL_SPR, 
		A.WN_DAY_GRC_ELP, 
		A.WN_DAY_ENR_RMN, 
		B.WC_TYP_SCL_CUR, 
		B.WX_TYP_SCL_CUR, 
		C.WI_PPR_SCL_CUR, 
		C.IF_GTR_RPT_SCL, 
		C.WC_SCL_CUR_DOM_ST, 
		C.WC_SCL_ORG_DOM_ST, 
		B.LD_RPS_1_PAY_DU, 
		B.LD_SNT_RPD_DIS, 
		B.LD_BIL_DU, 
		B.WN_MTH_INT_CAP_FRQ, 
		C.LC_TYP_SCH_DIS, 
		B.WA_RPS_ISL_1, 
		B.WA_RPS_ISL_2, 
		B.WA_RPS_ISL_3, 
		B.WA_RPS_ISL_4, 
		B.WA_RPS_ISL_5, 
		B.WA_RPS_ISL_6, 
		B.WA_RPS_ISL_7, 
		B.WN_RPS_TRM_1, 
		B.WN_RPS_TRM_2, 
		B.WN_RPS_TRM_3, 
		B.WN_RPS_TRM_4, 
		B.WN_RPS_TRM_5, 
		B.WN_RPS_TRM_6, 
		B.WN_RPS_TRM_7, 
		B.WN_RPS_TRM_INI, 
		B.WA_1_DSB, 
		B.WA_LON_TOT_DSB, 
		B.WA_LON_TOT_INS_PRM, 
		B.WA_LON_TOT_ORG_FEE, 
		B.WA_LON_TOT_OTH_FEE, 
		B.WA_ORG_PRI, 
		B.WI_LON_FUL_DSB, 
		B.LD_DSB, 
		B.WA_LST_DSB, 
		A.LD_DFR_BEG, 
		A.LD_DFR_END, 
		A.WN_DAY_DFR_RMN, 
		A.LC_DFR_TYP, 
		A.WN_MTH_IN_DFR, 
		A.LD_FOR_BEG, 
		A.LD_FOR_END, 
		B.WN_DAY_FOR_RMN, 
		A.LC_FOR_TYP, 
		A.WN_MTH_IN_FOR, 
		A.WI_INI_FOR_APL, 
		A.WN_SQ_FOR_APL, 
		B.WD_SBM_PCL, 
		B.WD_INI_CLM_SBM, 
		A.LC_REA_CLP_LON, 
		B.LD_CLM_REJ_RTN_ACL, 
		B.WD_INI_CLM_PD, 
		B.WA_INI_CLM_INT_PD, 
		B.WA_INI_CLM_PRI_PD, 
		A.WN_DAY_CLM_AGE, 
		B.WD_RS_INI_CLM, 
		B.WD_SUP_CLM_SBM, 
		B.WD_SUP_CLM_PD, 
		B.WA_SUP_CLM_INT_PD, 
		B.WA_SUP_CLM_PRI_PD, 
		B.WA_FAT_NSI_AT_PR, 
		B.WA_PRI_AT_PR, 
		B.WN_DAY_RPD_AFT_CVN, 
		B.WD_FAT_APL_LST_CAP, 
		B.WA_FAT_NSI_LST_CAP, 
		B.WA_TOT_INT_CAP, 
		B.WN_DAY_INT_CAP, 
		B.WA_INT_WOF, 
		B.WA_PRI_WOF, 
		B.WD_LST_BR_PAY, 
		B.WA_LST_PRI_PAY, 
		B.WA_LST_INT_PAY, 
		A.WN_DAY_DLQ_ISL, 
		B.WD_DLQ_DCO_ISL, 
		A.WN_DAY_DLQ_INT, 
		B.WD_DLQ_DCO_INT, 
		A.WC_LON_STA, 
		A.WC_LON_SUB_STA, 
		B.WN_RPS_TRM_RMN, 
		B.WA_CUR_ISL, 
		A.WD_XPC_POF, 
		A.WN_DAY_RPD_RMN, 
		A.IM_OWN_SHO, 
		A.IF_OWN_PRN, 
		A.WM_OWN_PRN_SHO, 
		B.IF_BND_ISS, 
		A.LF_CUR_POR, 
		A.LD_OWN_EFF_SR, 
		B.II_TX_BND, 
		A.ID_LON_SLE, 
		B.IF_SLL_OWN, 
		C.IC_OWN_DOM_ST, 
		A.WC_ITR_TYP_1, 
		A.WC_ITR_TYP_2, 
		A.WC_ITR_TYP_3, 
		A.WC_ITR_TYP_4, 
		C.WD_ITR_EFF_BEG_1, 
		C.WD_ITR_EFF_BEG_2, 
		C.WD_ITR_EFF_BEG_3, 
		C.WD_ITR_EFF_BEG_4, 
		C.WD_ITR_EFF_END_1, 
		C.WD_ITR_EFF_END_2, 
		C.WD_ITR_EFF_END_3, 
		C.WD_ITR_EFF_END_4, 
		C.WD_ITR_APL_1, 
		C.WD_ITR_APL_2, 
		C.WD_ITR_APL_3, 
		C.WD_ITR_APL_4, 
		A.WR_ITR_1, 
		A.WR_ITR_2, 
		A.WR_ITR_3, 
		A.WR_ITR_4, 
		C.WI_SPC_ITR_1, 
		C.WI_SPC_ITR_2, 
		C.WI_SPC_ITR_3, 
		C.WI_SPC_ITR_4, 
		A.WC_ELG_SIN_1, 
		A.WC_ELG_SIN_2, 
		A.WC_ELG_SIN_3, 
		A.WC_ELG_SIN_4, 
		B.WN_PAY_RPD, 
		C.WD_FNL_DMD_BR, 
		C.WD_FNL_DMD_COS, 
		A.WF_POR_AGE_LN_1, 
		A.WF_POR_AGE_LN_2, 
		A.WF_POR_TME_LN, 
		A.WD_MR50_CRT, 
		C.LC_LIT_STA, 
		C.LD_LIT_BEG, 
		A.WI_NEW_LON, 
		A.WF_TIR_PCE_LN35, 
		B.LA_LON_AMT_GTR, 
		B.LD_LON_GTR, 
		A.WN_MTH_GRC_RMN, 
		A.WN_MTH_DFR_RMN, 
		A.WN_MTH_FOR_RMN, 
		A.WN_MTH_ENR_RMN, 
		A.WN_MTH_RPD_RMN, 
		A.WN_MTH_ZRO_ELP, 
		A.WN_MTH_GRC_ELP, 
		A.WN_MTH_ENR_ELP, 
		A.WN_MTH_LIT_ELP, 
		C.LC_RPD_SLE, 
		C.WX_RPD_SLE, 
		C.LC_ST_BR_RSD_APL, 
		C.WA_LON_SLE_TRF_PRI, 
		C.WA_LON_SLE_TRF_INT, 
		A.WC_SUB_STA_RPT, 
		B.LD_MPN_EXP, 
		B.LF_ORG_RGN, 
		B.AF_LON_ALT, 
		B.AN_SEQ_COM_LN_APL, 
		C.LD_PNT_SIG,
		C.WX_LON_STA,
		C.WX_LON_SUB_STA
FROM	OLWHRM1.MR5A_MR_LON_MTH_01 A
LEFT OUTER JOIN OLWHRM1.MR5B_MR_LON_MTH_02 B
	ON A.BF_SSN = B.BF_SSN
	AND A.LN_SEQ = B.LN_SEQ
	AND A.IF_OWN = B.IF_OWN
	AND A.IC_LON_PGM = B.IC_LON_PGM 
	AND A.IF_GTR = B.IF_GTR 
	AND A.IF_BND_ISS = B.IF_BND_ISS
LEFT OUTER JOIN OLWHRM1.MR5C_MR_LON_MTH_03 C
	ON A.BF_SSN = C.BF_SSN
	AND A.LN_SEQ = C.LN_SEQ
	AND A.IF_OWN = C.IF_OWN
	AND A.IC_LON_PGM = C.IC_LON_PGM 
	AND A.IF_GTR = C.IF_GTR 
	AND A.IF_BND_ISS = C.IF_BND_ISS
WHERE A.WC_REA_ZRO_BAL <> '03'

);
DISCONNECT FROM DB2;
ENDRSUBMIT;

DATA LPPFMR50;
SET WORKLOCL.LPPFMR50;
RUN;

PROC SORT DATA=LPPFMR50;
BY BF_SSN LN_SEQ ;
RUN;

DATA _NULL_;
SET  WORK.LPPFMR50;
FILE 'T:\SAS\ULWE13.LWE13R2' DELIMITER=',' DSD DROPOVER LRECL=32767;
*FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
FORMAT BF_SSN $9. ;
FORMAT LN_SEQ 6. ;
FORMAT LD_END_GRC_PRD MMDDYY10. ;
FORMAT LN_MTH_GRC_PRD_DSC 4. ;
FORMAT LD_TRM_END MMDDYY10. ;
FORMAT LD_TRM_BEG MMDDYY10. ;
FORMAT LF_GTR_RFR $12. ;
FORMAT LF_DOE_SCL_ORG $8. ;
FORMAT WX_SCY_PGA $20. ;
FORMAT IC_LON_PGM $6. ;
FORMAT LF_RGL_CAT_LP06 $7. ;
FORMAT IF_DOE_LDR $8. ;
FORMAT IF_GTR $6. ;
FORMAT LF_STU_SSN $9. ;
FORMAT LD_LON_1_DSB MMDDYY10. ;
FORMAT LC_ACA_GDE_LEV $2. ;
FORMAT WX_SCY_PGA_PGM_YR $20. ;
FORMAT IF_OWN $8. ;
FORMAT LD_LON_EFF_ADD MMDDYY10. ;
FORMAT LA_R78_INT_MAX 9.2 ;
FORMAT WN_DAY_GRC_RMN 5. ;
FORMAT WN_DAY_ENR_ELP 5. ;
FORMAT WD_RPY_BEG MMDDYY10. ;
FORMAT WN_DAY_RPD_ELP 6. ;
FORMAT WN_MTH_RPD_ELP 4. ;
FORMAT IM_PGA_SHO $20. ;
FORMAT IM_GTR_SHO $20. ;
FORMAT WA_CUR_PRI 10.2 ;
FORMAT WA_CUR_BR_INT 10.2 ;
FORMAT WA_CUR_GOV_INT 9.2 ;
FORMAT WA_CUR_OTH_CHR 9.2 ;
FORMAT WA_AVG_DAY_BAL 10.2 ;
FORMAT WA_PRV_MTH_PRI 10.2 ;
FORMAT WA_PRV_MTH_BR_INT 10.2 ;
FORMAT WA_PRV_MTH_GOV_INT 9.2 ;
FORMAT WA_PRV_MTH_OTH_CHR 9.2 ;
FORMAT WM_BR_1 $13. ;
FORMAT WM_BR_MID $13. ;
FORMAT WM_BR_LST $23. ;
FORMAT WM_BR_LST_SFX $4. ;
FORMAT DD_BRT MMDDYY10. ;
FORMAT WM_STU_1 $13. ;
FORMAT WM_STU_MID $13. ;
FORMAT WM_STU_LST $23. ;
FORMAT WM_STU_LST_SFX $4. ;
FORMAT WX_STR_ADR_1 $30. ;
FORMAT WX_STR_ADR_2 $30. ;
FORMAT WX_STR_ADR_3 $30. ;
FORMAT WM_CT $20. ;
FORMAT DC_DOM_ST $2. ;
FORMAT DF_ZIP_CDE $17. ;
FORMAT DI_VLD_ADR $1. ;
FORMAT DM_FGN_CNY $25. ;
FORMAT DM_FGN_ST $15. ;
FORMAT DN_PHN_XTN $5. ;
FORMAT DN_DOM_PHN_LCL $4. ;
FORMAT DN_DOM_PHN_XCH $3. ;
FORMAT DN_DOM_PHN_ARA $3. ;
FORMAT DN_FGN_PHN_INL $3. ;
FORMAT DN_FGN_PHN_CNY $3. ;
FORMAT DN_FGN_PHN_CT $5. ;
FORMAT DN_FGN_PHN_LCL $11. ;
FORMAT DI_PHN_VLD $1. ;
FORMAT DD_SKP_BEG MMDDYY10. ;
FORMAT WI_LON_COS $1. ;
FORMAT WI_LON_CMK $1. ;
FORMAT WI_LON_CBR $1. ;
FORMAT WI_OTH_EDS_TYP $1. ;
FORMAT WM_DOE_SCL_ORG $20. ;
FORMAT WC_TYP_SCL_ORG $2. ;
FORMAT WI_PPR_SCL_ORG $1. ;
FORMAT LF_DOE_SCL_ENR_CUR $8. ;
FORMAT LD_SCL_SPR MMDDYY10. ;
FORMAT WN_DAY_GRC_ELP 5. ;
FORMAT WN_DAY_ENR_RMN 5. ;
FORMAT WC_TYP_SCL_CUR $2. ;
FORMAT WX_TYP_SCL_CUR $20. ;
FORMAT WI_PPR_SCL_CUR $1. ;
FORMAT IF_GTR_RPT_SCL $8. ;
FORMAT WC_SCL_CUR_DOM_ST $2. ;
FORMAT WC_SCL_ORG_DOM_ST $2. ;
FORMAT LD_RPS_1_PAY_DU MMDDYY10. ;
FORMAT LD_SNT_RPD_DIS MMDDYY10. ;
FORMAT LD_BIL_DU MMDDYY10. ;
FORMAT WN_MTH_INT_CAP_FRQ 3. ;
FORMAT LC_TYP_SCH_DIS $2. ;
FORMAT WA_RPS_ISL_1 9.2 ;
FORMAT WA_RPS_ISL_2 9.2 ;
FORMAT WA_RPS_ISL_3 9.2 ;
FORMAT WA_RPS_ISL_4 9.2 ;
FORMAT WA_RPS_ISL_5 9.2 ;
FORMAT WA_RPS_ISL_6 9.2 ;
FORMAT WA_RPS_ISL_7 9.2 ;
FORMAT WN_RPS_TRM_1 4. ;
FORMAT WN_RPS_TRM_2 4. ;
FORMAT WN_RPS_TRM_3 4. ;
FORMAT WN_RPS_TRM_4 4. ;
FORMAT WN_RPS_TRM_5 4. ;
FORMAT WN_RPS_TRM_6 4. ;
FORMAT WN_RPS_TRM_7 4. ;
FORMAT WN_RPS_TRM_INI 4. ;
FORMAT WA_1_DSB 10.2 ;
FORMAT WA_LON_TOT_DSB 10.2 ;
FORMAT WA_LON_TOT_INS_PRM 9.2 ;
FORMAT WA_LON_TOT_ORG_FEE 9.2 ;
FORMAT WA_LON_TOT_OTH_FEE 9.2 ;
FORMAT WA_ORG_PRI 10.2 ;
FORMAT WI_LON_FUL_DSB $1. ;
FORMAT LD_DSB MMDDYY10. ;
FORMAT WA_LST_DSB 10.2 ;
FORMAT LD_DFR_BEG MMDDYY10. ;
FORMAT LD_DFR_END MMDDYY10. ;
FORMAT WN_DAY_DFR_RMN 5. ;
FORMAT LC_DFR_TYP $2. ;
FORMAT WN_MTH_IN_DFR 4. ;
FORMAT LD_FOR_BEG MMDDYY10. ;
FORMAT LD_FOR_END MMDDYY10. ;
FORMAT WN_DAY_FOR_RMN 5. ;
FORMAT LC_FOR_TYP $2. ;
FORMAT WN_MTH_IN_FOR 4. ;
FORMAT WI_INI_FOR_APL $1. ;
FORMAT WN_SQ_FOR_APL 4. ;
FORMAT WD_SBM_PCL MMDDYY10. ;
FORMAT WD_INI_CLM_SBM MMDDYY10. ;
FORMAT LC_REA_CLP_LON $2. ;
FORMAT LD_CLM_REJ_RTN_ACL MMDDYY10. ;
FORMAT WD_INI_CLM_PD MMDDYY10. ;
FORMAT WA_INI_CLM_INT_PD 9.2 ;
FORMAT WA_INI_CLM_PRI_PD 10.2 ;
FORMAT WN_DAY_CLM_AGE 5. ;
FORMAT WD_RS_INI_CLM MMDDYY10. ;
FORMAT WD_SUP_CLM_SBM MMDDYY10. ;
FORMAT WD_SUP_CLM_PD MMDDYY10. ;
FORMAT WA_SUP_CLM_INT_PD 9.2 ;
FORMAT WA_SUP_CLM_PRI_PD 10.2 ;
FORMAT WA_FAT_NSI_AT_PR 9.2 ;
FORMAT WA_PRI_AT_PR 10.2 ;
FORMAT WN_DAY_RPD_AFT_CVN 6. ;
FORMAT WD_FAT_APL_LST_CAP MMDDYY10. ;
FORMAT WA_FAT_NSI_LST_CAP 9.2 ;
FORMAT WA_TOT_INT_CAP 9.2 ;
FORMAT WN_DAY_INT_CAP 5. ;
FORMAT WA_INT_WOF 9.2 ;
FORMAT WA_PRI_WOF 10.2 ;
FORMAT WD_LST_BR_PAY MMDDYY10. ;
FORMAT WA_LST_PRI_PAY 10.2 ;
FORMAT WA_LST_INT_PAY 9.2 ;
FORMAT WN_DAY_DLQ_ISL 5. ;
FORMAT WD_DLQ_DCO_ISL MMDDYY10. ;
FORMAT WN_DAY_DLQ_INT 5. ;
FORMAT WD_DLQ_DCO_INT MMDDYY10. ;
FORMAT WC_LON_STA $2. ;
FORMAT WC_LON_SUB_STA $2. ;
FORMAT WN_RPS_TRM_RMN 4. ;
FORMAT WA_CUR_ISL 9.2 ;
FORMAT WD_XPC_POF MMDDYY10. ;
FORMAT WN_DAY_RPD_RMN 6. ;
FORMAT IM_OWN_SHO $20. ;
FORMAT IF_OWN_PRN $8. ;
FORMAT WM_OWN_PRN_SHO $20. ;
FORMAT IF_BND_ISS $8. ;
FORMAT LF_CUR_POR $20. ;
FORMAT LD_OWN_EFF_SR MMDDYY10. ;
FORMAT II_TX_BND $1. ;
FORMAT ID_LON_SLE MMDDYY10. ;
FORMAT IF_SLL_OWN $8. ;
FORMAT IC_OWN_DOM_ST $2. ;
FORMAT WC_ITR_TYP_1 $2. ;
FORMAT WC_ITR_TYP_2 $2. ;
FORMAT WC_ITR_TYP_3 $2. ;
FORMAT WC_ITR_TYP_4 $2. ;
FORMAT WD_ITR_EFF_BEG_1 MMDDYY10. ;
FORMAT WD_ITR_EFF_BEG_2 MMDDYY10. ;
FORMAT WD_ITR_EFF_BEG_3 MMDDYY10. ;
FORMAT WD_ITR_EFF_BEG_4 MMDDYY10. ;
FORMAT WD_ITR_EFF_END_1 MMDDYY10. ;
FORMAT WD_ITR_EFF_END_2 MMDDYY10. ;
FORMAT WD_ITR_EFF_END_3 MMDDYY10. ;
FORMAT WD_ITR_EFF_END_4 MMDDYY10. ;
FORMAT WD_ITR_APL_1 MMDDYY10. ;
FORMAT WD_ITR_APL_2 MMDDYY10. ;
FORMAT WD_ITR_APL_3 MMDDYY10. ;
FORMAT WD_ITR_APL_4 MMDDYY10. ;
FORMAT WR_ITR_1 7.3 ;
FORMAT WR_ITR_2 7.3 ;
FORMAT WR_ITR_3 7.3 ;
FORMAT WR_ITR_4 7.3 ;
FORMAT WI_SPC_ITR_1 $1. ;
FORMAT WI_SPC_ITR_2 $1. ;
FORMAT WI_SPC_ITR_3 $1. ;
FORMAT WI_SPC_ITR_4 $1. ;
FORMAT WC_ELG_SIN_1 $1. ;
FORMAT WC_ELG_SIN_2 $1. ;
FORMAT WC_ELG_SIN_3 $1. ;
FORMAT WC_ELG_SIN_4 $1. ;
FORMAT WN_PAY_RPD 4. ;
FORMAT WD_FNL_DMD_BR MMDDYY10. ;
FORMAT WD_FNL_DMD_COS MMDDYY10. ;
FORMAT WF_POR_AGE_LN_1 $3. ;
FORMAT WF_POR_AGE_LN_2 $3. ;
FORMAT WF_POR_TME_LN $3. ;
FORMAT WD_MR50_CRT MMDDYY10. ;
FORMAT LC_LIT_STA $2. ;
FORMAT LD_LIT_BEG MMDDYY10. ;
FORMAT WI_NEW_LON $1. ;
FORMAT WF_TIR_PCE_LN35 $3. ;
FORMAT LA_LON_AMT_GTR 10.2 ;
FORMAT LD_LON_GTR MMDDYY10. ;
FORMAT WN_MTH_GRC_RMN 4. ;
FORMAT WN_MTH_DFR_RMN 4. ;
FORMAT WN_MTH_FOR_RMN 4. ;
FORMAT WN_MTH_ENR_RMN 4. ;
FORMAT WN_MTH_RPD_RMN 4. ;
FORMAT WN_MTH_ZRO_ELP 4. ;
FORMAT WN_MTH_GRC_ELP 4. ;
FORMAT WN_MTH_ENR_ELP 4. ;
FORMAT WN_MTH_LIT_ELP 4. ;
FORMAT LC_RPD_SLE $1. ;
FORMAT WX_RPD_SLE $20. ;
FORMAT LC_ST_BR_RSD_APL $2. ;
FORMAT WA_LON_SLE_TRF_PRI 10.2 ;
FORMAT WA_LON_SLE_TRF_INT 10.2 ;
FORMAT WC_SUB_STA_RPT $2. ;
FORMAT LD_MPN_EXP MMDDYY10. ;
FORMAT LF_ORG_RGN $8. ;
FORMAT AF_LON_ALT $17. ;
FORMAT AN_SEQ_COM_LN_APL 6. ;
FORMAT LD_PNT_SIG MMDDYY10. ;
FORMAT WX_LON_STA 20.;
FORMAT WX_LON_SUB_STA 20.;
IF _N_ = 1 THEN        /* HEADER */
DO;
PUT
'BF_SSN'
','
'LN_SEQ'
','
'LD_END_GRC_PRD'
','
'LN_MTH_GRC_PRD_DSC'
','
'LD_TRM_END'
','
'LD_TRM_BEG'
','
'LF_GTR_RFR'
','
'LF_DOE_SCL_ORG'
','
'WX_SCY_PGA'
','
'IC_LON_PGM'
','
'LF_RGL_CAT_LP06'
','
'IF_DOE_LDR'
','
'IF_GTR'
','
'LF_STU_SSN'
','
'LD_LON_1_DSB'
','
'LC_ACA_GDE_LEV'
','
'WX_SCY_PGA_PGM_YR'
','
'IF_OWN'
','
'LD_LON_EFF_ADD'
','
'LA_R78_INT_MAX'
','
'WN_DAY_GRC_RMN'
','
'WN_DAY_ENR_ELP'
','
'WD_RPY_BEG'
','
'WN_DAY_RPD_ELP'
','
'WN_MTH_RPD_ELP'
','
'IM_PGA_SHO'
','
'IM_GTR_SHO'
','
'WA_CUR_PRI'
','
'WA_CUR_BR_INT'
','
'WA_CUR_GOV_INT'
','
'WA_CUR_OTH_CHR'
','
'WA_AVG_DAY_BAL'
','
'WA_PRV_MTH_PRI'
','
'WA_PRV_MTH_BR_INT'
','
'WA_PRV_MTH_GOV_INT'
','
'WA_PRV_MTH_OTH_CHR'
','
'WM_BR_1'
','
'WM_BR_MID'
','
'WM_BR_LST'
','
'WM_BR_LST_SFX'
','
'DD_BRT'
','
'WM_STU_1'
','
'WM_STU_MID'
','
'WM_STU_LST'
','
'WM_STU_LST_SFX'
','
'WX_STR_ADR_1'
','
'WX_STR_ADR_2'
','
'WX_STR_ADR_3'
','
'WM_CT'
','
'DC_DOM_ST'
','
'DF_ZIP_CDE'
','
'DI_VLD_ADR'
','
'DM_FGN_CNY'
','
'DM_FGN_ST'
','
'DN_PHN_XTN'
','
'DN_DOM_PHN_LCL'
','
'DN_DOM_PHN_XCH'
','
'DN_DOM_PHN_ARA'
','
'DN_FGN_PHN_INL'
','
'DN_FGN_PHN_CNY'
','
'DN_FGN_PHN_CT'
','
'DN_FGN_PHN_LCL'
','
'DI_PHN_VLD'
','
'DD_SKP_BEG'
','
'WI_LON_COS'
','
'WI_LON_CMK'
','
'WI_LON_CBR'
','
'WI_OTH_EDS_TYP'
','
'WM_DOE_SCL_ORG'
','
'WC_TYP_SCL_ORG'
','
'WI_PPR_SCL_ORG'
','
'LF_DOE_SCL_ENR_CUR'
','
'LD_SCL_SPR'
','
'WN_DAY_GRC_ELP'
','
'WN_DAY_ENR_RMN'
','
'WC_TYP_SCL_CUR'
','
'WX_TYP_SCL_CUR'
','
'WI_PPR_SCL_CUR'
','
'IF_GTR_RPT_SCL'
','
'WC_SCL_CUR_DOM_ST'
','
'WC_SCL_ORG_DOM_ST'
','
'LD_RPS_1_PAY_DU'
','
'LD_SNT_RPD_DIS'
','
'LD_BIL_DU'
','
'WN_MTH_INT_CAP_FRQ'
','
'LC_TYP_SCH_DIS'
','
'WA_RPS_ISL_1'
','
'WA_RPS_ISL_2'
','
'WA_RPS_ISL_3'
','
'WA_RPS_ISL_4'
','
'WA_RPS_ISL_5'
','
'WA_RPS_ISL_6'
','
'WA_RPS_ISL_7'
','
'WN_RPS_TRM_1'
','
'WN_RPS_TRM_2'
','
'WN_RPS_TRM_3'
','
'WN_RPS_TRM_4'
','
'WN_RPS_TRM_5'
','
'WN_RPS_TRM_6'
','
'WN_RPS_TRM_7'
','
'WN_RPS_TRM_INI'
','
'WA_1_DSB'
','
'WA_LON_TOT_DSB'
','
'WA_LON_TOT_INS_PRM'
','
'WA_LON_TOT_ORG_FEE'
','
'WA_LON_TOT_OTH_FEE'
','
'WA_ORG_PRI'
','
'WI_LON_FUL_DSB'
','
'LD_DSB'
','
'WA_LST_DSB'
','
'LD_DFR_BEG'
','
'LD_DFR_END'
','
'WN_DAY_DFR_RMN'
','
'LC_DFR_TYP'
','
'WN_MTH_IN_DFR'
','
'LD_FOR_BEG'
','
'LD_FOR_END'
','
'WN_DAY_FOR_RMN'
','
'LC_FOR_TYP'
','
'WN_MTH_IN_FOR'
','
'WI_INI_FOR_APL'
','
'WN_SQ_FOR_APL'
','
'WD_SBM_PCL'
','
'WD_INI_CLM_SBM'
','
'LC_REA_CLP_LON'
','
'LD_CLM_REJ_RTN_ACL'
','
'WD_INI_CLM_PD'
','
'WA_INI_CLM_INT_PD'
','
'WA_INI_CLM_PRI_PD'
','
'WN_DAY_CLM_AGE'
','
'WD_RS_INI_CLM'
','
'WD_SUP_CLM_SBM'
','
'WD_SUP_CLM_PD'
','
'WA_SUP_CLM_INT_PD'
','
'WA_SUP_CLM_PRI_PD'
','
'WA_FAT_NSI_AT_PR'
','
'WA_PRI_AT_PR'
','
'WN_DAY_RPD_AFT_CVN'
','
'WD_FAT_APL_LST_CAP'
','
'WA_FAT_NSI_LST_CAP'
','
'WA_TOT_INT_CAP'
','
'WN_DAY_INT_CAP'
','
'WA_INT_WOF'
','
'WA_PRI_WOF'
','
'WD_LST_BR_PAY'
','
'WA_LST_PRI_PAY'
','
'WA_LST_INT_PAY'
','
'WN_DAY_DLQ_ISL'
','
'WD_DLQ_DCO_ISL'
','
'WN_DAY_DLQ_INT'
','
'WD_DLQ_DCO_INT'
','
'WC_LON_STA'
','
'WC_LON_SUB_STA'
','
'WN_RPS_TRM_RMN'
','
'WA_CUR_ISL'
','
'WD_XPC_POF'
','
'WN_DAY_RPD_RMN'
','
'IM_OWN_SHO'
','
'IF_OWN_PRN'
','
'WM_OWN_PRN_SHO'
','
'IF_BND_ISS'
','
'LF_CUR_POR'
','
'LD_OWN_EFF_SR'
','
'II_TX_BND'
','
'ID_LON_SLE'
','
'IF_SLL_OWN'
','
'IC_OWN_DOM_ST'
','
'WC_ITR_TYP_1'
','
'WC_ITR_TYP_2'
','
'WC_ITR_TYP_3'
','
'WC_ITR_TYP_4'
','
'WD_ITR_EFF_BEG_1'
','
'WD_ITR_EFF_BEG_2'
','
'WD_ITR_EFF_BEG_3'
','
'WD_ITR_EFF_BEG_4'
','
'WD_ITR_EFF_END_1'
','
'WD_ITR_EFF_END_2'
','
'WD_ITR_EFF_END_3'
','
'WD_ITR_EFF_END_4'
','
'WD_ITR_APL_1'
','
'WD_ITR_APL_2'
','
'WD_ITR_APL_3'
','
'WD_ITR_APL_4'
','
'WR_ITR_1'
','
'WR_ITR_2'
','
'WR_ITR_3'
','
'WR_ITR_4'
','
'WI_SPC_ITR_1'
','
'WI_SPC_ITR_2'
','
'WI_SPC_ITR_3'
','
'WI_SPC_ITR_4'
','
'WC_ELG_SIN_1'
','
'WC_ELG_SIN_2'
','
'WC_ELG_SIN_3'
','
'WC_ELG_SIN_4'
','
'WN_PAY_RPD'
','
'WD_FNL_DMD_BR'
','
'WD_FNL_DMD_COS'
','
'WF_POR_AGE_LN_1'
','
'WF_POR_AGE_LN_2'
','
'WF_POR_TME_LN'
','
'WD_MR50_CRT'
','
'LC_LIT_STA'
','
'LD_LIT_BEG'
','
'WI_NEW_LON'
','
'WF_TIR_PCE_LN35'
','
'LA_LON_AMT_GTR'
','
'LD_LON_GTR'
','
'WN_MTH_GRC_RMN'
','
'WN_MTH_DFR_RMN'
','
'WN_MTH_FOR_RMN'
','
'WN_MTH_ENR_RMN'
','
'WN_MTH_RPD_RMN'
','
'WN_MTH_ZRO_ELP'
','
'WN_MTH_GRC_ELP'
','
'WN_MTH_ENR_ELP'
','
'WN_MTH_LIT_ELP'
','
'LC_RPD_SLE'
','
'WX_RPD_SLE'
','
'LC_ST_BR_RSD_APL'
','
'WA_LON_SLE_TRF_PRI'
','
'WA_LON_SLE_TRF_INT'
','
'WC_SUB_STA_RPT'
','
'LD_MPN_EXP'
','
'LF_ORG_RGN'
','
'AF_LON_ALT'
','
'AN_SEQ_COM_LN_APL'
','
'LD_PNT_SIG'
','
'WX_LON_STA'
','
'WX_LON_SUB_STA'
;

END;
DO;
PUT BF_SSN $ @;
PUT LN_SEQ @;
PUT LD_END_GRC_PRD @;
PUT LN_MTH_GRC_PRD_DSC @;
PUT LD_TRM_END @;
PUT LD_TRM_BEG @;
PUT LF_GTR_RFR $ @;
PUT LF_DOE_SCL_ORG $ @;
PUT WX_SCY_PGA $ @;
PUT IC_LON_PGM $ @;
PUT LF_RGL_CAT_LP06 $ @;
PUT IF_DOE_LDR $ @;
PUT IF_GTR $ @;
PUT LF_STU_SSN $ @;
PUT LD_LON_1_DSB @;
PUT LC_ACA_GDE_LEV $ @;
PUT WX_SCY_PGA_PGM_YR $ @;
PUT IF_OWN $ @;
PUT LD_LON_EFF_ADD @;
PUT LA_R78_INT_MAX @;
PUT WN_DAY_GRC_RMN @;
PUT WN_DAY_ENR_ELP @;
PUT WD_RPY_BEG @;
PUT WN_DAY_RPD_ELP @;
PUT WN_MTH_RPD_ELP @;
PUT IM_PGA_SHO $ @;
PUT IM_GTR_SHO $ @;
PUT WA_CUR_PRI @;
PUT WA_CUR_BR_INT @;
PUT WA_CUR_GOV_INT @;
PUT WA_CUR_OTH_CHR @;
PUT WA_AVG_DAY_BAL @;
PUT WA_PRV_MTH_PRI @;
PUT WA_PRV_MTH_BR_INT @;
PUT WA_PRV_MTH_GOV_INT @;
PUT WA_PRV_MTH_OTH_CHR @;
PUT WM_BR_1 $ @;
PUT WM_BR_MID $ @;
PUT WM_BR_LST $ @;
PUT WM_BR_LST_SFX $ @;
PUT DD_BRT @;
PUT WM_STU_1 $ @;
PUT WM_STU_MID $ @;
PUT WM_STU_LST $ @;
PUT WM_STU_LST_SFX $ @;
PUT WX_STR_ADR_1 $ @;
PUT WX_STR_ADR_2 $ @;
PUT WX_STR_ADR_3 $ @;
PUT WM_CT $ @;
PUT DC_DOM_ST $ @;
PUT DF_ZIP_CDE $ @;
PUT DI_VLD_ADR $ @;
PUT DM_FGN_CNY $ @;
PUT DM_FGN_ST $ @;
PUT DN_PHN_XTN $ @;
PUT DN_DOM_PHN_LCL $ @;
PUT DN_DOM_PHN_XCH $ @;
PUT DN_DOM_PHN_ARA $ @;
PUT DN_FGN_PHN_INL $ @;
PUT DN_FGN_PHN_CNY $ @;
PUT DN_FGN_PHN_CT $ @;
PUT DN_FGN_PHN_LCL $ @;
PUT DI_PHN_VLD $ @;
PUT DD_SKP_BEG @;
PUT WI_LON_COS $ @;
PUT WI_LON_CMK $ @;
PUT WI_LON_CBR $ @;
PUT WI_OTH_EDS_TYP $ @;
PUT WM_DOE_SCL_ORG $ @;
PUT WC_TYP_SCL_ORG $ @;
PUT WI_PPR_SCL_ORG $ @;
PUT LF_DOE_SCL_ENR_CUR $ @;
PUT LD_SCL_SPR @;
PUT WN_DAY_GRC_ELP @;
PUT WN_DAY_ENR_RMN @;
PUT WC_TYP_SCL_CUR $ @;
PUT WX_TYP_SCL_CUR $ @;
PUT WI_PPR_SCL_CUR $ @;
PUT IF_GTR_RPT_SCL $ @;
PUT WC_SCL_CUR_DOM_ST $ @;
PUT WC_SCL_ORG_DOM_ST $ @;
PUT LD_RPS_1_PAY_DU @;
PUT LD_SNT_RPD_DIS @;
PUT LD_BIL_DU @;
PUT WN_MTH_INT_CAP_FRQ @;
PUT LC_TYP_SCH_DIS $ @;
PUT WA_RPS_ISL_1 @;
PUT WA_RPS_ISL_2 @;
PUT WA_RPS_ISL_3 @;
PUT WA_RPS_ISL_4 @;
PUT WA_RPS_ISL_5 @;
PUT WA_RPS_ISL_6 @;
PUT WA_RPS_ISL_7 @;
PUT WN_RPS_TRM_1 @;
PUT WN_RPS_TRM_2 @;
PUT WN_RPS_TRM_3 @;
PUT WN_RPS_TRM_4 @;
PUT WN_RPS_TRM_5 @;
PUT WN_RPS_TRM_6 @;
PUT WN_RPS_TRM_7 @;
PUT WN_RPS_TRM_INI @;
PUT WA_1_DSB @;
PUT WA_LON_TOT_DSB @;
PUT WA_LON_TOT_INS_PRM @;
PUT WA_LON_TOT_ORG_FEE @;
PUT WA_LON_TOT_OTH_FEE @;
PUT WA_ORG_PRI @;
PUT WI_LON_FUL_DSB $ @;
PUT LD_DSB @;
PUT WA_LST_DSB @;
PUT LD_DFR_BEG @;
PUT LD_DFR_END @;
PUT WN_DAY_DFR_RMN @;
PUT LC_DFR_TYP $ @;
PUT WN_MTH_IN_DFR @;
PUT LD_FOR_BEG @;
PUT LD_FOR_END @;
PUT WN_DAY_FOR_RMN @;
PUT LC_FOR_TYP $ @;
PUT WN_MTH_IN_FOR @;
PUT WI_INI_FOR_APL $ @;
PUT WN_SQ_FOR_APL @;
PUT WD_SBM_PCL @;
PUT WD_INI_CLM_SBM @;
PUT LC_REA_CLP_LON $ @;
PUT LD_CLM_REJ_RTN_ACL @;
PUT WD_INI_CLM_PD @;
PUT WA_INI_CLM_INT_PD @;
PUT WA_INI_CLM_PRI_PD @;
PUT WN_DAY_CLM_AGE @;
PUT WD_RS_INI_CLM @;
PUT WD_SUP_CLM_SBM @;
PUT WD_SUP_CLM_PD @;
PUT WA_SUP_CLM_INT_PD @;
PUT WA_SUP_CLM_PRI_PD @;
PUT WA_FAT_NSI_AT_PR @;
PUT WA_PRI_AT_PR @;
PUT WN_DAY_RPD_AFT_CVN @;
PUT WD_FAT_APL_LST_CAP @;
PUT WA_FAT_NSI_LST_CAP @;
PUT WA_TOT_INT_CAP @;
PUT WN_DAY_INT_CAP @;
PUT WA_INT_WOF @;
PUT WA_PRI_WOF @;
PUT WD_LST_BR_PAY @;
PUT WA_LST_PRI_PAY @;
PUT WA_LST_INT_PAY @;
PUT WN_DAY_DLQ_ISL @;
PUT WD_DLQ_DCO_ISL @;
PUT WN_DAY_DLQ_INT @;
PUT WD_DLQ_DCO_INT @;
PUT WC_LON_STA $ @;
PUT WC_LON_SUB_STA $ @;
PUT WN_RPS_TRM_RMN @;
PUT WA_CUR_ISL @;
PUT WD_XPC_POF @;
PUT WN_DAY_RPD_RMN @;
PUT IM_OWN_SHO $ @;
PUT IF_OWN_PRN $ @;
PUT WM_OWN_PRN_SHO $ @;
PUT IF_BND_ISS $ @;
PUT LF_CUR_POR $ @;
PUT LD_OWN_EFF_SR @;
PUT II_TX_BND $ @;
PUT ID_LON_SLE @;
PUT IF_SLL_OWN $ @;
PUT IC_OWN_DOM_ST $ @;
PUT WC_ITR_TYP_1 $ @;
PUT WC_ITR_TYP_2 $ @;
PUT WC_ITR_TYP_3 $ @;
PUT WC_ITR_TYP_4 $ @;
PUT WD_ITR_EFF_BEG_1 @;
PUT WD_ITR_EFF_BEG_2 @;
PUT WD_ITR_EFF_BEG_3 @;
PUT WD_ITR_EFF_BEG_4 @;
PUT WD_ITR_EFF_END_1 @;
PUT WD_ITR_EFF_END_2 @;
PUT WD_ITR_EFF_END_3 @;
PUT WD_ITR_EFF_END_4 @;
PUT WD_ITR_APL_1 @;
PUT WD_ITR_APL_2 @;
PUT WD_ITR_APL_3 @;
PUT WD_ITR_APL_4 @;
PUT WR_ITR_1 @;
PUT WR_ITR_2 @;
PUT WR_ITR_3 @;
PUT WR_ITR_4 @;
PUT WI_SPC_ITR_1 $ @;
PUT WI_SPC_ITR_2 $ @;
PUT WI_SPC_ITR_3 $ @;
PUT WI_SPC_ITR_4 $ @;
PUT WC_ELG_SIN_1 $ @;
PUT WC_ELG_SIN_2 $ @;
PUT WC_ELG_SIN_3 $ @;
PUT WC_ELG_SIN_4 $ @;
PUT WN_PAY_RPD @;
PUT WD_FNL_DMD_BR @;
PUT WD_FNL_DMD_COS @;
PUT WF_POR_AGE_LN_1 $ @;
PUT WF_POR_AGE_LN_2 $ @;
PUT WF_POR_TME_LN $ @;
PUT WD_MR50_CRT @;
PUT LC_LIT_STA $ @;
PUT LD_LIT_BEG @;
PUT WI_NEW_LON $ @;
PUT WF_TIR_PCE_LN35 $ @;
PUT LA_LON_AMT_GTR @;
PUT LD_LON_GTR @;
PUT WN_MTH_GRC_RMN @;
PUT WN_MTH_DFR_RMN @;
PUT WN_MTH_FOR_RMN @;
PUT WN_MTH_ENR_RMN @;
PUT WN_MTH_RPD_RMN @;
PUT WN_MTH_ZRO_ELP @;
PUT WN_MTH_GRC_ELP @;
PUT WN_MTH_ENR_ELP @;
PUT WN_MTH_LIT_ELP @;
PUT LC_RPD_SLE $ @;
PUT WX_RPD_SLE $ @;
PUT LC_ST_BR_RSD_APL $ @;
PUT WA_LON_SLE_TRF_PRI @;
PUT WA_LON_SLE_TRF_INT @;
PUT WC_SUB_STA_RPT $ @;
PUT LD_MPN_EXP @;
PUT LF_ORG_RGN $ @;
PUT AF_LON_ALT $ @;
PUT AN_SEQ_COM_LN_APL @;
PUT LD_PNT_SIG @;
PUT WX_LON_STA @;
PUT WX_LON_SUB_STA;
;
END;
RUN;

