USE BSYS
GO

ALTER PROCEDURE [promotion].[SASAndScriptPromotions]
	@Since DATE NULL
AS

--DECLARE @WeekAgo DATE = DATEADD(WEEK, -1, GETDATE())
DECLARE @LastDayID INT  = 2 -- 0=Mon, 1=Tue, 2 = Wed, ..., 5=Sat, 6=Sun
DECLARE @LastWednesday DATE = DATEADD(DAY, (DATEDIFF(DAY, @LastDayID, DATEADD(WEEK, -1, GETDATE())) / 7) * 7 + 7, @LastDayID)
IF @Since IS NULL
BEGIN
	SET @Since = @LastWednesday
END

DECLARE @NextDayID INT  = 0 -- 0=Mon, 1=Tue, 2 = Wed, ..., 5=Sat, 6=Sun
DECLARE @NextMonday DATE = DATEADD(DAY, (DATEDIFF(DAY, @NextDayID, GETDATE()) / 7) * 7 + 7, @NextDayID)
DECLARE @CCBMessage VARCHAR(50) = 'CCB APPROVAL RECEIVED'
DECLARE @Today DATE = GETDATE()
DECLARE @DefaultDate DATE = CAST('1900-01-01' AS DATE)
SELECT
	CASE 
		WHEN UPPER(STA.Class) = 'SAS' THEN 'SASR ' + CAST(STA.Request AS VARCHAR(10)) 
		WHEN UPPER(STA.Class) = 'SCR' THEN 'SR ' + CAST(STA.Request AS VARCHAR(10)) 
		ELSE 'Other ' + CAST(STA.Request AS VARCHAR(10)) 
	END AS [Request], 
	ISNULL(SASR.Title, SR.Title) AS Job,
	ISNULL(SAS.[Description], SCR.[Description]) AS [Description],
	CASE 
		WHEN STA.[Order] IN (17,18,19,20,22,23,24) AND UPPER(STA.Class) = 'SAS' 
			THEN 'PENDING PROMOTION SAS - ' + CASE WHEN SASR.Expedited = 1 THEN '(Expedited) ' ELSE '' END + 'Anticipated Promotion ' + CONVERT(VARCHAR(10), @NextMonday, 101)
		WHEN STA.[Order] IN (17,18,19,20,22,23,24) AND UPPER(STA.Class) = 'SCR' 
			THEN 'PENDING PROMOTION SCRIPT - ' + CASE WHEN SR.Expedited = 1 THEN '(Expedited) ' ELSE '' END + 'Anticipated Promotion ' + CONVERT(VARCHAR(10), @NextMonday, 101)
		WHEN STA.[Order] IN (25) AND UPPER(STA.Class) = 'SAS'  
			THEN 'COMPLETE SAS - Completed ' + CASE WHEN STA.[End] IS NOT NULL THEN 'Completed ' + CONVERT(VARCHAR(10), STA.[End], 101) ELSE CONVERT(VARCHAR(10), STA.[Begin], 101) END
		WHEN STA.[Order] IN (25) AND UPPER(STA.Class) = 'SCR'  
			THEN 'COMPLETE SCRIPT - Completed ' + CASE WHEN STA.[End] IS NOT NULL THEN 'Completed ' + CONVERT(VARCHAR(10), STA.[End], 101) ELSE CONVERT(VARCHAR(10), STA.[Begin], 101) END
		ELSE 'OTHER'
	END AS [Status],
	ISNULL(SASR.[Priority], SR.[Priority]) AS [Priority],
	ISNULL(SASR.[Summary], SR.[Summary]) AS [Summary],
	ROW_NUMBER() OVER (PARTITION BY STA.Request ORDER BY STA.[Begin] DESC) AS [MaxBegin]
FROM
	(
		SELECT 
			STA.Class,
			STA.[Status],
			STA.[Begin],
			STA.[End],
			STAS.[Order],
			STA.Request,
			STA.[Sequence],
			ROW_NUMBER() OVER (PARTITION BY STA.Request ORDER BY STA.[Begin] DESC) AS [MaxBegin]
		FROM	
			BSYS..SCKR_REF_STATUS STA
			INNER JOIN BSYS..SCKR_LST_STATUSES STAS
				ON STAS.[Status] = Sta.[Status]
		WHERE
			(
				CAST(STA.[Begin] AS DATE) >= @Since
				OR CAST(STA.[End] AS DATE) >= @Since
			)
			AND STAS.[Order] IN (17,18,19,20,22,23,24,25)
	) STA
	LEFT JOIN 
	(
		SELECT
			SASR.Request,
			SASR.Class,
			SASR.[Priority],
			SASR.[Summary],
			SASR.Title,
			SASR.Job,
			SASR.Expedited,
			CASE WHEN CHARINDEX(' ', LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SASR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SASR.History))) + LEN(@CCBMessage), 12)))) != 0
				THEN TRY_CAST(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(SUBSTRING(
							LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SASR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SASR.History))) + LEN(@CCBMessage), 12))), 
							0,
							CHARINDEX(' ', LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SASR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SASR.History))) + LEN(@CCBMessage), 12))))
						))), CHAR(13), ''), CHAR(10), ''), '.', '') AS DATE) 
			WHEN CHARINDEX(CHAR(13), LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SASR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SASR.History))) + LEN(@CCBMessage), 12)))) != 0
				THEN TRY_CAST(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(SUBSTRING(
							LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SASR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SASR.History))) + LEN(@CCBMessage), 12))), 
							0,
							CHARINDEX(CHAR(13), LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SASR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SASR.History))) + LEN(@CCBMessage), 12))))
						))), CHAR(13), ''), CHAR(10), ''), '.', '') AS DATE) 
			WHEN CHARINDEX(CHAR(10), LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SASR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SASR.History))) + LEN(@CCBMessage), 12)))) != 0
				THEN TRY_CAST(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(SUBSTRING(
							LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SASR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SASR.History))) + LEN(@CCBMessage), 12))), 
							0,
							CHARINDEX(CHAR(13), LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SASR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SASR.History))) + LEN(@CCBMessage), 12))))
						))), CHAR(13), ''), CHAR(10), ''), '.', '') AS DATE) 
			ELSE TRY_CAST(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SASR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SASR.History))) + LEN(@CCBMessage), 12))), CHAR(13), ''), CHAR(10), ''), '.', '') AS DATE)
			END AS CCBDate
		FROM
			BSYS..SCKR_DAT_SASRequests SASR
	) SASR
		ON SASR.Request = STA.Request
		AND SASR.Class = STA.Class
	LEFT JOIN BSYS..SCKR_DAT_SAS SAS
		ON SAS.Job = SASR.Job
	LEFT JOIN 
	(
		SELECT
			SR.Request,
			SR.Class,
			SR.[Priority],
			SR.[Summary],
			SR.Title,
			SR.Script,
			SR.Expedited,
			CASE WHEN CHARINDEX(' ', LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SR.History))) + LEN(@CCBMessage), 12)))) != 0
				THEN TRY_CAST(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(SUBSTRING(
							LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SR.History))) + LEN(@CCBMessage), 12))), 
							0,
							CHARINDEX(' ', LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SR.History))) + LEN(@CCBMessage), 12))))
						))), CHAR(13), ''), CHAR(10), ''), '.', '') AS DATE) 
			WHEN CHARINDEX(CHAR(13), LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SR.History))) + LEN(@CCBMessage), 12)))) != 0
				THEN TRY_CAST(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(SUBSTRING(
							LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SR.History))) + LEN(@CCBMessage), 12))), 
							0,
							CHARINDEX(CHAR(13), LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SR.History))) + LEN(@CCBMessage), 12))))
						))), CHAR(13), ''), CHAR(10), ''), '.', '') AS DATE) 
			WHEN CHARINDEX(CHAR(10), LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SR.History))) + LEN(@CCBMessage), 12)))) != 0
				THEN TRY_CAST(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(SUBSTRING(
							LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SR.History))) + LEN(@CCBMessage), 12))), 
							0,
							CHARINDEX(CHAR(13), LTRIM(RTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SR.History))) + LEN(@CCBMessage), 12))))
						))), CHAR(13), ''), CHAR(10), ''), '.', '') AS DATE) 
			ELSE TRY_CAST(REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(SUBSTRING(UPPER(CONVERT(VARCHAR(MAX), SR.History)), CHARINDEX(@CCBMessage, UPPER(CONVERT(VARCHAR(MAX), SR.History))) + LEN(@CCBMessage), 12))), CHAR(13), ''), CHAR(10), ''), '.', '') AS DATE)
			END AS CCBDate
		FROM
			BSYS..SCKR_DAT_SCRIPTREQUESTS SR
	) SR
		ON SR.Request = STA.Request
		AND SR.Class = STA.Class
	LEFT JOIN BSYS..SCKR_DAT_SCRIPTS SCR
		ON SCR.Script =  SR.Script
WHERE
	STA.MaxBegin = 1
	AND 
	(
		(
			STA.[Order] IN (17,18,19,20,22,23,24)
			AND ISNULL(SASR.CCBDate, @DefaultDate) < DATEADD(DAY, -20, @Today)
			AND ISNULL(SR.CCBDate, @DefaultDate) < DATEADD(DAY, -20, @Today)
		)
		OR STA.[Order] IN (25)
	)
ORDER BY
	CASE 
		WHEN STA.[Order] IN (17,18,19,20,22,23,24) AND UPPER(STA.Class) = 'SAS' 
			THEN 'PENDING PROMOTION SAS - Anticipated Promotion ' + CONVERT(VARCHAR(10), @NextMonday, 101)
		WHEN STA.[Order] IN (17,18,19,20,22,23,24) AND UPPER(STA.Class) = 'SCR' 
			THEN 'PENDING PROMOTION SCRIPT - Anticipated Promotion ' + CONVERT(VARCHAR(10), @NextMonday, 101)
		WHEN STA.[Order] IN (25) AND UPPER(STA.Class) = 'SAS'  
			THEN 'COMPLETE SAS - ' + STA.[Status] + ' ' + CASE WHEN STA.[End] IS NOT NULL THEN 'Completed ' + CONVERT(VARCHAR(10), STA.[End], 101) ELSE CONVERT(VARCHAR(10), STA.[Begin], 101) END
		WHEN STA.[Order] IN (25) AND UPPER(STA.Class) = 'SCR'  
			THEN 'COMPLETE SCRIPT - ' + STA.[Status] + ' ' + CASE WHEN STA.[End] IS NOT NULL THEN 'Completed ' + CONVERT(VARCHAR(10), STA.[End], 101) ELSE CONVERT(VARCHAR(10), STA.[Begin], 101) END
		ELSE 'OTHER'
	END,
	STA.Class,
	STA.Request