*------------------------------------*
| UTLWM25 - COLLECTION TERMINATED QC |
*------------------------------------*;
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/ULWM25.LWM25R2";
FILENAME REPORTZ "&RPTLIB/ULWM25.LWM25RZ";
LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
%MACRO SQLCHECK (SQLRPT= );
%IF &SQLXRC NE 0 %THEN %DO;
	DATA _NULL_;
    FILE REPORTZ NOTITLES;
    PUT @01 " ********************************************************************* "
      / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
      / @01 " ****  THE SAS LOG IN &SQLRPT SHOULD BE REVIEWED.          **** "       
      / @01 " ********************************************************************* "
      / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
      / @01 " ****  &SQLXMSG   **** "
      / @01 " ********************************************************************* ";
	RUN;
%END;
%MEND;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE CTERQC AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT A.BF_SSN
	,A.AF_APL_ID||A.AF_APL_ID_SFX AS CLUID
	,A.LF_CLM_ID
	,A.LF_LST_USR_DC10
	,A.LA_CLM_PRI
	,A.LA_CLM_INT
	,B.LA_CLM_INT_ACR
	,B.LA_CLM_PRJ_COL_CST
	,A.LD_AUX_STA_UPD
	,C.BD_ATY_PRF
	,D.DF_SPE_ACC_ID
FROM OLWHRM1.DC01_LON_CLM_INF A
LEFT OUTER JOIN OLWHRM1.DC02_BAL_INT B
	ON A.AF_APL_ID||A.AF_APL_ID_SFX = B.AF_APL_ID||B.AF_APL_ID_SFX
LEFT OUTER JOIN (
	SELECT DF_PRS_ID AS BF_SSN
		,MAX(BD_ATY_PRF) AS BD_ATY_PRF
	FROM OLWHRM1.AY01_BR_ATY
	WHERE PF_ACT = 'DAUX6'
	GROUP BY DF_PRS_ID  
	) C
	ON A.BF_SSN = C.BF_SSN
INNER JOIN OLWHRM1.PD01_PDM_INF D
	ON A.BF_SSN = D.DF_PRS_ID
WHERE A.LC_AUX_STA = '06'
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>>  ;  * INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK (SQLRPT=ULWM25.LWM25RZ);*/
/*QUIT;*/
ENDRSUBMIT;

DATA CTERQC;
SET WORKLOCL.CTERQC;
RUN;

PROC SQL;
CREATE TABLE CTERQC_PROC AS
SELECT DF_SPE_ACC_ID
	,LF_CLM_ID
	,LF_LST_USR_DC10
	,min(LD_AUX_STA_UPD) as LD_AUX_STA_UPD
	,SUM(
		COALESCE(LA_CLM_PRI,0) +
		COALESCE(LA_CLM_INT,0) +
		COALESCE(LA_CLM_INT_ACR,0) +
		COALESCE(LA_CLM_PRJ_COL_CST,0)
		) AS CUR_BAL	
FROM CTERQC
WHERE BD_ATY_PRF < LD_AUX_STA_UPD
GROUP BY DF_SPE_ACC_ID
	,LF_CLM_ID
	,LF_LST_USR_DC10
	,LD_AUX_STA_UPD
;
QUIT;

DATA _NULL_;
SET CTERQC_PROC ;
LENGTH DESCRIPTION $600.;
USER = LF_LST_USR_DC10;
ACT_DT = LD_AUX_STA_UPD;
DESCRIPTION = CATX(',',
	DF_SPE_ACC_ID, 
	CUR_BAL,
	LF_CLM_ID);
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
FORMAT USER $10. ;
FORMAT ACT_DT MMDDYY10. ;
FORMAT DESCRIPTION $600. ;
IF _N_ = 1 THEN DO;
	PUT "USER,ACT_DT,DESCRIPTION";
END;
DO;
   PUT USER $ @;
   PUT ACT_DT @;
   PUT DESCRIPTION $ ;
END;
RUN;
