CREATE TABLE [dbo].[AY20_ATY_TXT] (
    [BF_SSN]          CHAR (9)      NOT NULL,
    [LN_ATY_SEQ]      INT           NOT NULL,
    [LN_ATY_CMT_SEQ]  SMALLINT      NOT NULL,
    [LN_ATY_TXT_SEQ]  SMALLINT      NOT NULL,
    [LX_ATY]          VARCHAR (360) NOT NULL,
    [LF_LST_DTS_AY20] DATETIME2 (7) NOT NULL,
    CONSTRAINT [PK_AY20_ATY_TXT] PRIMARY KEY CLUSTERED ([BF_SSN] ASC, [LN_ATY_SEQ] ASC, [LN_ATY_CMT_SEQ] ASC, [LN_ATY_TXT_SEQ] ASC) WITH (FILLFACTOR = 95)
);


GO
CREATE NONCLUSTERED INDEX [IX_LNATYCMTSEQ]
    ON [dbo].[AY20_ATY_TXT]([LF_LST_DTS_AY20] ASC) WITH (FILLFACTOR = 98);

