CREATE TABLE [dbo].[LN59_CRB_DFR_FOR] (
    [BF_SSN]             VARCHAR (9)   NOT NULL,
    [LN_SEQ]             SMALLINT      NOT NULL,
    [LD_RPT_CRB]         DATE          NOT NULL,
    [LN_CRB_DFR_FOR_SEQ] SMALLINT      NOT NULL,
    [LF_CRT_DTS_LN59]    DATETIME2 (7) NOT NULL,
    [LF_CRT_USR_LN59]    VARCHAR (12)  NOT NULL,
    [LC_SPC_PAY_IND]     VARCHAR (2)   NOT NULL,
    [LD_DFR_PAY_SR]      DATE          NULL,
    [LD_BLL_PAY_DUE]     DATE          NULL,
    [LA_BLL_PAY]         NUMERIC (9)   NULL,
    CONSTRAINT [PK_LN59_CRB_DFR_FOR] PRIMARY KEY CLUSTERED ([BF_SSN] ASC, [LN_SEQ] ASC, [LD_RPT_CRB] ASC, [LN_CRB_DFR_FOR_SEQ] ASC) WITH (FILLFACTOR = 95)
);

