CREATE TABLE [dbo].[PD40_SKP_DTL] (
    [DF_SKP_TGT_PRS]     VARCHAR (9)   NOT NULL,
    [DF_EVT_ID]          VARCHAR (8)   NOT NULL,
    [DF_SKP_EVT_TGT_PRS] VARCHAR (9)   NOT NULL,
    [DF_CRT_DTS_PD40]    DATETIME2 (7) NOT NULL,
    [DD_PLN_SR]          DATE          NOT NULL,
    [DD_CTC_SR]          DATE          NULL,
    [DD_ACL_SR]          DATE          NULL,
    [DN_TME_ATT]         SMALLINT      NOT NULL,
    [DF_ACL_CMP]         DATETIME2 (7) NULL,
    [DF_EVT_ID_DEP]      VARCHAR (8)   NULL,
    [DC_EVT_STA]         VARCHAR (10)  NOT NULL,
    [DF_BCH]             DATETIME2 (7) NULL,
    [DX_EVT_CMT]         VARCHAR (60)  NULL,
    [PF_LST_DTS_PD40]    DATETIME2 (7) NOT NULL,
    [PF_LST_USR_PD40]    VARCHAR (8)   NOT NULL,
    [DF_CRT_DTS_PD26]    DATETIME2 (7) NOT NULL,
    CONSTRAINT [PK_PD40_SKP_DTL] PRIMARY KEY CLUSTERED ([DF_SKP_TGT_PRS] ASC, [DF_EVT_ID] ASC, [DF_SKP_EVT_TGT_PRS] ASC, [DF_CRT_DTS_PD40] ASC) WITH (FILLFACTOR = 95)
);

