USE [UDW]
GO

/****** Object:  View [uhedaymet].[Daily_PerformanceCategory]    Script Date: 11/5/2019 1:32:20 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [uhedaymet].[Daily_PerformanceCategory]

AS

-- set performance category
SELECT
	BD.BF_SSN,
	BD.LN_SEQ,
	PF.PerformanceCategory
FROM
	[uhedaymet].[Daily_BasePopulation] BD
	INNER JOIN
	(
		SELECT
			BD.BF_SSN,
			BD.LN_SEQ,
			CASE
				WHEN BD.ORD = 0 THEN
					CASE 
						WHEN M.ActiveMilitaryIndicator = 1 THEN '04'
						WHEN BD.WC_DW_LON_STA = '02' AND BD.LN_DLQ_MAX < 1 THEN '01'
						WHEN BD.WC_DW_LON_STA = '23' AND LN10.IC_LON_PGM NOT IN('PLUS') THEN '01'
						WHEN BD.WC_DW_LON_STA = '23' AND LN10.IC_LON_PGM IN('PLUS') THEN '02'
						WHEN BD.WC_DW_LON_STA = '01' AND BD.LN_DLQ_MAX < 1 THEN '02' 
						WHEN BD.WC_DW_LON_STA IN ('03','09','10','11','15','16','17','18','19','20','21','22','06','07','08','12','13','14') THEN
							CASE
								WHEN BD.LN_DLQ_MAX = 0 AND BD.BILL_SATISFIED = 1 THEN '03'
								WHEN BD.SPEC_FORB_IND = 1 AND BD.LN_DLQ_MAX = 0 THEN '06'
								WHEN BD.DefermentIndicator = 1 AND BD.LN_DLQ_MAX = 0 THEN '05'
								WHEN BD.LN_DLQ_MAX = 0 AND (BD.LC_CAM_LON_STA = '02' OR BD.SepDate >= CAST(DATEADD(SECOND,-1,DATEADD(MONTH, DATEDIFF(MONTH,0,GETDATE())+1,0)) AS DATE)) THEN '01'
								WHEN BD.LN_DLQ_MAX = 0 AND (BD.LC_CAM_LON_STA = '01' OR (BD.SepDate < CAST(DATEADD(SECOND,-1,DATEADD(MONTH, DATEDIFF(MONTH,0,GETDATE())+1,0)) AS DATE) AND BD.GraceEnd >= CAST(DATEADD(SECOND,-1,DATEADD(MONTH, DATEDIFF(MONTH,0,GETDATE())+1,0)) AS DATE))) THEN '02'
								WHEN BD.LN_DLQ_MAX BETWEEN 0 AND 5 THEN '03'
								WHEN BD.LN_DLQ_MAX <= 30 THEN '07'
								WHEN BD.LN_DLQ_MAX <= 90 THEN '08'
								WHEN BD.LN_DLQ_MAX <= 150 THEN '09'
								WHEN BD.LN_DLQ_MAX <= 270 THEN '10'
								WHEN BD.LN_DLQ_MAX <= 360 THEN '11'
								WHEN BD.LN_DLQ_MAX > 360 THEN '12'
								ELSE '99'
							END
						WHEN BD.WC_DW_LON_STA IN ('04', '05') THEN --defer / forb
							CASE
								WHEN BD.LA_OTS_PRI_ELG <= 0 THEN RIGHT('00'+ CAST(CAST(BD.WC_DW_LON_STA AS TINYINT) + 1 AS VARCHAR),2) --Paid off, but showing defer/forb (needs BU review)
								WHEN BD.LN_DLQ_MAX = 0 AND BD.BILL_SATISFIED = 1 THEN '03'
								WHEN BD.LN_DLQ_MAX = 0 THEN RIGHT('00'+ CAST(CAST(BD.WC_DW_LON_STA AS TINYINT) + 1 AS VARCHAR),2)--status 4 is category 5 etc.
								WHEN BD.LN_DLQ_MAX BETWEEN 1 AND 5 THEN '03'
								WHEN BD.LN_DLQ_MAX <= 30 THEN '07'
								WHEN BD.LN_DLQ_MAX <= 90 THEN '08'
								WHEN BD.LN_DLQ_MAX <= 150 THEN '09'
								WHEN BD.LN_DLQ_MAX <= 270 THEN '10'
								WHEN BD.LN_DLQ_MAX <= 360 THEN '11'
								WHEN BD.LN_DLQ_MAX > 360 THEN '12'
								ELSE '99'
							END
						WHEN BD.LN_DLQ_MAX <= 30 THEN '07'
						WHEN BD.LN_DLQ_MAX <= 90 THEN '08'
						WHEN BD.LN_DLQ_MAX <= 150 THEN '09'
						WHEN BD.LN_DLQ_MAX <= 270 THEN '10'
						WHEN BD.LN_DLQ_MAX <= 360 THEN '11'
						WHEN BD.LN_DLQ_MAX > 360 THEN '12'
						ELSE '99'
					END
				WHEN BD.ORD = 2 AND BD.PIF_TRN_DT BETWEEN CAST(DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0) AS DATE) AND CAST(DATEADD(SECOND,-1,DATEADD(MONTH, DATEDIFF(MONTH,0,GETDATE())+1,0)) AS DATE) THEN 'TRN' /*added to accomodate claim paid*/	
				WHEN BD.ORD = 1 AND BD.LD_PIF_RPT BETWEEN CAST(DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0) AS DATE) AND CAST(DATEADD(SECOND,-1,DATEADD(MONTH, DATEDIFF(MONTH,0,GETDATE())+1,0)) AS DATE) THEN 'PIF'
				WHEN BD.ORD = 2 AND BD.LC_STA_LON10 = 'D' AND BD.LA_OTS_PRI_ELG = 0 AND BD.LD_STA_LON10 BETWEEN CAST(DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0) AS DATE) AND CAST(DATEADD(SECOND,-1,DATEADD(MONTH, DATEDIFF(MONTH,0,GETDATE())+1,0)) AS DATE) THEN 'TRN'
				WHEN BD.ORD = 1 THEN 'PIFPRV'
				WHEN BD.ORD = 2 THEN 'TRNPRV'
				ELSE 'PRV'
			END [PerformanceCategory]
		FROM
			[uhedaymet].[Daily_BasePopulation] BD
			INNER JOIN UDW..LN10_LON LN10
				ON BD.BF_SSN = LN10.BF_SSN
				AND BD.LN_SEQ = LN10.LN_SEQ
			LEFT OUTER JOIN [uhedaymet].[Daily_Military] M
				ON M.BF_SSN = BD.BF_SSN
				AND M.LN_SEQ = BD.LN_SEQ
	) PF 
		ON PF.BF_SSN = BD.BF_SSN
		AND PF.LN_SEQ = BD.LN_SEQ



GO


