CREATE PROCEDURE [ECORRINERR].[InsertErrorRecord]
	@path VARCHAR(MAX),
	@SSN CHAR(9),
	@DOC_DATE DATETIME,
	@DOC_ID VARCHAR(10),
	@ADDR_ACCT_NUM VARCHAR(10),
	@LETTER_ID VARCHAR(10),
	@REQUEST_USER VARCHAR(8),
	@VIEWABLE CHAR(1),
	@CORR_METHOD VARCHAR(20),
	@REPORT_DESC VARCHAR(60),
	@LOAD_TIME DATETIME,
	@REPORT_NAME VARCHAR(17),
	@ADDRESSEE_EMAIL VARCHAR(254),
	@VIEWED CHAR(1),
	@CREATE_DATE DATETIME,
	@MAINFRAME_REGION VARCHAR(8),
	@DCN VARCHAR(17),
	@SUBJECT_LINE VARCHAR(50),
	@DOC_SOURCE VARCHAR(10),
	@DOC_COMMENT VARCHAR(255),
	@WORKFLOW CHAR(1),
	@DOC_DELETE CHAR(1),
	@Region VARCHAR(12),
	@ErrorText VARCHAR(MAX),
	@ErrorFileName VARCHAR(MAX)

AS

INSERT INTO EcorrUheaa.ECORRINERR.ErrorRecords(
	[Path], SSN, DOC_DATE, DOC_ID, ADDR_ACCT_NUM, 
	LETTER_ID, REQUEST_USER, VIEWABLE, CORR_METHOD, 
	REPORT_DESC, LOAD_TIME, REPORT_NAME, ADDRESSEE_EMAIL, 
	VIEWED, CREATE_DATE, MAINFRAME_REGION, DCN,
	SUBJECT_LINE, DOC_SOURCE, DOC_COMMENT, WORKFLOW,
	DOC_DELETE, Region, ErrorText, ErrorFileName)
VALUES
(@path, @SSN, @DOC_DATE, @DOC_ID, @ADDR_ACCT_NUM,
@LETTER_ID, @REQUEST_USER, @VIEWABLE, @CORR_METHOD, 
@REPORT_DESC, @LOAD_TIME, @REPORT_NAME, @ADDRESSEE_EMAIL,
@VIEWED, @CREATE_DATE, @MAINFRAME_REGION, @DCN,
@SUBJECT_LINE, @DOC_SOURCE, @DOC_COMMENT, @WORKFLOW,
@DOC_DELETE, @Region, @ErrorText, @ErrorFileName)

