CREATE TABLE [dbo].[LN15_DSB](
	[BF_SSN] [char](9) NOT NULL,
	[LN_BR_DSB_SEQ] [smallint] NOT NULL,
	[LA_DSB] [numeric](8, 2) NOT NULL,
	[LA_DSB_CAN] [numeric](8, 2) NULL,
	[LC_DSB_CAN_TYP] [char](1) NOT NULL,
	[LC_RCP_CHK_DSB] [char](1) NOT NULL,
	[LD_CAN_RPT_GTR] [date] NULL,
	[LD_DSB] [date] NOT NULL,
	[LD_DSB_RPT_GTR] [date] NULL,
	[LF_DSB_CHK] [varchar](10) NOT NULL,
	[LC_DSB_TYP] [char](1) NOT NULL,
	[LD_DSB_CAN] [date] NULL,
	[LI_LTE_DSB_APV] [char](1) NOT NULL,
	[LF_RCP_DSB_CHK] [varchar](9) NOT NULL,
	[LC_LDR_DSB_MDM] [char](1) NOT NULL,
	[LI_RDS] [char](1) NOT NULL,
	[LD_DSB_ROS_PRT] [date] NULL,
	[LR_DSB_ITR] [numeric](5, 3) NULL,
	[LD_STA_LON15] [date] NULL,
	[LC_STA_LON15] [char](1) NOT NULL,
	[LD_EFT_FND_RLS] [date] NULL,
	[LD_EFT_RLS] [date] NULL,
	[LF_LST_DTS_LN15] [datetime2](7) NOT NULL,
	[LR_IRM_APR] [numeric](5, 3) NULL,
	[LI_IDF_SIG] [char](1) NOT NULL,
	[AF_DSB_RPT] [varchar](8) NOT NULL,
	[LN_SEQ] [smallint] NULL,
	[AN_SEQ] [smallint] NULL,
	[IC_LON_PGM] [varchar](6) NULL,
	[LR_RPD_APR] [numeric](5, 3) NULL,
	[LA_PCV_LDR_CHK] [numeric](8, 2) NULL,
	[LC_DSB_RLS_STA] [char](1) NULL,
	[LC_LON_EXT_ORG_SRC] [char](1) NOT NULL,
	[LN_LON_DSB_SEQ] [smallint] NOT NULL,
	[LA_DSB_ORG_CHK_EFT] [numeric](8, 2) NULL,
	[LA_DSB_CAN_PCV] [numeric](8, 2) NULL,
	[LD_PRE_DSB_ROS_SNT] [date] NULL,
	[LD_SCL_DSB_ATH_RCV] [date] NULL,
	[LC_DSB_CAN_PCV] [char](1) NOT NULL,
	[LC_CMN_LN_HLD_RLS] [char](1) NOT NULL,
	[LC_PAY_DSB_CAN_LTR] [varchar](2) NOT NULL,
	[LD_PAY_DSB_CAN_LTR] [date] NULL,
	[LD_PRE_DSB_PRE_ROS] [date] NULL,
	[LA_PRE_DSB_CAN] [numeric](8, 2) NULL,
	[LD_PRE_DSB_CAN] [date] NULL,
	[LN_CMN_LN_DSB_SEQ] [smallint] NULL,
	[AF_APL_ID] [varchar](9) NULL,
	[LD_NTF_SCL_CDA] [date] NULL,
	[LD_NTF_OWN] [date] NULL,
	[LN_DSB_SUM_SEQ] [smallint] NULL,
	[LC_REU_REA] [varchar](2) NOT NULL,
	[IF_CDA] [varchar](8) NOT NULL,
	[LC_DSB_CAN_REA] [varchar](4) NOT NULL,
	[LC_DSB_EVT_LN15] [varchar](2) NOT NULL,
	[LF_LST_USR_LN15] [varchar](8) NOT NULL,
	[LF_DSB_EVT_LN15] [datetime2](7) NULL,
	[LD_DSB_RLS_STA] [date] NULL,
	[LA_DSB_RAL] [numeric](8, 2) NULL,
	[LD_DSB_RAL] [date] NULL,
	[LC_DSB_TYP_RAL] [char](1) NOT NULL,
	[LC_DSB_SRC_RAL] [char](1) NOT NULL,
	[LC_LO_AUT_RAL] [varchar](2) NOT NULL,
	[LC_DSB_IN_ERR] [char](1) NOT NULL,
	[LI_DSB_DIR_BR] [char](1) NOT NULL,
	[LC_DSB_DIR_BR_VER] [char](1) NOT NULL,
	[AN_LC_APL_SEQ] [smallint] NULL,
	[LA_DSB_CAN_PCV_RFD] [numeric](8, 2) NULL,
	[LA_DSB_CAN_RFD] [numeric](8, 2) NULL,
	[LD_DSB_CAN_RFD] [date] NULL,
	[LD_DSB_RFD_RPT_GTR] [date] NULL,
	[LF_ECA_LON_SCH_BCH] [varchar](3) NOT NULL,
	[LF_ECA_CTD] [varchar](8) NOT NULL,
	[LD_ECA_LON_SCH_CRT] [date] NULL,
	[LD_ECA_DSB_FUD] [date] NULL,
	[LC_DSB_ACH_OWN] [varchar](3) NOT NULL,
	[LC_DSB_ACH_SCL] [varchar](3) NOT NULL,
	[LA_DL_DSB_REB] [numeric](12, 2) NULL,
	[LA_DSB_REB_CAN] [numeric](12, 2) NULL,
	[LA_PCV_DSB_REB_CAN] [numeric](12, 2) NULL,
	[LC_CNL_DSB_CAN_REA] [varchar](1) NOT NULL,
	[LA_PRE_DSB_CAN_RPT] [numeric](12, 2) NULL,
	[LD_PRE_DSB_CAN_RPT] [date] NULL,
	[LD_DSB_ACP_FR_COD] [date] NULL,
	[LN_DL_DSB_PAY_SEQ] [smallint] NULL,
	[LF_DL_SCL_ENR_DSB] [varchar](8) NOT NULL,
	[LD_COD_DSB_PST] [date] NULL,
	[LC_CIP] [varchar](7) NOT NULL,
	[LC_DSB_ACP_MTD] [varchar](2) NOT NULL
) ON [PRIMARY]