/*DSASG05*/
/*ACCOUNT HELD*/

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;

PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE DEMO AS
SELECT *
FROM CONNECTION TO DB2 (

SELECT GA01.AF_APL_ID
/*	,GA01.DF_PRS_ID_BR*/
/*	,GA01.DF_PRS_ID_STU*/
	,PD01B.DF_SPE_ACC_ID	AS DF_PRS_ID_BR
	,PD01S.DF_SPE_ACC_ID	AS DF_PRS_ID_STU
	
FROM	OLWHRM1.GA01_APP GA01
INNER JOIN OLWHRM1.GA10_LON_APP GA10
ON GA01.AF_APL_ID = GA10.AF_APL_ID
AND GA10.AC_LON_TYP IN ('PL','SF','SU')
AND GA10.AC_PRC_STA IN ('M')
AND GA10.AC_APL_SPS_REA_1 NOT IN ('A','R','X')
INNER JOIN OLWHRM1.PD01_PDM_INF PD01B
ON PD01B.DF_PRS_ID = GA01.DF_PRS_ID_BR
AND PD01B.DC_PRS_HLD_REA_1 = ''
INNER JOIN OLWHRM1.PD01_PDM_INF PD01S
ON PD01S.DF_PRS_ID = GA01.DF_PRS_ID_STU
AND PD01S.DC_PRS_HLD_REA_1 = ''

);
DISCONNECT FROM DB2;
ENDRSUBMIT;

DATA DEMO; SET WORKLOCL.DEMO; RUN;

PROC SORT DATA=DEMO;
BY DF_PRS_ID_BR;
RUN;



/*PROC PRINTTO PRINT=REPORT2;
RUN;*/
/*For landscape reports:*/
/*OPTIONS ORIENTATION = LANDSCAPE;*/
/*OPTIONS PS=39 LS=127;*/

/*For portrait reports;*/
OPTIONS ORIENTATION = PORTRAIT;
OPTIONS PS=52 LS=96;

PROC PRINT NOOBS SPLIT='/' DATA=WORKLOCL.DEMO;

VAR AF_APL_ID
	DF_PRS_ID_BR
	DF_PRS_ID_STU;
LABEL	DF_PRS_ID_BR = 'BORROWER ACCOUNT NUMBER'
		DF_PRS_ID_STU = 'STUDENT ACCOUNT NUMBER'
		AF_APL_ID = 'ACCOUNT NUMBER';
TITLE 'ACCOUNT HELD';
FOOTNOTE  'JOB = DSASG05     REPORT = DSASG05R2';
RUN;



/*PROC EXPORT DATA=DEMO*/
/*            OUTFILE= "T:\SAS\DEMO.xls" */
/*            DBMS=EXCEL2000 REPLACE;*/
/*RUN;*/
