/*DSASQ04 APPROVED SCHOOLS FOR CONSOLIDATION LOANS*/

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE APSFCL AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT A.IF_DOE_SCL
FROM OLWHRM1.SC20_SCH_GTR A
WHERE A.IF_GTR = '000749'
ORDER BY A.IF_DOE_SCL
);
DISCONNECT FROM DB2;
ENDRSUBMIT;

DATA APSFCL;
SET WORKLOCL.APSFCL;
RUN;

DATA _NULL_;
SET  WORK.APSFCL;
FILE 'T:\SAS\DSASQ04.R2' DELIMITER=',' DSD DROPOVER LRECL=32767;
FORMAT IF_DOE_SCL $8. ;
PUT IF_DOE_SCL $ ;
RUN;
