*--------------------------------------------*
| ELM SCHOOLS RECEIVING PAPER CHECK 		 |
*--------------------------------------------*;
%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/ElmSchoolsReceivingPaperCheck.R2.txt";
LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE ESRPC AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT D.IF_DOE_SCL 
	,C.IM_SCL_FUL 
	,D.IX_SCL_STR_ADR_1
	,D.IX_SCL_STR_ADR_2
	,D.IX_SCL_STR_ADR_3
	,D.IM_SCL_CT
	,D.IC_SCL_DOM_ST
	,D.IF_SCL_ZIP_CDE
FROM OLWHRM1.SC22_SCH_STA_TRK A
INNER JOIN OLWHRM1.SC10_SCH_DMO C
	ON A.IF_DOE_SCL = C.IF_DOE_SCL
INNER JOIN OLWHRM1.SC25_SCH_DPT D
	ON C.IF_DOE_SCL = D.IF_DOE_SCL
LEFT JOIN OLWHRM1.SC26_DSB_SCH B
	ON A.IF_DOE_SCL = B.IF_DOE_SCL
	AND A.IC_LON_PGM = B.IC_LON_PGM
WHERE A.IF_SBU = 'ELMRES'
	AND COALESCE(B.IC_DSB_MDM,'0') <> '7'
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
ENDRSUBMIT;
DATA ESRPC ;
	SET WORKLOCL.ESRPC;
RUN;
PROC SORT DATA=ESRPC NODUPKEY;
	BY IF_DOE_SCL;
RUN;
DATA _NULL_;
SET  WORK.ESRPC ;
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
   FORMAT IF_DOE_SCL $8. ;
   FORMAT IM_SCL_FUL $40. ;
   FORMAT IX_SCL_STR_ADR_1 $30. ;
   FORMAT IX_SCL_STR_ADR_2 $30. ;
   FORMAT IX_SCL_STR_ADR_3 $30. ;
   FORMAT IM_SCL_CT $20. ;
   FORMAT IC_SCL_DOM_ST $2. ;
   FORMAT IF_SCL_ZIP_CDE $9. ;
DO;
   PUT IF_DOE_SCL $ @;
   PUT IM_SCL_FUL $ @;
   PUT IX_SCL_STR_ADR_1 $ @;
   PUT IX_SCL_STR_ADR_2 $ @;
   PUT IX_SCL_STR_ADR_3 $ @;
   PUT IM_SCL_CT $ @;
   PUT IC_SCL_DOM_ST $ @;
   PUT IF_SCL_ZIP_CDE $ ;
END;
RUN;
