/*DSASG13*/
/*LCO DUPLICATE LOAN*/

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;

PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE DEMO AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT
	DF_LCO_PRS_SSN_BR
	,LN_LCO_UND_LN_SEQ
	,IF_UND_LN_CDR
	,INTEGER(LA_UND_LN_BAL) AS LA_UND_LN_BAL
	,LR_UND_LN_INT

FROM	OLWHRM1.LC10_UND_LN_INF
WHERE LI_UND_LN_CON = 'N'

);


CREATE TABLE DEMO2 AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT
	DF_LCO_PRS_SSN_BR
	,LN_LCO_UND_LN_SEQ
	,IF_UND_LN_CDR
	,INTEGER(LA_UND_LN_BAL) AS LA_UND_LN_BAL
	,LR_UND_LN_INT

FROM	OLWHRM1.LC10_UND_LN_INF
WHERE LI_UND_LN_CON = 'Y'

);
DISCONNECT FROM DB2;
ENDRSUBMIT;

DATA DEMO; SET WORKLOCL.DEMO; RUN;
DATA DEMO2; SET WORKLOCL.DEMO2; RUN;

PROC SQL;
CREATE TABLE DEMO3 AS
SELECT DISTINCT *
FROM DEMO
INNER JOIN DEMO2
ON DEMO.DF_LCO_PRS_SSN_BR = DEMO2.DF_LCO_PRS_SSN_BR
AND DEMO.IF_UND_LN_CDR = DEMO2.IF_UND_LN_CDR
AND DEMO.LA_UND_LN_BAL = DEMO2.LA_UND_LN_BAL
AND DEMO.LR_UND_LN_INT = DEMO2.LR_UND_LN_INT

;
QUIT;

PROC SORT DATA=DEMO3;
BY DF_LCO_PRS_SSN_BR;
RUN;


/*PROC PRINTTO PRINT=REPORT2;
RUN;*/
/*For landscape reports:*/
/*OPTIONS ORIENTATION = LANDSCAPE;*/
/*OPTIONS PS=39 LS=127;*/

/*For portrait reports;*/
OPTIONS ORIENTATION = PORTRAIT;
OPTIONS PS=52 LS=96;

PROC PRINT NOOBS SPLIT='/' DATA=DEMO3;
BY DF_LCO_PRS_SSN_BR;
VAR DF_LCO_PRS_SSN_BR LN_LCO_UND_LN_SEQ IF_UND_LN_CDR LA_UND_LN_BAL LR_UND_LN_INT;
LABEL	DF_LCO_PRS_SSN_BR = 'SSN'
		LN_LCO_UND_LN_SEQ = 'LOAN SEQ'
		IF_UND_LN_CDR = 'CREDITOR CODE'
		LA_UND_LN_BAL = 'BALANCE'
		LR_UND_LN_INT = 'INTEREST RATE';


TITLE 'LCO DUPLICATE LOANS';
FOOTNOTE  'JOB = DSASG13     REPORT = DSASG13R2';
RUN;



/*PROC EXPORT DATA=WORKLOCL.DEMO*/
/*            OUTFILE= "T:\SAS\DEMO.xls" */
/*            DBMS=EXCEL2000 REPLACE;*/
/*RUN;*/