/*QSASE02 - IDENTIFY SCHOOLS WITH A PLUS FORM CODE = 4*/

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE SINFO AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT
	 A.IM_IST_FUL
	,A.IF_IST
	,A.IC_FRM_OPT
	,A.IC_PLS_FRM_OPT
	,A.IN_CNL_APL_FIL_VRS
FROM	OLWHRM1.SC01_LGS_SCL_INF A
WHERE	A.IC_PLS_FRM_OPT = '4'
ORDER BY A.IF_IST
);
DISCONNECT FROM DB2;
ENDRSUBMIT;

DATA SINFO;
SET WORKLOCL.SINFO;
RUN;

DATA _NULL_;
CALL SYMPUT('RUNDATE',PUT(INTNX('DAY',TODAY(),0,'beginning'), MMDDYY10.));
RUN;

OPTIONS CENTER NODATE NUMBER PAGENO=1 LS=90;
PROC PRINT NOOBS SPLIT='/' DATA=SINFO WIDTH=UNIFORM WIDTH=MIN;
VAR IM_IST_FUL IF_IST IC_PLS_FRM_OPT;
LABEL IM_IST_FUL='SCHOOL NAME' IF_IST='SCHOOL ID' 
IC_PLS_FRM_OPT='PLUS FORM TYPE';
TITLE 'SCHOOLS USING THE PLUS MPN';
TITLE2 '(PLUS FORM TYPE CODE = 4)';
TITLE3 "RUN DATE:  &RUNDATE.";
FOOTNOTE  'JOB = QSASE01     REPORT = QSASE01.R2';
RUN;