/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
/*FILENAME REPORT2 "&RPTLIB/ULW___.LW___R2";*/

libname  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=work  ;
RSUBMIT;

PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE DEMO AS
SELECT *
FROM CONNECTION TO DB2 (

SELECT X.BF_SSN
,X.AN_SEQ
,X.LN_SEQ
,x.LN_LON_DSB_SEQ
,Y.IF_GTR
,x.LA_DSB
,x.LA_DSB_CAN
FROM OLWHRM1.LN15_DSB X 
INNER JOIN OLWHRM1.AP20_APL_LON Y
	ON Y.BF_SSN = X.BF_SSN
	AND Y.AN_SEQ = X.AN_SEQ
WHERE X.LC_DSB_TYP = '1' /*ANTICIPATED DISBS*/
AND X.LC_STA_LON15 IN ('1','3') /*ONLY SELECT ACTIVE DISB ROWS*/
AND Y.IF_GTR = '000800'
);
DISCONNECT FROM DB2;
ENDRSUBMIT;

DATA DEMO; 
SET WORKLOCL.DEMO; 
RUN;

/*PROC PRINTTO PRINT=REPORT2;*/
/*RUN;*/
OPTIONS CENTER NODATE NUMBER PAGENO=1 LS=126;
PROC PRINT NOOBS SPLIT='/' DATA=DEMO WIDTH=UNIFORM WIDTH=MIN;
title;
footnote;
RUN;