/*UTLWQ11 BORROWERS WITH ERROR STATUS ON COMPASS LS*/
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
%LET RPTLIB = %SYSGET(reportdir);
FILENAME REPORT2 "&RPTLIB/ULWQ11.LWQ11R2";*/

%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/ULWQ11.LWQ11R2.txt";
LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;

PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE BESCLS AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT   A.BF_SSN
		,A.LN_SEQ
		,B.WC_DW_LON_STA
		,A.LF_LON_CUR_OWN
		,C.DF_SPE_ACC_ID
	
FROM	 OLWHRM1.LN10_LON A
		INNER JOIN OLWHRM1.DW01_DW_CLC_CLU B
		 ON A.BF_SSN = B.BF_SSN
		 AND A.LN_SEQ = B.LN_SEQ
		INNER JOIN OLWHRM1.PD10_PRS_NME C
		 ON A.BF_SSN = C.DF_PRS_ID

WHERE	A.LC_STA_LON10 = 'R'
AND 	A.LA_CUR_PRI > 0
AND 	B.WC_DW_LON_STA IN ('88','98')
/*AND 	B.WC_DW_LON_STA IN ('18','17') USED IN TESTING*/
);
DISCONNECT FROM DB2;

ENDRSUBMIT;
DATA BESCLS;
SET WORKLOCL.BESCLS;
RUN;

PROC SORT DATA=BESCLS;
BY DF_SPE_ACC_ID;
RUN;

PROC PRINTTO PRINT=REPORT2 NEW;
RUN;
OPTIONS PAGENO=1 LS=126;
PROC PRINT NOOBS SPLIT='/' DATA=BESCLS;
VAR DF_SPE_ACC_ID
	LN_SEQ
	WC_DW_LON_STA
	LF_LON_CUR_OWN;
LABEL	DF_SPE_ACC_ID = 'ACCT NUM'
		LN_SEQ = 'LOAN SEQ'
		WC_DW_LON_STA = 'DW LOAN STATUS'
		LF_LON_CUR_OWN = 'CURRENT OWNER';
TITLE	'BORROWERS WITH ERROR STATUS ON COMPASS LS';
FOOTNOTE  'JOB = UTLWQ11  	 REPORT = ULWQ11.LWQ11R2';
RUN;

PROC PRINTTO;
RUN;
