/*=====================================================*/
/*UTLWG79 Consolidation Loan with Duplicate File Number*/
/*=====================================================*/
LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
%LET RPTLIB = %SYSGET(reportdir);
/*%LET RPTLIB = T:\SAS;*/
FILENAME REPORT2 "&RPTLIB/ULWG79.LWG79R2";
FILENAME REPORTZ "&RPTLIB/ULWG79.LWG79RZ";
DATA _NULL_;
    CALL SYMPUT('RUNDT',PUT(INTNX('DAY',TODAY(),0,'BEGINNING'), MMDDYYS10.));
RUN;
/*LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;*/
/*RSUBMIT;*/
%MACRO SQLCHECK (SQLRPT= );
%IF &SQLXRC NE 0 %THEN %DO;
	FILENAME REPORTZ "&RPTLIB/&SQLRPT";
	DATA _NULL_;
    FILE REPORTZ NOTITLES;
    PUT @01 " ********************************************************************* "
      / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
      / @01 " ****  THE SAS LOG IN &SQLRPT SHOULD BE REVIEWED.          **** "       
      / @01 " ********************************************************************* "
      / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
      / @01 " ****  &SQLXMSG   **** "
      / @01 " ********************************************************************* ";
	RUN;
%END;
%MEND;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE CLWDFNQC AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT B.DF_SPE_ACC_ID
	,A.AN_LCO_APL_SEQ
	,A.AD_LCO_APL_DSB 
	,A.AF_LCO_APL_FIL1
	,A.AF_CRT_USR_AP1A
	,B.DM_LCO_PRS_LST
	,A.AD_CRT_AP1A
	,A.AD_LCO_APL_DSB
FROM OLWHRM1.AP1A_LCO_APL A
INNER JOIN OLWHRM1.PD6A_LCO_PRS_DMO B
	ON A.DF_LCO_PRS_SSN_BR = B.DF_LCO_PRS_SSN
WHERE EXISTS
	(SELECT X.DF_LCO_PRS_SSN_BR 
		,COUNT(*) 
	 FROM OLWHRM1.AP1A_LCO_APL X
	 WHERE X.DF_LCO_PRS_SSN_BR = A.DF_LCO_PRS_SSN_BR
	 GROUP BY X.DF_LCO_PRS_SSN_BR 
	 HAVING COUNT(*) > 1)	 
AND EXISTS
	(SELECT *
	 FROM OLWHRM1.AP1A_LCO_APL Y
	 WHERE Y.DF_LCO_PRS_SSN_BR = A.DF_LCO_PRS_SSN_BR
	 AND Y.AD_LCO_APL_DSB IS NULL)

FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>>  ;  * INCLUDES ERROR MESSAGES TO SAS LOG  ;
%SQLCHECK (SQLRPT=ULWG79.LWG79RZ);
QUIT;
/*ENDRSUBMIT;*/
/*DATA CLWDFNQC;*/
/*SET WORKLOCL.CLWDFNQC;*/
/*RUN;*/
PROC SORT DATA=CLWDFNQC;
BY DF_SPE_ACC_ID AN_LCO_APL_SEQ;
RUN;
PROC SQL;
CREATE TABLE CLWDFNL AS 
SELECT DISTINCT A.*
FROM CLWDFNQC A
INNER JOIN CLWDFNQC B
	ON A.DF_SPE_ACC_ID = B.DF_SPE_ACC_ID
	AND A.AF_LCO_APL_FIL1 = B.AF_LCO_APL_FIL1
	AND A.AN_LCO_APL_SEQ <> B.AN_LCO_APL_SEQ
ORDER BY A.DF_SPE_ACC_ID
;
QUIT;
RUN;
PROC PRINTTO PRINT=REPORT2 NEW;
RUN;
OPTIONS ORIENTATION = LANDSCAPE;
OPTIONS PS=39 LS=127 PAGENO=1 CENTER;
TITLE 'CONSOLIDATION LOANS WITH DUPLICATE FILE NUMBER QC';
TITLE2	"RUNDATE &RUNDT";
FOOTNOTE 'JOB = UTLWG79  	 REPORT = ULWG79.LWG79R2';

PROC CONTENTS DATA=CLWDFNL OUT=EMPTYSET NOPRINT;
DATA _NULL_;
SET EMPTYSET;
FILE PRINT;
IF  NOBS=0 AND _N_ =1 THEN DO;
	PUT // 126*'-';
	PUT      ////////
		@51 '**** NO OBSERVATIONS FOUND ****';
	PUT ////////
		@57 '-- END OF REPORT --';
	PUT ///////////
		@46 "JOB = UTLWG79  	 REPORT = ULWG79.LWG79R2";
	END;
RETURN;
RUN;

PROC REPORT DATA=CLWDFNL SPLIT='/' HEADSKIP NOWD;
COLUMN DF_SPE_ACC_ID DM_LCO_PRS_LST AN_LCO_APL_SEQ AF_LCO_APL_FIL1 AF_CRT_USR_AP1A AD_CRT_AP1A;
DEFINE DF_SPE_ACC_ID/DISPLAY 'ACCT #' WIDTH=10 FORMAT=$10.;
DEFINE DM_LCO_PRS_LST/DISPLAY 'LAST NAME' WIDTH=23 FORMAT=$23.;
DEFINE AN_LCO_APL_SEQ/DISPLAY 'TOMD/LOAN/SEQ #' WIDTH=10 FORMAT=$2.;
DEFINE AF_LCO_APL_FIL1/DISPLAY 'FILE/NUMBER' WIDTH=11 FORMAT=$6.;
DEFINE AF_CRT_USR_AP1A/DISPLAY 'USER ID' WIDTH=11 FORMAT=$8.;
DEFINE AD_CRT_AP1A/DISPLAY 'DATE CREATED' WIDTH=12 FORMAT=MMDDYY10.;
RUN;

PROC PRINTTO;
RUN;
