/*UTLWO06 - REPAYMENT SCHEDULE ERRORS*/

/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
%LET RPTLIB = %SYSGET(reportdir);
FILENAME REPORT2 "&RPTLIB/ULWO06.LWO06R2";*/

libname  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=work  ;
RSUBMIT;
OPTIONS NOCENTER NODATE NONUMBER LS=132;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE RPSCER AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT INTEGER(A.BF_SSN) AS BF_SSN
,RTRIM(D.DM_PRS_1)||' '||RTRIM(D.DM_PRS_LST) AS NAME
,A.IC_LON_PGM
,A.LD_LON_1_DSB
,A.LN_SEQ
,F.LD_SCL_SPR
,C.WD_LON_RPD_SR
,RS10.LD_RPS_1_PAY_DU
,RS10.LD_SNT_RPD_DIS
,PD30.DI_VLD_ADR
,DAYS(RS10.LD_SNT_RPD_DIS)
,DAYS(RS10.LD_RPS_1_PAY_DU)
,DAYS(RS10.LD_RPS_1_PAY_DU) - 30

FROM  OLWHRM1.LN10_LON A 
INNER JOIN OLWHRM1.LN65_LON_RPS B
	ON A.BF_SSN = B.BF_SSN
	AND A.LN_SEQ = B.LN_SEQ
	AND B.LC_STA_LON65 = 'A'
INNER JOIN OLWHRM1.RS10_BR_RPD RS10
	ON A.BF_SSN = RS10.BF_SSN
	AND B.LN_RPS_SEQ = RS10.LN_RPS_SEQ
	AND RS10.LC_STA_RPST10 = 'A'
INNER JOIN OLWHRM1.DW01_DW_CLC_CLU C
	ON A.BF_SSN = C.BF_SSN
	AND A.LN_SEQ = C.LN_SEQ
INNER JOIN OLWHRM1.PD10_PRS_NME D
	ON A.BF_SSN = D.DF_PRS_ID
INNER JOIN OLWHRM1.LN13_LON_STU_OSD E
	ON A.BF_SSN = E.BF_SSN
	AND A.LN_SEQ = E.LN_SEQ
	AND E.LC_STA_LON13 = 'A'
INNER JOIN OLWHRM1.SD10_STU_SPR F
	ON E.LF_STU_SSN = F.LF_STU_SSN
	AND E.LN_STU_SPR_SEQ = F.LN_STU_SPR_SEQ
	AND F.LC_STA_STU10 = 'A'
INNER JOIN OLWHRM1.PD30_PRS_ADR PD30
	ON A.BF_SSN = PD30.DF_PRS_ID
	AND PD30.DC_ADR = 'L'
INNER JOIN OLWHRM1.DW01_DW_CLC_CLU DW01
	ON A.BF_SSN = DW01.BF_SSN
	AND A.LN_SEQ = DW01.LN_SEQ

WHERE A.IC_LON_PGM IN ('STFFRD','UNSTFD','PLUS')
AND C.WD_LON_RPD_SR < CURRENT DATE
AND (DAYS(RS10.LD_SNT_RPD_DIS) 
	BETWEEN (DAYS(RS10.LD_RPS_1_PAY_DU) - 29) AND DAYS(RS10.LD_RPS_1_PAY_DU))

AND B.LC_TYP_SCH_DIS = 'L'
AND DW01.WC_DW_LON_STA <> '06'
AND PD30.DD_VER_ADR < RS10.LD_STA_RPST10
AND RS10.LD_SNT_RPD_DIS > '07/07/2003'

);
DISCONNECT FROM DB2;

PROC SORT DATA = RPSCER;
BY BF_SSN;
RUN;

ENDRSUBMIT  ;
DATA RPSCER; 
SET WORKLOCL.RPSCER; 
RUN;

DATA _NULL_;
CALL SYMPUT('RUNDATE',PUT(INTNX('DAY',TODAY(),0,'beginning'), MMDDYY10.));
RUN;

/*PROC PRINTTO PRINT=REPORT2;
RUN;*/
OPTIONS CENTER NODATE NUMBER PAGENO=1 LS=132;
TITLE 'REPAYMENT SCHEDULE ERRORS';
TITLE2 "&RUNDATE";

PROC CONTENTS DATA=RPSCER OUT=EMPTYSET NOPRINT;
DATA _NULL_;
SET EMPTYSET;
FILE PRINT;
IF  NOBS=0 AND _N_ =1 THEN DO;
	PUT // 132  *'-';
	PUT      ////////
		@51 '**** NO OBSERVATIONS FOUND ****';
	PUT ////////
		@57 '-- END OF REPORT --';
	PUT ////////////////
		@46 'JOB = UTLWO06     REPORT = ULWO06.LWO06R2';
	END;
RETURN;
run;
PROC PRINT NOOBS SPLIT='/' DATA=RPSCER WIDTH=UNIFORM WIDTH=MIN;
VAR BF_SSN NAME IC_LON_PGM LD_LON_1_DSB LN_SEQ 
LD_SCL_SPR WD_LON_RPD_SR LD_RPS_1_PAY_DU LD_SNT_RPD_DIS /*DI_VLD_ADR*/;
LABEL BF_SSN='BORROWER SSN' NAME='BORROWER NAME'
IC_LON_PGM='LOAN PROGRAM' LD_LON_1_DSB='1ST DISB DATE' LN_SEQ='LOAN SEQUENCE'
LD_SCL_SPR='SEPARATION DATE' WD_LON_RPD_SR='REPAYMENT START' 
LD_RPS_1_PAY_DU='1ST DUE DATE' LD_SNT_RPD_DIS='DISCLOSURE PRINT DATE'
/*DI_VLD_ADR='VALID ADDRESS INDICATOR'*/;
FORMAT BF_SSN SSN11. LD_LON_1_DSB LD_SCL_SPR WD_LON_RPD_SR LD_SNT_RPD_DIS
LD_RPS_1_PAY_DU MMDDYY10.;
TITLE 'REPAYMENT SCHEDULE ERRORS';
TITLE2 "&RUNDATE";
FOOTNOTE  'JOB = UTLWO06     REPORT = ULWO06.LWO06R2';
RUN;