OPTIONS NOCENTER NODATE NONUMBER LS=132 ;



%let  rptlib = %sysget(reportdir)  ;

filename report2  "&rptlib/ULWG2W.LWG2WR2"  ;

DATA NULLRPT  ;  STRING= "***   END OF REPORT   ***"  ;  RUN ;

PROC SQL  ;
CONNECT TO DB2 (database=dlgsutwh);
CREATE TABLE ONEMPN AS
SELECT *
FROM CONNECTION TO DB2  (
SELECT DISTINCT
  SUBSTR(A.DF_PRS_ID_BR,1,3)||'-'||SUBSTR(A.DF_PRS_ID_BR,4,2)||
         '-'||SUBSTR(A.DF_PRS_ID_BR,6,4) AS SSNB,
  A.AF_APL_OPS_SCL      AS SCODE,
  B.AD_PRC              AS DPROC,
  C.DM_PRS_MID          AS MID,
  C.DM_PRS_1            AS FIRST,
  C.DM_PRS_LST          AS LAST,
  B.AF_APL_ID||B.AF_APL_ID_SFX   AS UID
FROM
  OLWHRM1.GA01_APP A INNER JOIN OLWHRM1.GA10_LON_APP B
                  ON A.AF_APL_ID = B.AF_APL_ID
         INNER JOIN OLWHRM1.PD01_PDM_INF C
                  ON A.DF_PRS_ID_BR = C.DF_PRS_ID
WHERE
  A.AD_BR_SIG IS NULL
  AND A.AC_FRM_RVS = '09901'
  AND B.AC_PRC_STA = 'P'
  AND B.AD_PRC >= CURRENT DATE - 90 DAYS
  ) ;

    DISCONNECT FROM DB2 ;
  %PUT &SQLXRC& &SQLXMSG& ;

DATA ONEMPN ;
 SET ONEMPN ;

  NAME = TRIM(LAST)||','||TRIM(FIRST)||' '||MID ;
RUN ;

PROC SORT DATA=ONEMPN ;
 BY SCODE NAME DPROC ;
RUN ;

proc printto print=report2 ;
run  ;

PROC PRINT NOOBS N DATA=ONEMPN SPLIT='/' ;
 BY SCODE ;
 PAGEBY SCODE ;
 VAR NAME SSNB UID DPROC ;
 FORMAT DPROC MMDDYY10.  ;
 LABEL SSNB  = "BORROWER'S/SSN"
       UID   = "UNIQUE ID"
       DPROC = "DATE/PROCESSED"
       NAME  = "BORROWER'S/NAME"
       SCODE = "SCHOOL"
       ;
TITLE "PROVISIONAL MPN APPS PROCESSED IN THE LAST 90 DAYS NEEDING CERTIFIED" ;
FOOTNOTE 'MEM, NS4-LWG2W.SAS';
RUN ;

PROC PRINT DATA = NULLRPT ; RUN ;


