*-----------------------------------*
| UTLWG89 - D7						|
*-----------------------------------*;
LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
%LET RPTLIB = %SYSGET(reportdir);
/*%LET RPTLIB = T:\SAS;*/
FILENAME REPORT2 "&RPTLIB/ULWG89.LWG89R2";
FILENAME REPORTZ "&RPTLIB/ULWG89.LWG89RZ";

DATA _NULL_;
     CALL SYMPUT('SVN_DYS_AGO',"'"||PUT(INTNX('DAY',TODAY(),-7,'BEGINNING'), MMDDYYD10.)||"'");
RUN;
%LET CDATE = '04/01/2006';

/*%SYSLPUT CDATE = &CDATE;*/
/*%SYSLPUT SVN_DYS_AGO = &SVN_DYS_AGO;*/
/*LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;*/
/*RSUBMIT;*/
%MACRO SQLCHECK (SQLRPT= );
%IF &SQLXRC NE 0 %THEN %DO;
	DATA _NULL_;
    FILE REPORTZ NOTITLES;
    PUT @01 " ********************************************************************* "
      / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
      / @01 " ****  THE SAS LOG IN &SQLRPT SHOULD BE REVIEWED.          **** "       
      / @01 " ********************************************************************* "
      / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
      / @01 " ****  &SQLXMSG   **** "
      / @01 " ********************************************************************* ";
	RUN;
%END;
%MEND;
PROC SQL STIMER;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE D7DS AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT A.DF_LCO_PRS_SSN_BR
	,D.DM_LCO_PRS_1
	,D.DM_LCO_PRS_MI
	,D.DM_LCO_PRS_LST
	,D.DX_LCO_PRS_STR_1
	,D.DX_LCO_PRS_STR_2
	,D.DX_LCO_PRS_STR_3
	,D.DM_LCO_PRS_CT
	,D.DC_LCO_PRS_ST
	,D.DF_LCO_PRS_ZIP
	,D.DF_SPE_ACC_ID
	,D.DM_LCO_PRS_FGN_ST
	,D.DM_LCO_PRS_FGN_CNY
	,O1.PF_ACT 		AS OL_H8WVR
	,C1.PF_REQ_ACT 	AS CO_H8WVR
	,O2.PF_ACT 		AS OL_G7DEN
	,C2.PF_REQ_ACT	AS CO_G7DEN 
FROM OLWHRM1.AP1A_LCO_APL A
INNER JOIN OLWHRM1.PD6A_LCO_PRS_DMO D
	ON A.DF_LCO_PRS_SSN_BR = D.DF_LCO_PRS_SSN
LEFT OUTER JOIN OLWHRM1.AY01_BR_ATY O1
	ON A.DF_LCO_PRS_SSN_BR = O1.DF_PRS_ID
	AND O1.PF_ACT = 'H8WVR'
	AND O1.BD_ATY_PRF >= &CDATE
LEFT OUTER JOIN OLWHRM1.AY10_BR_LON_ATY C1
	ON A.DF_LCO_PRS_SSN_BR = C1.BF_SSN
	AND C1.PF_REQ_ACT = 'H8WVR'
	AND C1.LD_ATY_REQ_RCV >= &CDATE
LEFT OUTER JOIN OLWHRM1.AY01_BR_ATY O2
	ON A.DF_LCO_PRS_SSN_BR = O2.DF_PRS_ID
	AND O2.PF_ACT = 'G7DEN'
	AND O2.BD_ATY_PRF >= &SVN_DYS_AGO
LEFT OUTER JOIN OLWHRM1.AY10_BR_LON_ATY C2
	ON A.DF_LCO_PRS_SSN_BR = C2.BF_SSN
	AND C2.PF_REQ_ACT = 'G7DEN'
	AND C2.LD_ATY_REQ_RCV >= &SVN_DYS_AGO
WHERE A.AC_LCO_ACC_STA = 'D7'
FOR READ ONLY WITH UR
);
%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>>  ;  * INCLUDES ERROR MESSAGES TO SAS LOG  ;
%SQLCHECK (SQLRPT=ULWG89.LWG89RZ);
QUIT;
/*ENDRSUBMIT;*/
/**/
/*DATA D7DS;*/
/*SET WORKLOCL.D7DS;*/
/*RUN;*/

DATA D7DS;
SET D7DS;
IF (OL_H8WVR ^= '' OR CO_H8WVR ^= '') AND (OL_G7DEN ^= '' OR CO_G7DEN ^= '') 
	THEN OUTPUT;
ELSE 
	DELETE;
RUN;

DATA D7DS;
SET D7DS;
COST_CENTER_CODE = 'MA2324';
STATE = DC_LCO_PRS_ST;
DC_ADR = 'L';
IF DC_LCO_PRS_ST IN ('ZZ','') THEN DO;
	DC_LCO_PRS_ST = '';
	DM_LCO_PRS_FGN_ST = DM_LCO_PRS_FGN_ST;
	DM_LCO_PRS_FGN_CNY = DM_LCO_PRS_FGN_CNY;
	SVAR = 1;
	END;
ELSE DO;
	DM_LCO_PRS_FGN_ST = '';
	DM_LCO_PRS_FGN_CNY = '';
	SVAR = 2;
	END;
RUN;
/*KEYLINE CALCULATION*/
DATA D7DS (DROP = KEYSSN MODAY KEYLINE CHKDIG DIG I 
	CHKDIG CHK1 CHK2 CHK3 CHKDIGIT CHECK DC_ADR);
SET D7DS;
KEYSSN = TRANSLATE(DF_LCO_PRS_SSN_BR,'MYLAUGHTER','0987654321');
MODAY = PUT(DATE(),MMDDYYN4.);
KEYLINE = "P"||KEYSSN||MODAY||DC_ADR;
CHKDIG = 0;
LENGTH DIG $2.;
DO I = 1 TO LENGTH(KEYLINE);
	IF I/2 NE ROUND(I/2,1) 
		THEN DIG = PUT(INPUT(SUBSTR(KEYLINE,I,1),BITS4.4) * 2, 2.);
	ELSE DIG = PUT(INPUT(SUBSTR(KEYLINE,I,1),BITS4.4), 2.);
	IF SUBSTR(DIG,1,1) = " " 
		THEN CHKDIG = CHKDIG + INPUT(SUBSTR(DIG,2,1),1.);
		ELSE DO;
			CHK1 = INPUT(SUBSTR(DIG,1,1),1.);
			CHK2 = INPUT(SUBSTR(DIG,2,1),1.);
			IF CHK1 + CHK2 >= 10
				THEN DO;
					CHK3 = PUT(CHK1 + CHK2,2.);
					CHK1 = INPUT(SUBSTR(CHK3,1,1),1.);
					CHK2 = INPUT(SUBSTR(CHK3,2,1),1.);
				END;
			CHKDIG = CHKDIG + CHK1 + CHK2;
		END;
END;
CHKDIGIT = 10 - INPUT(SUBSTR((RIGHT(PUT(CHKDIG,3.))),3,1),3.);
IF CHKDIGIT = 10 THEN CHKDIGIT = 0;
CHECK = PUT(CHKDIGIT,1.);
ACSKEY = "#"||KEYLINE||CHECK||"#";
RUN;

PROC SORT DATA=D7DS;
BY SVAR STATE;
RUN;

DATA _NULL_;
SET  WORK.D7DS;
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
   FORMAT DF_LCO_PRS_SSN_BR $9. ;
   FORMAT DM_LCO_PRS_1 $13. ;
   FORMAT DM_LCO_PRS_MI $1. ;
   FORMAT DM_LCO_PRS_LST $23. ;
   FORMAT DX_LCO_PRS_STR_1 $40. ;
   FORMAT DX_LCO_PRS_STR_2 $40. ;
   FORMAT DM_LCO_PRS_CT $30. ;
   FORMAT DC_LCO_PRS_ST $3. ;
   FORMAT DF_LCO_PRS_ZIP $17. ;
   FORMAT DF_SPE_ACC_ID $10. ;
   FORMAT DM_LCO_PRS_FGN_ST $30. ;
   FORMAT DM_LCO_PRS_FGN_CNY $25. ;
   FORMAT OL_H8WVR $5. ;
   FORMAT CO_H8WVR $5. ;
   FORMAT OL_G7DEN $5. ;
   FORMAT CO_G7DEN $5. ;
   FORMAT COST_CENTER_CODE $6. ;
   FORMAT STATE $3. ;
   FORMAT SVAR BEST12. ;
   FORMAT ACSKEY $18. ;
IF _N_ = 1 THEN        
 DO;
   PUT
    'DF_LCO_PRS_SSN_BR'
    ','
	'DF_SPE_ACC_ID' 
	','
	'DM_LCO_PRS_1' 
	','
	'DM_LCO_PRS_MI' 
	','
	'DM_LCO_PRS_LST' 
	','
	'DX_LCO_PRS_STR_1' 
	','
	'DX_LCO_PRS_STR_2' 
	','
	'DM_LCO_PRS_CT' 
	','
	'DC_LCO_PRS_ST' 
	','
	'DM_LCO_PRS_FGN_ST'
	','
	'DM_LCO_PRS_FGN_CNY'
	','
	'DF_LCO_PRS_ZIP'
	','
	'ACSKEY'
	','
	'STATE' 
	','
	'COST_CENTER_CODE'
   ;
END;
DO;
   PUT DF_LCO_PRS_SSN_BR $ @;
   PUT DF_SPE_ACC_ID $ @;
   PUT DM_LCO_PRS_1 $ @;
   PUT DM_LCO_PRS_MI $ @;
   PUT DM_LCO_PRS_LST $ @;
   PUT DX_LCO_PRS_STR_1 $ @;
   PUT DX_LCO_PRS_STR_2 $ @;
   PUT DM_LCO_PRS_CT $ @;
   PUT DC_LCO_PRS_ST $ @;
   PUT DM_LCO_PRS_FGN_ST $ @;
   PUT DM_LCO_PRS_FGN_CNY $ @;
   PUT DF_LCO_PRS_ZIP $ @;
   PUT ACSKEY $ @;
   PUT STATE $ @;
   PUT COST_CENTER_CODE $ ;
   END;
RUN;
