CREATE TABLE [dbo].[PI10_PID_CHG_LOG] (
    [DN_PID_CHG_REQ_SEQ] INT           NOT NULL,
    [DC_STA_PI10]        CHAR (1)      NOT NULL,
    [DC_PID_CRR_PRS]     CHAR (1)      NOT NULL,
    [DF_PID_CHG_REQ_DTS] DATETIME2 (7) NOT NULL,
    [DF_USR_ID_CHG_REQ]  VARCHAR (8)   NOT NULL,
    [DF_PRS_ID_NEW]      VARCHAR (9)   NOT NULL,
    [DF_PRS_ID_OLD]      VARCHAR (9)   NOT NULL,
    [DF_LST_DTS_PI10]    DATETIME2 (7) NOT NULL,
    [DC_SRC_PID]         CHAR (1)      NOT NULL,
    [DC_EDS_CHG_REQ]     CHAR (1)      NOT NULL,
    [DC_STU_LON_CHG_REQ] CHAR (1)      NOT NULL,
    [DC_STU_APL_CHG_REQ] CHAR (1)      NOT NULL,
    [DC_RFR_CHG_REQ]     CHAR (1)      NOT NULL,
    [DC_PCV_LON_CHG_REQ] CHAR (1)      NOT NULL,
    [DC_SER_LON_CHG_REQ] CHAR (1)      NOT NULL,
    [DC_APL_CHG_REQ]     CHAR (1)      NOT NULL,
    [DD_STA_PI10]        DATE          NULL,
    [DC_LC_APL_CHG_REQ]  CHAR (1)      NOT NULL,
    CONSTRAINT [PK_PI10_PID_CHG_LOG] PRIMARY KEY CLUSTERED ([DN_PID_CHG_REQ_SEQ] ASC) WITH (FILLFACTOR = 95)
);

