/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/ULWN12.LWN12RZ";
FILENAME REPORT2 "&RPTLIB/ULWN12.LWN12R2";
FILENAME REPORT3 "&RPTLIB/ULWN12.LWN12R3";
FILENAME REPORT4 "&RPTLIB/ULWN12.LWN12R4";
FILENAME REPORT5 "&RPTLIB/ULWN12.LWN12R5";
FILENAME REPORT6 "&RPTLIB/ULWN12.LWN12R6";
FILENAME REPORT7 "&RPTLIB/ULWN12.LWN12R7";
FILENAME REPORT8 "&RPTLIB/ULWN12.LWN12R8";
FILENAME REPORT9 "&RPTLIB/ULWN12.LWN12R9";
FILENAME REPORT10 "&RPTLIB/ULWN12.LWN12R10";
FILENAME REPORT11 "&RPTLIB/ULWN12.LWN12R11";
FILENAME REPORT12 "&RPTLIB/ULWN12.LWN12R12";
FILENAME REPORT13 "&RPTLIB/ULWN12.LWN12R13";
FILENAME REPORT14 "&RPTLIB/ULWN12.LWN12R14";
FILENAME REPORT15 "&RPTLIB/ULWN12.LWN12R15";
FILENAME REPORT16 "&RPTLIB/ULWN12.LWN12R16";
FILENAME REPORT17 "&RPTLIB/ULWN12.LWN12R17";
FILENAME REPORT18 "&RPTLIB/ULWN12.LWN12R18";
FILENAME REPORT19 "&RPTLIB/ULWN12.LWN12R19";
FILENAME REPORT20 "&RPTLIB/ULWN12.LWN12R20";
FILENAME REPORT21 "&RPTLIB/ULWN12.LWN12R21";
FILENAME REPORT22 "&RPTLIB/ULWN12.LWN12R22";
FILENAME REPORT23 "&RPTLIB/ULWN12.LWN12R23";
FILENAME REPORT24 "&RPTLIB/ULWN12.LWN12R24";

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;

OPTIONS SYMBOLGEN;

DATA _NULL_;		
	CALL SYMPUT('BEGIN',"'"||PUT(INTNX('MONTH',TODAY(),-1,'BEGINNING'), MMDDYYD10.)||"'"); /*beginning of previous month*/
	CALL SYMPUT('END',"'"||PUT(INTNX('MONTH',TODAY(),-1,'END'), MMDDYYD10.)||"'"); /*end of previous month*/ 
RUN; 

%SYSLPUT END = &END; 
%SYSLPUT BEGIN = &BEGIN; 

RSUBMIT;

%macro sqlcheck ;
  %if  &sqlxrc ne 0  %then  %do  ;
    data _null_  ;
            file reportz notitles  ;
            put @01 " ********************************************************************* "
              / @01 " ****  The SQL code above has experienced an error.               **** "
              / @01 " ****  The SAS should be reviewed.                                **** "       
              / @01 " ********************************************************************* "
              / @01 " ****  The SQL error code is  &sqlxrc  and the SQL error message  **** "
              / @01 " ****  &sqlxmsg   **** "
              / @01 " ********************************************************************* "
            ;
         run  ;
  %end  ;
%mend  ;


PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE APPDATA AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT
	A.AF_APL_ID				AS APPID,
	A.AD_PRC				AS PROCDATE,
	B.AD_APL_RCV 			AS RCVDATE,
	A.AF_CUR_LON_OPS_LDR	AS LENDERID
FROM	OLWHRM1.GA10_LON_APP A
INNER JOIN OLWHRM1.GA01_APP B
ON A.AF_APL_ID = B.AF_APL_ID
WHERE A.AC_PRC_STA = 'A' 
AND B.AD_APL_RCV BETWEEN &BEGIN AND &END
FOR READ ONLY WITH UR
);

CREATE TABLE LENDERS AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT
	A.IM_IST_FUL			AS FULLNAME,
	A.IF_IST				AS ID
FROM	OLWHRM1.IN01_LGS_IDM_MST A
WHERE A.IC_IST_TYP = '002'

FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;

/*%put  sqlxrc= >>> &sqlxrc <<< ||| sqlxmsg= >>> &sqlxmsg >>> ;  ** includes error messages to SAS log  ;*/
/*%sqlcheck;*/
/*quit;*/

ENDRSUBMIT;

DATA APPDATA;
SET WORKLOCL.APPDATA;
RUN;

DATA LENDERS;
SET WORKLOCL.LENDERS;
RUN;

PROC SORT DATA=APPDATA;
BY LENDERID;
RUN;

DATA APPDATA;
SET APPDATA;
FORMAT DAYS2PROC 10.;
DAYS2PROC = (DATDIF(RCVDATE,PROCDATE,'ACTUAL') + 1);
FORMAT CALCFLD 10.;
CALCFLD = 1;
RUN;

/*RUN MACRO FOR EACH LENDER*/
%MACRO LENDERRPT(LID, RPT);
	/*GET LENDER FULL NAME*/
	DATA _NULL_;
	SET LENDERS;
	IF ID = &LID THEN CALL SYMPUT ('LNAME', FULLNAME);
	RUN;

	/*STRIP OUT LENDER DATA*/
	DATA TEMP;
	SET APPDATA;
	IF LENDERID = &LID THEN OUTPUT;
	RUN;
	/*CREATE REPORT FOR LENDER*/
	PROC PRINTTO PRINT=REPORT&RPT NEW;
	RUN;
	OPTIONS CENTER PAGENO=1 ORIENTATION=PORTRAIT ;
	OPTIONS LS=96 PS=52;
	/*HANDLE EMPTY SETS*/
	PROC CONTENTS DATA=TEMP OUT=EMPTYSET NOPRINT;
	DATA _NULL_;
	SET EMPTYSET;
	FILE PRINT;
	IF NOBS=0 AND _N_ =1 THEN DO;
	PUT // 96*'-';
	PUT ////////
	@35 '**** NO RECORDS FOUND ****';
	PUT ////////
	@38 '-- END OF REPORT --';
	PUT ////////////////
	@27 "JOB = UTLWN12     REPORT = ULWL03.LWN12R&RPT";
	END;
	RETURN;
	TITLE "UTAH HIGHER EDUCATION ASSISTANCE AUTHORITY";
	TITLE2 "MONTHLY APPLICATION DATA FOR LENDERS - (&LID) &LNAME";
	RUN;
	/*PRINT REPORT IF DATA SET HAS DATA*/
	PROC REPORT DATA=TEMP NOWD HEADSKIP SPLIT='/' SPACING=3;
	COLUMN LENDERID CALCFLD DAYS2PROC;
	DEFINE LENDERID / GROUP "LENDERID" WIDTH=31 NOPRINT;
	DEFINE CALCFLD / ANALYSIS "TOTAL APPS RECEIVED" SUM;
	DEFINE DAYS2PROC / ANALYSIS "AVG DAYS PROCESSED" MEAN;
	COMPUTE AFTER;
	ENDCOMP;
	TITLE "UTAH HIGHER EDUCATION ASSISTANCE AUTHORITY";
	TITLE2 "MONTHLY APPLICATION DATA FOR LENDERS - (&LID) &LNAME";
	FOOTNOTE "JOB = UTLWN12     REPORT = ULWL03.LWN12R&RPT";
	RUN;
%MEND;

%LENDERRPT(817575,2);
%LENDERRPT(822373,3);
%LENDERRPT(833577,4);
%LENDERRPT(833828,5);
%LENDERRPT(817440,6);
%LENDERRPT(817545,7);
%LENDERRPT(834265,8);
%LENDERRPT(830791,9);
%LENDERRPT(819628,10);
%LENDERRPT(813760,11);
%LENDERRPT(834370,12);
%LENDERRPT(817546,13);
%LENDERRPT(834122,14);
%LENDERRPT(832241,15);
%LENDERRPT(820200,16);
%LENDERRPT(828476,17);
%LENDERRPT(830132,18);
%LENDERRPT(811698,19);
%LENDERRPT(830146,20);
%LENDERRPT(829123,21);
%LENDERRPT(829158,22);
%LENDERRPT(813894,23);
%LENDERRPT(817455,24);

PROC PRINTTO;
RUN;
