/*UTLWK07 SKIP ACTIVITY*/

/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/ULWK07.LWK07R2";

DATA _NULL_;
	CALL SYMPUT('YESTERDAY',"'"||PUT(INTNX('DAY',TODAY(),-1,'BEGINNING'),MMDDYY10.)||"'");
RUN;

%SYSLPUT YESTERDAY = &YESTERDAY;

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
/*GET BORROWER ACTIVITY*/
CREATE TABLE SKPACT_BR AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT A.DF_PRS_ID
	,A.PF_ACT
	,A.BX_CMT
	,CASE 
		WHEN A.BC_ATY_TYP IN (
				'TC','T1','T3',
				'T4'
				) THEN 'CNTCT'
		WHEN A.BC_ATY_TYP IN (
				'CO','FO','LT'
				) THEN 'PRNTD'
		WHEN A.BC_ATY_TYP IN (
				'TE','TT','T2',
				'T5','T6','T7',
				'T8'
				) THEN 'NOCTC' 
		ELSE 'COMPL'
	 END AS BC_ATY_TYP
FROM OLWHRM1.AY01_BR_ATY A
INNER JOIN OLWHRM1.LN10_LON B
	ON A.DF_PRS_ID = B.BF_SSN
WHERE A.BD_ATY_PRF = &YESTERDAY
AND A.PF_ACT IN ('KUBTL','KSBTL','KUBHL','KSBHL','KUBTF','KUBHF','KUETL','KSETL','KUEHL','KSEHL')
AND B.LC_STA_LON10 = 'R'
AND B.LA_CUR_PRI > 0
);

/*GET REFERENCE ACTIVITY*/
CREATE TABLE SKPACT_RF AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT B.DF_PRS_ID_BR AS DF_PRS_ID
	,RTRIM(B.BM_RFR_1)||' '||BM_RFR_LST AS RFNM
	,B.DF_PRS_ID_RFR
	,A.PF_ACT
	,A.BX_CMT
	,CASE 
		WHEN A.BC_ATY_TYP IN (
				'TC','T1','T3',
				'T4'
				) THEN 'CNTCT'
		WHEN A.BC_ATY_TYP IN (
				'CO','FO','LT'
				) THEN 'PRNTD'
		WHEN A.BC_ATY_TYP IN (
				'TE','TT','T2',
				'T5','T6','T7',
				'T8'
				) THEN 'NOCTC' 
		ELSE 'COMPL'
	 END AS BC_ATY_TYP
FROM OLWHRM1.AY01_BR_ATY A
INNER JOIN OLWHRM1.BR03_BR_REF B
	ON A.DF_PRS_ID = B.DF_PRS_ID_RFR
INNER JOIN OLWHRM1.LN10_LON B
	ON B.DF_PRS_ID_BR = B.BF_SSN
WHERE A.BD_ATY_PRF = &YESTERDAY
AND A.DF_PRS_ID LIKE 'RF%'
AND A.PF_ACT IN ('KUBTL','KSBTL','KUBHL','KSBHL','KUBTF','KUBHF','KUETL','KSETL','KUEHL','KSEHL')
AND B.LC_STA_LON10 = 'R'
AND B.LA_CUR_PRI > 0
);
DISCONNECT FROM DB2;
ENDRSUBMIT;
DATA SKPACT_BR;SET WORKLOCL.SKPACT_BR;RUN;
DATA SKPACT_RF;SET WORKLOCL.SKPACT_RF;RUN;

/*CREATE NEW COMMENT FOR REFERENCES*/
DATA SKPACT_RF (DROP=DF_PRS_ID_RFR RFNM);
SET SKPACT_RF;
BX_CMT = '{'||TRIM(DF_PRS_ID_RFR)||', '||TRIM(RFNM)||'} '||TRIM(BX_CMT);
RUN;

DATA SKPACT;
SET SKPACT_RF SKPACT_BR;
RUN;

PROC SORT DATA=SKPACT;
BY DF_PRS_ID;
RUN;

DATA _NULL_;
SET  WORK.SKPACT;
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
FORMAT DF_PRS_ID $9. ;
FORMAT PF_ACT $5. ;
FORMAT BX_CMT $600. ;
FORMAT BC_ATY_TYP $5. ;
IF _N_ = 1 THEN 
DO;
   PUT
   'DF_PRS_ID'
   ','
   'PF_ACT'
   ','
   'BX_CMT'
   ','
   'BC_ATY_TYP'
   ;
END;
DO;
   PUT DF_PRS_ID $ @;
   PUT PF_ACT $ @;
   PUT BX_CMT $ @;
   PUT BC_ATY_TYP $ ;
 END;
RUN;
