CREATE TABLE [dbo].[ports] (
    [borrower_id]                                   INT            NOT NULL,
    [school_id]                                     VARCHAR (6)    NOT NULL,
    [last_name]                                     NVARCHAR (50)  NOT NULL,
    [first_name]                                    NVARCHAR (50)  NOT NULL,
    [middle_name]                                   NVARCHAR (50)  NULL,
    [dob]                                           DATE           NOT NULL,
    [academic_level]                                CHAR (1)       NULL,
    [anticipated_completion_date]                   DATE           NULL,
    [data_provider_identifier_or_award_identifier]  VARCHAR (21)   NOT NULL,
    [original_lender_code]                          VARCHAR (6)    NULL,
    [current_lender_code]                           VARCHAR (6)    NULL,
    [loan_date]                                     DATE           NULL,
    [loan_type]                                     CHAR (2)       NULL,
    [interest_rate_code]                            CHAR (1)       NULL,
    [indicator_of_separate_loan]                    CHAR (1)       NULL,
    [loan_amount]                                   INT            NULL,
    [current_opb_amount]                            INT            NULL,
    [current_oib_amount]                            INT            NULL,
    [current_ofb_amount]                            INT            NULL,
    [balance_date]                                  DATE           NULL,
    [current_loan_status]                           CHAR (2)       NULL,
    [current_loan_status_date]                      DATE           NULL,
    [loan_period_begin_date]                        DATE           NULL,
    [loan_period_end_date]                          DATE           NULL,
    [total_refund_amount]                           INT            NULL,
    [total_cancellation_amount]                     INT            NULL,
    [original_ga_ed_servicer_code]                  INT            NULL,
    [current_ga_ed_servicer_code]                   INT            NULL,
    [date_entered_repayment]                        DATE           NULL,
    [delinquency_date]                              DATE           NULL,
    [last_payment_date]                             DATE           NULL,
    [claim_discharge_amount]                        INT            NULL,
    [claim_discharge_reason_code]                   VARCHAR (4)    NULL,
    [claim_discharge_date_paid]                     DATE           NULL,
    [cdr_date_of_default]                           DATE           NULL,
    [rehabilitation__repurchased_indicator]         CHAR (1)       NULL,
    [rehabilitation__repurchased_date]              DATE           NULL,
    [amount_rehabilitated__repurchased]             INT            NULL,
    [consolidation_indicator]                       CHAR (1)       NULL,
    [consolidation_loan_identifier]                 VARCHAR (21)   NULL,
    [most_recent_repayment_plan_begin_date]         DATE           NULL,
    [most_recent_repayment_plan_type]               CHAR (2)       NULL,
    [most_recent_repayment_plan_term]               VARCHAR (3)    NULL,
    [most_recent_scheduled_payment_amount]          INT            NULL,
    [payment_due_day]                               CHAR (2)       NULL,
    [most_recent_deferment_begin_date_]             DATE           NULL,
    [most_recent_deferment_end_date]                DATE           NULL,
    [most_recent_deferment_reason_code]             CHAR (2)       NULL,
    [most_recent_forbearance_begin_date]            DATE           NULL,
    [most_recent_forbearance_end_date]              DATE           NULL,
    [most_recent_forbearance_reason_code]           CHAR (2)       NULL,
    [sula_flag]                                     CHAR (1)       NULL,
    [confirmed_loan_subsidy_status]                 CHAR (1)       NULL,
    [loan_level_sup]                                INT            NULL,
    [first_payment_due_date]                        DATE           NULL,
    [cumulative_total_payment_amount]               INT            NULL,
    [next_payment_due_date]                         DATE           NULL,
    [most_recent_payment_effective_date]            DATE           NULL,
    [income_driven_repayment_plan_anniversary_date] DATE           NULL,
    [statutory_interest_rate]                       DECIMAL (5, 2) NULL,
    [actual_interest_rate]                          DECIMAL (5, 2) NULL,
    [active_cohort]                                 BIT            CONSTRAINT [DF_ports_active_cohort] DEFAULT ((0)) NOT NULL,
    [table_source]                                  VARCHAR (4)    NOT NULL,
    [created_on]                                    DATETIME       CONSTRAINT [DF_ports_created_on] DEFAULT (getdate()) NOT NULL,
    [modified_on]                                   DATETIME       CONSTRAINT [DF_ports_modified_on] DEFAULT (getdate()) NOT NULL
);

