'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class TstDSLPPVoids
    Inherits DataSet
    
    Private tableLPPVoids As LPPVoidsDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("LPPVoids")) Is Nothing) Then
                Me.Tables.Add(New LPPVoidsDataTable(ds.Tables("LPPVoids")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property LPPVoids As LPPVoidsDataTable
        Get
            Return Me.tableLPPVoids
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As TstDSLPPVoids = CType(MyBase.Clone,TstDSLPPVoids)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("LPPVoids")) Is Nothing) Then
            Me.Tables.Add(New LPPVoidsDataTable(ds.Tables("LPPVoids")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableLPPVoids = CType(Me.Tables("LPPVoids"),LPPVoidsDataTable)
        If (Not (Me.tableLPPVoids) Is Nothing) Then
            Me.tableLPPVoids.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "TstDSLPPVoids"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/TstDSLPPVoids.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableLPPVoids = New LPPVoidsDataTable
        Me.Tables.Add(Me.tableLPPVoids)
    End Sub
    
    Private Function ShouldSerializeLPPVoids() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub LPPVoidsRowChangeEventHandler(ByVal sender As Object, ByVal e As LPPVoidsRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class LPPVoidsDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnReceiptNumber As DataColumn
        
        Private columnNotes As DataColumn
        
        Private columnDateVoided As DataColumn
        
        Friend Sub New()
            MyBase.New("LPPVoids")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property ReceiptNumberColumn As DataColumn
            Get
                Return Me.columnReceiptNumber
            End Get
        End Property
        
        Friend ReadOnly Property NotesColumn As DataColumn
            Get
                Return Me.columnNotes
            End Get
        End Property
        
        Friend ReadOnly Property DateVoidedColumn As DataColumn
            Get
                Return Me.columnDateVoided
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As LPPVoidsRow
            Get
                Return CType(Me.Rows(index),LPPVoidsRow)
            End Get
        End Property
        
        Public Event LPPVoidsRowChanged As LPPVoidsRowChangeEventHandler
        
        Public Event LPPVoidsRowChanging As LPPVoidsRowChangeEventHandler
        
        Public Event LPPVoidsRowDeleted As LPPVoidsRowChangeEventHandler
        
        Public Event LPPVoidsRowDeleting As LPPVoidsRowChangeEventHandler
        
        Public Overloads Sub AddLPPVoidsRow(ByVal row As LPPVoidsRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddLPPVoidsRow(ByVal ReceiptNumber As Long, ByVal Notes As String, ByVal DateVoided As Date) As LPPVoidsRow
            Dim rowLPPVoidsRow As LPPVoidsRow = CType(Me.NewRow,LPPVoidsRow)
            rowLPPVoidsRow.ItemArray = New Object() {ReceiptNumber, Notes, DateVoided}
            Me.Rows.Add(rowLPPVoidsRow)
            Return rowLPPVoidsRow
        End Function
        
        Public Function FindByReceiptNumber(ByVal ReceiptNumber As Long) As LPPVoidsRow
            Return CType(Me.Rows.Find(New Object() {ReceiptNumber}),LPPVoidsRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As LPPVoidsDataTable = CType(MyBase.Clone,LPPVoidsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New LPPVoidsDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnReceiptNumber = Me.Columns("ReceiptNumber")
            Me.columnNotes = Me.Columns("Notes")
            Me.columnDateVoided = Me.Columns("DateVoided")
        End Sub
        
        Private Sub InitClass()
            Me.columnReceiptNumber = New DataColumn("ReceiptNumber", GetType(System.Int64), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnReceiptNumber)
            Me.columnNotes = New DataColumn("Notes", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNotes)
            Me.columnDateVoided = New DataColumn("DateVoided", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDateVoided)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnReceiptNumber}, true))
            Me.columnReceiptNumber.AllowDBNull = false
            Me.columnReceiptNumber.Unique = true
        End Sub
        
        Public Function NewLPPVoidsRow() As LPPVoidsRow
            Return CType(Me.NewRow,LPPVoidsRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New LPPVoidsRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(LPPVoidsRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.LPPVoidsRowChangedEvent) Is Nothing) Then
                RaiseEvent LPPVoidsRowChanged(Me, New LPPVoidsRowChangeEvent(CType(e.Row,LPPVoidsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.LPPVoidsRowChangingEvent) Is Nothing) Then
                RaiseEvent LPPVoidsRowChanging(Me, New LPPVoidsRowChangeEvent(CType(e.Row,LPPVoidsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.LPPVoidsRowDeletedEvent) Is Nothing) Then
                RaiseEvent LPPVoidsRowDeleted(Me, New LPPVoidsRowChangeEvent(CType(e.Row,LPPVoidsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.LPPVoidsRowDeletingEvent) Is Nothing) Then
                RaiseEvent LPPVoidsRowDeleting(Me, New LPPVoidsRowChangeEvent(CType(e.Row,LPPVoidsRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveLPPVoidsRow(ByVal row As LPPVoidsRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class LPPVoidsRow
        Inherits DataRow
        
        Private tableLPPVoids As LPPVoidsDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableLPPVoids = CType(Me.Table,LPPVoidsDataTable)
        End Sub
        
        Public Property ReceiptNumber As Long
            Get
                Return CType(Me(Me.tableLPPVoids.ReceiptNumberColumn),Long)
            End Get
            Set
                Me(Me.tableLPPVoids.ReceiptNumberColumn) = value
            End Set
        End Property
        
        Public Property Notes As String
            Get
                Try 
                    Return CType(Me(Me.tableLPPVoids.NotesColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLPPVoids.NotesColumn) = value
            End Set
        End Property
        
        Public Property DateVoided As Date
            Get
                Try 
                    Return CType(Me(Me.tableLPPVoids.DateVoidedColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableLPPVoids.DateVoidedColumn) = value
            End Set
        End Property
        
        Public Function IsNotesNull() As Boolean
            Return Me.IsNull(Me.tableLPPVoids.NotesColumn)
        End Function
        
        Public Sub SetNotesNull()
            Me(Me.tableLPPVoids.NotesColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDateVoidedNull() As Boolean
            Return Me.IsNull(Me.tableLPPVoids.DateVoidedColumn)
        End Function
        
        Public Sub SetDateVoidedNull()
            Me(Me.tableLPPVoids.DateVoidedColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class LPPVoidsRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As LPPVoidsRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As LPPVoidsRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As LPPVoidsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
