CREATE PROCEDURE [lnderlettr].[GetBorrowerData]
	@TestMode bit,
	@BF_SSN char(9)
AS
DECLARE @Query VARCHAR(Max)
IF @TestMode = 0
	SET @Query = 'SELECT * FROM OPENQUERY(DUSTER,'
ELSE 
	SET @Query = 'SELECT * FROM OPENQUERY(QADBD004,'

SELECT
	@Query = @Query +
		'''
		SELECT Distinct
			PD10.DF_SPE_ACC_ID,
			PD10.DF_PRS_ID,
			PD10.DF_PRS_LST_4_SSN,
			PD10.DM_PRS_1,
			PD10.DM_PRS_MID,
			PD10.DM_PRS_LST,
			PD10.DD_BRT,
			PD11.DM_PRS_1_HST, 
			PD11.DM_PRS_MID_HST, 
			PD11.DM_PRS_LST_HST,
			PD30.DX_STR_ADR_1,
			PD30.DX_STR_ADR_2,
			PD30.DM_CT,
			PD30.DC_DOM_ST,
			PD30.DF_ZIP_CDE,
			PD30.DM_FGN_CNY,
			PD32.DX_ADR_EML,
			CONCAT(PD42_H.DN_DOM_PHN_ARA, CONCAT(PD42_H.DN_DOM_PHN_XCH, PD42_H.DN_DOM_PHN_LCL)) AS HomePhone,
			CONCAT(PD42_A.DN_DOM_PHN_ARA, CONCAT(PD42_A.DN_DOM_PHN_XCH, PD42_A.DN_DOM_PHN_LCL)) AS AlternatePhone,
			CONCAT(PD42_W.DN_DOM_PHN_ARA, CONCAT(PD42_W.DN_DOM_PHN_XCH, PD42_W.DN_DOM_PHN_LCL)) AS WorkPhone
		FROM
			OLWHRM1.PD10_PRS_NME PD10
			LEFT JOIN OLWHRM1.PD30_PRS_ADR PD30
				ON PD10.DF_PRS_ID = PD30.DF_PRS_ID
			LEFT JOIN OLWHRM1.PD42_PRS_PHN PD42_H
				ON PD10.DF_PRS_ID = PD42_H.DF_PRS_ID AND PD42_H.DC_PHN = ''''H''''
			LEFT JOIN OLWHRM1.PD42_PRS_PHN PD42_W
				ON PD10.DF_PRS_ID = PD42_W.DF_PRS_ID AND PD42_W.DC_PHN = ''''W''''
			LEFT JOIN OLWHRM1.PD42_PRS_PHN PD42_A
				ON PD10.DF_PRS_ID = PD42_A.DF_PRS_ID AND PD42_A.DC_PHN = ''''A''''
			LEFT JOIN OLWHRM1.PD32_PRS_ADR_EML PD32
				ON PD10.DF_PRS_ID = PD32.DF_PRS_ID
			LEFT OUTER JOIN /*Use oldest row*/
				(
					SELECT
						PD11Inner.DN_PRS_SEQ AS DN_PRS_SEQ,
						PD11Inner.DM_PRS_1_HST,
						PD11Inner.DM_PRS_MID_HST,
						PD11Inner.DM_PRS_LST_HST,
						PD11Inner.DF_PRS_ID
					FROM
						OLWHRM1.PD11_PRS_NME_HST PD11Inner
						INNER JOIN 
							(
								SELECT 
									MIN(PD11Min.DN_PRS_SEQ) AS DN_PRS_SEQ_MIN,
									PD11Min.DF_PRS_ID AS DF_PRS_ID_MIN
								FROM 
									OLWHRM1.PD11_PRS_NME_HST PD11Min
								GROUP BY
									PD11Min.DF_PRS_ID
							) PD11Min
							ON PD11Min.DN_PRS_SEQ_MIN = PD11Inner.DN_PRS_SEQ
							AND PD11Min.DF_PRS_ID_MIN = PD11Inner.DF_PRS_ID					
				) PD11
			ON PD11.DF_PRS_ID = PD10.DF_PRS_ID
		WHERE
			PD10.DF_PRS_ID = ''''' + CAST(@BF_SSN AS CHAR(9)) + '''''
		'')'
EXEC(@Query)
GO
GRANT EXECUTE
    ON OBJECT::[lnderlettr].[GetBorrowerData] TO [db_executor]
    AS [dbo];

