/*=========================*/
/*UTLWN04 US BANK MR57 MR58*/
/*=========================*/
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = /sas/whse/progrevw ;*/
/*FILENAME REPORT2 "&RPTLIB/ULWN04.LWN04R2";*/
/*FILENAME REPORTZ "&RPTLIB/ULWN04.LWN04RZ";*/

FILENAME REPORT2 'T:\SAS\ULWN04.ULWN04R2';

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;

%MACRO SQLCHECK (SQLRPT= );
%IF &SQLXRC NE 0 %THEN %DO;
	DATA _NULL_;
    FILE REPORTZ NOTITLES;
    PUT @01 " ********************************************************************* "
      / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
      / @01 " ****  THE SAS LOG IN &SQLRPT SHOULD BE REVIEWED.          **** "       
      / @01 " ********************************************************************* "
      / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
      / @01 " ****  &SQLXMSG   **** "
      / @01 " ********************************************************************* ";
	RUN;
%END;
%MEND;

PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE MR57 AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT A.BF_SSN AS MR57_SSN
,A.LN_SEQ AS MR57_LN_SEQ
,A.LN_CU_SEQ
,A.LD_CU_ENT
,A.LD_CU_END
,A.LC_CU_REA
,A.WX_CU_REA
,A.LC_CU_REA_END
,A.WX_CU_REA_END
,A.LC_CU_LIA
,A.WX_CU_LIA
,A.LC_CU_CND
,A.WX_CU_CND
,A.LC_CU_TYP
,A.WX_CU_TYP
,A.LC_CU_SCH
,A.WX_CU_SCH
,A.LD_CU_SR_ORG
,A.LD_DLQ_1_CU_BEG
,A.WA_PRI_CU_BEG
,A.WA_BRI_ACR_CU_BEG
,A.WI_APL_OVR_CU_BEG
,A.LD_CU_RTT_1
,A.LC_CU_RTT_REA_1 
,A.WX_CU_RTT_REA_1
,A.LD_CU_RTT_2
,A.LC_CU_RTT_REA_2
,A.WX_CU_RTT_REA_2
,A.LD_CU_RTT_3
,A.LC_CU_RTT_REA_3
,A.WX_CU_RTT_REA_3
,A.LD_CU_RTT_4
,A.LC_CU_RTT_REA_4
,A.WX_CU_RTT_REA_4
,A.LD_CU_RTT_5
,A.LC_CU_RTT_REA_5
,A.WX_CU_RTT_REA_5
,A.WF_OWN_CU_BEG
,A.WF_OWN_CU_END
,A.WC_CU_LIA_PRV
,A.WX_CU_LIA_PRV

FROM OLWHRM1.MR57_MR_CU_MTH A
INNER JOIN OLWHRM1.MR5A_MR_LON_MTH_01 B
	ON A.BF_SSN = B.BF_SSN
	AND A.LN_SEQ = B.LN_SEQ
WHERE B.IF_OWN = '811698'

FOR READ ONLY WITH UR
);

CREATE TABLE MR58 AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT B.BF_SSN AS MR58_SSN
,B.LN_SEQ AS MR58_LN_SEQ
,B.LN_SEQ_CLM_PCL
,B.LA_SBM_CLM_PCL_PRI
,B.LA_SBM_CLM_PCL_INT
,B.LC_CLM_REJ_RTN_LIB
,B.WX_CLM_REJ_RTN_LIB
,B.LC_REA_CAN_CLM_PCL
,B.WX_REA_CAN_CLM_PCL
,B.LD_CRT_CLM_PCL
,B.LD_CLM_REJ_RTN_ACL
,B.LD_CLM_REJ_RTN_EFF
,B.LD_CLM_REJ_RTN_MAX 
,B.LD_CAN_CLM_PCL
,B.LD_SBM_CLM_PCL
,B.LC_TYP_REJ_RTN
,B.WX_TYP_REJ_RTN
,B.LC_REA_CLP_LON
,B.WX_REA_CLP_LON
,B.LF_USR_ASN_CLM_PCL
,B.LC_TYP_REC_CLP_LON
,B.WX_TYP_REC_CLP_LON
,B.WA_CLM_PD
,B.WD_CLM_PD
,B.WN_DAY_AFT_CLM_FIL
,B.WC_CLM_AGE_CAT
,B.WX_CLM_AGE_CAT
,B.LD_CLM_ORG_SBM

FROM OLWHRM1.MR58_MR_CLM_MTH B
INNER JOIN OLWHRM1.MR5A_MR_LON_MTH_01 C
	ON B.BF_SSN = C.BF_SSN
	AND B.LN_SEQ = C.LN_SEQ
WHERE C.IF_OWN = '811698'
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;

/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>>  ;  * INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK (SQLRPT=ULWN04.LWN04RZ);*/
/*QUIT;*/

PROC SQL;
CREATE TABLE USBMRTBL AS
SELECT DISTINCT A.*
	,B.*
FROM MR57 A
FULL OUTER JOIN MR58 B
	ON A.MR57_SSN = B.MR58_SSN
	AND A.MR57_LN_SEQ = B.MR58_LN_SEQ
;
RUN;

ENDRSUBMIT;

DATA USBMRTBL;
SET WORKLOCL.USBMRTBL;
RUN;

DATA _NULL_;
SET  WORK.USBMRTBL;
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
FORMAT MR57_SSN $9. ;
FORMAT MR57_LN_SEQ 6. ;
FORMAT LN_CU_SEQ 6. ;
FORMAT LD_CU_ENT MMDDYY10. ;
FORMAT LD_CU_END MMDDYY10. ;
FORMAT LC_CU_REA $2. ;
FORMAT WX_CU_REA $20. ;
FORMAT LC_CU_REA_END $1. ;
FORMAT WX_CU_REA_END $20. ;
FORMAT LC_CU_LIA $1. ;
FORMAT WX_CU_LIA $20. ;
FORMAT LC_CU_CND $1. ;
FORMAT WX_CU_CND $20. ;
FORMAT LC_CU_TYP $1. ;
FORMAT WX_CU_TYP $20. ;
FORMAT LC_CU_SCH $1. ;
FORMAT WX_CU_SCH $20. ;
FORMAT LD_CU_SR_ORG MMDDYY10. ;
FORMAT LD_DLQ_1_CU_BEG MMDDYY10. ;
FORMAT WA_PRI_CU_BEG 10.2 ;
FORMAT WA_BRI_ACR_CU_BEG 9.2 ;
FORMAT WI_APL_OVR_CU_BEG $1. ;
FORMAT LD_CU_RTT_1 MMDDYY10. ;
FORMAT LC_CU_RTT_REA_1 $1. ;
FORMAT WX_CU_RTT_REA_1 $20. ;
FORMAT LD_CU_RTT_2 MMDDYY10. ;
FORMAT LC_CU_RTT_REA_2 $1. ;
FORMAT WX_CU_RTT_REA_2 $20. ;
FORMAT LD_CU_RTT_3 MMDDYY10. ;
FORMAT LC_CU_RTT_REA_3 $1. ;
FORMAT WX_CU_RTT_REA_3 $20. ;
FORMAT LD_CU_RTT_4 MMDDYY10. ;
FORMAT LC_CU_RTT_REA_4 $1. ;
FORMAT WX_CU_RTT_REA_4 $20. ;
FORMAT LD_CU_RTT_5 MMDDYY10. ;
FORMAT LC_CU_RTT_REA_5 $1. ;
FORMAT WX_CU_RTT_REA_5 $20. ;
FORMAT WF_OWN_CU_BEG $8. ;
FORMAT WF_OWN_CU_END $8. ;
FORMAT WC_CU_LIA_PRV $1. ;
FORMAT WX_CU_LIA_PRV $20. ;
FORMAT MR58_SSN $9. ;
FORMAT MR58_LN_SEQ 6. ;
FORMAT LN_SEQ_CLM_PCL 6. ;
FORMAT LA_SBM_CLM_PCL_PRI 10.2 ;
FORMAT LA_SBM_CLM_PCL_INT 9.2 ;
FORMAT LC_CLM_REJ_RTN_LIB $2. ;
FORMAT WX_CLM_REJ_RTN_LIB $20. ;
FORMAT LC_REA_CAN_CLM_PCL $2. ;
FORMAT WX_REA_CAN_CLM_PCL $20. ;
FORMAT LD_CRT_CLM_PCL MMDDYY10. ;
FORMAT LD_CLM_REJ_RTN_ACL MMDDYY10. ;
FORMAT LD_CLM_REJ_RTN_EFF MMDDYY10. ;
FORMAT LD_CLM_REJ_RTN_MAX MMDDYY10. ;
FORMAT LD_CAN_CLM_PCL MMDDYY10. ;
FORMAT LD_SBM_CLM_PCL MMDDYY10. ;
FORMAT LC_TYP_REJ_RTN $1. ;
FORMAT WX_TYP_REJ_RTN $20. ;
FORMAT LC_REA_CLP_LON $2. ;
FORMAT WX_REA_CLP_LON $20. ;
FORMAT LF_USR_ASN_CLM_PCL $8. ;
FORMAT LC_TYP_REC_CLP_LON $1. ;
FORMAT WX_TYP_REC_CLP_LON $20. ;
FORMAT WA_CLM_PD 11.2 ;
FORMAT WD_CLM_PD MMDDYY10. ;
FORMAT WN_DAY_AFT_CLM_FIL 4. ;
FORMAT WC_CLM_AGE_CAT $1. ;
FORMAT WX_CLM_AGE_CAT $20. ;
FORMAT LD_CLM_ORG_SBM MMDDYY10. ;
DO;
PUT MR57_SSN $ @;
PUT MR57_LN_SEQ @;
PUT LN_CU_SEQ @;
PUT LD_CU_ENT @;
PUT LD_CU_END @;
PUT LC_CU_REA $ @;
PUT WX_CU_REA $ @;
PUT LC_CU_REA_END $ @;
PUT WX_CU_REA_END $ @;
PUT LC_CU_LIA $ @;
PUT WX_CU_LIA $ @;
PUT LC_CU_CND $ @;
PUT WX_CU_CND $ @;
PUT LC_CU_TYP $ @;
PUT WX_CU_TYP $ @;
PUT LC_CU_SCH $ @;
PUT WX_CU_SCH $ @;
PUT LD_CU_SR_ORG @;
PUT LD_DLQ_1_CU_BEG @;
PUT WA_PRI_CU_BEG @;
PUT WA_BRI_ACR_CU_BEG @;
PUT WI_APL_OVR_CU_BEG $ @;
PUT LD_CU_RTT_1 @;
PUT LC_CU_RTT_REA_1 $ @;
PUT WX_CU_RTT_REA_1 $ @;
PUT LD_CU_RTT_2 @;
PUT LC_CU_RTT_REA_2 $ @;
PUT WX_CU_RTT_REA_2 $ @;
PUT LD_CU_RTT_3 @;
PUT LC_CU_RTT_REA_3 $ @;
PUT WX_CU_RTT_REA_3 $ @;
PUT LD_CU_RTT_4 @;
PUT LC_CU_RTT_REA_4 $ @;
PUT WX_CU_RTT_REA_4 $ @;
PUT LD_CU_RTT_5 @;
PUT LC_CU_RTT_REA_5 $ @;
PUT WX_CU_RTT_REA_5 $ @;
PUT WF_OWN_CU_BEG $ @;
PUT WF_OWN_CU_END $ @;
PUT WC_CU_LIA_PRV $ @;
PUT WX_CU_LIA_PRV $ @;
PUT MR58_SSN $ @;
PUT MR58_LN_SEQ @;
PUT LN_SEQ_CLM_PCL @;
PUT LA_SBM_CLM_PCL_PRI @;
PUT LA_SBM_CLM_PCL_INT @;
PUT LC_CLM_REJ_RTN_LIB $ @;
PUT WX_CLM_REJ_RTN_LIB $ @;
PUT LC_REA_CAN_CLM_PCL $ @;
PUT WX_REA_CAN_CLM_PCL $ @;
PUT LD_CRT_CLM_PCL @;
PUT LD_CLM_REJ_RTN_ACL @;
PUT LD_CLM_REJ_RTN_EFF @;
PUT LD_CLM_REJ_RTN_MAX @;
PUT LD_CAN_CLM_PCL @;
PUT LD_SBM_CLM_PCL @;
PUT LC_TYP_REJ_RTN $ @;
PUT WX_TYP_REJ_RTN $ @;
PUT LC_REA_CLP_LON $ @;
PUT WX_REA_CLP_LON $ @;
PUT LF_USR_ASN_CLM_PCL $ @;
PUT LC_TYP_REC_CLP_LON $ @;
PUT WX_TYP_REC_CLP_LON $ @;
PUT WA_CLM_PD @;
PUT WD_CLM_PD @;
PUT WN_DAY_AFT_CLM_FIL @;
PUT WC_CLM_AGE_CAT $ @;
PUT WX_CLM_AGE_CAT $ @;
PUT LD_CLM_ORG_SBM $ ;
END;
RUN;
