/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/ULWK30.LWK30RZ";
FILENAME REPORT2 "&RPTLIB/ULWK30.LWK30R2";

LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;

OPTIONS SYMBOLGEN;

DATA _NULL_;		
	CALL SYMPUT('TESTDATE',"'"||PUT(INTNX('YEAR',TODAY(),-2,'SAMEDAY'), MMDDYYD10.)||"'");
RUN; 

%SYSLPUT TESTDATE = &TESTDATE; 

RSUBMIT;

%macro sqlcheck ;
  %if  &sqlxrc ne 0  %then  %do  ;
    data _null_  ;
            file reportz notitles  ;
            put @01 " ********************************************************************* "
              / @01 " ****  The SQL code above has experienced an error.               **** "
              / @01 " ****  The SAS should be reviewed.                                **** "       
              / @01 " ********************************************************************* "
              / @01 " ****  The SQL error code is  &sqlxrc  and the SQL error message  **** "
              / @01 " ****  &sqlxmsg   **** "
              / @01 " ********************************************************************* "
            ;
         run  ;
  %end  ;
%mend  ;


PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
/*SKIP BORROWERS WITH AT LEAST ONE LOAN IN CLAIM PAID STATUS WITH REASON CODE OF DEFAULT*/
CREATE TABLE STARTINGPOP AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT
	BORR.DF_PRS_ID			AS SSN,
	BORR.DF_SPE_ACC_ID		AS ACCTNUM,
	BORR.DM_PRS_1 			AS FIRST,
	BORR.DM_PRS_LST			AS LAST,
	LOAN.AC_LON_STA_TYP		AS LOANSTATUS,
	LOAN.AC_LON_STA_REA		AS STATUSREASON,
	CASE 
	WHEN BORR.DI_VLD_ADR = 'N' AND BORR.DI_PHN_VLD = 'N' THEN 'BOTH'
	WHEN BORR.DI_VLD_ADR = 'N' THEN 'ADDRESS'
	WHEN BORR.DI_PHN_VLD = 'N' THEN 'PHONE'
	END AS SKIPTYPE,
	Q.DF_PRS_ID_BR
FROM OLWHRM1.PD01_PDM_INF BORR
INNER JOIN OLWHRM1.GA01_APP APP
	ON BORR.DF_PRS_ID = APP.DF_PRS_ID_BR
INNER JOIN OLWHRM1.GA14_LON_STA LOAN
	ON APP.AF_APL_ID = LOAN.AF_APL_ID
	AND LOAN.AC_LON_STA_TYP IN ('CP','DN')
	AND LOAN.AC_LON_STA_REA IN ('DF','DB','DQ')
INNER JOIN OLWHRM1.DC01_LON_CLM_INF CLAIM
	ON CLAIM.AF_APL_ID = LOAN.AF_APL_ID
	AND CLAIM.LC_STA_DC10 = '03'
	AND CLAIM.LC_AUX_STA = ''
	AND CLAIM.LC_REA_CLM_ASN_DOE = '' 
	AND LD_LDR_POF <= &TESTDATE
LEFT JOIN (
			SELECT DF_PRS_ID_BR
			FROM OLWHRM1.CT30_CALL_QUE A
			WHERE A.IF_WRK_GRP = 'KDFLTSKP'
			) Q
	ON BORR.DF_PRS_ID = Q.DF_PRS_ID_BR
WHERE BORR.DI_VLD_ADR = 'N' OR BORR.DI_PHN_VLD = 'N'
FOR READ ONLY WITH UR
);

/*BORROWERS WITH BALANCE OF $50,000.00 OR MORE*/
CREATE TABLE SSNSWBIGPRINBALS AS 
SELECT *
FROM CONNECTION TO DB2 (
SELECT
	PRINAPP.DF_PRS_ID_BR AS SSN, 
	SUM(PRINLOAN.AA_CUR_PRI) AS TOTALCURPRIN
FROM OLWHRM1.GA01_APP PRINAPP
INNER JOIN OLWHRM1.GA10_LON_APP PRINLOAN
	ON PRINAPP.AF_APL_ID = PRINLOAN.AF_APL_ID
GROUP BY PRINAPP.DF_PRS_ID_BR
HAVING SUM(PRINLOAN.AA_CUR_PRI) > 50000 
);

DISCONNECT FROM DB2;

/*%put  sqlxrc= >>> &sqlxrc <<< ||| sqlxmsg= >>> &sqlxmsg >>> ;  ** includes error messages to SAS log  ;*/
/*%sqlcheck;*/
/*quit;*/

ENDRSUBMIT;

DATA STARTINGPOP;
SET WORKLOCL.STARTINGPOP;
RUN;

DATA SSNSWBIGPRINBALS;
SET WORKLOCL.SSNSWBIGPRINBALS;
RUN;

PROC SORT DATA=STARTINGPOP;
BY SSN;
RUN;

PROC SORT DATA=SSNSWBIGPRINBALS;
BY SSN;
RUN;

/*REMOVE BORROWERS THAT ALREADY HAVE A QUEUE TASK*/
DATA STARTINGPOP;
SET STARTINGPOP;
IF DF_PRS_ID_BR = NULL THEN OUTPUT;
RUN;

DATA FINAL;
MERGE STARTINGPOP (IN=A) SSNSWBIGPRINBALS (IN=B);
BY SSN;
IF A AND B;
RUN;

PROC SORT DATA=FINAL;
BY ACCTNUM;
RUN;

DATA _NULL_;
SET  WORK.FINAL;
FILE REPORT2 DELIMITER=',' DSD DROPOVER LRECL=32767;
 FORMAT SSN $9. ;
DO;
 PUT SSN $ @;
 PUT 'KDFLTSKP,' @;
 PUT ',' @;
 PUT ',' @;
 PUT ',' @;
 PUT ',' ;
 ;
END;
RUN;

