USE [master]
GO

/****** Object:  Database [AuditCDW]    Script Date: 6/15/2017 8:43:03 AM ******/
CREATE DATABASE [AuditCDW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AuditCDW', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\AuditCDW.mdf' , SIZE = 2928320KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AuditCDW_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\AuditCDW_log.ldf' , SIZE = 2105344KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AuditCDW] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AuditCDW].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [AuditCDW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AuditCDW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AuditCDW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AuditCDW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AuditCDW] SET ARITHABORT OFF 
GO

ALTER DATABASE [AuditCDW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AuditCDW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AuditCDW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AuditCDW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AuditCDW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AuditCDW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AuditCDW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AuditCDW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AuditCDW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AuditCDW] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AuditCDW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AuditCDW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AuditCDW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AuditCDW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AuditCDW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AuditCDW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AuditCDW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AuditCDW] SET RECOVERY FULL 
GO

ALTER DATABASE [AuditCDW] SET  MULTI_USER 
GO

ALTER DATABASE [AuditCDW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AuditCDW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AuditCDW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AuditCDW] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AuditCDW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AuditCDW] SET  READ_WRITE 
GO


