USE CDW
GO

MERGE 
	CDW.dbo.LN65_RepaymentSched LN65
USING
	(
		SELECT DISTINCT
			PD10.DF_SPE_ACC_ID,
			LN65.LN_SEQ,
			ISNULL(CONVERT(VARCHAR(10),LN65.LD_CRT_LON65,101),'') AS LD_CRT_LON65,
			COALESCE(FMT.[Label],LN65.LC_TYP_SCH_DIS,'') AS TYP_SCH_DIS,
			ISNULL(CONVERT(VARCHAR(10),RS10.LD_SNT_RPD_DIS,101),'') AS LD_SNT_RPD_DIS,
			ISNULL(CASE WHEN DW01.WX_OVR_DW_LON_STA = 'LITIGATION' THEN 0
				 ELSE RS.LN_RPS_TRM
			END, 0) AS LN_RPS_TRM,
			CASE WHEN DW01.WX_OVR_DW_LON_STA = 'LITIGATION' THEN ''
				 ELSE CAST(DAY(RS10.LD_RPS_1_PAY_DU) AS VARCHAR(2))
			END AS DUE_DAY,
			ISNULL(CASE WHEN DW01.WX_OVR_DW_LON_STA = 'LITIGATION' THEN 0.00
				 ELSE CAST(RS.LA_RPS_ISL AS NUMERIC(9,2))
			END, 0.00) AS LA_RPS_ISL
		FROM
			CDW..PD10_PRS_NME PD10
			INNER JOIN CDW.calc.RepaymentSchedules RS
				ON RS.BF_SSN = PD10.DF_PRS_ID
				AND RS.CurrentGradation = 1
			INNER JOIN CDW..LN65_LON_RPS LN65
				ON LN65.BF_SSN = RS.BF_SSN
				AND LN65.LN_SEQ = RS.LN_SEQ
				AND LN65.LN_RPS_SEQ = RS.LN_RPS_SEQ
				AND LN65.LC_STA_LON65 = 'A'
			INNER JOIN CDW..RS10_BR_RPD RS10
				ON RS10.BF_SSN = LN65.BF_SSN
				AND RS10.LN_RPS_SEQ = LN65.LN_RPS_SEQ
				AND RS10.LC_STA_RPST10 = 'A'
			INNER JOIN CDW..DW01_DW_CLC_CLU DW01
				ON DW01.BF_SSN = LN65.BF_SSN
				AND DW01.LN_SEQ = LN65.LN_SEQ
			LEFT JOIN CDW..FormatTranslation FMT
				ON FMT.[Start] = LN65.LC_TYP_SCH_DIS
				AND FMT.FmtName = '$SCHTYP'
		WHERE
			CentralData.dbo.TRIM(PD10.DF_SPE_ACC_ID) != ''
	) NewData
		ON NewData.DF_SPE_ACC_ID = LN65.DF_SPE_ACC_ID
		AND NewData.LN_SEQ = LN65.LN_SEQ
WHEN MATCHED THEN 
	UPDATE SET 
		LN65.LD_CRT_LON65 = NewData.LD_CRT_LON65,
		LN65.TYP_SCH_DIS = NewData.TYP_SCH_DIS,
		LN65.LD_SNT_RPD_DIS = NewData.LD_SNT_RPD_DIS,
		LN65.LN_RPS_TRM = NewData.LN_RPS_TRM,
		LN65.DUE_DAY = NewData.DUE_DAY,
		LN65.LA_RPS_ISL = NewData.LA_RPS_ISL
WHEN NOT MATCHED THEN
	INSERT 
	(
		DF_SPE_ACC_ID,
		LN_SEQ,
		LD_CRT_LON65,
		TYP_SCH_DIS,
		LD_SNT_RPD_DIS,
		LN_RPS_TRM,
		DUE_DAY,
		LA_RPS_ISL
	)
	VALUES 
	(
		NewData.DF_SPE_ACC_ID,
		NewData.LN_SEQ,
		NewData.LD_CRT_LON65,
		NewData.TYP_SCH_DIS,
		NewData.LD_SNT_RPD_DIS,
		NewData.LN_RPS_TRM,
		NewData.DUE_DAY,
		NewData.LA_RPS_ISL
	)
WHEN NOT MATCHED BY SOURCE THEN
	DELETE
;
