USE CDW
GO

--TODO: Concerns due to field length mismatches
MERGE 
	CDW.dbo.PD30_Address PD30
USING
	(
		SELECT DISTINCT
			PD10.DF_SPE_ACC_ID,
			ISNULL(PD30.DX_STR_ADR_1,'') AS DX_STR_ADR_1,
			ISNULL(PD30.DX_STR_ADR_2,'') AS DX_STR_ADR_2,
			ISNULL(PD30.DM_CT,'') AS DM_CT,
			ISNULL(PD30.DC_DOM_ST,'') AS DC_DOM_ST,
			ISNULL(PD30.DF_ZIP_CDE,'') AS DF_ZIP_CDE,
			ISNULL(PD30.DM_FGN_ST,'') AS DM_FGN_ST,
			ISNULL(PD30.DM_FGN_CNY,'') AS DM_FGN_CNY,
			ISNULL(CONVERT(VARCHAR(10),PD30.DD_VER_ADR,101),'') AS DD_VER_ADR,
			ISNULL(PD30.DI_VLD_ADR,'') AS DI_VLD_ADR
		FROM
			CDW..PD10_PRS_NME PD10
			INNER JOIN CDW..PD30_PRS_ADR PD30
				ON PD30.DF_PRS_ID = PD10.DF_PRS_ID
		WHERE
			PD30.DC_ADR = 'L'
			AND CentralData.dbo.TRIM(PD10.DF_SPE_ACC_ID) != ''
	) NewData 
		ON NewData.DF_SPE_ACC_ID = PD30.DF_SPE_ACC_ID
WHEN MATCHED THEN 
	UPDATE SET 
		PD30.DX_STR_ADR_1 = NewData.DX_STR_ADR_1,
		PD30.DX_STR_ADR_2 = NewData.DX_STR_ADR_2,
		PD30.DM_CT = NewData.DM_CT,
		PD30.DC_DOM_ST = NewData.DC_DOM_ST,
		PD30.DF_ZIP_CDE = NewData.DF_ZIP_CDE,
		PD30.DM_FGN_ST = NewData.DM_FGN_ST,
		PD30.DM_FGN_CNY = NewData.DM_FGN_CNY,
		PD30.DD_VER_ADR = NewData.DD_VER_ADR,
		PD30.DI_VLD_ADR = NewData.DI_VLD_ADR
WHEN NOT MATCHED THEN
	INSERT 
	(
		DF_SPE_ACC_ID,
		DX_STR_ADR_1,
		DX_STR_ADR_2,
		DM_CT,
		DC_DOM_ST,
		DF_ZIP_CDE,
		DM_FGN_ST,
		DM_FGN_CNY,
		DD_VER_ADR,
		DI_VLD_ADR
	)
	VALUES 
	(
		NewData.DF_SPE_ACC_ID,
		NewData.DX_STR_ADR_1,
		NewData.DX_STR_ADR_2,
		NewData.DM_CT,
		NewData.DC_DOM_ST,
		NewData.DF_ZIP_CDE,
		NewData.DM_FGN_ST,
		NewData.DM_FGN_CNY,
		NewData.DD_VER_ADR,
		NewData.DI_VLD_ADR
	)
WHEN NOT MATCHED BY SOURCE THEN
	DELETE
;
