USE CDW
GO

MERGE 
	CDW.dbo.PD42_Phone PD42
USING
	( --Ok to pull invalid phones as the table indicates whether or not the phone is invalid
		SELECT DISTINCT
			PD10.DF_SPE_ACC_ID,
			PD40.DC_PHN,
			ISNULL(CONVERT(VARCHAR(10),PD40.DD_PHN_VER,101),'') AS DD_PHN_VER,
			ISNULL(PD40.DI_PHN_VLD,'') AS DI_PHN_VLD,
			ISNULL(PD40.DN_DOM_PHN_ARA,'') AS DN_DOM_PHN_ARA,
			ISNULL(PD40.DN_DOM_PHN_XCH,'') AS DN_DOM_PHN_XCH,
			ISNULL(PD40.DN_DOM_PHN_LCL,'') AS DN_DOM_PHN_LCL,
			ISNULL(PD40.DN_PHN_XTN,'') AS DN_PHN_XTN,
			ISNULL(PD40.DN_FGN_PHN_CNY,'') AS DN_FGN_PHN_CNY,
			ISNULL(PD40.DN_FGN_PHN_CT,'') AS DN_FGN_PHN_CT,
			ISNULL(PD40.DN_FGN_PHN_LCL,'') AS DN_FGN_PHN_LCL,
			ISNULL
			(
				CASE WHEN PD40.DC_ALW_ADL_PHN IN('L','P','X') THEN 'Y'
					 ELSE 'N'
				END,''
			) AS CONSENT_IND,
			ISNULL
			(
				CASE WHEN PD40.DC_ALW_ADL_PHN IN('N','P') THEN 'M'
					 WHEN PD40.DC_ALW_ADL_PHN IN('L','Q') THEN 'L'
					 WHEN PD40.DC_ALW_ADL_PHN IN('U','X') THEN 'U'
					 ELSE 'U'
				END,''
			) AS LINE_TYP
		FROM
			CDW..PD10_PRS_NME PD10
			INNER JOIN CDW..PD40_PRS_PHN PD40
				ON PD40.DF_PRS_ID = PD10.DF_PRS_ID
		WHERE
			CentralData.dbo.TRIM(PD10.DF_SPE_ACC_ID) != ''
	) NewData 
		ON NewData.DF_SPE_ACC_ID = PD42.DF_SPE_ACC_ID
		AND NewData.DC_PHN = PD42.DC_PHN
WHEN MATCHED THEN 
	UPDATE SET 
		PD42.DD_PHN_VER = NewData.DD_PHN_VER,
		PD42.DI_PHN_VLD = NewData.DI_PHN_VLD,
		PD42.DN_DOM_PHN_ARA = NewData.DN_DOM_PHN_ARA,
		PD42.DN_DOM_PHN_XCH = NewData.DN_DOM_PHN_XCH,
		PD42.DN_DOM_PHN_LCL = NewData.DN_DOM_PHN_LCL,
		PD42.DN_PHN_XTN = NewData.DN_PHN_XTN,
		PD42.DN_FGN_PHN_CNY = NewData.DN_FGN_PHN_CNY,
		PD42.DN_FGN_PHN_CT = NewData.DN_FGN_PHN_CT,
		PD42.DN_FGN_PHN_LCL = NewData.DN_FGN_PHN_LCL,
		PD42.CONSENT_IND = NewData.CONSENT_IND,
		PD42.LINE_TYP = NewData.LINE_TYP
WHEN NOT MATCHED THEN
	INSERT 
	(
		DF_SPE_ACC_ID,
		DC_PHN,
		DD_PHN_VER,
		DI_PHN_VLD,
		DN_DOM_PHN_ARA,
		DN_DOM_PHN_XCH,
		DN_DOM_PHN_LCL,
		DN_PHN_XTN,
		DN_FGN_PHN_CNY,
		DN_FGN_PHN_CT,
		DN_FGN_PHN_LCL,
		CONSENT_IND,
		LINE_TYP
	)
	VALUES 
	(
		NewData.DF_SPE_ACC_ID,
		NewData.DC_PHN,
		NewData.DD_PHN_VER,
		NewData.DI_PHN_VLD,
		NewData.DN_DOM_PHN_ARA,
		NewData.DN_DOM_PHN_XCH,
		NewData.DN_DOM_PHN_LCL,
		NewData.DN_PHN_XTN,
		NewData.DN_FGN_PHN_CNY,
		NewData.DN_FGN_PHN_CT,
		NewData.DN_FGN_PHN_LCL,
		NewData.CONSENT_IND,
		NewData.LINE_TYP
	)
WHEN NOT MATCHED BY SOURCE THEN
	DELETE
;
