/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORTZ "&RPTLIB/ULWB07.LWB07RZ";
FILENAME REPORT2 "&RPTLIB/ULWB07.LWB07R2";
LIBNAME  WORKLOCL  REMOTE  SERVER=DUSTER  SLIBREF=WORK;
RSUBMIT;
%MACRO SQLCHECK ;
  %IF  &SQLXRC NE 0  %THEN  %DO  ;
    DATA _NULL_  ;
            FILE REPORTZ NOTITLES  ;
            PUT @01 " ********************************************************************* "
              / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
              / @01 " ****  THE SAS SHOULD BE REVIEWED.                                **** "       
              / @01 " ********************************************************************* "
              / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
              / @01 " ****  &SQLXMSG   **** "
              / @01 " ********************************************************************* "
            ;
         RUN  ;
  %END  ;
%MEND  ;

PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE DEMO AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT DISTINCT	C.DF_SPE_ACC_ID	
	,TRIM(C.DM_PRS_1) || ' ' || TRIM(C.DM_PRS_LST) AS BNAME

FROM OLWHRM1.PD10_PRS_NME C
INNER JOIN OLWHRM1.LN10_LON B
	ON C.DF_PRS_ID = B.BF_SSN
INNER JOIN OLWHRM1.LN60_BR_FOR_APV D
	ON B.BF_SSN = D.BF_SSN
	AND B.LN_SEQ = D.LN_SEQ
INNER JOIN OLWHRM1.FB10_BR_FOR_REQ A
	ON D.BF_SSN = A.BF_SSN
	AND D.LF_FOR_CTL_NUM = A.LF_FOR_CTL_NUM
WHERE B.LA_CUR_PRI > 0
	AND B.LC_STA_LON10 = 'R'
	AND B.IC_LON_PGM = 'TILP'
	AND B.LC_STP_PUR != 'Y'
	AND A.LC_FOR_STA = 'A'
	AND D.LD_FOR_BEG > B.LD_LON_1_DSB
	AND D.LC_FOR_RSP != '003'
/*	and c.df_spe_acc_id In ('3945944743')*/
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;

/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>> ;  ** INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK;*/
/*QUIT;*/

ENDRSUBMIT;
DATA DEMO;
	SET WORKLOCL.DEMO;
RUN;
PROC SORT DATA=DEMO;
	BY DF_SPE_ACC_ID;
RUN;
PROC PRINTTO PRINT=REPORT2 NEW;
RUN;

/*FOR PORTRAIT REPORTS;*/
OPTIONS ORIENTATION = PORTRAIT;
OPTIONS PS=52 LS=96;
TITLE 'TILP Loans With Forbearance';

PROC CONTENTS DATA=DEMO OUT=EMPTYSET NOPRINT;
DATA _NULL_;
SET EMPTYSET;
FILE PRINT;
IF  NOBS=0 AND _N_ =1 THEN DO;
	PUT // 132*'-';
	PUT      //////
		@51 '**** NO OBSERVATIONS FOUND ****';
	PUT //////
		@57 '-- END OF REPORT --';
	PUT //////////////
		@46 "JOB = UTLWB07  	 REPORT = ULWB07.LWB07R2";
	END;
RETURN;
RUN;

PROC PRINT NOOBS SPLIT='/' DATA=DEMO WIDTH=UNIFORM WIDTH=MIN LABEL;
VAR DF_SPE_ACC_ID BNAME;
LABEL DF_SPE_ACC_ID = 'ACCOUNT NUMBER'
	BNAME = 'BORROWER NAME';
RUN;

PROC PRINTTO;
RUN;
