/*UTLWQ06 - FISCAL YEAR OUTSTANDING GROSS GUARANTY VOLUME BY MONTH*/

/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;
%LET RPTLIB = %SYSGET(reportdir);
FILENAME REPORT2 "&RPTLIB/ULWQ06.LWQ06R2";*/

libname  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=work  ;
RSUBMIT;
OPTIONS SYMBOLGEN;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE GRSOUT AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT COUNT(B.AF_APL_ID||B.AF_APL_ID_SFX) AS LON_CT
	,COUNT(DISTINCT A.DF_PRS_ID_BR) AS BWR_CT
	,SUM(B.AA_GTE_LON_AMT) AS GRS_GTY

FROM  OLWHRM1.GA01_APP A 
INNER JOIN OLWHRM1.GA10_LON_APP B
	ON A.AF_APL_ID = B.AF_APL_ID
INNER JOIN OLWHRM1.GA14_LON_STA C
	ON B.AF_APL_ID = C.AF_APL_ID
	AND B.AF_APL_ID_SFX = C.AF_APL_ID_SFX
LEFT OUTER JOIN OLWHRM1.DC01_LON_CLM_INF D
	ON B.AF_APL_ID = D.AF_APL_ID
	AND B.AF_APL_ID_SFX = D.AF_APL_ID_SFX
	AND D.LC_STA_DC10 = '03'

WHERE B.AC_PRC_STA = 'A'
AND C.AC_STA_GA14 = 'A'
AND ((C.AC_LON_STA_TYP <> 'CP'
	AND B.AA_GTE_LON_AMT > B.AA_TOT_AMT_PD + B.AA_TOT_RFD + COALESCE(B.AA_TOT_CAN,0))
	OR 
	(C.AC_LON_STA_TYP = 'CP'
	AND D.LC_STA_DC10 = '03'
	AND (D.LD_CLM_ASN_DOE IS NULL
		OR D.LD_CLM_ASN_DOE IN ('05/31/2001','06/01/2001'))))
);
DISCONNECT FROM DB2;
endrsubmit  ;

DATA GRSOUT; 
SET WORKLOCL.GRSOUT; 
RUN;

DATA _NULL_;
CALL SYMPUT('RUNDATE',PUT(INTNX('DAY',TODAY(),0,'beginning'), MMDDYY10.));
RUN;

/*PROC PRINTTO PRINT=REPORT2;
RUN;*/
OPTIONS CENTER NODATE NUMBER PAGENO=1 LS=126;
PROC REPORT DATA=GRSOUT NOWD SPACING=1 HEADSKIP SPLIT='/';
TITLE "UHEAA OUTSTANDING GROSS GUARANTY VOLUME";
TITLE2 "RUN DATE: &RUNDATE";
FOOTNOTE  'JOB = UTLWQ06     REPORT = ULWQ06.LWQ06R2';
COLUMN GRS_GTY LON_CT BWR_CT;
DEFINE GRS_GTY / ANALYSIS FORMAT=DOLLAR18.2 "GROSS GUARANTY AMOUNT" WIDTH=20;
DEFINE LON_CT / ANALYSIS FORMAT=COMMA7. "NUMBER OF/OUTSTANDING LOANS" WIDTH=20;
DEFINE BWR_CT / ANALYSIS FORMAT=COMMA7. "BORROWERS WITH/OUTSTANDING LOANS" WIDTH=20;
RUN;

/* *TEST STUFF;
libname  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=work  ;
RSUBMIT;
OPTIONS SYMBOLGEN;
PROC SQL ;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE GRSOUTTEST AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT B.AF_APL_ID||B.AF_APL_ID_SFX AS LON_CT
	,A.DF_PRS_ID_BR
	,B.AA_GTE_LON_AMT
	,D.LC_STA_DC10 
	,D.LD_CLM_ASN_DOE

FROM  OLWHRM1.GA01_APP A 
INNER JOIN OLWHRM1.GA10_LON_APP B
	ON A.AF_APL_ID = B.AF_APL_ID
INNER JOIN OLWHRM1.GA14_LON_STA C
	ON B.AF_APL_ID = C.AF_APL_ID
	AND B.AF_APL_ID_SFX = C.AF_APL_ID_SFX
LEFT OUTER JOIN OLWHRM1.DC01_LON_CLM_INF D
	ON B.AF_APL_ID = D.AF_APL_ID
	AND B.AF_APL_ID_SFX = D.AF_APL_ID_SFX
	AND D.LC_STA_DC10 = '03'

WHERE B.AC_PRC_STA = 'A'
AND C.AC_STA_GA14 = 'A'
AND ((C.AC_LON_STA_TYP <> 'CP'
	AND B.AA_GTE_LON_AMT > B.AA_TOT_AMT_PD + B.AA_TOT_RFD + COALESCE(B.AA_TOT_CAN,0))
	OR 
	(C.AC_LON_STA_TYP = 'CP'
	AND D.LC_STA_DC10 = '03'
	AND (D.LD_CLM_ASN_DOE IS NULL
		OR D.LD_CLM_ASN_DOE IN ('05/31/2001','06/01/2001'))))
ORDER BY A.DF_PRS_ID_BR
);
DISCONNECT FROM DB2;
endrsubmit  ;

DATA GRSOUTTEST; 
SET WORKLOCL.GRSOUTTEST (OBS=10000); 
RUN;

PROC EXPORT DATA= GRSOUTTEST 
            OUTFILE= "T:\SAS\GRSOUTTEST.xls" 
            DBMS=EXCEL2000 REPLACE;
RUN;

*/
