*------------------------------------------------------------------------------*
| UTLWO71 - ONELINK CLAIM PAID AND LR POSTED WITHIN 30 DAYS OF CLAIM PAID DATE |
*------------------------------------------------------------------------------*;
/*LIBNAME DLGSUTWH DB2 DATABASE=DLGSUTWH OWNER=OLWHRM1;*/
/*%LET RPTLIB = %SYSGET(reportdir);*/
%LET RPTLIB = T:\SAS;
FILENAME REPORT2 "&RPTLIB/ULWO71.LWO71R2";
FILENAME REPORTZ "&RPTLIB/ULWO71.LWO71RZ";
DATA _NULL_;
	CALL SYMPUT('DAYS_AGO_30',"'"||PUT(INTNX('DAY',TODAY(),-30,'BEGINNING'), MMDDYYD10.)||"'");
	CALL SYMPUT('RUNDATE',PUT(INTNX('DAY',TODAY(),0,'beginning'), MMDDYY10.));
	CALL SYMPUT('RUNTIME',PUT(TIME(), TIME.));
RUN;
%SYSLPUT DAYS_AGO_30 = &DAYS_AGO_30;
LIBNAME  WORKLOCL  REMOTE  SERVER=CYPRUS  SLIBREF=WORK;
RSUBMIT;
%MACRO SQLCHECK (SQLRPT= );
%IF &SQLXRC NE 0 %THEN %DO;
	DATA _NULL_;
    FILE REPORTZ NOTITLES;
    PUT @01 " ********************************************************************* "
      / @01 " ****  THE SQL CODE ABOVE HAS EXPERIENCED AN ERROR.               **** "
      / @01 " ****  THE SAS LOG IN &SQLRPT SHOULD BE REVIEWED.          **** "       
      / @01 " ********************************************************************* "
      / @01 " ****  THE SQL ERROR CODE IS  &SQLXRC  AND THE SQL ERROR MESSAGE  **** "
      / @01 " ****  &SQLXMSG   **** "
      / @01 " ********************************************************************* ";
	RUN;
%END;
%MEND;
PROC SQL;
CONNECT TO DB2 (DATABASE=DLGSUTWH);
CREATE TABLE CPW30D AS
SELECT *
FROM CONNECTION TO DB2 (
SELECT C.DF_SPE_ACC_ID
	,A.AF_APL_ID||A.AF_APL_ID_SFX AS CLUID
	,A.LD_LDR_POF
	,B.LD_TRX_EFF
	,B.LA_TRX
	,B.LC_TRX_TYP
FROM OLWHRM1.DC01_LON_CLM_INF A
INNER JOIN OLWHRM1.DC11_LON_FAT B
	ON A.AF_APL_ID = B.AF_APL_ID
	AND A.AF_APL_ID_SFX = B.AF_APL_ID_SFX
	AND A.LF_CRT_DTS_DC10 = B.LF_CRT_DTS_DC10
INNER JOIN OLWHRM1.PD01_PDM_INF C
	ON A.BF_SSN = C.DF_PRS_ID
WHERE A.LC_STA_DC10 = '03'
	AND B.LC_TRX_TYP IN 
	(
		'LR','BR'
	)
	AND DAYS(B.LD_TRX_EFF) BETWEEN DAYS(A.LD_LDR_POF) - 30 AND DAYS(A.LD_LDR_POF) 
	AND B.LD_TRX_EFF > &DAYS_AGO_30
FOR READ ONLY WITH UR
);
DISCONNECT FROM DB2;
/*%PUT  SQLXRC= >>> &SQLXRC <<< ||| SQLXMSG= >>> &SQLXMSG >>>  ;  * INCLUDES ERROR MESSAGES TO SAS LOG  ;*/
/*%SQLCHECK (SQLRPT=ULWO71.LWO71RZ);*/
/*QUIT;*/
ENDRSUBMIT;

DATA CPW30D ;
SET WORKLOCL.CPW30D;
RUN;

PROC SORT DATA = CPW30D; BY DF_SPE_ACC_ID; RUN;

PROC PRINTTO PRINT=REPORT2 NEW;
RUN;
OPTIONS ORIENTATION = LANDSCAPE;
OPTIONS PS=39 LS=127 NODATE CENTER PAGENO=1;
TITLE 'LR PAYMENT LESS THAN 30 DAYS SINCE CLAIM';
TITLE2	"&RUNDATE - &RUNTIME";
FOOTNOTE   'JOB = UTLWO71  	 REPORT = ULWO71.LWO71R2';
PROC CONTENTS DATA=CPW30D OUT=EMPTYSET NOPRINT;
DATA _NULL_;
SET EMPTYSET;
FILE PRINT;
IF  NOBS=0 AND _N_ =1 THEN DO;
	PUT // 126*'-';
	PUT      //////
		@51 '**** NO OBSERVATIONS FOUND ****';
	PUT //////
		@57 '-- END OF REPORT --';
	PUT //////////////
		@46 "JOB = UTLWO71  	 REPORT = ULWO71.LWO71R2";
	END;
RETURN;
RUN;
PROC PRINT NOOBS SPLIT='/' DATA=CPW30D WIDTH=UNIFORM WIDTH=MIN LABEL;
FORMAT LD_LDR_POF LD_TRX_EFF MMDDYY10. LA_TRX 10.2;
VAR DF_SPE_ACC_ID CLUID LD_LDR_POF LD_TRX_EFF LA_TRX LC_TRX_TYP;
LABEL DF_SPE_ACC_ID = 'ACCOUNT #'
	CLUID = 'UNIQUE ID'
	LD_LDR_POF = 'CLAIM PAY OFF DATE' 
	LD_TRX_EFF = 'PAYMENT DATE' 
	LA_TRX = 'AMOUNT OF PAYMENT' 
	LC_TRX_TYP = 'TRANSACTION TYPE'
;
RUN;
PROC PRINTTO;
RUN;
