CREATE PROCEDURE [dashcache].[RPMTDISC_CS]
AS

SELECT
	C.MissingCount
FROM
	OPENQUERY
	(
		LEGEND,
		'
			SELECT DISTINCT
				COUNT(RS10.BF_SSN) "MissingCount"
			FROM 
				PKUB.RS10_BR_RPD RS10
				INNER JOIN PKUB.PD30_PRS_ADR PD30 ON PD30.DF_PRS_ID = RS10.BF_SSN -- must have an address
				INNER JOIN PKUB.LN65_LON_RPS LN65 ON RS10.BF_SSN = LN65.BF_SSN AND RS10.LN_RPS_SEQ = LN65.LN_RPS_SEQ
				INNER JOIN PKUB.LN10_LON LN10 ON LN65.BF_SSN = LN10.BF_SSN AND LN65.LN_SEQ = LN10.LN_SEQ
				INNER JOIN PKUB.LN66_LON_RPS_SPF LN66 ON LN65.BF_SSN = LN66.BF_SSN AND LN65.LN_SEQ = LN66.LN_SEQ AND LN65.LN_RPS_SEQ = LN66.LN_RPS_SEQ
				LEFT JOIN PKUB.DW01_DW_CLC_CLU DW01 ON LN65.BF_SSN = DW01.BF_SSN AND LN65.LN_SEQ = DW01.LN_SEQ
				LEFT JOIN
				(
					SELECT
						LN50.BF_SSN,
						LN50.LN_SEQ,
						LN50.LD_DFR_END
					FROM
						PKUB.DF10_BR_DFR_REQ DF10
						INNER JOIN PKUB.LN50_BR_DFR_APV LN50 ON DF10.BF_SSN = LN50.BF_SSN AND DF10.LF_DFR_CTL_NUM = LN50.LF_DFR_CTL_NUM
					WHERE
						DF10.LC_STA_DFR10 = ''A''
						AND 
						LN50.LC_STA_LON50 = ''A''
						AND 
						DF10.LC_DFR_TYP = ''46''
						AND 
						LN50.LD_DFR_BEG < CURRENT DATE
						AND 
						LN50.LD_DFR_END > CURRENT DATE
						AND
						LN50.LD_DFR_APL < CURRENT DATE - 2 DAYS --give the process a couple of days to process new updates
				) DEFR ON LN10.BF_SSN = DEFR.BF_SSN	AND LN10.LN_SEQ = DEFR.LN_SEQ
				LEFT JOIN
				(
					SELECT
						BF_SSN,
						MAX(LD_ATY_RSP) AS LD_ATY_RSP
					FROM
						PKUB.AY10_BR_LON_ATY
					WHERE
						PF_REQ_ACT = ''MSRPD''
					GROUP BY 
						BF_SSN
				) AY10 ON RS10.BF_SSN = AY10.BF_SSN
				--LEFT JOIN PKUB.LN72_INT_RTE_HST LN72 ON LN10.BF_SSN = LN72.BF_SSN AND LN10.LN_SEQ = LN72.LN_SEQ	AND CURRENT DATE BETWEEN LN72.LD_ITR_EFF_BEG AND LN72.LD_ITR_EFF_END AND LN72.LC_STA_LON72 = ''A''
			WHERE 
				RS10.LC_STA_RPST10 = ''A''
				AND
				RS10.LD_SNT_RPD_DIS < CURRENT DATE - 5 DAYS
				AND
				PD30.DI_VLD_ADR = ''Y''
				AND 
				(  -- account for redisclosures
					AY10.LD_ATY_RSP IS NULL
					OR
					DAYS(RS10.LD_SNT_RPD_DIS) > DAYS(AY10.LD_ATY_RSP)
				)
				AND 
				LN65.LC_STA_LON65 = ''A''
				AND 
				(
					DW01.WC_DW_LON_STA = ''01'' 
					OR 
					DEFR.BF_SSN IS NOT NULL 
					OR 
					LN10.LD_LON_ACL_ADD > ''12/01/2014''
				)
		'
	) C


RETURN 0