CREATE TABLE [dbo].[LN54_BenefitProgram]
(
	[DF_SPE_ACC_ID] VARCHAR(10) NOT NULL , 
    [LN_SEQ] INT NOT NULL, 
    [PM_BBS_PGM] VARCHAR(3) NOT NULL, 
    [PN_BBS_PGM_SEQ] INT NOT NULL, 
    [LN_LON_BBS_PGM_SEQ] INT NOT NULL, 
    [LD_EFF_BEG_LN54] VARCHAR(10) NULL, 
    [LI_BBS_ITD_LTR_SNT] VARCHAR NULL, 
    [LN_BBS_STS_PCV_PAY] NUMERIC(3) NULL, 
    [LC_BBS_REB_MTD] VARCHAR NULL, 
    [LC_STA_LN54] VARCHAR NULL, 
    [LD_STA_LN54] VARCHAR(10) NULL, 
    [LC_BBS_DSQ_REA] VARCHAR(2) NULL, 
    [LD_BBS_DSQ] VARCHAR(10) NULL, 
    [LC_BBS_ELG] VARCHAR NULL, 
    PRIMARY KEY ([DF_SPE_ACC_ID], [LN_SEQ], [PM_BBS_PGM], [PN_BBS_PGM_SEQ], [LN_LON_BBS_PGM_SEQ])
)
