CREATE TABLE [dbo].[RS05_IDR_Repayment]
(
    [DF_SPE_ACC_ID] VARCHAR(10) NOT NULL , 
	[BD_CRT_RS05] DATETIME NOT NULL, 
	[BN_IBR_SEQ] INT NOT NULL, 
	[BF_CRY_YR]  VARCHAR(4) NULL,
	[BC_ST_IBR] VARCHAR(2) NULL,
	[BC_STA_RS05] VARCHAR(1) NULL,
	[BA_AGI] NUMERIC(12, 2) NULL, 
	[BN_MEM_HSE_HLD] INT NULL, 
	[BA_PMN_STD_TOT_PAY] NUMERIC(12, 2) NULL, 
	[BC_IBR_INF_SRC_VER] VARCHAR(3) NULL, 
	[BF_SSN_SPO] VARCHAR(9) NULL, 
	[BC_IRS_TAX_FIL_STA] VARCHAR(1) NULL, 
	[BI_JNT_BR_SPO_RPY] VARCHAR(1) NULL, 
	[BD_ANV_QLF_IBR]  DATETIME NULL, 
    CONSTRAINT [PK_RS05_IDR_Repayment] PRIMARY KEY ([DF_SPE_ACC_ID], [BD_CRT_RS05], [BN_IBR_SEQ])
)
