CREATE TABLE [dbo].[ZDEL_LN15_DISBURSEMENT] (
    [DF_SPE_ACC_ID] VARCHAR (10) NOT NULL,
    [LN_BR_DSB_SEQ] INT          NOT NULL,
    CONSTRAINT [PK_ZDEL_LN15_DISBURSEMENT] PRIMARY KEY CLUSTERED ([DF_SPE_ACC_ID] ASC, [LN_BR_DSB_SEQ] ASC)
);

