CREATE TABLE [dbo].[ZDEL_DF10_DefermentLetter]
(
	[DF_SPE_ACC_ID] VARCHAR(10) NOT NULL , 
    [LN_SEQ] INT NOT NULL, 
    [LF_DFR_CTL_NUM] VARCHAR(3) NOT NULL, 
    [LN_DFR_OCC_SEQ] INT NOT NULL, 
    PRIMARY KEY ([DF_SPE_ACC_ID], [LN_DFR_OCC_SEQ], [LN_SEQ], [LF_DFR_CTL_NUM])
)
