CREATE TABLE [dbo].[ZDEL_WK1J_LON_SLE_PLR]
(
	[IF_LON_SLE] VARCHAR(7) NOT NULL, 
	[ID_LON_SLE_LST_PLR] DATETIME NOT NULL, 
	[IT_SLE_LST_PLR_Varchar] VARCHAR(8) NOT NULL, 
	[BF_SSN] VARCHAR(9) NOT NULL, 
	[LN_SEQ] SMALLINT NOT NULL, 
)
