CREATE TABLE [dbo].[LN10_LON](
	[BF_SSN] [varchar](9) NOT NULL,
	[LN_SEQ] [smallint] NOT NULL,
	[LC_STA_LON10] [char](1) NULL,
	[LI_FGV_PGM] [char](1) NULL,
	[LF_LON_SLE_PND] [varchar](7) NULL,
	[LA_CUR_PRI] [numeric](8, 2) NULL,
	[LI_ELG_CPN_BOK] [char](1) NULL,
	[LA_LON_AMT_GTR] [numeric](8, 2) NULL,
	[LD_LON_GTR] [date] NULL,
	[LD_PIF_PNT_RTN] [date] NULL,
	[LD_PNT_SIG] [date] NULL,
	[LC_INT_BIL_OPT] [char](1) NULL,
	[LI_CAP_ALW] [char](1) NULL,
	[LD_END_GRC_PRD] [date] NULL,
	[LN_MTH_GRC_PRD_DSC] [numeric](3, 0) NULL,
	[LA_R78_INT_PD] [numeric](7, 2) NULL,
	[LA_R78_INT_MAX] [numeric](7, 2) NULL,
	[LD_CAP_LST_PIO_CVN] [date] NULL,
	[LD_TRM_END] [date] NULL,
	[LD_TRM_BEG] [date] NULL,
	[LI_GTR_NAT] [char](1) NULL,
	[LF_GTR_RFR] [varchar](12) NULL,
	[LI_ELG_SPA] [char](1) NULL,
	[LD_GTE_LOS] [date] NULL,
	[LA_SCL_CLS] [numeric](8, 2) NULL,
	[LA_CUR_ILG] [numeric](8, 2) NULL,
	[LA_ILG] [numeric](8, 2) NULL,
	[LD_PIF_RPT] [date] NULL,
	[LA_NSI_OTS] [numeric](7, 2) NULL,
	[LD_NSI_ACR_THU] [date] NULL,
	[LD_STA_LON10] [date] NULL,
	[LD_LON_ACL_ADD] [date] NULL,
	[LD_LON_EFF_ADD] [date] NULL,
	[LF_DOE_SCL_ORG] [varchar](8) NULL,
	[LC_PCV_DIS_STA] [char](1) NULL,
	[LC_RPR_TYP] [char](1) NULL,
	[LF_RGL_CAT_LP19] [varchar](7) NULL,
	[LF_RGL_CAT_LP18] [varchar](7) NULL,
	[LF_RGL_CAT_LP17] [varchar](7) NULL,
	[LF_RGL_CAT_LP13] [varchar](7) NULL,
	[LF_RGL_CAT_LP12] [varchar](7) NULL,
	[LF_RGL_CAT_LP11] [varchar](7) NULL,
	[LF_RGL_CAT_LP10] [varchar](7) NULL,
	[LF_RGL_CAT_LP08] [varchar](7) NULL,
	[LF_RGL_CAT_LP07] [varchar](7) NULL,
	[LF_RGL_CAT_LP06] [varchar](7) NULL,
	[LF_RGL_CAT_LP05] [varchar](7) NULL,
	[LF_RGL_CAT_LP04] [varchar](7) NULL,
	[LF_RGL_CAT_LP03] [varchar](7) NULL,
	[LF_RGL_CAT_LP02] [varchar](7) NULL,
	[LF_RGL_CAT_LP01] [varchar](7) NULL,
	[LD_SCL_CLS_NTF] [date] NULL,
	[LD_ILG_NTF] [date] NULL,
	[LF_LON_CUR_OWN] [varchar](8) NULL,
	[LF_LST_DTS_LN10] [datetime2](7) NULL,
	[LC_STA_NEW_BR] [varchar](3) NULL,
	[LC_SCY_PGA] [varchar](2) NULL,
	[LD_SIN_LST_PD_PCV] [date] NULL,
	[LD_SIN_ACR_THU_PCV] [date] NULL,
	[LA_SIN_OTS_PCV] [numeric](7, 2) NULL,
	[IC_LON_PGM] [varchar](6) NULL,
	[PF_MAJ_BCH] [varchar](10) NULL,
	[PF_MNR_BCH] [numeric](5, 0) NULL,
	[IF_DOE_LDR] [varchar](8) NULL,
	[IF_GTR] [varchar](6) NULL,
	[LF_STU_SSN] [varchar](9) NULL,
	[LD_LON_1_DSB] [date] NULL,
	[LC_ACA_GDE_LEV] [varchar](2) NULL,
	[LD_NEW_SYS_CVN] [date] NULL,
	[LC_SCY_PGA_PGM_YR] [char](1) NULL,
	[IC_HSP_CSE] [varchar](3) NULL,
	[LI_TL4_793_XCL_CON] [char](1) NULL,
	[LI_DFR_REQ_ON_APL] [char](1) NULL,
	[LI_LN_PT_COM_APL] [char](1) NULL,
	[LN_SEQ_RPR] [smallint] NULL,
	[LR_WIR_CON_LON] [numeric](5, 3) NULL,
	[LR_INT_RDC_PGM_DSU] [numeric](5, 3) NULL,
	[LI_1_TME_BR] [char](1) NULL,
	[BF_SSN_RPR] [varchar](9) NULL,
	[LC_ELG_RDC_PGM] [char](1) NULL,
	[LD_ELG_RDC_PGM] [date] NULL,
	[LC_RPD_SLE] [char](1) NULL,
	[LR_ITR_ORG] [numeric](5, 3) NULL,
	[LC_ITR_TYP_ORG] [varchar](2) NULL,
	[LC_RDC_PGM] [varchar](2) NULL,
	[LC_TIR_GRP] [char](1) NULL,
	[LD_SER_RSB_BEG] [date] NULL,
	[LC_EFT_RDC] [char](1) NULL,
	[LD_LTS_STS_BIL] [date] NULL,
	[IF_TIR_PCE] [varchar](3) NULL,
	[LF_RGL_CAT_LP20] [varchar](7) NULL,
	[LN_RDC_PGM_PAY_PCV] [numeric](3, 0) NULL,
	[LC_REA_PIF_PCV] [char](1) NULL,
	[LD_FAT_PIF_TOL_PCV] [date] NULL,
	[LA_FAT_PIF_TOL_PCV] [numeric](9, 2) NULL,
	[LI_RTE_RDC_ELG] [char](1) NULL,
	[LD_LTE_FEE_ELG] [date] NULL,
	[LA_LTE_FEE_OTS] [numeric](7, 2) NULL,
	[LD_LON_LTE_FEE_WAV] [date] NULL,
	[LC_CUR_RDC_PGM_NME] [varchar](3) NULL,
	[LI_RIR_SCY_ELG] [char](1) NULL,
	[LD_END_RIR_DSQ_OVR] [date] NULL,
	[LF_LON_ALT] [varchar](17) NULL,
	[LN_LON_ALT_SEQ] [smallint] NULL,
	[LI_LDR_LST_RST_DSB] [char](1) NULL,
	[LC_ST_BR_RSD_APL] [varchar](2) NULL,
	[LI_PIF_RPT_REQ] [char](1) NULL,
	[LD_AMR_BEG] [date] NULL,
	[LD_ORG_XPC_GRD] [date] NULL,
	[LD_CON_LST_RPY_BEG] [date] NULL,
	[LN_CON_MTH_DFR_FOR] [numeric](4, 0) NULL,
	[LD_LON_APL_RCV] [date] NULL,
	[LR_SCL_SUB] [numeric](6, 3) NULL,
	[LI_BLL_PAY_SES_OVR] [char](1) NULL,
	[LC_MPN_TYP] [char](1) NULL,
	[LD_MPN_EXP] [date] NULL,
	[LC_MPN_SRL_LON] [char](1) NULL,
	[LC_MPN_REV_REA] [varchar](2) NULL,
	[LF_ORG_RGN] [varchar](8) NULL,
	[LC_CAM_LON_STA] [varchar](2) NULL,
	[LD_DFR_FOR_END] [date] NULL,
	[LC_DFR_FOR_TYP] [varchar](2) NULL,
	[LF_CAM_DFR_SCL_ENR] [varchar](8) NULL,
	[LD_DFR_FOR_BEG] [date] NULL,
	[LD_CAM_DFR_INF_CER] [date] NULL,
	[LI_BR_DET_RPD_XTN] [char](1) NULL,
	[DD_DTH_VER] [date] NULL,
	[DD_DSA_VER] [date] NULL,
	[LI_CON_PAY_STP_PUR] [char](1) NULL,
	[LD_FSE_CER_NTF] [date] NULL,
	[LA_TOT_EDU_DET] [numeric](10, 2) NULL,
	[LI_LDR_BG_APL] [char](1) NULL,
	[LD_RIR_CSC_BIL_STS] [date] NULL,
	[LI_ESG] [char](1) NULL,
	[LC_RIR_DSQ_REA] [varchar](2) NULL,
	[LF_MN_MST_NTE] [varchar](11) NULL,
	[LN_MN_MST_NTE_SEQ] [smallint] NULL,
	[LC_LON_SND_CHC] [char](1) NULL,
	[LC_SST_LON10] [char](1) NULL,
	[LF_RGL_CAT_LP09] [varchar](7) NULL,
	[LI_MN_PSD_BS] [char](1) NULL,
	[LF_CRD_RTE_SRE] [varchar](4) NULL,
	[LF_ESG_SRC] [varchar](9) NULL,
	[PC_PNT_YR] [varchar](7) NULL,
	[LF_OWN_BND_ISS_TE1] [varchar](8) NULL,
	[LF_OWN_BND_ISS_TE2] [varchar](8) NULL,
	[LF_OWN_BND_ISS_TE3] [varchar](8) NULL,
	[LD_MPN_STM_SNT] [date] NULL,
	[LI_MNT_BIL_RCP] [char](1) NULL,
	[LX_BS_POI] [varchar](4) NULL,
	[LA_BS_POI] [numeric](6, 4) NULL,
	[LA_INT_FEE_URP_IRS] [numeric](8, 2) NULL,
	[LC_BR_ALW_SCL_DFR] [char](1) NULL,
	[LD_BR_ALW_SCL_DFR] [date] NULL,
	[LC_LON_DFR_SUB_TYP] [varchar](2) NULL,
	[LD_FAT_PRI_BAL_ZRO] [date] NULL,
	[LC_ST_SCL_ATD_APL] [varchar](2) NULL,
	[LD_EFT_DSQ_NSF_LMT] [date] NULL,
	[LD_CLM_PD] [date] NULL,
	[LC_STP_PUR] [char](1) NULL,
	[LD_CON_PAY_EFF] [date] NULL,
	[LD_CON_PAY_APL] [date] NULL,
	[LC_ESG] [char](1) NULL,
	[LC_LON_RPE_CVN_REA] [char](1) NULL,
	[LC_UDL_DSB_COF] [char](1) NULL,
	[LI_BR_LT_HT] [char](1) NULL,
	[LI_ALL_PAY_FLG_SPS] [char](1) NULL,
	[LN_MFY_GRS_PAY] [numeric](2, 0) NULL,
	[LC_ESP_RPD_OPT_SEL] [varchar](2) NULL,
	[LC_ELG_95_SPA_BIL] [char](1) NULL,
	[LC_SGM_COS_PRC] [varchar](2) NULL,
	[LD_GTR_DR_DCH_CER] [date] NULL,
	[LD_RPD_ELY_CL_BEG] [date] NULL,
	[LD_RPD_ELY_CL_END] [date] NULL,
	[LF_GTR_RFR_XTN] [varchar](23) NULL,
	[LA_MSC_FEE_OTS] [numeric](12, 2) NULL,
	[LA_MSC_FEE_PCV_OTS] [numeric](12, 2) NULL,
	[LF_LON_GRP_WI_BR] [smallint] NULL,
	[LC_TL4_IBR_ELG] [char](1) NULL,
	[LD_LON_IBR_ENT] [date] NULL,
	[LC_LON_IBR_RPY_TYP] [char](1) NULL,
	[LI_BYP_COL_OUT_SRC] [char](1) NULL,
	[LI_BR_GRP_RLP] [char](1) NULL,
	[LI_OO_PST_ENR_DFR] [char](1) NULL,
	[LD_OO_PST_ENR_DFR] [date] NULL,
	[LF_FED_CLC_RSK] [varchar](6) NULL,
	[LF_FED_FFY_1_DSB] [varchar](4) NULL,
	[LF_PRV_GTR] [varchar](6) NULL,
	[LC_FED_PGM_YR] [varchar](3) NULL,
	[LA_INT_RCV_GOV] [numeric](12, 2) NULL,
	[LC_WOF_WUP_REA] [char](1) NULL,
	[LC_VRS_ALT_APL] [varchar](4) NULL,
	[LF_LON_DCV_CLI] [varchar](2) NULL,
	[LN_LON_SEQ_DCV_CLI] [smallint] NULL,
	[LI_EDS_BKR_STP_PUR] [char](1) NULL,
	[LF_EDS] [varchar](9) NULL,
	[LD_EFF_LBR_RTE] [date] NULL,
	[LA_STD_STD_PAY] [numeric](12, 2) NULL,
	[LI_FRC_IBR] [char](1) NULL,
	[LC_STP_PUR_REA] [char](1) NULL,
	[LD_IDR_ELG_CHG] [date] NULL,
	[LC_IDR_ELG_CRI] [varchar](2) NULL,
	[LA_NSI_OTS_CAP] [numeric](12, 2) NULL,
	[LA_NSI_OTS_NCA] [numeric](12, 2) NULL,
	[LA_NSI_OTS_NAM] [numeric](12, 2) NULL,
	[LC_INT_BKT_CUP_STA] [char](1) NULL,
	[BF_ORG_SSN] [varchar](9) NULL,
	[LC_CRB_RPT_LON_MCH] [varchar](2) NULL,
 CONSTRAINT [PK_LN10_LON] PRIMARY KEY CLUSTERED 
(
	[BF_SSN] ASC,
	[LN_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

