CREATE TABLE [dbo].[LT20_LTR_REQ_PRC_Coborrower](
	[DF_SPE_ACC_ID] [char](10) NOT NULL,
	[Borrower_DF_SPE_ACC_ID] [char](10) NOT NULL,
	[RM_APL_PGM_PRC] [varchar](8) NOT NULL,
	[RT_RUN_SRT_DTS_PRC] [datetime] NOT NULL,
	[RN_SEQ_LTR_CRT_PRC] [int] NOT NULL,
	[RN_SEQ_REC_PRC] [int] NOT NULL,
	[RM_DSC_LTR_PRC] [varchar](10) NOT NULL,
	[RC_TYP_SBJ_PRC] [char](1) NOT NULL,
	[RF_SBJ_PRC] [char](9) NOT NULL,
	[RN_ENT_REQ_PRC] [numeric](3, 0) NOT NULL,
	[RN_ATY_SEQ_PRC] [int] NOT NULL,
	[RI_REC_PRC] [char](1) NOT NULL,
	[RX_REQ_ARA_1_PRC] [varchar](250) NOT NULL,
	[RX_REQ_ARA_2_PRC] [varchar](250) NOT NULL,
	[RX_REQ_ARA_3_PRC] [varchar](250) NOT NULL,
	[RX_REQ_ARA_4_PRC] [varchar](250) NOT NULL,
	[RX_REQ_ARA_5_PRC] [varchar](250) NOT NULL,
	[RX_REQ_ARA_6_PRC] [varchar](250) NOT NULL,
	[RI_LTR_REQ_DEL_PRC] [char](1) NOT NULL,
	[RC_LTR_REQ_SRC_PRC] [char](1) NOT NULL,
	[RI_PRV_RUN_ERR_PRC] [char](1) NOT NULL,
	[RF_LST_DTS_LT20] [datetime] NOT NULL,
	[RF_COR_DOC_PRC] [varchar](17) NOT NULL,
	[RX_REQ_ARA_16_PRC] [varchar](210) NOT NULL,
	[RX_REQ_ARA_15_PRC] [varchar](250) NOT NULL,
	[RX_REQ_ARA_14_PRC] [varchar](250) NOT NULL,
	[RX_REQ_ARA_13_PRC] [varchar](250) NOT NULL,
	[RX_REQ_ARA_12_PRC] [varchar](250) NOT NULL,
	[RX_REQ_ARA_11_PRC] [varchar](250) NOT NULL,
	[RX_REQ_ARA_10_PRC] [varchar](250) NOT NULL,
	[RX_REQ_ARA_9_PRC] [varchar](250) NOT NULL,
	[RX_REQ_ARA_8_PRC] [varchar](250) NOT NULL,
	[RX_REQ_ARA_7_PRC] [varchar](250) NOT NULL,
	[RI_LTR_OPT_ENC_PRC] [char](1) NOT NULL,
	[RN_ARR_PAR_PRC] [smallint] NULL,
	[OnEcorr] [bit] NOT NULL,
	[PrintedAt] [datetime] NULL,
	[EcorrDocumentCreatedAt] [datetime] NULL,
	[InactivatedAt] [datetime] NULL,
	[SystemLetterExclusionReasonId] [int] NULL,
	[CreatedAt] [datetime] NULL
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[LT20_LTR_REQ_PRC_Coborrower] ADD  CONSTRAINT [DF_LT20_LTR_REQ_PRC_Coborrower_CreatedAt]  DEFAULT (getdate()) FOR [CreatedAt]
GO